### ISSUE TITLE
FTPS using libcurl 8.9.1 fails with CURLE_OPERATION_TIMEDOUT

### ISSUE THREAD

**Issue by Valery-OT** [curl/curl#14800] opened 2024-09-05 16:44 UTC
### I did this

FTPS file transfer C++ implementation using libcurl working with libcurl versions up to 8.7.1 failed with versions 8.9.0 and 8.9.1 with the following error: CURLE_OPERATION_TIMEDOUT from curl_easy_perform. Although file was successfully transferred. FTP log has the following last 2 records:
INFO_TEXT:
SSL shutdown timeout

INFO_TEXT:
closing connection #0

Simple replacement libcurl.dll to v. 8.7.1 make it work in same environment. The same behaviour of libcurl.so(a) 8.9.1 is observed on Linux, UNIX AIX, Solaris SPARC and Solaris Intel.

### I expected the following

Expected successful file transfer without error like it was with curl 8.7.1 and earlier versions

### curl/libcurl version

curl 8.9.1

### operating system

Windows 2019

**Comment by bagder** [comment] 2024-09-06 06:50
First you say:

> The same behaviour of libcurl.so(a) 8.9.1 is observed on Linux, UNIX AIX, Solaris SPARC and Solaris Intel.

And then you say:

> Windows 2019

Does it mean it *also* reproduces on Windows or ...?

Further: which TLS library (and version) are you using with your builds?

**Comment by Valery-OT** [comment] 2024-09-06 21:50
1.  Yes, first it was detected it on Windows and then confirmed on other platforms as well.
  2.  Sorry, I don’t get your question related to TLS library. We don’t use separate TLS library. We build libcurl.dll(so,a) 8.9.1.0, same way as we built all previous versions of libcurl up to 8.7.1 as following:
C:\ curl-8.9.1\winbuild> nmake /f Makefile.vc mode=dll VC=17 WITH_SSL=dll SSL_PATH="C:\ OpenSSL\VS2022.Win64.Release" MACHINE=x64 ENABLE_WINSSL=no ZLIB_PATH="C:\zlib-1.2.12" ZLIB_LIB="C:\ zlib\x64\Release" "RELEASE=yes"

Regards,
Valery

From: Daniel Stenberg ***@***.***>
Sent: September 6, 2024 2:51 AM
To: curl/curl ***@***.***>
Cc: Valery Bachinsky ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] - Re: [curl/curl] FTPS transfer C++ implementation using libcurl 8.9.1 failed with CURLE_OPERATION_TIMEDOUT ("SSL shutdown timeout" in the log) (Issue #14800)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe. If you feel that the email is suspicious, please report it using PhishAlarm.


First you say:

The same behaviour of libcurl.so(a) 8.9.1 is observed on Linux, UNIX AIX, Solaris SPARC and Solaris Intel.

And then you say:

Windows 2019

Does it mean it also reproduces on Windows or ...?

Further: which TLS library (and version) are you using with your builds?

**Comment by bagder** [comment] 2024-09-08 22:01
> We don’t use separate TLS library

I'm asking for which TLS library and which version you use.

Further: we need more details about the problem. Preferably a recipe so that we can reproduce.

Does it always happen to you against any server?

**Comment by Valery-OT** [comment] 2024-09-10 01:58
Hi Daniel,


>> I'm asking for which TLS library and which version you use.

We built curl with openssl-3.3.1
>> Further: we need more details about the problem. Preferably a recipe so that we can reproduce.
The following options are set by seria of curl_easy_setopt calls prior curl_easy_perform call where “SSL shutdown timeout” error is generated:
CURLOPT_UPLOAD - 1
CURLOPT_FTPAPPEND – 0
CURLOPT_READFUNCTION – FtpReaderCallback
CURLOPT_READDATA – this
CURLOPT_INFILESIZE_LARGE - (curl_off_t)fileSize – 2103
CURLOPT_VERBOSE - GEN_TRUE
CURLOPT_DEBUGDATA – pointer (&m_DbgData)
CURLOPT_DEBUGFUNCTION – DebugCallback
CURLOPT_HEADER – 0
CURLOPT_HEADERFUNCTION – FtpNullWriterCallback
CURLOPT_WRITEHEADER – this
CURLOPT_TRANSFERTEXT – 0
CURLOPT_CRLF – 0
CURLOPT_FTPPORT - ":1649-1990"
CURLOPT_FTP_USE_EPRT – 0
CURLOPT_USERPWD – UsrPass
CURLOPT_FTPLISTONLY – 0
CURLOPT_USE_SSL - CURLUSESSL_ALL
CURLOPT_FTP_SSL_CCC – 0
CURLOPT_SSL_VERIFYPEER – 0
CURLOPT_SSL_VERIFYHOST – 0
CURLOPT_SSLVERSION – 0 (default)
CURLOPT_SSL_SESSIONID_CACHE – 0
CURLOPT_SSLCERT – path to certificate file
CURLOPT_SSLCERTTYPE - "P12"
CURLOPT_SSLKEY – path to certificate file
CURLOPT_SSLKEYTYPE - "P12"
CURLOPT_KEYPASSWD – private key password
CURLOPT_URL  ftp://10.3.19.80:21/ws777%2Etxt
CURLOPT_QUOTE – null
CURLOPT_POSTQUOTE – null
CURLOPT_FTP_RESPONSE_TIMEOUT – 300
CURLOPT_TIMEOUT – 300
CURLOPT_NOPROGRESS – 0
CURLOPT_PROGRESSFUNCTION – FtpProgressCallback
CURLOPT_PROGRESSDATA – this

Then curl_easy_perform call.

>> Does it always happen to you against any server?
It always happen with curl 8.9.1 and 8.9.0 and never happens with curl 8.7.1 and earlier against the same FTP server. FTP server version 10.0.17763.1.
Regards,
Valery

From: Daniel Stenberg ***@***.***>  To: curl/curl ***@***.***>
Cc: Valery Bachinsky ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] - Re: [curl/curl] FTPS using libcurl 8.9.1 fails with CURLE_OPERATION_TIMEDOUT (Issue #14800)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe. If you feel that the email is suspicious, please report it using PhishAlarm.


We don’t use separate TLS library

I'm asking for which TLS library and which version you use.

Further: we need more details about the problem. Preferably a recipe so that we can reproduce.

Does it always happen to you against any server?

**Comment by dfandrich** [comment] 2024-09-10 02:33
Can you provide a debug log of the session? That server is not accessible to us. Can you reproduce this with the curl command-line tool?

**Comment by Valery-OT** [comment] 2024-09-10 20:06
Thank you, Rasmus.
You are absolutely right. The fix resolved the issue. Just tested it on Windows.
Do you know, approximately, when official release having this fix will be available?

Regards,
Valery

From: Rasmus Melchior Jacobsen ***@***.***>
Sent: September 10, 2024 8:46 AM
To: curl/curl ***@***.***>
Cc: Valery Bachinsky ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] - Re: [curl/curl] FTPS using libcurl 8.9.1 fails with CURLE_OPERATION_TIMEDOUT (Issue #14800)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe. If you feel that the email is suspicious, please report it using PhishAlarm.


I believe this is the same issue as #14843<https://urldefense.com/v3/__https:/github.com/curl/curl/issues/14843__;!!Obbck6kTJA!ajVbj1CjAc0nd030vLZZbLp7bWekqlzNqALhwixkBqBEcoUst_H1H0A9XOhJvJZ3NShvw6nh9WRy5bOcOpK_Fpo_bg$> for which there currently is a fix in #14848<https://urldefense.com/v3/__https:/github.com/curl/curl/pull/14848__;!!Obbck6kTJA!ajVbj1CjAc0nd030vLZZbLp7bWekqlzNqALhwixkBqBEcoUst_H1H0A9XOhJvJZ3NShvw6nh9WRy5bOcOpIFBIgIeg$>.

**Comment by Valery-OT** [comment] 2024-09-10 20:23
Hi Dan,

Issue is fixed by this commit:
#14848<https://urldefense.com/v3/__https:/github.com/curl/curl/pull/14848__;!!Obbck6kTJA!ajVbj1CjAc0nd030vLZZbLp7bWekqlzNqALhwixkBqBEcoUst_H1H0A9XOhJvJZ3NShvw6nh9WRy5bOcOpIFBIgIeg$>
I verified the fix.

Thanks to Rasmus Melchior Jacobsen providing this info.

Regards,
Valery

From: Dan Fandrich ***@***.***>
Sent: September 9, 2024 10:34 PM
To: curl/curl ***@***.***>
Cc: Valery Bachinsky ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] - Re: [curl/curl] FTPS using libcurl 8.9.1 fails with CURLE_OPERATION_TIMEDOUT (Issue #14800)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe. If you feel that the email is suspicious, please report it using PhishAlarm.

Can you provide a debug log of the session? That server is not accessible to us. Can you reproduce this with the curl command-line tool?

**Comment by bagder** [comment] 2024-09-10 21:38
> Do you know, approximately, when official release having this fix will be available?

It will *not* be in the 8.10.0 release that ships tomorrow, simply because it was not done in time. It will most likely be merged and ship in the first release after that.

**Comment by Valery-OT** [comment] 2024-09-11 12:45
Thank you!

Regards,
Valery

From: Daniel Stenberg ***@***.***>
Sent: September 10, 2024 5:39 PM
To: curl/curl ***@***.***>
Cc: Valery Bachinsky ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] - Re: [curl/curl] FTPS using libcurl 8.9.1 fails with CURLE_OPERATION_TIMEDOUT (Issue #14800)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe. If you feel that the email is suspicious, please report it using PhishAlarm.


Do you know, approximately, when official release having this fix will be available?

It will not be in the 8.10.0 release that ships tomorrow, simply because it was not done in time. It will most likely be merged and ship in the first release after that.

**Comment by bagder** [comment] 2024-10-04 16:02
Fixed

**Closed by bagder** 2024-10-04 16:02 UTC
Labels: TLS, FTP
