### ISSUE TITLE
HTTP/2 (h2c) upgrade in clear-text problem

### ISSUE THREAD

**Issue by tk-xiong** [curl/curl#7633] opened 2021-08-26 03:04 UTC
### I did this
I use curl and Golang HttpClient to call my service.
Golang's HttpClient is working fine.

curl:
This does not work if --http2 is used.
This works if use --http2-prior-knowledge.

### I expected the following
both use --http2 and --http2-prior-knowledge working fine.

### curl/libcurl version
Windows:
curl 7.78.0 (x86_64-pc-win32) libcurl/7.78.0 OpenSSL/1.1.1l (Schannel) zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libssh2/1.9.0 nghttp2/1.44.0 libgsasl/1.10.0
Release-Date: 2021-07-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP UnixSockets zstd

Linux:
curl 7.78.0 (x86_64-pc-linux-gnu) libcurl/7.78.0 zlib/1.2.7 nghttp2/1.44.0
Release-Date: 2021-07-21
Protocols: dict file ftp gopher http imap mqtt pop3 rtsp smtp telnet tftp 
Features: alt-svc AsynchDNS HTTP2 IPv6 Largefile libz UnixSockets

[curl -V output]
~~~
*   Trying 192.168.0.11:10001...
* Connected to 192.168.0.11 (192.168.0.11) port 10001 (#0)
> Get /hello/ HTTP/1.1
> Host: 192.168.0.11:10001
> User-Agent: curl/7.78.0
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAAQCAAAAAAIAAAAA
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 101 Switching Protocols
HTTP/1.1 101 Switching Protocols
< Connection: Upgrade
Connection: Upgrade
< Upgrade: h2c
Upgrade: h2c
* Received 101
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
~~~
### operating system

Linux <hostname> 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment] 2021-08-30 10:57
I can't repro that error. With the reverted commit I get this (debug build):
~~~
$ ./src/curl -v --http2 http://121.37.5.232:10000/hello/
* STATE: INIT => CONNECT handle 0x55e7b84e20a8; line 1780 (connection #-5000)
* Added connection 0. The cache now contains 1 members
* family0 == v4, family1 == v6
*   Trying 121.37.5.232:10000...
* STATE: CONNECT => CONNECTING handle 0x55e7b84e20a8; line 1841 (connection #0)
* Connected to 121.37.5.232 (121.37.5.232) port 10000 (#0)
* STATE: CONNECTING => PROTOCONNECT handle 0x55e7b84e20a8; line 1971 (connection #0)
* STATE: PROTOCONNECT => DO handle 0x55e7b84e20a8; line 1994 (connection #0)
> GET /hello/ HTTP/1.1
> Host: 121.37.5.232:10000
> User-Agent: curl/7.79.0-DEV
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAAQCAAAAAAIAAAAA
> 
* STATE: DO => DID handle 0x55e7b84e20a8; line 2068 (connection #0)
* STATE: DID => PERFORMING handle 0x55e7b84e20a8; line 2187 (connection #0)
* Mark bundle as not supporting multiuse
* HTTP/2 found, allow multiplexing
< HTTP/1.1 101 Switching Protocols
< Connection: Upgrade
< Upgrade: h2c
* Received 101
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* multi changed, check CONNECT_PEND queue!
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
* multi changed, check CONNECT_PEND queue!
* HTTP/2 found, allow multiplexing
< HTTP/2 200 
< content-type: text/plain; charset=utf-8
< content-length: 6
< date: Mon, 30 Aug 2021 10:54:30 GMT
< 
* nread == 0, stream closed, bailing
* STATE: PERFORMING => DONE handle 0x55e7b84e20a8; line 2386 (connection #0)
* multi_done
* Connection #0 to host 121.37.5.232 left intact
* Expire cleared (transfer 0x55e7b84e20a8)

**Comment by tk-xiong** [comment] 2021-08-30 12:07
I revert https://github.com/curl/curl/commit/455a63c66f188598275e87d32de2c4e8e26b80cb
It returns the correct results, but I still think there are some problems.

`$ ./curl -v --http2 -g "121.37.5.232:10000/hello/"
*   Trying 121.37.5.232:10000...
* Connected to 121.37.5.232 (121.37.5.232) port 10000 (#0)
> GET /hello/ HTTP/1.1
> Host: 121.37.5.232:10000
> User-Agent: curl/7.78.0
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAAQCAAAAAAIAAAAA
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 101 Switching Protocols
< Connection: Upgrade
< Upgrade: h2c
* Received 101
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 200 
< content-type: text/plain; charset=utf-8
< content-length: 6
< date: Mon, 30 Aug 2021 12:04:46 GMT
< 
* Connection #0 to host 121.37.5.232 left intact
Hello.`

`$ ./curl -vI --http2 -g "121.37.5.232:10000/hello/"
*   Trying 121.37.5.232:10000...
* Connected to 121.37.5.232 (121.37.5.232) port 10000 (#0)
> HEAD /hello/ HTTP/1.1
> Host: 121.37.5.232:10000
> User-Agent: curl/7.78.0
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAAQCAAAAAAIAAAAA
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 101 Switching Protocols
HTTP/1.1 101 Switching Protocols
< Connection: Upgrade
Connection: Upgrade
< Upgrade: h2c
Upgrade: h2c
* Received 101
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0

* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
* HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
* stopped the pause stream!
* Connection #0 to host 121.37.5.232 left intact
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
`

**Comment by tk-xiong** [comment] 2021-08-30 12:12
I revert 455a63c
It returns the correct results, but I still think there are some problems.

```
$ ./curl -v --http2 -g "121.37.5.232:10000/hello/"

Trying 121.37.5.232:10000...
Connected to 121.37.5.232 (121.37.5.232) port 10000 (#0)
GET /hello/ HTTP/1.1
Host: 121.37.5.232:10000
User-Agent: curl/7.78.0
Accept: /
Connection: Upgrade, HTTP2-Settings
Upgrade: h2c
HTTP2-Settings: AAMAAABkAAQCAAAAAAIAAAAA

Mark bundle as not supporting multiuse
< HTTP/1.1 101 Switching Protocols
< Connection: Upgrade
< Upgrade: h2c
Received 101
Using HTTP2, server supports multiplexing
Connection state changed (HTTP/2 confirmed)
Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 200
< content-type: text/plain; charset=utf-8
< content-length: 6
< date: Mon, 30 Aug 2021 12:04:46 GMT
<
Connection #0 to host 121.37.5.232 left intact
Hello.
```


```
$ ./curl -vI --http2 -g "121.37.5.232:10000/hello/"

Trying 121.37.5.232:10000...
Connected to 121.37.5.232 (121.37.5.232) port 10000 (#0)
HEAD /hello/ HTTP/1.1
Host: 121.37.5.232:10000
User-Agent: curl/7.78.0
Accept: /
Connection: Upgrade, HTTP2-Settings
Upgrade: h2c
HTTP2-Settings: AAMAAABkAAQCAAAAAAIAAAAA

Mark bundle as not supporting multiuse
< HTTP/1.1 101 Switching Protocols
HTTP/1.1 101 Switching Protocols
< Connection: Upgrade
Connection: Upgrade
< Upgrade: h2c
Upgrade: h2c

Received 101

Using HTTP2, server supports multiplexing

Connection state changed (HTTP/2 confirmed)

Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0

Connection state changed (MAX_CONCURRENT_STREAMS == 250)!

HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)

stopped the pause stream!

Connection #0 to host 121.37.5.232 left intact
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
Does this need to be fixed?

**Comment by bagder** [comment] 2021-08-30 12:12
> Does this need to be fixed?

Probably, but as I've said: I cannot reproduce that.

**Comment by tk-xiong** [comment] 2021-08-30 13:02
I Use git clone master branch and revert code.
It also has error.

```
git clone https://github.com/curl/curl.git
 
autoreconf -fi
 
# change configure file:
want_h2_path="$withval/lib/pkgconfig" to want_h2_path="$withval/lib64/pkgconfig"
 
# revert code.
... ... 
 
# build
./configure --prefix=/data/tkxiong/curl/release \
    --with-nghttp2=/data/tkxiong/nghttp2/release \
    --disable-shared \
    --without-ssl
 
make && make install
```
Wow~ It work!

```
$ ./curl -vI -g "http://121.37.5.232:10000/hello/"
*   Trying 121.37.5.232:10000...
* Connected to 121.37.5.232 (121.37.5.232) port 10000 (#0)
> HEAD /hello/ HTTP/1.1
> Host: 121.37.5.232:10000
> User-Agent: curl/7.79.0-DEV
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Date: Mon, 30 Aug 2021 13:01:31 GMT
Date: Mon, 30 Aug 2021 13:01:31 GMT
< Content-Length: 6
Content-Length: 6
< Content-Type: text/plain; charset=utf-8
Content-Type: text/plain; charset=utf-8

< 
* Connection #0 to host 121.37.5.232 left intact


$ ./curl -v -g "http://121.37.5.232:10000/hello/"
*   Trying 121.37.5.232:10000...
* Connected to 121.37.5.232 (121.37.5.232) port 10000 (#0)
> GET /hello/ HTTP/1.1
> Host: 121.37.5.232:10000
> User-Agent: curl/7.79.0-DEV
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Mon, 30 Aug 2021 13:01:39 GMT
< Content-Length: 6
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host 121.37.5.232 left intact
Hello.
```

**Comment by tk-xiong** [comment] 2021-08-30 13:09
When I back to /data/tkxiong/curl-7.78.0/release/bin, It also worked!

I think that should be settled. Thank you.

**Comment by tk-xiong** [comment] 2021-08-30 13:11
Nonono ... I forgot use --http2

**Comment by tk-xiong** [comment] 2021-08-30 13:16
[tkxiong@algorithm-test01 bin]$ ./curl --version
curl 7.79.0-DEV (x86_64-unknown-linux-gnu) libcurl/7.79.0-DEV zlib/1.2.7 nghttp2/1.44.0
Release-Date: [unreleased]
Protocols: dict file ftp gopher http imap mqtt pop3 rtsp smtp telnet tftp 
Features: alt-svc AsynchDNS HTTP2 IPv6 Largefile libz UnixSockets

**Comment by bagder** [comment] 2021-08-30 14:45
I believe the `HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR` error is unrelated and a different thing.

Your server sends a `RST_STREAM` with this error when curl sends a `HEAD` request, but now when a `GET` is sent.

**Comment by tk-xiong** [comment] 2021-08-30 15:41
Ok, thank you very much. I'll try to learn the difference between HEAD and GET requests.
close the issue.

**Comment by bagder** [comment] 2021-08-30 15:57
The revert is still needed so this issue is still real and thus you closed it prematurely.

**Comment by tk-xiong** [comment] 2021-08-31 05:50
Sorry, I will reopen it, so when should I close this issue?

**Comment by bagder** [comment] 2021-08-31 06:58
When we merged the fix, which was done already.

**Closed by bagder** 2021-08-31 06:58 UTC
Labels: HTTP/2
