### ISSUE TITLE
FTP upload fails if remebered dir is deleted

### ISSUE THREAD

**Issue by JayDommaschk** [curl/curl#12181] opened 2023-10-23 03:19 UTC
### I did this

I have some server application which would upload files to some FTP server upon certain events. The user sets the path to which the file should be uploaded. If the target folder doesn't already exists, curl creates the folder and then "remembers we are in dir ...", which is all good. However, if someone, for whatever reason, where to delete the target folder from the server, then subsequent uploads will fail.

This can be seen with the following super simple test code:

```c
#include <curl/curl.h>
#include <sys/stat.h>
#include <unistd.h>

#define TEST_FILE_PATH "/tmp/testfile"
#define TEST_FOLDER "/folder/"

int main()
{
    FILE *file = fopen(TEST_FILE_PATH, "rb");
    struct stat file_info;
    stat(TEST_FILE_PATH, &file_info);

    char SERVER_URL[512];
    CURLcode res = CURLE_OK;
    CURL *curl = curl_easy_init();

    curl_version_info_data *ver = curl_version_info(CURLVERSION_NOW);
    printf("curl version: %u.%u.%u\n", (ver->version_num >> 16) & 0xff,
                                       (ver->version_num >> 8) & 0xff,
                                       ver->version_num & 0xff);

    curl_easy_setopt(curl, CURLOPT_USERNAME, "test");
    curl_easy_setopt(curl, CURLOPT_PASSWORD, "testtest");

    snprintf(SERVER_URL, sizeof(SERVER_URL), "ftp://%s:%s/%s%s", "192.168.0.104", "21", TEST_FOLDER, "curltest.txt");
    curl_easy_setopt(curl, CURLOPT_URL, SERVER_URL);
    curl_easy_setopt(curl, CURLOPT_INFILESIZE_LARGE, (curl_off_t)(file_info.st_size));
    curl_easy_setopt(curl, CURLOPT_FTP_CREATE_MISSING_DIRS, CURLFTP_CREATE_DIR_RETRY);
    curl_easy_setopt(curl, CURLOPT_READDATA, file);
    curl_easy_setopt(curl, CURLOPT_UPLOAD, 1L);

    curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);

    for (int i = 0; i < 10; ++i)
    {
        res = curl_easy_perform(curl);
        printf("curl result: %s (%d)\n", curl_easy_strerror(res), res);
        if (res != CURLE_OK)
            break;
        sleep(10);
        fseek(file, 0, SEEK_SET);
    }
    fclose(file);
    curl_easy_cleanup(curl);
}
```

which produces the following output, where between the second and third upload, I went to the file system of my FTP server and deleted the folder "folder":
```console
curl version: 8.4.0
*   Trying 192.168.0.104:21...
* Connected to 192.168.0.104 (192.168.0.104) port 21
< 220-FileZilla Server 1.4.1
< 220 Please visit https://filezilla-project.org/
> USER test
< 331 Please, specify the password.
> PASS testtest
< 230 Login successful.
> PWD
< 257 "/" is current directory.
* Entry path is '/'
> CWD /
* ftp_perform ends with SECONDARY: 0
< 250 CWD command successful
> CWD Folder
< 550 Couldn't open the file or directory
> MKD Folder
< 257 "/Folder" created successfully.
> CWD Folder
< 250 CWD command successful
> EPSV
* Connect data stream passively
< 229 Entering Extended Passive Mode (|||49211|)
* Connecting to 192.168.0.104 (192.168.0.104) port 49211
*   Trying 192.168.0.104:49211...
* Connected to 192.168.0.104 (192.168.0.104) port 21
> TYPE I
< 200 Type set to I
> STOR curltest.txt
< 150 Starting data transfer.
* We are completely uploaded and fine
* Remembering we are in dir "/Folder/"
< 226 Operation successful
* Connection #0 to host 192.168.0.104 left intact
curl result: No error (0)

* Found bundle for host: 0x1af9c70 [serially]
* Re-using existing connection with host 192.168.0.104
* Request has same path as previous transfer
> EPSV
* Connect data stream passively
* ftp_perform ends with SECONDARY: 0
< 229 Entering Extended Passive Mode (|||49212|)
* Connecting to 192.168.0.104 (192.168.0.104) port 49212
*   Trying 192.168.0.104:49212...
* Connected to 192.168.0.104 (192.168.0.104) port 21
> STOR curltest.txt
< 150 Starting data transfer.
* We are completely uploaded and fine
* Remembering we are in dir "/Folder/"
< 226 Operation successful
* Connection #0 to host 192.168.0.104 left intact
curl result: No error (0)

* Found bundle for host: 0x1af9c70 [serially]
* Re-using existing connection with host 192.168.0.104
* Request has same path as previous transfer
> EPSV
* Connect data stream passively
* ftp_perform ends with SECONDARY: 0
< 229 Entering Extended Passive Mode (|||49213|)
* Connecting to 192.168.0.104 (192.168.0.104) port 49213
*   Trying 192.168.0.104:49213...
* Connected to 192.168.0.104 (192.168.0.104) port 21
> STOR curltest.txt
< 550 Couldn't open the file or directory
* Failed FTP upload: 550
* Remembering we are in dir "/Folder/"
* Uploaded unaligned file size (0 out of 7 bytes)
* Connection #0 to host 192.168.0.104 left intact
curl result: Upload failed (at start/before it took off) (25)
```

### I expected the following

I think it would make more sense for curl to just re-create the folder and continue the upload normally.

### curl/libcurl version

curl 8.4.0

### operating system

Linux NVTEVM 4.19.91 #5 SMP PREEMPT Mon Jun 12 12:34:00 UTC 2023 armv7l GNU/Linux
(I've been testing this on some embedded device)

**Comment by bagder** [comment] 2023-10-23 08:15
> I think it would make more sense for curl to just re-create the folder and continue the upload normally.

I think that is hard. There is no clear error code for curl that tells it exactly what the problem is. The 550 error is very generic, and I'm not sure curl has the mandate to try to make the directory on 550 errors in general.

This error is of course a side-effect of curl assuming things are the same as before when it comes back to the server, which is a rather naive and simplified world-view, but one that works surprisingly well in the general case.

At least retrying the same transfer again here would likely succeed as then curl more specifically will detect that the directory does not exist and create it if asked to.

**Comment by JayDommaschk** [comment] 2023-10-23 10:07
Thanks for your reply

> At least retrying the same transfer again here would likely succeed as then curl more specifically will detect that the directory does not exist and create it if asked to.

Do you mean this is something that could be changed on the curl side or is this something that my application should do? Because currently it seems like simply retrying does not really help. If I remove the break from my above test code, every upload after the deletion still fails. 

> This error is of course a side-effect of curl assuming things are the same as before when it comes back to the server, which is a rather naive and simplified world-view, but one that works surprisingly well in the general case.

Is there any way to stop curl from making this assumption? I actually searched for this because it would have been an easy solution, but I did not find any such setting.

**Comment by bagder** [comment] 2023-10-23 21:57
>  If I remove the break from my above test code, every upload after the deletion still fails.

Aaah, yes. Because it thinks its just a failed upload so it keeps the connection alive and the (bad) state, so repeated attempts will just get the same problem again. Hm. Complicated.

I think we might need to introduce a command or something when reusing a connection that verifies that the path is still legit and working.

**Comment by dfandrich** [comment] 2023-10-23 22:09
Or just close the connection on error. Adding another round trip on every
transfer will have a negative performance impact when transferring lots of
files.

**Comment by JayDommaschk** [comment] 2023-10-25 11:45
Forgetting the path on error would solve the problem for the next upload, but the current one, i.e. the one that triggered the error, would still be lost. That being said, I understand that this is a complicated problem and I would feel bad for demanding something that just can't be done.

My best idea would be to have some setting that would keep curl from remembering directories, basically a less brutal version of CURLOPT_FORBID_REUSE. Then everyone can decide for their own application whether they need this, since - let's be real - having folders deleted from the FTP server is probably not exactly an everyday use case. I, too, was only alerted to this by some user.

Also in the meantime I found the option CURLOPT_FRESH_CONNECT which might be helpful to just retry the upload on the application side when it receives CURLE_UPLOAD_FAILED (haven't tested this yet, though), so even if nothing can be done about the issue whatsoever, there might be hope to keep my user happy.

**Comment by bagder** [comment] 2023-10-26 10:36
> Forgetting the path on error would solve the problem for the next upload, but the current one, i.e. the one that triggered the error, would still be lost

The only semi-reliable way to avoid that completely is to always CURLOPT_FORBID_REUSE. It's only "semi" because the directory could also in fact get removed while the transfer is in progress, assuming it can happen at any random moment in time.

I think we need to accept the fact that if parts of the dir hierarchy can get removed while the connection is used, an individual transfer can fail. But that is also returned as a failure and an application could, by its own decision, decide to retry.

> My best idea would be to have some setting that would keep curl from remembering directories, basically a less brutal version of CURLOPT_FORBID_REUSE

When would a user know to set this option? Surely very few user actually *expect* the directory to vanish during transfer or between transfers? And even if it happens only once in a million, surely apps want to survive this then as well?

**Comment by JayDommaschk** [comment] 2023-10-26 11:50
> I think we need to accept the fact that if parts of the dir hierarchy can get removed while the connection is used, an individual transfer can fail

fair enough

> When would a user know to set this option? 

Actually, in the specific case that started this, this is not something that happens randomly, but the user does this on purpose: They have a script running that checks periodically whether a certain folder on their FTP server exists and if it does, the folder gets downloaded and deleted. What makes this worse is that they keep shoving into my face that some different software handles this case correctly. (I don't know what the other software does) So in that case it would be obvious enough to use the new option. 

I do agree, however, that the case of stuff vanishing unexpectedly should also be considered and probably it is even more important. So if this concludes with just forgetting the dir on error such that at least subsequent uploads can recover, while I have to find another solution for the above special use case, I would not complain.

**Closed** 2024-02-10 17:49 UTC
Labels: FTP, KNOWN_BUGS material
