### ISSUE TITLE
Paused connection DONE prematurely

### ISSUE THREAD

**Issue by pprindeville** [curl/curl#2424] opened 2018-03-23 21:36 UTC
### I did this

Possibly related to issue #2393.

Running a program similar to the `pacing.c` test case.  At some point, it pauses the CURL session because data isn't being consumed fast enough.

Read events on the socket seem to be stopped, as indicated by:

```
write_cb: need 16384 but have 804 (pausing)
socket callback: s=8 e=0x250f3d0 what=REMOVE
```

then, despite the socket supposedly being paused, we see:

```
DONE: https://r1---sn-ntgpob5-cvpe.googlevideo.com/videoplayback?fexp=23731050&ratebypass=yes&mt=1521824322&signature=582CF53AA6F9217BD8F252F7FF5EF47D223F706F.BD72F3910D92F364062B1E44BDDDB7D781568BFD&lmt=15... => (28) Operation timed out after 330002 milliseconds with 50744211 out of 57230575 bytes received
```

Note that 6486364 bytes have not been received (the difference above).

Eventually we try to resume the connection with `curl_easy_pause(conn->easy, CURLPAUSE_RECV_CONT);` but as we've already done a `curl_multi_remove_handle(g->multi, easy);` this doesn't work.

### I expected the following

The `DONE:` message (due to the `CURLMSG_DONE` indication from `curl_multi_info_read()`) should not have happened (a) while the socket was paused and (b) until all the data was delivered.

### curl/libcurl version

```
curl 7.59.0 (x86_64-pc-linux-gnu) libcurl/7.59.0 OpenSSL/1.1.0g zlib/1.2.11
Release-Date: 2018-03-14
Protocols: http https ldap ldaps 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy 
```

patched (per PR #2391).

### operating system

Fedora 27

**Comment by bagder** [comment] 2018-03-23 21:58
"Operation timed out after 330002" sounds like a timeout that triggers. Did you have a `CURLOPT_TIMEOUT` set?

**Comment by bagder** [comment] 2018-03-24 12:58
Is this a pause returned for the last chunk of the file being written?

**Comment by pprindeville** [comment] 2018-03-25 18:06
No, before then.

**Comment by bagder** [comment] 2018-03-25 21:45
I can't repro this though so unless you give me more details, you're sort of on your own to hunt it down.

**Comment by pprindeville** [comment] 2018-03-25 21:52
I have code that can reproduce it reliably, but I can't disclose that code to the public at large.

**Comment by pprindeville** [comment] 2018-04-19 20:53
Yes, I'm working on it.

**Comment by bagder** [comment] 2018-06-14 12:17
Two more months have passed. Closing this. We can't work with bugs we can't reproduce or get enough details to work on. If you get more data/details on this, feel free to amend and we can re-open or create a new issue. Thanks!

**Closed by bagder** 2018-06-14 12:17 UTC
Labels: needs-info-or-update
