### ISSUE TITLE
Payload dropped from POST when using proxy with NTLM authentication - again

### ISSUE THREAD

**Issue by genotrance** [curl/curl#8778] opened 2022-04-29 21:52 UTC
Referring to issues https://github.com/curl/curl/issues/2431 and https://github.com/jeroen/curl/issues/146 which was fixed a few [years](https://github.com/jeroen/curl/issues/146#issuecomment-476216584) ago.

### I did this

```bash
# curl --proxy proxy:80 --proxy-any --proxy-user : --verbose --data 12345 http://httpbin.org/post

*   Trying IP:80...
* Connected to proxy (IP) port 80 (#0)
> POST http://httpbin.org/post HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.79.1
> Accept: */*
> Proxy-Connection: Keep-Alive
> Content-Length: 5                                                                                              <====
> Content-Type: application/x-www-form-urlencoded
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Fri, 29 Apr 2022 21:32:51 GMT
< Content-Type: application/json
< Content-Length: 468
< Server: gunicorn/19.9.0
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< Proxy-Connection: Keep-Alive
< Connection: Keep-Alive
<
{
  "args": {},
  "data": "",
  "files": {},
  "form": {
    "12345": ""                                                                                                   <====
  },
  "headers": {
    "Accept": "*/*",
    "Content-Length": "5",
    "Content-Type": "application/x-www-form-urlencoded",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.79.1",
    "X-Amzn-Trace-Id": "Root=1-626c5983-33d39ebf66f98f0277729cf5",
  },
  "json": null,
  "url": "http://httpbin.org/post"
}
* Connection #0 to host proxy left intact
```

Works as expected, for ANY and NEGOTIATE. Going direct (without proxy) also works.

Change to NTLM and it fails.

```bash
# curl --proxy proxy:80 --proxy-ntlm --proxy-user : --verbose --data 12345 http://httpbin.org/post

*   Trying IP:80...
* Connected to proxy (IP) port 80 (#0)
* Proxy auth using NTLM with user ''
> POST http://httpbin.org/post HTTP/1.1
> Host: httpbin.org
> Proxy-Authorization: NTLM xxxxxxxx
> User-Agent: curl/7.79.1
> Accept: */*
> Proxy-Connection: Keep-Alive
> Content-Length: 0                                                                                              <====
> Content-Type: application/x-www-form-urlencoded
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Fri, 29 Apr 2022 21:32:37 GMT
< Content-Type: application/json
< Content-Length: 449
< Server: gunicorn/19.9.0
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< Proxy-Connection: Keep-Alive
< Connection: Keep-Alive
<
{
  "args": {},
  "data": "",
  "files": {},
  "form": {},                                                                                                    <====
  "headers": {
    "Accept": "*/*",
    "Content-Length": "0",
    "Content-Type": "application/x-www-form-urlencoded",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.79.1",
    "X-Amzn-Trace-Id": "Root=1-626c5975-13ea51a9668fa8170055502a",
  },
  "json": null,
  "url": "http://httpbin.org/post"
}
* Connection #0 to host proxy.us.dell.com left intact
```

### curl/libcurl version

This is demonstrated above with curl CLI v7.79.1. I originally found the issue with libcurl v7.82.0 and also see it with v7.80.0 and v7.68.0.

### operating system

Duplicated on Windows 10, Alpine Linux and Ubuntu.

Cc @jeroen @matthijsvanderloos

**Comment by jay** [comment] 2022-04-30 06:48
If you ask for NTLM specifically then the post data is withheld until the authentication is completed. In your case the server ignores NTLM and because the post data is withheld it replies with bad request. IMO not retrying is not a bug and the solution is do not use  --proxy-ntlm.

> Referring to issues #2431 and [jeroen/curl#146](https://github.com/jeroen/curl/issues/146) which was fixed a few [years](https://github.com/jeroen/curl/issues/146#issuecomment-476216584) ago.

That issue isn't the same because it was a bug that AFAICT could only happen when proxy tunneling. If curl tunnels through a proxy (like for https urls or if --proxytunnel) that means it first sends a CONNECT request to the proxy because it needs to send the actual request to the server rather than have the proxy do it. Once the connection is established (the proxy replies 200 OK connection to server has been opened and then proxy auth is marked done) then curl sends the request to the server. It looks like the bug was that curl did not properly check if the proxy auth phase was done when deciding whether or not to withhold post data.

**Comment by genotrance** [comment] 2022-05-01 05:16
Good catch, I didn't notice that https://github.com/curl/curl/issues/2431 was related to `CONNECT`.

I also found few other links where this exact issue was discussed in the past:
- Stack [overflow](https://stackoverflow.com/questions/2028559/commandline-curl-post-gives-zero-content-length) in 2010
- Curl [mailing](http://curl.haxx.se/mail/archive-2009-03/0013.html) list in 2009

In both cases, the recommendation was to avoid using `--proxy-ntlm` and to prefer `--proxy-anyauth`.

Question: why do `--proxy-negotiate` and `--proxy-anyauth` not optimize away the `POST` data for initial connect and `--proxy-ntlm` does? Don't they expect to be challenged? Why is this optimization only for NTLM?

Meanwhile, I tested against my proxy after several hours and still didn't get challenged for `POST`. Switch to `GET` and it challenges me every time. Amusingly, my proxy does not ever challenge `POST` with `--proxy-negotiate` or `--proxy-anyauth` either.

Is this because the proxy expects that `POST` usually follow a `GET`? You typically have to load a page before POSTing which will be challenged anyway so it seems like a decent optimization. If that is the case then it seems prudent for curl to not optimize for NTLM. I'd think browsers don't do this either - start with ANY and then just assume NTLM since it worked once. Considering this issue has been known for over 13 years and `--proxy-anyauth` is only a workaround, it is worth a thought.

I'd also like to point out that `--proxy-anyauth` is not always practical since https://github.com/curl/curl/issues/876 is still not resolved. On systems where `--proxy-anyauth` doesn't work, you are expected to use `--proxy-ntlm` and thanks to this issue, you cannot.

I use libcurl directly so I could do `CURLAUTH_ANY & ~CURLAUTH_NEGOTIATE` if a user wants `CURLAUTH_NTLM` - not sure if it will work as expected though.

**Comment by jay** [comment] 2022-05-03 06:00
> I also found few other links where this exact issue was discussed in the past:

Note the mailing list article does not appear to be the exact issue.

> Question: why do `--proxy-negotiate` and `--proxy-anyauth` not optimize away the `POST` data for initial connect and `--proxy-ntlm` does? Don't they expect to be challenged? Why is this optimization only for NTLM?

For proxy-negotiate I didn't know that and I'm not sure why... For proxy-ntlm curl expects a challenge reply. proxy-anyauth is when there _may_ be a challenge reply, and you want curl to figure out which auth to use. In that case the actual request may be sent, challenged, then sent again. That is a waste if you expect there definitely will be a challenge.

> Amusingly, my proxy does not ever challenge POST with --proxy-negotiate or --proxy-anyauth either.
> Is this because the proxy expects that POST usually follow a GET?

This sounds like an issue specific to your proxy.

> I'd also like to point out that `--proxy-anyauth` is not always practical since #876 is still not resolved. On systems where `--proxy-anyauth` doesn't work, you are expected to use `--proxy-ntlm` and thanks to this issue, you cannot.

IMO that is a corner case but maybe others disagree?

I realize this does not answer all your questions but this is all I know the answer to. I once again suggest use proxy-anyauth.

/cc @iboukris @captain-caveman2k

**Comment by bagder** [comment] 2022-05-03 06:01
Everything involving NTLM is complicated, painful and special because that authentication method uniquely breaks common HTTP paradigms in ways nothing else does. NTLM will always be special.

> Meanwhile, I tested against my proxy after several hours and still didn't get challenged for POST. Switch to GET and it challenges me every time

That's of course up to your proxy to do, but it sounds rather crazy to me to have authentication differ depending on method.

> I'd also like to point out that --proxy-anyauth is not always practical since https://github.com/curl/curl/issues/876 is still not resolved

I'm pretty sure `--proxy-anyauth` is not *universally* broken, it was "only" for that use case. I believe it has been used fine for others. And of course, if there's a bug there's a place to start debugging!

**Comment by genotrance** [comment] 2022-05-03 15:36
> This sounds like an issue specific to your proxy.

Being the opaque blob that commercial proxies are, who knows if we will ever find out if this is intentional or a bug. Given most POST happen through HTTPS nowadays, probably why no one cares at this point. If `--proxy-ntlm` works for many other proxies then it's hard to argue beyond a point and I'm not even sure how to check the way browsers deal with this situation to really compare. I do see similar reports for IE6 which also optimized POST since it expects a challenge and it caused all sorts of headaches.

> I'm pretty sure --proxy-anyauth is not universally broken, it was "only" for that use case. I believe it has been used fine for others. And of course, if there's a bug there's a place to start debugging!

I only mentioned #876 since I see that issue blocking me when I try to workaround this NTLM issue with ANY on my setup. While I can workaround these issues on my setup, my actual goal is to replace the current Python based backend for my [authenticating proxy](https://github.com/genotrance/px) with libcurl. That means users of Px could run into such situations in their setups so there needs to be some generic solution.

I was hoping to do away with having to deal with complex HTTP and proxy behavior and relax on libcurl's giant shoulders but these issues shows there's no free lunch. That being said, making this transition for my small project is still a huge improvement given libcurl's huge list of capabilities and sustained support.

I am planning on using `CURLAUTH_ANY` as the default setup and if anyone requests `CURLAUTH_NTLM` due to #876, I will configure libcurl with `CURLAUTH_ANY & ~CURLAUTH_NEGOTIATE`. That way, users of Px hopefully won't run into either of these issues.

If there's no action possible on this issue, we can close it. Maybe document if it makes sense but if this is very uncommon or likely a proxy bug then we can drop that as well. This issue can serve as documentation.

**Comment by bagder** [comment] 2023-08-14 07:07
We can't reproduce. We have no test case reproducing. Nobody is working on this. Closing.

**Closed by bagder** 2023-08-14 07:07 UTC
Labels: KNOWN_BUGS material, connecting & proxies, authentication
