### ISSUE TITLE
time_total millisecond

### ISSUE THREAD

**Issue by ccesara** [curl/curl#6367] opened 2020-12-24 12:24 UTC
After the last update the value returned when using the "**- total-time**" in the option "**--write-out**" or "**-w**" is not returning in millisecond (float).

Example -> **curl -o /dev/null -w %{time_total} google.com**

Old Version (7.72.0) -> 0.060416
Current Version (7.74.0) -> 74602 

curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1i zlib/1.2.11 zstd/1.4.5 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.41.0
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd

ArchLinux (x86_64) -> 5.9.14-arch1-1 (Updated in 23/Dec/2020)
build script -> https://github.com/archlinux/svntogit-packages/blob/packages/curl/trunk/PKGBUILD

**Comment by bagder** [comment] 2020-12-24 16:07
Duplicate of #6321

Fixed in #6322, already in master

**Closed by bagder** 2020-12-24 16:07 UTC
