### ISSUE TITLE
--data --get with an invalid URL returns "Out of memory" error

### ISSUE THREAD

**Issue by verhovsky** [curl/curl#10086] opened 2022-12-13 12:10 UTC
### I did this

```
$ curl /localhost:8888 --data foo --get
curl: (27) Out of memory
$ curl //localhost:8888 --data foo --get
curl: (27) Out of memory
$ curl ///localhost:8888 --data foo --get
curl: (27) Out of memory
$ curl ////localhost:8888 --data foo --get
curl: (27) Out of memory
```

### I expected the following
An invalid URL error:

```
$ curl /localhost:8888
curl: (3) URL using bad/illegal format or missing URL
```

### curl/libcurl version

```
curl 7.86.0 (aarch64-apple-darwin22.1.0) libcurl/7.86.0 (SecureTransport) OpenSSL/1.1.1s zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.4 libssh2/1.10.0 nghttp2/1.51.0 librtmp/2.3
Release-Date: 2022-10-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

### operating system

```
Darwin myhostname 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64 arm Darwin
```

I noticed this working on https://github.com/curlconverter/curlconverter/pull/487

**Comment by bagder** [comment] 2022-12-13 12:13
Duplicate of #9889 

Fixed in #9892, will be included in the next release

**Closed by bagder** 2022-12-13 12:13 UTC
