### ISSUE TITLE
curl error 23 when output to a local file with special characters

### ISSUE THREAD

**Issue by 1404020324** [curl/curl#5184] opened 2020-04-04 15:49 UTC
### I did this

Run curl and output the file to a filename using unicode/emojis. This makes curl exit with errror 23.

I have a folder  ,named as emoji: 😄 /
```
$ ls
 CURL.EXE*   LIBCURL.DLL*   LIBCURL.EXE*   LIBCURL.LIB  ''$'\360\237\230\200'/
```
then download a png from url, here is the output:
```
 curl -o /😊/head.png https://www.baidu.com/img/bd_logo1.png
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file __/head.png: No such file or directory
 12  7877   12   947    0     0   2332      0  0:00:03 --:--:--  0:00:03  2332
curl: (23) Failed writing body (0 != 947)
```

```
>chcp
Active code page: 65001
```
### curl/libcurl version

`
$ 
curl 7.60.0 (x86_64-w64-mingw32) libcurl/7.60.0 OpenSSL/1.0.2o (WinSSL) zlib/1.2.11 libidn2/2.0.5 nghttp2/1.32.0
Release-Date: 2018-05-16
`

### operating system

Windows 10

**Comment by 1404020324** [comment] 2020-04-04 16:05
for example: I want to save as C:\users\😊😊😊\download\page.html ,but  the curl outout :Fail to create the file ,no such file or directory ,curl : (23) failed writing body

**Comment by jay** [comment] 2020-04-04 18:31
> for example: I want to save as C:\users\\download\page.html ,but the curl outout :Fail to create the file ,no such file or directory ,curl : (23) failed writing body

Please fill out the template when you file an issue and give us a way to reproduce, if possible.

**Comment by bagder** [comment] 2020-04-04 20:44
Known bug? https://curl.haxx.se/docs/knownbugs.html#can_t_handle_Unicode_arguments_i

**Comment by 1404020324** [comment] 2020-04-05 07:00
> > for example: I want to save as C:\users\download\page.html ,but the curl outout :Fail to create the file ,no such file or directory ,curl : (23) failed writing body
> 
> Please fill out the template when you file an issue and give us a way to reproduce, if possible.

Ok, I updated the Issus.

**Comment by bagder** [comment] 2020-04-05 09:09
I could be wrong, but isn't #3784 an attempt to fix this?

**Comment by 1404020324** [comment] 2020-04-05 09:20
> I could be wrong, but isn't #3784 an attempt to fix this?

So this issue has not been resolved and is currently being fixed

**Comment by bagder** [comment] 2020-04-05 09:27
It is marked 'known-issue' since this problem is documented as a **known bug** since a long time back (I linked to that mention). #3784 is an attempt to fix it, but I don't know if the fix is the right thing to land and it seems to have stalled a bit...

**Comment by MarcelRaad** [comment] 2020-04-05 09:31
> isn't #3784 an attempt to fix this?

Yes, if curl is built with Unicode support (as is the default for the Visual Studio project file builds and an option for winbuild). I was waiting for a review or @captain-caveman2k 's alternative, less conservative approach in #4999 to go forward.

**Comment by bagder** [comment] 2020-04-08 14:49
Since this is an already known issue, and one even with some work in progress I'm going to close this issue soon.

**Comment by bagder** [comment] 2020-04-14 07:00
Known issue, closing. We will of course still appreciate work on fix it.

**Closed by bagder** 2020-04-14 07:00 UTC
Labels: Windows, cmdline tool, known-issue
