### ISSUE TITLE
--retry does not retry when combined with --fail-with-body 

### ISSUE THREAD

**Issue by LukeMathWalker** [curl/curl#9078] opened 2022-07-01 11:19 UTC
### I did this

`curl --retry 3 --fail-with-body http://localhost:8082`

where the server is returning 500 errors via this script

```python
from http.server import BaseHTTPRequestHandler, HTTPServer
import time

hostName = "localhost"
serverPort = 8082

class MyServer(BaseHTTPRequestHandler):
    def do_GET(self):
        print("hello")
        self.send_response(500)
        self.send_header("Content-type", "text/html")
        self.end_headers()
        self.wfile.write(bytes("<html><head><title>https://pythonbasics.org/</title></head>", "utf-8"))
        self.wfile.write(bytes("<p>Request: %s</p>" % self.path, "utf-8"))
        self.wfile.write(bytes("<body>", "utf-8"))
        self.wfile.write(bytes("<p>This is an example web server.</p>", "utf-8"))
        self.wfile.write(bytes("</body></html>", "utf-8"))

if __name__ == "__main__":
    webServer = HTTPServer((hostName, serverPort), MyServer)
    print("Server started http://%s:%s" % (hostName, serverPort))

    try:
        webServer.serve_forever()
    except KeyboardInterrupt:
        pass

    webServer.server_close()
    print("Server stopped.")
```

### I expected the following

I expect to see 3 retries, but there were none. If I change the command to `curl --retry --fail http://localhost:8082`, it behaves as expected.

### curl/libcurl version

curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.5 zlib/1.2.11 nghttp2/1.45.1
Release-Date: 2021-09-22
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets

### operating system

System Version: macOS 12.3.1 (21E258)
Kernel Version: Darwin 21.4.0

**Comment by bagder** [comment] 2022-07-01 11:23
Duplicate of #8845 
Fixed in #8847, released in curl 7.84.0

**Closed by bagder** 2022-07-01 11:23 UTC
