### ISSUE TITLE
verbose flag got why too many `Expire ... (transfer [internal pointer to ...])` verbose lines?

### ISSUE THREAD

**Issue by tx0c** [curl/curl#4083] opened 2019-07-01 16:33 UTC
### I did this

    $ curl -v .../           # any url

it's showing too many lines of `Expire in 0/1 ms for x (transfer [pointer to ...])`, I don't understand why this maybe for curl internal debugging showing up; I'd like to show a parameter to show same verbose as before (prior to 7.50)

```
* Expire in 0 ms for 6 (transfer 0x55a76012b690)
* Expire in 1 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 1 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 1 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 1 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 1 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 1 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 1 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 1 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 1 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 1 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 1 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 1 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
* Expire in 0 ms for 1 (transfer 0x55a76012b690)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55a76012b690)
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /databases HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.0
> Accept: */*
[...]
```

### I expected the following

with verbose request headers and response headers and body, only

### curl/libcurl version

[curl -V output]

```console
➸ curl -V
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1b zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.8.6/openssl/zlib nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

### operating system
Linux Ubuntu19.04, while also reproduced on latest Fedora, and other Linux running in Cloud, it's more of a problem of newer curl version; prior to curl 7.50 did not have the problem

**Comment by bagder** [comment] 2019-07-01 16:54
Duplicate of #3558, fixed since long.

**Closed by bagder** 2019-07-01 16:54 UTC
