### ISSUE TITLE
Build: "libs available at link-time are not available run-time" with --disabled-shared

### ISSUE THREAD

**Issue by dgdy9hvz** [curl/curl#2287] opened 2018-02-05 08:48 UTC
### I did this

The current directory is the parent directory of
"curl-7.58.0", to which "curl-7.58.0.tar.gz" expanded.

    confOp="--enable-static --disable-shared"
    confOp+=" --without-ssl --with-mbedtls=/opt/mbedtls"
    confOp+=" --without-zlib --disable-ldap"
    
    mkdir curl-7.58.0-build
    cd curl-7.58.0-build
    
    ../curl-7.58.0/configure $confOp

MbedTLS had been built statically with the shared option disabled.
Only the static libraries of MbedTLS had been installed, which are "libmbedcrypto.a", "libmbedx509.a" and "libmbedtls.a".  The shared libraries (*.dylib) of MbedTLS had not been installed.

### I expected the following
The configure script completes successfully and creates "Makefile", in which the "static" is enabled, and the "shared" is disabled.

### what happened
The "Makefile" was not created.
The configure script was terminated with the following error messages:

    checking run-time libs availability... failed

    configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lmbedtls -lmbedx509 -lmbedcrypto 

These error messages do not make sense.  They imply that the "shared" is enabled, and that the option "--disable-shared" has been ignored.  If the "static" is enabled and the "shared" is disabled, then there should be no hassle of run-time availability.

### environment

curl-7.58.0
mbedtls-2.6.0
Mac OS X

------------------------------
### Another test

To show that the above failure is not the fault of MbedTLS, I ran another experiment with MbedTLS disabled and LDAP enabled.

### I did this (2)

The current directory is the parent directory of
"curl-7.58.0", to which "curl-7.58.0.tar.gz" expanded.

    confOp="--enable-static --disable-shared"
    confOp+=" --without-ssl"
    confOp+=" --without-zlib --enable-ldap"

    rm -r curl-7.58.0-build
    mkdir curl-7.58.0-build
    cd curl-7.58.0-build
    
    ../curl-7.58.0/configure $confOp

### I expected the following (2)
The configure script completes successfully and creates "Makefile", in which the "static" is enabled, and the "shared" is disabled.

### what happened (2)
The "Makefile" was not created.
The configure script was terminated with the following error messages:

    checking run-time libs availability... failed

    configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lldap

**Comment by bagder** [comment] 2018-02-05 09:53
The configure option `--disable-shared` makes the build *not* create a shared version of libcurl. It does not make the build automatically reject shared versions of the dependencies.

As always, configure failures are often figured out by reading  `config.log`. In this case, the problem is rather self-explanatory I think: the configure script detect that it could use a library (ie link fine with it) in the configure script, but when it tries to run a binary linked with the lib setup it fails. Because a library is probably not found at run-time that was found at link-time.

**Comment by bagder** [comment] 2018-02-15 09:43
Nothing further in ten days in spite of immediate response to issue. No noticeable bug in report. Closing.

**Closed by bagder** 2018-02-15 09:43 UTC
Labels: build

**Comment by dgdy9hvz** [comment] 2018-03-01 00:25
Your comment was a very helpful hint.  I can successfully build it now, after tweaking options for the configure script.  Thanks a lot!
