### ISSUE TITLE
Test harness can't run tasklist process on Windows

### ISSUE THREAD

**Issue by dfandrich** [curl/curl#11009] opened 2023-04-22 18:41 UTC
This [Cirrus CI / Windows 64-bit static/release Schannel/SSPI/WinIDN/libssh2 build](https://github.com/curl/curl/pull/11008/checks?check_run_id=12933222618) ended with this error:

```
test 1236...[[] globbing overflowing the range counter]
-------e--- OK (919 out of 1585, remaining: 08:00, took 0.165s, duration: 11:03)
test 1237...[URL with 1000+ letter user name + password]
--pd---e--- OK (920 out of 1585, remaining: 07:59, took 0.184s, duration: 11:03)
test 1238...[slow TFTP retrieve cancel due to -Y and -y]
Warning: server logs lock timeout (2 seconds) expired
make: *** [Makefile:1741: test-ci] Terminated

C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build>if 3840 NEQ 0 exit /b 3840 
Can't exec "/bin/sh": Permission denied at processhelp.pm line 122.

Exit status: 3840
```
processhelp.pm line 122 is in `pidexists`:
```
my $result = `tasklist -fi \"$filter\" 2>nul`;
```
Does this mean that backticks in perl won't work without a Bourne shell available, or is it something else? I'm pretty sure other uses of backticks are working. Or is this just Windows' way of saying `tasklist: command not found`? If that's it, what's the right way of doing this on this (or all) Windows versions?

**Comment by jay** [comment] 2023-04-23 07:48
tasklist should always work, I don't know why it would say permission denied, and if that error means it really can't run it or it runs it and it can't write. NUL (or nul) is the Windows null device. In msys (or cygwin) shell you would use /dev/null and not nul. nul is for native shells. In msys 2>nul writes to a file 'nul'. Still, it would not show permission denied. @mback2k

**Comment by gvanem** [comment] 2023-04-23 10:08
> `tasklist -fi ...`

A typo? I think you mean `taskkill`?

```
c:\Windows\System32\tasklist.exe /?
Description:
    This tool displays a list of currently running processes on
    either a local or remote machine.

c:\Windows\System32\taskkill.exe /?
Description:
   This tool is used to terminate tasks by process id (PID) or image name.
```

**Comment by dfandrich** [comment] 2023-04-24 17:55
This particular function is calling `tasklist` to determine if the given if the process is still alive, so it can kill it later. The issue title is misleading that way—I'll try to improve it.

**Comment by bagder** [comment] 2023-07-31 06:59
What is the actual impact of this problem? It seems this risks to just linger here...

**Comment by mback2k** [comment] 2023-08-12 18:41
For some tests it is necessary to kill the servers and launch new ones or stop other stuck test processes. So, not being able to kill processes can lead to the following tests failing.

**Comment by bagder** [comment] 2023-08-17 15:53
ok, but do we actually suffer much from this? This bug was filed a long time ago, nobody is working on it and yet we run tests on Windows many times every day...

**Comment by bagder** [comment] 2024-02-10 17:28
Closing, nothing to act on here.

**Closed by bagder** 2024-02-10 17:28 UTC
Labels: tests, Windows

**Comment by vszakats** [comment] 2024-09-16 20:58
Sorry for popping into this sleeping thread, but I was wondering what is the purpose of the `tasklist` call before calling `taskkill`?

I could be missing something, but could it be safe to just kill the PID without checking if it exists? If the PID doesn't exist, kill becomes a no-op, or?

As for `taskkill`, what is the reason for not using Perl's built-in [`kill()`](https://perldoc.perl.org/perlport#kill) function, or the Windows specific `Win32::Process::KillProcess()` from the [`Win32::Procss`](https://metacpan.org/release/JDB/Win32-Process-0.16/view/Process.pm) package?

This came up while trying to get closer to the root cause for flaky issues in Windows tests. One of them is failing to invoke `taskkill`, due to `Win32 error 1114 Can't fork`: https://github.com/curl/curl/discussions/14854#discussion-7165915

I figure if there is a way to avoid calling an external application for these tasks, it might help fixing the above and make the process more efficient.

**Comment by mback2k** [comment] 2024-09-17 19:00
> Sorry for popping into this sleeping thread, but I was wondering what is the purpose of the `tasklist` call before calling `taskkill`?
> 
> I could be missing something, but could it be safe to just kill the PID without checking if it exists? If the PID doesn't exist, kill becomes a no-op, or?

I think `tasklist.exe` before `taskkill.exe` is just a best practive. Ask/check before you shoot/kill, right?

> As for `taskkill`, what is the reason for not using Perl's built-in [`kill()`](https://perldoc.perl.org/perlport#kill) function, or the Windows specific `Win32::Process::KillProcess()` from the [`Win32::Process`](https://metacpan.org/release/JDB/Win32-Process-0.16/view/Process.pm) package?

The commands are used from an msys-based Perl (see `if($^O ne 'MSWin32') {`) handling Windows-native processes. Win32 package is not installed there by default and cannot access Win32-native processes from the emulated Unix environment. On Win32-native Perl you could probably use the native functions or Win32 package if it were installed.

> This came up while trying to get closer to the root cause for flaky issues in Windows tests. One of them is failing to invoke `taskkill`, due to `Win32 error 1114 Can't fork`: [#14854 (comment)](https://github.com/curl/curl/discussions/14854#discussion-7165915)
> 
> I figure if there is a way to avoid calling an external application for these tasks, it might help fixing the above and make the process more efficient.

I think this error is a symptom of some other bigger issue, but not the root cause here.

**Comment by mback2k** [comment] 2024-09-17 19:04
Also, Win32-based Perl emulates kill not as expected by pidterm and pidkill, therefore I added this to the test servers:
https://github.com/curl/curl/blob/210cf7cd9d839c55af8bac8e11d7404641be1c49/tests/server/util.c#L584-L590

**Comment by vszakats** [comment] 2024-09-17 21:15
@mback2k Thanks for jumping in!

> > Sorry for popping into this sleeping thread, but I was wondering what is the purpose of the `tasklist` call before calling `taskkill`?
> > I could be missing something, but could it be safe to just kill the PID without checking if it exists? If the PID doesn't exist, kill becomes a no-op, or?
> 
> I think `tasklist.exe` before `taskkill.exe` is just a best practive. Ask/check before you shoot/kill, right?

Fair enough!

But, is it serving a purpose in this particular case? Speaking of a parallel env, it's a chance for race conditions (though likely nothing of concern in this particular scenario). Is there an evidence that `taskkill` can do harm when asked to kill a non-existing process? According to local tests, `taskkill` returns 128 and shows this error when asked to kill a non-existing PID:
```
ERROR: The process "123456" not found.
```

Due to the cost (and unreliability) of external calls on Windows, unless a strong reason, would it be better to drop it, to lessen the strain on the machine and make it more efficient?

> > As for `taskkill`, what is the reason for not using Perl's built-in [`kill()`](https://perldoc.perl.org/perlport#kill) function, or the Windows specific `Win32::Process::KillProcess()` from the [`Win32::Process`](https://metacpan.org/release/JDB/Win32-Process-0.16/view/Process.pm) package?
> 
> The commands are used from an msys-based Perl (see `if($^O ne 'MSWin32') {`) handling Windows-native processes. Win32 package is not installed there by default and cannot access Win32-native processes from the emulated Unix environment. On Win32-native Perl you could probably use the native functions or Win32 package if it were installed.

Indeed, all jobs use MSYS2 Perl.

According to a quick test, `Win32::` is available also on MSYS2 Perl. `runtests.pl` already uses `Win32::Sleep()`.

The GHA runner offers Strawberry Perl, too, where `$^O` = `MSWin32`, so it's native. (AppVeyor CI Windows 2019/22 also has it, though we don't run tests there anymore.)

`Win32::Process` on the other hand is missing from MSYS2 (I'm not sure if it's installable, there is no internet in my broken Windows VM.), but Strawberry Perl has it by default. There is also `Win32::Process::List()` which is missing from both, but possible installable? That could potentially replace `tasklist`.

I wonder how to install Perl packages for MSYS2 / Strawberry Perl, could that be possible in CI?

> > This came up while trying to get closer to the root cause for flaky issues in Windows tests. One of them is failing to invoke `taskkill`, due to `Win32 error 1114 Can't fork`: [#14854 (comment)](https://github.com/curl/curl/discussions/14854#discussion-7165915)
> > I figure if there is a way to avoid calling an external application for these tasks, it might help fixing the above and make the process more efficient.
> 
> I think this error is a symptom of some other bigger issue, but not the root cause here.

It's possible. The internet is silent about this. The only thing I've found is two long, old, Git for Windows threads, but those were 32-bit-specific. Finding the root cause would be nice, but this looks like a little bit impossible task at this point. Based on mere hunch I think what we're seeing is the result of multiple issues, not a single big one. Either way, I figure until we find something big, any incremental improvement could be useful, if they help stabilizing jobs.

**Comment by vszakats** [comment] 2024-09-17 21:48
> Also, Win32-based Perl emulates kill not as expected by pidterm and pidkill, therefore I added this to the test servers:
> 
> https://github.com/curl/curl/blob/210cf7cd9d839c55af8bac8e11d7404641be1c49/tests/server/util.c#L584-L590

Maybe `Win32::Process::KillProcess()` could help us here? (via native Perl, or if installable for MSYS2?)

The code could check what's available and fall back to `taskkill`, to not make extra packages a hard requirement.

**Comment by vszakats** [comment] 2024-09-18 12:43
> But, is it serving a purpose in this particular case? Speaking of a parallel env, it's a chance for race conditions (though likely nothing of concern in this particular scenario). Is there an evidence that `taskkill` can do harm when asked to kill a non-existing process? According to local tests, `taskkill` returns 128 and shows this error when asked to kill a non-existing PID:
> 
> ```
> ERROR: The process "123456" not found.
> ```

Minor correction: There are at least two ways of calling `taskkill` to do this, the above test was done with `-pid <pid>`. `runtests.pl` does it with `-fi 'PID eq <pid>', in which case `taskkill` returns 0 and there is no error message, meaning it behaves the way a successfull kill does. Either way, it doesn't matter because the code is not using result of the kill.
