### ISSUE TITLE
Deprecated API usage in system_win32.c

### ISSUE THREAD

**Issue by FuccDucc** [curl/curl#4995] opened 2020-02-28 02:55 UTC
The current version of cURL is using a deprecated Windows API function `GetVersionEx` at this location: [system_win32.c @ 226](https://github.com/curl/curl/blob/05b1b3508535bfe1fe6c8f76e7e8ddbda6f7b7d6/lib/system_win32.c#L226)

Is this really neccesary? For increased reliability, refactoring it using the replacement, [Version Helper Functions](https://docs.microsoft.com/en-gb/windows/win32/sysinfo/version-helper-apis), sounds like a good idea.

**Comment by jay** [comment] 2020-02-28 04:13
VerifyVersionInfo is used when available. I don't see the problem.

/cc @captain-caveman2k

**Comment by FuccDucc** [comment] 2020-02-28 19:34
> VerifyVersionInfo is used when available. I don't see the problem.

Well, let me reverse the question.

This usage causes a compiler warning in projects that use cURL.

Why would you keep using a deprecated function? Why would you use it when a replacement (or alternative) is available, when using the deprecated function is also unnecesary, since all old Windows versions support the replacement. Without a reason not to upgrade it. Pro's versus cons.

**Comment by jay** [comment] 2020-02-28 20:10
> This usage causes a compiler warning in projects that use cURL.

What is the warning, how are you building curl and what are you using to build it?

> Why would you keep using a deprecated function?

Because not all build systems or targets may support the replacement function.

**Comment by FuccDucc** [comment] 2020-02-28 22:38
> What is the warning, how are you building curl and what are you using to build it?

All modern versions of Visual Studio, for example, give a deprecation warning.

> Because not all build systems or targets may support the replacement function.

Yes they do, GetVersionEx is a Windows API function (talking about targets) and the replacement, like I said, supports all old versions of Windows. In fact, the behavior on newer OS has been

Since it appears no one understands anything, maybe it's better to go and read this article: [https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversionexa](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversionexa)

It is deprecated. The following description matters to understand the pro's and cons (as I said before, you don't want to risk unexpected behavior in the future for no good reason right?):

> [GetVersionEx may be altered or unavailable for releases after Windows 8.1. Instead, use the Version Helper functions]
With the release of Windows 8.1, the behavior of the GetVersionEx API has changed in the value it will return for the operating system version

**Comment by jay** [comment] 2020-02-28 22:47
VerifyVersionInfo should be used when available. Please tell us:

What is the warning, how are you building curl and what are you using to build it?

**Comment by bagder** [comment] 2020-02-28 23:00
> Since it appears no one understands anything

I think it is you who misses the point: the code tries to use the right function already and we'd appreciate if you helped us figure out why it doesn't!

**Comment by captain-caveman2k** [comment] 2020-02-29 02:23
I've only just seen this - so my apologies for jumping in late.

The idea with #if block at line [218](https://github.com/curl/curl/blob/05b1b3508535bfe1fe6c8f76e7e8ddbda6f7b7d6/lib/system_win32.c#L218) is that `GetVersionEx()` should only be used on Non-Windows NT based versions of Windows (i.e. Windows 9x / ME and versions of NT earlier than Windows 2000, ie Windows NT 3.5x and 4.0) where a) it isn't deprecated and b) `VerifyVersionInfo()` isn't available. Anything newer should be using `VerifyVersionInfo()` as seen at line [345](https://github.com/curl/curl/blob/05b1b3508535bfe1fe6c8f76e7e8ddbda6f7b7d6/lib/system_win32.c#L345).

It would seem that for some reason this #if block isn't working as intended and I, like my colleagues, would like to try and understand why.

- Where was the source code/libcurl API obtained from (Official tarball/zip, or Github, etc...)?
- Are you using libcurl with the default config-win32.h?

**Comment by bagder** [comment] 2020-03-05 11:52
No feedback, closing.

**Closed by bagder** 2020-03-05 11:52 UTC
Labels: Windows, needs-info-or-update, not-a-bug
