### ISSUE TITLE
Static compiled curl report "Couldn't resolve host"

### ISSUE THREAD

**Issue by ayanamist** [curl/curl#796] opened 2016-05-11 09:53 UTC
### I did this
static compile curl. ref #503 
`./buildconf`
`LDFLAGS="-static" PKG_CONFIG="pkg-config --static" ./configure --with-nghttp2=/usr/local --with-ssl --disable-shared --enable-static`
`make -j4 V=1 curl_LDFLAGS=-all-static`
`sudo make install`
then execute
`curl -Iv http://www.example.com`

### I expected the following
It access sucessfully.

### curl/libcurl version
git HEAD 856baf5

[curl -V output perhaps?]
```
* getaddrinfo(3) failed for www.example.com:80
* Couldn't resolve host 'www.example.com'
* Closing connection 0
curl: (6) Couldn't resolve host 'www.example.com'
```

### operating system
Ubuntu 14.04

### addtional
strace output
```
execve("/usr/local/bin/curl", ["curl", "-vI", "http://www.example.com/"], [/* 73 vars */]) = 0
uname({sys="Linux", node="ubuntu", ...}) = 0
brk(0)                                  = 0x243d000
brk(0x243e1c0)                          = 0x243e1c0
arch_prctl(ARCH_SET_FS, 0x243d880)      = 0
readlink("/proc/self/exe", "/usr/local/bin/curl", 4096) = 19
brk(0x245f1c0)                          = 0x245f1c0
brk(0x2460000)                          = 0x2460000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
pipe([3, 4])                            = 0
close(3)                                = 0
close(4)                                = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x585470}, {SIG_DFL, [], 0}, 8) = 0
open("/usr/lib/ssl/openssl.cnf", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=10835, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f46cf9cd000
read(3, "#\n# OpenSSL example configuratio"..., 4096) = 4096
read(3, "Netscape crash on BMPStrings or "..., 4096) = 4096
read(3, " this to avoid interpreting an e"..., 4096) = 2643
read(3, "", 4096)                       = 0
close(3)                                = 0
munmap(0x7f46cf9cd000, 4096)            = 0
brk(0x2481000)                          = 0x2481000
open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=7216688, ...}) = 0
mmap(NULL, 7216688, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f46cf2ec000
close(3)                                = 0
open("/home/ayanamist/.curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
ioctl(1, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B38400 opost isig icanon echo ...}) = 0
clock_gettime(CLOCK_MONOTONIC, {14496, 78541165}) = 0
clock_gettime(CLOCK_MONOTONIC, {14496, 78606234}) = 0
rt_sigaction(SIGPIPE, NULL, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x585470}, 8) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x585470}, NULL, 8) = 0
clock_gettime(CLOCK_MONOTONIC, {14496, 78700733}) = 0
clock_gettime(CLOCK_MONOTONIC, {14496, 78728939}) = 0
clock_gettime(CLOCK_MONOTONIC, {14496, 78757909}) = 0
clock_gettime(CLOCK_MONOTONIC, {14496, 78824447}) = 0
rt_sigaction(SIGPIPE, NULL, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x585470}, 8) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x585470}, NULL, 8) = 0
clock_gettime(CLOCK_MONOTONIC, {14496, 79001494}) = 0
clock_gettime(CLOCK_MONOTONIC, {14496, 79132125}) = 0
clock_gettime(CLOCK_MONOTONIC, {14496, 79187804}) = 0
clock_gettime(CLOCK_MONOTONIC, {14496, 79247772}) = 0
clock_gettime(CLOCK_MONOTONIC, {14496, 79326095}) = 0
clock_gettime(CLOCK_MONOTONIC, {14496, 79394540}) = 0
clock_gettime(CLOCK_MONOTONIC, {14496, 79438915}) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigaction(SIGALRM, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGALRM, {0x420240, [], SA_RESTORER, 0x585470}, NULL, 8) = 0
alarm(300)                              = 0
socket(PF_INET6, SOCK_DGRAM, IPPROTO_IP) = 3
close(3)                                = 0
socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
close(3)                                = 0
socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
close(3)                                = 0
open("/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=507, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f46cf2eb000
read(3, "# /etc/nsswitch.conf\n#\n# Example"..., 4096) = 507
read(3, "", 4096)                       = 0
close(3)                                = 0
munmap(0x7f46cf2eb000, 4096)            = 0
open("/etc/host.conf", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=92, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f46cf2eb000
read(3, "# The \"order\" line is only used "..., 4096) = 92
read(3, "", 4096)                       = 0
close(3)                                = 0
munmap(0x7f46cf2eb000, 4096)            = 0
getpid()                                = 61805
open("/etc/resolv.conf", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=202, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f46cf2eb000
read(3, "# Dynamic resolv.conf(5) file fo"..., 4096) = 202
read(3, "", 4096)                       = 0
close(3)                                = 0
munmap(0x7f46cf2eb000, 4096)            = 0
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=87840, ...}) = 0
mmap(NULL, 87840, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f46cf2d6000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
munmap(0x7f46cf2d6000, 87840)           = 0
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=87840, ...}) = 0
mmap(NULL, 87840, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f46cf2d6000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
munmap(0x7f46cf2d6000, 87840)           = 0
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=87840, ...}) = 0
mmap(NULL, 87840, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f46cf2d6000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
munmap(0x7f46cf2d6000, 87840)           = 0
write(2, "*", 1*)                        = 1
write(2, " ", 1 )                        = 1
write(2, "getaddrinfo(3) failed for www.ex"..., 45getaddrinfo(3) failed for www.example.com:80
) = 45
alarm(0)                                = 300
rt_sigaction(SIGALRM, {SIG_DFL, [], SA_RESTORER, 0x585470}, NULL, 8) = 0
write(2, "*", 1*)                        = 1
write(2, " ", 1 )                        = 1
write(2, "Couldn't resolve host 'www.examp"..., 40Couldn't resolve host 'www.example.com'
) = 40
time([1462960352])                      = 1462960352
write(2, "*", 1*)                        = 1
write(2, " ", 1 )                        = 1
write(2, "Closing connection 0\n", 21Closing connection 0
)  = 21
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x585470}, NULL, 8) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x585470}, NULL, 8) = 0
write(2, "c", 1c)                        = 1
write(2, "u", 1u)                        = 1
write(2, "r", 1r)                        = 1
write(2, "l", 1l)                        = 1
write(2, ":", 1:)                        = 1
write(2, " ", 1 )                        = 1
write(2, "(", 1()                        = 1
write(2, "6", 16)                        = 1
write(2, ")", 1))                        = 1
write(2, " ", 1 )                        = 1
write(2, "C", 1C)                        = 1
write(2, "o", 1o)                        = 1
write(2, "u", 1u)                        = 1
write(2, "l", 1l)                        = 1
write(2, "d", 1d)                        = 1
write(2, "n", 1n)                        = 1
write(2, "'", 1')                        = 1
write(2, "t", 1t)                        = 1
write(2, " ", 1 )                        = 1
write(2, "r", 1r)                        = 1
write(2, "e", 1e)                        = 1
write(2, "s", 1s)                        = 1
write(2, "o", 1o)                        = 1
write(2, "l", 1l)                        = 1
write(2, "v", 1v)                        = 1
write(2, "e", 1e)                        = 1
write(2, " ", 1 )                        = 1
write(2, "h", 1h)                        = 1
write(2, "o", 1o)                        = 1
write(2, "s", 1s)                        = 1
write(2, "t", 1t)                        = 1
write(2, " ", 1 )                        = 1
write(2, "'", 1')                        = 1
write(2, "w", 1w)                        = 1
write(2, "w", 1w)                        = 1
write(2, "w", 1w)                        = 1
write(2, ".", 1.)                        = 1
write(2, "e", 1e)                        = 1
write(2, "x", 1x)                        = 1
write(2, "a", 1a)                        = 1
write(2, "m", 1m)                        = 1
write(2, "p", 1p)                        = 1
write(2, "l", 1l)                        = 1
write(2, "e", 1e)                        = 1
write(2, ".", 1.)                        = 1
write(2, "c", 1c)                        = 1
write(2, "o", 1o)                        = 1
write(2, "m", 1m)                        = 1
write(2, "'", 1')                        = 1
write(2, "\n", 1
)                       = 1
rt_sigaction(SIGPIPE, NULL, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x585470}, 8) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x585470}, NULL, 8) = 0
rt_sigaction(SIGPIPE, NULL, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x585470}, 8) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x585470}, NULL, 8) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x585470}, NULL, 8) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x585470}, NULL, 8) = 0
exit_group(6)                           = ?
+++ exited with 6 +++
```

**Comment by jay** [comment] 2016-05-11 19:56
This doesn't appear to be a curl problem, what makes you think it is?

**Comment by ayanamist** [comment] 2016-05-12 00:50
Because if i don't use static compile but dynamic linked, it works on the same machine, so it caused by static compile. If it's not the fault of curl, would you do a favor to tell me which part i should consider and digest?

**Comment by bagder** [comment] 2016-05-12 14:35
Cannot reproduce. In my case, I used these exact command lines using the current git master:

    LDFLAGS="-static" PKG_CONFIG="pkg-config --static" ./configure --with-nghttp2=$HOME/build-nghttp2 --with-ssl --disable-shared --enable-static --without-libssh2
    make -j curl_LDFLAGS=-all-static

This of course causes a few warnings at link time shown below that we have to ignore if want to proceed. The result:

    $ ldd src/curl
        not a dynamic executable
    $ ls -l src/curl
    -rwxr-xr-x 1 daniel daniel 4805824 maj 12 16:30 src/curl
    $ ./src/curl -V
    curl 7.49.0-DEV (x86_64-pc-linux-gnu) libcurl/7.49.0-DEV OpenSSL/1.0.2h zlib/1.2.8 libidn/1.32 nghttp2/1.11.0-DEV
    Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
    Features: IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets 


And it works fine to get both `www.example.com` and `https://www.example.com` for me.

~~~~
(.text+0x11): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
tool_homedir.c:(.text+0x60): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
netrc.c:(.text+0x393): warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
curl_addrinfo.c:(.text+0x60): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

**Comment by jay** [comment] 2016-05-12 20:16
I could reproduce in Ubuntu 14 x64 LTS but then it went away. I don't know what's causing it yet but maybe it's something to do with that required shared libraries warning. Weird!

~~~
owner@ubuntu1404-x64-vm:~/curltest/curl$ ./src/curl -V
curl 7.49.0-DEV (x86_64-unknown-linux-gnu) libcurl/7.49.0-DEV OpenSSL/1.0.2h zlib/1.2.8 libidn/1.28 nghttp2/1.10.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets 
owner@ubuntu1404-x64-vm:~/curltest/curl$ ./src/curl -Iv http://www.example.com
* Rebuilt URL to: http://www.example.com/
* getaddrinfo(3) failed for www.example.com:80
* Couldn't resolve host 'www.example.com'
* Closing connection 0
curl: (6) Couldn't resolve host 'www.example.com'
~~~

I tried disabling ipv6 but there was no change. getaddrinfo is returning EAI_NODATA (-5) for hostnames. If I connect to test.com via ip:
./src/curl -L -Iv http://69.172.200.235
it works and then I get EAI_SYSTEM on the redirect to www.test.com
~~~
* Connection #0 to host 69.172.200.235 left intact
* Issue another request to this URL: 'https://www.test.com/'
-11
errno: 115, Operation now in progress
* Curl_ipv4_resolve_r failed for www.test.com
* Couldn't resolve host 'www.test.com'
* Closing connection 1
curl: (6) Couldn't resolve host 'www.test.com'
~~~
I thought maybe it was a timing issue so I tried to sleep but that didn't help. It doesn't make any sense.

This was all reproducible. I sanity checked occasionally that curl 7.48 dynamically linked was working during that time. After all this I came back about 15 minutes later and it worked. Fortunately it's a VM and I have a snapshot of before I tried this so maybe if I go back I can reproduce again and figure it out. Any ideas?

**Comment by jay** [comment] 2016-05-12 20:54
The reason it appeared to work is because I ran `sudo make install` without `curl_LDFLAGS=-all-static`, the safe way is `sudo make install curl_LDFLAGS=-all-static`. I had modified hostip4.c without running `make -j4 V=1 curl_LDFLAGS=-all-static` again and so `make install` first rebuilt hostip4 and then curl without static. So what I thought was a static build was not fully. None of this explains why static builds don't work.

**Comment by bagder** [comment] 2016-05-12 21:19
Really odd. The warning does say "Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking". Could it then be that you don't have the shared libraries **from the glibc version** when you run it?

I do still believe this isn't a curl problem though. It's a linking/system problem.

**Comment by jay** [comment] 2016-05-13 05:39
> I do still believe this isn't a curl problem though. It's a linking/system problem.

Yeah I think you're right. I found these:
https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/134400
https://gcc.gnu.org/ml/gcc-help/2010-04/msg00302.html
http://stackoverflow.com/questions/3430400/linux-static-linking-is-dead
http://stackoverflow.com/questions/8140439/why-would-it-be-impossible-to-fully-statically-link-an-application


I made a simple program using getaddrinfo and I get the same errors.
~~~c
#include <stdio.h>
#include <arpa/inet.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <errno.h>
#include <string.h>

int main(int argc, char *argv[]) {
  struct addrinfo *ai = NULL;
  struct addrinfo hints;
  char sbuf[12];
  char *sbufptr = NULL;
  int port;
  char *hostname;

  if(argc != 3) {
    printf("gai <hostname> <port|0>\n");
    return 1;
  }

  hostname = argv[1];
  port = atoi(argv[2]);

  memset(&hints, 0, sizeof(hints));
  hints.ai_family = PF_INET;
  hints.ai_socktype = SOCK_STREAM;
  if(port) {
    snprintf(sbuf, sizeof(sbuf), "%d", port);
    sbufptr = sbuf;
  }
  int x = getaddrinfo(hostname, sbufptr, &hints, &ai);
  printf("getaddrinfo returned: %d (%s)\n", x, x ? gai_strerror(x) : "Success");
  if(x == EAI_SYSTEM)
    printf("errno: %d (%s)\n", errno, strerror(errno));

  return 0;
}
~~~


If I change the gcc line and remove -static but turn on static temporarily (-Wl,-Bstatic -lssl -lcrypto -lz -Wl,-Bdynamic) for all libraries on the command line (except dl) and then turn it back to dynamic it will work but then it isn't fully static:
~~~
gcc -Wl,--verbose  -O2 -Wno-system-headers -o curl curl-slist_wc.o curl-tool_binmode.o curl-tool_bname.o curl-tool_cb_dbg.o curl-tool_cb_hdr.o curl-tool_cb_prg.o curl-tool_cb_rea.o curl-tool_cb_see.o curl-tool_cb_wrt.o curl-tool_cfgable.o curl-tool_convert.o curl-tool_dirhie.o curl-tool_doswin.o curl-tool_easysrc.o curl-tool_formparse.o curl-tool_getparam.o curl-tool_getpass.o curl-tool_help.o curl-tool_helpers.o curl-tool_homedir.o curl-tool_hugehelp.o curl-tool_libinfo.o curl-tool_main.o curl-tool_metalink.o curl-tool_mfiles.o curl-tool_msgs.o curl-tool_operate.o curl-tool_operhlp.o curl-tool_panykey.o curl-tool_paramhlp.o curl-tool_parsecfg.o curl-tool_strdup.o curl-tool_setopt.o curl-tool_sleep.o curl-tool_urlglob.o curl-tool_util.o curl-tool_vms.o curl-tool_writeenv.o curl-tool_writeout.o curl-tool_xattr.o ../lib/curl-strtoofft.o ../lib/curl-rawstr.o ../lib/curl-nonblock.o ../lib/curl-warnless.o  -L/usr/local/ssl/lib -L/usr/local/lib ../lib/.libs/libcurl.a /usr/local/lib/libnghttp2.a -Wl,-Bstatic -lssl -lcrypto -lz -Wl,-Bdynamic -ldl 
~~~
~~~
owner@ubuntu1404-x64-vm:~/curltest/curl/src$ ldd curl
	linux-vdso.so.1 =>  (0x00007ffc7dfa9000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdb51810000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdb5144b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fdb51a14000)
~~~

**Comment by bagder** [comment] 2016-05-15 09:52
Since this problem is reproducible completely without curl/libcurl, I don't think it is a curl issue. I'd suggest taking it to your distribution's bug tracker and their gcc/glibc/nss (the nss that's part of the name resolver, not the crypto library with the same name) team to see what they have to say about it.

**Closed by bagder** 2016-05-15 09:52 UTC
Labels: build
