### ISSUE TITLE
Curl is not able to close connection with LDAPs

### ISSUE THREAD

**Issue by ic-ruben-burgue** [curl/curl#11863] opened 2023-09-15 14:07 UTC
### I did this

In curl>=8.2.0:

```
curl -vvv ldaps://HOST:PORT -k
* processing: ldaps://HOST:PORT
*   Trying HOST:PORT...
* Connected to HOST (HOST_IP) port PORT
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* Server certificate:
	[...]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* LDAP local: ldaps://HOST:PORT/
DN:
	objectClass: CLASS
	objectClass: DS

	startupUUID: UUID

	startTime: 20230914123241Z


[HANGS for long time]

* Connection #0 to host HOST left intact
```

### I expected the following

in curl<8.2.0:

```
curl -vvv ldaps://HOST:PORT -k
*   Trying HOST:PORT...
* Connected to HOST (HOST_IP) port PORT (#0)
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* Server certificate:
	[...]
* LDAP local: LDAP Vendor = OpenLDAP ; LDAP Version = 20516
* LDAP local: ldaps://HOST:PORT/
* LDAP local: trying to establish encrypted connection
DN:
	objectClass: CLASS
	objectClass: DS

	startupUUID: UUID

	startTime: 20230914123241Z

* Closing connection 0
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (OUT), TLS alert, close notify (256):
```

### curl/libcurl version

```
Seen in curl:8.2.0, curl:8.2.1 and curl:8.3.0
curl:8.1.2 is working as expected.
```

### operating system

`Linux (at least Ubuntu)`

### Notes
`LDAP is working without any issue. It's only affecting LDAPs.`

**Comment by bagder** [comment] 2023-09-16 16:30
and not a single change was done to lib/openldap.c in the mean time...

**Comment by bagder** [comment] 2023-09-19 08:34
LDAP(S) is one of those protocol sets in curl that is lacking an internal test server, making it fragile.

I don't even know of a public LDAPS server to test against. Anyone?

**Comment by jzakrzewski** [comment] 2023-09-19 09:15
Could this be of use: https://hub.docker.com/r/pgarrett/ldap-alpine ?

**Comment by dfandrich** [comment] 2023-09-19 10:21
Here's a URL on a public server:
ldaps://ldap.udel.edu/ou=people,o=udel.edu??sub?(udUsernum=82515)

**Comment by gingerbeard-man** [comment] 2023-10-11 16:03
> and not a single change was done to lib/openldap.c in the mean time...

I've ended up here due to an issue we are having with LDAPS after SUSE upgraded SLES 12's curl from 7.60 to 8.0.  Our problem is a little bit different but I believe in both cases the changes in behaviour are related to #11374.

During my analysis so far I noted that the messages `LDAP local: LDAP Vendor ...` and `LDAP local: trying to establish encrypted connection` are printed only by lib/ldap.c.  They do not exist in lib/openldap.c.  In our case curl 7.60 had been built with lib/openldap.c whereas curl 8.0 was built with lib/ldap.c due to the problem mentioned in the PR.  I still don't know why our use case fails with lib/ldap.c but if we can get SUSE to rebuild curl 8 with lib/openldap.c then it doesn't really matter.

Here it appears to be the opposite.  The expected behaviour of curl<8.2.0 indicates that lib/ldap.c is used due to the presence of the `LDAP local` messages.  I suggest that curl>=8.2.0 is now using lib/openldap.c instead and this is at least the cause for different behaviour.  There may still be some problem in lib/openldap.c but it was never triggered in the older versions due to fallback on lib/ldap.c.

**Comment by bagder** [comment] 2023-10-19 12:21
> Here's a URL on a public server: ldaps://ldap.udel.edu/ou=people,o=udel.edu??sub?(udUsernum=82515)

I can get this URL just fine with 8.4.0 on Linux.

**Comment by dfandrich** [comment] 2023-10-19 23:41
It works fine for me in 8.2.0 as well (openldap-2.4.57 on x86_64 Linux) on the test URL & supplied as well as plain ldaps://ldap.udel.edu/. Can you supply the URL to a server that shows this issue? And, when you say "hangs for a long time", how long is that? And have you checked that it's not just the server being slow?

**Comment by bagder** [comment] 2023-11-24 07:48
No additional info after a month+, closing.

**Closed by bagder** 2023-11-24 07:48 UTC
Labels: needs-info, LDAP

**Comment by ozancsl** [comment] 2023-12-22 11:52
I am having the same issue on Ubuntu 22.04. Curl package which is installed from ubuntu repos doesn't close after fetching query result. Compiled from the source 8.5.0 but unfortunately it stucks as well. It only happens with ldaps. Ldap is working well.

I also compiled `curl 8.5.0` library at `freebsd 13.2`, and it doesn't hang, ldaps just works fine there.

Can it be related with openssl version?

**Comment by jay** [comment] 2023-12-22 18:47
We need a way to reproduce and the `curl -V` version info. Also try running curl with -v for verbose mode.

**Comment by ozancsl** [comment] 2023-12-23 05:10
My setup:
- Curl client is used on `Ubuntu 22.04`.
- A microsoft active directory server is running at `172.16.43.167` on `Windows Server`. `636` is TLS port to the active directory.
- Curl client version is `8.5.0`, also tried bunch of `8.0+` versions and having the same issue with all of them.

The problem is simply, curl fetches the `ldaps` query result flawlessly but doesn't close the connection at the end, so it stays until the timeout duration is reached.

This problem doesn't occur if I use `ldap` (without `TLS`).

I compiled and tested `8.5.0` on `FreeBSD 13.2`. This issue doesn't occur there. I will attach a video to demonstrate the problem.

### Script used on the video
``` sh
#!/usr/bin/env bash

CURL=../../curl/build/src/curl

# LDAP_URL=ldap://127.0.0.1:33389

# Uncomment to use LDAPS
LDAP_URL=ldaps://172.16.43.167:636
BASE_DN=DC=corp,DC=sunnyvalley,DC=io

read  -p 'Enter username: ' LOGON_NAME
read -sp 'Enter password: ' PASSWD

# user -> ozanadmin@corp.sunnyvalley.io
# user -> corp.sunnyvalley.io\\ozanadmin
$CURL -V

$CURL   -v \
        --max-time 5 \
        --insecure \
        --user "${LOGON_NAME}:${PASSWD}" \
        "${LDAP_URL}/${BASE_DN}??sub?(|(userPrincipalName=${LOGON_NAME#*\\})(sAMAccountName=${LOGON_NAME#*\\}))"
```
### Output
``` Console
zanc@ozanc-dev:~/repo/engine-misc/ldap$ ./curl-sign-in-ad.sh 
Enter username: ozanadmin@corp.sunnyvalley.io
Enter password: curl 8.5.0-DEV (Linux) libcurl/8.5.0-DEV OpenSSL/3.0.2 zlib/1.2.11 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) OpenLDAP/2.5.16
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IDN IPv6 Largefile libz NTLM PSL SSL threadsafe TLS-SRP UnixSockets
*   Trying 172.16.43.167:636...
* Connected to 172.16.43.167 (172.16.43.167) port 636
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384 / secp384r1 / rsaEncryption
* Server certificate:
*  subject: CN=dc.corp.sunnyvalley.io
*  start date: Dec 21 13:35:59 2023 GMT
*  expire date: Dec 20 13:35:59 2024 GMT
*  issuer: DC=io; DC=sunnyvalley; DC=corp; CN=corp-DC-CA-1
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
*   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
* LDAP local: ldaps://172.16.43.167:636/DC=corp,DC=sunnyvalley,DC=io??sub?(|(userPrincipalName=ozanadmin@corp.sunnyvalley.io)(sAMAccountName=ozanadmin@corp.sunnyvalley.io))
DN: CN=Ozan Admin,OU=AdminS,DC=corp,DC=sunnyvalley,DC=io
        objectClass: top
        objectClass: person
        objectClass: organizationalPerson
        objectClass: user

        cn: Ozan Admin

        sn: Admin

        givenName: Ozan

        distinguishedName: CN=Ozan Admin,OU=AdminS,DC=corp,DC=sunnyvalley,DC=io

        instanceType: 4

        whenCreated: 20231221134931.0Z

        whenChanged: 20231222045540.0Z

        displayName: Ozan Admin

        uSNCreated: 49196

        memberOf: CN=Group Policy Creator Owners,CN=Users,DC=corp,DC=sunnyvalley,DC=io
        memberOf: CN=Domain Admins,CN=Users,DC=corp,DC=sunnyvalley,DC=io
        memberOf: CN=Enterprise Admins,CN=Users,DC=corp,DC=sunnyvalley,DC=io
        memberOf: CN=Schema Admins,CN=Users,DC=corp,DC=sunnyvalley,DC=io
        memberOf: CN=Remote Desktop Users,CN=Builtin,DC=corp,DC=sunnyvalley,DC=io
        memberOf: CN=Administrators,CN=Builtin,DC=corp,DC=sunnyvalley,DC=io

        uSNChanged: 49422

        name: Ozan Admin

        objectGUID:: vAzjGRFWaEC0pz1wqJ7kWw==

        userAccountControl: 66048

        badPwdCount: 0

        codePage: 0

        countryCode: 0

        badPasswordTime: 133477191309999559

        lastLogoff: 0

        lastLogon: 133477206211459558

        pwdLastSet: 133476401720319025

        primaryGroupID: 513

        objectSid:: AQUAAAAAAAUVAAAA6FkH+TIyOcvN3Xt3XwQAAA==

        adminCount: 1

        accountExpires: 9223372036854775807

        logonCount: 7

        sAMAccountName: ozanadmin

        sAMAccountType: 805306368

        userPrincipalName: ozanadmin@corp.sunnyvalley.io

        objectCategory: CN=Person,CN=Schema,CN=Configuration,DC=corp,DC=sunnyvalley,DC=io

        dSCorePropagationData: 20231221140012.0Z
        dSCorePropagationData: 20231221134959.0Z
        dSCorePropagationData: 16010101000000.0Z

        lastLogonTimestamp: 133476945409728752


* Operation timed out after 5001 milliseconds with 1610 bytes received
* Closing connection
* Send failure: Bad file descriptor
* Recv failure: Bad file descriptor
curl: (28) Operation timed out after 5001 milliseconds with 1610 bytes received
```

https://github.com/curl/curl/assets/133976781/c8f9b65e-ed07-40a1-924e-bee913bd5d54
