### ISSUE TITLE
curl 7.81.0 fails to configure on macos:  one or more libs available at link-time are not available run-time

### ISSUE THREAD

**Issue by mario-grgic** [curl/curl#8294] opened 2022-01-19 00:05 UTC
I am trying to compile curl 7.81.0 on macOS 10.15.7. I am using the following build script:

```
#!/bin/bash

tar xvf curl-7.81.0.tar.gz
cd curl-7.81.0

# configure curl
./configure --enable-optimize --enable-http --enable-ftp --enable-file --enable-ldap --enable-ldaps --enable-rtsp --enable-proxy --enable-dict --enable-telnet --enable-tftp --enable-pop3 --enable-imap --enable-smtp --enable-gopher --enable-manual --enable-ipv6 --enable-threaded-resolver --enable-crypto-auth --enable-tls-srp --enable-cookies --with-gssapi --with-spengo --with-nghttp2 --with-libssh2 --with-secure-transport --without-libidn2  --with-librtmp --without-libpsl --with-ssl --with-openssl

make -j $(nproc)
```
which fails to configure the build with the following error:

```
configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lnghttp2 -lidn2 -lrtmp -lz -lssl -lcrypto -lssh2 -L/usr/local/lib -lssh2 -lssl -lcrypto -lssl -lcrypto -lgssapi_krb5 -lresolv -lldap -lzstd  -lbrotlidec  -lz 
```

It turns out that both libssh2 and libidn2 are the cause of the above message. pkg-config correctly prints out library paths:

```
 pkg-config --libs libidn2
-L/usr/local/lib -lidn2

pkg-config --libs libssh2
-L/usr/local/lib -lssh2
```

I attempted to pass exact path to the libraries `--with-libidn2=/usr/local/lib`, which allows configure script to continue. 

This curl then builds, however you get a warning:

```
ld: warning: directory not found for option '-L/usr/local/lib/lib'
```

Looking at differences between curl 7.80.0 (which builds without issues) and 7.81.0, it looks like this is caused by changes in

`m4/curl-fuctions.m4` introduced in e39421cef

Fixing `curl-fuctions.m4` 

```
diff --git a/m4/curl-functions.m4 b/m4/curl-functions.m4
index 1a5954871..91bf3ffde 100644
--- a/m4/curl-functions.m4
+++ b/m4/curl-functions.m4
@@ -6515,7 +6515,6 @@ dnl changes contained within this macro.
 
 AC_DEFUN([CURL_RUN_IFELSE], [
    case $host_os in
-     darwin*) library_path_var=DYLD_LIBRARY_PATH ;;
      *)       library_path_var=LD_LIBRARY_PATH ;;
    esac
 ```
allows configure to work and to build correctly.

**Comment by dfandrich** [comment] 2022-01-19 00:35
This sounds like pr#8247

**Comment by bagder** [comment] 2022-01-19 10:49
Duplicate of #8229

**Closed by bagder** 2022-01-19 10:49 UTC
Labels: build
