### ISSUE TITLE
The lib1541 unit test fails on Ubuntu 18.04.4.

### ISSUE THREAD

**Issue by ladar** [curl/curl#5551] opened 2020-06-10 21:33 UTC
I ran `make test` and naively expected all of the test cases to pass. And for the most part, they did. The exception seems to be unit test 1541. The cURL, version is 7.70.1, and the operating system is Ubuntu 18.04.4. Note that everything works perfectly on my CentOS 6.10 development system.

The failure only seems to occur when the system is under heavy load, but the failure does occur consistently in this scenario. The build output provides the error message `lib1541 returned 134, when expecting 0` ... with 134 appearing to be the exit status, and a by product of the test program encountering a segmentation fault.

With significant effort, I was able to run the test manually atop `gdb` and capture a stack trace showing the error:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x0000155554aaa801 in __GI_abort () at abort.c:79
#2  0x00001555544fd9c2 in int_thread_release (hash=0x155553424990) at err.c:485
#3  0x00001555544fd6b7 in int_thread_del_item (d=<optimized out>) at err.c:547
#4  0x00001555544fe19d in ERR_remove_thread_state (id=<optimized out>) at err.c:1030
#5  0x00001555550e21fd in Curl_ossl_close_all (data=0x155544006728) at vtls/openssl.c:1427
#6  0x00001555550ea067 in Curl_ssl_close_all (data=0x155544006728) at vtls/vtls.c:522
#7  0x0000155555096f33 in Curl_close (datap=0x155544010e30) at url.c:366
#8  0x00001555550864ff in Curl_conncache_close_all_connections (connc=0x155544010de0) at conncache.c:563
#9  0x00001555550bb455 in curl_multi_cleanup (multi=0x155544010cf8) at multi.c:2436
#10 0x0000155555096eb6 in Curl_close (datap=0x155553424de8) at url.c:346
#11 0x000015555509308b in curl_easy_cleanup (data=0x0) at easy.c:737
#12 0x0000555555555a1f in run_thread (ptr=0x7fffffffd818) at lib1541.c:96
#13 0x0000155554e626db in start_thread (arg=0x155553425700) at pthread_create.c:463
#14 0x0000155554b8b88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
This was generated by running `gdb --eval-command=run --args sources/curl/tests/libtest/.libs/lib1541 http://127.0.0.1:46821/1` ... with the full output as follows:

```
make@dark:sources/curl/tests$ gdb --eval-command=run --args sources/curl/tests/libtest/.libs/lib1541 http://127.0.0.1:46821/1
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from sources/curl/tests/libtest/.libs/lib1541...done.
Starting program: sources/curl/tests/libtest/.libs/lib1541 http://127.0.0.1:46821/1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
URL: http://127.0.0.1:46821/1
[New Thread 0x155553626700 (LWP 9330)]
Thread 0, gets http://127.0.0.1:46821/1
[New Thread 0x155553425700 (LWP 9332)]
Thread 1, gets http://127.0.0.1:46Thread 0 transfer 0
821/1
Thread 1 transfer 0
Thread 1 transfer 1
T[New Thread 0x155553224700 (LWP 9333)]
hread 1 transfer 2
TThread 2, gets http://127.0.0.1:46821/1
Thread 1 trhread 0 traThrenasad 2fne transfrs e3fe
r 0
Tr 1
hread 1 transfer 4
Thread 0 transfer 2
Thread 1 transfer 5
Thread 0 transfer 3
Thread 1 transfer 6
Thread 0 transfer 4
[New Thread 0x155553023700 (LWP 9336)]
Thread 3, gets http://127.0.0.1:4682Thread1/1
Thread [New Thread 0x155552e22700 (LWP 9337)]
2 transfer 1
Thread 1 transfer 7
Thread 1 transfer 8
Thread 1 transfer 9
Thread 3 transfer 0
Thread 3 transfer 1
Thread 3 transfer 2
Thread 3 transfer 3
Thread 3 transfer 4
Thread 3 transfer 5
Thread 3 transfer 6
Thread 3 transfer 7
Thread 3 transfer 8
Thread 3 transfer 9
Thread 3 transfer 10
Thread 3 transfer 11
Thread 3 transfer 12
Thread 3 transfer 13
Thread 3 transfer 14
Thread 3 transfer 15
Thread 3 transfer 16
Thread 3 transfer 17
Thread 3 transfer 18
Thread 3 transfer 19
Thread 3 transfer 20
Thread 3 transfer 21
Thread 3 transfer 22
Thread 3 transfer 23
Thread 3 transfer 24
Thread 3 transfer 25
Thread 3 transfer 26
Thread 3 transfer 27
Thread 3 transfer 28
Thread 3 transfer 29
Thread 3 transfer 30
Thread 3 transfer 31
Thread 3 transfer 32
Thread 3 transfer 33
Thread 3 transfer 34
Thread 3 transfer 35
Thread 3 transfer 36
Thread 3 transfer 37
Thread 3 transfer 38
Thread 3 transfer 39
Thread 3 transfer 40
Thread 3 transfer 41
Thread 3 transfer 42
Thread 3 transfer 43
Thread 3 transfer 44
Thread 3 transfer 45
Thread 3 transfer 46
Thread 3 transfer 47
Thread 3 transfer 48
Thread 3 transfer 49
Thread 3 transfer 50
Thread 3 transfer 51
Thread 3 transfer 52
Thread 3 transfer 53
Thread 3 transfer 54
Thread 2 transfer 2
Thread 2 transfer 3
Thread 2 transfer 4
Thread 2 transfer 5
Thread 2 transfer 6
Thread 2 transfer 7
Thread 2 transfer 8
Thread 2 transfer 9
Thread 2 transfer 10
Thread 2 transfer 11
Thread 2 transfer 12
Thread 2 transfer 13
Thread 2 transfer 14
Thread 2 transfer 15
Thread 2 transfer 16
Thread 2 transfer 17
Thread 2 transfer 18
Thread 2 transfer 19
Thread 2 transfer 20
Thread 2 transfer 21
Thread 2 transfer 22
Thread 2 transfer 23
 Thread 4, gets http://127.0.0.1:46821/1
0 transfer 5
Thread 0 transfer 6
Thread 0 transfer 7
Thread 0 transfer 8
Thread 0 transfer 9
Thread 0 transfer 10
Thread 4 transfer 0
Thread 2 transferThread 1 transfer TTh1 h20rr4
ead 0 transfer 11
T
ead 4 transfer 1
Thread 2 thTrrTaehhnarrsdeaef d1e  a0t drrt  4ra2 an5tns
ransfer 2
TsffheeTrrrhe  1ar12de1
 4 transfer 3
ThreadTad
 2 transfer 26
Thread 1 Thr t0e rhatardrne asa4nfd se tfr2re  ar1tn 21sr
3
fer 4
ansfer 27
Thread 4 transfer 5
Thread 2 transfer 28
Thread 2 transfer 29
Thread 1 transfer 13
TThread 0 transfer 14
[New Thread 0x155552c21700 (LWP 9338)]
int_thread_release, bad reference count
int_thread_release, bad reference count
Thread 2 transfer 30
int_thread_release, bad reference count
hread 3 transfer 55
int_thread_release, bad reference count
int_thread_release, bad reference count
Thread 5, gets http://12
Thread 3 "lib1541" received signal SIGABRT, Aborted.
[Switching to Thread 0x155553425700 (LWP 9332)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x0000155554aaa801 in __GI_abort () at abort.c:79
#2  0x00001555544fd9c2 in int_thread_release (hash=0x155553424990) at err.c:485
#3  0x00001555544fd6b7 in int_thread_del_item (d=<optimized out>) at err.c:547
#4  0x00001555544fe19d in ERR_remove_thread_state (id=<optimized out>) at err.c:1030
#5  0x00001555550e21fd in Curl_ossl_close_all (data=0x155544006728) at vtls/openssl.c:1427
#6  0x00001555550ea067 in Curl_ssl_close_all (data=0x155544006728) at vtls/vtls.c:522
#7  0x0000155555096f33 in Curl_close (datap=0x155544010e30) at url.c:366
#8  0x00001555550864ff in Curl_conncache_close_all_connections (connc=0x155544010de0) at conncache.c:563
#9  0x00001555550bb455 in curl_multi_cleanup (multi=0x155544010cf8) at multi.c:2436
#10 0x0000155555096eb6 in Curl_close (datap=0x155553424de8) at url.c:346
#11 0x000015555509308b in curl_easy_cleanup (data=0x0) at easy.c:737
#12 0x0000555555555a1f in run_thread (ptr=0x7fffffffd818) at lib1541.c:96
#13 0x0000155554e626db in start_thread (arg=0x155553425700) at pthread_create.c:463
#14 0x0000155554b8b88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 
```

I will post the build steps momentarily.

**Comment by ladar** [comment] 2020-06-11 03:46
Try as I might I haven't been able to reproduce the issue inside a fresh virtual machine. And after updating the original virtual machine, and rebooting, she won't reproduce it either.

**Comment by bagder** [comment] 2020-06-11 08:04
For me it doesn't matter that much as we already know this an area with a problem and until we believe we have fixed that problem multiple reports won't help much.

**Comment by bagder** [comment] 2020-06-12 12:06
Duplicate of #4915

**Closed** 2020-06-20 22:01 UTC
Labels: crash, tests
