### ISSUE TITLE
ssl session cache and CURLINFO_APPCONNECT_TIME_T  

### ISSUE THREAD

**Issue by patrickkh7788** [curl/curl#4294] opened 2019-09-04 11:03 UTC
I try build curl 7.65.3 with woflSSL v4.1.0 with multi handle.  

I pass one easy handle with ssl, finish and free easy. then try again with same url.

I print `CURLINFO_APPCONNECT_TIME_T` when easy handle finished,  seems the seconds call  
use the same `CURLINFO_APPCONNECT_TIME_T` like first one. 

for the first domain `Weibo.com`: (249ms, 204ms), (225ms, 187ms)

the `www.baidu.com`:  (38ms, 39ms)

And others like (55ms, 54ms).
 
The seconds  call should avoid ssl handshake, why still use so much time ?

If the first socket force closed, I expect  0-rtt tls1.3 handshake.

I build wolfSSL with ` --enable-savesession` and `--enable-bigcache`, `--enable-sessioncerts`

CURLINFO_PRIMARY_IP =1048608, CURLINFO_PRIMARY_PORT, return `null` and  `0`, is this expect value ?

**Comment by bagder** [comment] 2019-09-04 11:35
Duplicate of #3760

**Comment by bagder** [comment] 2019-09-04 11:38
> CURLINFO_PRIMARY_PORT, return null and 0, is this expect value ?

No, but seems totally unrelated to the issue here.

**Closed by bagder** 2019-09-04 11:38 UTC

**Comment by patrickkh7788** [comment] 2019-09-04 12:59
I am not sure it is Duplicate of #3760.

I modify my code to `curl_multi_remove_handle` before `curl_easy_cleanup`. (the old call is from `CURLMSG_DONE`)

I test on `macOS` and `linux`.

the  `CURLINFO_ACTIVESOCKET = 5242924`  value is not the same if the seconds easy curl `CURLINFO_APPCONNECT_TIME_T` is big than 0.

I add sleep 30ms before call the seconds easy call, and all first call handle is destroyed. 

when I link with `-flto=full` on macOS, it always return diff socket. when link without `LTO`, it some time return same socket then seconds CURLINFO_APPCONNECT_TIME_T is 0.

on linux it seems always return diff socket.  (I test on last alpine)

**Comment by bagder** [comment] 2019-09-04 13:07
I don't understand what relevance those details have. You say there's a APPCONNECT_TIME problem, and #3760 identified one. Possibly going to be fixed like #3773 so you could try that one (which sets the time to 0 for reused connections).

**Comment by patrickkh7788** [comment] 2019-09-04 13:36
The problem is there is no socket reuse.  (create new socket for the same url in two easy call).

**Comment by bagder** [comment] 2019-09-04 13:39
and with the proposed fix, what happens then?

**Comment by patrickkh7788** [comment] 2019-09-04 14:06
with the pr 3773,   all platform pass the test with or without lto.  the socket reuse issue is fixed.

The CURLINFO_PRIMARY_IP, CURLINFO_PRIMARY_PORT still remain the same, should I create a new issue for this?

**Comment by patrickkh7788** [comment] 2019-09-04 14:13
I do more test with diff domain. `https://imququ.com`  reuse socket every time.

but "https://www.baidu.com" and "https://weibo.com" not reuse the socket all the time.

On browser test:  The `https://imququ.com` use tls1.3,   "https://www.baidu.com" and "https://weibo.com" use tls1.2. 

On browser the socket for Weibo.com and Baidu.com get reused.

**Comment by patrickkh7788** [comment] 2019-09-04 14:35
when I call one 1.3 site, them 1.2 site, it all re handshake  for every call.

in one process run once by this order: 
```sh
socket=10, ssltime=51ms, time=63ms, url=https://www.qq.com/ 
socket=12, ssltime=255ms, time=331ms, url=https://passport.weibo.com/visitor/visitor?entry=miniblog&a=enter&url=https%3A%2F%2Fweibo.com%2F&domain=.weibo.com&sudaref=https%3A%2F%2Fweibo.com&ua=php-sso_sdk_client-0.6.28&_rand=1567607543.347
socket=13, ssltime=1314ms, time=3726ms, url=https://imququ.com
socket=14, ssltime=42ms, time=85ms, url=https://www.baidu.com
socket=10, ssltime=54ms, time=68ms, url=https://www.qq.com/ 
socket=12, ssltime=222ms, time=300ms, url=https://passport.weibo.com/visitor/visitor?entry=miniblog&a=enter&url=https%3A%2F%2Fweibo.com%2F&domain=.weibo.com&sudaref=https%3A%2F%2Fweibo.com&ua=php-sso_sdk_client-0.6.28&_rand=1567607547.5938
socket=13, ssltime=1822ms, time=3607ms, url=https://imququ.com
socket=14, ssltime=34ms, time=72ms, url=https://www.baidu.com
socket=10, ssltime=52ms, time=67ms, url=https://www.qq.com/ 
socket=12, ssltime=200ms, time=281ms, url=https://passport.weibo.com/visitor/visitor?entry=miniblog&a=enter&url=https%3A%2F%2Fweibo.com%2F&domain=.weibo.com&sudaref=https%3A%2F%2Fweibo.com&ua=php-sso_sdk_client-0.6.28&_rand=1567607551.7112
socket=13, ssltime=1966ms, time=4734ms, url=https://imququ.com
socket=14, ssltime=35ms, time=71ms, url=https://www.baidu.com
```

when call easy one 3 time continuously:
```sh
socket=10, ssltime=60ms, time=74ms, url=https://www.qq.com/ 
socket=10, ssltime=0ms, time=13ms, url=https://www.qq.com/ 
socket=10, ssltime=0ms, time=13ms, url=https://www.qq.com/ 
socket=12, ssltime=216ms, time=294ms, url=https://passport.weibo.com/visitor/visitor?entry=miniblog&a=enter&url=https%3A%2F%2Fweibo.com%2F&domain=.weibo.com&sudaref=https%3A%2F%2Fweibo.com&ua=php-sso_sdk_client-0.6.28&_rand=1567607678.4895
socket=14, ssltime=207ms, time=278ms, url=https://passport.weibo.com/visitor/visitor?entry=miniblog&a=enter&url=https%3A%2F%2Fweibo.com%2F&domain=.weibo.com&sudaref=https%3A%2F%2Fweibo.com&ua=php-sso_sdk_client-0.6.28&_rand=1567607678.7736
socket=11, ssltime=187ms, time=264ms, url=https://passport.weibo.com/visitor/visitor?entry=miniblog&a=enter&url=https%3A%2F%2Fweibo.com%2F&domain=.weibo.com&sudaref=https%3A%2F%2Fweibo.com&ua=php-sso_sdk_client-0.6.28&_rand=1567607679.1185
socket=12, ssltime=1371ms, time=2417ms, url=https://imququ.com
socket=12, ssltime=0ms, time=580ms, url=https://imququ.com
socket=12, ssltime=0ms, time=841ms, url=https://imququ.com
socket=13, ssltime=39ms, time=81ms, url=https://www.baidu.com
socket=14, ssltime=30ms, time=62ms, url=https://www.baidu.com
socket=10, ssltime=29ms, time=74ms, url=https://www.baidu.com
```

**Comment by patrickkh7788** [comment] 2019-09-04 15:01
without pr 3773, https://www.qq.com/  will  do the handshake and create new socket for continuously call .

**Comment by patrickkh7788** [comment] 2019-09-04 19:15
I build curl with cares:  https://curl.haxx.se/libcurl/c/multi-uv.html

the CURL_POLL_REMOVE from handle_socket 2 time for first easy call. (and create socket 2 time for first easy call)

So the socket get closed every time when the easy finished,  still not get reused.

And the tls session cache also not work. (only work for tls1.3 without multi domains).   

I already set `CURLMOPT_MAX_TOTAL_CONNECTIONS`,  this seems is a bugs.

**Comment by bagder** [comment] 2019-09-04 21:53
> The CURLINFO_PRIMARY_IP, CURLINFO_PRIMARY_PORT still remain the same, should I create a new issue for this?

As they are separate from CURLINFO_APPCONNECT_TIME_T, yes.

I don't understand what you're saying with the next comments.
