### ISSUE TITLE
curl: (55) ngtcp2_conn_handle_expiry returned error: ERR_HANDSHAKE_TIMEOUT

### ISSUE THREAD

**Issue by sagisar1** [curl/curl#15336] opened 2024-10-18 23:46 UTC
### I did this

`curl -I https://www.cloudflare.com --http3-only -v`

when issuing this command I got the following output:

```
Note: Using embedded CA bundle, for proxies (234847 bytes)
* Host www.cloudflare.com:443 was resolved.
* IPv6: 2606:4700::6810:7b60, 2606:4700::6810:7c60
* IPv4: 104.16.123.96, 104.16.124.96
*   Trying [2606:4700::6810:7b60]:443...
*  CAfile: C:\Users\myuser\AppData\Local\Microsoft\WinGet\Packages\cURL.cURL_Microsoft.Winget.Source_8wekyb3d8bbwe\curl-8.10.1_6-win64-mingw\bin\curl-ca-bundle.crt
*  CApath: none
*   Trying 104.16.123.96:443...
* ngtcp2_conn_handle_expiry returned error: ERR_HANDSHAKE_TIMEOUT
*   Trying [2606:4700::6810:7c60]:443...
* ngtcp2_conn_handle_expiry returned error: ERR_HANDSHAKE_TIMEOUT
*   Trying 104.16.124.96:443...
* ngtcp2_conn_handle_expiry returned error: ERR_HANDSHAKE_TIMEOUT
* ngtcp2_conn_handle_expiry returned error: ERR_HANDSHAKE_TIMEOUT
* Failed to connect to www.cloudflare.com port 443 after 20308 ms: Failed sending data to the peer
* closing connection #0
curl: (55) ngtcp2_conn_handle_expiry returned error: ERR_HANDSHAKE_TIMEOUT
```

### I expected the following

I expected to get a 200 response code of an HTTP/3 Connection

### curl/libcurl version

```
curl 8.10.1 (x86_64-w64-mingw32) libcurl/8.10.1 LibreSSL/4.0.0 zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 WinIDN libpsl/0.21.5 libssh2/1.11.1 nghttp2/1.63.0 ngtcp2/1.8.1 nghttp3/1.6.0
Release-Date: 2024-09-18
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli CAcert HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL SSPI threadsafe UnixSockets zstd
```

### operating system

Windows 10 latest version

**Comment by edmcln** [comment] 2024-10-19 07:33
Try the same URL in Chrome/Firefox and ensure the page is served via the QUIC protocol. Chances are, your ISP or Network Firewall is blocking the QUIC traffic to that destination.

**Comment by bagder** [comment] 2024-10-19 08:10
That command line works fine for me on Linux, even though I did not use the exact same library versions involved.

Add `--trace-config http/3` to the command line and show us the full trace, it might show something.

**Comment by sagisar1** [comment] 2024-10-19 14:49
On linux it works fine also for me, maybe the library is the problem, but I wait for the experts here to say.
Anyway, with `--trace-config http/3` I get the same output as without

**Comment by vszakats** [comment] 2024-10-19 17:29
One thing to test is with the previous 8.10.1_4 and 8.10.1_3 builds to see if the ngtcp 1.8.1 or libressl 4.0.0 upgrades played any role.

https://curl.se/windows/dl-8.10.1_5/curl-8.10.1_5-win64-mingw.zip (libressl 4.0.0 ngtcp 1.8.0 libssh2 1.11.1, should be irrelevant)
https://curl.se/windows/dl-8.10.1_4/curl-8.10.1_4-win64-mingw.zip (libressl 4.0.0 ngtcp 1.8.0)
https://curl.se/windows/dl-8.10.1_3/curl-8.10.1_3-win64-mingw.zip (libressl 3.9.2 ngtcp2 1.8.0)

**Comment by edmcln** [comment] 2024-10-19 17:35
> Firstly, my firewall is handed by Avast antivirus

I don't care about your personal AV firewall, I was referring to hardware firewalls.
> Secondly, why would the ISP would block QUIC traffic?

This is a common practice in the censorship industry in countries like China, Iran, and Russia. In these scenarios, even if a website works with one TLS backend, it might not work with others (e.g., `LibreSSL` might fail, whereas `GnuTLS` or `OpenSSL` succeeds).

PS, it works fine on my Windows machine.
```
curl.exe -Iv --http3-only https://www.cloudflare.com

Note: Using embedded CA bundle, for proxies (234847 bytes)
* Host www.cloudflare.com:443 was resolved.
* IPv6: (none)
* IPv4: 104.16.124.96, 104.16.123.96
*   Trying 104.16.124.96:443...
*  CAfile: C:\Users\???\Desktop\???\curl-ca-bundle.crt
*  CApath: none
* Server certificate:
*  subject: CN=www.cloudflare.com
*  start date: Sep  5 16:56:35 2024 GMT
*  expire date: Dec  4 17:56:31 2024 GMT
*  subjectAltName: host "www.cloudflare.com" matched cert's "www.cloudflare.com"

*  issuer: C=US; O=Google Trust Services; CN=WE1
*  SSL certificate verify ok.
*   Certificate level 0: Public key type ? (256/128 Bits/secBits), signed using
ecdsa-with-SHA256
*   Certificate level 1: Public key type ? (256/128 Bits/secBits), signed using
ecdsa-with-SHA384
*   Certificate level 2: Public key type ? (384/192 Bits/secBits), signed using
ecdsa-with-SHA384
* Connected to www.cloudflare.com (104.16.124.96) port 443
* using HTTP/3
* [HTTP/3] [0] OPENED stream for https://www.cloudflare.com/
* [HTTP/3] [0] [:method: HEAD]
* [HTTP/3] [0] [:scheme: https]
* [HTTP/3] [0] [:authority: www.cloudflare.com]
* [HTTP/3] [0] [:path: /]
* [HTTP/3] [0] [user-agent: curl/8.10.1]
* [HTTP/3] [0] [accept: */*]
> HEAD / HTTP/3
> Host: www.cloudflare.com
> User-Agent: curl/8.10.1
> Accept: */*
>
* Request completely sent off
< HTTP/3 200
HTTP/3 200
< date: Sat, 19 Oct 2024 16:29:24 GMT
.
.
.
```
```
curl 8.10.1 (x86_64-w64-mingw32) libcurl/8.10.1 LibreSSL/4.0.0 zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 WinIDN libpsl/0.21.5 libssh2/1.11.1 nghttp2/1.63.0 ngtcp2/1.8.1 nghttp3/1.6.0
Release-Date: 2024-09-18
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli CAcert HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL SSPI threadsafe UnixSockets zstd
```

**Comment by sagisar1** [comment] 2024-10-20 12:58
@edmcln , by refering to hardware firewall, you mean if the firewall of my home router? If yes, so I don't have actual firewall settings there related to the QUIC protocol or UDP
and about censorship, I don't live in a country from the ones you sepcified, neither a country that enforce internet censoreship, so this is possibly not the reason

@vszakats I don't think it will help because I had the 8.10.1_3 version (build 3) and it was the same problem

**Comment by vszakats** [comment] 2024-10-20 16:52
> @vszakats I don't think it will help because I had the 8.10.1_3 version (build 3) and it was the same problem

The version string in your original post says libressl 4.0.0 and ngtcp 1.8.1, which mean it's 8.10.1_6.
If it happens with 8.10.1_3 too, it means these updates are unrelated. Thanks for checking.

**Comment by sagisar1** [comment] 2024-10-22 12:55
@edmcln ?

**Comment by edmcln** [comment] 2024-10-23 11:41
As a rule of thumb, if you are a residential internet user, you don't have to worry too much about firewalls. But having said that, without more detailed information we can't rule out anything.

So far, nobody has been able to reproduce the issue. If I were you, I'd try the following list to narrow down the cause of the problem:

- different internet providers
- connecting via VPNs
- analyzing network traffic with Wireshark
- building curl with different TLS backends (OpenSSL 3.3+)
- other QUIC enabled websites that use cloudflare services (for example https://pubs.acs.org)

**Comment by sagisar1** [comment] 2024-10-24 12:29
First of all, you are saying that no one has been able to reproduce this issue,  but for now only you shown that it worked for you, so I am sure that there are other people who encountered this issue.

> - different internet providers
 I tried with a different ISP, it didn't work
> - building curl with different TLS backends (OpenSSL 3.3+)
The question here is does LibreSSL 4.0.0 supports QUIC  traffic, since I prefer to use curl version that I can download with winget, since it's more comfortable 
> - other QUIC enabled websites that use cloudflare services (for example https://pubs.acs.org/)
This produced me the same error
> - analyzing network traffic with Wireshark
these are the first 3 QUIC packets sent when I issue the command:
![image](https://github.com/user-attachments/assets/66a2bca0-2756-40d4-a848-f4aa4419a682)
then In the third packet content I got this warning:
field name: _ws.expert 
 description: [Expert Info (Warning/Decryption): Failed to create decryption context: Secrets are not available]

**Comment by jay** [comment] 2024-10-24 17:46
> The question here is whether LibreSSL 4.0.0 supports QUIC traffic

Yes. I tested [curl-8.10.1_6](https://curl.se/windows/dl-8.10.1_6/curl-8.10.1_6-win64-mingw.zip) with cloudflare and acm with HEAD and GET requests, and confirmed in Wireshark that only QUIC was used.

> description: [Expert Info (Warning/Decryption): Failed to create decryption context: Secrets are not available]

I do notice that Wireshark decryption doesn't work even though I've set SSLKEYLOGFILE so maybe we don't support that for libressl and quic?

**Comment by sagisar1** [comment] 2024-10-25 18:11
@jay what is acs?
And anyway , if you say that libressl 4.0.0 is supporting http 3 and QUIC, do you have any idea to why I receive the error?

**Comment by AchilleasTsiamoulis** [comment] 2024-10-28 21:16
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by bagder** [comment] 2024-10-29 09:02
@sagisar1 yes, curl built with libressl performs QUIC and HTTP/3 fine. We test that all the time in CI and numerous people can use it fine, on Windows and elsewhere.

We don't know why you get this problem, but based on reports from numerous people in here it seems to be something related to your network setup and surrounding rather than a problem in curl or libressl.

**Comment by sagisar1** [comment] 2024-10-29 11:28
@bagder I see, I'll check more about that to try to understand the root cause of the problem. 
Again I am saying, maybe there are other people in the world who encountered this problem.
Thank you anyway fro the replay

**Comment by jay** [comment] 2024-10-29 16:27
Closing since as far as we can tell this isn't a curl issue.

> @jay what is acs?

an earlier post mentioned the website https://pubs.acs.org/

**Closed by jay** 2024-10-29 16:27 UTC
Labels: HTTP/3
