### ISSUE TITLE
netrc not respected if login token is not present

### ISSUE THREAD

**Issue by centromere** [curl/curl#9148] opened 2022-07-13 01:14 UTC
### I did this

```
➜  ~ cat netrc
machine foo.cachix.org password foo
➜  ~ /usr/local/opt/curl/bin/curl -v --netrc-file netrc https://foo.cachix.org/nix-cache-info
...
> GET /nix-cache-info HTTP/2
> Host: foo.cachix.org
> user-agent: curl/7.83.1
> accept: */*
>
...
< HTTP/2 401
...
```

### I expected the following

```
> GET /nix-cache-info HTTP/2
> Host: foo.cachix.org
> authorization: Basic IiI6Zm9v
> user-agent: curl/7.83.1
> accept: */*
>
...
< HTTP/2 200
...
```

### It works when

```
➜  ~ cat netrc
machine foo.cachix.org login "" password foo
➜  ~ /usr/local/opt/curl/bin/curl -v --netrc-file netrc https://foo.cachix.org/nix-cache-info
...
> GET /nix-cache-info HTTP/2
> Host: foo.cachix.org
> authorization: Basic IiI6Zm9v
> user-agent: curl/7.83.1
> accept: */*
>
...
```

### curl/libcurl version

```
➜  ~ /usr/local/opt/curl/bin/curl --version
curl 7.83.1 (x86_64-apple-darwin21.3.0) libcurl/7.83.1 (SecureTransport) OpenSSL/1.1.1o zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.47.0 librtmp/2.3 OpenLDAP/2.6.2
Release-Date: 2022-05-11
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets zstd
```

### operating system

OSX 12.4, curl installed with homebrew.

**Comment by bagder** [comment] 2022-07-13 21:19
see #9066

**Comment by bagder** [comment] 2022-07-13 22:08
Duplicate of #8653

**Closed by bagder** 2022-07-13 22:08 UTC
