### ISSUE TITLE
Restore echo on terminal after Ctrl+C

### ISSUE THREAD

**Issue by dilyanpalauzov** [curl/curl#4318] opened 2019-09-10 12:57 UTC
I use curl 7.65.3 .  If I send `curl -uusername ...` without a password and without a colon, curl prints `Enter host password for user ... :`.  When I type something, it is not visible on the terminal, as the echo (or however it is called) is off.

If I press now Ctrl+C, curl terminates, but the echo is not restored.

* In Ctrl+C after asking for password on the terminal and before entering the password, curl shall restore the echo on the terminal.

**Comment by bagder** [comment] 2019-09-10 13:02
what operating system are you seeing this on?

**Comment by dilyanpalauzov** [comment] 2019-09-10 13:12
On a Linux from Scratch.  `ldd curl` shows:

        linux-vdso.so.1 (0x00007ffc8c95d000)
        libcurl.so.4 => /usr/local/lib/libcurl.so.4 (0x00007fae58684000)
        libssl.so.1.1 => /usr/local/lib64/libssl.so.1.1 (0x00007fae585f1000)
        libcrypto.so.1.1 => /usr/local/lib64/libcrypto.so.1.1 (0x00007fae5830e000)
        libz.so.1 => /usr/local/lib/libz.so.1 (0x00007fae580f3000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fae580d2000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fae57f18000)
        libnghttp2.so.14 => /usr/local/lib/libnghttp2.so.14 (0x00007fae57eee000)
        libidn2.so.0 => /usr/local/lib/libidn2.so.0 (0x00007fae57ca1000)
        libssh2.so.1 => /usr/local/lib/libssh2.so.1 (0x00007fae57c6f000)
        libpsl.so.5 => /usr/local/lib/libpsl.so.5 (0x00007fae57c5d000)
        libgssapi_krb5.so.2 => /usr/local/lib/libgssapi_krb5.so.2 (0x00007fae57c08000)
        libkrb5.so.3 => /usr/local/lib/libkrb5.so.3 (0x00007fae57b1a000)
        libk5crypto.so.3 => /usr/local/lib/libk5crypto.so.3 (0x00007fae57adf000)
        libcom_err.so.3 => /usr/local/lib/libcom_err.so.3 (0x00007fae57ada000)
        libldap-2.4-releng.so.2 => /usr/local/lib/libldap-2.4-releng.so.2 (0x00007fae57a8f000)
        liblber-2.4-releng.so.2 => /usr/local/lib/liblber-2.4-releng.so.2 (0x00007fae57a80000)
        libbrotlidec.so.1 => /usr/local/lib/libbrotlidec.so.1 (0x00007fae57873000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fae5786e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fae58768000)
        libicuuc.so.63 => /usr/local/lib/libicuuc.so.63 (0x00007fae57614000)
        libicudata.so.63 => /usr/local/lib/libicudata.so.63 (0x00007fae55c26000)
        libkrb5support.so.0 => /usr/local/lib/libkrb5support.so.0 (0x00007fae55c18000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fae55bff000)
        libsasl2.so.3 => /usr/local/lib/libsasl2.so.3 (0x00007fae55be0000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fae55a9e000)
        libbrotlicommon.so.1 => /usr/local/lib/libbrotlicommon.so.1 (0x00007fae5587d000)
        libstdc++.so.6 => /usr/local/lib64/libstdc++.so.6 (0x00007fae556a5000)
        libgcc_s.so.1 => /usr/local/lib64/libgcc_s.so.1 (0x00007fae5568b000)

so no termcap, tinfow or curses.  ./configure has printed:

checking for termios.h... yes
checking for termio.h... yes

and I don't see anything else relevant.

**Comment by bagder** [comment] 2019-09-13 14:13
I can't reproduce on my debian Linux. I run:

    $ curl ftp://localhost/ -u hello
    Enter host password for user 'hello':

And then while entering the password, I press control-c and I'm back in the shell with full echo. Is that how you do it as well?

**Comment by dilyanpalauzov** [comment] 2019-09-13 16:43
I create a file with this content (one line):
```
curl -v -uaaa@aegee.org -HDepth:0 -XPROPFIND -HContent-Type:application/xml https://mail.aegee.org/dav/addressbooks
```
change its mode to 755.  When I execute the file, and interrupt it with Ctrl+C, the echo is gone.  If I run the curl-command outside of a file (script) the echo returns.  Maybe the problem is not in curl, but in the sh, which is interrupted, without interrupting curl and letting it restore the terminal?

**Comment by bagder** [comment] 2019-10-13 09:46
I've tried bash 5.0 and dash 0.5.10.2, none of them reproduce this problem for me on Debian Linux.

**Comment by bagder** [comment] 2019-11-23 20:10
Cannot reproduce and no more information provided. Closing.

**Closed by bagder** 2019-11-23 20:10 UTC
Labels: cmdline tool, needs-info-or-update
