### ISSUE TITLE
Application crash when "Proxy connect abort due to timeout" happens Randomly in multithreaded.

### ISSUE THREAD

**Issue by hideme4u** [curl/curl#7283] opened 2021-06-21 19:23 UTC
I am using the multithreaded application with libcurl.  Application is thread-safe.
When no proxy is used, the application does not crash even multiple instances are ran parallel. 
curl_multi_perform API is used.  No of threads using curl api : 8.
Each thread has it's own instance of CURLM handle and easy handle is added in that thread itself. Not shared to other threads. 

Expected ->  When proxy connection timeout, the application should not be crashed. 

### curl/libcurl version -> 7.77  and openssl -> 1.1.1

Stack Trace: 
Program terminated with signal 6, Aborted.
(gdb) bt full
#0  0x00007f0da60de1d7 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007f0da60df8c8 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007f0da611df07 in __libc_message () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007f0da6123da4 in malloc_printerr () from /lib64/libc.so.6
No symbol table info available.
#4  0x00007f0da6125715 in _int_free () from /lib64/libc.so.6
No symbol table info available.
#5  0x00007f0da97d0241 in Curl_free_request_state () from /lib64/libcurl.so.4
No symbol table info available.
#6  0x00007f0da97b14fd in multi_done () from /lib64/libcurl.so.4
No symbol table info available.
#7  0x00007f0da97b19b3 in multi_runsingle () from /lib64/libcurl.so.4
No symbol table info available.
#8  0x00007f0da97b29cf in curl_multi_perform () from /lib64/libcurl.so.4

**corrupted double-linked list: 0x00007fc67c010ae0**

I am seeing the following error in logs: "**Proxy CONNECT aborted due to timeout**"  after which my application crashes.
No of threads used: 8.    
When the same application is ran in loop multiple times (like 200, 300 times) at a time. it crashed. 

### operating system
Linux.

**Comment by bagder** [comment] 2021-06-21 21:16
Duplicate of #7236 it sounds like.

Can you try current master and see if it works?

**Comment by hideme4u** [comment] 2021-06-22 09:22
@bagder  Yes with that #7236 fix,  crashed did not happen.  Thanks for it. 
But I wanted to know, are we creating any release from 7.77 for this issue as this will be breaking lot of applications that are using curl 7.77 ?   Or we need to wait till the next release? 

In general, How soon we can say that particular new release is stable?

**Comment by bagder** [comment] 2021-06-23 21:23
The fix will be included in the pending curl release. The next release date is always at https://curl.se/dev/release-notes.html  (July 21, 2021)

**Closed by bagder** 2021-06-23 21:23 UTC
Labels: connecting & proxies, crash
