### ISSUE TITLE
macOS: configure error with c-ares

### ISSUE THREAD

**Issue by antkudr** [curl/curl#5313] opened 2020-04-30 13:59 UTC
###  configure error
 configure: pkg-config: ares LIBS: "-lcares"
 configure: pkg-config: ares LDFLAGS: "-L/Users/user/c-ares/build/install/lib"
 configure: pkg-config: ares CPPFLAGS: "-I/Users/user/c-ares/build/install/include"

### pkg-config of cares is
prefix=/Users/user/c-ares/build/install
exec_prefix=${prefix}/bin
libdir=${prefix}/lib
includedir=${prefix}/include

Name: c-ares
URL: https://c-ares.haxx.se/
Description: asynchronous DNS lookup library
Version: 1.16.0
Requires: 
Requires.private: 
Cflags: -I${includedir} -DCARES_STATICLIB
Libs: -L${libdir} -lcares
Libs.private:  -lresolv

### how to fix

take into account `Libs.private:  -lresolv` to make `ares LIBS: "-lcares -lresolv"`

### operating system
macOS 10.15

**Comment by bagder** [comment] 2020-04-30 14:16
I cannot reproduce. I installed c-ares 1.16.0 with homebrew and then (using the code in current git master):
~~~
$ ./configure --enable-ares=/usr/local/opt/c-ares
$ make -sj
$ ./src/curl -V
curl 7.70.1-DEV (x86_64-apple-darwin19.3.0) libcurl/7.70.1-DEV zlib/1.2.11 c-ares/1.16.0 libidn2/2.3.0 nghttp2/1.40.0
Release-Date: [unreleased]
Protocols: dict file ftp gopher http imap ldap ldaps pop3 rtsp smtp telnet tftp 
Features: AsynchDNS HTTP2 IDN IPv6 Largefile libz UnixSockets

**Comment by antkudr** [comment] 2020-04-30 14:19
hmm, I use static build of c-ares.

just clone and build like `cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/Users/user/work/c-ares/build/install -DCARES_STATIC=On -DCARES_SHARED=Off -DCARES_STATIC_PIC=On -DCARES_BUILD_TOOLS=OFF ../`

**Comment by bagder** [comment] 2020-04-30 14:25
In general, when doing static builds you are basically giving up automated help and get to manage dependencies on your own. Also, you apparently build with cmake which I don't and I would expect has a few more/other nits to it.

**Comment by antkudr** [comment] 2020-04-30 15:02
c-ares build step:

git clone https://github.com/c-ares/c-ares.git && cd c-ares && mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/Users/user/c-ares/build/install -DCARES_STATIC=On -DCARES_SHARED=Off -DCARES_STATIC_PIC=On -DCARES_BUILD_TOOLS=OFF ..

make -j8
make install

curl build step:

./configure --enable-ipv6  --disable-shared --enable-static --disable-ldap --prefix="$pwd/build" --without-ca-path --without-ca-bundle --disable-threaded-resolver --enable-ares=/Users/user/c-ares/build/install

**Comment by bagder** [comment] 2020-04-30 15:46
The fact remains: we focus on making the build scripts work with *shared* libraries as hunting down the possible dependency chains when linking statically is really annoying, boring work and can even change between versions and operating systems. If you can fix your issue and submit a PR for it, we will likely accept it but I personally will not spent much time to work on static builds.

**Comment by bagder** [comment] 2020-05-11 09:26
This is now mentioned in the [KNOWN_BUGS](https://github.com/curl/curl/blob/4b88ac71f2e93d1158f29fff7fa577a78c534733/docs/KNOWN_BUGS#L358-L378) file. We will accept improvements but this is tricky business. Closing this issue now.

**Closed by bagder** 2020-05-11 09:26 UTC
Labels: KNOWN_BUGS material, build
