### ISSUE TITLE
libcurl / libnss leak memory on CENTOS and RHEL when CURLOPT_SSL_VERIFYPEER = 1

### ISSUE THREAD

**Issue by sandisn-zbx** [curl/curl#696] opened 2016-03-02 14:13 UTC
### I did this

Several of our customers reported memory leaks when using Zabbix with web-scenarios. We tracked down the problem to libcurl / libnss and CURLOPT_SSL_VERIFYPEER  = 1 option on CENTOS 6, CENTOS 7 and the corresponding RHEL versions. Eventually OOM killer kicks in and kills Zabbix processes.

The attached program demonstrates the issue (see the included README for running instructions). If you run it on the aforementioned operating systems with the default libcurl from their repositories then heap memory segment will grow continuously (run it for several minutes and use the included topmap.sh script to monitor memory segments).

Valgrind doesn't show any lost memory.

Workarounds:
* compiling libcurl from sources and using OpenSSL as the TLS backend;
* calling curl_global_init() / curl_global_cleanup() for each retrieved page - unfortunately on Debian based distributions this triggers a memory leak in GnuTLS;
* disabling CURLOPT_SSL_VERIFYPEER.

[leak.zip](https://github.com/curl/curl/files/154865/leak.zip)

### I expected the following

All memory related to handle created with curl_easy_init() is freed after calling curl_easy_cleanup() regardless of the libcurl's TLS backend.

### curl/libcurl version

Default libcurl on the latest CENTOS 6, CENTOS 7.

### operating system

CENTOS 6, CENTOS 7, corresponding RHEL releases.

**Comment by bagder** [comment] 2016-03-02 16:11
> Default libcurl on the latest CENTOS 6, CENTOS 7.

and they are... ?

**Comment by sandisn-zbx** [comment] 2016-03-02 16:17
http://vault.centos.org/6.7/os/Source/SPackages/
curl-7.19.7-46.el6.src.rpm

http://vault.centos.org/7.2.1511/os/Source/SPackages/
curl-7.29.0-25.el7.centos.src.rpm

**Comment by bagder** [comment] 2016-03-02 16:25
ping @kdudka, anything you recognize?

**Comment by kdudka** [comment] 2016-03-02 16:46
The program in question does not seem to be correct.  It either calls ```curl_global_init() ``` and ``` curl_global_cleanup()```  per connection or not at all.  According to documentation, these functions should be called exactly once: ```curl_global_init() ``` near the begin of ```main()``` and ``` curl_global_cleanup()``` before exit.  Calling them per connection is overkill and unnecessary waste of resources.  Additionally, the global initialization functions are not thread-safe.

If I rewrite the program to use ```curl_global_init() ```/``` curl_global_cleanup()``` as documented, I see no memory leaks with ```libcurl-7.19.7-46.el6```.

**Comment by sandisn-zbx** [comment] 2016-03-03 11:37
Updated the program to call curl_global_init() once. According to the manual of curl_easy_init() it can be omitted in which case curl_easy_init() will call it.
[leak_v2.zip](https://github.com/curl/curl/files/156672/leak_v2.zip)

In any case - the leak is still present at least on CENTOS 6.7 (see "leak.txt" and "smaps" files in "leak_v2.zip").

Please let me know if you need help reproducing the issue. For me it always reproduces on freshly installed CENTOS 6.7 and CENTOS 7 virtual machines.

**Comment by kdudka** [comment] 2016-03-03 12:26
Thanks for the updated program!  The problem is that ```curl_global_cleanup()``` will never be called by your program because the ```for(;;)``` loop never escapes.  If you instead use a finite number of iterations, can you see any memory leaks after the program exits?

**Comment by sandisn-zbx** [comment] 2016-03-03 13:16
Thanks for the suggestion! Limited the loop to 120 iterations (2 minutes) and put a sleep of 100 seconds after the call to curl_global_cleanup().

Indeed, as expected (and tested in the first iteration of the program), the heap size is reduced after cleanup.

This doesn't solve the problem though. As you pointed out, curl_global_init() and curl_global_cleanup() are supposed to be called once per program (process). We are using libcurl in daemon processes so the leak will not stop until the processes are terminated.

**Comment by kdudka** [comment] 2016-03-03 13:53
Thanks for clarifying that!  The problem is then not leaking memory on program exit, but the continuous memory allocation during program's life time.  This seems to be a known bug of nss:

https://bugzilla.redhat.com/1057388

Let me close this bug as there is nothing to fix in curl.  Please follow-up on the above Bugzilla.

**Closed by kdudka** 2016-03-03 13:53 UTC

**Comment by patrikhson** [comment] 2016-07-12 15:05
Hello,

We have recently had a splendid dinner with my family in a great place, just take a look <http://stiwonkumy.txpageantnetwork.info/xyywt>

Kind regards, paf@frobbit.se
