### ISSUE TITLE
Windows build in 7.66.0 failing

### ISSUE THREAD

**Issue by levicki** [curl/curl#4513] opened 2019-10-21 08:19 UTC
I cloned the repo from github, checked out the 7.66.0 release by commit hash, called buildconf.bat, switched to winbuilds folder, and attempted to build curl using the following command:
```
nmake -f Makefile.vc mode=dll VC=16 ENABLE_IPV6=no GEN_PDB=yes DEBUG=no MACHINE=x86
```
I expected it to build like it did before (last time I used commit hash f3294d9d86e6a7915a967efff2842089b8b0d071 which worked), but it failed linking with the following message:
```
LINK : fatal error LNK1181: cannot open input file '..\builds\libcurl-vc16-x86-release-dll-sspi-winssl-obj-lib\vssh\libssh2.obj'
```
I am not using or setting SSH2 option, this worked in 7.64.0.

**Comment by bagder** [comment] 2019-10-21 08:39
Duplicate of #4322 

Already fixed!

**Closed by bagder** 2019-10-21 08:39 UTC
