### ISSUE TITLE
curl/libcurl framing error while trying to receive push data in http2 protocol

### ISSUE THREAD

**Issue by hatimuradin** [curl/curl#2976] opened 2018-09-11 07:40 UTC
### I did this
I'm trying to receive data from my http2 server which sends some files with `http2` push. push seems working when I test it with some web browsers like `Google Chrome` and `Mozilla Firefox`. In both of these browsers, there is an inspector tool which I can get cURL code of the request and send it with curl. I also have tried `libcurl` `serverpush` [example](https://curl.haxx.se/libcurl/c/http2-serverpush.html) I just modified the server address of the code with my server which is universally accessible from [my server](https://www.sonicserver1.com:8681/Servlet4Push/sonicServer)
### I expected the following
I know curl does not support push in command line tool, but I expected it to perform operation without error. It produces the following error: 
`curl: (16) Error in the HTTP2 framing layer`
And with running the exmaple code I'm receiving the following output:
```
== Info:   Trying 185.112.34.186...
== Info: TCP_NODELAY set
== Info: Connected to sonicserver1.com (185.112.34.186) port 8681 (#0)
== Info: ALPN, offering h2
== Info: ALPN, offering http/1.1
== Info: Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
== Info: successfully set certificate verify locations:
== Info:   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
== Info: TLSv1.2 (OUT), TLS header, Certificate Status (22):
=> Send SSL data, 5 bytes (0x5)
0000: .....
== Info: TLSv1.2 (OUT), TLS handshake, Client hello (1):
=> Send SSL data, 512 bytes (0x200)
0000: ......BG.../...c...:TQ.~..2....U..sr......0.,.(.$.............k.
0040: j.i.h.9.8.7.6.........2...*.&.......=.5.../.+.'.#.............g.
0080: @.?.>.3.2.1.0.........E.D.C.B.1.-.).%.......<./...A.....G.......
00c0: ..sonicserver1.com........................................... ..
0100: ...................................3t.........h2.http/1.1.......
0140: ................................................................
0180: ................................................................
01c0: ................................................................
<= Recv SSL data, 5 bytes (0x5)
0000: ....&
== Info: TLSv1.2 (IN), TLS handshake, Server hello (2):
<= Recv SSL data, 90 bytes (0x5a)
0000: ...V..[...).<...(...z..>f..L..}.U6...G [........dG....<.l4.&.;Z.
0040: .Gy...?./...............h2
== Info: TLSv1.2 (IN), TLS handshake, Certificate (11):
<= Recv SSL data, 891 bytes (0x37b)
0000: ...w..t..q0..m0..U.......YM.J0...*.H........0g1.0...U....Unknown
0040: 1.0...U....Unknown1.0...U....Unknown1.0...U....rv1.0...U....Unkn
0080: own1.0...U....Unknown0...180725084132Z..190725084132Z0g1.0...U..
00c0: ..Unknown1.0...U....Unknown1.0...U....Unknown1.0...U....rv1.0...
0100: U....Unknown1.0...U....Unknown0.."0...*.H.............0.........
0140: ..}..v$Hq.5...?I.O.*....J6v...'........'..d....8.RZ.^....s.H.b..
0180: ,.Q.A..6gQ..W.7.q]..&.].=...b...b.. .B>/...Q.)..yX.U@..M.%.h.k.s
01c0: .H..&.U.|..|o/.iQ...DN.0...W....XX....m\.>.I2.5..../.'.:.......+
0200: p.........X@E...f.(=...).|.7...<r..1.......H...s......T.o.8/..9.
0240: .....!0.0...U......d|.JN.Hb...NA|....|X0...*.H.................2
0280: A...1..j..G.R..n..r.n..Ie..=..*........A........./8.M"..V..(|.@.
02c0: Sh..w.~?..0..,......`yt6.|.*....v7..$b.i?mu.u{.A.E..(K......j...
0300: <.....q.U..{.{...).#B..4....>6...(.sQ].>..m.W..Z...&.....B....`.
0340: 5.?.2m.N.-.N...5...1.w.ItIEm......Q!.k.iW1.W.....:.....7...
== Info: TLSv1.2 (IN), TLS handshake, Server key exchange (12):
<= Recv SSL data, 333 bytes (0x14d)
0000: ...I...A.j)Mb4..s.&..>.yE_7..F..9d.t..1..|.U.,N...\i..*Z.']Po.L.
0040: @m..9..y.....N.W..h"..11..h...&@.A.CoB......c/.....;.;2..j.4yD.n
0080: 3...Y~.2.D .$....[...2.........E\f.....@g4........i04?.~Fok.u P.
00c0: .h..Q......c.P<.L.....>.n.._V.}w.R.M...m1..O...H.@)....}......._
0100: ].8...AZ....kN.._}..?F.rU.@#I.+...4q...o...ax.Y.....x=.x|.v....\
0140: `T...~gW..sI.
== Info: TLSv1.2 (IN), TLS handshake, Server finished (14):
<= Recv SSL data, 4 bytes (0x4)
0000: ....
=> Send SSL data, 5 bytes (0x5)
0000: ....F
== Info: TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
=> Send SSL data, 70 bytes (0x46)
0000: ...BA...fB...+=f..1.......0....:..d........F....0...zv.OGs>.]...
0040: ..M>*L
=> Send SSL data, 5 bytes (0x5)
0000: .....
== Info: TLSv1.2 (OUT), TLS change cipher, Client hello (1):
=> Send SSL data, 1 bytes (0x1)
0000: .
=> Send SSL data, 5 bytes (0x5)
0000: ....(
== Info: TLSv1.2 (OUT), TLS handshake, Finished (20):
=> Send SSL data, 16 bytes (0x10)
0000: ........U.\k..:.
<= Recv SSL data, 5 bytes (0x5)
0000: .....
== Info: TLSv1.2 (IN), TLS change cipher, Client hello (1):
<= Recv SSL data, 1 bytes (0x1)
0000: .
<= Recv SSL data, 5 bytes (0x5)
0000: ....(
== Info: TLSv1.2 (IN), TLS handshake, Finished (20):
<= Recv SSL data, 16 bytes (0x10)
0000: .......7_.5.....
== Info: SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
== Info: ALPN, server accepted to use h2
== Info: Server certificate:
== Info:  subject: C=Unknown; ST=Unknown; L=Unknown; O=rv; OU=Unknown; CN=Unknown
== Info:  start date: Jul 25 08:41:32 2018 GMT
== Info:  expire date: Jul 25 08:41:32 2019 GMT
== Info:  issuer: C=Unknown; ST=Unknown; L=Unknown; O=rv; OU=Unknown; CN=Unknown
== Info:  SSL certificate verify result: self signed certificate (18), continuing anyway.
== Info: Using HTTP2, server supports multi-use
== Info: Connection state changed (HTTP/2 confirmed)
== Info: Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
=> Send SSL data, 5 bytes (0x5)
0000: ....0
=> Send SSL data, 5 bytes (0x5)
0000: ....-
=> Send SSL data, 5 bytes (0x5)
0000: ....%
== Info: Using Stream ID: 1 (easy handle 0x3345c0)
=> Send SSL data, 5 bytes (0x5)
0000: ....N
=> Send header, 84 bytes (0x54)
0000: GET /Servlet4Push/sonicServer HTTP/1.1
0028: Host: sonicserver1.com:8681
0045: Accept: */*
0052:
<= Recv SSL data, 5 bytes (0x5)
0000: .....
== Info: http2 error: Remote peer returned unexpected data while we expected SETTINGS frame.  Perhaps, peer does not support HTTP/2 properly.
=> Send SSL data, 5 bytes (0x5)
0000: ....:
== Info: Curl_http_done: called premature == 1
== Info: Closing connection 0
=> Send SSL data, 5 bytes (0x5)
0000: .....
== Info: TLSv1.2 (OUT), TLS alert, Client hello (1):
=> Send SSL data, 2 bytes (0x2)
0000: 
```
### curl/libcurl version
```
curl 7.60.0 (Linux) libcurl/7.52.1 OpenSSL/1.0.2l zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Release-Date: 2018-05-16
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```
### operating system
Raspbian stretch 9.4 and I've also tested this for Ubuntu 18.04

**Comment by bagder** [comment] 2018-09-11 15:17
> curl 7.60.0 (Linux) libcurl/7.52.1

That's an interesting mix.

curl usually has no problems with push. What server software and version is this?

**Comment by hatimuradin** [comment] 2018-09-11 15:36
Java Servlet 4, GlassFish Server Open Source Edition 5.
I also checked curl 7.61 and libcurl 7.61 mix and still I got same error.

**Comment by jay** [comment] 2018-09-11 15:47
I was able to reproduce like 1 out of 3, the server is closing the connection. Is it normally reliable in Firefox and Chrome? In success cases the server normally replies to SETTINGS, HEADERS with two SETTINGS but in the fail case it just closes. AFAICS curl is sending the same frames and data in the same order in all cases.

**Comment by hatimuradin** [comment] 2018-09-11 15:57
Jay's comment is a bit hard to understand according to AFAICS. But as I tested it's reliable in Firefox and Chrome. The server is not trusted in a global CA but due to these two lines in the example file:
```
curl_easy_setopt(hnd, CURLOPT_SSL_VERIFYPEER, 0L);
curl_easy_setopt(hnd, CURLOPT_SSL_VERIFYHOST, 0L);
```
I think I should work without problem just like browsers. Do you have any idea what's happening in this case? Thanks for your attention.

**Comment by jay** [comment] 2018-09-11 16:03
A packet capture shows the server closing the connection without sending anything, and since curl seems to be sending the same data in the same frames in the same order in all cases I think the server is at fault.

**Comment by hatimuradin** [comment] 2018-09-11 16:12
Do you have any suggestion for a test server that pushes files so that I can ensure my curl code correctness?

**Comment by hatimuradin** [comment] 2018-09-12 05:15
### As you suggested I tried with nghttpd 
Version: 1.33.0-DEV
My command for running server: `nghttpd -v -d . --push=/=1.png 8444 pt2.key pt2.crt`
libcurl server push example changing uri to: `curl_easy_setopt(hnd, CURLOPT_URL, "https://localhost:8444");`
### I expected the following
I expected that curl create a file push0 in his running directory that contains 1.png file.
This is the curl log:
```
== Info: Rebuilt URL to: https://localhost:8444/
== Info:   Trying 127.0.0.1...
== Info: TCP_NODELAY set
== Info: Connected to localhost (127.0.0.1) port 8444 (#0)
== Info: found 134 certificates in /etc/ssl/certs/ca-certificates.crt
== Info: found 406 certificates in /etc/ssl/certs
== Info: ALPN, offering h2
== Info: ALPN, offering http/1.1
== Info: SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
== Info: 	 server certificate verification SKIPPED
== Info: 	 server certificate status verification SKIPPED
== Info: 	 common name: localhost (matched)
== Info: 	 server certificate expiration date OK
== Info: 	 server certificate activation date OK
== Info: 	 certificate public key: RSA
== Info: 	 certificate version: #3
== Info: 	 subject: C=IR,ST=Tehran,L=Tehran,O=PooyeshTaradeh,OU=Software,CN=localhost,EMAIL=1@gmail.com
== Info: 	 start date: Sat, 08 Sep 2018 11:32:11 GMT
== Info: 	 expire date: Sun, 08 Sep 2019 11:32:11 GMT
== Info: 	 issuer: C=IR,ST=Tehran,L=Tehran,O=PooyeshTaradeh,OU=Software,CN=localhost,EMAIL=1@gmail.com
== Info: 	 compression: NULL
== Info: ALPN, server accepted to use h2
== Info: Using HTTP2, server supports multi-use
== Info: Connection state changed (HTTP/2 confirmed)
== Info: Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
== Info: Using Stream ID: 1 (easy handle 0x563d10bdb870)
=> Send header, 51 bytes (0x33)
0000: GET / HTTP/2
000e: Host: localhost:8444
0024: Accept: */*
0031: 
== Info: Connection state changed (MAX_CONCURRENT_STREAMS updated)!
<= Recv header, 13 bytes (0xd)
0000: HTTP/2 200 
<= Recv header, 36 bytes (0x24)
0000: server: nghttpd nghttp2/1.33.0-DEV
<= Recv header, 29 bytes (0x1d)
0000: cache-control: max-age=3600
<= Recv header, 37 bytes (0x25)
0000: date: Wed, 12 Sep 2018 05:11:17 GMT
<= Recv header, 20 bytes (0x14)
0000: content-length: 13
<= Recv header, 46 bytes (0x2e)
0000: last-modified: Wed, 12 Sep 2018 05:11:13 GMT
<= Recv header, 25 bytes (0x19)
0000: content-type: text/html
<= Recv header, 2 bytes (0x2)
0000: 
<= Recv data, 13 bytes (0xd)
0000: Hello World!.
== Info: Connection #0 to host localhost left intact
```
And this is the nghttpd log:
```
IPv4: listen 0.0.0.0:8444
IPv6: listen :::8444
[ALPN] client offers:
 * h2
 * http/1.1
SSL/TLS handshake completed
The negotiated protocol: h2
[id=1] [  2.481] send SETTINGS frame <length=6, flags=0x00, stream_id=0>
          (niv=1)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
[id=1] [  2.481] recv SETTINGS frame <length=18, flags=0x00, stream_id=0>
          (niv=3)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
          [SETTINGS_INITIAL_WINDOW_SIZE(0x04):1073741824]
          [SETTINGS_ENABLE_PUSH(0x02):1]
[id=1] [  2.481] recv WINDOW_UPDATE frame <length=4, flags=0x00, stream_id=0>
          (window_size_increment=1073676289)
[id=1] [  2.481] recv (stream_id=1) :method: GET
[id=1] [  2.481] recv (stream_id=1) :path: /
[id=1] [  2.481] recv (stream_id=1) :scheme: https
[id=1] [  2.481] recv (stream_id=1) :authority: localhost:8444
[id=1] [  2.481] recv (stream_id=1) accept: */*
[id=1] [  2.481] recv HEADERS frame <length=20, flags=0x05, stream_id=1>
          ; END_STREAM | END_HEADERS
          (padlen=0)
          ; Open new stream
[id=1] [  2.481] send SETTINGS frame <length=0, flags=0x01, stream_id=0>
          ; ACK
          (niv=0)
[id=1] [  2.481] send PUSH_PROMISE frame <length=24, flags=0x04, stream_id=1>
          ; END_HEADERS
          (padlen=0, promised_stream_id=2)
          :method: GET
          :path: 1.png
          :scheme: https
          :authority: localhost:8444
[id=1] [  2.481] send HEADERS frame <length=95, flags=0x04, stream_id=1>
          ; END_HEADERS
          (padlen=0)
          ; First response header
          :status: 200
          server: nghttpd nghttp2/1.33.0-DEV
          cache-control: max-age=3600
          date: Wed, 12 Sep 2018 05:11:17 GMT
          content-length: 13
          last-modified: Wed, 12 Sep 2018 05:11:13 GMT
          content-type: text/html
[id=1] [  2.481] send HEADERS frame <length=42, flags=0x04, stream_id=2>
          ; END_HEADERS
          (padlen=0)
          ; First push response header
          :status: 200
          server: nghttpd nghttp2/1.33.0-DEV
          cache-control: max-age=3600
          date: Wed, 12 Sep 2018 05:11:17 GMT
          content-length: 14
          last-modified: Tue, 11 Sep 2018 09:37:14 GMT
          content-type: image/png
[id=1] [  2.482] send DATA frame <length=13, flags=0x01, stream_id=1>
          ; END_STREAM
[id=1] [  2.482] stream_id=1 closed
[id=1] [  2.482] send DATA frame <length=14, flags=0x01, stream_id=2>
          ; END_STREAM
[id=1] [  2.482] stream_id=2 closed
[id=1] [  2.482] recv SETTINGS frame <length=0, flags=0x01, stream_id=0>
          ; ACK
          (niv=0)
[id=1] [  2.482] recv RST_STREAM frame <length=4, flags=0x00, stream_id=2>
          (error_code=PROTOCOL_ERROR(0x01))
[id=1] [  2.482] closed

```
### curl/libcurl version
```
curl 7.61.1 (x86_64-pc-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.0g zlib/1.2.11 nghttp2/1.33.0-DEV
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy
```
### operating system
uname -a: 
```
Linux PT2 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
lsb_release -a: Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

**Comment by bagder** [comment] 2018-09-12 09:44
> I expected that curl create a file push0 in his running directory

So what did your libcurl code look like?

**Comment by hatimuradin** [comment] 2018-09-12 09:56
> So what did your libcurl code look like?

```
/***************************************************************************
 *                                  _   _ ____  _
 *  Project                     ___| | | |  _ \| |
 *                             / __| | | | |_) | |
 *                            | (__| |_| |  _ <| |___
 *                             \___|\___/|_| \_\_____|
 *
 * Copyright (C) 1998 - 2017, Daniel Stenberg, <daniel@haxx.se>, et al.
 *
 * This software is licensed as described in the file COPYING, which
 * you should have received as part of this distribution. The terms
 * are also available at https://curl.haxx.se/docs/copyright.html.
 *
 * You may opt to use, copy, modify, merge, publish, distribute and/or sell
 * copies of the Software, and permit persons to whom the Software is
 * furnished to do so, under the terms of the COPYING file.
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
 * KIND, either express or implied.
 *
 ***************************************************************************/
/* <DESC>
 * HTTP/2 server push
 * </DESC>
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* somewhat unix-specific */
#include <sys/time.h>
#include <unistd.h>

/* curl stuff */
#include <curl/curl.h>

#ifndef CURLPIPE_MULTIPLEX
#error "too old libcurl, can't do HTTP/2 server push!"
#endif

static
void dump(const char *text, unsigned char *ptr, size_t size,
          char nohex)
{
  size_t i;
  size_t c;

  unsigned int width = 0x10;

  if(nohex)
    /* without the hex output, we can fit more on screen */
    width = 0x40;

  fprintf(stderr, "%s, %lu bytes (0x%lx)\n",
          text, (unsigned long)size, (unsigned long)size);

  for(i = 0; i<size; i += width) {

    fprintf(stderr, "%4.4lx: ", (unsigned long)i);

    if(!nohex) {
      /* hex not disabled, show it */
      for(c = 0; c < width; c++)
        if(i + c < size)
          fprintf(stderr, "%02x ", ptr[i + c]);
        else
          fputs("   ", stderr);
    }

    for(c = 0; (c < width) && (i + c < size); c++) {
      /* check for 0D0A; if found, skip past and start a new line of output */
      if(nohex && (i + c + 1 < size) && ptr[i + c] == 0x0D &&
         ptr[i + c + 1] == 0x0A) {
        i += (c + 2 - width);
        break;
      }
      fprintf(stderr, "%c",
              (ptr[i + c] >= 0x20) && (ptr[i + c]<0x80)?ptr[i + c]:'.');
      /* check again for 0D0A, to avoid an extra \n if it's at width */
      if(nohex && (i + c + 2 < size) && ptr[i + c + 1] == 0x0D &&
         ptr[i + c + 2] == 0x0A) {
        i += (c + 3 - width);
        break;
      }
    }
    fputc('\n', stderr); /* newline */
  }
}

static
int my_trace(CURL *handle, curl_infotype type,
             char *data, size_t size,
             void *userp)
{
  const char *text;
  (void)handle; /* prevent compiler warning */
  (void)userp;
  switch(type) {
  case CURLINFO_TEXT:
    fprintf(stderr, "== Info: %s", data);
    /* FALLTHROUGH */
  default: /* in case a new one is introduced to shock us */
    return 0;

  case CURLINFO_HEADER_OUT:
    text = "=> Send header";
    break;
  case CURLINFO_DATA_OUT:
    text = "=> Send data";
    break;
  case CURLINFO_SSL_DATA_OUT:
    text = "=> Send SSL data";
    break;
  case CURLINFO_HEADER_IN:
    text = "<= Recv header";
    break;
  case CURLINFO_DATA_IN:
    text = "<= Recv data";
    break;
  case CURLINFO_SSL_DATA_IN:
    text = "<= Recv SSL data";
    break;
  }

  dump(text, (unsigned char *)data, size, 1);
  return 0;
}

#define OUTPUTFILE "dl"

static void setup(CURL *hnd)
{
  FILE *out = fopen(OUTPUTFILE, "wb");

  /* write to this file */
  curl_easy_setopt(hnd, CURLOPT_WRITEDATA, out);

  /* set the same URL */
  curl_easy_setopt(hnd, CURLOPT_URL, "https://localhost:8444");

  /* please be verbose */
  curl_easy_setopt(hnd, CURLOPT_VERBOSE, 1L);
  curl_easy_setopt(hnd, CURLOPT_DEBUGFUNCTION, my_trace);

  /* HTTP/2 please */
  curl_easy_setopt(hnd, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_2_0);

  /* we use a self-signed test server, skip verification during debugging */
  curl_easy_setopt(hnd, CURLOPT_SSL_VERIFYPEER, 0L);
  curl_easy_setopt(hnd, CURLOPT_SSL_VERIFYHOST, 0L);

#if (CURLPIPE_MULTIPLEX > 0)
  /* wait for pipe connection to confirm */
  curl_easy_setopt(hnd, CURLOPT_PIPEWAIT, 1L);
#endif

}

/* called when there's an incoming push */
static int server_push_callback(CURL *parent,
                                CURL *easy,
                                size_t num_headers,
                                struct curl_pushheaders *headers,
                                void *userp)
{
  char *headp;
  size_t i;
  int *transfers = (int *)userp;
  char filename[128];
  FILE *out;
  static unsigned int count = 0;

  (void)parent; /* we have no use for this */

  snprintf(filename, 128, "push%u", count++);

  /* here's a new stream, save it in a new file for each new push */
  out = fopen(filename, "wb");

  /* write to this file */
  curl_easy_setopt(easy, CURLOPT_WRITEDATA, out);

  fprintf(stderr, "**** push callback approves stream %u, got %lu headers!\n",
          count, (unsigned long)num_headers);

  for(i = 0; i<num_headers; i++) {
    headp = curl_pushheader_bynum(headers, i);
    fprintf(stderr, "**** header %lu: %s\n", (unsigned long)i, headp);
  }

  headp = curl_pushheader_byname(headers, ":path");
  if(headp) {
    fprintf(stderr, "**** The PATH is %s\n", headp /* skip :path + colon */);
  }

  (*transfers)++; /* one more */
  return CURL_PUSH_OK;
}


/*
 * Download a file over HTTP/2, take care of server push.
 */
int main(void)
{
  CURL *easy;
  CURLM *multi_handle;
  int still_running; /* keep number of running handles */
  int transfers = 1; /* we start with one */
  struct CURLMsg *m;

  /* init a multi stack */
  multi_handle = curl_multi_init();

  easy = curl_easy_init();

  /* set options */
  setup(easy);

  /* add the easy transfer */
  curl_multi_add_handle(multi_handle, easy);

  curl_multi_setopt(multi_handle, CURLMOPT_PIPELINING, CURLPIPE_MULTIPLEX);
  curl_multi_setopt(multi_handle, CURLMOPT_PUSHFUNCTION, server_push_callback);
  curl_multi_setopt(multi_handle, CURLMOPT_PUSHDATA, &transfers);

  /* we start some action by calling perform right away */
  curl_multi_perform(multi_handle, &still_running);

  do {
    struct timeval timeout;
    int rc; /* select() return code */
    CURLMcode mc; /* curl_multi_fdset() return code */

    fd_set fdread;
    fd_set fdwrite;
    fd_set fdexcep;
    int maxfd = -1;

    long curl_timeo = -1;

    FD_ZERO(&fdread);
    FD_ZERO(&fdwrite);
    FD_ZERO(&fdexcep);

    /* set a suitable timeout to play around with */
    timeout.tv_sec = 1;
    timeout.tv_usec = 0;

    curl_multi_timeout(multi_handle, &curl_timeo);
    if(curl_timeo >= 0) {
      timeout.tv_sec = curl_timeo / 1000;
      if(timeout.tv_sec > 1)
        timeout.tv_sec = 1;
      else
        timeout.tv_usec = (curl_timeo % 1000) * 1000;
    }

    /* get file descriptors from the transfers */
    mc = curl_multi_fdset(multi_handle, &fdread, &fdwrite, &fdexcep, &maxfd);

    if(mc != CURLM_OK) {
      fprintf(stderr, "curl_multi_fdset() failed, code %d.\n", mc);
      break;
    }

    /* On success the value of maxfd is guaranteed to be >= -1. We call
       select(maxfd + 1, ...); specially in case of (maxfd == -1) there are
       no fds ready yet so we call select(0, ...) --or Sleep() on Windows--
       to sleep 100ms, which is the minimum suggested value in the
       curl_multi_fdset() doc. */

    if(maxfd == -1) {
#ifdef _WIN32
      Sleep(100);
      rc = 0;
#else
      /* Portable sleep for platforms other than Windows. */
      struct timeval wait = { 0, 100 * 1000 }; /* 100ms */
      rc = select(0, NULL, NULL, NULL, &wait);
#endif
    }
    else {
      /* Note that on some platforms 'timeout' may be modified by select().
         If you need access to the original value save a copy beforehand. */
      rc = select(maxfd + 1, &fdread, &fdwrite, &fdexcep, &timeout);
    }

    switch(rc) {
    case -1:
      /* select error */
      break;
    case 0:
    default:
      /* timeout or readable/writable sockets */
      curl_multi_perform(multi_handle, &still_running);
      break;
    }

    /*
     * A little caution when doing server push is that libcurl itself has
     * created and added one or more easy handles but we need to clean them up
     * when we are done.
     */

    do {
      int msgq = 0;;
      m = curl_multi_info_read(multi_handle, &msgq);
      if(m && (m->msg == CURLMSG_DONE)) {
        CURL *e = m->easy_handle;
        transfers--;
        curl_multi_remove_handle(multi_handle, e);
        curl_easy_cleanup(e);
      }
    } while(m);

  } while(transfers); /* as long as we have transfers going */

  curl_multi_cleanup(multi_handle);


  return 0;
}
```

**Comment by bagder** [comment] 2018-09-12 09:58
So the `http2-serverpush.c` example unmodified?

**Comment by hatimuradin** [comment] 2018-09-12 10:01
> So the http2-serverpush.c example unmodified?

As i said just modified the uri from 
`curl_easy_setopt(hnd, CURLOPT_URL, "https://localhost:8443/index.html");`
to:
`  curl_easy_setopt(hnd, CURLOPT_URL, "https://localhost:8444");
`
8444 is the port number my nghttpd listening on it.

**Comment by bagder** [comment] 2018-09-18 11:43
Can you trigger this problem with nghttpd or any public URL? I can't reproduce this.

**Comment by jmccl** [comment] 2018-10-12 00:04
This may or may not be related. I'm getting a similar problem on Manjaro when trying to update Visual Studio Code. 

> $ curl -V
curl 7.61.1 (x86_64-pc-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) libssh2/1.8.0 nghttp2/1.33.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
$ curl https://az764295.vo.msecnd.net/stable/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/code-stable-1538751479.tar.gz
curl: (16) Error in the HTTP2 framing layer

It works OK on a Debian and Redhat(ish) distro that have different versions of curl.

I'll open another issues if you want / think this is unrelated.

**Comment by bagder** [comment] 2018-10-12 06:05
> It works OK on a Debian and Redhat(ish) distro that have different versions of curl.

That command line also works for me with current git and curl 7.61.0 on Debian. (and on 7.47.0 which I happened to have installed somewhere and tested with)

> I'll open another issues if you want / think this is unrelated.

Yes please. It might be different, since @hatimuradin's issue involves push and yours doesn't. I think opening a separate is the sensible thing here.

**Comment by bagder** [comment] 2018-10-18 21:45
No answer for a month to an outstanding question.

**Closed by bagder** 2018-10-18 21:45 UTC
Labels: HTTP/2, needs-info-or-update
