### ISSUE TITLE
early response causes sslhandshake to hang?

### ISSUE THREAD

**Issue by danjohansson** [curl/curl#6785] opened 2021-03-24 12:24 UTC
In the log below (last two lines) the server seem to send a response before the request is complete by initiating the tls handshake. When this happens curl does not continue the handshake and the communication hangs.

For some requests with the same server the response comes after the request is complete, then all works as expected.

client: Linux 5.11.7-arch1-1
server:  Microsoft-IIS/8.5

```
curl --cert-type p12 --cert /tmp/cert.p12:<xxxxxxxxxxxx> -X POST -d @/tmp/soap-body.xml -H "SOAPAction: \"<xxxxxxxxxxxx>\"" -H "Content-Type: text/xml; charset=utf-8" -vvvvv https://<xxxxxxxxxxxx> 

*   Trying <xxxxxxxxxxxx>...
* Connected to <xxxxxxxxxxxx> port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / AES256-SHA
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: <xxxxxxxxxxxx>
*  start date: Aug 25 00:00:00 2020 GMT
*  expire date: Nov 16 12:00:00 2022 GMT
*  subjectAltName: host "<xxxxxxxxxxxx>" matched cert's "<xxxxxxxxxxxx>"
*  issuer: <xxxxxxxxxxxx>
*  SSL certificate verify ok.
> POST /<xxxxxxxxxxxx> HTTP/1.1
> Host: <xxxxxxxxxxxx>
> User-Agent: curl/7.75.0
> Accept: */*
> SOAPAction: "<xxxxxxxxxxxx>"
> Content-Type: text/xml; charset=utf-8
> Content-Length: 45137
> 
* TLSv1.2 (IN), TLS handshake, Hello request (0):
* We are completely uploaded and fine
```

**Comment by jay** [comment] 2021-03-25 06:36
The [hellorequest](https://tools.ietf.org/html/rfc5246#section-7.4.1.1) from what I read is a request to renegotiate. The client may ignore it but if it does the server may terminate the connection. What is the `curl -V`?

**Comment by bagder** [comment] 2021-03-25 07:10
Yes that seems like are reasonable suspicion. Since the HTTP part cannot be done at all until *after* the handshake is done, the description of this issue is a bit hard to decipher.

Client certificate auth is often triggered by a renegotiation I believe.

**Comment by danjohansson** [comment] 2021-03-25 08:33
@jay here is the version information
```
> curl -V
curl 7.75.0 (x86_64-pc-linux-gnu) libcurl/7.75.0 OpenSSL/1.1.1j zlib/1.2.11 zstd/1.4.9 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0
Release-Date: 2021-02-03
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

**Comment by danjohansson** [comment] 2021-03-25 08:48
@bagder I will try to give more context to what I am doing.
I'm doing an upload to a server that requires a client certificate. The upload succeeds but when I get the response too soon the renegotiation is started before the upload is complete. It then hangs. Curl does not respond with a client hello.
There seems to be a racecondition with this server because sometimes the response does succeed for the same data. When it does the `Hello request` is logged after `We are completely uploaded and fine`
Also if I inspect the network traffic I see that the curl log is in the same order as the packets for the `hello request` and upload completion.

Let me know if I need to provide more information.
Thanks

**Comment by jay** [comment] 2021-03-26 07:27
Is it possible that you could use [SSLKEYLOGFILE](https://everything.curl.dev/usingcurl/tls/sslkeylogfile) to look into this further? I'm interested in whether it's the client or server hanging, but I don't have a way to reproduce it here.

**Comment by danjohansson** [comment] 2021-03-27 06:26
@jay here is a pcap of a session that failed:
[failed.pcap.zip](https://github.com/curl/curl/files/6215249/failed.pcap.zip)

I noticed that the hello request from the server comes before the POST is complete in both successful and failed sessions (I said differently in a previous comment). But the `hello request` is always logged before the `we are completely uploaded and fine` when the session hangs.

**Comment by jay** [comment] 2021-03-27 06:48
~~~
17	2021-03-26 10:19:38.039393	193.182.50.70	192.168.86.55	TLSv1.2	123	Finished
...
43	2021-03-26 10:19:38.133227	193.182.50.70	192.168.86.55	TLSv1.2	107	Hello Request
...
46	2021-03-26 10:19:38.133665	192.168.86.55	193.182.50.70	HTTP/XML	733	POST /rdtws/secure/ExternalWebServiceSecure.asmx HTTP/1.1 
~~~

It looks like a race condition. The server says the TLS handshake is finished so curl prepares and sends the request. However at almost the exact same time that happens a TLS hello request is received. Then curl is waiting for an HTTP response from the server while at the same time the server is waiting for a handshake response from curl (presumably since nothing else happens but keep alives). I don't know what curl could do here, I would expect it to be handled by OpenSSL.

**Comment by danjohansson** [comment] 2021-03-27 07:20
@jay I think you are right. Thanks for looking into it.

**Comment by jay** [comment] 2021-03-27 17:54
Maybe we are doing something wrong but I don't know what. OpenSSL says renegotiations are supposed to be transparent for [SSL_read](https://www.openssl.org/docs/man1.1.1/man3/SSL_read.html)/[SSL_write](https://www.openssl.org/docs/man1.1.1/man3/SSL_write.html). Could you try [jay:ossl_dbg_sendrecv](https://github.com/curl/curl/compare/master...jay:ossl_dbg_sendrecv?expand=1) and post the verbose output?

**Comment by danjohansson** [comment] 2021-03-28 07:59
```
*   Trying 193.182.50.70:443...
* Connected to rdtoc.transportstyrelsen.se (193.182.50.70) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / AES256-SHA
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=SE; L=Norrkoping; O=Transportstyrelsen; OU=IT; CN=*.transportstyrelsen.se
*  start date: Aug 25 00:00:00 2020 GMT
*  expire date: Nov 16 12:00:00 2022 GMT
*  subjectAltName: host "rdtoc.transportstyrelsen.se" matched cert's "*.transportstyrelsen.se"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
ossl_send BEGIN
ossl_send END
> POST /rdtws/secure/ExternalWebServiceSecure.asmx HTTP/1.1
> Host: rdtoc.transportstyrelsen.se
> User-Agent: curl/7.76.0-DEV
> Accept: */*
> SOAPAction: "http://www.vv.se/rdt/secure/LevereraForeteelse"
> Content-Type: text/xml; charset=utf-8
> Content-Length: 48141
> 
ossl_send BEGIN
ossl_send SSL_ERROR_WANT_WRITE
ossl_recv BEGIN
* TLSv1.2 (IN), TLS handshake, Hello request (0):
ossl_recv SSL_ERROR_WANT_READ
ossl_recv SSL_ERROR_WANT_WRITE
ossl_send BEGIN
ossl_send END
* We are completely uploaded and fine
```

**Comment by danjohansson** [comment] 2021-03-28 08:03
A successful session looks like this:
```
*   Trying 193.182.50.70:443...
* Connected to rdtoc.transportstyrelsen.se (193.182.50.70) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / AES256-SHA
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=SE; L=Norrkoping; O=Transportstyrelsen; OU=IT; CN=*.transportstyrelsen.se
*  start date: Aug 25 00:00:00 2020 GMT
*  expire date: Nov 16 12:00:00 2022 GMT
*  subjectAltName: host "rdtoc.transportstyrelsen.se" matched cert's "*.transportstyrelsen.se"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
ossl_send BEGIN
ossl_send END
> POST /rdtws/secure/ExternalWebServiceSecure.asmx HTTP/1.1
> Host: rdtoc.transportstyrelsen.se
> User-Agent: curl/7.76.0-DEV
> Accept: */*
> SOAPAction: "http://www.vv.se/rdt/secure/LevereraForeteelse"
> Content-Type: text/xml; charset=utf-8
> Content-Length: 48141
> 
ossl_send BEGIN
ossl_send SSL_ERROR_WANT_WRITE
ossl_send BEGIN
ossl_send END
* We are completely uploaded and fine
ossl_recv BEGIN
* TLSv1.2 (IN), TLS handshake, Hello request (0):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
ossl_recv SSL_ERROR_WANT_READ
ossl_recv SSL_ERROR_WANT_WRITE
ossl_recv BEGIN
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
ossl_recv SSL_ERROR_WANT_READ
ossl_recv SSL_ERROR_WANT_WRITE
ossl_recv BEGIN
* TLSv1.2 (IN), TLS handshake, Finished (20):
ossl_recv SSL_ERROR_WANT_READ
ossl_recv SSL_ERROR_WANT_WRITE
ossl_recv BEGIN
ossl_recv END
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
...
```

**Comment by danjohansson** [comment] 2021-03-29 05:19
@jay I get the same result with the latest PR. I guess this means that we are waiting for openssl to continue the handshake but it doesn't?

**Comment by jay** [comment] 2021-03-29 06:50
> @jay I get the same result with the latest PR. I guess this means that we are waiting for openssl to continue the handshake but it doesn't?

I made a mistake in the first commit so you may have seen some extra SSL_WANT_... in the output. I adjusted both of your verbose output logs to remove those extra incorrect lines, which is fixed in the latest commit (ie the one you just tested) and there's no reason to repost the results.

I reported this issue to OpenSSL at openssl/openssl#14722

**Comment by bagder** [comment] 2021-08-16 07:05
Does it really serve any purpose to keep this issue open if we think this is an OpenSSL problem? Nothing's going to happen here...

**Closed** 2021-08-18 07:43 UTC
Labels: SSL/TLS

**Comment by danjohansson** [comment] 2022-01-10 11:05
I have looked at this issue a bit closer now. And I think the problem lies in that Curl does not call `ossl_recv` again even though the last call to it returned SSL_ERROR_WANT_READ.

The api documentation for `ssl_write` and `ssl_read` states that upon receiving the error the operation should be retried.
https://www.openssl.org/docs/man1.1.1/man3/SSL_read.html (see section about nonblocking bio)

The following commit 1650b5f818dd66200fe8e7c1e097459b69a5a003 make it so that ossl_recv is called again and the problem cannot be reproduced with this fix.

Though the fix works, it seems to generate a lot of calls to ossl_recv, and perhaps it should be retried differently?

@jay

**Comment by jay** [comment] 2022-01-10 21:33
> I have looked at this issue a bit closer now. And I think the problem lies in that Curl does not call `ossl_recv` again even though the last call to it returned SSL_ERROR_WANT_READ.
> 
> The api documentation for `ssl_write` and `ssl_read` states that upon receiving the error the operation should be retried. https://www.openssl.org/docs/man1.1.1/man3/SSL_read.html (see section about nonblocking bio)

This is tricky. We are following their documentation. When SSL_read returns SSL_ERROR_WANT_READ it is supposed to mean (at least in our case) that everything that could be read has been read and therefore we wait on the socket:

_The calling process then must repeat the call after taking appropriate action to satisfy the needs of the read function. The action depends on the underlying BIO. **When using a nonblocking socket, nothing is to be done,** but select() can be used to check for the required condition_

At this point in the repro curl is waiting not just to receive data but also to send it because of the SSL_write that failed earlier. According to the ossl bug basically they seem to be saying they can't send back a handshake acknowledgement during the SSL_read because of the incomplete SSL_write. If a record was already partially sent (which in this case it wasn't but let's give them the odds) then maybe it is required that until the rest of that record is sent the handshake cannot be sent. So then why can't they send the next message in the handshake during SSL_write? IMO this is a bug in OpenSSL and the burden is on them.

**Comment by danjohansson** [comment] 2022-01-13 16:22
@jay Thanks that cleared things up for me :+1:
