### ISSUE TITLE
(92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2) on tesla.com

### ISSUE THREAD

**Issue by robinbrisa** [curl/curl#12301] opened 2023-11-09 22:43 UTC
### I did this

`curl -v https://www.tesla.com/`

**Response :**

```
*   Trying 2a02:26f0:2b00:3ac::700:443...
* Connected to www.tesla.com (2a02:26f0:2b00:3ac::700) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=Texas; L=Austin; O=TESLA, INC.; CN=*.tesla.com
*  start date: Mar 20 00:00:00 2023 GMT
*  expire date: Mar 21 23:59:59 2024 GMT
*  subjectAltName: host "www.tesla.com" matched cert's "*.tesla.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=GeoTrust RSA CA 2018
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7ef770)
> GET / HTTP/2
> Host: www.tesla.com
> user-agent: curl/7.74.0
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
* HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
* stopped the pause stream!
* Connection #0 to host www.tesla.com left intact
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
```

I also tried with a full cURL command dumped from the Chrome dev tools :

```
curl 'https://www.tesla.com/inventory/api/v1/inventory-results?query=\{%22query%22:\{%22model%22:%22ms%22,%22condition%22:%22new%22,%22options%22:\[\],%22arrangeby%22:%22Price%22,%22order%22:%22asc%22,%22market%22:%22FR%22,%22language%22:%22fr%22,%22super_region%22:%22europe%22,%22zip%22:61122\},%22offset%22:0,%22count%22:50,%22outsideOffset%22:0,%22outsideSearch%22:false\}' \
  -H 'authority: www.tesla.com' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  -H 'accept-language: fr,en-US;q=0.9,en;q=0.8,fr-FR;q=0.7' \
  -H 'cache-control: max-age=0' \
  -H $'cookie: <cookies...> \
  -H 'sec-ch-ua: "Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: document' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-site: none' \
  -H 'sec-fetch-user: ?1' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36' \
  -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" \
  --compressed
```

Same results :

`curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)`

### I expected the following

A successful response

### curl/libcurl version

curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1w zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
curl 7.77.0-DEV (x86_64-pc-linux-musl) libcurl/7.77.0-DEV OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 libssh2/1.9.0 nghttp2/1.41.0
curl 8.4.0 (x86_64-pc-linux-musl) libcurl/8.4.0 OpenSSL/3.1.3 zlib/1.2.13 brotli/1.0.9 libidn2/2.3.4 libssh2/1.10.0 nghttp2/1.57.0
curl 8.4.0 (x86_64-w64-mingw32) libcurl/8.4.0 OpenSSL/3.1.4 (Schannel) zlib/1.3 brotli/1.1.0 zstd/1.5.5 WinIDN libssh2/1.11.0 nghttp2/1.58.0 ngtcp2/1.0.1 nghttp3/1.0.0

### operating system

Debian 11, Windows 11, Docker

**Comment by dfandrich** [comment] 2023-11-09 23:07
This is probably a dupe of one of [these recent issues](https://github.com/curl/curl/issues?q=is%3Aissue++%22stream+0+was+not+closed+cleanly%22).

**Comment by robinbrisa** [comment] 2023-11-09 23:13
I did check those already, the most recent identical issues seem to be caused by the fact that curl was blocked by the server and setting the user agent would fix the problem. However, in my case, it does not work even when sending the full HTTP headers dumped from a browser.

**Comment by pierrepinon** [comment] 2023-11-10 09:47
Same that #12114, the server send RST_FRAME in stream

`[  0.123] recv RST_STREAM frame <length=4, flags=0x00, stream_id=13>
          (error_code=INTERNAL_ERROR(0x02))`

**Comment by icing** [comment] 2023-11-10 10:50
Looks like some "browser only" protection running at tesla.com. It could make its decision based on all sorts of things.

It is not the projects goal to work around such site protections. We think they are ill advised, to be sure. If you find a bug in our use of the HTTP protocol, we'll be all ears.

**Closed by icing** 2023-11-10 10:50 UTC
Labels: not-a-bug

**Comment by robinbrisa** [comment] 2023-11-10 11:06
One interesting fact is that the request seems to work fine using libcurl 7.77.0 in PHP 8.1 running on Windows.

**Comment by icing** [comment] 2023-11-10 11:13
> One interesting fact is that the request seems to work fine using libcurl 7.77.0 in PHP 8.1 running on Windows.

Just built curl 7.77.0 locally and it shows the same behaviour with tesla.com. Could be the versions of ngtcp2 or openssl/schannel or other side effects that trigger the detection.

**Comment by pierrepinon** [comment] 2023-11-10 20:19
@icing I agree with you that is not the projects goal to works with site protections. This messages and issues was not the only one, other issues was opened about error with h2 stream. 

No body have facts if tesla release recently an website protection from curl or another requesting tools, so i think the issue need to be keep open the time of investigation. It's would be done by community not only by project's members.

Thx
