### ISSUE TITLE
Transfer-Encoding: chunked is forced even when Content-Length is set by CURLOPT_HTTPHEADER

### ISSUE THREAD

**Issue by tmkk** [curl/curl#5593] opened 2020-06-23 18:18 UTC
### I did this
Compiled and ran the following code:
```c
#include <curl/curl.h>
#include <assert.h>

static char *postdata = "postdata";
static int postsize = 8;

static size_t read_callback(char *buffer, size_t size, size_t nitems, void *userdata)
{
    assert(postsize <= size*nitems);

    int copied = 0;
    for(;postsize>0;postsize--) *buffer++ = *(postdata+copied++);
    return copied;
}

int main(void)
{
    struct curl_slist *headers = curl_slist_append(NULL, "Content-Length: 8");
    CURL *curl = curl_easy_init();
    curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);
    curl_easy_setopt(curl, CURLOPT_URL, "http://localhost/");
    curl_easy_setopt(curl, CURLOPT_POST, 1L);
    curl_easy_setopt(curl, CURLOPT_READFUNCTION, read_callback);
    curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
    curl_easy_setopt(curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_0);

    curl_easy_perform(curl);

    return 0;
}
```
and it fails to make a request because `Transfer-Encoding: chunked` is used on HTTP 1.0 request.
```
% ./a.out
*   Trying ::1:80...
* Connected to localhost (::1) port 80 (#0)
* Chunky upload is not supported by HTTP 1.0
```
### I expected the following
Actually `Content-Length` is known and chunked transfer is not required. On 7.65.3 and earlier it works properly.
```
% ./a.out
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 80 (#0)
> POST / HTTP/1.0
Host: localhost
Accept: */*
Content-Length: 8
Content-Type: application/x-www-form-urlencoded

< HTTP/1.1 200 OK
```

### curl/libcurl version
7.66.0 and later, including the latest 7.70.0. Probably caused by the commit 802aa5a

### operating system
macOS 10.12.6
```
% uname -a
Darwin venus.local 16.7.0 Darwin Kernel Version 16.7.0: Sun Jun  2 20:26:31 PDT 2019; root:xnu-3789.73.50~1/RELEASE_X86_64 x86_64
```

**Comment by bagder** [comment] 2020-06-23 18:42
I think the bug here is that curl tries to do a chunked request even when `CURL_HTTP_VERSION_1_0` is used.

You should however use `CURLOPT_INFILESIZE` rather than setting the HTTP header manually, to let curl know the size and pass on the right header.

**Comment by bagder** [comment] 2020-06-23 21:19
I did #5595 in an attempt to reproduce this, but it doesn't. It seems to show it already works...

**Comment by tmkk** [comment] 2020-06-24 03:00
Setting `CURLOPT_INFILESIZE` doesn't solve the issue (still the same error), but using `CURLOPT_POSTFIELDSIZE` does. Can we use the `CURLOPT_POSTFIELDSIZE` safely in case the post data is given by `CURLOPT_READFUNCTION`?

**Comment by bagder** [comment] 2020-06-24 13:38
Yes you can, it is for setting the size of the POST body no matter how that post body is provided.

**Comment by bagder** [comment] 2020-06-24 13:51
And I still can't understand why my test case in #5595 works (returns a failure) when I tried a POST using HTTP/1.0 without a set size. Meaning I can't reproduce this bug with current libcurl.

**Comment by tmkk** [comment] 2020-06-24 14:14
It seems the test make a POST request using `CURLOPT_CUSTOMREQUEST` (which is how `curl -X POST` [does](https://github.com/curl/curl/blob/master/src/tool_operate.c#L1745)). When `CURLOPT_CUSTOMREQUEST` is used, it seems libcurl never make a chunked request.

**Comment by bagder** [comment] 2020-06-24 14:19
I'm not sure what you're talking about. The existing test 1514 does a post with a read callback without setting the size, and verifies that this then gets done chunked.

In #5595 I did a slight alteration of that code to enforce HTTP/1.0 in the new test 1539, but when I run this libcurl properly detects that it has no size and wants HTTP/1.0, so it instead returns an error. As libcurl does not support that combo.

**Comment by tmkk** [comment] 2020-06-24 14:53
Sorry I'm confused. The test make a POST HTTP/1.0 request without setting a size, but the issue I report is about a behavior when a `Content-Length` header **is set** but it is by `CURLOPT_HTTPHEADER`. In that case a chunked request is not required, but libcurl detects the post size is unknown and tries to make a chunked request.

**Comment by jay** [comment] 2020-06-25 05:03
I would think that's expected. You are bypassing the API by setting the length via header.

**Comment by bagder** [comment] 2020-06-25 06:48
Yes, I don't think former behavior when not setting the size did much good - as it created a POST that most servers would reject. You can easily make the post work with both old and new libcurls by setting the POSTFIELDSIZE instead of the custom header.

**Comment by bagder** [comment] 2020-06-26 13:10
I think we can leave this behavior as-is, as "the right way" to do this post is working and it was working before.

**Comment by bagder** [comment] 2020-07-01 08:43
Closing, working as expected.

**Closed by bagder** 2020-07-01 08:43 UTC
Labels: HTTP

**Comment by behnamshayani** [comment] 2021-07-09 11:32
Sorry for commenting on a closed issue, CURL/PHP does not expose POSTFIELDSIZE option. It is only set when CURLOPT_POSTFIELDS is used:
http://git.php.net/?p=php-src.git;a=blob;f=ext/curl/interface.c;hb=HEAD#l2266

Do you think it is a bug for php team to expose POSTFIELDSIZE ?
