### ISSUE TITLE
CURLOPT_CAPATH does not default to NULL

### ISSUE THREAD

**Issue by abarnert-pg** [curl/curl#7056] opened 2021-05-12 18:19 UTC
### I did this

Build libcurl 7.76.1 against mbedtls 2.26.0, using `configure` on some platforms and `cmake` on others. Do not specify a `--with-ca-path`, `--with-ca-bundle`, or `--with-ca-fallback` or the cmake equivalents.

Use `curl_easy_*` to fetch https://example.com, after setting `CURLOPT_CAINFO` to the path to a valid CA store file, and not setting `CURLOPT_CAPATH`.

### I expected the following

According to the docs (https://curl.se/libcurl/c/CURLOPT_CAPATH.html as well as the locally built manpage), `CURLOPT_CAPATH` defaults to `NULL`. 

So, I expected that if I never set it (unless I'd passed some config flags to change the default behavior, which I didn't), it will be `NULL`. And mbedtls would then use my specified CA store bundle file, and not try to parse any directory, and my request would succeed.

### I observed instead

Libcurl tells mbedtls to parse my CA store file (which succeeds), and then tells it to parse a CA store directory.

On Android, the directory it passes (`/etc/ssl/certs/`) doesn't exist, so mbedtls returns an error attempting to parse it, and the code (lib/vtls/mbedtls.c:303) causes the whole operation to fail if either parse fails. So, all https requests fail with an mbedtls error about invalid CA certs. Which seems reasonable, except that it shouldn't have been passing a path in the first place.

On iOS and macOS, it passes a directory that does exist, so everything works—but it's adding more CAs that I didn't ask for. I have no reason to suspect Apple's CA store, but that's still not good, especially since it's not obvious things are working differently from what I expected, and the only way I even found out about it was debugging into the mbedtls interface code.

Explicitly setting `CURLOPT_CAPATH` to `NULL` works around the problem.

I haven't dug into where this path is coming from, but my guess would be that the configuration defaults to some kind of auto-detection? 

That behavior actually makes sense for building the app, if not necessarily for building the lib, it's just not what the documentation leads you to expect. Although, as a side issue, if it is meant to auto-detect and just work, the fact that it guesses a nonexistent path on Android cross-compiles is not great.

If I'm right that the directory is coming from configure/cmake, then the docs for ` CURLOPT_CAPATH` should not say that the default is `NULL`, but that it's whatever you configured it to be—and by default, that's configured to be something auto-detected, not `NULL`

### curl/libcurl version

libcurl 7.76.1

Here's an example of how it's configured on one platform (Android NDK arm64-v8a):

    cmake -DCMAKE_TOOLCHAIN_FILE=$toolchain -DENABLE_STATIC_LIB=true -DANDROID_ABI=$ANDROID_ABI \
      -DBUILD_SHARED_LIBS=OFF -DBUILD_CURL_EXE=OFF \
      -DCMAKE_INSTALL_PREFIX="$(pwd)/install" \
      -DCMAKE_USE_OPENSSL=OFF -DCMAKE_USE_MBEDTLS=ON -DMBEDTLS_LIBRARY=$mbedtlspath/lib/libmbedtls.a -DMBEDX509_LIBRARY=$mbedtlspath/lib/libmbedx509.a -DMBEDCRYPTO_LIBRARY=$mbedtlspath/lib/libmbedcrypto.a -DMBEDTLS_INCLUDE_DIRS=$mbedtlspath/include \
      -DUSE_NGHTTP2=ON -DCMAKE_USE_NGHTTP2=ON -DNGHTTP2_LIBRARY=$nghttp2path/lib/libnhttp2.a -DNGHTTP2_INCLUDE_DIR=$nghttp2path/include \
      ../..

### operating system

Various versions of Android, iOS, macOS.

**Comment by bagder** [comment] 2021-05-13 10:05
The cmake auto-detect of the `CURL_CA_PATH` seems like it checks the host's path rather than the target's path?

**Comment by bagder** [comment] 2021-05-14 20:47
The title of this issue says **CURLOPT_CAPATH does not default to NULL** but your actual issue isn't that, right? If I read your description correctly the problem is that you have a bad/non-existing path set as default?

#7062 updates the docs to match reality

**Comment by bagder** [comment] 2021-05-24 15:28
No further responses. Closing

**Closed by bagder** 2021-05-24 15:28 UTC
Labels: SSL/TLS, cmake, needs-info-or-update
