### ISSUE TITLE
Curl website is living in 1990s; I want to contribute

### ISSUE THREAD

**Issue by avadhbsd** [curl/curl#1513] opened 2017-05-26 15:30 UTC
I am a designer and I would love to design a fresh website for curl which looks awesome works great and kicks ass ;)

Kindly point me to right direction is there a core team? who makes design decisions for the website?

I would love to get in touch.

Thanks

**Comment by bagder** [comment] 2017-05-26 21:08
Hello and thanks for your offer!

The curl web site may very well "live in the 1990s", but we have a lot of automation and integration done on the site that I value greatly and I prefer rather than have a fancy design. We can't easily just switch over to a fancy new web site somewhere.

A lot of the contents are converted from source and other text sources. It is updated automatically directly from the web site git repo so it allows any number of contributors/editors etc.

This said, I'm open for help to get new designs, looks or improvements for the web site. It just takes designers with a sincere interest to cooperate and work together with us (me mostly) to figure out what can be done and how to do it the best way.

What exactly do you have in mind and how would you like to move forward?

Note that the curl web site is hosted in a separate code repository already: https://github.com/curl/curl-www/

**Comment by avadhbsd** [comment] 2017-05-28 05:47
I did not mean to offend, but yes reading it "1990" thing felt slightly offensive. sorry for that 🙏🏻

Thanks for revert Mr. Stenberg, 

Sure, I will have a look at the website repo and try to figure out how can I best beef up the website without making lots of changes on your end.

Will share something soon.

Thanks again; 
Looking forward to working with you.

**Comment by bagder** [comment] 2017-05-28 10:44
Since this is not a bug, I'm closing this issue.

**Closed by bagder** 2017-05-28 10:44 UTC
