### ISSUE TITLE
CURLMOPT_SOCKETFUNCTION called before CURLOPT_OPENSOCKETFUNCTION

### ISSUE THREAD

**Issue by georgeOik** [curl/curl#5747] opened 2020-07-30 12:44 UTC
### I did this
With the use of `sokcetpair.h` on `lib/async-thread.c` the CURLMOPT_SOCKETFUNCTION is fired before the CURLOPT_OPENSOCKETFUNCTION callback when using the **multi** interface. This is in [here](https://github.com/curl/curl/blob/master/lib/asyn-thread.c#L417) in https://github.com/curl/curl/commit/9c76f694de1765152e0b349cd55baad5a501f55b. 

As a result the sockp in ```static int sock_cb(CURL* e, curl_socket_t s, int what, void* cbp, void* sockp)``` is a null making it harder for users who use libraries such as uv or libevent to create/remove sockets to track socket failures as they are usually created in the CURLOPT_OPENSOCKETFUNCTION callback and the user has no knowledge of the sockets that cURL created for the socket pair but get a callback. 

### I expected the following
The callback order to be preserved and CURLOPT_OPENSOCKETFUNCTION to be called before CURLMOPT_SOCKETFUNCTION or to receive no callbacks for sockets that were created by libcurl itself.

### curl/libcurl version

curl 7.67.0-DEV (i386-pc-win32) libcurl/7.67.0-DEV Schannel
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Debug IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI UnixSockets

### operating system
Windows 10, but I think it affects all platforms

**Comment by bagder** [comment] 2020-07-30 17:49
On Windows, #5634 will change this behavior if/when merged...

**Comment by georgeok** [comment] 2020-08-03 21:04
The same happens on macOS `curl 7.71.1 (x86_64-apple-darwin19.5.0) libcurl/7.71.1 SecureTransport zlib/1.2.11`.

@bagder It would be great if you can give us your lights and clarify if this is the desired behaviour or needs to get changed.

**Comment by bagder** [comment] 2020-08-03 21:53
I'm not sure what the desired behavior is here. You probably refer to the socketpair that gets created and used, and I don't know how we can get such a set with CURLOPT_OPENSOCKETFUNCTION... We might need a bigger take.

**Comment by kunalekawde** [comment] 2020-09-01 17:43
yes I too observed this while using CURLOPT_OPENSOCKETFUNCTION & CURLMOPT_SOCKETFUNCTION. OpenSocket finally gets invoked and continues. But this is introducing some delay which I'm currently working on -- looking first my API arrangement and callback functionality.

**Comment by ned14** [comment] 2020-12-16 18:07
Just ran into this exact problem when upgrading our code from libcurl 7.60 to 7.74. We are using ASIO/Standard C++ Networking as the sockets implementation. libcurl needs to exclusively use ASIO, and nothing else. This used to work just fine, but now it would appear that libcurl is creating its own sockets, which have no representation with ASIO, and therefore ASIO cannot use them without taking ownership of them, which then introduces lifetime problems. Looking forward to seeing a fix for this.

**Comment by bagder** [comment] 2020-12-16 22:01
I would appreciate a small example program reproducing/visualizing the issue.

**Comment by ned14** [comment] 2020-12-17 09:35
@bagder Do you want a simple repro, or do you want an ASIO based repro?

(Be aware that the way libcurl currently implements SOCKETFUNCTION is not compatible with Standard Networking's `async_wait()`, and we have to use a timer to poke libcurl to resume sending on a write congested socket. This is very inefficient. Incidentally your existing documented ASIO-libcurl implementation no longer works, it is too old)

**Comment by bagder** [comment] 2020-12-17 22:03
> simple repro, or do you want an ASIO based repro?

Since the problem is in order of the actions, I figured it should be possible to make something simple even without asio.

> Incidentally your existing documented ASIO-libcurl implementation no longer works

I didn't know we have one?

**Comment by bagder** [comment] 2020-12-17 22:05
Did you mean `asiohiper.cpp` ? The one we removed in 9d47ff5323?

**Comment by ned14** [comment] 2020-12-18 19:46
Ok you can find a repro at https://github.com/ned14/libcurl-cxx-std-networking-integration. On Microsoft Windows, in debug build, I get:

```
Fetching from URL http://www.nedprod.com...
Assertion failed: it != _sockets.end(), file G:\boostish\libcurl-cxx-std-networking-integration\libcurl-cxx-std-networking-integration.cpp, line 208
```

Obviously do check my program for correctness as well. In particular, does libcurl only request `CURL_POLL_OUT` on sockets whose write buffers are full, and then issue `CURL_POLL_REMOVE` when the socket becomes writable? Because if it does not, ASIO will spin loop the `_write_possible()` handler forever.

If you like this example of how to integrate standard C++ networking and libcurl, I could probably add some documentation, and you could link to it in your docs if you wanted to.

**Comment by bagder** [comment] 2020-12-18 22:25
Thanks a lot but I'm sorry, my C++ is so rusty that code is beyond what I can use to debug anything. I was hoping for something much simpler and something I could translate to C.

Anyway, isn't the sockets we're talking about here the sockets curl creates with `socketpair()` ? They really cannot be made with plain `socket()` so the `CURLOPT_OPENSOCKETFUNCTION` is not used for them and I presume that is what causes this? Any chance you can confirm if this is true?

If they are, then we need to figure out a way to deal with these sockets. Can't you consider an "unknown socket" to be one you have to create and start monitoring? I mean, most event-based programs work like that and they do not use the `OPENSOCKET` callback at all...

> If you like this example of how to integrate standard C++ networking and libcurl, I could probably add some documentation, and you could link to it in your docs if you wanted to.

That sounds like a neat idea but maybe we should wait with that until the code actually works with libcurl as-is? :smile:

**Comment by ned14** [comment] 2020-12-19 12:43
> Thanks a lot but I'm sorry, my C++ is so rusty that code is beyond what I can use to debug anything. I was hoping for something much simpler and something I could translate to C.

I felt it was important to demonstrate the current gap between libcurl's present third party socket support and the bare minimum viable actually required. I was careful to write the program in simple terms, it's mostly C rather than C++ in fact. I avoided what a C++ 20 programmer would actually write for this, which almost certainly would be C++ Coroutines based and therefore probably quite alien to those not familiar with stackless Coroutine programming.

> Anyway, isn't the sockets we're talking about here the sockets curl creates with socketpair() ? They really cannot be made with plain socket() so the CURLOPT_OPENSOCKETFUNCTION is not used for them and I presume that is what causes this? Any chance you can confirm if this is true?

libcurl's big problem currently is that it thinks it knows all the kinds of socket possible, that those are exclusively kernel sockets, and that it can manipulate them directly. I am sure that you can see that this is fundamentally incompatible with any other kind of library which assumes the same.

What would be ideal is if going forth that libcurl stops using kernel syscalls directly completely for all socket i/o. If instead you took a third party replaceable const struct of function pointers for all the operations you might want to do on socket-like things, including all creation, manipulation, and destruction, that would make libcurl considerably more useful to integrate with other networking code.

Above you say "we use socketpair so we can't use CURLOPT_OPENSOCKETFUNCTION". I would say "why didn't you add a CURLOPT_OPENSOCKETPAIRFUNCTION when you started using socketpair?"

> If they are, then we need to figure out a way to deal with these sockets. Can't you consider an "unknown socket" to be one you have to create and start monitoring? I mean, most event-based programs work like that and they do not use the OPENSOCKET callback at all...

You're thinking in terms of knowing that these are kernel sockets. In the code example I supplied, I was able to "get away with" extracting the `native_handle()` from the ASIO socket because it just happens to be a `curl_socket_t`.

However standard C++ Networking certainly will not guarantee that, and in fact, for many use cases C++ sockets cannot have a kernel socket representation. Consider running libcurl on a GPU where the socket implementation is a CUDA one. Consider running libcurl on a freestanding C++ program where there is no OS kernel at all, and where sockets are 100% userspace (here is a popular example: https://www.includeos.org/). Finally, consider running libcurl within C++ Coroutines, where each i/o is a suspend-resume point i.e. when libcurl does i/o with a socket, instead of the kernel potentially sleeping the calling thread, instead the C++ coroutine suspends until the i/o completes, whereupon libcurl execution is resumed. In this final use case, the socket implementation is a Coroutines based implementation, and which may have no representation whatsoever with an OS kernel.

Obviously what I'm suggesting here is a lot of work for you guys to go do, basically it's an i/o abstraction layer, and you'd probably abstract out platform specific differences behind that. If you guys were willing to move libcurl onto C++, I could offer a C ABI compatible generalised i/o abstraction currently before WG21 for standardisation into C++ 26. So while the implementation would become C++, the external API and ABI would remain C. But I suspect that's a step too far for you guys, so I'd suggest you consider doing something similar to what OpenSSL does, basically a replaceable table of const function pointers.

> That sounds like a neat idea but maybe we should wait with that until the code actually works with libcurl as-is?

Agreed. Right now it can't be made to work because of lifetime issues - ASIO needs to take ownership of awaitable things before you can await upon them. This is because you might be running your standard C++ program over heterogeneous devices e.g. some threads of execution might be on your CPU, others on on your GPU, and still others running on your NIC (this is all perfectly possible today using non-standardised technologies, which is why we are standardising it). So libcurl can't just hand us some kernel socket handle and ask "please tell me when something changes on this" because we have no way of knowing what i/o context, execution context, or scheduling context any of that means.

If, instead, you exclusively let third party code define what a socket is, and libcurl only demands they behave like BSD sockets, third party code can go "do the right thing" as far as libcurl is aware. And everything "just works".

I appreciate the above was a long answer, and my apologies for that. But I wanted to explain the wider context of where ISO standardisation is going next, and I thought that knowing this would help aid your decision making.

**Comment by bagder** [comment] 2020-12-19 17:02
> libcurl's big problem currently is that it thinks it knows all the kinds of socket possible

I don't think it is libcurl's "big problem" and I think that's a weird characterization. Why would libcurl know "all the kinds of sockets" ? It doesn't make sense. It knows what sockets it needs to perform its operations, no more.

> I felt it was important to demonstrate the current gap between libcurl's present third party socket support and the bare minimum viable actually required.

It is strange how users have been able to use libcurl with several different event libraries on multiple operating systems for well over a decade when libcurl clearly can't provide that functionality...

>  Above you say "we use socketpair so we can't use CURLOPT_OPENSOCKETFUNCTION". I would say "why didn't you add a CURLOPT_OPENSOCKETPAIRFUNCTION when you started using socketpair?"

You probably don't realize how you extremely rude you sound to me when saying this. I fricking wrote this functionality on my spare time, I give it to the world, I ask for feedback, I debug the thing, I document every tiny detail, it ships to thousands and yet thousands of apps and *billions* of end users run the code. 

So when what I did have flaws left, it isn't complete or there are more things left in there we can do to improve it, I would rather have you help out with constructive ideas rather than a snarky comment on why I didn't write things perfect the first time around.

**I didn't provide that callback at the time because I didn't think about the case and nobody else told or reminded me about it.**

I will most likely continue to write things imperfectly, and then work on polishing them up over time. Open source style.

> Obviously what I'm suggesting here is a lot of work for you guys to go do, basically it's an i/o abstraction layer

You had me at "you guys". An abstraction layer would be great to support, but if you think we have an army of developers ready to write code at the whims of someone in a GitHub issue, you're wrong. We're very few regulars here and we have a lot on our plates already. A good idea is easy. Making it reality is what counts and an "abstraction layer" layer like this is... well, saying **a lot of work** probably understates it.

So then, if you just throw an idea at us and hope that it'll happen I'm sorry to disappoint. You should at the very least state things in the form of "**we** should...".

> However standard C++ Networking certainly will not guarantee that

We've provided libcurl for over twenty years, and the multi socket for about 15 years already. It's unfortunate that A) when "C++ standard networking" finally comes along, it can't work with libcurl - the most used internet transfer library in the world and B) people who know about this inability don't want to work with us to create could be the perfect combination for future C++ users.

> I thought that knowing this would help aid your decision making.

This is not a question about decision making. I would love to support and offer such an abstraction layer you mention but I don't see that happening unless someone steps forward with some serious energy and/or funding.

----

So is the answer that a `CURLOPT_OPENSOCKETPAIRFUNCTION` callback would help solving this issue?

**Comment by bagder** [comment] 2021-01-06 00:05
This issue cannot advance without additional information.

**Comment by MarcelRaad** [comment] 2021-01-06 00:19
@bagder wrote:
> So is the answer that a CURLOPT_OPENSOCKETPAIRFUNCTION callback would help solving this issue?

@georgeOik That would help, right?

**Comment by georgeok** [comment] 2021-01-06 00:59
CURLOPT_OPENSOCKETPAIRFUNCTION could be a solution, but we would also need the equivalent close socket pair callback in track of the sockets created by the library internally and not mix it with the the ones created by the users.

**Comment by nardl** [comment] 2021-01-25 01:34
Wasaa

**Comment by bagder** [comment] 2021-02-13 21:53
It would help a lot of someone could come up with a suggestion on what we could/should do to fix this.

**Comment by georgeok** [comment] 2021-02-17 23:32
I will to implement a CURLOPT_OPENSOCKETPAIRFUNCTION and feedback as soon as possible

**Closed** 2021-03-18 11:54 UTC
Labels: KNOWN_BUGS material, libcurl API, needs-info-or-update
