### ISSUE TITLE
Broken connection handling with CURLOPT_CONNECT_ONLY and multi interface

### ISSUE THREAD

**Issue by pps83** [curl/curl#4426] opened 2019-09-26 03:18 UTC
I'm trying to impl websocket with libcurl's CURLOPT_CONNECT_ONLY. It all works (eg I can connect and exchange websocket messages), however, I cannot get libcurl to close connections when I close websocket connection. I tried all kinds of stuff and I'm fairly convinced that the connection pool handling is buggy in curl: in many cases it closes connection when it should not, but when it should, you'll probably won't be able to make it close your connection.

Unlike examples/sendrecv.c sample, I have to use multi interface to create connection that I can later use, and there is no sample code that shows multi interface with CURLOPT_CONNECT_ONLY. As a result, I have no choice but to guess what the proper use has to be.

First of all, it's not clear what's the proper approach has to be in the multi+CURLOPT_CONNECT_ONLY case. After an easy handle was created with CURLOPT_CONNECT_ONLY, I add it to a multi handle. Then when I get a notification on this handle (when connection is established) do I need to remove it from the multi handle and keep using easy handle?.. it seems that this won't work, and I have to keep the easy handle attached to the multi handle and keep using the easy handle and only at the end when I'm done I remove the easy handle from multi and cleanup the easy handle.

This approach overall works. Unfortunately I cannot provide sample code, as it's part of huge codebase and it's difficult to extract relevant parts. The problem however, is that I cannot close the tcp connection after I close my websocket connection: it stays half open (even though remote closes it on the other end). So, I tried all kinds of stuff and workarounds and all I see is  buggy behavior from curl.

baseline of the settings and pseudo code that I use:

        m = curl_multi_init
        curl_easy_init
        set(CURLOPT_CONNECT_ONLY, 1L);
        set(CURLOPT_MAXCONNECTS, 1L);
        set(CURLOPT_FRESH_CONNECT, 1L);
        curl_multi_add_handle
        curl_multi_perform
        websocket = curl_easy_getinfo(CURLINFO_ACTIVESOCKET)
        while (!websocket closed) // send-recv messages
        {
                curl_easy_send(sock)
                curl_easy_recv(sock)
        }
        curl_multi_remove_handle
        curl_easy_cleanup

These are the things that I tried:

1)
        set(CURLOPT_FORBID_REUSE, 1L);

This triggers complete failure from curl. It connects and immediately closes the connection (I inspect with wireshark). I don't get any errors, CURLINFO_ACTIVESOCKET though returns CURLE_OK with sock=-1. This method closes connection way to soon for my liking that I don't even have a chance to enjoy it :)

2)
        curl_multi_setopt(m, CURLMOPT_MAXCONNECTS, 1L));

This also doesn't work. When I try to establish second websock connection it acts in identical way to what I get with CURLOPT_FORBID_REUSE: after second connection is established curl closes it immediately and I get sock=-1 from CURLINFO_ACTIVESOCKET .

3)
I tried to track manually number of easy handles that I add to multi handle and dynamically adjust CURLMOPT_MAXCONNECTS when I add/remove new handles. First of all, it's strange that multi interface doesn't have a way to get count of easy handles that it manages. Anyways, I count them myself and before adding new easy handle I increase CURLMOPT_MAXCONNECTS by one. Now at least curl doesn't close connections immediately after opening them. I can use them, but when I close websocket connection curl doesn't do anything at all. I tried to reduce by 1 CURLMOPT_MAXCONNECTS before or after I remove my easy handle. Connection does not get closed. I tried to set CURLOPT_FORBID_REUSE before removing from multi handle: still no effect. The only thing that does work properly is when I close multi handle itself: all connections that were hanging around from previous websocket connections are immediately closed.

As a side note: if a CURLOPT_CONNECT_ONLY easy handle is part of multi handle and I call perform on that multi handle, what does libcurl do internally to that member easy handle that was already connected? Hopefully it doesn't try to do anything with it.

**Comment by bagder** [comment] 2019-09-26 09:32
First, multi interface or easy interface makes really no difference. It is all the same internally anyway.

> do I need to remove it from the multi handle and keep using easy handle?

I don't think you should remove it. The handle should signal transfer complete but you should keep it as-as and when done, remove it and cleanup. IIRC.

> I cannot provide sample code

That's suspicious. You should be able to write up a stand-alone example, perhaps based on one of the many examples we provide, that reproduces the same logic and setup that you use.

That way we could see this for ourselves, debug it and help you work on a fix. Without it, that burden instead falls upon us...

> if a CURLOPT_CONNECT_ONLY easy handle is part of multi handle and I call perform on that multi handle, what does libcurl do internally to that member easy handle that was already connected?

Each added easy handle is independent and has its own set of options and they will of course be honored independently.

(A seemingly related issue that still hasn't been resolved is #4369.)

**Comment by pps83** [comment] 2019-09-28 05:40
One more related problem:
4)
 I set CURLMOPT_MAXCONNECTS to N, create N connections, everything is OK, I close a handle and remove it from multi handle. Now if I try to create a new connection I get the same behavior: everything succeeds, except when I try to get socket I get -1. Basically connection gets immediately closed as well.

I'll try to create some basic examples when I have a chance

**Comment by pps83** [comment] 2019-09-28 09:47
https://gist.github.com/pps83/f9f6193055faa5a3ecce3be7f6e29309

contains readme with direction and all the files needed to reproduce these issues.

**Comment by pps83** [comment] 2019-09-29 02:50
as a side note, since I have to manually craft and parse initial websocket handshake, I'd like to ensure that all headers and values that I format are properly quoted.
That's basically the code that I use:
```
    // TODO: quote values, check security/url injection
    bufferOut = RBX::format("GET %s HTTP/1.1\r\n", path.c_str());
    for (const auto& h : httpReq->rawHeaders)
        RBX::append_format(bufferOut, "%s: %s\r\n", h.first.c_str(), h.second.c_str());
    bufferOut += "\r\n";
```
where should I look for the code that curl uses to quote url and header values? (it's ok even if these aren't exposed/static functions)

**Comment by jay** [comment] 2019-10-06 22:30
> where should I look for the code that curl uses to quote url and header values?

I'm not sure what you mean by quote values, can you explain?

**Comment by pps83** [comment] 2019-10-07 02:13
> I'm not sure what you mean by quote values, can you explain?

Well, if I set a header's value to something like "abs\r\nxyz", will libcurl create corrupted request, or it will quote the value with percent encoding for example? I tested, and it doesn't seem to be doing it, so, not really important.
Were you able to reproduce the issues described above with supplied gist/repo?

**Comment by bagder** [comment] 2019-10-07 08:52
Please stop hi-jacking issues to start talking about completely different subjects in them. If it isn't related to connection handling with CURLOPT_CONNECT_ONLY, either file a new issue or ask questions on the mailing list. We don't use the issue tracker for questions.

**Comment by marc-groundctl** [comment] 2019-10-11 17:53
I have a much shorter reproduction:
```c++
#include <stdlib.h>

#include <curl/curl.h>

int main()
{
	auto multi = curl_multi_init();
	curl_multi_setopt(multi, CURLMOPT_MAXCONNECTS, 2);
	while (true)
	{
		auto easy = curl_easy_init();
		curl_easy_setopt(easy, CURLOPT_URL, "http://127.0.0.1:1234/");
		curl_easy_setopt(easy, CURLOPT_CONNECT_ONLY, 1);
		curl_easy_setopt(easy, CURLOPT_VERBOSE, 1);
		curl_multi_add_handle(multi, easy);
		while (true)
		{
			int running;
			curl_multi_socket_action(multi, CURL_SOCKET_TIMEOUT, 0, &running);
			int remaining;
			if (curl_multi_info_read(multi, &remaining))
				break;
		}
		while (true)
		{
			char c;
			size_t n;
			auto ret = curl_easy_recv(easy, &c, 1, &n);
			if (n == 0)
			{
				if (ret == CURLE_AGAIN)
					continue;
				if (ret == CURLE_OK)
					break;
			}
			exit(1);
		}
		curl_multi_remove_handle(multi, easy);
		curl_easy_cleanup(easy);
	}
}
```

Run a tcp server on 127.0.0.1:1234 that hangs up after a while (an easy way to do this is `ncat -l 1234 -k -c 'sleep 1'`) and run this program.  With older versions of curl this program will loop forever.  With newer versions of curl this program will exit saying "Failed to get recent socket".  Git bisect indicates this was caused by commit e3a53e3efb942a5446a22725340e36af63f1632e.

**Comment by marc-groundctl** [comment] 2019-10-11 21:28
It looks like the issue is that `curl_easy_recv` calls `Curl_getconnectinfo` which sets `c->data`, so when curl calls `extract_if_dead` the connection has a non-null `data` and so isn't considered dead.  Eventually the connection cache fills up and when we finish calling `curl_multi_socket_action` it calls `Curl_conncache_return_conn` which attempts to close the oldest connection, but since `Curl_conncache_extract_oldest` ignores connections with non-null `data`s it skips the already-used connections and finds the current connection, which it then closes.  This can be fixed with the following diff, but I don't know if that catches all cases.

```diff
--- a/lib/multi.c
+++ b/lib/multi.c
@@ -749,6 +749,11 @@ CURLMcode curl_multi_remove_handle(struct Curl_multi *multi,
     detach_connnection(data);
   }
 
+  /* Remove the association between the connection and the connect-only handle */
+  if(data->state.lastconnect && data->state.lastconnect->data == data) {
+    data->state.lastconnect->data = NULL;
+  }
+
 #ifdef USE_LIBPSL
   /* Remove the PSL association. */
   if(data->psl == &multi->psl)
```

This also has the effect that when we clean up the easy handle the connection still has a pointer to the now destroyed `Curl_easy`, which I don't think is used but can be confusing when debugging the problem.

**Comment by yanpqi** [comment] 2019-11-27 12:14
I have the same problem on 7.65.1. 
I use libcurl's connect_only to implement a websocket client, all work well except that, when i try to reuse ssl-session-id, i can not call curl_easy_cleanup. default libcurl connect cache max num is 4 in my device, so the first 4 connects success and placed in cache. the 5th and after is refused for cache is full and closed directly, in this case, i get -1 when called CURL_LAST_ACTIVESOCKET.

ehh, i think drop new connect is stupid for a cache, more worsely, the first 4 connects is long live in cache.  

why not provide connect close interface to user for connect-only. in this mode, when to close a connect should be decided by user, not library itself.

I check the verbose log which shows this when in problem.
Connection cache is full, closing the oldest one.
* Closing connection 114
.....
* Connection cache is full, closing the oldest one.
* Closing connection 115

**Closed** 2019-12-11 08:27 UTC
Labels: connecting & proxies, libcurl API

**Comment by marc-groundctl** [comment] 2019-12-12 17:19
Although 1d5c427 fixes this issue's symptoms, in doing so it introduces a handle leak.  This can be observed by setting the file descriptor limit to a low number (e.g. `ulimit -n 20`) and running the above reproduction program.  With curl 7.63 it runs forever, but with the current master (5dc56eb95) it stops after looping 14 times on my system.

**Comment by bagder** [comment] 2019-12-12 22:53
I think this highlights a problem with my change but I don't have any really good fix. It's not really a leak though.

The issue is that with my change the connection is now considered in use until closed. And closing the easy handle won't be enough to close the connection as the connection cache is held by the multi handle. Thus, as long as you keep the multi handle around, the connection remains (and you can keep using that socket you once extracted).

**Comment by bagder** [comment] 2019-12-12 22:55
I suppose the fix would be to remove the "keep it" bit when `curl_easy_recv()` gets an error...

**Comment by bagder** [comment] 2019-12-12 22:57
Maybe something like this
~~~diff
diff --git a/lib/easy.c b/lib/easy.c
index 6382cee3d..86e537cb4 100644
--- a/lib/easy.c
+++ b/lib/easy.c
@@ -1084,12 +1084,16 @@ CURLcode curl_easy_recv(struct Curl_easy *data, void *buffer, size_t buflen,
     return result;
 
   *n = 0;
   result = Curl_read(c, sfd, buffer, buflen, &n1);
 
-  if(result)
+  if(result) {
+    /* mark for closure */
+    c->bits.close = TRUE;
+    c->bits.connect_only = FALSE;
     return result;
+  }
 
   *n = (size_t)n1;
 
   return CURLE_OK;
 }
~~~
