### ISSUE TITLE
Curl is failing when downloading a already downloaded file with resume download and --fail error set

### ISSUE THREAD

**Issue by Anubhav-Rai** [curl/curl#12174] opened 2023-10-21 10:54 UTC
### I did this

I tried to download a file and it got downloaded and then again i tried to download with resume download and --fail. 

# ran it twice
curl -O -C - -f "https://github.com/robots.txt"
curl -O -C - -f "https://github.com/robots.txt"

### I expected the following

curl: (22) The requested URL returned error: 416

The above was the error recieved which shouldn,t have happened as this was fixed already in https://github.com/curl/curl/issues/6740 as part of Fixed in 7.76.0 - March 31 2021 release

### curl/libcurl version

curl 7.88.1 (x86_64-pc-linux-gnu) libcurl/7.88.1 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.3 libpsl/0.21.2 (+libidn2/2.3.3) libssh/0.10.4/openssl/zlib nghttp2/1.52.0 librtmp/2.3
Release-Date: 2023-02-20
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

### operating system

Linux ar 6.2.0-34-generic #34-Ubuntu SMP PREEMPT_DYNAMIC Mon Sep  4 13:06:55 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment] 2023-10-21 12:09
In spite of what the reporter says here,  #6753 also landed a test case (1273) and that still works. This is not the exact same case.

**Comment by Smackd0wn** [comment] 2023-10-22 14:37
Probably duplicate of #10521?

**Comment by bagder** [comment] 2023-10-22 18:05
Indeed. The #12176 fix is just a little more extended since it also addresses updated testcases.

**Closed** 2023-10-30 16:01 UTC
Labels: HTTP
