### ISSUE TITLE
macos10.15 curl  uploadfile not success not fail

### ISSUE THREAD

**Issue by happyxb** [curl/curl#4641] opened 2019-11-27 10:06 UTC
### I expected the following

AnyInfo can fix the question.

### curl/libcurl version

curl/7.64.1

### cmd

[curl -F "file=@yyy.ipa" -F "_api_key=xxxx" -F "buildInstallType=2" -F "buildPassword=1" https://www.pgyer.com/apiv2/app/upload -v --connect-timeout 30]

### operating system

macos 10.15

### Detail Log

```
 Trying 120.78.242.5...
* TCP_NODELAY set
* Connected to www.pgyer.com (120.78.242.5) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.pgyer.com
*  start date: Apr 16 00:00:00 2019 GMT
*  expire date: Apr 15 12:00:00 2020 GMT
*  subjectAltName: host "www.pgyer.com" matched cert's "*.pgyer.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=Encryption Everywhere DV TLS CA - G1
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fcb3f805400)
> POST /apiv2/app/upload HTTP/2
> Host: www.pgyer.com
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Length: 226306929
> Content-Type: multipart/form-data; boundary=------------------------c0856e36de945acb
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* We are completely uploaded and fine
```

**Comment by bagder** [comment] 2019-11-27 13:32
I don't think this is a curl bug. You're talking about a very simple and common operation that is used by many people and that gets tested frequently during development. The fact that it works from one place but not from another also indicates that the problem is rather specific to that certain location or network setup. Without a lot of more details it is impossible for us to tell exactly what's happening.

It is interesting to note that in your verbose output above, we can see that the upload succeeds and curl considers it completed but then it doesn't get the expected response back from the server and instead sits there and wait for it to arrive.

**Comment by happyxb** [comment] 2019-11-28 03:04
when i add -m 120,the log add some info 

```
  3  202M    0     0    3 7216k      0  7201k  0:00:28  0:00:01  0:00:27 7201k
 15  202M    0     0   15 30.5M      0  15.3M  0:00:13  0:00:01  0:00:12 15.3M
 23  202M    0     0   23 47.4M      0  12.9M  0:00:15  0:00:03  0:00:12 12.9M
 23  202M    0     0   23 47.4M      0  10.1M  0:00:19  0:00:04  0:00:15 10.1M
 23  202M    0     0   23 47.4M      0  8566k  0:00:24  0:00:05  0:00:19 8566k
 23  202M    0     0   23 47.4M      0  7283k  0:00:28  0:00:06  0:00:22 7298k
 25  202M    0     0   25 52.5M      0  7709k  0:00:26  0:00:06  0:00:20 4515k
 36  202M    0     0   36 74.0M      0  9492k  0:00:21  0:00:07  0:00:14 6305k
 46  202M    0     0   46 94.8M      0  9815k  0:00:21  0:00:09  0:00:12 9290k
 46  202M    0     0   46 94.8M      0  8913k  0:00:23  0:00:10  0:00:13 9290k
 46  202M    0     0   46 94.8M      0  8621k  0:00:24  0:00:11  0:00:13 10.3M
 53  202M    0     0   53  108M      0  9273k  0:00:22  0:00:11  0:00:11 11.1M
 63  202M    0     0   63  129M      0   9.9M  0:00:20  0:00:12  0:00:08 11.0M
 71  202M    0     0   71  145M      0   9.8M  0:00:20  0:00:14  0:00:06 10.4M
 71  202M    0     0   71  145M      0  9464k  0:00:21  0:00:15  0:00:06 10.4M
 71  202M    0     0   71  145M      0  9026k  0:00:22  0:00:16  0:00:06 9897k
 76  202M    0     0   76  154M      0  9296k  0:00:22  0:00:16  0:00:06 9352k
 85  202M    0     0   85  173M      0  9863k  0:00:21  0:00:17  0:00:04 9028k
 95  202M    0     0   95  193M      0  10.1M  0:00:19  0:00:18  0:00:01 11.2M
 97  202M    0     0   97  197M      0   9.7M  0:00:20  0:00:20 --:--:-- 11.7M
 97  202M    0     0   97  197M      0  9546k  0:00:21  0:00:21 --:--:-- 11.1M
 97  202M    0     0   97  197M      0  9115k  0:00:22  0:00:22 --:--:-- 8523k
 97  202M    0     0   97  197M      0  8720k  0:00:23  0:00:23 --:--:-- 4777k
 99  202M    0     0   99  201M      0  8588k  0:00:24  0:00:24 --:--:-- 1623k* We are completely uploaded and fine

100  202M    0     0  100  202M      0  8292k  0:00:24  0:00:24 --:--:-- 1019k
100  202M    0     0  100  202M      0  7973k  0:00:25  0:00:25 --:--:-- 1020k
100  202M    0     0  100  202M      0  7677k  0:00:26  0:00:26 --:--:-- 1020k
100  202M    0     0  100  202M      0  7403k  0:00:27  0:00:27 --:--:-- 1021k
100  202M    0     0  100  202M      0  7148k  0:00:28  0:00:28 --:--:--  210k
100  202M    0     0  100  202M      0  6909k  0:00:29  0:00:29 --:--:--     0
100  202M    0     0  100  202M      0  6686k  0:00:30  0:00:30 --:--:--     0
100  202M    0     0  100  202M      0  6477k  0:00:31  0:00:31 --:--:--     0
100  202M    0     0  100  202M      0  6281k  0:00:32  0:00:32 --:--:--     0
100  202M    0     0  100  202M      0  6096k  0:00:33  0:00:33 --:--:--     0
100  202M    0     0  100  202M      0  5922k  0:00:34  0:00:34 --:--:--     0
100  202M    0     0  100  202M      0  5757k  0:00:35  0:00:35 --:--:--     0
100  202M    0     0  100  202M      0  5601k  0:00:36  0:00:36 --:--:--     0
100  202M    0     0  100  202M      0  5454k  0:00:37  0:00:37 --:--:--     0
100  202M    0     0  100  202M      0  5314k  0:00:38  0:00:38 --:--:--     0
100  202M    0     0  100  202M      0  5181k  0:00:39  0:00:39 --:--:--     0
100  202M    0     0  100  202M      0  5055k  0:00:40  0:00:40 --:--:--     0
100  202M    0     0  100  202M      0  4934k  0:00:41  0:00:41 --:--:--     0
100  202M    0     0  100  202M      0  4820k  0:00:42  0:00:42 --:--:--     0
100  202M    0     0  100  202M      0  4710k  0:00:43  0:00:43 --:--:--     0
100  202M    0     0  100  202M      0  4605k  0:00:44  0:00:44 --:--:--     0
100  202M    0     0  100  202M      0  4505k  0:00:45  0:00:45 --:--:--     0
100  202M    0     0  100  202M      0  4409k  0:00:46  0:00:46 --:--:--     0
100  202M    0     0  100  202M      0  4317k  0:00:47  0:00:47 --:--:--     0
100  202M    0     0  100  202M      0  4229k  0:00:48  0:00:48 --:--:--     0
100  202M    0     0  100  202M      0  4145k  0:00:49  0:00:49 --:--:--     0
100  202M    0     0  100  202M      0  4063k  0:00:50  0:00:50 --:--:--     0
100  202M    0     0  100  202M      0  3985k  0:00:51  0:00:51 --:--:--     0
100  202M    0     0  100  202M      0  3910k  0:00:52  0:00:52 --:--:--     0
100  202M    0     0  100  202M      0  3837k  0:00:53  0:00:53 --:--:--     0
100  202M    0     0  100  202M      0  3768k  0:00:54  0:00:54 --:--:--     0
100  202M    0     0  100  202M      0  3700k  0:00:55  0:00:55 --:--:--     0
100  202M    0     0  100  202M      0  3635k  0:00:56  0:00:56 --:--:--     0
100  202M    0     0  100  202M      0  3573k  0:00:57  0:00:57 --:--:--     0
100  202M    0     0  100  202M      0  3512k  0:00:58  0:00:58 --:--:--     0
100  202M    0     0  100  202M      0  3454k  0:00:59  0:00:59 --:--:--     0
100  202M    0     0  100  202M      0  3397k  0:01:00  0:01:00 --:--:--     0
100  202M    0     0  100  202M      0  3342k  0:01:01  0:01:01 --:--:--     0
100  202M    0     0  100  202M      0  3289k  0:01:02  0:01:02 --:--:--     0
100  202M    0     0  100  202M      0  3238k  0:01:03  0:01:03 --:--:--     0
100  202M    0     0  100  202M      0  3188k  0:01:04  0:01:04 --:--:--     0
100  202M    0     0  100  202M      0  3139k  0:01:05  0:01:05 --:--:--     0
100  202M    0     0  100  202M      0  3093k  0:01:06  0:01:06 --:--:--     0
100  202M    0     0  100  202M      0  3047k  0:01:07  0:01:07 --:--:--     0
100  202M    0     0  100  202M      0  3003k  0:01:08  0:01:08 --:--:--     0
100  202M    0     0  100  202M      0  2960k  0:01:09  0:01:09 --:--:--     0
100  202M    0     0  100  202M      0  2918k  0:01:10  0:01:10 --:--:--     0
100  202M    0     0  100  202M      0  2878k  0:01:11  0:01:11 --:--:--     0
100  202M    0     0  100  202M      0  2838k  0:01:12  0:01:12 --:--:--     0
100  202M    0     0  100  202M      0  2800k  0:01:13  0:01:13 --:--:--     0
100  202M    0     0  100  202M      0  2763k  0:01:14  0:01:14 --:--:--     0
100  202M    0     0  100  202M      0  2726k  0:01:15  0:01:15 --:--:--     0
100  202M    0     0  100  202M      0  2691k  0:01:16  0:01:16 --:--:--     0
100  202M    0     0  100  202M      0  2656k  0:01:17  0:01:17 --:--:--     0
100  202M    0     0  100  202M      0  2623k  0:01:18  0:01:18 --:--:--     0
100  202M    0     0  100  202M      0  2590k  0:01:19  0:01:19 --:--:--     0
100  202M    0     0  100  202M      0  2558k  0:01:20  0:01:20 --:--:--     0
100  202M    0     0  100  202M      0  2527k  0:01:21  0:01:21 --:--:--     0
100  202M    0     0  100  202M      0  2496k  0:01:22  0:01:22 --:--:--     0
100  202M    0     0  100  202M      0  2467k  0:01:23  0:01:23 --:--:--     0
100  202M    0     0  100  202M      0  2437k  0:01:24  0:01:24 --:--:--     0
100  202M    0     0  100  202M      0  2409k  0:01:25  0:01:25 --:--:--     0
100  202M    0     0  100  202M      0  2381k  0:01:26  0:01:26 --:--:--     0
100  202M    0     0  100  202M      0  2354k  0:01:27  0:01:27 --:--:--     0
100  202M    0     0  100  202M      0  2328k  0:01:28  0:01:28 --:--:--     0
100  202M    0     0  100  202M      0  2302k  0:01:29  0:01:29 --:--:--     0
100  202M    0     0  100  202M      0  2277k  0:01:30  0:01:30 --:--:--     0
100  202M    0     0  100  202M      0  2252k  0:01:31  0:01:31 --:--:--     0
100  202M    0     0  100  202M      0  2228k  0:01:32  0:01:32 --:--:--     0
100  202M    0     0  100  202M      0  2204k  0:01:33  0:01:33 --:--:--     0
100  202M    0     0  100  202M      0  2181k  0:01:34  0:01:34 --:--:--     0
100  202M    0     0  100  202M      0  2158k  0:01:35  0:01:35 --:--:--     0
100  202M    0     0  100  202M      0  2136k  0:01:36  0:01:36 --:--:--     0
100  202M    0     0  100  202M      0  2114k  0:01:37  0:01:37 --:--:--     0
100  202M    0     0  100  202M      0  2093k  0:01:38  0:01:38 --:--:--     0
100  202M    0     0  100  202M      0  2072k  0:01:39  0:01:39 --:--:--     0
100  202M    0     0  100  202M      0  2051k  0:01:40  0:01:40 --:--:--     0
100  202M    0     0  100  202M      0  2031k  0:01:41  0:01:41 --:--:--     0
100  202M    0     0  100  202M      0  2011k  0:01:42  0:01:42 --:--:--     0
100  202M    0     0  100  202M      0  1992k  0:01:43  0:01:43 --:--:--     0
100  202M    0     0  100  202M      0  1973k  0:01:44  0:01:44 --:--:--     0
100  202M    0     0  100  202M      0  1954k  0:01:45  0:01:45 --:--:--     0
100  202M    0     0  100  202M      0  1936k  0:01:46  0:01:46 --:--:--     0
100  202M    0     0  100  202M      0  1918k  0:01:47  0:01:47 --:--:--     0
100  202M    0     0  100  202M      0  1901k  0:01:48  0:01:48 --:--:--     0
100  202M    0     0  100  202M      0  1883k  0:01:49  0:01:49 --:--:--     0
100  202M    0     0  100  202M      0  1866k  0:01:50  0:01:50 --:--:--     0
100  202M    0     0  100  202M      0  1850k  0:01:51  0:01:51 --:--:--     0
100  202M    0     0  100  202M      0  1833k  0:01:52  0:01:52 --:--:--     0
100  202M    0     0  100  202M      0  1817k  0:01:53  0:01:53 --:--:--     0
100  202M    0     0  100  202M      0  1801k  0:01:54  0:01:54 --:--:--     0
100  202M    0     0  100  202M      0  1786k  0:01:55  0:01:55 --:--:--     0
100  202M    0     0  100  202M      0  1771k  0:01:56  0:01:56 --:--:--     0
100  202M    0     0  100  202M      0  1756k  0:01:57  0:01:57 --:--:--     0
100  202M    0     0  100  202M      0  1741k  0:01:58  0:01:58 --:--:--     0
100  202M    0     0  100  202M      0  1726k  0:01:59  0:01:59 --:--:--     0* Operation timed out after 120000 milliseconds with 0 bytes received
* stopped the pause stream!

100  202M    0     0  100  202M      0  1726k  0:01:59  0:01:59 --:--:--     0
* Connection #0 to host www.pgyer.com left intact
curl: (28) Operation timed out after 120000 milliseconds with 0 bytes received
* Closing connection 0
```

**Comment by bagder** [comment] 2019-11-28 11:33
My key take-away from that output is how the received data counter remains a zero. curl doesn't get any data back and eventually stops waiting when the timeout limit is reached.

But, as you're using HTTP/2 there's a small risk that you're seeing a bug in that area and we fixed a few of them after the 7.64.1 version you're using so you might want to try a more recent version to see if it behaves better.

Alternatively, tell curl to use HTTP/1.1 instead (`--http1.1`) and see if that behaves more reliably for you.

**Comment by happyxb** [comment] 2019-11-29 03:17
Maybe we got it!
When I add `--http1.1`,upload works well so far.
Then I check the previous work well mac's env,

```
System: MacOS 10.13.6
Curl Version: 7.54.0
Use HTTP Version: HTTP2
```
So the bug about HTTP/2 begin in which version and  fixed in which version?

**Comment by bagder** [comment] 2019-11-29 07:33
I don't think we can tell. It's not a bout *the* bug, it is about *a* (probable) bug. It could even be in the server end.

From curl 7.54.0 to 7.64.1 we landed **2380** commits in curl. 60 of them modified the http2.c source.

If you can reproduce the problem with 7.67.0 then I'll be interested in more details.

**Comment by bagder** [comment] 2019-12-07 12:11
No more response, possibly fixed in current version.

**Closed by bagder** 2019-12-07 12:11 UTC
Labels: HTTP, HTTP/2, cmdline tool
