### ISSUE TITLE
Threaded resolver enabled but no thread library found

### ISSUE THREAD

**Issue by ben29** [curl/curl#1795] opened 2017-08-16 21:36 UTC
Curl version : 7.55.1
Os: centos 7
configure:

```
./configure \
	--disable-debug \
	--disable-dict \
	--disable-ipv6 \
	--disable-telnet \
	--disable-ftp \
	--disable-tftp \
	--disable-pop3 \
	--disable-imap \
	--disable-smb \
	--disable-smtp \
	--disable-gopher \
	--disable-ldap \
	--disable-ldaps \
	--disable-rtsp \
	--disable-warnings \
	--disable-werror \
	--disable-symbol-hiding \
	--disable-ares \
	--disable-rt \
	--disable-dependency-tracking \
	--disable-libcurl-option \
	--disable-versioned-symbols \
	--disable-threaded-resolver \
	--disable-verbose \
	--disable-sspi \
	--disable-crypto-auth \
	--disable-ntlm-wb
```
see:
**--disable-threaded-resolver** 

the error:

> configure: error: Threaded resolver enabled but no thread library found

how it's happen ? it's disabled

version 7.55.0 works fine with it

**Comment by jay** [comment] 2017-08-17 02:07
Yeah it was a bug. Duplicate of #1784 and fixed in 3cb4bb6. Thanks

**Closed by jay** 2017-08-17 02:07 UTC
Labels: build

**Comment by ben29** [comment] 2017-08-29 08:24
when the next version will be release ?

**Comment by bagder** [comment] 2017-08-29 08:36
4th of October.

The next planned release date is always mentioned on the release-notes in progress page: https://curl.haxx.se/dev/release-notes.html
