### ISSUE TITLE
build curl 7.59.0 against libressl 2.7.1 fail

### ISSUE THREAD

**Issue by ingothierack** [curl/curl#2439] opened 2018-03-30 05:40 UTC
### I did this
try to build from source against libressl 2.7.1
get the error

```
make[2]: Entering directory `/mnt/data/install/curl-7.59.0/lib'
  CC       vtls/libcurl_la-openssl.lo
vtls/openssl.c:121:22: error: static declaration of ‘OpenSSL_version_num’ follows non-static declaration
 static unsigned long OpenSSL_version_num(void)
                      ^
In file included from /opt/lib/libressl/2.7.1/include/openssl/bio.h:69:0,
                 from /opt/lib/libressl/2.7.1/include/openssl/evp.h:67,
                 from /opt/lib/libressl/2.7.1/include/openssl/hmac.h:67,
                 from /opt/lib/libressl/2.7.1/include/openssl/ssl.h:149,
                 from vtls/openssl.c:52:
/opt/lib/libressl/2.7.1/include/openssl/crypto.h:340:15: note: previous declaration of ‘OpenSSL_version_num’ was here
 unsigned long OpenSSL_version_num(void);
               ^
make[2]: *** [vtls/libcurl_la-openssl.lo] Error 1
make[2]: Leaving directory `/mnt/data/install/curl-7.59.0/lib'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/mnt/data/install/curl-7.59.0/lib'
make: *** [all-recursive] Error 1
```

looks like OpenSSL_version_num is duplicated code now. Dirty hack was, comment out the function in vtls/openssl.c

### I expected the following
did compile

### curl/libcurl version
7.59.0 source
### operating system
Centos 7 with gcc 6.3.1

**Comment by bagder** [comment] 2018-03-30 08:43
See #2319

**Comment by bagder** [comment] 2018-03-30 09:38
Duplicate of #2319

**Closed by bagder** 2018-03-30 09:38 UTC
Labels: SSL/TLS, build
