### ISSUE TITLE
8.4.0 fails to build with CURL_DISABLE_VERBOSE_STRINGS=ON

### ISSUE THREAD

**Issue by SChernykh** [curl/curl#12083] opened 2023-10-11 07:49 UTC
### I did this

The cmake command line I used to generate Visual Studio solution file:
```
cmake .. -G "Visual Studio 16 2019" -DCURL_TARGET_WINDOWS_VERSION=0x0600 -DBUILD_CURL_EXE=OFF -DBUILD_SHARED_LIBS=OFF -DCURL_ZLIB=OFF -DCURL_DISABLE_ALTSVC=ON -DCURL_DISABLE_COOKIES=ON -DCURL_DISABLE_DOH=ON -DCURL_DISABLE_GETOPTIONS=ON -DCURL_DISABLE_HSTS=ON -DCURL_DISABLE_LIBCURL_OPTION=ON -DCURL_DISABLE_MIME=ON -DCURL_DISABLE_NETRC=ON -DCURL_DISABLE_NTLM=ON -DCURL_DISABLE_PARSEDATE=ON -DCURL_DISABLE_PROGRESS_METER=ON -DCURL_DISABLE_SHUFFLE_DNS=ON -DCURL_DISABLE_SOCKETPAIR=ON -DCURL_DISABLE_VERBOSE_STRINGS=ON -DHTTP_ONLY=ON -DCURL_ENABLE_SSL=OFF -DUSE_LIBIDN2=OFF -DCURL_USE_LIBPSL=OFF -DCURL_USE_LIBSSH2=OFF -DENABLE_UNIX_SOCKETS=OFF
```

It generated a solution file without issues, but then it failed to compile with this error:
```
curl_trc.c(247,1): error C2059: syntax error: 'do'`
```

Removing `Curl_trc_cf_infof` definition in `curl_trc.c` fixed the build for me.

### I expected the following

curl should build without errors when CURL_DISABLE_VERBOSE_STRINGS=ON

### curl/libcurl version

curl 8.4.0

### operating system

Windows

**Comment by pedro0311** [comment] 2023-10-11 11:45
Did you try to add to "-DCMAKE_C_FLAGS" -> -std=gnu99 ?

**Comment by SChernykh** [comment] 2023-10-11 12:36
> Did you try to add to "-DCMAKE_C_FLAGS" -> -std=gnu99 ?

I still get the same error with this flag.

**Comment by jay** [comment] 2023-10-12 03:00
@vszakats is this a duplicate of #11880

**Comment by SChernykh** [comment] 2023-10-12 05:43
This is exactly the same as #11891 but I got it with Visual Studio on Windows.

**Comment by vszakats** [comment] 2023-10-12 06:17
@jay I think so.

**Comment by jay** [comment] 2023-10-12 07:06
@vszakats would you mind creating a PR with [your fix](https://github.com/curl/curl/pull/11880#issuecomment-1740045337) so we can see if it works? #11880 seems to have gone stale. maybe @SChernykh can test?

**Comment by vszakats** [comment] 2023-10-12 07:19
@jay: I will do that in the coming days/week, unless someone beats me to it.

**Comment by vszakats** [comment] 2023-10-14 11:22
PR #12105 is ready for testing. We're appreciating feedback.

**Closed** 2023-10-26 15:43 UTC
Labels: build
