### ISSUE TITLE
libcurl is stuck when the application isn't allowed to use 3G/4G

### ISSUE THREAD

**Issue by dangvohoanganhvn** [curl/curl#5630] opened 2020-06-30 02:46 UTC
Hi, I have a problem with the HTTP application when using multi curl. I Have a function like that 
~~~c
do
 {
             int numfds = 0;
            {
                std::lock_guard<std::mutex> guard(m_mutex);
                mc = curl_multi_perform(multi_handle, &still_running);

            }
            if (mc == CURLM_OK)
            {
                mc = curl_multi_wait(multi_handle, nullptr, 0, MAX_WAIT_MSECS, &numfds);
            }

            if (mc != CURLM_OK)
            {
                still_running = 0;
                break;
            }
            else
            {
                std::lock_guard<std::mutex> guard(m_mutex);
                CheckEvent();
            }

            if (!numfds)
            {
                repeats++;

                if (repeats)
                {
                    WAITMS(100)
                }
            }
...}
while(still_running);

**in CheckEvent:**
do {
        int msg_in_queue = 0;
        msg = curl_multi_info_read(multi_handle, &msg_in_queue);
       ....
     }
while(msg)
~~~
When I don't allow my application to use mobile data in the background ( HTTP requests still are sent in this case), the msg return nullptr and when I turn on the internet. Both old and new HTTP requests add to multi curl cannot be sent and msg in CheckEvent function always return nullptr.

Platform: Android
Curl version: 7.64.1
Please help me to address this problem. Thanks

**Comment by bagder** [comment] 2020-06-30 07:23
libcurl will not return error just because the transfer is slow or stalled. If there's no error detected, libcurl will continue. If you want to error out when nothing happens for a long period of time, you need to use libcurl's timeout options or make your own.

This is by design.

**Comment by dangvohoanganhvn** [comment] 2020-06-30 08:01
When I turn on the Internet ( good network), the transfer still does not continue.

**Comment by bagder** [comment] 2020-06-30 08:44
I'm not sure what that means in pure technical terms. curl doesn't know when the network is good or bad, it just knows if there's an established connection and it will wait for activity on that (until the transfer is done, fails or times out). There's no difference to curl if the connection is idle because it isn't "allowed to use it" or because the server just doesn't send anything.

I read this as saying that the connection is again transferring data after a previous period of idleness and curl is then not delivering that data to the application as expected. Correct?

I'm afraid that I'm not able to reproduce any such problem so I would suggest you set a break-point in curl and first figure out in which general state it is in `data->mstate` and then what socket "activities" it checks and that the pattern includes the connection it should check and then ultimately how it comes those activities are not detected on the connection.

Another angle to debugging would be to try to reproduce this setup in a plain desktop surrounding with a simple libcurl-using demo app.

**Comment by dangvohoanganhvn** [comment] 2020-06-30 09:13
Good network I mean that I  use wifi to search/play the web, youtube, music,... other application with very fast loading. And I really don't know curl connection whether being transfer data or not. the problem is that although the network is on, curl lib does not return any error code or data after a long time and when call **curl_multi_info_read** the msg ptr always null and still_running var having value ( equal the number of requests) when call **curl_multi_perform**,  and the nums_fd is 0 when call **curl_multi_wait(..)**

**Comment by bagder** [comment] 2020-06-30 09:21
I understand, and that's why I proposed the approach to debugging this as outlined above.

**Comment by dangvohoanganhvn** [comment] 2020-06-30 11:34
It's very hard for me to debug curl code... Is there a better solution for this issue?

**Comment by bagder** [comment] 2020-06-30 12:29
Until we know what the problem is, it is very hard to say what the (best) solution is.

And if we cannot reproduce the problem, it is hard for us to debug the issue.

If none of us can debug the issue, all we have left is trying different versions and guessing.

**Comment by dfandrich** [comment] 2020-06-30 15:38
On Tue, Jun 30, 2020 at 01:01:33AM -0700, Anh Dang Vo Hoang wrote:
> When I turn on the Internet ( good network), the transfer still does not
> continue.

When you turn on the Internet, does the device receive the same IP address that
it had when the transfer started?  If not, then the existing transfers cannot
continue—that's just how IP works. You would need to configure something like
Mobile IP or a VPN to keep a stable IP address. Otherwise, you will be forced
to tear down the old connection and start a new one with the new IP address and
use "resume" in order to continue a transfer.

**Comment by dangvohoanganhvn** [comment] 2020-07-01 06:49
> Until we know what the problem is, it is very hard to say what the (best) solution is.
> 
> And if we cannot reproduce the problem, it is hard for us to debug the issue.
> 
> If none of us can debug the issue, all we have left is trying different versions and guessing.

thanks for your helping. I maybe workaround with this case by cleaning up multi curl handle and reinitialize it again...

**Comment by dangvohoanganhvn** [comment] 2020-07-01 06:51
> On Tue, Jun 30, 2020 at 01:01:33AM -0700, Anh Dang Vo Hoang wrote: When I turn on the Internet ( good network), the transfer still does not continue.
> When you turn on the Internet, does the device receive the same IP address that it had when the transfer started? If not, then the existing transfers cannot continue—that's just how IP works. You would need to configure something like Mobile IP or a VPN to keep a stable IP address. Otherwise, you will be forced to tear down the old connection and start a new one with the new IP address and use "resume" in order to continue a transfer.

I test all of your cases you mentioned (keep use mobile data and turn on wifi,...) however the transfers still don't continue.

**Comment by dfandrich** [comment] 2020-07-01 15:32
Do you know what happens at the routing level during those cases? It wouldn't
surprise me if a phone that has both 3G and WiFi data will remove the route to
3G data (or close the PDP context) to force applications to use WiFi instead.
That kind of case would also prevent an existing transfer over 3G to stop.

**Comment by bagder** [comment] 2020-08-12 08:25
Without more details or a way to reproduce this issue, I'm going to close it soon.

**Closed** 2020-08-21 08:27 UTC
Labels: needs-info-or-update, not-a-bug
