### ISSUE TITLE
curl throws away partial downloads on retry, even if told to resume

### ISSUE THREAD

**Issue by lolilolicon** [curl/curl#1084] opened 2016-10-24 08:59 UTC
Say I want to download a large file, 1 GiB perhaps. I specify `-O`.
My network connection isn't very reliable, so I specify `-m` and `--retry`, so it doesn't hang up.

The problem is, on every retry, the output file is truncated, effectively throwing away all the work so far.
```
Warning: Transient problem: timeout Will retry in 1 seconds. 5 retries left.
Throwing away 327962289 bytes
```
This is wasteful, and makes `--retry` quite useless.
At least, if `-C -` is specified, it's pretty clear the user wants to _always_ resume automatically.

The workaround is to either not to use `--retry` & shell-wrap `curl` in a `for` loop, or to use `wget`.

Relevant [source](https://github.com/curl/curl/blob/8e8afa82cbb629bd2a95eba1cdf47f65dd62a6d5/src/tool_operate.c#L1521), for anyone interested.

---
curl 7.50.3

**Comment by bagder** [comment] 2016-10-24 09:52
As that output suggests, this is not a bug but actually a missing feature. I would welcome to have such functionality added.

**Comment by bagder** [comment] 2016-10-27 21:41
This is now mentioned as a suggestion in the TODO. Closing this for now.

**Closed by bagder** 2016-10-27 21:41 UTC
Labels: cmdline tool, feature-request
