### ISSUE TITLE
Strange output with cURL 7.61.0 and PuTTY 0.70

### ISSUE THREAD

**Issue by SeLLeRoNe** [curl/curl#2781] opened 2018-07-23 16:23 UTC
### I did this
Installed cURL 7.61.0 from source
Tried to get Header information for google.it (using PuTTY 0.70 to connect to the server)
Tried also with the OS  version of cURL 7.29.0, the problem doesn't appear because cURL is not changing the output color)

I guess that the color change is not reset when needed.

Connecting using a linux console doesn't show the same issue, it is something related to PuTTY and cURL, not sure which one to blame more tho :)

### I expected the following
A normal output from curl -I command
### curl/libcurl version
>curl -V
curl 7.61.0 (x86_64-pc-linux-gnu) libcurl/7.61.0 OpenSSL/1.0.2k zlib/1.2.7 nghttp2/1.32.0
Release-Date: 2018-07-11
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy

### operating system
CentOS 7.5.1804 (Core)
![curl output](https://user-images.githubusercontent.com/9599441/43089524-c08c5f7a-8e9c-11e8-85d2-bada8a141a3b.PNG)

**Comment by bagder** [comment] 2018-07-23 18:56
Duplicate of #2736

**Closed by bagder** 2018-07-23 18:56 UTC
