### ISSUE TITLE
POST over http(s) bug when the data are not sent all at once

### ISSUE THREAD

**Issue by vfloyd6** [curl/curl#2947] opened 2018-09-06 14:28 UTC
Hello !

### I did this
I found an infinite loop when trying to POST data over https. If the data can't be sent all at once, the lib is gonna loop indefinetly spamming wrong data.  (until the server closes the connection).

The fact that it has not been seen is that the POST data are probably always all sent at once. But I'm working under wince 5 and the system probably has to do with the fact that my data are split.

### How I fixed it

I've fixed it by changing the following line :

file http.c line 1148
FROM THIS
http->writebytecount += bodylen;
TO THIS
http->writebytecount += amount;

### I expected the following
The data are sent properly :)

### curl/libcurl version
I've found this issue with libcurl 7.59.0 but from what I can see the bug is still present in the latest version (7.61.1)

### operating system
wince 5.

**Comment by bagder** [comment] 2018-09-07 12:30
Seem entirely correct. I'll write up a PR with this...

**Comment by vfloyd6** [comment] 2018-09-07 12:42
Thank you for the fast review.

**Comment by bagder** [comment] 2018-09-08 21:26
I was too quick. This change causes numerous tests failures. Looking at it closer, I can't really see why you need this change. Can you explain your rationale for this patch?

`bodylen` in this function is the number of *body bytes* sent. `amount` is the total number of bytes sent, both header and body.

**Comment by vfloyd6** [comment] 2018-09-11 13:16
I didn't checked it very in depth. It's just that without this patch libcurl keeps sending the N last bytes of my payload indefinetly eventhough the entire payload has already been sent. For example, sending "abcdef" will result in sending "abcdefdefdefdefdefdefdef........"

The thing is we just called Curl_write() and it actually wrote "amount" bytes. I don't understand why we would substract "headlen". Like line 1143, "bytes_written" is incremented with "amount", not with "bodylen".

I've tried to write an example to reproduce the issue under win32 cause I guess you have no way to run an example under wince ... But I can't manage to compile it properly for win32 with visual 2008 and with HTTPS support. I don't have a lot of time to work on it either unfortunatly.

**Comment by bagder** [comment] 2018-09-20 12:10
You can't provide a reproducible example and your suggest fix breaks this code for everyone. This issue isn't reproducible for the rest of us. We also have test 1522 that sends 40K POST data with a 4K send buffer, thus very likely to exercise this code path - and this works in the CI on all platforms.

Unless we get more data/info on this, I don't see what else we can do but to close this.

**Comment by vfloyd6** [comment] 2018-09-20 12:40
I reproduce the issue as long as the buffer is not sent all at once. I don't know if you can ensure your test case reproduces this. If you don't want to "fix" I'm fine since you don't reproduce it I just wanted to let you know what I found. Are you compiling with USE_SCHANNEL;USE_WINDOWS_SSPI;USE_WINSOCK ?

**Comment by bagder** [comment] 2018-09-20 12:58
> I don't know if you can ensure your test case reproduces this

I don't think we can be sure, no.

> If you don't want to "fix"

I want it fixed, but that's hard when we can't reproduce and the only suggested fix so far was incorrect... I have not seen an error in the code by manual review either.

**Comment by jay** [comment] 2018-09-20 18:06
We need your curl_version() and a self contained example that can be used to reproduce. Is there something about your repro that is specific to WinCE? If you can't give us the server then use httpbin.org to do the POST.

**Comment by jacmet** [comment] 2018-10-19 21:09
Maybe related to this, flickcurl (http://librdf.org/flickcurl/) hangs when uploading big images with 7.61.1, but not 7.61.0 (openssl 1.0.2 as TLS backend). flickcurl does a multipart form post to https://up.flickr.com.
It starts nicely sending blocks of ~16KB data but then gets stuck in a poll loop:
`write(3, "\27\3\3@\30\3\211\345\316\202\24\354\16\264\21\206I$\210\357\236\21\3508\373\255\265\251\204\243\237\241"..., 16413) = 16413
poll([{fd=3, events=POLLIN}], 1, 110)   = 0 (Timeout)
poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
poll([{fd=3, events=POLLIN}], 1, 1000)  = 0 (Timeout)
poll(NULL, 0, 1000)                     = 0 (Timeout)
poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
poll([{fd=3, events=POLLIN}], 1, 1000)  = 0 (Timeout)
poll(NULL, 0, 1000)                     = 0 (Timeout)
poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
poll([{fd=3, events=POLLIN}], 1, 1000)  = 0 (Timeout)
poll(NULL, 0, 1000)                     = 0 (Timeout)
poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
poll([{fd=3, events=POLLIN}], 1, 1000)  = 0 (Timeout)
poll(NULL, 0, 1000)                     = 0 (Timeout)
poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
poll([{fd=3, events=POLLIN}], 1, 1000)  = 0 (Timeout)
poll(NULL, 0, 1000)                     = 0 (Timeout)
poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
poll([{fd=3, events=POLLIN}], 1, 1000)  = 0 (Timeout)
poll(NULL, 0, 1000)                     = 0 (Timeout)
poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
poll([{fd=3, events=POLLIN}], 1, 1000)  = 0 (Timeout)
poll(NULL, 0, 1000)                     = 0 (Timeout)
poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
poll([{fd=3, events=POLLIN}], 1, 1000)  = 0 (Timeout)
`

**Comment by bagder** [comment] 2018-10-19 22:12
@jacmet this isn't the same symptom as the original description at all so I don't think we can assume or even suspect this is the same problem. Can you perhaps file a new issue and when doing so, also answer to my questions below?

Can you trigger this in any other way than actually sending data to flickr, like for debugging? Have you tried/considered bisecting to find the offending change that broke this functionality? Between 7.61.0 and 7.61.1 there's less than 200 commits so it should be possible to find in 7-8 builds.

**Comment by jacmet** [comment] 2018-10-20 06:50
@bagder sure, will do so!

**Comment by jacmet** [comment] 2018-10-20 08:50
@badger New issue: https://github.com/curl/curl/issues/3151

**Comment by slib00** [comment] 2019-03-02 00:23
good

**Comment by bagder** [comment] 2019-03-06 10:53
We can't reproduce, the suggested fix is wrong and there's been no additional comment from the reporter in 5 months. This case won't move. I'm closing this. If more details should appeare we can reopen or file a new one!

**Closed by bagder** 2019-03-06 10:53 UTC
Labels: HTTP
