### ISSUE TITLE
Unable to disable sslv3

### ISSUE THREAD

**Issue by grosch** [curl/curl#912] opened 2016-07-13 00:21 UTC
### I did this

curl -k --cacert client.pem --tlsv1.2 https://....

### I expected the following

Some data to come back :)  Instead, I'm getting this ssl3 error.  The site has disabled SSL3, and I expected that by specifying --tlsv1.2 that I was forcing that and disabling sslv3

curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure

### curl/libcurl version

curl 7.49.1 (x86_64-apple-darwin15.5.0) libcurl/7.49.1 OpenSSL/1.0.2h zlib/1.2.5 nghttp2/1.12.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets 

### operating system

Mac El Capitan

**Comment by jay** [comment] 2016-07-13 01:52
In your case by default TLS v1.0 - 1.2 is used, but if you specify `--tlsv1.2` then solely TLSv1.2 is used. In more detail: If you use [`--tlsv1.2`](https://curl.haxx.se/docs/manpage.html#--tlsv12) *and* you are using curl/libcurl >= 7.34.0 *and* libcurl was built with an SSL library that supports TLSv1.2 connections then libcurl will tell it to only allow TLSv1.2. You can see the actual code we use for OpenSSL [here](https://github.com/curl/curl/blob/curl-7_49_1/lib/vtls/openssl.c#L1849-L1854). By default in curl/libcurl >= 7.39.0 SSLv3 is not used unless you specify [`-3, --sslv3`](https://curl.haxx.se/docs/manpage.html#-3).

The error you are seeing is very likely because the server does not support TLSv1.2 as you thought.  If the server is public the easiest way to get information on protocol intolerance is using [SSL Labs' free SSL testing](https://www.ssllabs.com/ssltest/) and when it finishes the report go to Configuration > Protocols to see which ones are supported. Update this thread with the result. If TLSv1.2 is supported I will need the website URL to try to reproduce.

**Comment by grosch** [comment] 2016-07-13 02:37
Thanks, Jay. Unfortunately that site only works with port 443 and this site is on a nonstandard port. Do you have other ways I can check this?

**Comment by jay** [comment] 2016-07-13 05:19
Yes, use [SSL/TLS Security Test by High-Tech Bridge](https://www.htbridge.com/ssl/), also free

**Comment by grosch** [comment] 2016-07-13 05:38
OK, looks like a server configuration issue.  As soon as I put the 'SSLVerifyClient require' directive in the VirtualHost block I get that error.  If I take it out, then I don't.  I know it's not a curl issue, but if you've got any ideas I'm all ears.  I'm basically trying to make it so that the client has to present a certificate which was signed by the server.  I've got my

**Comment by jay** [comment] 2016-07-13 07:00
? your message cut off. But yeah if you put SSLVerifyClient require and the client cert either isn't presented or is bad then apache will drop the connection. My guess is the cert isn't presented based on the alert message you received. curl has a [`--cert`](https://curl.haxx.se/docs/manpage.html#-E) option that you use for that. Your private key has to be in the certificate so you do something like this:
~~~
cat client.key client.crt > client.pem
curl --cert client.pem:yourpasswordhereifany https://host
~~~

In Apache's httpd-ssl.conf you will also need to enable `SSLCACertificateFile` (or Path) and it must contain the CA that signed the client certificate.

Closing since this isn't a curl issue. If you have curl questions in the future please ask on one of the [mailing lists](https://curl.haxx.se/mail/).

**Closed by jay** 2016-07-13 07:00 UTC
Labels: SSL/TLS
