### ISSUE TITLE
./configure --with-openssl breaks with release 8.1.1

### ISSUE THREAD

**Issue by mmdevl** [curl/curl#11208] opened 2023-05-26 06:44 UTC
### I did this

```
curl -s -O https://curl.se/download/curl-8.1.1.tar.xz
tar xf curl-8.1.1.tar.xz
cd curl-8.1.1
./configure --with-openssl
```

### I get this

```
checking run-time libs availability... failed
configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lnghttp2   -lssl -lcrypto -lssl -lcrypto   -lz 
```

the generated file `run-compiler` (which seems to be new) looks like this

```
CC=gcc -std=gnu11
LD_LIBRARY_PATH=
exec $CC $@
```

and is run like this:

```
configure:18715: sh ./run-compiler -o conftest -Werror-implicit-function-declaration   conftest.c  >&5
./run-compiler: line 1: -std=gnu11: command not found
./run-compiler: line 3: exec: -o: invalid option
```

### fix 1

rerun `autoconf`

### fix 2

Replace line 6679 of `configure` with this

```
echo "CC='$CC'" > $compilersh
```

### operating system

```
Linux asterix 5.13.0-1.el7.elrepo.x86_64 #1 SMP Sun Jun 27 19:45:23 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bagder** [comment] 2023-05-26 06:51
Duplicate of #11179 fixed in #11180 + #11182. Try git master.

**Closed** 2023-05-28 06:38 UTC
Labels: build, duplicate
