### ISSUE TITLE
Public and Private Keys stopped working in later versions

### ISSUE THREAD

**Issue by fborges22** [curl/curl#10757] opened 2023-03-13 19:01 UTC
**Greetings,**

I am having problems with libcurl and curl that I cannot access my SFTP server using my private and public keys. Recently, when libcurl and curl was updated it stopped working. Please note that my login certificates types are:

/home/fborges/Shared/SFTPDEV_PREFERED/nopass/id_rsa.pub: OpenSSH RSA public key
/home/fborges/Shared/SFTPDEV_PREFERED/nopass/id_rsa:     PEM RSA private key

### I did this

curl --key ~/Shared/SFTPDEV_PREFERED/nopass/id_rsa --pubkey ~/Shared/SFTPDEV_PREFERED/nopass/id_rsa.pub sftp://alien@server2.borges.tec.br/home/alien

### I expected the following

Sucessfully access to my SFTP Server

### curl/libcurl version

[curl -V output]

curl 7.88.1 (x86_64-pc-linux-gnu) libcurl/7.88.1 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.52.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

**Comment by bagder** [comment] 2023-03-13 21:50
Since all of that is handled by the SSH library @libssh2, it seems like that this change is not due to curl at all.

I *presume* your updated curl also updated libssh2 at some point?

**Comment by fborges22** [comment] 2023-03-13 22:11
Yes. I updated curl and libssh2 at some point. I am also using it in my latest version of Arch Linux and OpenSUSE distros. When I tried to run that command using an earlier version of Oracle Linux (i.e., 8.5) the curl command works normally with my login certificates.

**Comment by dfandrich** [comment] 2023-03-13 22:41
Did you update your SSH server at the same time? Recent OpenSSH versions disable some algorithms by default that might be causing the problem.

**Comment by fborges22** [comment] 2023-03-13 23:24
Yes. I did update my SSH server and the problem persists.

**Comment by dfandrich** [comment] 2023-03-13 23:53
I'm suggesting that's the cause of the problem. Try reconfiguring your server to enable some algorithms that it has disabled by default.

**Comment by fborges22** [comment] 2023-03-14 01:12
What algorithms should be interesting to enable? There are several of them and could you please give some suggestions? I noticed that in my older client on Oracle Linux 8.5 the curl is working normally. However, they are using an early version of the libraries.

**Comment by dfandrich** [comment] 2023-03-14 01:19
The algorithms supported by libssh2 are listed at https://libssh2.org/
You can use "ssh -Q X" to see what protocols are supported by OpenSSH, assuming
that your ssh and sshd are of the same version (see man ssh to find the
various X).  If you enable debug logging in curl, you should get some
indication what protocols are attempted to be negotiated.

**Comment by fborges22** [comment] 2023-03-14 01:28
Here is my algorithms supported. I noticed that ssh-rsa is supported and my login public key and private key was generated using him. Also, my SSH and SSHD are the same version.

ssh-ed25519
ssh-ed25519-cert-v01@openssh.com
sk-ssh-ed25519@openssh.com
sk-ssh-ed25519-cert-v01@openssh.com
ssh-rsa
ssh-dss
ecdsa-sha2-nistp256
ecdsa-sha2-nistp384
ecdsa-sha2-nistp521
sk-ecdsa-sha2-nistp256@openssh.com
ssh-rsa-cert-v01@openssh.com
ssh-dss-cert-v01@openssh.com
ecdsa-sha2-nistp256-cert-v01@openssh.com
ecdsa-sha2-nistp384-cert-v01@openssh.com
ecdsa-sha2-nistp521-cert-v01@openssh.com
sk-ecdsa-sha2-nistp256-cert-v01@openssh.com

**Comment by dfandrich** [comment] 2023-03-15 17:54
That looks like the `sig` list, but there are several other types that are involved in protocol negotiation; see `ssh -Q help`. You'll then need to edit `/etc/ssh/sshd_config` to enable an algorithm on the server that libssh2 speaks. It's probably as simple as adding `PubkeyAcceptedAlgorithms +ssh-rsa` to /etc/ssh/sshd_config.

**Comment by fborges22** [comment] 2023-03-16 11:27
I tried to add the `PubkeyAcceptedAlgorithms +ssh-rsa` to the `/etc/ssh/sshd_config` and I am still getting the same error login denied.

**Comment by fborges22** [comment] 2023-03-16 18:45
I am getting these at my SSH server according to `systemctl status sshd`

`Mar 16 18:39:10 server2 sshd[2835]: Received disconnect from 177.143.134.22 port 40564:11: [SFTP][DISCONNECT] Normal Shutdown due to Close request\\n [postauth]
Mar 16 18:39:10 server2 sshd[2835]: Disconnected from user sftpuser 177.143.134.22 port 40564 [postauth]
Mar 16 18:39:10 server2 sshd[2835]: pam_unix(sshd:session): session closed for user sftpuser
Mar 16 18:39:10 server2 sshd[2841]: Accepted password for testuser from 177.143.134.22 port 40576 ssh2
Mar 16 18:39:10 server2 sshd[2841]: pam_unix(sshd:session): session opened for user testuser(uid=1002) by (uid=0)
Mar 16 18:39:11 server2 sshd[2841]: pam_unix(sshd:session): session closed for user testuser
Mar 16 18:39:11 server2 sshd[2873]: Accepted password for testuser from 177.143.134.22 port 40588 ssh2
Mar 16 18:39:11 server2 sshd[2873]: pam_unix(sshd:session): session opened for user testuser(uid=1002) by (uid=0)
Mar 16 18:44:10 server2 sshd[2936]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
Mar 16 18:44:10 server2 sshd[2936]: Connection closed by authenticating user alien 177.143.134.22 port 54140 [preauth]`

**Comment by dfandrich** [comment] 2023-03-16 19:29
It's probably being overridden by another line somewhere, perhaps in /etc/ssh/sshd_config.d/

**Comment by fborges22** [comment] 2023-03-16 19:35
I noticed that there is an single file in `/etc/ssh/sshd_config.d/` named `50-redhat.conf`. In his contents, I noticed that an file are being included:

Include /etc/crypto-policies/back-ends/opensshserver.config
SyslogFacility AUTHPRIV
ChallengeResponseAuthentication no
GSSAPIAuthentication yes
GSSAPICleanupCredentials no
UsePAM yes
X11Forwarding yes
PrintMotd no

The contents of `/etc/crypto-policies/back-ends/opensshserver.config` is:

Ciphers aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr,aes128-gcm@openssh.com,aes128-ctr
MACs hmac-sha2-256-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha1,umac-128@openssh.com,hmac-sha2-512
GSSAPIKexAlgorithms gss-curve25519-sha256-,gss-nistp256-sha256-,gss-group14-sha256-,gss-group16-sha512-
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512
HostKeyAlgorithms ecdsa-sha2-nistp256,ecdsa-sha2-nistp256-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-256-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-512-cert-v01@openssh.com
PubkeyAcceptedAlgorithms ecdsa-sha2-nistp256,ecdsa-sha2-nistp256-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-256-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-512-cert-v01@openssh.com
CASignatureAlgorithms ecdsa-sha2-nistp256,sk-ecdsa-sha2-nistp256@openssh.com,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,sk-ssh-ed25519@openssh.com,rsa-sha2-256,rsa-sha2-512
RSAMinSize 2048

**Comment by dfandrich** [comment] 2023-03-16 19:46
There you go!

**Comment by fborges22** [comment] 2023-03-16 19:53
I added the ssh-rsa to the `PubkeyAcceptedAlgorithms` in the file `/etc/crypto-policies/back-ends/opensshserver.config` and I am still getting the error 67 in libcurl as logged by sshd:

Mar 16 19:50:10 server2 sshd[5334]: Server listening on 0.0.0.0 port 22.
Mar 16 19:50:10 server2 sshd[5334]: Server listening on :: port 22.
Mar 16 19:50:10 server2 systemd[1]: Started OpenSSH server daemon.
Mar 16 19:50:19 server2 sshd[5337]: Connection closed by authenticating user alien 177.143.134.22 port 54720 [preauth]
Mar 16 19:50:52 server2 sshd[5341]: Connection closed by authenticating user alien 177.143.134.22 port 54732 [preauth]
Mar 16 19:51:12 server2 sshd[5343]: Connection closed by authenticating user alien 177.143.134.22 port 54746 [preauth]
Mar 16 19:51:40 server2 sshd[5345]: Connection closed by authenticating user alien 177.143.134.22 port 54760 [preauth]
Mar 16 19:51:55 server2 sshd[5347]: Connection closed by authenticating user alien 177.143.134.22 port 54772 [preauth]
Mar 16 19:52:25 server2 sshd[5351]: Connection closed by authenticating user alien 2804:1b3:a9c0:dcdc:975f:cdf1:ea6e:b068 port 46728 [preauth]
Mar 16 19:52:30 server2 sshd[5353]: Connection closed by authenticating user alien 2804:1b3:a9c0:dcdc:975f:cdf1:ea6e:b068 port 54318 [preauth]

**Comment by dfandrich** [comment] 2023-03-16 20:27
You've moved past that problem and have hit a different issue. You'll probably
have to client logs to figure out what's going on here. It's probably another
mismatched protocol that the client is now have trouble with.

**Comment by fborges22** [comment] 2023-03-16 22:20
In the client side, I enabled the DEBUG in libcurl and I am getting these:

Running...
[DEBUG][CLIENT] [SFTP][tSFTPAuthCertFileDownload] Doing now the CURL_EASY_PERFORM...
[DEBUG][CLIENT] [SFTP] ** Info:   Trying 129.151.37.36:22...
[DEBUG][CLIENT] [SFTP] ** Info: Connected to server2.borges.tec.br (129.151.37.36) port 22 (#0)
[DEBUG][CLIENT] [SFTP] ** Info: SSH MD5 public key: NULL
[DEBUG][CLIENT] [SFTP] ** Info: SSH SHA256 public key: NULL
[DEBUG][CLIENT] [SFTP] ** Info: SSH authentication methods available: publickey,gssapi-keyex,gssapi-with-mic
[DEBUG][CLIENT] [SFTP] ** Info: Using SSH public key file 'd:\Keys\SFTPDEV_DSA\withpass\id_dsa.pub'
[DEBUG][CLIENT] [SFTP] ** Info: Using SSH private key file 'd:\Keys\SFTPDEV_DSA\withpass\id_dsa'
[DEBUG][CLIENT] [SFTP] ** Info: SSH public key authentication failed: Username/PublicKey combination invalid
[DEBUG][CLIENT] [SFTP] ** Info: Authentication failure
[DEBUG][CLIENT] [SFTP] ** Info: Closing connection 0
[ERROR][CLIENT] SFTPDwld2() Failed - Error 67 : Login denied
cStatus reported: 67
cError1 reported: SFTPDwld2() Failed - Error 67 : Login denied

**Comment by dfandrich** [comment] 2023-03-17 18:08
Try commenting out all those other config overrides because they may be disabling other algorithms. When I tested libssh2 1.10.0 against OpenSSH 9 in the latest Fedora it only took that one `PubkeyAcceptedAlgorithms` change to let it work. If you enable trace logging in libssh2 you'll get more detailed information about what part of the handshake is failing.

But, this is clearly not a curl problem so I'm going to close this issue here.

**Closed by dfandrich** 2023-03-17 18:08 UTC
Labels: SCP/SFTP

**Comment by fborges22** [comment] 2023-03-17 18:49
I commented out all the other config overrides and the problems persists. I will open an issue in the LIBSSH2 because it seems that the problem are in the roots of LIBSSH2 and/or OpenSSL.
