### ISSUE TITLE
misses call to POLL_REMOVE since conn->data is already clear when socket closes

### ISSUE THREAD

**Issue by bagder** [curl/curl#3597] opened 2019-02-21 15:49 UTC
### I did this

Pavel Löbl submitted [this report](https://curl.haxx.se/mail/lib-2019-02/0101.html):

> I've noticed that SOCKETFUNCTION is called to POLL_REMOVE the socket from watched set after the socket was already closed by curl internally.

> I think I've identified the code path. It all starts in Curl_disconnect. At first Curl_conncache_remove_conn unlinks easy handle from connectdata structure then conn_free is called. conn_free calls Curl_closesocket which calls Curl_multi_closed. However Curl_multi_closed expects there is still easy handle associated so it does nothing (not calling SOCKETFUNCTION). Control is returned to Curl_multi_closed where socket is closed. Later the SOCKETFUNCTION is called probably from singlesocket function.

A quick look gives Pavel right. 'conn->data' is already cleared when `conn_free()` is called so when it closes the socket, it can't find the multi handle and no remove callback is called.

### curl/libcurl version

curl git master

### operating system

all

**Comment by jay** [comment] 2019-02-21 20:37
I just submitted a PR for this. I finished working on it before I had read your [reply](https://curl.haxx.se/mail/lib-2019-02/0102.html) to the mailing list that you were going to work on it.

**Comment by loblik** [comment] 2019-02-22 07:24
Using https://github.com/curl/curl/commit/6a45ac5bbd8b626a72ec062b9b37679d29e64e3e solves the problem. Not able to reproduce it any longer.

**Comment by jay** [comment] 2019-02-22 20:24
> Using [6a45ac5](https://github.com/curl/curl/commit/6a45ac5bbd8b626a72ec062b9b37679d29e64e3e) solves the problem. Not able to reproduce it any longer.

Just landed it thanks for testing

**Closed** 2019-02-22 20:23 UTC
