### ISSUE TITLE
Could not resolve host on any link on windows 10

### ISSUE THREAD

**Issue by s00ny5** [curl/curl#13155] opened 2024-03-20 16:15 UTC
### I did this

Any links I use will return the same error: Could not resolve host.
I also disabled firewalls and antivirus. 
Tried HTTP and HTTPS links. 
cUrl is the latest one 8.6.0 from vcpkg.

```
    curl_version_info_data* ver = curl_version_info(CURLVERSION_NOW);
      printf("%s\n", curl_version());

        curl_global_init(CURL_GLOBAL_ALL);
        CURL* curl = curl_easy_init();
        if (!curl) {
            std::cout << "Error: Unable to initialize cURL." << std::endl;
        }


        // Set the cURL options
        curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);
        curl_easy_setopt(curl, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);
        curl_easy_setopt(curl, CURLOPT_URL, "https://www.google.com");
        curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
        curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);
        curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);

        std::string apiResponse;

        // Set callback function to handle response data
        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteCallback);
        curl_easy_setopt(curl, CURLOPT_WRITEDATA, &apiResponse);
        curl_easy_setopt(curl, CURLOPT_DEBUGFUNCTION, WriteCallbackVerbose);
        curl_easy_setopt(curl, CURLOPT_TIMEOUT, 10);
        curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT, 10);

        // Perform the request
        CURLcode res = curl_easy_perform(curl);
        if (res != CURLE_OK) {
            std::cout << "Error: " << curl_easy_strerror(res) << std::endl;
        }
        else {
            // Print the API response
            std::cout << "API Response: " << apiResponse << std::endl;
        }

        // Clean up
        curl_formfree(formPost);
        curl_easy_cleanup(curl);
        curl_global_cleanup();
```

And this is the debug:
```
STATE: INIT => CONNECT handle 0x1122c840; line 1982
Added connection 0. The cache now contains 1 members
getaddrinfo() thread failed to start
Could not resolve host: google.com
The cache now contains 0 members
Curl_disconnect(conn #0, dead=1)
Closing connection
Expire cleared
Error: Couldn't resolve host name
```

### I expected the following

to load the link ..

### curl/libcurl version

curl 8.6.0

### operating system

Windows 10

**Comment by dfandrich** [comment] 2024-03-20 22:20
Can you access the site using the curl command-line? What is the output of curl -V?

**Comment by bagder** [comment] 2024-03-20 22:30
Then as a follow-up, does the curl 8.6.0 command line tool from https://curl.se/windows/ work? Because if it does, it smells like a vcpkg related issue maybe?

**Comment by s00ny5** [comment] 2024-03-20 23:49
ok. downloaded the curl.se and the cmd worked.
![image](https://github.com/curl/curl/assets/30322461/86c36479-7c8d-43ba-a07c-d0b9786caa74)

The dll had same problem in my project:
![image](https://github.com/curl/curl/assets/30322461/6fd0087c-f318-4288-aba1-702814001d88)

**Comment by jay** [comment] 2024-03-21 21:11
What is the `curl -V` of the vcpkg build that does not work? Does it work if you omit the ipv4 resolve option? Can you give a command line that can be used to reproduce?

> The dll had same problem in my project:

Which dll has the same problem in your project?

**Comment by s00ny5** [comment] 2024-03-22 00:43
> What is the `curl -V` of the vcpkg build that does not work? Does it work if you omit the ipv4 resolve option? Can you give a command line that can be used to reproduce? **Please use text and not screenshots.**
> 
> > The dll had same problem in my project:
> 
> Which dll has the same problem in your project?

The dll that ship in the zip from https://curl.se/windows/
This is the version info: libcurl/8.6.0-DEV Schannel zlib/1.3.1
"Does it work if you omit the ipv4 resolve option?" Nope. same error with or without.
"Can you give a command line that can be used to reproduce?" I don't have a command line. I use it as library in my c++ project. It should make a request to one of my websites.

**Comment by jay** [comment] 2024-03-22 06:19
> The dll that ship in the zip from https://curl.se/windows/

I downloaded the latest 64-bit release curl-8.6.0_7-win64-mingw and I cannot reproduce in Windows 10 unless I intentionally use a third party program to block your program's internet access. I modified your sample code to make it build:

~~~diff
--- a.cpp.orig	2024-03-22 02:04:12.060103600 -0400
+++ a.cpp	2024-03-22 02:05:54.712975000 -0400
@@ -1,3 +1,9 @@
+#include <curl/curl.h>
+#include <iostream>
+#include <string>
+
+int main()
+{
     curl_version_info_data* ver = curl_version_info(CURLVERSION_NOW);
       printf("%s\n", curl_version());
 
@@ -19,9 +25,9 @@
         std::string apiResponse;
 
         // Set callback function to handle response data
-        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteCallback);
-        curl_easy_setopt(curl, CURLOPT_WRITEDATA, &apiResponse);
-        curl_easy_setopt(curl, CURLOPT_DEBUGFUNCTION, WriteCallbackVerbose);
+        //curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteCallback);
+        //curl_easy_setopt(curl, CURLOPT_WRITEDATA, &apiResponse);
+        //curl_easy_setopt(curl, CURLOPT_DEBUGFUNCTION, WriteCallbackVerbose);
         curl_easy_setopt(curl, CURLOPT_TIMEOUT, 10);
         curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT, 10);
 
@@ -36,6 +42,9 @@
         }
 
         // Clean up
-        curl_formfree(formPost);
+        //curl_formfree(formPost);
         curl_easy_cleanup(curl);
         curl_global_cleanup();
+        
+        return 0;
+}
~~~

~~~
J:\curl-for-win_builds\curl-8.6.0_7-win64-mingw\bin>g++ -o a a.cpp -I..\include -L..\lib -lcurl
~~~

> This is the version info: libcurl/8.6.0-DEV Schannel zlib/1.3.1

That's not the curl_version output of the official curl dll, so your program is using a different curl dll. This is the curl_version output you should see:

~~~
libcurl/8.6.0 LibreSSL/3.8.3 zlib/1.3.1 brotli/1.1.0 zstd/1.5.5 WinIDN libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.60.0 ngtcp2/1.4.0 nghttp3/1.2.0
~~~

**Comment by s00ny5** [comment] 2024-03-22 08:58
Hey.

I forgot to say this is the **x86** dll as my app is for x86.
I also used the DLL from win32-mingw:
`libcurl/8.6.0 LibreSSL/3.8.3 zlib/1.3.1 brotli/1.1.0 zstd/1.5.5 WinIDN libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.60.0 ngtcp2/1.4.0 nghttp3/1.2.0
getaddrinfo() thread failed to start
Could not resolve host: portquiz.net
Closing connection
response_code: 0
Error: Couldn't resolve host name`
Regards

**Comment by jay** [comment] 2024-03-23 05:37
> I also used the DLL from win32-mingw

It works here. You could try building libcurl and debugging it and stepping into init_resolve_thread to find out where it fails

https://github.com/curl/curl/blob/5ce164e0e9290c96eb7d502173426c0a135ec008/lib/asyn-thread.c#L896-L902

**Comment by s00ny5** [comment] 2024-03-24 11:54
Hey,
I did what you said and here is where is failing:
"init_thread_sync_data"
![image](https://github.com/curl/curl/assets/30322461/9bac5d38-56fc-47ac-b845-192c5b47f306)
Further:
"Curl_socketpair"
![image](https://github.com/curl/curl/assets/30322461/98a0b9dc-5604-45a2-9deb-cbe68d3e53c8)

Regards

**Comment by jay** [comment] 2024-03-24 20:43
> "Curl_socketpair"

It's failing at accept which allows incoming connections on the socket, in this case localhost, so maybe your firewall or third party software is blocking it. that is very unusual. windows firewall normally allows localhost connections even if you block other connections.

try WSAGetLastError() to get more info

~~~diff
diff --git a/lib/socketpair.c b/lib/socketpair.c
index d01b255..b76f614 100644
--- a/lib/socketpair.c
+++ b/lib/socketpair.c
@@ -121,8 +121,11 @@ int Curl_socketpair(int domain, int type, int protocol,
   pfd[0].revents = 0;
   (void)Curl_poll(pfd, 1, 1000); /* one second */
   socks[1] = accept(listener, NULL, NULL);
-  if(socks[1] == CURL_SOCKET_BAD)
+  if(socks[1] == CURL_SOCKET_BAD) {
+    int gle = WSAGetLastError();
+    fprintf(stderr, "accept failure: (%d) %s\n", gle, gai_strerrorA(gle));
     goto error;
+  }
   else {
     struct curltime start = Curl_now();
     char rnd[9];
~~~

you can build curl with CURL_DISABLE_SOCKETPAIR defined (or if you're using autotools ./configure --disable-socketpair) to disable localhost socketpair, but the build will lack support for some asynchronous behavior

**Comment by s00ny5** [comment] 2024-03-24 22:37
Hey,

I tried CURL_DISABLE_SOCKETPAIR:
`Host portquiz.net:80 was resolved.
IPv6: (none)
IPv4: 35.180.139.74
  Trying 35.180.139.74:80...
getsockname() failed with errno 10022: Invalid arguments
Connection timed out after 10002 milliseconds
Closing connection
response_code: 0
Error: Timeout was reached`

And the error from your suggestion:
`
accept failure: (10035) A non-blocking socket operation could not be completed immediately. 
`
Also I did specified I disabled windows firewalls and antivirus and no other firewall tool.

Regards

**Comment by jay** [comment] 2024-03-24 22:49
I don't think there's anything else we can do for you. It is something specific to your system. The non-blocking accept returns that error because the connection was not initiated (even though it should have been) and it's set not to block waiting for it. I've never seen a failure like that.

**Comment by s00ny5** [comment] 2024-03-25 21:08
I see.
Well, we can close this as I also found no other solutions.
Thank you for the answers.

**Comment by jay** [comment] 2024-04-02 18:50
No evidence this is a bug in curl. Closing.

**Closed by jay** 2024-04-02 18:50 UTC
Labels: not-a-bug, Windows
