### ISSUE TITLE
the io timeout of easy handle doesn't work when using multi interface

### ISSUE THREAD

**Issue by inter169** [curl/curl#1498] opened 2017-05-20 07:13 UTC
### I did this
I'm using the curl multiple API's, and using libevent API's to detect the events with curl easy handle's.
I have read the sample codes:
https://curl.haxx.se/libcurl/c/hiperfifo.html
and added some timeout's on socket I/O, like following:
...
curl_easy_setopt(conn -> easy, CURLOPT_CONNECTTIMEOUT, 5);
curl_easy_setopt(conn -> easy, CURLOPT_TIMEOUT, 10);
...

in my tests I set a gdb break point on my web server, so that the web server doesn't respond to the curl client, to see whether the client itself can detect the io time out.
Unfortunately, it can't detect the io time out which is set by CURLOPT_TIMEOUT option. 

### I expected the following
CURLOPT_TIMEOUT should work on the multi interface, 
as a workaround, when registered the socket event I passed a timeout:
//event_add(&f -> ev, NULL); //original codes
event_add(&f -> ev, &timeout);

### curl/libcurl version

libcurl-7.19.7-46.el6.x86_64

### operating system
CentOS release 6.7 (Final)

**Comment by bagder** [comment] 2017-05-20 09:17
The non-support for multi interface timeouts in 7.19.7 was documented in the KNOWN_BUGS document in that release (and many more). This is not a bug.

The timeout has however been supported for over **six years**, as we fixed that in 7.21.2 - released in October 2010.

Recommended action: use a modern libcurl version for best functionality.

**Closed by bagder** 2017-05-20 09:17 UTC
