### ISSUE TITLE
CMake static library error

### ISSUE THREAD

**Issue by ChrisWardy** [curl/curl#960] opened 2016-08-12 13:35 UTC
### I did this

I used libcurl as a static library in a cmake project where 
### I expected the following

cmake to not error on this line in lib/CMakeLists.txt:79
set_target_properties(${LIB_NAME} PROPERTIES STATIC_LIBRARY_FLAGS ${CMAKE_EXE_LINKER_FLAGS})
### curl/libcurl version

7.52
### operating system

Windows 8, VC++ 2015

**Comment by ChrisWardy** [comment] 2016-08-12 13:37
This can be easily fixed by putting quotes around ${CMAKE_EXE_LINKER_FLAGS}. I will submit a pull request shortly.

**Comment by Lekensteyn** [comment] 2016-10-31 00:03
Possible alternative is to check:
```
if(MSVC AND CURL_STATICLIB AND CMAKE_EXE_LINKER_FLAGS)
  set_target_properties(${LIB_NAME} PROPERTIES STATIC_LIBRARY_FLAGS ${CMAKE_EXE_LINKER_FLAGS})
endif()
```

but after reviewing the history, the change was introduced with 448d55ef0a2d6a0d8a18778f6d6a6a432d05bbb6 by @snikulov. Any idea here?

**Comment by snikulov** [comment] 2016-10-31 07:32
@Lekensteyn Peter, I'm not sure I understand what issues is. Refer to AppVeyour builds https://ci.appveyor.com/project/curlorg/curl/history

**Comment by Lekensteyn** [comment] 2016-10-31 09:31
@snikulov The issue is that when the variable `CMAKE_EXE_LINKER_FLAGS` is empty, it results in an arguments error (see secondcomment from @ChrisWardy).

My question is why you need to set `CMAKE_EXE_LINKER_FLAGS`, the one other place where it is set is with GSS enabled, but that seems a library for *nix and not so much Windows if I'm not mistaken?

**Comment by snikulov** [comment] 2016-10-31 09:41
@Lekensteyn Where is issue?
In which case CMAKE_EXE_LINKER_FLAGS becomes empty?
Did you see failed build on Windows/Linux on AppVeyour/Travis?
I suspect this issue is incorrectly described, or just plain wrong.

**Comment by snikulov** [comment] 2016-10-31 10:03
@ChrisWardy Could you please provide your command line or provide [MCVE](http://stackoverflow.com/help/mcve) for this case?
Thank you.

**Comment by Lekensteyn** [comment] 2016-10-31 10:07
@snikulov Issue is described by the author, I am just interpreting it :) My question for you remains, why do we need to set this target property for static builds?

**Comment by snikulov** [comment] 2016-10-31 10:17
@Lekensteyn should evaluate it. 
CMake is the tool with dynamic release schedule.
So perhaps now it's not required for CMake v3+ (hello cmake_minimum_required), but in time I 've done this change (back in 2013), it solves link issue as described (Ref to original issue here http://public.kitware.com/Bug/view.php?id=11240).

**Comment by bagder** [comment] 2017-03-14 23:07
so @snikulov and @Lekensteyn, do you have any proposed fixes for this?

**Comment by snikulov** [comment] 2017-03-15 07:18
@bagder As I mentioned earlier, I see no issue with static builds on CI servers.
But I could be wrong.
Since @ChrisWardy does not provide any further details for the issue - I suggest closing this issue.

**Comment by bagder** [comment] 2017-03-15 07:25
Thank you @snikulov, closing. Will reopen if someone brings more details and evidence of wrongdoings.

**Closed by bagder** 2017-03-15 07:25 UTC
Labels: cmake
