### ISSUE TITLE
Build using cmake incorrectly creates Libs.private with full paths

### ISSUE THREAD

**Issue by heitbaum** [curl/curl#12748] opened 2024-01-21 10:13 UTC
### I did this

Compile with `configure` generates a libcurl.pc with

### correct
```
prefix=/usr
exec_prefix=${prefix}
libdir=/usr/lib
includedir=${prefix}/include
supported_protocols="FILE FTP FTPS HTTP HTTPS RTMP RTSP"
supported_features="AsynchDNS HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile NTLM SSL TLS-SRP UnixSockets alt-svc libz threadsafe"

Name: libcurl
URL: https://curl.se/
Description: Library to transfer files with ftp, http, etc.
Version: 8.5.0
Libs: -L${libdir} -lcurl 
Libs.private: -lnghttp2 -lidn2 -lrtmp -lz -lssl -lcrypto -lssl -lcrypto -lssl -lcrypto -lz -lgcc
Cflags: -I${includedir}
```
Build with cmake
### incorrect
```
prefix=/usr
exec_prefix=${prefix}
libdir=/usr/lib
includedir=${prefix}/include
supported_protocols="FILE FTP FTPS HTTP HTTPS RTMP RTSP"
supported_features="SSL IPv6 UnixSockets libz AsynchDNS IDN Largefile alt-svc HSTS NTLM TLS-SRP HTTP2 HTTPS-proxy threadsafe"

Name: libcurl
URL: https://curl.se/
Description: Library to transfer files with ftp, http, etc.
Version: 8.5.0
Libs: -L${libdir} -lcurl 
Libs.private:  -lgcc -lgcc_s -lc -lgcc -lgcc_s -lidn2 /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-dev
el/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libssl.so /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86
_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libcrypto.so /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreE
LEC-Generic.x86_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libz.so /var/media/DATA/home-rudi/LibreELEC.tv/bu
ild.LibreELEC-Generic.x86_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libnghttp2.so
Cflags: -I${includedir}
```

### I expected the following

libcurl.pc should be -lyyyyy

### curl/libcurl version

curl 8.5.0

### operating system

LibreELEC 12 master build

**Comment by vszakats** [comment] 2024-01-23 18:43
Possibly duplicate of:
- #6169 aka KNOWN_BUGS 15.8.
- #6167 aka KNOWN_BUGS 15.7.

**Comment by vszakats** [comment] 2024-01-23 21:51
It'd be useful to know what rules autotools is following to decide which libpaths and libs to drop safely of those returned by dependencies.

**Comment by levitte** [comment] 2024-02-10 17:12
grep for CURL_LIBS in the top CMakeLists.txt.  Libraries are collected there, depending on what the configuration finds or assumes.  In cases where assumptions are made, you see simple library names being added, like for example:

https://github.com/curl/curl/blob/f8bd04ec50ba0a4e100267dec6a0a07cf238859a/CMakeLists.txt#L372-L385

In other cases, CMake functions like `find_library` or `find_package` are used to figure out all the details:

https://github.com/curl/curl/blob/f8bd04ec50ba0a4e100267dec6a0a07cf238859a/CMakeLists.txt#L658-L663

This is unsurprising if you know that CMake is that it's all about absolute paths, and rather deals with files specified as absolute paths over directory and file specified with different flags and other "magic", because that covers a large set of platforms, like Windows...  and it does work on Unix, even though it looks strange.

**Comment by levitte** [comment] 2024-02-10 17:14
I forgot to mention that later on in the same file, CURL_LIBS is processed into LIBCURL_LIBS using diverse CMake criteria.  This is the variable that's used for libcurl.pc.in → libcurl.pc in the case you show.

**Comment by vszakats** [comment] 2024-02-10 22:52
These absolute paths (e.g. `/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-dev
el/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/`) are coming from a pkg-config call or similar detection, and don't appear specific to the curl sandbox or cmake. I understand the desire is to magically guess if these absolute paths are or aren't wanted in a distributed `.pc` files and drop or keep them accordingly.

In this specific case, the absolute paths point to a local cross-toolchain root, which will be different in another env. It also remains a question how that other environment would magically find these lib dependencies without their paths present in the `.pc` file, and if this is what the builder wants.

ATM our CMakeLists.txt is passing through whatever it gets from detection. [ Except for presumably curl libs (under `if(TARGET ..)`) where there is some processing done. But this isn't hit in this report. ]

**Comment by vszakats** [comment] 2024-02-12 18:58
`CMake/FindNGHTTP3.cmake` could be wrong, but the original report shows `libssl`, `libcrypto`, `libz` and `libnghttp2` with their full paths, of which, OpenSSL and zlib libs are using CMake's own detection modules. What could be the explanation for that?

**Comment by levitte** [comment] 2024-02-12 20:32
You do know that `find_package(<name> ...)` works by, among others, running the module `Find<name>.cmake`, right?  So, the general way to find answers is to actually read those files.  It's quite educational!

Anyway, many if these Find*.cmake scripts find libraries and other files by using `find_path`, `find_file`, `find_library`, that sort of function.  As already mentioned, those CMake functions give you full paths, without exception.  So there's nothing wrong with `CMake/FindNGHTTP3.cmake`, it does exactly what it should.

Like I said earlier, having full paths to libraries in .pc files *isn't wrong*...  it's just unusual when you've lived your life with -L and -l...

**Comment by vszakats** [comment] 2024-02-12 20:51
> You do know that `find_package(<name> ...)` works by, among others, running the module `Find<name>.cmake`, right? So, the general way to find answers is to actually read those files. It's quite educational!

I do, yes. It was indeed helpful to better understand CMake. Not just the Find* ones but the rest too. (Also tracking an obscure FindOpenSSL.cmake incompatibility with BoringSSL, that triggers a build bug with libssh.)

> Anyway, many if these Find*.cmake scripts find libraries and other files by using `find_path`, `find_file`, `find_library`, that sort of function. As already mentioned, those CMake functions give you full paths, without exception. So there's nothing wrong with `CMake/FindNGHTTP3.cmake`, it does exactly what it should.
> 
> Like I said earlier, having full paths to libraries in .pc files _isn't wrong_... it's just unusual when you've lived your life with -L and -l...

Yes, though the reporter expects those paths to be missing from the `.pc` file.

Taking one step back: Just splitting the `/abspath/libname.a` style lib specs 
into `-L/abspath -lname` might already help or even fix the issue, because it 
allows to pass a correct local libpath manually and make the `.pc` file useful
(while ignoring the bogus libpath stuck there from the build env).

Splitting a libname like this is not always safe (e.g. for .DLLs), but perhaps 
splitting `<path>/lib<name>.a` to `-L<path> -l<name>` would be an
improvement?

**Comment by levitte** [comment] 2024-02-13 05:45
I heard your arguments and gave this a little bit of thought.  I think I have a solution, coming up!

**Comment by levitte** [comment] 2024-02-13 06:17
Regarding DLLs, is that applicable?  Considering that half the libraries in libcurl.pc are still specified in `-l` form, it seems that if there's a problem, it's already there anyway.

I've read somewhere that pkg-config on Windows does some, er, magic stuff that makes sense in a Windows environment...  haven't gone digging into that, though.

**Comment by vszakats** [comment] 2024-02-13 07:35
The chances are probably low for a DLL there, I'd just be conservative in selecting what to transform to avoid surprises.

One of the linked similar issues specifically mention `.so` files in a similar situation, but I have no idea how that should be handled.

**Comment by levitte** [comment] 2024-02-13 07:37
> One of the linked similar issues specifically mention `.so` files in a similar situation, but I have no idea how that should be handled.

Exactly like .a libraries, I'd say.

**Comment by vszakats** [comment] 2024-02-13 08:44
Regarding the direct DLL linking feature, here's the relevant doc:
https://sourceware.org/binutils/docs/ld/WIN32.html / 'direct linking to a dll' section.

(I remember `/patch/name.dll` to be a special case, but a quick skim of the docs doesn't confirm this.)

**Comment by levitte** [comment] 2024-02-13 12:05
I'd suggest that the DLL question should become another issue.  It's certainly a "fun" issue to dive into (believe you me, I've dealt a lot with that for OpenSSL), and I'd say it's not in scope for this PR.

**Comment by vszakats** [comment] 2024-02-13 12:07
Agreed, it's a corner case and it enough to tackle it when there is an actual report about it.

**Closed** 2024-03-07 08:19 UTC
Labels: cmake
