### ISSUE TITLE
FTP: CURLFTPMETHOD_NOCWD does not URL-decode the path

### ISSUE THREAD

**Issue by Zenju** [curl/curl#1974] opened 2017-10-09 13:18 UTC
### I did this

An FTP transfer with `CURLFTPMETHOD_NOCWD` selected.

A URL with one or more URL encoded "letters".

### I expected the following

The path to be URL decoded by curl before use.

### curl/libcurl version

any

### operating system

any

**Comment by bagder** [comment] 2017-10-09 13:25
Please elaborate or this will be closed within shortly.

**Comment by Zenju** [comment] 2017-10-09 13:39
I'm basically having the same issue as in https://github.com/curl/curl/issues/1812
When CURLFTPMETHOD_NOCWD is used and the URL contains a hash, e.g. "/dir/#name", then the rest including the hash is stripped, resulting in a file because lstArg is "/dir/" from the code example in the other ticket.

**Comment by bagder** [comment] 2017-10-09 14:07
duplicate of #1812

**Comment by Zenju** [comment] 2017-10-09 14:29
Okay, let's see what happens when we urlencode the string...

lstArg becomes /dir/%23name, still file not found, ups...

**Comment by bagder** [comment] 2017-10-09 14:33
That is a bug.

**Comment by bagder** [comment] 2017-10-09 20:52
I can't reproduce. So I edited test 298 to use an URL encoded path with nocwd (see commit above) and it works just fine.

**Comment by Zenju** [comment] 2017-10-10 09:23
It seems CURLOPT_CUSTOMREQUEST "MLSD" is needed to reproduce

**Comment by bagder** [comment] 2017-10-10 09:57
Not quite. But it seems a directory listing is needed!

**Closed** 2017-10-10 13:03 UTC
Labels: FTP, URL
