### ISSUE TITLE
curl_multi_fdset() change of behavior

### ISSUE THREAD

**Issue by jeroen** [curl/curl#11351] opened 2023-06-20 09:55 UTC
We have a unit test in the R bindings that was stable for many years, but seems to have broken after https://github.com/curl/curl/pull/10801. I am not sure if this is expected or not.

We use the test to check that the curl opens the expected number of concurrent connections to a host.

The unit test sets `CURLMOPT_MAX_HOST_CONNECTIONS` to 5 and then makes about 10 concurrent requests to a host, and then calls `curl_multi_fdset()` repeatedly as the requests complete. We assert repeatedly that `read_fd_set + write_fd_set` equals the smaller one of `running_handles` (as returned by `curl_multi_perform`) and `CURLMOPT_MAX_HOST_CONNECTIONS`.

It now started failing because `read_fd_set` is actually smaller than `CURLMOPT_MAX_HOST_CONNECTIONS`, suggesting that either libcurl is not making enough connections, or that `curl_multi_fdset()` is not showing all of them.

For example, we may see:

 - `CURLMOPT_MAX_HOST_CONNECTIONS` set to 5
 - `running_handles` (from `curl_multi_perform`): 8
 - `curl_multi_fdset()` shows only 4 fds:
```
$read_fd_set:  29, 30, 52, 56
$write_fd_set: -
$exc_fd_set: -
```

The upstream issue is here: https://github.com/jeroen/curl/issues/299

If this is expected behavior, or a silly test, feel free to close this issue :)

**Comment by bagder** [comment] 2023-06-20 11:57
> We assert repeatedly that read_fd_set + write_fd_set equals the smaller one of running_handles (as returned by curl_multi_perform)

This is a  assumption. But you might still be on to something.

Each transfer may use zero, one or several file descriptors for several purposes. All of them (might) get exposed via `curl_multi_fdset()`. It might use one or more during name resolving. It might use up to **4** for connecting (but **2** is more common). These descriptors can of course wait for read and or write during different states.

Still, if you expect to have 5 connections, it says 8 running and you only get 4 file descriptors that either means that you do multiplexing or that there's a bug somewhere.

Have you tried writing up an example in plain C that can reproduce?

**Comment by jeroen** [comment] 2023-06-20 12:39
> Have you tried writing up an example in plain C that can reproduce?

It's a bit of a complicated test, and also the problem happens only intermittently. But here is an attempt to port the test to C:

https://gist.github.com/jeroen/3089e67bfc858127ef7496b43e87b06b

**Comment by bagder** [comment] 2023-06-21 07:08
Thanks.

Using this I believe I can reproduce what you see. I am however not convinced this is a bug. Perhaps room for improvement.

First I applied this patch to your code to make more info outputs
~~~diff
--- issue11351.c~       2023-06-20 23:48:39.974226752 +0200
+++ issue11351.c        2023-06-21 08:52:00.094694311 +0200
@@ -56,6 +56,7 @@
     curl_multi_perform(multi_handle, &still_running);
     curl_multi_wait(multi_handle, NULL, 0, 1000, &numfds);
 
+    print_fd_count(multi_handle, still_running);
 
     /* See how the transfers went */
     CURLMsg *m = NULL;
~~~

Then when I run the code with current git master, it looks like this:
~~~sh
Using curl 8.2.0-DEV
Pending: 9. FD count: (read) 5, (write) 0, (exc) 0
Pending: 9. FD count: (read) 5, (write) 0, (exc) 0
Pending: 9. FD count: (read) 5, (write) 0, (exc) 0
Pending: 9. FD count: (read) 3, (write) 2, (exc) 0
Pending: 9. FD count: (read) 0, (write) 5, (exc) 0
Pending: 9. FD count: (read) 1, (write) 4, (exc) 0
Pending: 9. FD count: (read) 5, (write) 0, (exc) 0
Pending: 9. FD count: (read) 5, (write) 0, (exc) 0
Pending: 9. FD count: (read) 5, (write) 0, (exc) 0
Pending: 9. FD count: (read) 5, (write) 0, (exc) 0
Pending: 9. FD count: (read) 5, (write) 0, (exc) 0
Pending: 9. FD count: (read) 5, (write) 0, (exc) 0
Pending: 9. FD count: (read) 5, (write) 0, (exc) 0
Pending: 9. FD count: (read) 5, (write) 0, (exc) 0
Pending: 9. FD count: (read) 5, (write) 0, (exc) 0
Pending: 9. FD count: (read) 5, (write) 0, (exc) 0
Pending: 9. FD count: (read) 5, (write) 0, (exc) 0
Pending: 9. FD count: (read) 5, (write) 0, (exc) 0
Pending: 9. FD count: (read) 5, (write) 0, (exc) 0
Pending: 9. FD count: (read) 5, (write) 0, (exc) 0
Pending: 9. FD count: (read) 5, (write) 0, (exc) 0
Pending: 9. FD count: (read) 5, (write) 0, (exc) 0
Pending: 9. FD count: (read) 5, (write) 0, (exc) 0
Pending: 9. FD count: (read) 5, (write) 0, (exc) 0
Pending: 8. FD count: (read) 4, (write) 0, (exc) 0
Pending: 8. FD count: (read) 4, (write) 0, (exc) 0
Pending: 8. FD count: (read) 5, (write) 0, (exc) 0
Pending: 8. FD count: (read) 5, (write) 0, (exc) 0
Pending: 7. FD count: (read) 5, (write) 0, (exc) 0
Pending: 7. FD count: (read) 5, (write) 0, (exc) 0
Pending: 7. FD count: (read) 5, (write) 0, (exc) 0
Pending: 7. FD count: (read) 5, (write) 0, (exc) 0
Pending: 6. FD count: (read) 5, (write) 0, (exc) 0
Pending: 6. FD count: (read) 5, (write) 0, (exc) 0
Pending: 6. FD count: (read) 5, (write) 0, (exc) 0
Pending: 5. FD count: (read) 5, (write) 0, (exc) 0
Pending: 5. FD count: (read) 5, (write) 0, (exc) 0
Pending: 4. FD count: (read) 4, (write) 0, (exc) 0
Pending: 4. FD count: (read) 4, (write) 0, (exc) 0
Pending: 3. FD count: (read) 3, (write) 0, (exc) 0
Pending: 3. FD count: (read) 3, (write) 0, (exc) 0
Pending: 2. FD count: (read) 2, (write) 0, (exc) 0
Pending: 2. FD count: (read) 2, (write) 0, (exc) 0
Pending: 2. FD count: (read) 2, (write) 0, (exc) 0
Pending: 1. FD count: (read) 1, (write) 0, (exc) 0
Pending: 1. FD count: (read) 1, (write) 0, (exc) 0
Pending: 1. FD count: (read) 1, (write) 0, (exc) 0
Pending: 0. FD count: (read) 0, (write) 0, (exc) 0
Pending: 0. FD count: (read) 0, (write) 0, (exc) 0
~~~

It varies a little between runs.

The output shows that sure, it goes down to 4 read sockets when it goes down to 8 pending, but that's just temporary and it goes up to 5 while still remaining 8 pending. This tells me this seems to work but could possibly be improved so that it moves transfers out from PENDING faster.

**Comment by jeroen** [comment] 2023-06-21 12:23
The thing that changed in https://github.com/curl/curl/pull/10801 is that we sometimes get this first line, where all transfers have started, but somehow we still only have 4 connections. 

```
jeroen@Jeroens-MBP-2 Desktop % ./a.out
Using curl 8.1.2
Pending: 8. FD count: (read) 4, (write) 0, (exc) 0
Pending: 7. FD count: (read) 5, (write) 0, (exc) 0
Pending: 6. FD count: (read) 5, (write) 0, (exc) 0
...
```

Before https://github.com/curl/curl/pull/10801 this had never happened and we always got at least 5 fds in the first call. Again I am not sure if it hints at a bug of any kind, I can just remove the test, but it used to work before curl 8.0.0 :)

**Closed** 2023-06-21 12:54 UTC
Labels: libcurl API
