### ISSUE TITLE
Doc say seconds, but this is microseconds

### ISSUE THREAD

**Issue by Korsani** [curl/curl#6422] opened 2021-01-07 16:46 UTC
### I did this

curl -w '%{time_pretransfer}' -I www.free.fr
[...]
4064

And man page say this is seconds. Obviously not.

### I expected the following

0,004064
And man page say 'microseconds'

### curl/libcurl version

curl 7.74.0 (amd64-portbld-freebsd12.2) libcurl/7.74.0 LibreSSL/3.2.3 zlib/1.2.11 nghttp2/1.42.0
Release-Date: 2020-12-09
Protocols: file ftp ftps http https mqtt
Features: AsynchDNS HTTP2 HTTPS-proxy IPv6 Largefile libz SSL UnixSockets

### operating system

FreeBSD xxx 12.2-RELEASE-p1 FreeBSD 12.2-RELEASE-p1 GENERIC  amd64

**Comment by bagder** [comment] 2021-01-07 16:48
Duplicate of #6321

**Closed** 2021-01-10 14:46 UTC
Labels: cmdline tool
