### ISSUE TITLE
Shouldn't the progress callback be called between DNS resolution and connection?

### ISSUE THREAD

**Issue by nicolas-grekas** [curl/curl#4388] opened 2019-09-20 11:31 UTC
As far as I tested correctly, the progress callback is not called just after DNS resolution, before the connection to the remote server.

Would it make sense to add a call at this stage?

This would allow e.g checking the remote IP before connecting to it (and aborting the connection when needing).

**Comment by bagder** [comment] 2019-09-20 11:35
Checking the IP? But the progress callback doesn't tell you the IP address. If you want to prevent curl from connecting to a specific address shouldn't you rather use `CURLOPT_OPENSOCKETFUNCTION` ?

The progress callback should be called *at least* once per second so if there's ever chance of it not doing that, then we should fix it.

**Comment by nicolas-grekas** [comment] 2019-09-20 11:38
> Checking the IP?

I'm using curl from PHP: all I have is the `CURLOPT_PROGRESSFUNCTION`, and then I can use `curl_getinfo()` from within the callback to read the IP. It works, but it's a but late right now :)

**Comment by bagder** [comment] 2019-09-20 14:32
Ok, I understand. You then also assume that you'd get the IP even before it has connected. I'm hesitant to agree to both these new suggested promises. Especially since we already provide this data in the API. To me it seems more reasonable that PHP/CURL would adapt to using the libcurl API and thus expose this rather that we should change libcurl just so that PHP/CURL can remain unmodified...

**Comment by nicolas-grekas** [comment] 2019-09-20 14:51
The progress callback is called SO OFTEN that I was surprised it was not called there honestly :)
I understand your point... yet it would be way more convenient to have this in curl, as that would also allow propagating the change must faster to userland. Doing it in PHP would mean exposing `CURLOPT_OPENSOCKETFUNCTION`, which I'm not sure how it maps there + waiting for the new minor version. That's PHP 7.4, but it's in feature-freeze. Thus wait for PHP 8, which has no planned release date. Then, it'd mean we couldn't achieve the benefit of this before PHP libraries bump their minimum version to PHP 8.

I'm going to be old by then, while a progress-callback call in curl could be usable next month.

Thanks for considering :)

**Comment by bagder** [comment] 2019-09-21 14:28
As I see it, the problem isn't to add the callback getting called there. It is the fact that it won't help you - since you won't get the IP address *before* the connection is done and that we need to add this to the documented behavior and thus add tests for it.

**Comment by bagder** [comment] 2019-11-23 20:11
This is not a bug but a request for a change, and one I don't even understand. Closing this.

**Closed by bagder** 2019-11-23 20:11 UTC
Labels: enhancement, libcurl API
