### ISSUE TITLE
Unable to connect to unix socket of Linux's abstract namespace

### ISSUE THREAD

**Issue by typeless** [curl/curl#1061] opened 2016-10-09 09:21 UTC
### I did this

```
$ netstat -l 
[root@Foo:/]# netstat -l
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node Path
unix  2      [ ACC ]     STREAM     LISTENING       1014 @/tmp/test.sock

$ curl --unix-socket @/tmp/test.sock http:/api/version
```
### I expected the following

`0.0.1`
Instead, I got `curl: (7) Couldn't connect to server`
### curl/libcurl version

```
7.49.1
```

[curl -V output perhaps?]

```
curl 7.49.1 (arm-broadcom-linux-gnueabi) libcurl/7.49.1 zlib/1.2.8
Protocols: dict file ftp gopher http imap pop3 rtsp smtp telnet tftp
Features: IPv6 Largefile libz UnixSockets
```
### operating system

Linux 3.10.100 (ARCH=arm)

**Comment by bagder** [comment] 2016-10-09 22:18
The domain socket path is probably incorrectly specified to curl, as it is only shown with that `@` character in the netstat output. Maybe `-v` helps to figure that out.

Also, your specified URL doesn't look like a valid URL as it doesn't have two slashes after the `http:`.

**Comment by frenche** [comment] 2016-10-09 22:44
I think the '@' sign is just a way netstat chose to denote it is in abstract socket namespace, because they begin with a NULL character which cannot be displayed.
Technically, perhaps the curl tool could support the same notation (and change to NULL).

**Comment by frenche** [comment] 2016-10-09 23:12
After taking a closer look, I think libcurl option 'CURLOPT_UNIX_SOCKET_PATH' would also need some adjustments in order to work with abstract socket namespace, as otherwise it might consider the path parameter as an empty string.

Perhaps we can introduce a new 'CURLOPT_UNIX_ABSTRACT_SOCKET_PATH' which the app supplies without the null prefix, and the library adds it (and perhaps a companion --unix-abstract-socket flag for the curl tool would be more suitable than parsing the '@' sign).

**Comment by typeless** [comment] 2016-10-10 06:55
@bagder The URL is correct without the '@' symbol when the server does not listen on an abstract socket.

**Comment by bagder** [comment] 2016-10-10 07:08
> Perhaps we can introduce a new 'CURLOPT_UNIX_ABSTRACT_SOCKET_PATH`

We can do that, but we can also check for and parse a leading `@` character so that users can do exactly what @typeless did above. Or perhaps use an even more explicit markup that is less likely to ever occur in an actual file path.

This abstract path for unix domain sockets feature is Linux specific it seems.

**Comment by typeless** [comment] 2016-10-10 07:34
@bagder Yes, this is a Linux specific feature.

**Comment by frenche** [comment] 2016-10-10 23:43
I'm not sure how common is the 'netstat' way to denote abstract unix sockets ('@'), and as you mentioned, this might collide with an actual file name (admittedly, not likely). 
That's why I suggested the alternative tool option '--unix-abstract-socket' to match the suggested library option (which we could make only available on supporting platforms).

Meanwhile, I managed to reproduce this by using 'socat' tool to listen on a unix socket and to proxy the stream to a local TCP http server as below.

Regular unix domain socket:
socat UNIX-LISTEN:/tmp/foo.sock TCP:localhost:80

Abstract unix domain socket:
socat ABSTRACT-LISTEN:/tmp/foo.sock TCP:localhost:80

I've got curl to work with the abstract socket by making the changes at (draft): https://github.com/frenche/curl/commit/3e6f3f8fd113bcd11a59bdc22972eea70cd40847

**Comment by frenche** [comment] 2016-10-11 00:01
Hmm, actually, the 'strace' tool also uses the '@' notation for abstract socket.

**Comment by frenche** [comment] 2016-10-14 13:12
There is yet another problem to bear in mind.

The unix man page says that besides the first byte being a NULL to denote an abstract name, the NULL value has no special meaning in the reset of the name (and therefore the length must be specified).

This means that all the below examples are valid and distinct abstract names:
NULLa, NULLaNULL, NULLaNULLNULL, NULLaNULLb, NULLNULL

So to fully support abstract socket at the library level, we'll need the app to specify both buffer and len.
While for the curl tool, we might even need to encode the name in hex or base64.

HTH

**Comment by bagder** [comment] 2016-10-14 13:20
Anyone checked what netstat and strace show for abstract paths that contain zero bytes?

It might make sense to for example support URL-encoding with %00 for zeros rather than having the entire thing as hex/base64.

**Comment by frenche** [comment] 2016-10-14 18:15
For "\0/tmp/fo\0.sock" the strace tool gets it right:
bind(5, {sa_family=AF_UNIX, sun_path=@"/tmp/fo\0.sock"}, 16) = 0
But netstat only shows up to the second null (which doesn't work): @/tmp/fo

URL-encoded would indeed be simpler.

**Comment by bagder** [comment] 2016-10-18 06:22
@typeless, @frenche feel free to submit a pull request for this for when the feature window opens again after November 2.

**Comment by bagder** [comment] 2016-11-05 11:43
We can actually add an option named something like `CURLOPT_UNIX_SOCKET_PATH_ENCODED` and have that support a URL encoded path name and this should work fine to use an abstract name space path when prefixed with `%00`. Like `%00/tmp/test.sock` for the path in the original comment.

Alternatively we call it `CURLOPT_UNIX_ABSTRACT_SOCKET_PATH`, which also assumes URL encoding but always puts the initial zero byte in there so that `/tmp/test.sock` passed to this option would work.

**Comment by frenche** [comment] 2016-11-07 20:17
@bagder I like the first idea, though perhaps CURLOPT_UNIX_SOCKET_URL would be more descriptive.

I'm trying to implement it, but came across another issue with unix socket. It looks like we don't distinguish between unix sockets and regular ones when reusing a connection and might reuse incorrectly IMO. I've also looked at the initial commit introducing unix domain sockets (https://github.com/curl/curl/commit/970c22f970f0172e6a4c98ccc3176c740ddaa1c6).

So I've tested it with the 'socat' command above:
# socat UNIX-LISTEN:/tmp/foo.sock TCP:localhost:80
Then if I run:
# curl -v --unix-socket /tmp/foo.sock http://abc/ --next http://abc/
I can see that the unix connection is reused, same happens with libcurl if set CURLOPT_UNIX_SOCKET_PATH to null or call curl_easy_reset() just before reusing the easy handle (it reuses the unix connection).

I've made a patch for this problem, which fixes my libcurl tests but not the '--next' example.
I think though, this should be fixed in the '--next' logic to have it invoke curl_easy_reset (judging by their manual pages, this should be ok).
The path can be found at: https://github.com/frenche/curl/tree/unix_socket_reuse

Note, the fix is not complete yet as it lacks freeing of 'conn->unix_domain_socket' in the reuse_conn() call, but I'm thinking to refactor so that reuse_conn() would not bother with freeing stuff but instead call conn_free() right afterwards.

Thoughts?

**Comment by frenche** [comment] 2016-11-07 20:27
I think I found one more justification for the refactoring of reuse_conn() as suggested above.
The 'conn->oauth_bearer' is allocated in create_conn() before ConnectionExists(), but it is only freed in conn_free(), so it may leak if we decide to reuse another connection instead of the 'needle'.

**Comment by frenche** [comment] 2016-11-09 15:48
See PR above, I left out the reuse_conn() refactoring as it isn't required for now.

Otherwise, I am also wondering why we disable proxy in when unix socket is specified.
I could think of a use-case where a proxy listens on a unix socket serving local processes.

**Comment by Lekensteyn** [comment] 2016-11-09 21:26
For the `curl` tool, I think that making it handle `curl --unix-socket @abstract_path_here` as an abstract Unix socket is okay. You already have `-F field=@file.txt` for example where some values are special.

Percent-escapes are a bit unnatural for a Unix domain socket. One option is to overload the curl option too (like the tool, subject to the NULL limitation), the alternative is to add a new option (but with ugly encoding semantics).

**Comment by frenche** [comment] 2016-11-09 22:23
@Lekensteyn, I think url encoding will be fine, along with option names like CURLOPT_UNIX_SOCKET_URL and '--unix-socket-url' so the name will imply the usage. This will allow for better granularity.

Internally though, we can save them in one string, of which we always keep the length.

**Comment by frenche** [comment] 2016-11-10 17:48
> I've made a patch for this problem, which fixes my libcurl tests but not the '--next' example. I think though, this should be fixed in the '--next' logic to have it invoke curl_easy_reset (judging by their manual pages, this should be ok).

Actually I'm not so sure about that - should we expect from '--next' to reset the easy handle in between operations?
It looks like it does reset some flags, e.g. the second command below fails on certificate verification (no -k):
curl -v -k https://localhost/ --next https://localhost/

I've made a tentative patch to reset the easy handle between operations (passes make test):

```diff
diff --git a/src/tool_operate.c b/src/tool_operate.c
index deae877..dbfc71e 100644
--- a/src/tool_operate.c
+++ b/src/tool_operate.c
@@ -1904,6 +1904,9 @@ CURLcode operate(struct GlobalConfig *config, int argc, argv_item_t argv[])
           result = operate_do(config, config->current);

           config->current = config->current->next;
+
+          if(config->current && config->current->easy)
+            curl_easy_reset(config->current->easy);
         }

 #ifndef CURL_DISABLE_LIBCURL_OPTION
```

Thoughts?

Thanks!

**Comment by frenche** [comment] 2017-01-08 23:52
Just opened #1197 to add support for abstract unix domain sockets, reviews are welcome :)
I opted to simplify it and only support normal abstract sockets (not ones embedding zero bytes).

@bagder btw, in future Linux kernel versions, abstract unix path that contains zero bytes will be shown correctly by netstat and other tools :)
See: https://github.com/torvalds/linux/commit/e7947ea770d0de434d38a0f823e660d3fd4bebb5

**Closed** 2017-01-13 15:29 UTC
Labels: connecting & proxies, enhancement, KNOWN_BUGS material
