### ISSUE TITLE
"unexpected eof while reading" with openssl-1.1.1e

### ISSUE THREAD

**Issue by hasso** [curl/curl#5138] opened 2020-03-23 07:35 UTC
### I did this

```
$ curl https://www.presseportal.de 1>NUL
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  114k    0  114k    0     0   129k      0 --:--:-- --:--:-- --:--:--  129k
curl: (56) OpenSSL SSL_read: error:14095126:SSL routines:ssl3_read_n:unexpected eof while reading, errno 0
$
```

### I expected the following

I expected it to succeed without an error. Downgrading openssl to 1.1.1d fixes the problem. My wild guess is that it's related to #4982 and this entry in the openssl-1.1.1e CHANGES file:
```
  *) Properly detect EOF while reading in libssl. Previously if we hit an EOF
     while reading in libssl then we would report an error back to the
     application (SSL_ERROR_SYSCALL) but errno would be 0. We now add
     an error to the stack (which means we instead return SSL_ERROR_SSL) and
     therefore give a hint as to what went wrong.
     [Matt Caswell]
```

### curl/libcurl version
```
$ curl -V
curl 7.69.1 (x86_64-pc-linux-gnu) libcurl/7.69.1 OpenSSL/1.1.1e zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2020-03-11
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz NTLM SPNEGO SSL TLS-SRP UnixSockets
```

### operating system
```
$ uname -a
Linux builder 4.19.111 #1 SMP Wed Mar 18 08:18:00 -00 2020 x86_64 Intel(R) Xeon(R) CPU E5-2637 v2 @ 3.50GHz GenuineIntel GNU/Linux
```

**Comment by bagder** [comment] 2020-03-23 08:43
I can't reproduce. I tried with 7.68.0 and 7.70.0-DEV, both using OpenSSL 1.1.1e. Both get this from this URL:

    curl: (35) error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type

**Comment by bagder** [comment] 2020-03-23 11:52
(Reproducible with Debian's OpenSSL 1.1.1e with `curl -v https://www.presseportal.de --ciphers DEFAULT@SECLEVEL=1`)

This is not #4982. This is OpenSSL returning an error for a case it previously didn't return error for. I don't think this is a curl problem, this is a bad server.

**Comment by hasso** [comment] 2020-03-23 12:47
Yes, it's a probably a bad server that closes a connection abruptly.

**Comment by bagder** [comment] 2020-03-24 10:44
> errors are back in different form.

Again: that is not the problem we fixed in #4623. 4623 fixed a *regression* that made it show an error when there was no error.

**Comment by bagder** [comment] 2020-03-24 10:45
Also, even if it was, are you suggesting we should hide the server error?

**Comment by jay** [comment] 2020-03-25 06:44
I can also reproduce. OpenSSL 1.1.1d works fine but 1.1.1e does not. The reporter's analysis is likely correct. We allow for this, as seen in 78cef06, but the recent change in openssl/openssl#10882  mean it is now a different error. I kind of don't want to work around this, but OTOH I suspect we will have more reports once more people upgrade.

**Comment by bagder** [comment] 2020-03-25 07:13
> I suspect we will have more reports once more people upgrade

Possibly, yes. But hopefully curl won't be alone in this and more people will actually try to fix the server ends.

We should perhaps be prepared with an actual plan. Should we consider an option that lets users ignore these errors?

**Comment by jay** [comment] 2020-03-25 07:34
> We should perhaps be prepared with an action plan. Should we consider an option that lets users ignore these errors?

I'd rather wait and see if we get more reports. I'm not against an option, I'd just prefer to leave allowing truncation as the default in 1.1.1x if it's still possible and it comes to that.

**Comment by bagder** [comment] 2020-03-25 07:47
Agreed!

**Comment by bagder** [comment] 2020-03-25 21:53
It seems the OpenSSL team plans to revert that change and ship a 1.1.1f soon: https://github.com/openssl/openssl/pull/11400 - but keep it for version 3.

**Comment by jay** [comment] 2020-03-25 22:04
Works for me, tested ok.

**Comment by bagder** [comment] 2020-03-29 20:57
Since the OpenSSL pretty must view this as a bug of theirs and will ship a new release soon with this change reverted, I'm going to close this curl issue. It sounds as if this change is still on target to ship enabled in OpenSSL v3, so I believe that we might have reason to revisit this topic later this year if this sticks...

**Closed by bagder** 2020-03-29 20:57 UTC
Labels: SSL/TLS, not-a-bug

**Comment by Zenju** [comment] 2021-09-29 08:14
The "unexpected eof while reading" is back in OpenSSL 3, as expected. However, OpenSSL 3 added [ SSL_OP_IGNORE_UNEXPECTED_EOF](https://www.openssl.org/docs/man3.0/man3/SSL_CTX_set_options.html#SSL_OP_IGNORE_UNEXPECTED_EOF)
Maybe this should be added to [ctx_options](https://github.com/curl/curl/blob/2b7e56aab353188e7919cd941150abb77ffc4d97/lib/vtls/openssl.c#L2726) to continue with the old EOF handling?

Or just embrace the new one and have curl check instead:
`if (SSL_get_error() == SSL_ERROR_SSL && ERR_GET_REASON(ec) == SSL_R_UNEXPECTED_EOF_WHILE_READING)`

**Comment by bagder** [comment] 2021-09-29 08:17
Can you please submit this as a new issue or pull-request? Comments on old closed issues do not get much attention.
