### ISSUE TITLE
curl/8.6.0 version `time_starttransfer` is always 0.000000

### ISSUE THREAD

**Issue by sbwml** [curl/curl#13142] opened 2024-03-17 19:37 UTC
### I did this

curl 8.6.0:
`curl --connect-timeout 3 -o /dev/null -I -sk -w "%{http_code}:%{time_starttransfer}" http://www.google.com/generate_204`
204:0.000000

curl 8.5.0:
`curl --connect-timeout 3 -o /dev/null -I -sk -w "%{http_code}:%{time_starttransfer}" http://www.google.com/generate_204`
204:0.021347

---------

Since upgrading to version 8.6.0, I have never been able to get the time taken by `time_starttransfer` in this way. There is no problem with curl/8.5.0 and previous versions.

Is this expected behavior? If so, I hope someone can tell me which commit started making such changes, and I wish I revert that commit when building.

### curl/libcurl version

curl 8.6.0

### operating system

```
Linux OpenWrt 6.6.22 #0 SMP PREEMPT_DYNAMIC Sun Mar 17 12:40:16 2024 aarch64 GNU/Linux

Linux localhost 6.6.22-1.el7.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Mar 15 23:31:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Linux redhat 5.14.0-284.11.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May 9 17:09:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jay** [comment] 2024-03-17 21:48
Duplicate of #13125.

Fixed by #13052 c426277b

**Closed by jay** 2024-03-17 21:48 UTC
Labels: duplicate
