### ISSUE TITLE
Windows 10, VS 2019 build broken

### ISSUE THREAD

**Issue by JW-Schuetz** [curl/curl#5329] opened 2020-05-03 09:02 UTC
### I did this
"nmake /f Makefile.vc mode=static" in the winbuild directory with the VS2019 console

### I expected the following
that the build finished without errors

### curl/libcurl version
actual git content of master-branch

[curl -V output]
-

### operating system
Windows 10 x64

[console-output.txt](https://github.com/curl/curl/files/4569868/console-output.txt)

**Comment by JW-Schuetz** [comment] 2020-05-03 09:13
... in the past this worked fine!

**Comment by JW-Schuetz** [comment] 2020-05-03 09:17
I accidental closed this issue.

**Comment by JWS1954** [comment] 2020-05-03 18:30
... but it is still solved. Thanks for re-open.

**Comment by mback2k** [comment] 2020-05-03 18:30
Duplicate of #5331.

**Closed** 2020-05-03 18:30 UTC
