### ISSUE TITLE
Memory leaks on vcpkg when compiling statically

### ISSUE THREAD

**Issue by angelmixu** [curl/curl#2323] opened 2018-02-22 08:46 UTC
Hi! 

I was using curl from vcpkg and found a memory leak, I created an issue on vcpkg issues and was redirected here ( https://github.com/Microsoft/vcpkg/issues/2851 )

> We had some leaks on our application and after using Visual Leak Detector, Deleaker, and the integrated profiler or VS2017 we found that there are leaks with minimum code.
> 
> I'm using this triplet for compiling curl:
> 
> 	set(VCPKG_TARGET_ARCHITECTURE x86)
> 	set(VCPKG_CRT_LINKAGE dynamic)
> 	set(VCPKG_LIBRARY_LINKAGE static)
> 
> And this small application for testing it:
> 
> 		#include <curl/curl.h>
> 
> 		int main()
> 		{
> 			bool testGlobal = false;
> 
> 			if (testGlobal)
> 			{
> 				curl_global_init(CURL_GLOBAL_ALL);
> 				curl_global_cleanup();
> 			}
> 			else
> 			{
> 				CURL* curl = curl_easy_init();
> 				curl_easy_cleanup(curl);
> 			}
> 
> 			return 0;
> 		}
> 
> There are leaks in both cases, in the global one there are like 144 leaks and on easy there are 3641 leaks.
> Deleaker points to this file:
> 
> 		mem.c, line 79 (c:\src\vcpkg\buildtrees\openssl\win32-dbg\openssl-1.0.2n\crypto\mem.c)	0x02bc8d00	326	Heap memory	testCurl.exe	C:\testCurl\testCurl\Debug\testCurl.exe	15648	11140	21/02/2018 11:41:55	
> (there are more leaks listed like this one)
> 
> And VS2017 profiler shows this on the easy case:
> ![curl_leak](https://user-images.githubusercontent.com/2285977/36476001-d7df8408-16fc-11e8-966d-1741e86a4769.png)
> 
> I'm statically linking with these libraries:
> 
> 		libcurl.lib; libssh2.lib; libeay32.lib; ssleay32.lib; crypt32.lib; Ws2_32.lib; Wldap32.lib;
> 
> The funny thing though, is that if I use the default x86 triplet, generating DLL's, there won't appear any memory leak.
> 
> I've taken a look at curl and openssl forums/lists/etc. and found nothing clear as to how to fix this leak.
> Do you have any idea?
> 

I'm using the versions in vcpkg as today date, which are:

libcurl: 7.58
libssh2: 1.8.0
openssl: 1.0.2n
zlib: 1.2.11

I'm using Windows 10 and Visual Studio 2017.

If you need more info or testing I can provide it.
Thanks!

**Comment by bagder** [comment] 2018-02-22 09:19
> if I use the default x86 triplet, generating DLL's, there won't appear any memory leak.

That sounds very fishy to me. libcurl will of course do the exact same function calls no matter how you link it. And so will OpenSSL (which you identify as the one that does the memory allocation call that leaks).

Unfortunately, `crypto/mem.c:79` is not saying us much since that since to be the general malloc for OpenSSL's crypto parts, so we can't easily deduce which OpenSSL call that leaked this memory.

I presume the amount of leaked memory is at least pretty static and won't grow?

(Chasing memory leaks due to something about OpenSSL is a never-ending game and you can find numerous attempts and back and forths through-out our history.)

**Comment by angelmixu** [comment] 2018-02-22 10:25
Yeah, I was looking for lots of issues regarding memory leaks from years ago! 

> I presume the amount of leaked memory is at least pretty static and won't grow?
Yes, I ran the test some times and always shows the same amount of memory and allocations.

May I test something? Do you need anything?

**Comment by bagder** [comment] 2018-02-22 12:41
> May I test something? Do you need anything?

I can't reproduce this. curl with openssl 1.0.2n leaks nothing on my attempts on Linux. Also, the fact that you get different results based on how you *link* the libraries make me not fully trust your results. I fear your tool is playing us.

You can of course continue and try to remove OpenSSL-calls in Curl_ossl_init() to figure out which one that leaks, and make sure that the corresponding cleanup-function is called. And if it is, the bug is in OpenSSL and if the cleanup function call isn't called, then how on earth is not leaking for everyone else? And if it is called, then it is an OpenSSL problem (or again, your tool).

**Comment by angelmixu** [comment] 2018-02-23 11:59
I've tested a mix of static and dynamic libraries.
If I use all static libraries but with dynamic libeay32.lib/dll there's no memory leak.
If I change that libeay32.lib with an static one, then... all above mentioned leaks start to show.

Also I haved tested to use static libeay32*.lib compiled libraries from http://slproweb.com/products/Win32OpenSSL.html and the leak appears.
If using dynamic libraries from that web, there are no leaks.

I'm going to talk to the OpenSSL guys.
Thanks!

**Comment by jay** [comment] 2018-02-23 22:00
We don't call OpenSSL CRYTPO_cleanup_all_ex_data because multiple calls can cause a crash in 1.0.2, see curl de71e68. So there is some leakage at termination because of that. See if the leaks go away if you call it in your program before terminating

/cc @richsalz

**Comment by angelmixu** [comment] 2018-02-26 08:33
```
#include <curl/curl.h>
#include <openssl/ssl.h>

FILE _iob[] = { *stdin, *stdout, *stderr };

extern "C" FILE * __cdecl __iob_func(void)
{
	return _iob;
}

int main()
{
	bool testGlobal = true; 

	if (testGlobal)
	{
		curl_global_init(CURL_GLOBAL_ALL);
		curl_global_cleanup();
	}
	else
	{
		CURL* curl = curl_easy_init();
		curl_easy_cleanup(curl);
	}
	CRYPTO_cleanup_all_ex_data();

    return 0;
}
```

With this test application I get 108 leaks on global case and 3635 on the easy one.
There are fewer leaks, but still there are leaks :/

**Comment by gvanem** [comment] 2018-02-26 10:47
I guess this *Deleaker* is to blame. I changed your program into this:
```c
#ifdef _DEBUG
  #include <crtdbg.h>
  static _CrtMemState last_state;
#else
  #error "Compile this with '-MDd' or '-MTd'"
#endif

#include <curl/curl.h>
#include <openssl/ssl.h>

FILE _iob[] = { *stdin, *stdout, *stderr };

extern "C" FILE * __cdecl __iob_func(void)
{
  return _iob;
}

void crtdbug_init (void)
{
  _CrtSetDbgFlag (_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF | _CRTDBG_DELAY_FREE_MEM_DF |
                  _CrtSetDbgFlag(_CRTDBG_REPORT_FLAG));
  _CrtSetReportFile (_CRT_WARN, _CRTDBG_FILE_STDERR);
  _CrtSetReportMode (_CRT_WARN, _CRTDBG_MODE_FILE);
  _CrtMemCheckpoint (&last_state);
}

void crtdbug_exit (void)
{
  _CrtMemDumpStatistics (&last_state);
  _CrtMemDumpAllObjectsSince (&last_state);
}

int main (int argc, const char **argv)
{
  bool testGlobal = false;

  if (argc == 2 && !stricmp(argv[1],"testGlobal"))
     testGlobal = true;

  crtdbug_init();

  if (testGlobal)
  {
    curl_global_init(CURL_GLOBAL_ALL);
    curl_global_cleanup();
  }
  else
  {
    CURL* curl = curl_easy_init();
    curl_easy_cleanup(curl);
  }
  CRYPTO_cleanup_all_ex_data();

  crtdbug_exit();
  return 0;
}
```
That reported no leaks at all. Only this:
```
0 bytes in 0 Free Blocks.
0 bytes in 0 Normal Blocks.
34561 bytes in 392 CRT Blocks.
0 bytes in 0 Ignore Blocks.
0 bytes in 0 Client Blocks.
Largest number used: 57410 bytes.
Total allocations: 64809 bytes.
Dumping objects ->
Object dump complete.
```

*PS*. Why are you messing with the CRT's ` _iob[]`? Looks very suspicious.

**Comment by angelmixu** [comment] 2018-02-26 11:23
The _iob[] stuff was for compiling with some binaries that didn't have those symbols.

I've tested your code, and it shows lots of leaks too:

> 0 bytes in 0 Free Blocks.
> 0 bytes in 0 Normal Blocks.
> 10699 bytes in 59 CRT Blocks.
> 0 bytes in 0 Ignore Blocks.
> 0 bytes in 0 Client Blocks.
> Largest number used: 10831 bytes.
> Total allocations: 18279 bytes.
> Dumping objects ->
> {4688} normal block at 0x03625FF0, 12 bytes long.
>  Data: <  a     /   > D8 E8 61 03 00 00 00 00 2F 03 00 00
> {4687} normal block at 0x0361E898, 16 bytes long.
>  Data: <  b             > E8 0A 62 03 00 00 00 00 00 00 00 00 00 00 00 00
> {4686} normal block at 0x0361E7D8, 20 bytes long.
> [plus a lot more]

BTW, I'm using VS2017 latest version, Windows 10, using debug configuration and x86 platform.
As suggested in OpenSSL bug report, I compiled from sources the library, and the leaks still are there.

I have attached the VS2017 solution, there are two configurations of importance: 

- **Debug_Static_OSSLDynamic** is using vcpkg's static libraries, but with only OSSL Dynamic ones, all put into a subdir
- **Debug_OSSL_OwnCompiled_Static is using vckpg's static libraries, but using statically compiled OSSL from sources.

The other two configurations are for using static or dynamic libraries from vckpg source tree.
[testCurl.zip](https://github.com/curl/curl/files/1758330/testCurl.zip)

**Comment by gvanem** [comment] 2018-02-26 11:45
> Dumping objects ->
> {4688} normal block at 0x03625FF0, 12 bytes long.

This was better, but not very detailed. Change the project so `_CrtMemDumpAllObjectsSince()` can report filenames and line-numbers. Not sure how, but I guess you'll have to rebuild *everything* with 
`-MDd -D_CRTDBG_MAP_ALLOC`.

Must be something with the way you build all of this.

**Comment by angelmixu** [comment] 2018-02-26 12:44
In nt.mak from OpenSSL win32 build I changed CFLAG's removing /MT, adding /MDd -MDd -D_CRTDBG_MAP_ALLOC
Rebuilt OpenSSL in the same way as before, and added _CRTDBG_MAP_ALLOC to the preprocessor line of VS2017 project configuration.

Still the same :(
```
0 bytes in 0 Free Blocks.
0 bytes in 0 Normal Blocks.
10699 bytes in 59 CRT Blocks.
0 bytes in 0 Ignore Blocks.
0 bytes in 0 Client Blocks.
Largest number used: 10831 bytes.
Total allocations: 18279 bytes.
Dumping objects ->
{4688} normal block at 0x03446150, 12 bytes long.
 Data: <  C     /   > B0 F8 43 03 00 00 00 00 2F 03 00 00
{4687} normal block at 0x0343F2B0, 16 bytes long.
 Data: <  D             > 00 17 44 03 00 00 00 00 00 00 00 00 00 00 00 00
{4686} normal block at 0x0343F7F0, 20 bytes long.
 Data: <      C         > 01 00 00 00 B0 F2 43 03 00 00 00 00 04 00 00 00
{4685} normal block at 0x0343F8B0, 16 bytes long.
 Data: </     C         > 2F 03 00 00 F0 F7 43 03 00 00 00 00 00 00 00 00
{4684} normal block at 0x03445E08, 12 bytes long.
 Data: <  C     +   > B0 F6 43 03 00 00 00 00 2B 03 00 00
{4683} normal block at 0x0343F770, 16 bytes long.
[lots more]
```

**Comment by gvanem** [comment] 2018-02-26 14:18
Still not very useful w/o file and line-numbers. Try adding a `-D _CRTDBG_MAP_ALLOC -FIcrtdbg.h` 
to the `CFLAGS` and rebuild everything.

**Comment by angelmixu** [comment] 2018-02-26 14:28
There's no more info :/

```
0 bytes in 0 Free Blocks.
0 bytes in 0 Normal Blocks.
10699 bytes in 59 CRT Blocks.
0 bytes in 0 Ignore Blocks.
0 bytes in 0 Client Blocks.
Largest number used: 10831 bytes.
Total allocations: 18279 bytes.
Dumping objects ->
{4688} normal block at 0x00D97BC8, 12 bytes long.
 Data: <        /   > 10 08 D9 00 00 00 00 00 2F 03 00 00
{4687} normal block at 0x00D90490, 16 bytes long.
 Data: <                > 00 17 D9 00 00 00 00 00 00 00 00 00 00 00 00 00
{4686} normal block at 0x00D90050, 20 bytes long.
 Data: <                > 01 00 00 00 90 04 D9 00 00 00 00 00 04 00 00 00
{4685} normal block at 0x00D90810, 16 bytes long.
 Data: </   P           > 2F 03 00 00 50 00 D9 00 00 00 00 00 00 00 00 00
{4684} normal block at 0x00D98098, 12 bytes long.
 Data: <        +   > D0 03 D9 00 00 00 00 00 2B 03 00 00
{4683} normal block at 0x00D90310, 16 bytes long.
[bunch more]
```

**Comment by jay** [comment] 2018-02-28 08:10
[_CRTDBG_MAP_ALLOC](https://msdn.microsoft.com/en-us/library/x98tx3cf.aspx#Anchor_1) doesn't work in libcurl because the memory overrides in crtdbg.h are themselves overridden by libcurl's [curl_memory.h](https://github.com/curl/curl/blob/master/lib/curl_memory.h), which is necessary because libcurl allows the user to override the heap functions via [curl_global_init_mem](https://curl.haxx.se/libcurl/c/curl_global_init_mem.html). You could as a complete hack define HEADER_CURL_MEMORY_H to get around that and then you'd see the source and line numbers in the dump. Instead though I would suggest recording the stack for each allocation; see [here](https://www.youtube.com/watch?v=HUZW8m_3XvE), [here](http://blogs.microsoft.co.il/sasha/2014/12/01/native-memory-leak-diagnostics-visual-studio-2015/) and [here](http://www.dorodnic.com/blog/2014/03/08/dont-fear-the-memory-leak/).

**Comment by angelmixu** [comment] 2018-02-28 11:52
Defining the header on my project didn't show any source and line numbers, so I recompiled OpenSSL in debug mode, and added a print of the stack trace for each allocation in the function that was pointed where leaks started:

```

	void* allocated_memory = malloc_func(num);

	printf("===============================================================\n");
	printf("Allocated memory: %ld bytes at %p\n", num, allocated_memory);

	unsigned int   i;
	void         * stack[100];
	unsigned short frames;
	SYMBOL_INFO  * symbol;
	HANDLE         process;

	process = GetCurrentProcess();

	SymInitialize(process, NULL, TRUE);

	frames = CaptureStackBackTrace(0, 100, stack, NULL);
	symbol = (SYMBOL_INFO *)calloc(sizeof(SYMBOL_INFO) + 256 * sizeof(char), 1);
	symbol->MaxNameLen = 255;
	symbol->SizeOfStruct = sizeof(SYMBOL_INFO);
	IMAGEHLP_LINE *imgline = (IMAGEHLP_LINE *)malloc(sizeof(IMAGEHLP_LINE));
	imgline->SizeOfStruct = sizeof(IMAGEHLP_LINE);


	for (i = 0; i < frames; i++)
	{
		SymFromAddr(process, (DWORD64)(stack[i]), 0, symbol);
		DWORD dwDisplacement;
		SymGetLineFromAddr(process, (DWORD)(stack[i]), &dwDisplacement, imgline);

		printf("%i: %s : %s - 0x%0llX (%p)\n", frames - i - 1, symbol->Name, imgline->FileName, symbol->Address, (void*)symbol->Address);
	}

	free(symbol);
	printf("===============================================================\n\n");

    return allocated_memory;
}
``` 

So, I printed the output to a file and it's the one attached.
As you can see on the file of leaks, the crtDebug methods don't output any source line or name, so I take the address of the leak, and search above for the stack trace for when it was allocated.

[leaks.zip](https://github.com/curl/curl/files/1766921/leaks.zip)

Here are a couple of the stacktraces that looks like there's a leak, there are a lot more.

```
> ===============================================================
> Allocated memory: 12 bytes at 071352E8
> 22: default_malloc_ex : c:\code\openssl-1.0.2n\crypto\mem.c - 0x1435600 (01435600)
> 21: CRYPTO_malloc : c:\code\openssl-1.0.2n\crypto\mem.c - 0x1435AB0 (01435AB0)
> 20: lh_insert : c:\code\openssl-1.0.2n\crypto\lhash\lhash.c - 0x1463B40 (01463B40)
> 19: int_err_set_item : c:\code\openssl-1.0.2n\crypto\err\err.c - 0x1448E00 (01448E00)
> 18: err_load_strings : c:\code\openssl-1.0.2n\crypto\err\err.c - 0x144A4D0 (0144A4D0)
> 17: ERR_load_strings : c:\code\openssl-1.0.2n\crypto\err\err.c - 0x1449BE0 (01449BE0)
> 16: ERR_load_CAPI_strings : c:\code\openssl-1.0.2n\engines\e_capi_err.c - 0x14A3450 (014A3450)
> 15: bind_capi : c:\code\openssl-1.0.2n\engines\e_capi.c - 0x14A34F0 (014A34F0)
> 14: engine_capi : c:\code\openssl-1.0.2n\engines\e_capi.c - 0x14A5810 (014A5810)
> 13: ENGINE_load_capi : c:\code\openssl-1.0.2n\engines\e_capi.c - 0x14A33D0 (014A33D0)
> 12: ENGINE_load_builtin_engines : c:\code\openssl-1.0.2n\crypto\engine\eng_all.c - 0x1454F00 (01454F00)
> 11: libssh2_init : c:\src\vcpkg\buildtrees\libssh2\src\libssh2-1.8.0\src\global.c - 0x140E860 (0140E860)
> 10: global_init : c:\src\vcpkg\buildtrees\curl\src\curl-curl-7_58_0\lib\easy.c - 0x13904E0 (013904E0)
> 9: curl_global_init : c:\src\vcpkg\buildtrees\curl\src\curl-curl-7_58_0\lib\easy.c - 0x138F860 (0138F860)
> 8: curl_easy_init : c:\src\vcpkg\buildtrees\curl\src\curl-curl-7_58_0\lib\easy.c - 0x138FBA0 (0138FBA0)
> 7: main : c:\testcurl\testcurl\testcurl\testcurl.cpp - 0x138F7C0 (0138F7C0)
> 6: invoke_main : f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl - 0x1562140 (01562140)
> 5: __scrt_common_main_seh : f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl - 0x1561F00 (01561F00)
> 4: __scrt_common_main : f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl - 0x1561EF0 (01561EF0)
> 3: mainCRTStartup : f:\dd\vctools\crt\vcstartup\src\startup\exe_main.cpp - 0x15621C0 (015621C0)
> 2: BaseThreadInitThunk : f:\dd\vctools\crt\vcstartup\src\startup\exe_main.cpp - 0x75B68630 (75B68630)
> 1: RtlGetAppContainerNamedObjectPath : f:\dd\vctools\crt\vcstartup\src\startup\exe_main.cpp - 0x77544940 (77544940)
> 0: RtlGetAppContainerNamedObjectPath : f:\dd\vctools\crt\vcstartup\src\startup\exe_main.cpp - 0x77544940 (77544940)
> 
> ===============================================================
```


```
===============================================================
Allocated memory: 16 bytes at 070CDA20
20: default_malloc_ex : c:\code\openssl-1.0.2n\crypto\mem.c - 0x1435600 (01435600)
19: CRYPTO_malloc : c:\code\openssl-1.0.2n\crypto\mem.c - 0x1435AB0 (01435AB0)
18: sk_new : c:\code\openssl-1.0.2n\crypto\stack\stack.c - 0x1435240 (01435240)
17: sk_new_null : c:\code\openssl-1.0.2n\crypto\stack\stack.c - 0x1435310 (01435310)
16: engine_table_register : c:\code\openssl-1.0.2n\crypto\engine\eng_table.c - 0x14C5B60 (014C5B60)
15: ENGINE_register_DSA : c:\code\openssl-1.0.2n\crypto\engine\tb_dsa.c - 0x1484720 (01484720)
14: ENGINE_register_complete : c:\code\openssl-1.0.2n\crypto\engine\eng_fat.c - 0x144C7B0 (0144C7B0)
13: ENGINE_register_all_complete : c:\code\openssl-1.0.2n\crypto\engine\eng_fat.c - 0x144C760 (0144C760)
12: ENGINE_load_builtin_engines : c:\code\openssl-1.0.2n\crypto\engine\eng_all.c - 0x1454F00 (01454F00)
11: libssh2_init : c:\src\vcpkg\buildtrees\libssh2\src\libssh2-1.8.0\src\global.c - 0x140E860 (0140E860)
10: global_init : c:\src\vcpkg\buildtrees\curl\src\curl-curl-7_58_0\lib\easy.c - 0x13904E0 (013904E0)
9: curl_global_init : c:\src\vcpkg\buildtrees\curl\src\curl-curl-7_58_0\lib\easy.c - 0x138F860 (0138F860)
8: curl_easy_init : c:\src\vcpkg\buildtrees\curl\src\curl-curl-7_58_0\lib\easy.c - 0x138FBA0 (0138FBA0)
7: main : c:\testcurl\testcurl\testcurl\testcurl.cpp - 0x138F7C0 (0138F7C0)
6: invoke_main : f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl - 0x1562140 (01562140)
5: __scrt_common_main_seh : f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl - 0x1561F00 (01561F00)
4: __scrt_common_main : f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl - 0x1561EF0 (01561EF0)
3: mainCRTStartup : f:\dd\vctools\crt\vcstartup\src\startup\exe_main.cpp - 0x15621C0 (015621C0)
2: BaseThreadInitThunk : f:\dd\vctools\crt\vcstartup\src\startup\exe_main.cpp - 0x75B68630 (75B68630)
1: RtlGetAppContainerNamedObjectPath : f:\dd\vctools\crt\vcstartup\src\startup\exe_main.cpp - 0x77544940 (77544940)
0: RtlGetAppContainerNamedObjectPath : f:\dd\vctools\crt\vcstartup\src\startup\exe_main.cpp - 0x77544940 (77544940)
===============================================================

```

**Comment by gvanem** [comment] 2018-03-23 11:39
Still an issue for you? 

You could try building OpenSSL with `enable-crypto-mdebug`. Or make sure that 
`-DOPENSSL_NO_CRYPTO_MDEBUG=1` is *not* in your `CFLAGS`. There is some mem-leak report functions in OpenSSL too. You enable that calling `CRYPTO_set_mem_debug(1)` early in `main()` and `CRYPTO_mem_leaks()` prior to `exit()`. 

Refer `man OpenSSL_malloc` or `pod2text doc\man3\OPENSSL_malloc.pod`.

**Comment by angelmixu** [comment] 2018-03-26 11:20
Hi @gvanem thanks for the suggestion!

I configured and compiled OpenSSL 1.0.2n like this:

> perl Configure VC-WIN32 --prefix=c:\some\openssl\dir enable-crypto-mdebug
> ms\do_nasm
> nmake -f ms\nt.mak

As CRYPTO_set_mem_debug function was not on the sources I have, I looked a little on the code and changed my test like this:

```

#include "stdafx.h"
#ifdef _DEBUG
#include <crtdbg.h>
static _CrtMemState last_state;
#else
#error "Compile this with '-MDd' or '-MTd'"
#endif

#include <curl/curl.h>
#include <openssl/ssl.h>
#include <openssl/engine.h>

void crtdbug_init(void)
{
	_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF | _CRTDBG_DELAY_FREE_MEM_DF |
		_CrtSetDbgFlag(_CRTDBG_REPORT_FLAG));
	_CrtSetReportFile(_CRT_WARN, _CRTDBG_FILE_STDERR);
	_CrtSetReportMode(_CRT_WARN, _CRTDBG_MODE_FILE);
	_CrtMemCheckpoint(&last_state);
}

void crtdbug_exit(void)
{
	_CrtMemDumpStatistics(&last_state);
	_CrtMemDumpAllObjectsSince(&last_state);
}

int main(int argc, const char **argv)
{
	bool testGlobal = false;
	crtdbug_init();

	CRYPTO_malloc_debug_init();
	CRYPTO_set_mem_debug_options(V_CRYPTO_MDEBUG_ALL);
	CRYPTO_mem_ctrl(CRYPTO_MEM_CHECK_ON);

	ERR_load_crypto_strings();


	if (testGlobal)
	{
		curl_global_init(CURL_GLOBAL_ALL);
		curl_global_cleanup();
	}
	else
	{
		CURL* curl = curl_easy_init();
		curl_easy_cleanup(curl);
	}
	
	ENGINE_cleanup();
	
	EVP_cleanup();
	CRYPTO_cleanup_all_ex_data();
	ERR_remove_thread_state(NULL);
	ERR_free_strings();
	CRYPTO_mem_leaks_fp(stderr);

	crtdbug_exit();
	return 0;
}
```

Apart from other debug stuff from crtdebug_exit is prints this:

> [13:09:14]  2123 file=.\crypto\conf\conf_mod.c, line=285, thread=2252, number=24, address=06C98048
> [13:09:14]  2125 file=.\crypto\conf\conf_mod.c, line=285, thread=2252, number=24, address=06C98090
> [13:09:14]  2121 file=.\crypto\conf\conf_mod.c, line=285, thread=2252, number=24, address=06C98000
> [13:09:14]  2120 file=.\crypto\stack\stack.c, line=164, thread=2252, number=16, address=06C45E30
> [13:09:14]  2126 file=.\crypto\buffer\buf_str.c, line=92, thread=2252, number=12, address=06C52138
> [13:09:14]  2122 file=.\crypto\buffer\buf_str.c, line=92, thread=2252, number=12, address=06C59F38
> [13:09:14]  2124 file=.\crypto\buffer\buf_str.c, line=92, thread=2252, number=8, address=06C5A050
> [13:09:14]  2119 file=.\crypto\stack\stack.c, line=162, thread=2252, number=20, address=06C460B0
> 140 bytes leaked in 8 chunks

conf_mod.c line 285 belongs to a OPENSSL_malloc call inside this function:

> static CONF_MODULE *module_add(DSO *dso, const char *name,
>                                conf_init_func *ifunc, conf_finish_func *ffunc)

stack.c line 164 belongs to another OPENSSL_malloc call inside this function:

> _STACK *sk_new(int (*c) (const void *, const void *))

buf_str.c line 92 belongs to another OPENSSL_malloc call inside this function:
> char *BUF_strndup(const char *str, size_t siz)

**Comment by bagder** [comment] 2018-04-29 21:59
This has still not been reproduced by any curl developer so I'm likely to close this soon if nothing new shows up.

**Comment by angelmixu** [comment] 2018-05-09 07:08
Tell me something If I can test anything more.

**Comment by angelmixu** [comment] 2018-05-14 09:16
Ok! It's quite strange, as I can reproduce it as I mentioned above, but anyone is able to.
If I have some time, I'll try to fix it and provide a patch, but I think that in few time we (in my current job) will update to a newer version of SSL where probably this issue is not found.
Thanks all for your time!

**Comment by Nekto89** [comment] 2018-06-13 05:43
CONF_modules_unload(1); makes "stuff from crtdebug_exit" go away.

**Comment by bagder** [comment] 2018-06-13 06:23
@angelmixu does adding that call to `Curl_multi_add_perform()` make any difference for you?

**Comment by Nekto89** [comment] 2018-06-13 07:51
If numbers in {} are the same each run, you can use _CrtSetBreakAlloc(this_number); during debug to break at this call to malloc.
![image](https://user-images.githubusercontent.com/4276548/41337358-add4d1d8-6ef7-11e8-96d5-a5903ac005d5.png)

**Comment by angelmixu** [comment] 2018-06-15 09:04
Hi guys! Thanks for your suggestions!

Adding CONF_modules_unload(1);  just before return on Curl_multi_add_perform function doesn't make any difference :(

```
140 bytes leaked in 8 chunks
0 bytes in 0 Free Blocks.
0 bytes in 0 Normal Blocks.
10849 bytes in 61 CRT Blocks.
0 bytes in 0 Ignore Blocks.
0 bytes in 0 Client Blocks.
Largest number used: 11123 bytes.
Total allocations: 18571 bytes.
Dumping objects ->
{35288} normal block at 0x04C3C588, 20 bytes long.
 Data: <            ,   > 14 00 00 00 00 00 00 00 11 00 00 00 2C 0F F9 00 
{35286} normal block at 0x04D16E18, 12 bytes long.
 Data: <ho          > 68 6F D1 04 00 00 00 00 00 00 00 00 
{35285} normal block at 0x04C3C908, 20 bytes long.
```

If I set the debug number _CrtSetBreakAlloc on the first number, 35288, I get this callstack on file c:\code\openssl-1.0.2n\crypto\mem.c :

![dbgbreak_35288_curl_ssl](https://user-images.githubusercontent.com/2285977/41459958-659b32dc-708b-11e8-8194-b64f4e5481a1.png)

The printf's you see are mine, for debugging and listing callstacks.

**Comment by bagder** [comment] 2018-06-15 09:08
I'm sorry, I think my comment got completely messed up (possibly because my mind was stuck in another issue)!

I actually meant that you should try to add that function call to the `Curl_ossl_cleanup()` function which is what is called when you do `curl_global_cleanup()`, supposedly the last thing you do in your program basically and after you're all done using libcurl.

**Comment by angelmixu** [comment] 2018-06-18 07:42
No problem!
I tested it again putting the function on Curl_ossl_cleanup(), but still the same output/leaks as before :(

I wonder if it could be something external, I've tried using different windows SDK's but it still reports leaks.

**Comment by Nekto89** [comment] 2018-06-18 17:24
btw calls to CRYPTO_mem_ctrl and CRYPTO_mem_leaks_fp(stderr); create memory leaks from Visual Studio point of view

**Comment by richsalz** [comment] 2018-06-18 17:30
Those calls are for debugging. The fact that VS finds problems is not something the team is likely to address.

**Comment by bagder** [comment] 2018-06-19 06:59
> still the same output/leaks as before

Did you set `testGlobal` to true then? libcurl doesn't free all the resources until you call `curl_global_cleanup()` so your tests without that call are not really that useful.

**Comment by angelmixu** [comment] 2018-06-21 07:46
@bagder yes, I tried both cases, and the output is quite similar:

```
140 bytes leaked in 8 chunks
0 bytes in 0 Free Blocks.
0 bytes in 0 Normal Blocks.
10887 bytes in 61 CRT Blocks.
0 bytes in 0 Ignore Blocks.
0 bytes in 0 Client Blocks.
Largest number used: 11199 bytes.
Total allocations: 18647 bytes.
```

**Comment by bagder** [comment] 2018-09-10 15:51
This is the only report of memory leakage that we have and it is a single user and nobody else can reproduce. I'm going go out on limb here and say that this is not a real curl bug but something else. Also, it has been quiet for almost three months.

**Closed by bagder** 2018-09-10 15:51 UTC
Labels: Windows, memory-leak, needs-info-or-update
