### ISSUE TITLE
DNS resolves failed?

### ISSUE THREAD

**Issue by akitaTian** [curl/curl#5692] opened 2020-07-17 02:06 UTC
### I did this
I had a website and DNS server,   like http://MyUrl.com   and 192.168.128.34,  **/etc/resolv.conf**  and  **Network card config file** has been set correctly.

I did this 
I used system curl (7.29) visit site, it works return 200 code,

I used my program that uses **libcurl(7.61.1)** internally， **libcurl** is compiled by 
```
./configure --prefix=insdir --disable-shared --enable-static --disable-ldap --disable-ldaps --enable-ipv6 --enable-ares=c-ares-path --with-zlib=zlib-path --with-ssl=openssl-path 

version 
curl  7.61.1
zlib 1.2.8
openssl 1.0.2k
c-ares  1.14.0
```
visit site, not work.   error is **curl resolve timeout**,    if I change my program like **curl_easy_setopt(curl, CURLOPT_DNS_SERVERS, host)** it works,   Why does this happen？

### I expected the following
My program can correctly read the system default DNS server to access my website when I do not set DNS in my program.

### curl/libcurl version

system default curl 7.29 
my program libcurl 7.61.1

[curl -V output]

### operating system
Linux CentOS7.7 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment] 2020-07-17 17:36
Please give us a more detailed recipe on how to reproduce this problem. Also, since the resolving is done by c-ares in your case, I would recommend you make sure you also try with the latest c-ares version to see if the problem remains, or even with the plain c-ares tools to see if you can reproduce the issue with c-ares only even without including curl...

**Comment by akitaTian** [comment] 2020-07-20 03:11
> Please give us a more detailed recipe on how to reproduce this problem. Also, since the resolving is done by c-ares in your case, I would recommend you make sure you also try with the latest c-ares version to see if the problem remains, or even with the plain c-ares tools to see if you can reproduce the issue with c-ares only even without including curl...


Thanks Reply,   I had removed the c-ares ,   but the above problems still occur.

I copy my test code.
```
#include <stdio.h>
#include <curl/curl.h>
#include <curl/easy.h>

int test(char *URL, char * host) 
{
    CURLcode res;
    CURL *curl;

    if (curl_global_init(CURL_GLOBAL_ALL) != CURLE_OK) 
    {
        printf("curl_global_init() failed\n");
        return -1; 
    }

    curl = curl_easy_init();
    if (!curl) {
        printf("curl_easy_init() failed\n");
        curl_global_cleanup();
        return 1;
    }   

    curl_easy_setopt(curl, CURLOPT_URL, URL);
    curl_easy_setopt(curl, CURLOPT_TIMEOUT, 10);
    curl_easy_setopt(curl, CURLOPT_FILETIME, 1L);
    curl_easy_setopt(curl, CURLOPT_NOBODY, 1L);
    curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);

    res = curl_easy_perform(curl);
    return (int)res;
}

int main(int argc, char *argv[]) 
{
    test(argv[2], argv[1]);
    return 0;
}    

```
The above code cannot access my default DNS server to access my website.
if I add **curl_easy_setopt(curl, CURLOPT_DNS_SERVERS, host)**,  the host parameter is my DNS server address, it's OK.

**Comment by bagder** [comment] 2020-07-20 08:23
`CURLOPT_DNS_SERVERS` only works for libcurl built with c-ares. libcurl built without c-ares will only return an error when that option is attempted to get set.

And again: you need to tell us how to reproduce the error or we can't do anything. This is not a known problem.

**Comment by bagder** [comment] 2020-07-27 10:13
Closed due to lack of details and because this is *probably* a c-ares issue.

**Closed by bagder** 2020-07-27 10:13 UTC
Labels: name lookup
