### ISSUE TITLE
curl: (56) Illegal or missing hexadecimal sequence in chunked-encoding

### ISSUE THREAD

**Issue by momala454** [curl/curl#6760] opened 2021-03-18 10:42 UTC
### I did this
`curl "http://appluslaboratories.com/" -L --proxy "an http proxy" -v --compressed`

The error curl: (56) Illegal or missing hexadecimal sequence in chunked-encoding
is returned.

The request works if I don't use a proxy, and also works on firefox

### I expected the following
html returned

### curl/libcurl version

curl -V output
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

### operating system

Linux ns3167701 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

**Comment by bagder** [comment] 2021-03-18 11:10
I suspect the proxy breaks the chunking, perhaps it removes it but leaves the headers?

Without more details about exactly how that chunk looks like it's hard to do or say anything. If you add `--trace filename.txt` does the log show the problem? (you can edit the file to remove sensitive data before you share it)

Firefox is very forgiving for some chunking errors so unfortunately I don't think that's a very good metric to compare against.

**Comment by momala454** [comment] 2021-03-18 11:17
thanks, here is the trace

[filename.txt](https://github.com/curl/curl/files/6163577/filename.txt)

**Comment by momala454** [comment] 2021-03-18 11:20
When i tried another proxy, on another server, it returned this :

`curl: (56) Problem (2) in the Chunked-Encoded data`

```
curl -V output
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.53.1 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets
```

**Comment by bagder** [comment] 2021-03-18 11:26
The log dump shows that my suspicion was exactly right: there's no chunked hexadecimal sequence at all in the beginning of the data (it should be the length of the initial chunk in hexadecimal, followed by CRLF) and thus the HTTP response is broken, format wise. The header says it is using chunked encoding, but the data that arrives is not encoded correctly. That's a proxy bug and curl works as intended.

**Comment by momala454** [comment] 2021-03-18 11:32
apparently chrome and firefox both are able to read the data, maybe it could be a good idea to mimic them as this difference could be used to detect curl ?

**Comment by bagder** [comment] 2021-03-18 11:37
Chrome and Firefox take (horrible) shortcuts in order to do so and for them it is easier (and assumed) to be "sloppy" in this regard. curl cannot easily do the same without problems.

Like for example how do you tell the end of the response body for this response?

If someone would work on it and get a decent work-around for it, I believe I could be convinced to merge, but I don't think I'm going to work on this personally.

**Comment by bagder** [comment] 2021-03-18 11:39
You much easier detect a browser vs curl by just inserting a little javascript in the page.

**Comment by jay** [comment] 2021-03-18 22:28
IMO Chrome and Firefox shouldn't overcompensate for bad behavior like that. I don't think pursuing this is worthwhile.

**Comment by bagder** [comment] 2021-03-21 10:23
This is not a bug, closing.

**Closed by bagder** 2021-03-21 10:23 UTC
Labels: HTTP, connecting & proxies, not-a-bug
