### ISSUE TITLE
Connection aborted

### ISSUE THREAD

**Issue by paulharris** [curl/curl#1430] opened 2017-04-19 09:51 UTC
Hi,

I'm looking for a little guidance here,
I have my program with libcurl (fairly recent from git, last month or so),
it uploads via POST to a HTTP (no SSL) server.

It seems to work ok on most computers,
but there is one computer (that is not mine) that can only send about 800kb before it stops sending, pauses, and then times out with a "Send failed: Connection aborted" message.

This computer is painful to debug on for many reasons, so, how would I even begin?
If other client computers are not a problem, why would this one computer consistently suffer from aborted connections?

I confirmed that Chrome can upload to the same server (plain POST to the same lighttpd, which will pass the data onto a cgi-bin program)... so its not the server or connection, so I assume its something related to libcurl.

Further hint: it uploaded twice ok (500k at a time), but after that couldn't upload anymore.

Ideas?  Where to from here?

cheers,
Paul

**Comment by bagder** [comment] 2017-04-20 09:06
What operating system is this?

Since you say it works from many other computers, why would it imply that libcurl is to blame for this single problematic instance? It seems more like something specific to that single computer/system. Network drivers? Out of memory?

`ECONNABORTED` is a very generic error code for basically "a timeout or a protocol error" so it alone doesn't give us much to go on. If you manage to record the HTTP traffic with wireshark/tcpdump when this problem occurs, I suppose that might be a way to get some further clues.

**Comment by paulharris** [comment] 2017-04-21 00:04
Hi,

It is windows,
Yes I agree it is something unique to this computer,
But other software (like chrome) is able to upload reliably to the same
server, so I think that unique feature is triggering bad behaviour in
libcurl.

What is good for recording traffic on Windows?
There is no compiler so if I need to try different hacks, I'll need to
compile at my end, upload and test, so will be painful.
I am looking for the most efficient path...

This week I'll be in an area of poor internet. Maybe I can simulate the
same problem.

To me, it feels like libcurl is seeing delays and waiting before sending,
but maybe not computing the delays correctly?
Perhaps because I am reusing multi handles, and there are leftover delays
stats that are carrying over to the next upload...

Any ideas where to start probing?

Cheers,
Paul

On 20 Apr 2017 5:06 PM, "Daniel Stenberg" <notifications@github.com> wrote:

What operating system is this?

Since you say it works from many other computers, why would it imply that
libcurl is to blame for this single problematic instance? It seems more
like something specific to that single computer/system. Network drivers?
Out of memory?

ECONNABORTED is a very generic error code for basically "a timeout or a
protocol error" so it alone doesn't give us much to go on. If you manage to
record the HTTP traffic with wireshark/tcpdump when this problem occurs, I
suppose that might be a way to get some further clues.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/curl/curl/issues/1430#issuecomment-295643807>, or mute
the thread

**Comment by paulharris** [comment] 2017-04-21 01:45
Maybe the timeouts are the problem.

I haven't tried your new slow speed timeout fix yet. Been busy.
I'll do that next.

**Comment by bagder** [comment] 2017-04-21 13:39
> But other software (like chrome) is able to upload reliably to the same server, so I think that unique feature is triggering bad behavior in libcurl. 

Right, but it's next to impossible to figure out what those differences can be that make one application trigger this problem when the other doesn't. We would need a lot more details for that!

> What is good for recording traffic on Windows?

The only thing Windows I know is what I can google myself to... Wireshark and tshark don't work on windows?

> To me, it feels like libcurl is seeing delays and waiting before sending, but maybe not computing the delays correctly?

libcurl doesn't really wait for anything unless you have set an artificial transfer limit. The waiting that might happen (like when TCP has to slow down due to network conditions) is done in the TCP/IP stack and is done by the operating system and the error `ECONNABORTED` is generated by the operating system. Sure there might be a timeout problem here, but that's most likely in a layer that is outside of libcurl! Are you using libcurl's speed limit feature? 

Is there anything particular that libcurl does that triggers this problem one might wonder? I have no idea. This is the first time I've seen someone report a problem like this and even you see that it is only one machine out of several where this issue occurs. Also, libcurl really doesn't do anything special on windows for normal file transfers, it acts the same way on all operating systems - and we don't see this elsewhere either.

Lots of indications that this is a special snow flake. I realize that doesn't really help fixing the issue, it mostly just emphasizes that this is a hard-to-figure-out bug and we don't even know who/what to blame yet...

**Comment by jay** [comment] 2017-04-21 19:13
> I have my program with libcurl (fairly recent from git, last month or so),

Building from an arbitrary recent commit in the repo is not suitable for production. We make changes that can evolve before release. Before we get ahead of ourselves here try the latest release 7.54.0 if you can, and post the OS and `curl_version()` information. Try to boil it down as much as you can. Is it just one website you have the problem with, what about other websites? What happens when you send a POST to http://httpbin.org/ for example? Do you have a repro case that only reproduces on that one computer, what happens when you send that same data from another computer using the same libcurl?

If none of that helps then +1 for Wireshark. You will likely have to run it as admin for the network adapters to be visible in the list. Select the adapter and then type host xxx in capture filter field above and you can get just that traffic, like 'host example.com'.

Note wireshark captures may contain sensitive information, you can do some sanitizing using TraceWrangler but that only goes so far and the actual content of what is sent/received typically isn't modified if left in the capture and therefore may still contain sensitive information.

**Comment by paulharris** [comment] 2017-04-21 23:09
Thanks guys,

When I say 'latest git' I should say, latest tag from git, so it would be a
stable version.

Yes I'm using the slow-transfer timeouts, but that only timeouts after a
whole minute.
So even if it is a timeout problem, it is transferring much slower than
Chrome within that first minute,
so it looks like something is weird.

re using curl straight - its currently libcurl inside my program, so I'll
try and get curl.exe onto the computer and get some diagnostics.
I've done that before, I can make it print out all the protocol info,
but what I think we'll need is printouts of when and why its deciding to
send data (or when its deciding to wait).
Any idea where I/we could add some debug printouts for that?

re Wireshark, I like that idea, and I MIGHT be able to get admin on it.

cheers,
Paul

**Comment by jay** [comment] 2017-04-22 07:31
You could always output timestamps every time the read callback is called but I think it's premature for that. First try disabling the timeouts and see what happens. Also you can try the [PostUpload speed test](https://gist.github.com/jay/daac01682f17c2dc213e) and use it to upload 50MB to a speed test server and see if that works consistently. If it does try POSTing to your own server with your own data, and see if you have the same problem.

**Comment by bagder** [comment] 2017-05-16 06:19
@paulharris: any news on this?

**Comment by paulharris** [comment] 2017-05-16 06:55
Not yet, its on my list for this week, just been busy.
The bug is really annoying so it won't fall off the list!

**Comment by bagder** [comment] 2017-08-27 18:08
This issue has been left silent for three month, so I'm now closing it. If you manage to bring back more details then please feel free to provide them and we can re-open this again.

**Closed by bagder** 2017-08-27 18:08 UTC
Labels: connecting & proxies
