### ISSUE TITLE
Random HTTP2 Streaming alert error after Ubuntu update

### ISSUE THREAD

**Issue by lveitch** [curl/curl#4123] opened 2019-07-18 16:03 UTC
So this past Friday we updated our Ubuntu servers and everything is fine.  However, our Nagios server started presenting an alert "CRITICAL: Stream error in the HTTP/2 framing layer for (our website address)  We have restarted nagios, reset the service schedule, etc. but the alert doesn't clear.  This alert was not present prior to updating and nothing has been done with the server in question that runs the website (Windows Server 2016).  Some web searches led me here where this error appears, typically, with a discrepancy with the cURL and libcurl versioning on my linux server.  However mine are the same as indicated below.  Investigation and questions with the Nagios folks has not yielded any results so I come to you. Is this a result of something with regard to cURL/libcurl on the Nagios or is something else in play that I am unaware of?

### curl/libcurl version
curl 7.65.2 (x86_64-pc-linux-gnu) libcurl/7.65.2 OpenSSL/1.1.1b zlib/1.2.11
Release-Date: 2019-07-17
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets

### operating system
Linux Ubuntu Server 19.04 (Disco Dingo)

**Comment by bagder** [comment] 2019-07-18 22:22
I'm afraid this is far too little details for anyone to work with. Tell us how to reproduce this problem, preferably with the curl command line tool or by running a small libcurl example against a public site.

**Comment by lveitch** [comment] 2019-07-19 15:17
So this is part of the conundrum; I dont honestly know anything about libcurl or cURL at all.  I know it was a required package on Nagios (which is running on Ubuntu server) during installation so I dont know what it is even using it for.  i am unsure how to replicate the problem because I have never had the issue before.  I updated Ubuntu server to the latest version, applied all updates, etc. and now I am getting the above alert for a windows server thats running a website.  Nothing changed with the windows server, so I am trying to figure out why updating Ubuntu and its packages would start reflecting this error on this website and not any of our other sites.  After investigating around, I found numerous posts concerning curl and this error which led me to asking the question here.  Is there anyway to turn off this HTTP2 framing layer (conf file with some lines I can comment out) or is there something else at play

**Comment by bagder** [comment] 2019-07-19 17:37
libcurl of course offers ways to not use HTTP/2, but you're using an app that is using libcurl and I can't tell you how you tell your app to tell libcurl to do that... You need to read up or ask the devs of the app you're using.

The fact that you get an error code or message from libcurl when you use an app against an unspecified server is too vague for us to work on.

**Comment by bagder** [comment] 2019-07-19 17:39
Also, this problem might even be caused by the server end for all we know.

The `curl -V` output doesn't include nghttp2 and doesn't mention HTTP/2 support, which might imply that it isn't the actually used libcurl installation...

**Comment by jay** [comment] 2019-07-19 17:42
We can't do anything with this you will have to work with nagios to find out which plugin is causing the issue. "Stream error in the HTTP/2 framing layer" is the error string for error CURLE_HTTP2_STREAM. I don't see any direct evidence though that it's libcurl. Also your curl version doesn't show http2 if it did it would look like this:

curl 7.65.3-DEV (i386-pc-win32) libcurl/7.65.3-DEV OpenSSL/1.0.2s **nghttp2/1.39.1**
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s
 rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Debug **HTTP2** HTTPS-proxy IPv6 Largefile NTLM SSL

If you get a build with http2 then you can try connecting to the problem server using the curl tool and see if you can reproduce.

**Comment by lveitch** [comment] 2019-07-19 17:46
Hey this is more than I got with the nagios folks...i appreciate it kindly!  This gives me something to go on and look for.  Is there anyway to verify the libcurl installation that is used instead of the one that is output in curl -V?

**Comment by jay** [comment] 2019-07-19 18:34
You can use `apt list --installed '*libcurl*'` to see the packaged versions of libcurl that are installed and `apt-cache show <package>` to see the details. AFAICS all official packaged versions for disco have http2 support ([libcurl3-gnutls](https://packages.ubuntu.com/disco/libs/libcurl3-gnutls), [libcurl3-nss](https://packages.ubuntu.com/disco/libs/libcurl3-nss), [libcurl4 (openssl variant)](https://packages.ubuntu.com/disco/libs/libcurl4)), same for dev. Either someone built curl on that machine or you have a 3rd party package for it which is why that 7.65.2 build you showed doesn't have http2 support.

I'd guess a nagios plugin is using a packaged version of libcurl, **which should be fine**. I think you are approaching this wrong, I would go to nagios and request support if you can't figure it out from the logs.

**Comment by lveitch** [comment] 2019-07-19 19:16
Interesting...it doesnt even show 7.65.2 at all...lol

# apt list --installed '*libcurl*'
Listing... Done
libcurl3-gnutls/disco-updates,disco-security,now 7.64.0-2ubuntu1.1 amd64 [installed]
libcurl3-nss/disco-updates,disco-security,now 7.64.0-2ubuntu1.1 amd64 [installed,automatic]
libcurl4-nss-dev/disco-updates,disco-security,now 7.64.0-2ubuntu1.1 amd64 [installed]
libcurl4/disco-updates,disco-security,now 7.64.0-2ubuntu1.1 amd64 [installed]

So I found the 7.65.2 package in /usr/curl on the system and deleted it.  i also, to be clean, decided to uninstall 7.64 (apt-get remove curl).  I then rebooted and reinstalled (apt-get install curl) but the curl-V still showcases 7.65.2.  I know its just cosmetic at this point as its not showing the correct information but is there anyway to update that output?

**Comment by bagder** [comment] 2019-07-21 10:46
Unfortunately this report doesn't include details that are actionable for us and seems unlikely to get any. Closing.

**Closed by bagder** 2019-07-21 10:46 UTC
Labels: HTTP/2, needs-info-or-update

**Comment by lveitch** [comment] 2019-07-22 14:59
So I found the issue; for some reason with the recent linux updates, we had to specify the HTTP_VERSION within the perl script that is used for the site monitor and restrict it to HTTP1.1

**Comment by bagder** [comment] 2019-07-29 20:44
That wasn't really the reason.

current libcurl versions default to HTTP/2 for HTTPS so that's no surprise. It still shouldn't get stream errors. Downgrading to HTTP/1.1 might be a decent and manageable work-around of course.
