### ISSUE TITLE
How to get Cookie while use CURLOPT_CONNECT_TO for libcurl

### ISSUE THREAD

**Issue by CuiTongyun** [curl/curl#1775] opened 2017-08-14 05:49 UTC
Everything is working fine while use the bellow setting.

      curl_easy_setopt(easyHandle, CURLOPT_URL, "https://vcse.example.com:8443/[...]");
      curl_easy_getinfo(easyHandle, CURLINFO_COOKIELIST, &cookies)

libcurl could set SNI server_name "vcse.example.com" in SSL ClientHello, and we could obtain Cookie from HTTP header Set-Cookie:<>.

But, after we add CURLOPT_CONNECT_TO for SNI Server Name Indication "mra-host.example.com", it could not obtain Cookie again.

      struct curl_slist *connect_to = NULL;
      connect_to = curl_slist_append(NULL, "mra-host.example.com::vcse.example.com:8443");
      curl_easy_setopt(easyHandle, CURLOPT_CONNECT_TO, connect_to);
      curl_easy_setopt(easyHandle, CURLOPT_URL, "https://mra-host.example.com:8443/[...]);

      curl_easy_getinfo(easyHandle, CURLINFO_COOKIELIST, &cookies)

We take try to add CURLOPT_COOKIEFILE, but there is still no Cookie captured.

      curl_easy_setopt(easyHandle, CURLOPT_COOKIEFILE, "");
 
The requirement is that:

1. use libcurl to send HTTP request https://vcse.example.com:8443/[...].
2. at the same time, set SNI server_name "mra-host.example.com" in SSL ClientHello.
3. could obtain Cookie in HTTP response from Header Set-Cookie: <>.

The HTTP response is:

      Content-Type: text/xml
      Server: CE_C ECS
      Set-Cookie: X-Auth=1e1fb8c4-3e28-4e84-b4ec-65176ba62a4e; Expires=Fri, 11 Aug 2017 17:09:17 GMT; Domain=.jabberqa.example.com; Path=/; Secure
      Date: Fri, 11 Aug 2017 09:09:17 GMT
      Age: 0
      Content-Length: 1146
      Connection: keep-alive

Any suggestion would be appreciated.

**Comment by jay** [comment] 2017-08-14 06:28
I can't reproduce, tested with `libcurl/7.55.1-DEV OpenSSL/1.0.2l nghttp2/1.23.1`. 

~~~
.mra-host.example.com   TRUE    /       TRUE    1502471357      X-Auth  1e1fb8c4-3e28-4e84-b4ec-65176ba62a4e
~~~

Can you try the latest libcurl, and if that doesn't work give us a self contained example that can be used to reproduce.

**Comment by CuiTongyun** [comment] 2017-08-14 07:36
our libcurl version is 7.54.1

Is there any option to set SNI for libcurl directly, such as SSL_set_tlsext_host_name(m_ssl, "mra-host.cisco.com") for OpenSSL.
We saw a option “CURLOPT_SNI_HOSTNAME”, but it seems it is not officially supported in libcurl.

If we use CURLOPT_CONNECT_TO for SNI, how to obtain Cookie?

The requirement is that:
1. use libcurl to send HTTP request https://vcse.example.com:8443/[...].
2. at the same time, set SNI server_name "mra-host.example.com<http://mra-host.example.com/>" in SSL ClientHello.
3. could obtain Cookie in HTTP response from Header Set-Cookie: <>.

**Comment by bagder** [comment] 2017-08-14 07:41
The `CURLOPT_CONNECT_TO` option only changes what host libcurl resolves and connects to, it will still use the name in the URL for cookies and SNI.

If you want cookies and SNI to use `mra-host.example.com`, use that name in the URL!

**Comment by CuiTongyun** [comment] 2017-08-14 08:00
if we use mra-host.example.com in the URL, that means the hostname in HTTP URL should be same as SNI server_name.  it could not satisfy the requirement:
1. use libcurl to send HTTP request https://vcse.example.com:8443/[...].
2. set a different SNI server_name "mra-host.example.com" in SSL ClientHello.

**Comment by bagder** [comment] 2017-08-14 08:08
Ah, so you want:
1. connect to host A
2. use host B for cookies
3. use host C for SNI

Where A and B might be the same?

**Comment by CuiTongyun** [comment] 2017-08-14 08:14
Yes, A and B is same, A and C is different.

if we use the bellow:
  curl_easy_setopt(easyHandle, CURLOPT_URL, "https://vcse.example.com:8443/[...]");
  curl_easy_getinfo(easyHandle, CURLINFO_COOKIELIST, &cookies)
libcurl could set SNI server_name "vcse.example.com" in SSL ClientHello, and we could obtain Cookie from HTTP header Set-Cookie:<>.
(Set-Cookie: X-Auth=1e1fb8c4-3e28-4e84-b4ec-65176ba62a4e; Expires=Fri, 11 Aug 2017 17:09:17 GMT; Domain=.jabberqa.cisco.com; Path=/; Secure)

**Comment by bagder** [comment] 2017-08-14 08:20
How about this setup:

1. Use host A in the `URL`, the host name you want SNI for
2. Set `CONNECT_TO` or `RESOLVE` so that libcurl connects to B instead of the host the URL specifies
3. Set `Host:` in `HTTPHEADER` to the HTTP level hostname (C) you want to reach and for which you want cookies to work/use. libcurl has logic that extracts the cookie host from a custom `Host:`, but that host name is not used for SNI!

A, B and C in there can all be different...

**Comment by CuiTongyun** [comment] 2017-08-14 08:26
But actually, B is virtual Hostname, there is no any IP address, we could not connect to this Hostname.

**Comment by bagder** [comment] 2017-08-14 08:33
B in comment https://github.com/curl/curl/issues/1775#issuecomment-322127957 would be the host you *do* connect to. There has to be a host you connect to... =)

**Comment by CuiTongyun** [comment] 2017-08-14 08:44
host A: vcse.example.com with IP address xxx.xxx.xxx.xxx
host B. jabberqa.example.com with Cookie
host C. mra-host.example for SNI

We could take a try to 
1. set host C in url (curl_easy_setopt(easyHandle, CURLOPT_URL, "https://mra-host.example.com:8443/[...]);), to set SNI. 
2. set Connect_To with host A which we need to connect.
3. set Host: in HTTPHEADER with host B to get Cookie
will be working or not.

**Comment by CuiTongyun** [comment] 2017-08-14 09:11
another question: 
if we use: 
    curl_easy_setopt(easyHandle, CURLOPT_URL, "https://vcse.example.com:8443/[...]");
    curl_easy_getinfo(easyHandle, CURLINFO_COOKIELIST, &cookies)
libcurl could set SNI server_name "vcse.example.com" in SSL ClientHello, and we could obtain Cookie from HTTP header Set-Cookie:<>. (Set-Cookie: X-Auth=88e387ff-ed8a-4105-9028-3ebf86037f57; Expires=Mon, 14 Aug 2017 12:03:04 GMT; Domain=.jabberqa.example.com; Path=/; Secure)

but we use CONNECT_TO, why it could not obtain Cookie.

It would be convenient that libcurl could support “CURLOPT_SNI_HOSTNAME” to set a custom SNI and doesn't depend on CURLOPT_URL.

**Comment by bagder** [comment] 2017-08-14 09:18
If you connect to `vcse.example.com` and the cookie is set for ``Domain=.jabberqa.example.com``, then that cookie shouldn't match. If you make it do that, it is a bug.

`CONNECT_TO` is done at the network layer in libcurl and does not affect HTTP or cookies. It really can't.

**Comment by CuiTongyun** [comment] 2017-08-14 09:36
Client reconstructs SNI server_name "mra-host.example.com".
Server will search its cert store to find a domain certificate matching SNI hostname:
            1. if a match is found, Server will send back the cert (include SNI hostname)
            2. otherwise, Server will return its platform certificate.
Client validates server certificate:
            1. if certificate is good, SSL setup continues and SSL setup finishes successfully.
            2. otherwise, Client will request the user to accept or decline the cert.

if the customer accept the certificate, then it would accept the Cookie from the server.
So they could be different.

**Comment by bagder** [comment] 2017-08-14 09:39
Sorry but I don't understand what you're responding to here. Yes, it is important to pass on the correct SNI to the host.

**Comment by CuiTongyun** [comment] 2017-08-14 09:45
I want to say that Client can not consider Domain=.jabberqa.example.com, and didn't need to verify the Domain in Cookie if we accept the cert and know the risk.

**Comment by bagder** [comment] 2017-08-14 09:51
Right, that's your view. But libcurl's cookie parser has no "ignore the domain attribute" option, it will ignore all received cookies set for domains that doesn't match the host set in the URL or in a custom `Host:` header. That's totally separate from the question of SNI and TLS certificates.

**Comment by CuiTongyun** [comment] 2017-08-14 14:09
OK, thanks for kind support.
Is there any plan for libcurl to support CURLOPT_SNI_HOSTNAME to set custom SNI, otherwise, it needs to depend on both CURLOPT_CONNECT_TO and CURLOPT_URL to achieve this.

**Comment by bagder** [comment] 2017-08-14 21:01
> Is there any plan for libcurl to support CURLOPT_SNI_HOSTNAME

I can't say I know of anyone planning to work on this, but I also don't think I would object to such a change if someone would bring it.

**Comment by bagder** [comment] 2017-08-14 21:39
As an issue however, I think I've responded to all possible issues and I don't feel that there's any bug in what we've discussed here? Can we close this then?

**Comment by jay** [comment] 2017-08-15 01:22
We abandoned CURLOPT_SNI_HOSTNAME because there was no interest, see #607

**Comment by CuiTongyun** [comment] 2017-08-15 03:26
It could not work with Host: header, what I do:

host A: vcse.example.com with IP address 10.10.10.10.
host B. jabberqa.example.com is Domain name in Set-Cookie header, which is configured in Server and there is no real IP address.
host C. mra-host.example.com for SNI server_name in SSL ClientHello, there is no real IP address.

set CURLOPT_URL with host C, as SNI is extracted from url.
set CURLOPT_CONNECT_TO with host A, Client need to connect with the server IP address.

I take try to set Host: header with host A and host C, it didn't work, Client could not obtain Cookie.

**Comment by jay** [comment] 2017-08-15 04:55
You have changed the details on this. Originally you said the cookie Domain was mra-host.example.com but now you are saying it is jabberqa.example.com and you want those cookies? As @bagder suggested you'd have to set the host:
~~~c
  struct curl_slist *header_list = NULL;
  header_list = curl_slist_append(NULL, "Host: jabberqa.example.com:8443");
  curl_easy_setopt(curl, CURLOPT_HTTPHEADER, header_list);
~~~
Using that host I'm able to obtain a cookie from this response:
~~~
HTTP/1.0 200 OK
Content-Type: text/xml
Server: CE_C ECS
Set-Cookie: X-Auth=1e1fb8c4-3e28-4e84-b4ec-65176ba62a4e; Expires=Fri, 11 Aug 2017 17:09:17 GMT; Domain=.jabberqa.example.com; Path=/; Secure
Date: Fri, 11 Aug 2017 09:09:17 GMT
Age: 0
Content-Length: 0
Connection: keep-alive

~~~
The cookie from [CURLINFO_COOKIELIST](https://curl.haxx.se/libcurl/c/CURLINFO_COOKIELIST.html):
~~~
.jabberqa.example.com   TRUE    /       TRUE    1502471357      X-Auth  1e1fb8c4-3e28-4e84-b4ec-65176ba62a4e
~~~

**Comment by CuiTongyun** [comment] 2017-08-15 06:43
Thanks for kind support. we could get Cookie while set Host as you suggested.

It would be convenient that libcurl could support CURLOPT_SNI_HOSTNAME to set custom SNI. if SNI aways extract from url, we need to replace the url from https://vcse.example.com:8443 to https://mra-host.example.com:8443 for every HTTP request. and it also needs to set Host: <> to get Cookie. 

Please close the case, thanks for all your effort and support.

**Closed** 2017-08-15 06:45 UTC
