### ISSUE TITLE
HTTP/2 connection closed when a stream gets an error

### ISSUE THREAD

**Issue by hon-key** [curl/curl#1009] opened 2016-09-12 19:05 UTC
# I did

I implemented a HTTP/2 APNs post client using curl_multi_perform(),when I send right data,its all ok.but if one of the APNs requests is a bad request,it got HTTP/2 400 bad request and print "HTTP error before end of send, stop sending",and then closing connection 0.

# I expected

when I send many request to APNs server,they don't close connection but keep connection ,then they send successfully.but once one of them is a bad request , connection will be closed,and reconnect.this will cause a incorrect perform，for example，if I send 3 request , the second request is a bad request,APNs always get 3 correct request because the third request was perform twice.and I try to solve this question by using curl_easy_setopt(),but failed.
and I saw the source code of libcurl,I found this question can't be avoid.

# version
curl/libcurl version 7.50.1

# operating system
mac os x 10.11.6

**Comment by bagder** [comment] 2016-09-12 20:47
I believe that bug was fixed with commit 3533def3d, included in curl 7.50.2. Can you please try that version or the latest from git and see if your problem persists?

**Comment by bagder** [comment] 2016-09-12 20:51
BTW, this is probably a dupe of #941

**Comment by caihongji123** [comment] 2016-09-13 04:14
thanks a lot,I solve the prolem by updating curl version to 7.50.2, my APNs notification pushing module seems to be stable when pushing over 10000 concurrent notification.

**Comment by jay** [comment] 2016-09-13 04:21
@caihongji123 Are you the original reporter hon-key (HJ-Cai)?

**Comment by hon-key** [comment] 2016-09-13 04:56
@jay sorry,I made a mistake,that is my company's account

**Closed** 2016-09-13 04:56 UTC
Labels: HTTP/2

**Comment by jay** [comment] 2016-09-13 05:05
No problem, thanks for letting us know this is resolved.
