### ISSUE TITLE
curl_easy_perform block for a long time

### ISSUE THREAD

**Issue by zhenghj8** [curl/curl#4769] opened 2019-12-30 09:58 UTC
### I did this
I set CURLOPT_TIMEOUT for 10s, and run curl_easy_perform to make the http request for domain1.But curl_easy_perform did not send the request untill my app exit and after the request send it return successfully.However, the other request call with curl_easy_perform for domain2 run normally.I use CURLOPT_DEBUGFUNCTION to trace the request and got this log:

```
[I] [2019-12-30 09:14:15.292] [2124] [105553123227648] [curl_wrapper.cpp] [CurlEasyRequest] [236] [F3CNet] [Curl]send request
[I] [2019-12-30 09:15:30.997] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]=> Send SSL data:
[I] [2019-12-30 09:15:30.997] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]=> Send SSL data:
[I] [2019-12-30 09:15:31.059] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]<= Recv SSL data:
[I] [2019-12-30 09:15:31.059] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]<= Recv SSL data:
[I] [2019-12-30 09:15:31.059] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]<= Recv SSL data:}
[I] [2019-12-30 09:15:31.082] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]<= Recv SSL data:
[I] [2019-12-30 09:15:31.083] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]<= Recv SSL data:M
[I] [2019-12-30 09:15:31.083] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]<= Recv SSL data:
[I] [2019-12-30 09:15:31.083] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]<= Recv SSL data:
[I] [2019-12-30 09:15:31.083] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]<= Recv SSL data:
[I] [2019-12-30 09:15:31.083] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]=> Send SSL data:
[I] [2019-12-30 09:15:31.083] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]=> Send SSL data:
[I] [2019-12-30 09:15:31.083] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]=> Send SSL data:
[I] [2019-12-30 09:15:31.083] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]=> Send SSL data:
[I] [2019-12-30 09:15:31.083] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]=> Send SSL data:
[I] [2019-12-30 09:15:31.083] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]=> Send SSL data:
[I] [2019-12-30 09:15:31.119] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]<= Recv SSL data:
[I] [2019-12-30 09:15:31.119] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]<= Recv SSL data:
[I] [2019-12-30 09:15:31.119] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]<= Recv SSL data:
[I] [2019-12-30 09:15:31.119] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]<= Recv SSL data:
[I] [2019-12-30 09:15:31.119] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]=> Send SSL data:X
[I] [2019-12-30 09:15:31.119] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]=> Send header:POST /authority/ HTTP/1.1
[I] [2019-12-30 09:15:31.119] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]=> Send data:xxxxxxxxxxxxxxxxxxxxxx
[I] [2019-12-30 09:15:31.307] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]<= Recv header:HTTP/1.1 200 OK
[I] [2019-12-30 09:15:31.308] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]<= Recv header:Date: Mon, 30 Dec 2019 01:15:27 GMT
[I] [2019-12-30 09:15:31.308] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]<= Recv header:Content-Type: application/json
[I] [2019-12-30 09:15:31.308] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]<= Recv header:Content-Length: 1406
[I] [2019-12-30 09:15:31.308] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]<= Recv header:Connection: keep-alive
[I] [2019-12-30 09:15:31.308] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]<= Recv header:Set-Cookie: tgw_l7_route=c7c5591d982da5325beb06c51eb928d0; Expires=Mon, 30-Dec-2019 01:15:57 GMT; Path=/
[I] [2019-12-30 09:15:31.308] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]<= Recv header:Server: nginx/1.8.0
[I] [2019-12-30 09:15:31.308] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]<= Recv header:
[I] [2019-12-30 09:15:31.308] [2124] [105553123227648] [curl_wrapper.cpp] [my_trace] [52] [F3CNet] [curl]<= Recv data:xxxxxxxxxxxxxxxxxxx
[I] [2019-12-30 09:15:31.308] [2124] [105553123227648] [curl_wrapper.cpp] [CurlEasyRequest] [238] [F3CNet] [Curl]recv curl_code=0
[I] [2019-12-30 09:15:31.310] [2124] [105553123227648] [thread_pool.cpp] [Run] [61] [F3CNet] [curl]thread pool wake up
[I] [2019-12-30 09:15:31.310] [2124] [105553123227648] [thread_pool.cpp] [Run] [71] [F3CNet] [curl]thread pool sleep
```

105553123227648 is the thead id. I call the curl_easy_perform at  09:14:15 but it send data at 09:15:30.This is where the "send request" and "recv curl_code=" print:

```
FTLogInfo("Curl") << "send request";
CURLcode code = curl_easy_perform(session->curl_easy_handle_);
FTLogInfo("Curl") << "recv curl_code=" << code;
```

### I expected the following
I expected the request will send as soon as possible after call curl_easy_perform, and no mater what it will return with a CURLcode when the time I set for CURLOPT_TIMEOUT is trigger.Or is there something special I need to pay attention to？

### curl/libcurl version

7.62.0

### operating system
macOS

**Comment by jay** [comment] 2019-12-30 19:30
Retool your debug to record [CURLINFO_TEXT](https://curl.haxx.se/libcurl/c/CURLOPT_DEBUGFUNCTION.html) with a timestamp, that will help identify where the problem is. Can you reproduce using the curl tool? `curl -v --max-time 10 https://...`

> 105553123227648 is the thead id

Are you sure about that? Have you read [libcurl thread safety (https://curl.haxx.se/libcurl/c/threadsafe.html) guidelines? What is the output of `curl_version()`?

**Comment by zhenghj8** [comment] 2019-12-31 03:12
>105553123227648 is the thead id
I'm sure about that and the logs above were printed in the same thread.I'm sorry that we have updated the version at one time and the output of `curl_version()` is `libcurl/7.64.0 OpenSSL/1.0.2k zlib/1.2.11`.
The curl handle is Initialized in one thread and used in another but it's guaranteed there is only one thread use the handle at the same time.I find that we have not set the CURLOPT_NOSIGNAL, so is it the reason cause the curl_easy_perform block?
>Retool your debug to record CURLINFO_TEXT with a timestamp, that will help identify where the problem is.
I will try that but I could't make sure that it can be reproduce again.

**Comment by zhenghj8** [comment] 2019-12-31 03:14
>105553123227648 is the thead id

I'm sure about that and the logs above were printed in the same thread.I'm sorry that we have updated the version at one time and the output of `curl_version()` is `libcurl/7.64.0 OpenSSL/1.0.2k zlib/1.2.11`.
The curl handle is Initialized in one thread and used in another but it's guaranteed there is only one thread use the handle at the same time.I find that we have not set the CURLOPT_NOSIGNAL, so is it the reason cause the curl_easy_perform block?
>Retool your debug to record CURLINFO_TEXT with a timestamp, that will help identify where the problem is.

I will try that but I could't make sure that it can be reproduced again.

**Comment by jay** [comment] 2019-12-31 07:35
Please run [ShowLibcurlResolver](https://gist.github.com/jay/d3323a81345e75462b70) and tell us the resolver used by your libcurl.

**Comment by zhenghj8** [comment] 2019-12-31 07:41
It print `threaded`.

**Comment by jay** [comment] 2019-12-31 08:17
Set CURLOPT_NOSIGNAL to 1L in all handles if you are using libcurl from multiple threads, and follow other thread guidelines. Without knowing what step libcurl is hanging at there is not enough information to investigate further.

The only issue I am aware of with the threaded resolver hanging is [on cleanup](https://github.com/curl/curl/issues/2975) waiting for an incomplete resolve.

**Comment by bagder** [comment] 2020-01-03 15:19
If you think curl is doing wrong, please provide us with a way to reproduce and see the problem for ourselves, preferably against a public URL. I don't think the information given in this report is enough for us to say much about what you're seeing.

**Comment by bagder** [comment] 2020-01-11 22:06
Initial quick responses and then nothing for over a week and we don't have anything to go on. Closing.

**Closed by bagder** 2020-01-11 22:06 UTC
Labels: needs-info-or-update, performance
