### ISSUE TITLE
http3 stopped working on windows from curl-7.83.1_5

### ISSUE THREAD

**Issue by shithappens2016** [curl/curl#9053] opened 2022-06-26 02:16 UTC
I tested from `curl-7.83.1_3` to `curl-7.83.1_7` on windows, http3 only works with `curl-7.83.1_3` and `curl-7.83.1_4`.

```bash
curl\bin>curl -v --http3 https://www.cloudflare.com
*   Trying 104.16.123.96:443...
* Connect socket 320 over QUIC to 104.16.123.96:443
*  CAfile: curl\bin\curl-ca-bundle.crt
*  CApath: none
* ngtcp2_conn_handle_expiry returned error: ERR_HANDSHAKE_TIMEOUT
* connect to 104.16.123.96 port 443 failed: Failed sending data to the peer
*   Trying 104.16.124.96:443...
* Connect socket 368 over QUIC to 104.16.124.96:443
*  CAfile: curl\bin\curl-ca-bundle.crt
*  CApath: none
* ngtcp2_conn_handle_expiry returned error: ERR_HANDSHAKE_TIMEOUT
* connect to 104.16.124.96 port 443 failed: Failed sending data to the peer
* Failed to connect to www.cloudflare.com port 443 after 21662 ms: Failed sending data to the peer
* Closing connection 0
curl: (55) ngtcp2_conn_handle_expiry returned error: ERR_HANDSHAKE_TIMEOUT
```

**Comment by gvanem** [comment] 2022-06-26 02:46
Works fine for me with `curl 7.84.0-DEV (i386-pc-win32)`.
I also have `msh3/0.4.0.0`.

**Comment by bagder** [comment] 2022-06-26 08:59
@shithappens2016 I recommend building the latest curl with the latest h3 library. I believe curl in git works with ngtcp2 from git.

**Comment by vszakats** [comment] 2022-06-27 00:45
rev5 got ngtcp2 and nghttp3 bumped to their new releases (all pre-releases at this point). This made this warning appear in the build:

x64
```
[00:16:32] vquic/ngtcp2.c:776:1: warning: missing field 'recv_rx_key' initializer [-Wmissing-field-initializers]
```

x86
```
[00:28:28] vquic/ngtcp2.c:776:1: warning: missing field 'recv_rx_key' initializer [-Wmissing-field-initializers]
[00:28:28] vquic/ngtcp2.c:1188:3: warning: incompatible function pointer types initializing 'nghttp3_acked_stream_data' (aka 'int (*)(struct nghttp3_conn *, long long, unsigned long long, void *, void *)') with an expression of type 'int (nghttp3_conn *, int64_t, size_t, void *, void *)' (aka 'int (struct nghttp3_conn *, long long, unsigned int, void *, void *)') [-Wincompatible-function-pointer-types]
[00:28:28]   cb_h3_acked_stream_data, /* acked_stream_data */
[00:28:28]   ^~~~~~~~~~~~~~~~~~~~~~~
```

HTTP/3 support is experimental, with interfaces in flux. These updates apparently broke compatibility with 7.83.1,
while introducing necessary changes for the upcoming curl release. Hopefully the 7.84.0 release will fix it.

**Comment by vszakats** [comment] 2022-06-27 11:20
With 7.84.0, the missing field warning is resolved, but [this one](https://ci.appveyor.com/project/curlorg/curl-for-win/builds/43996352#L19539) remained in the Intel 32-bit build (x64 is fine):
```
clang -I. -I../include -I"../../nghttp2/pkg/usr/local/include" -I"../../libssh2/pkg/usr/local/include" -I"../../libssh2/pkg/usr/local/win32" -I"../../nghttp3/pkg/usr/local/include" -I"../../ngtcp2/pkg/usr/local/include" -I"../../openssl-quic/pkg/usr/local/include" -I"../../zlib/pkg/usr/local" -I"../../brotli/pkg/usr/local/include" -I"../../libgsasl/pkg/usr/local/include" -I"../../libidn2/pkg/usr/local/include" -O3 --target=i686-w64-mingw32 --sysroot=/usr/i686-w64-mingw32 -fno-ident -DCURL_STATICLIB -DHAVE_ATOMIC -DHAVE_SIGNAL -DNDEBUG -DHAVE_STRTOK_R -DUSE_HEADERS_API -DHAVE_BOOL_T -DHAVE_STDBOOL_H -DHAVE_STRING_H -DHAVE_SETJMP_H -DHAVE_FTRUNCATE -D_FILE_OFFSET_BITS=64 -DSIZEOF_OFF_T=8 -DHAVE_LIBGEN_H -DHAVE_BASENAME -fno-asynchronous-unwind-tables -D_WIN32_WINNT=0x0501 -D_UCRT -DOPENSSL_SUPPRESS_DEPRECATED -DCURL_DISABLE_OPENSSL_AUTO_LOAD_CONFIG -DHAS_ALPN -DNGHTTP2_STATICLIB -DNGHTTP3_STATICLIB -DNGTCP2_STATICLIB -W -Wall -m32 -DBUILDING_LIBCURL -DCURL_WITH_MULTI_SSL -DUSE_NGHTTP2 -DUSE_LIBSSH2 -DHAVE_LIBSSH2_H -DUSE_NGHTTP3 -DUSE_NGTCP2 -DUSE_OPENSSL -DHAVE_OPENSSL_SRP -DUSE_TLS_SRP -DUSE_SCHANNEL -DHAVE_LIBZ -DHAVE_ZLIB_H -DHAVE_BROTLI -DUSE_GSASL -DUSE_LIBIDN2 -DUSE_WINDOWS_SSPI -DENABLE_IPV6 -DHAVE_LDAP_SSL -c vquic/vquic.c -o vquic/vquic.o
vquic/ngtcp2.c:1081:3: warning: incompatible function pointer types initializing 'nghttp3_acked_stream_data' (aka 'int (*)(struct nghttp3_conn *, long long, unsigned long long, void *, void *)') with an expression of type 'int (nghttp3_conn *, int64_t, size_t, void *, void *)' (aka 'int (struct nghttp3_conn *, long long, unsigned int, void *, void *)') [-Wincompatible-function-pointer-types]
  cb_h3_acked_stream_data, /* acked_stream_data */
  ^~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

/cc @tatsuhiro-t

**Comment by vszakats** [comment] 2022-06-27 12:08
`--http3` seems to be broken since 7.83.1_5, including 7.84.0. But with a slightly different effect in my case:
```
$ wine64 curl.exe -q -v --http3 https://curl.se/
*   Trying 2a04:4e42:a00::347:443...
* Connect socket 108 over QUIC to 2a04:4e42:a00::347:443
*  CAfile: /usr/local/etc/ca-certificates/cert.pem
*  CApath: none
*   Trying 151.101.193.91:443...
* Connect socket 112 over QUIC to 151.101.193.91:443
*  CAfile: /usr/local/etc/ca-certificates/cert.pem
*  CApath: none
*   Trying 151.101.193.91:443...
* Connect socket 116 over QUIC to 151.101.193.91:443
*  CAfile: /usr/local/etc/ca-certificates/cert.pem
*  CApath: none
*   Trying 151.101.193.91:443...
* Connect socket 120 over QUIC to 151.101.193.91:443
*  CAfile: /usr/local/etc/ca-certificates/cert.pem
*  CApath: none
[...repeated infinitely...]
```
Tested with <https://curl.se/windows/dl-7.84.0/curl-7.84.0-win64-mingw.zip>. (Same result with the `msvcrt` [build](https://ci.appveyor.com/project/curlorg/curl-for-win/builds/43997336/artifacts).)

**Comment by bagder** [comment] 2022-06-27 12:53
When I try the latest ngtcp2 and the latest curl on git, getting http3 from curl.se works just fine on my Debian Linux. I wonder if there's a recent windows related issue in ngtcp2 causing this?

**Comment by vszakats** [comment] 2022-06-27 14:09
Tried to build a curl 7.84.0 with previous ngtcp2/nghttp3 versions (including one patch retrofitted), but enough had changed, that it [no longer builds](https://ci.appveyor.com/project/curlorg/curl-for-win/builds/43998361).

**Comment by tatsuhiro-t** [comment] 2022-06-27 23:42
@vszakats when we had a discussion in #8978, did curl + ngtcp2 work for you?  If so, I think not much code is changed since then, we can git bisect to find the cause.

**Comment by vszakats** [comment] 2022-06-28 01:01
@tatsuhiro-t It did compile fine, without any warnings/errors, but I did not do functional tests at the time. That patch was for 7.84.0dev though, while the breakage happened with curl 7.83.1 stable, when I [upgraded](https://github.com/curl/curl-for-win/commit/88db86b9b1d17d06e5bd3bf938713ffce69fa298) ngtcp2 to 0.6.0 (from 0.5.0) and nghttp3 to 0.5.0 (from 0.4.1). 7.83.1 did not have the Linux GSO patch yet. So, to me tells it is unrelated to #8978.

**Comment by tatsuhiro-t** [comment] 2022-06-28 08:10
Thank you.  Looks like we need someone who can build and run + debug curl on windows.

**Comment by tatsuhiro-t** [comment] 2022-06-28 10:08
I tried wine, but it sends tiny UDP datagram and lots of 0 sized UDP datagram.  ngtcp2 produced 1200 bytes packet, so it does not make sense at all.  No idea wine works for UDP.

**Comment by vszakats** [comment] 2022-06-28 11:23
I managed to official 7.84.0 release on a real Windows machine, and I'm getting this error:
```
> curl.exe -V
curl 7.84.0 (x86_64-pc-win32) libcurl/7.84.0 OpenSSL/3.0.4 (Schannel) zlib/1.2.12 brotli/1.0.9 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.48.0 ngtcp2/0.6.0 nghttp3/0.5.0 libgsasl/1.10.0
Release-Date: 2022-06-27
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps matt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDN5 brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe TLS-SRP UnixSockets

> curl.exe -v -http3 https://curl.se/
Trying 151.101.193.91:443.
Connect socket 136 over QUIC to 151.101.193.91:443
CAfile: [...]\curl-ca-bundle.crt
CApath: none
* Failed to connect to curl.se port 443 after 255 ms: Failure when receiving data from the peer
Closine connection 0
curl: (56) Failed to connect to curl.se port 443 after 255 ms: Failure when receiving data from the peer
```

I could also find a `curl.exe` which I created on the day of #8978. It is built with 7.84.0dev + previous ngtcp2/nghttp3 releases, and it does work correctly on the same real Windows machine as above:
```
> curl.exe -V
curl 7.84.0-DEV (x86_64-pc-win32) libcur1/7.84.0-DEV OpenSSL/3.0.2 (Schannel) zlib/1.2.12 brotli/1.0.9 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.47.0 ngtcp2/0.5.0 nghttp3/0.4.1 libgsasl/1.10.0
Release-Date: [unreleased]
Protocols: dict file ftp Ftps gopher gophers http https imap imaps ldap ldaps matt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tfto
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe-init TLS-SRP UnixSockets
```
(Typos due to OCR-ing a screenshot, sorry about that.)

I'd rule out wine64 as a root-cause for this (at least with my system's WINE), though it breaks differently than real Windows.

**Comment by dkarpov1970** [comment] 2022-06-28 18:19
If it helps I can describe the problem on Windows:

The sever returns 
    CONNECTION_CLOSE (Transport) Error code: FRAME_ENCODING_ERROR
        Frame Type: CONNECTION_CLOSE (Transport) (0x000000000000001c)
        Error code: FRAME_ENCODING_ERROR (7)
        Frame Type: 9077
        Reason phrase Length: 0
        Reason phrase:

My client seems to send bad Tls data, which Wireshark marks as "Unknown" parts.
Some of that "Unknown" parts contain ALPN stuff:

I am attaching a Wireshark trace with the failed connection.

[bad_quic_connection.zip](https://github.com/curl/curl/files/9003722/bad_quic_connection.zip)

**Comment by dkarpov1970** [comment] 2022-06-28 23:54
@tatsuhiro-t  I bisected the problem and it looks like the regression occurred in https://github.com/ngtcp2/ngtcp2/pull/445
in commit: https://github.com/ngtcp2/ngtcp2/pull/445/commits/8e7b3d530da80effc63fa217dafd9e9d6d091d4c

**Comment by tatsuhiro-t** [comment] 2022-06-29 00:07
Thank you. I'll look into it.

**Comment by dkarpov1970** [comment] 2022-06-29 01:05
@tatsuhiro-t  The problem was identified. Small typo in one change.  The patch is attached.
[0001-Fixed-error-in-ngtcp2_htons.zip](https://github.com/curl/curl/files/9006421/0001-Fixed-error-in-ngtcp2_htons.zip)
.

**Comment by vszakats** [comment] 2022-06-29 01:54
I can confirm @dkarpov1970's patch fixed it. Test build available here: https://ci.appveyor.com/project/curlorg/curl-for-win/builds/44018111/artifacts

**Comment by tatsuhiro-t** [comment] 2022-06-29 09:06
Thank you all.  Patch has been merged.  Now I can successfully run mingw64 curl on wine to access nghttp2.org.  It still sends a lost of 0 bytes UDP datagrams.  That is probably caused by something else, maybe wine runtime?  Note that you need check server log to detect this datagrams, or run wireshark.

**Comment by tatsuhiro-t** [comment] 2022-06-29 09:25
It looks like this 0 bytes UDP datagram is caused by tcpkeepalive.

**Comment by tatsuhiro-t** [comment] 2022-06-29 11:00
Even after applying the ngtcp2 patch, I sometimes get SOCKERRNO == 10061 (WSAECONNREFUSED) from recvfrom.
Just ignoring it will complete QUIC handshake and connection succeeds.

**Comment by vszakats** [comment] 2022-06-29 12:58
The fix is now included in 7.84.0_1 (and newer), downloadable from <https://curl.se/windows/>.

**Comment by bagder** [comment] 2022-06-30 06:32
Thanks everyone, this issue is then considered fixed!

**Closed by bagder** 2022-06-30 06:32 UTC
Labels: HTTP/3

**Comment by shithappens2016** [comment] 2022-07-01 00:52
@gvanem @bagder @vszakats @tatsuhiro-t @dkarpov1970 

Thanks guys.  and `https://curl.se/windows/dl-7.84.0_3/curl-7.84.0_3-win64-mingw.zip` seems to be the `ucrt` version, where can I download the `msvcrt` version?
