### ISSUE TITLE
curl: option --data-urlencode: out of memory

### ISSUE THREAD

**Issue by JohnGoebel2** [curl/curl#5620] opened 2020-06-27 06:40 UTC
### I did this
curl --user sk_test_fG: --write-out "xresponsecodex %{response_code}" --globoff  --header "Stripe-Version: 2017-04-06" --silent --data-urlencode "source=tok_Yg" --data-urlencode "metadata[company]=" https://api.stripe.com/v1/customers/cus_HXa/sources
### Expected result
{
  "error": {
    "message": "Invalid API Key provided: sk_test_fG",
    "type": "invalid_request_error"
  }
}

### Result
curl: option --data-urlencode: out of memory
### Changes to get Expected Result
replace **--data-urlencode** with **--data** 
remove either **--data-urlencode** and its data
### Work around
revert to 7.69.1
### curl/libcurl version
curl 7.71.0 (x86_64-pc-linux-gnu) libcurl/7.71.0 OpenSSL/1.1.1g zlib/1.2.3.3
Release-Date: 2020-06-24
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets

curl 7.69.1 (x86_64-pc-linux-gnu) libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.3.3
Release-Date: 2020-03-11
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets
### operating system
Linux forrests-web 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment] 2020-06-27 10:25
Very strange. I cannot reproduce with current git master nor 7.70.0 and I also tried with 7.68.0 but they all worked the same way for me.

**Comment by OldTimer571** [comment] 2020-06-28 20:54
@JohnGoebel2
(using curl 7.71.0 (x86_64-pc-linux-gnu) libcurl/7.71.0 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.3.0 libpsl/0.20.1 (+libidn2/2.0.4) libssh2/1.8.2 nghttp2/1.41.0 librtmp/2.3)

No clear idea why this is happening at the moment, however, if a SPACE is added after [company]= then the url should complete sucessfully?

As in:-
--data-urlencode "metadata[company]= "

**Comment by bagder** [comment] 2020-06-28 21:54
Does running it with valgrind give any more clues?

**Comment by gvanem** [comment] 2020-06-29 07:53
I get the same `out of memory` on Win32/MSVC. But patching to:
```diff
--- a/tool_getparam.c 2020-06-09 16:35:00
+++ b/tool_getparam.c 2020-06-29 07:50:05
@@ -1380,7 +1380,7 @@
             size = strlen(postdata);
         }

-        if(!postdata) {
+        if(!postdata || !*postdata) {
           /* no data from the file, point to a zero byte string to make this
              get sent as a POST anyway */
           postdata = strdup("");
```

fixed it (w/o really knowing why).

**Comment by bagder** [comment] 2020-06-29 08:20
Hm, didn't perhaps 32defc31970ddd0 already fix this issue in master?

**Comment by gvanem** [comment] 2020-06-29 08:49
Yes, it did.

**Comment by bagder** [comment] 2020-06-29 11:23
thanks @gvanem! 

@JohnGoebel2, this issue is a regression in 7.71.0. You can try the current master and the issue should be gone. We will release 7.71.1 on July 1st that will contain this fix.

**Comment by JohnGoebel2** [comment] 2020-06-29 23:12
Thank you all very much for your help. I'll wait for 7.71.1, I have 
great faith if you say it's fixed it is.

**Comment by bagder** [comment] 2020-06-30 09:23
Ok, thanks. Closing this now then as I believe this is fixed already in master.

**Closed by bagder** 2020-06-30 09:23 UTC
Labels: cmdline tool
