### ISSUE TITLE
curl: could detect deflated content and notice the user about the --compressed flag

### ISSUE THREAD

**Issue by perlun** [curl/curl#2062] opened 2017-11-08 19:57 UTC
### I did this

```
$ curl -v http://some-server/some-path
> GET /some-path HTTP/1.1
> Host: some-server
> User-Agent: curl/7.47.1
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Server: nginx/1.12.2
< Date: Wed, 08 Nov 2017 19:51:39 GMT
< Content-Type: text/plain
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Origin,Accept-Encoding
< X-Content-Type-Options: nosniff
< X-Robots-Tag: noindex
< Content-Encoding: deflate
< X-Upstream: 10.11.1.12.13:8000
<
* Connection #0 to host some-server intact
��+I-�K�Q(N-*K-RH-*�/��IM,NUH�HM�V(�H�I�����
```

(The deflated content is being shown as-is.)

### I expected the following

I expected it to behave like this, since I know that's how `curl` works currently. 😉 But it would be really _nice_ if `curl` would detect this (slightly misbehaving) server which forces deflated content on all requests, and auto-deflate it.

The reason it's forcibly deflated is because the `nginx` proxy adds the `Accept-Encoding "deflate, gzip"` header on all requests, to ensure that content is always encoded whenever possible. (We opt-out certain clients, like MSIE 1-6 which cannot handle this, but try to have it enabled as much as possible.)

Adding `--compressed` makes it decode the response without problems, but as stated, it would be nice if it could detect this based on the `Content-Encoding` being returned here.

### curl/libcurl version

```
$ curl -V
curl 7.47.1 (x86_64-apple-darwin15.3.0) libcurl/7.47.1 SecureTransport zlib/1.2.11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets
```

### operating system
macOS High Sierra

**Comment by bagder** [comment] 2017-11-08 23:38
> it would be nice if it could detect this based on the Content-Encoding being returned here.

Yes, but... you then presume that all users want compressed data automatically uncompressed on download. I've talked to several users with use cases where they download compressed data for later use so such a move would not be a welcome change to those.

All since the beginning of the curl project, the default curl request has been very basic and only does exactly what you ask for. You then add options to make curl do more than just the basic stuff. I'm inclined to lean towards that adding automatic decompression by default is crossing that line of doing slightly more than what's been asked.

As a work-around, you can basically get what you want by adding `--compressed` in your .curlrc file.

Finally: [curl doesn't spew binary anymore!](https://daniel.haxx.se/blog/2017/06/17/curl-doesnt-spew-binary-anymore/)

**Comment by perlun** [comment] 2017-11-10 09:40
> Yes, but... you then presume that all users want compressed data automatically uncompressed on download. I've talked to several users with use cases where they download compressed data for later use so such a move would not be a welcome change to those.

Point. I _do_ consider that an edgy case, albeit completely valid; however, I have absolutely zero statistical evidence to substantiate that claim. 😃 

> Finally: curl doesn't spew binary anymore!

That's great news! As can be seen, the version I am running is somewhat older.

> I'm inclined to lean towards that adding automatic decompression by default is crossing that line of doing slightly more than what's been asked.

I understand these valid points as well. How about this then: would you be willing to live with a feature that _detects_ the compressed content, and emits a message like "Deflated content detected. To decompress this content, use the --compressed parameter"? That way, we keep the KISS principle, and at the same time try to make it somewhat more helpful for our clueless users (like me. 😉)

(All this is of course presuming that detecting deflated content is reasonably easy. I don't know if this is the case or not.)

**Comment by monnerat** [comment] 2017-11-10 20:02
In a perfect world, a proxy should decompress if it is responsible for the request's `Accept-Encoding` header. Another tricky possibility (ok in curl but not supported by all clients) would be (still for the proxy) to move the `Content-Encoding` parameters to the `Transfer-Encoding` header. IMHO curl is on the right side.

**Comment by bagder** [comment] 2017-11-11 13:18
> I think it's reasonably to assume that if it's being printed to STDOUT, and STDOUT is a TTY, you do want it decompressed. Do you agree?

I think that's a reasonable guess, yes. Or that the user forgot to use an option to save the output correctly...

> would you be willing to live with a feature that detects the compressed content, and emits a message like "Deflated content detected"...

That would require added code in the curl tool for that detection, and it would then need to check what compressions the current libcurl support since gzip is not the only possibility these days.

Are you suggesting this output when passing the output to the terminal only? I don't think I would object to something like that.

**Comment by perlun** [comment] 2017-11-17 13:26
> In a perfect world, a proxy should decompress if it is responsible for the request's Accept-Encoding header

Not necessarily. Think "reverse proxy" and I think you'll understand what I mean. The reverse proxy might be near the upstream server (zero to low network latency), whereas the leaf client might be at the other end of the world on a slow GPRS link or whatever (where compression makes sense.)

>> I think it's reasonably to assume that if it's being printed to STDOUT, and STDOUT is a TTY, you do want it decompressed. Do you agree?
 > I think that's a reasonable guess, yes. Or that the user forgot to use an option to save the output correctly...

😄 There's always that possibility indeed. It's not easy to _know_ for certain these things.

> That would require added code in the curl tool for that detection, and it would then need to check what compressions the current libcurl support since gzip is not the only possibility these days.
> 
> Are you suggesting this output when passing the output to the terminal only? I don't think I would object to something like that.

Yes - only when passing the output to the terminal.

I suggest we leave the issue open until someone has a chance to look into this then. If you or anyone else want to approximately outline the details like how the "check what compressions are supported" etc can be done (just a high-level, rough pointer is enough) that would be useful, to help the implementation if/when it gets done.

**Comment by monnerat** [comment] 2017-11-17 15:40
> The reverse proxy might be near the upstream server (zero to low network latency), whereas the leaf client might be at the other end of the world on a slow GPRS link or whatever (where compression makes sense.)

Content-Encoding is meant to be an end-to-end compression controlled by the client request's accept encoding header. If hop-by-hop compression is to be considered, Transfer-Encoding should be used.

**Comment by bagder** [comment] 2017-12-07 16:58
This is not a bug, closing.

**Closed by bagder** 2017-12-07 16:58 UTC
Labels: cmdline tool, enhancement
