### ISSUE TITLE
7.61.1 build error with mingw

### ISSUE THREAD

**Issue by KangLin** [curl/curl#3236] opened 2018-11-05 07:20 UTC
### I did this
I am build the libcurl in mingw. error information:

D:/Source/curl/build_windows_mingw/src/tool_hugehelp.c:1:2: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token
 D:/msys64/* built-in manual is disabled, blank function */
  ^
In file included from C:/Qt/Qt5.11.1/Tools/mingw530_32/i686-w64-mingw32/include/_mingw.h:275:0,
                 from C:/Qt/Qt5.11.1/Tools/mingw530_32/i686-w64-mingw32/include/windows.h:9,
                 from C:/Qt/Qt5.11.1/Tools/mingw530_32/i686-w64-mingw32/include/winsock2.h:23,
                 from D:/Source/curl/include/curl/system.h:411,
                 from D:/Source/curl/include/curl/curl.h:38,
                 from D:/Source/curl/lib/curl_setup.h:145,
                 from D:/Source/curl/src/tool_setup.h:36,
                 from D:/Source/curl/src/tool_hugehelp.h:24,
                 from D:/Source/curl/build_windows_mingw/src/tool_hugehelp.c:2:
C:/Qt/Qt5.11.1/Tools/mingw530_32/i686-w64-mingw32/include/vadefs.h:31:11: error: unknown type name '__gnuc_va_list'
   typedef __gnuc_va_list va_list;
           ^

### I expected the following
I suggest adding mingw to compile in ci

### curl/libcurl version
curl-7_61_1
[curl -V output]

### operating system
windows 10

$ uname -a
MSYS_NT-10.0 DESKTOP-RFFCG63 2.11.1(0.329/5/3) 2018-09-10 14:19 x86_64 Msys
GCC: 5.3.0

**Comment by KangLin** [comment] 2018-11-05 08:12
The openssl is build 

> 
> 
> Others have manged to build this version fine with mingw. In fact, our [official curl builds for Windows](https://curl.haxx.se/windows/) are built with mingw. This would suggest maybe something went wrong with your curl build or your mingw setup?


Is openssl compiled together?

**Comment by MarcelRaad** [comment] 2018-11-05 08:32
That's probably the same as https://github.com/curl/curl/issues/3125? I actually wanted to add MinGW to AppVeyor, but this very issue was the blocker.
The autotools build works fine, though.

**Comment by bagder** [comment] 2018-11-05 08:48
@KangLin ah, did you use cmake? If so it indeed looks like a duplicate of #3125 ...

**Comment by KangLin** [comment] 2018-11-05 08:50
@bagder Yes

**Comment by KangLin** [comment] 2018-11-05 08:50
https://ci.appveyor.com/project/KangLin/rabbitim/builds/20048669

**Comment by KangLin** [comment] 2018-11-05 08:52
https://github.com/KangLin/RabbitThirdLibrary

**Comment by bagder** [comment] 2018-11-05 08:55
Duplicate of #3125

**Closed by bagder** 2018-11-05 08:55 UTC
Labels: Windows, build
