### ISSUE TITLE
Resolve hostname before matching against no_proxy env var

### ISSUE THREAD

**Issue by patrycjadziubek** [curl/curl#4759] opened 2019-12-26 05:53 UTC
Hello,

I noticed that when curl is used against a short name (hostname or service name), it does not respect proxy variables. Curl will not connect to the proxy if the URL doesn't use a string which matches one of the list provided by the no_proxy env variable. If the short name doesn't contain that string, curl connects to the proxy and asks for the full request without doing a lookup first. This results in "curl: (5) Could not resolve proxy: <proxy name>; Name or service not known" error.

I had a look at the code and it seems to be an expected behaviour. Could some kind of a flag be added to curl in order to mitigate this if it doesn't go against some RFCs? I.e. "--resolve-first". 

Curl version: curl-7.29.0-54.el7.x86_64. Tested the latest one too - same behaviour.

**Comment by jay** [comment] 2019-12-26 06:56
I can't reproduce, NO_PROXY works here with a short hostname.
~~~
set http_proxy=localhost:8888
set no_proxy=TEST
curl -v http://TEST
~~~

~~~
curl 7.66.0-DEV (i386-pc-win32) libcurl/7.66.0-DEV OpenSSL/1.0.2t
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Debug HTTPS-proxy IPv6 Largefile NTLM SSL
~~~

**Comment by patrycjadziubek** [comment] 2019-12-26 10:12
This is situation I encountered in OpenShift and Kubernetes inside a container, but was able to reproduce on a simple RHEL machine (see the example below).

```
cat /etc/resolv.conf
nameserver xx.xx.xx.xx
search xxx.svc.cluster.local svc.cluster.local cluster.local xxx.yyy.zzz.com
options ndots:5

export NO_PROXY=.local
export no_proxy=.local
export http_proxy=http://proxytest.com
export HTTPS_PROXY=http://proxytest.com
export https_proxy=http://proxytest.com
export HTTP_PROXY=http://proxytest.com

sh-4.2$ curl -v serviceX:8080
* Could not resolve proxy: http://proxytest.com; Name or service not known
* Closing connection 0

sh-4.2$ curl -vvv  serviceX.svc.cluster.local:8080
[...]
>
< HTTP/1.1 200 OK
```

Based on /etc/resolv.conf manual the search domain will be appended in a sequential order to the short hostname (ndots <5). So in this example it will reach .local so that the short name will be resolvable and will match the no_proxy setting. Hence it should not be proxied.

**Comment by jay** [comment] 2019-12-26 17:55
Ok I don't think that's a bug. I think adding a feature for that is unlikely but I will leave open to gather feedback and see what others think.

**Comment by KrE80r** [comment] 2019-12-26 18:33
Is there an RFC/standard around this bit?

Should the no_proxy matching be done before or after appending the search domains, and - accordingly - dns resolution ?

**Comment by bagder** [comment] 2020-01-03 15:18
That "appending of search domains" is done by the resolver function, not by curl, so we really cannot do the comparison or exclusion with that part taken into account.

**Comment by bagder** [comment] 2020-01-05 20:33
This 1. asks for a feature (and we don't keep feature requests around in the issue tracker) and even 2. a feature we can't provide. Closing.

**Closed by bagder** 2020-01-05 20:33 UTC
Labels: connecting & proxies, feature-request
