### ISSUE TITLE
`curl --include --fail --show-error` does not show response headers

### ISSUE THREAD

**Issue by jamshid** [curl/curl#6911] opened 2021-04-19 03:16 UTC
### I did this

Is there *any* way to see the response headers when using `-f` ? It seems `-i` is **ignored**.

```
 % curl --include --fail --show-error -XPOST https://www.cnn.com/
curl: (22) The requested URL returned error: 403 
```

### I expected the following
I use `-f` in scripts for error handling, but when I get an error I really need to be able to diagnose it and response headers are critical for that. E.g. I'd like to see this output with `--fail` if I use `--include`.
```
curl: (22) The requested URL returned error: 403 
HTTP/2 403 
content-type: application/xml
server: Microsoft-HTTPAPI/2.0
...
```
I even tried an explicit `-D` but that is also **ignored**. 
```
 % curl -D - --include --fail --show-error -XPOST https://www.cnn.com/
curl: (22) The requested URL returned error: 403 
```
### curl/libcurl version

UPDATE: here is version I'm using, sorry had bad copy&paste originally.
```
% curl -V
curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```
### operating system

macOS Big Sur 11.2.3 but applies to any OS

**Comment by bagder** [comment] 2021-04-19 06:10
You don't show which curl version you use. I cannot reproduce this issue with a modern curl version.

**Comment by jay** [comment] 2021-04-19 07:41
reproducible in a7696c7
not reproducible in e38f4b7
(I didn't have time to do a full bisect)

**Comment by bagder** [comment] 2021-04-19 07:47
Right, see ab525c059eb44883d

**Comment by jamshid** [comment] 2021-04-19 15:57
Thanks, I didn't realize later curl fixed this. Okay I can use the curl container in my script so I get an error exit code and I see the response headers, either with `-D -` or `--include`. 
```
% docker run curlimages/curl --include --fail --show-error -XPOST https://www.cnn.com/ 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/2 403 
content-type: application/xml
server: Microsoft-HTTPAPI/2.0
x-ms-request-id: 01e100eb-b01e-007b-4333-3598b8000000
...
% echo $?
22
```
But is there any way to avoid the progress bar, which even with simple `-#` messes up script output? `--silent` does not show _anything_, which seems like a bug since docs say
> Use -S, --show-error in  addition  to  this  option  to  disable progress meter but still show error messages.
```
% docker run curlimages/curl -D - --fail --silent --show-error -XPOST https://www.cnn.com/
(no output at all)
% echo $?
22
```

**Comment by jay** [comment] 2021-04-19 18:31
> But is there any way to avoid the progress bar, which even with simple `-#` messes up script output? `--silent` does not show _anything_, which seems like a bug since docs say
> 
> > Use -S, --show-error in  addition  to  this  option  to  disable progress meter but still show error messages.
> 
> ```
> % docker run curlimages/curl -D - --fail --silent --show-error -XPOST https://www.cnn.com/
> (no output at all)
> % echo $?
> 22
> ```

try this
docker run -i --log-driver=none -a stdin -a stdout -a stderr curlimages/curl -D - --fail --silent --show-error -XPOST https://www.cnn.com/

**Comment by jamshid** [comment] 2021-04-19 20:18
Thank you @jay and sorry about this docker red herring, `curl --silent --show-error` **is** working as expected. 

---

Btw it's very weird, in my env (docker client on mac talking to remote docker server on mac via either ssh or tcp :2376) I have to use `docker run -i` to see the curl output when connecting via **tcp**, but that's _not_ necessary when using the **local** docker or connecting to the remote via **ssh** instead of tcp.

```
% DOCKER_HOST= DOCKER_CERT_PATH= DOCKER_TLS_VERIFY= docker run curlimages/curl -D /tmp/xx --fail --silent --show-error -XPOST https://www.cnn.com/
curl: (22) The requested URL returned error: 403

% DOCKER_HOST=ssh://192.168.1.50 docker run curlimages/curl -D /tmp/xx --fail --silent --show-error -XPOST https://www.cnn.com/
curl: (22) The requested URL returned error: 403

% DOCKER_HOST=tcp://192.168.1.50:2376 DOCKER_CERT_PATH=... DOCKER_TLS_VERIFY=1 docker run curlimages/curl -D /tmp/xx --fail --silent --show-error -XPOST https://www.cnn.com/
(nothing output!)

% DOCKER_HOST=tcp://192.168.1.50:2376 DOCKER_CERT_PATH=... DOCKER_TLS_VERIFY=1 docker run -i curlimages/curl -D /tmp/xx --fail --silent --show-error -XPOST https://www.cnn.com/
curl: (22) The requested URL returned error: 403
```

**Comment by jay** [comment] 2021-04-19 20:38
I don't know but it's surely related to docker and not curl. If you find out let us know.

Closing since the reported issue was already fixed.

Ref: https://github.com/curl/curl/issues/6408

**Closed by jay** 2021-04-19 20:38 UTC
Labels: HTTP, cmdline tool
