### ISSUE TITLE
Windows build fails because vssh directory is not created

### ISSUE THREAD

**Issue by zedalaye** [curl/curl#4515] opened 2019-10-21 14:19 UTC
# I did this

```
git clone <curl>
git checkout curl-7_66_0
cd curl
buildconf.bat
cd winbuild
nmake /f Makefile.vc mode=static machine=x86
```

### I expected the following

libcurl_a.lib is built

### but 

libcurl_a.lib was not built because linked could not find vssh\libssh2.obj

### So I fixed the build

I patched winbuild\MakefileBuild.vc this way :

```diff
 winbuild/MakefileBuild.vc | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/winbuild/MakefileBuild.vc b/winbuild/MakefileBuild.vc
index b5742e109..07acc6a9a 100644
--- a/winbuild/MakefileBuild.vc
+++ b/winbuild/MakefileBuild.vc
@@ -560,6 +560,7 @@ $(LIB_DIROBJ):
 	@if not exist "$(LIB_DIROBJ)\vauth" mkdir $(LIB_DIROBJ)\vauth
 	@if not exist "$(LIB_DIROBJ)\vtls" mkdir $(LIB_DIROBJ)\vtls
 	@if not exist "$(LIB_DIROBJ)\vquic" mkdir $(LIB_DIROBJ)\vquic
+	@if not exist "$(LIB_DIROBJ)\vssh" mkdir $(LIB_DIROBJ)\vssh
 
 $(CURL_DIROBJ):
 	@if not exist "$(CURL_DIROBJ)" mkdir $(CURL_DIROBJ)
@@ -581,6 +582,9 @@ $(CURL_DIROBJ):
 {$(LIBCURL_SRC_DIR)\vquic\}.c{$(LIB_DIROBJ)\vquic\}.obj:
 	$(CURL_CC) $(CFLAGS) /Fo"$@"  $<
 
+{$(LIBCURL_SRC_DIR)\vssh\}.c{$(LIB_DIROBJ)\vssh\}.obj:
+	$(CURL_CC) $(CFLAGS) /Fo"$@"  $<
+
 $(LIB_DIROBJ)\libcurl.res: $(LIBCURL_SRC_DIR)\libcurl.rc
 	$(RC) $(RC_FLAGS)
 ```

**Comment by bagder** [comment] 2019-10-21 14:51
Duplicate of #4322 - already fixed

**Closed by bagder** 2019-10-21 14:51 UTC
