### ISSUE TITLE
trying to build curl in windows and it fails with LINK : fatal error LNK1181 cant find '..\builds\libcurl-vc-x64-release-static-ipv6-sspi-obj-lib\vssh\libssh2.obj'

### ISSUE THREAD

**Issue by jcbritobr** [curl/curl#4351] opened 2019-09-14 02:43 UTC
curl fails in win 10 64 bits, ms visual c++ 17 build tools with

LINK : fatal error LNK1181 cant find '..\builds\libcurl-vc-x64-release-static-ipv6-sspi-obj-lib\vssh\libssh2.obj'

command line in msvc++ 64 bits prompt:
nmake /f Makefile.vc mode=static MACHINE=x64

Seems the configuration always put libssh2 opt on in build configuration

**Comment by bagder** [comment] 2019-09-14 17:49
Duplicate of #4322 fixed in git master already

**Closed by bagder** 2019-09-14 17:49 UTC
