### ISSUE TITLE
C-ares Compile Error With Curl.

### ISSUE THREAD

**Issue by kevinlovejia** [curl/curl#4440] opened 2019-09-29 09:56 UTC
I try to use c-ares in libcurl. After follow 4 steps and got the error msg.
```
/root/Desktop/CC_TOOLS/bin/../lib/gcc/mipsel-openwrt-linux-uclibc/4.8.3/../../../../
mipsel-openwrt-linux-uclibc/bin/ld: warning: libcares.so.2, needed by 
../lib/.libs/libcurl.so, not found (try using -rpath or -rpath-link)
../lib/.libs/libcurl.so: undefined reference to `ares_getsock'
../lib/.libs/libcurl.so: undefined reference to `ares_set_servers_csv'
../lib/.libs/libcurl.so: undefined reference to `ares_gethostbyname'
../lib/.libs/libcurl.so: undefined reference to `ares_set_local_ip6'
../lib/.libs/libcurl.so: undefined reference to `ares_library_init'
../lib/.libs/libcurl.so: undefined reference to `ares_dup'
../lib/.libs/libcurl.so: undefined reference to `ares_destroy'
../lib/.libs/libcurl.so: undefined reference to `ares_init'
../lib/.libs/libcurl.so: undefined reference to `ares_process_fd'
../lib/.libs/libcurl.so: undefined reference to `ares_library_cleanup'
../lib/.libs/libcurl.so: undefined reference to `ares_cancel'
../lib/.libs/libcurl.so: undefined reference to `ares_strerror'
../lib/.libs/libcurl.so: undefined reference to `ares_set_local_ip4'
../lib/.libs/libcurl.so: undefined reference to `ares_version'
../lib/.libs/libcurl.so: undefined reference to `ares_set_local_dev'
../lib/.libs/libcurl.so: undefined reference to `ares_timeout'
collect2: error: ld returned 1 exit status
```
Operation System:
```
name: "ubuntu"
     version: 14.04.5 LTS
     type: "vmware"
     arhitecture:"x86_64"
mipsel-openwrt-linux-gcc:    version: 4.8.3
openssl:                     version: 1.1.1 pre8
libcurl:                     version: 7.61.0
zlib:                        version: 1.2.11
c-ares:                      version: 1.15.0 (1.14.0, 1.10.0 are same error)
```
Prepare Work.
```
Step 1. openssl
./Configure --cross-compile-prefix=mipsel-openwrt-linux- no-async \
linux-mips32 --prefix=/home/wei/openssl
make clean && make && make install
Step 2. c-ares
./configure --host=mipsel-openwrt-linux --prefix=/home/wei/c-ares \
--with-random=/dev/urandom
make clean && make && make install
Step 3. zlib
export CC=mipsel-openwrt-linux-gcc 
./configure --prefix=/home/wei/zlib
make clean && make && make install
Step 4. curl
./configure --enable-ares=/home/wei/c-ares --with-zlib=/home/wei/zlib \
--with-ssl=/home/wei/openssl --host=mipsel-openwrt-linux \
CC=mipsel-openwrt-linux-gcc --with-random=/dev/urandom \
LDFLAGS="-lpthread -ldl"
make clean && make && make install
```
After Step 4 `./configure...`, I got below.

  curl version:     7.61.0
  Host setup:       mipsel-openwrt-linux-gnu
  Install prefix:   /usr/local
  Compiler:         mipsel-openwrt-linux-gcc
  **SSL support:      enabled (OpenSSL)**
  SSH support:      no      (--with-libssh2)
  **zlib support:     enabled**
  brotli support:   no      (--with-brotli)
  GSS-API support:  no      (--with-gssapi)
  TLS-SRP support:  enabled
  **resolver:         c-ares**
  IPv6 support:     enabled
  Unix sockets support: enabled
  IDN support:      no      (--with-{libidn2,winidn})
  Build libcurl:    Shared=yes, Static=yes
  Built-in manual:  enabled
  --libcurl option: enabled (--disable-libcurl-option)
  Verbose errors:   enabled (--disable-verbose)
  SSPI support:     no      (--enable-sspi)
  ca cert bundle:   no
  ca cert path:     no
  ca fallback:      no
  LDAP support:     no      (--enable-ldap / --with-ldap-lib / --with-lber-lib)
  LDAPS support:    no      (--enable-ldaps)
  RTSP support:     enabled
  RTMP support:     no      (--with-librtmp)
  metalink support: no      (--with-libmetalink)
  PSL support:      no      (libpsl not found)
  HTTP2 support:    disabled (--with-nghttp2)
  Protocols:        DICT FILE FTP FTPS GOPHER HTTP HTTPS IMAP IMAPS POP3 POP3S RTSP SMB SMBS SMTP SMTPS TELNET TFTP

**Comment by bagder** [comment] 2019-09-29 10:11
This surprises me. I build with c-ares like this almost on a daily basis and this has worked perfectly for many years. Also, configure detected it nicely but it seems that it still didn't provide the correct `-L` or something in the generated Makefile.

If you run make as `make V=1` you'll get all the command lines shown and you can inspect the ld line and all its flags. Does it provide the -L flag for the c-ares dir?

**Comment by kevinlovejia** [comment] 2019-09-30 01:18
Thanks @bagder . I run make V=1 in curl, I got some warnning.
```
/root/Desktop/CC_TOOLS/bin/../lib/gcc/mipsel-openwrt-linux-uclibc/4.8.3/../../../../mipsel-
openwrt-linux-uclibc/bin/ld: skipping incompatible /home/wei/openssl/lib/libssl.so when 
searching for -lssl
/root/Desktop/CC_TOOLS/bin/../lib/gcc/mipsel-openwrt-linux-uclibc/4.8.3/../../../../mipsel-
openwrt-linux-uclibc/bin/ld: skipping incompatible /home/wei/openssl/lib/libssl.a when 
searching for -lssl
/root/Desktop/CC_TOOLS/bin/../lib/gcc/mipsel-openwrt-linux-uclibc/4.8.3/../../../../mipsel-
openwrt-linux-uclibc/bin/ld: skipping incompatible /home/wei/openssl/lib/libcrypto.so 
when searching for -lcrypto
/root/Desktop/CC_TOOLS/bin/../lib/gcc/mipsel-openwrt-linux-uclibc/4.8.3/../../../../mipsel-
openwrt-linux-uclibc/bin/ld: skipping incompatible /home/wei/openssl/lib/libcrypto.a 
when searching for -lcrypto
../lib/.libs/libcurl.so: warning: gethostbyname is obsolescent, use getnameinfo() instead.
```
I don't know wether this is the reason. Before I compile the openssl, I delete two `-m64`
in Makefile, because the cross compile tools is 32 bit.
BTW, c-ares support `-L`, I can find `-L` in `make --help` in c-ares.

**Comment by bagder** [comment] 2019-09-30 07:20
None of those warnings were about c-ares, were they?

If you check the actual command line that invokes the final link command that links curl, does it contain a -L to the c-ares directory or not?

**Comment by kevinlovejia** [comment] 2019-09-30 07:31
I can find some msg in `Makefile` of curl.
```
LD = /root/Desktop/CC_TOOLS/mipsel-openwrt-linux-uclibc/bin/ld
LDFLAGS = -lpthread -ldl -L/home/wei/zlib/lib -L/home/wei/openssl/lib \
-L/home/wei/c-ares/lib
```

**Comment by kevinlovejia** [comment] 2019-09-30 10:01
I tried the curl 7.67.0-DEV. I got the different error. Am I need to use the lastest openssll?
```
vtls/openssl.c: In function 'ossl_connect_step1':
vtls/openssl.c:2690:3: error: implicit declaration of function 'SSL_CTX_set_post_handshake_auth' [-Werror=implicit-function-declaration]
   SSL_CTX_set_post_handshake_auth(BACKEND->ctx, 1);
   ^
cc1: some warnings being treated as errors
make[2]: *** [vtls/libcurl_la-openssl.lo] Error 1
make[2]: Leaving directory `/home/wei/curl-master/lib'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/wei/curl-master/lib'
make: *** [all-recursive] Error 1
```

**Comment by bagder** [comment] 2019-09-30 11:58
> -L/home/wei/c-ares/lib

And there's a libcares.so* or libcares.a file (or both) in there? Then it sounds as if you've manged to get c-ares libs put there that aren't okay to your linker.

> error: implicit declaration of function 'SSL_CTX_set_post_handshake_auth

(this is a different problem and thus not actually related ot the c-ares issue and it should strictly not be handled in the same issue)

The use of `SSL_CTX_set_post_handshake_auth()` is protected by an #ifdef that makes sure it is only used if you build with a new enough OpenSSL present. You getting this link problem indicates that you have a funny mix of new include files but older lib? The warnings from before about your libssl might be relevant then I guess.

**Comment by kevinlovejia** [comment] 2019-10-04 01:12
@bagder , I'm sorry about the late reply. I can find the libcares.so* or libcares.a file there.
```
root@ubuntu:/home/wei/c-ares/lib# ls
libcares.a   libcares.so    libcares.so.2.1.0  libcares.so.2.3.0
libcares.la  libcares.so.2  libcares.so.2.2.0  pkgconfig
```

**Comment by kevinlovejia** [comment] 2019-10-04 03:55
I update the openssl to the master branch, `SSL_CTX_set_post_handshake_auth` the error won't come out. And I still can't make finish curl with the 
```
/root/Desktop/CC_TOOLS/bin/../lib/gcc/mipsel-openwrt-linux-uclibc/4.8.3/../../../../mipsel-openwrt-linux-uclibc/bin/ld: warning: libcares.so.2, needed by ../lib/.libs/libcurl.so, not found (try using -rpath or -rpath-link)
../lib/.libs/libcurl.so: undefined reference to `ares_process_fd'
../lib/.libs/libcurl.so: undefined reference to `ares_set_local_ip6'
...
```
I used the newest version.
OpenSSL 3.0.0-dev
curl 7.67.0-DEV
c-ares 1.15.0
zlib 1.2.11

**Comment by bagder** [comment] 2019-10-05 10:12
This is still a problem with your setup. As the [OpenSSL docs say](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_post_handshake_auth.html): "SSL_set_post_handshake_auth() functions were added in OpenSSL 1.1.1.". You seems to link with the wrong OpenSSL lib and probably wrong c-ares too. `ares_process_fd()` was added already in c-ares 1.4.0 back in 2007...

**Comment by kevinlovejia** [comment] 2019-10-08 06:16
Hi @bagder. I try this #2203 use the pkg-config and add `-Wl,-rpath -Wl,/home/wei/c-ares/lib` in `Makefile` LDFLAGS, but the same issue.
When I deleted the folder directory (/home/wei/c-ares/lib) of c-ares make install, in curl `make` will see the same issue too. I think curl `configure` find the c-ares, but `Makefile` can't. Should I use `-rpath or -rpath-link`? Where shall I add them? THANKS.

**Comment by bagder** [comment] 2019-10-13 09:09
This issue gets complicated because you keep changing what the problem is and you add unrelated matters.

When configure runs, it detects c-ares, right? configure then generates the Makefiles and then it generates the correct -L paths into them so when make runs it passes those flags to the compiler/linker.

If you then suspect the 'make' phase differs from the 'configure' phase, I suggest you first check `config.log` to see exactly what path configure found c-ares to be in and then you invoke 'make V=1' when you build and check for that c-ares path provide as a `-L` flag. And you could also paste your findings here and we might be able to assist.

**Comment by bagder** [comment] 2019-10-13 09:12
Maybe also try the latest libcurl version?

**Comment by kevinlovejia** [comment] 2019-10-15 03:12
I recompile them with latest version.
```
1.zlib 1.2.11
export CC=mipsel-openwrt-linux-gcc 
./configure --prefix=/home/wei/zlib
make clean && make && make install
2.c-ares 1.15.0
./configure --host=mipsel-openwrt-linux --prefix=/home/wei/c-ares --with-random=/dev/urandom
make clean && make && make install
3.openssl 3.0.0-dev
./Configure --cross-compile-prefix=mipsel-openwrt-linux- no-async linux-mips32 --prefix=/home/wei/openssl
make clean && make && make install
4.curl 7.67.0-DEV
./buildconf
./configure --enable-ares=/home/wei/c-ares --with-zlib=/home/wei/zlib --with-ssl=/home/wei/openssl --host=mipsel-openwrt-linux CC=mipsel-openwrt-linux-gcc --with-random=/dev/urandom LDFLAGS="-lpthread -ldl"
```
After four step above, I check the config.log, C-ares lib different from I check before.
```
LDFLAGS = -lpthread -ldl -L/home/wei/zlib/lib -L/home/wei/openssl/lib -L/usr/local/lib
```
`-L/usr/local/lib` become the load lib dir. I copy **libcares.so libcares.so.2 libcares.so.2.3.0** three file to `/usr/lib`. The issue disappear. I got below.
```
root@ubuntu:/home/wei/curl-master# make
Making all in lib
make[1]: Entering directory `/home/wei/curl-master/lib'
make  all-am
make[2]: Entering directory `/home/wei/curl-master/lib'
make[2]: Leaving directory `/home/wei/curl-master/lib'
make[1]: Leaving directory `/home/wei/curl-master/lib'
Making all in src
make[1]: Entering directory `/home/wei/curl-master/src'
Making all in ../docs
make[2]: Entering directory `/home/wei/curl-master/docs'
Making all in .
make[3]: Entering directory `/home/wei/curl-master/docs'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/home/wei/curl-master/docs'
Making all in cmdline-opts
make[3]: Entering directory `/home/wei/curl-master/docs/cmdline-opts'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/wei/curl-master/docs/cmdline-opts'
make[2]: Leaving directory `/home/wei/curl-master/docs'
make[2]: Entering directory `/home/wei/curl-master/src'
  CCLD     curl
/home/wei/openssl/lib/libcrypto.so: warning: gethostbyname is obsolescent, use getnameinfo() instead.
```
I think curl doesn't check the directory of `configure`  cmd (/home/wei/c-ares). Do I compile curl and enable c-ares sucessfully? I want to use static lib of c-ares and curl.

**Comment by bagder** [comment] 2019-10-15 06:55
> I check the config.log, C-ares lib different from I check before.

What does this mean? Does `config.log` show it found and used c-ares from `/home/wei/c-ares` ?

**Comment by kevinlovejia** [comment] 2019-10-15 08:25
Yeah, 15 days ago, I checked `Makefile`, I can found the right directory in makefile. [Here](https://github.com/curl/curl/issues/4440#issuecomment-536439576). 
Now I run `apt-get remove libc-ares-dev`, I try to `apt-get install libc-ares-dev` the following days. Both `config.log` and `Makefile` can't find `-L/home/wei/c-ares` but instead of `-L/usr/local/lib` . I try Curl-7.61.0, reinstall c-ares 1.15.0, but still can't come back to find the right lib load dir.

**Comment by bagder** [comment] 2019-10-15 09:34
You keep changing the premises so I don't know where we're at.

> Both config.log and Makefile can't find -L/home/wei/c-ares

If configure cannot find it, then naturally it shouldn't be in the generated Makefiles. So when configure doesn't find it, check `config.log` for the c-ares check and see the test failure and try to address it. If you can understand that, consider attaching the `config.log` from the failing configure run here and we might be able to assist.

**Comment by kevinlovejia** [comment] 2019-10-16 01:23
Okay, I can't figure out the directory problem although Curl configure show me `enabled  resolver:         c-ares`. [config.log](https://github.com/kevinlovejia/xixi-s-garden/blob/master/config.log)

**Comment by bagder** [comment] 2019-10-16 10:51
Your c-ares installation looks confused:

> configure:41230: checking for libcares options with pkg-config
> configure:41244: result: found
> configure:41271: pkg-config: ares LIBS: "-lcares  "
> configure:41273: pkg-config: ares LDFLAGS: "-L/usr/local/lib  "
> configure:41275: pkg-config: ares CPPFLAGS: "-I/usr/local/include  "

The pkg-config file in your installed c-ares dir tree seems to have another idea of where it is installed so that's what condfigure finds and uses.

**Comment by kevinlovejia** [comment] 2019-10-17 04:01
I run this in vmware, so I get back to the first snapshot in vmware. Recompile all file. And the `LDFLAGS` and `CPPFLAGS` become `/home/wei/c-ares`, but same issue. [New config.log](https://github.com/kevinlovejia/xixi-s-garden/blob/master/config1.log).

**Comment by bagder** [comment] 2019-10-17 07:32
That configure run finds c-ares in the `/home/wei/c-ares` prefix all right. So when you invoke `make V=1`, doesn't that show that the c-ares path is used for -L and -I properly?

**Comment by kevinlovejia** [comment] 2019-10-17 08:43
`make V=1` will see the same issue.
```
undefined reference to `ares_process_fd'
```
I can find below in [Makefile](https://github.com/kevinlovejia/xixi-s-garden/blob/master/Makefile).
```
CPPFLAGS = -I/home/wei/zlib/include -I/home/wei/openssl/include -I/home/wei/c-ares/include
...
LDFLAGS = -lpthread -ldl -L/home/wei/zlib/lib -L/home/wei/openssl/lib -L/home/wei/c-ares/lib
...
```

**Comment by bagder** [comment] 2019-10-17 12:53
Is that really the same issue? Your original post mentioned a whole list of missing functions and now you're only getting one?

Anyway, is there any chance that you have a (very old) separate c-ares lib somewhere in your system that gets picked up before the one in `/home/wei/c-ares/lib` ?  `ares_process_fd` was added in c-ares 1.4.0 though (from 2007) so it would have to be really old.

The CPPFLAGS and LDFLAGS variables look correct and good. You need to debug why the linker isn't happy with them!

**Comment by kevinlovejia** [comment] 2019-10-18 02:30
Yes, that's really the same issue. I omit the details. Okay, I'll try to find the reason why the linker is unhappy. : )

**Comment by bagder** [comment] 2019-11-08 22:36
This is more of a user problem than a curl problem and nothing new in three weeks. Closing.

**Closed by bagder** 2019-11-08 22:36 UTC
Labels: build
