### ISSUE TITLE
memory leak occurs in cross platform

### ISSUE THREAD

**Issue by xuwenlong02** [curl/curl#12455] opened 2023-12-05 08:52 UTC
### I did this

![20231205-164311](https://github.com/curl/curl/assets/20473316/36c6e840-90d1-46a7-ab62-abd9fa9a131e)
下面是一段在线程内运行的代码，每300毫秒添加一个easy handle, 直到1000个，结果内存一直在增长，但是一到while 退出时，内存突然释放。我们已经确认我们自己的内存都是释放了的，每个easy handle 用完立即释放。退出时也没有调用curl_multi_clean, curl_global_clean，就是一退出线程，就自动释放了。
```c++
void HttpSession::RequestAndResponse()
{
    NETSTACK_LOGD("HttpSession::RequestAndResponse() start");

    CURLMcode ret = CURLM_LAST;
    int runningHandle = 0;
    do {
        ret = PerformRequest(runningHandle);
        if (ret == CURLM_CALL_MULTI_PERFORM) {
            continue;
        } else if (ret == CURLM_OK) {
            ReadResponse();
            continue;
        } else {
            // others are error
            continue;
        }
        // read response
        std::unique_lock<std::mutex> lock(taskQueueMutex_);
        if (runningHandle == 0  && taskIdMap_.empty()) {
            runThread_ = false;
            break;
        }
    } while (runningHandle > 0 && runThread_);
    NETSTACK_LOGD("HttpSession::RequestAndResponse() end");
}

void HttpSession::ReadResponse()
{
    struct CURLMsg *m = nullptr;
    do {
        int msgq = 0;
        std::unique_lock<std::mutex> lock(curlMultiMutex_);
        struct CURLMsg *m = curl_multi_info_read(curlMulti_, &msgq);
        if (m) {
            NETSTACK_LOGI("curl_multi_info_read() m->msg = %{public}d", m->msg);
            if (m->msg != CURLMSG_DONE) {
                NETSTACK_LOGI("curl_multi_info_read failed, m->msg = %{public}d", m->msg);
                continue;
            }
            curl_multi_remove_handle(curlMulti_, m->easy_handle);
            lock.unlock();
            auto task = GetTaskByCurlHandle(m->easy_handle);
            if (task) {
                task->ProcessResponse(m);
            }
            StopTask(task);
            lock.lock();
        }
    } while (m && runThread_);
}

void HttpSession::RunThread()
{
    runThread_ = true;
    NETSTACK_LOGI("RunThread start runThread_ = %{public}s", runThread_ ? "true" : "false");

    while (runThread_) {
         RequestAndResponse();
         std::this_thread::sleep_for(std::chrono::milliseconds(CURL_TIMEOUT_MS));
         NETSTACK_LOGD("RunThread in loop runThread_ = %{public}s, Id = %{public}d, task = %{public}d", 
             runThread_ ? "true" : "false", taskIdMap_.size(), curlTaskMap_.size());
        
         std::function<bool()> f = [this]() -> bool {
             NETSTACK_LOGD("RunThread in loop wait_for taskQueue_.empty() = %{public}d runThread_ = %{public}s",
                          taskIdMap_.empty(), runThread_ ? "true" : "false");
             return !taskIdMap_.empty() || !runThread_;
         };
         std::unique_lock<std::mutex> lock(taskQueueMutex_);
         conditionVariable_.wait_for(lock, std::chrono::seconds(CONDITION_TIMEOUT_S), f);
     }
}
```

### I expected the following

分析清楚内存增长的原因

### curl/libcurl version

v8.4.0

### operating system

cross platform, like linux

**Comment by bagder** [comment] 2023-12-05 09:06
As you say it leaks on Linux, then I suggest you run it with valgrind for a while and let it pinpoint the source of the leak. I strongly suspect the leak is not caused by libcurl.

Also, note that libcurl has not returned `CURLM_CALL_MULTI_PERFORM` for over a decade.

**Comment by xuwenlong02** [comment] 2023-12-06 12:20
![image](https://github.com/curl/curl/assets/20473316/0bd03af4-adf2-42b5-8e2b-b0c4d5228158)


> As you say it leaks on Linux, then I suggest you run it with valgrind for a while and let it pinpoint the source of the leak. I strongly suspect the leak is not caused by libcurl.
> 
> Also, note that libcurl has not returned `CURLM_CALL_MULTI_PERFORM` for over a decade.

I located the memory leak occurs in openssl. But I don't know why.

**Comment by xuwenlong02** [comment] 2023-12-06 12:22
> As you say it leaks on Linux, then I suggest you run it with valgrind for a while and let it pinpoint the source of the leak. I strongly suspect the leak is not caused by libcurl.
> 
> Also, note that libcurl has not returned `CURLM_CALL_MULTI_PERFORM` for over a decade.

I located the memory leak occurs in openssl. But I don't know why.

**Comment by bagder** [comment] 2023-12-07 10:17
A memory leak in OpenSSL could still be curl's fault if it uses it wrongly. But you have not given us any details to go on, not even which OpenSSL version you use so there is nothing for us to do. Closing.

**Closed as completed by bagder** 2023-12-07 10:17 UTC
Labels: memory-leak, needs-info
