### ISSUE TITLE
HTTP3: Segmentation fault

### ISSUE THREAD

**Issue by jurisuk** [curl/curl#11090] opened 2023-05-08 13:41 UTC
Upon compiling from the master branch and against approved versions of nghttp3 (v0.10.0) and ngtcp2 (v0.13.1), curl produces segmentation fault when asked to connect using HTTP3:
```
curl --include --http3 --HEAD https://www.google.com/
Segmentation fault
```

**Comment by icing** [comment] 2023-05-08 15:08
Using the same library versions, building curl from master on my macOS machine, I see no such thing. Would you be able to produce a backtrace of the crash? What OS are you on?

**Comment by jurisuk** [comment] 2023-05-08 15:13
> Also note that --http3 may attempt a parallel HTTP/2 connection. Does the segfault also happen with --http3-only? Just to narrow things down.

Only with HTTP3.

**Comment by icing** [comment] 2023-05-08 15:17
That points to trouble in the secondary HTTP/2 attempt. Do you also have the matching `nghttp2` version`? I know of a hard `assert` in the ngtcp2 code that happens with older nghttp2 libs.

**Comment by bagder** [comment] 2023-05-08 15:22
It reproduced on my debian machine just now with ngtcp2 + nghttp3 combo. It does not reproduce with ngtcp2 and nghttp3 from their git master:

## my curl
~~~
$ ./src/curl -V
WARNING: this libcurl is Debug-enabled, do not use in production

curl 8.1.0-DEV (x86_64-pc-linux-gnu) libcurl/8.1.0-DEV OpenSSL/3.0.7 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 c-ares/1.18.1 libidn2/2.3.3 libpsl/0.21.2 (+libidn2/2.3.3) nghttp2/1.50.0-DEV ngtcp2/0.13.1 nghttp3/0.10.0 librtmp/2.3 libgsasl/2.2.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli Debug gsasl GSS-API HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP TrackMemory UnixSockets zstd
~~~

## run with gdb
~~~

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7f34507 in conn_compute_pto (pktns=0x0, conn=0x555555892300)
    at ngtcp2_conn.c:887
887       if (pktns->rtb.pktns_id == NGTCP2_PKTNS_ID_APPLICATION &&
(gdb) bt 10
#0  0x00007ffff7f34507 in conn_compute_pto (pktns=0x0, conn=0x555555892300)
    at ngtcp2_conn.c:887
#1  ngtcp2_conn_get_idle_expiry (conn=conn@entry=0x555555892300) at ngtcp2_conn.c:13402
#2  0x00007ffff7f34754 in ngtcp2_conn_handle_expiry (conn=0x555555892300, 
    ts=3050374351322000) at ngtcp2_conn.c:10963
#3  0x0000555555637b80 in cf_flush_egress (cf=0x555555778878, data=0x555555736e18)
    at vquic/curl_ngtcp2.c:1963
#4  0x0000555555638cd1 in cf_ngtcp2_connect (cf=0x555555778878, data=0x555555736e18, 
    blocking=false, done=0x7fffffffd6b7) at vquic/curl_ngtcp2.c:2374
#5  0x00005555555dcec1 in Curl_conn_cf_connect (cf=0x555555778878, data=0x555555736e18, 
    blocking=false, done=0x7fffffffd6b7) at cfilters.c:318
#6  0x00005555555dfe65 in baller_connect (cf=0x555555777ae8, data=0x555555736e18, 
    baller=0x555555777b28, now=0x7fffffffd420, connected=0x7fffffffd6b7) at connect.c:548
#7  0x00005555555dffec in is_connected (cf=0x555555777ae8, data=0x555555736e18, 
    connected=0x7fffffffd6b7) at connect.c:603
#8  0x00005555555e0b9b in cf_he_connect (cf=0x555555777ae8, data=0x555555736e18, 
    blocking=false, done=0x7fffffffd6b7) at connect.c:901
#9  0x00005555555dcec1 in Curl_conn_cf_connect (cf=0x555555777ae8, data=0x555555736e18, 
    blocking=false, done=0x7fffffffd6b7) at cfilters.c:318

**Comment by jurisuk** [comment] 2023-05-08 15:38
Okay, if I compile (try) against ngtcp2 v0.15.0, I get compile error:
```
make[2]: Entering directory '/var/build-git2/curl/lib'
  CC       vquic/libcurl_la-curl_ngtcp2.lo
vquic/curl_ngtcp2.c:143:3: error: unknown type name ‘ngtcp2_connection_close_error’
  143 |   ngtcp2_connection_close_error last_error;
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
vquic/curl_ngtcp2.c: In function ‘cb_recv_stream_data’:
vquic/curl_ngtcp2.c:732:5: error: implicit declaration of function ‘ngtcp2_connection_close_error_set_application_error’; did you mean ‘ngtcp2_ccerr_set_application_error’? [-Werror=implicit-function-declaration]
  732 |     ngtcp2_connection_close_error_set_application_error(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     ngtcp2_ccerr_set_application_error
vquic/curl_ngtcp2.c: In function ‘init_ngh3_conn’:
vquic/curl_ngtcp2.c:1260:6: error: implicit declaration of function ‘ngtcp2_conn_get_max_local_streams_uni’; did you mean ‘ngtcp2_conn_extend_max_streams_uni’? [-Werror=implicit-function-declaration]
 1260 |   if(ngtcp2_conn_get_max_local_streams_uni(ctx->qconn) < 3) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |      ngtcp2_conn_extend_max_streams_uni
vquic/curl_ngtcp2.c: In function ‘recv_pkt’:
vquic/curl_ngtcp2.c:1782:24: error: request for member ‘error_code’ in something not a structure or union
 1782 |     if(!ctx->last_error.error_code) {
      |                        ^
vquic/curl_ngtcp2.c:1784:9: error: implicit declaration of function ‘ngtcp2_connection_close_error_set_transport_error_tls_alert’ [-Werror=implicit-function-declaration]
 1784 |         ngtcp2_connection_close_error_set_transport_error_tls_alert(
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
vquic/curl_ngtcp2.c:1789:9: error: implicit declaration of function ‘ngtcp2_connection_close_error_set_transport_error_liberr’ [-Werror=implicit-function-declaration]
 1789 |         ngtcp2_connection_close_error_set_transport_error_liberr(
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from vquic/curl_ngtcp2.c:28:
vquic/curl_ngtcp2.c: In function ‘cf_ngtcp2_close’:
vquic/curl_ngtcp2.c:2209:45: warning: passing argument 7 of ‘ngtcp2_conn_write_connection_close_versioned’ from incompatible pointer type [-Wincompatible-pointer-types]
 2209 |                                             &ctx->last_error, ts);
      |                                             ^
      |                                             |
      |                                             int *
/usr/local/include/ngtcp2/ngtcp2.h:5390:25: note: expected ‘const ngtcp2_ccerr *’ {aka ‘const struct ngtcp2_ccerr *’} but argument is of type ‘int *’
 5390 |     const ngtcp2_ccerr *ccerr, ngtcp2_tstamp ts);
      |     ~~~~~~~~~~~~~~~~~~~~^~~~~
vquic/curl_ngtcp2.c: In function ‘cf_connect_start’:
vquic/curl_ngtcp2.c:2320:3: error: implicit declaration of function ‘ngtcp2_connection_close_error_default’ [-Werror=implicit-function-declaration]
 2320 |   ngtcp2_connection_close_error_default(&ctx->last_error);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [Makefile:3268: vquic/libcurl_la-curl_ngtcp2.lo] Error 1
make[2]: Leaving directory '/var/build-git2/curl/lib'
make[1]: *** [Makefile:1505: all] Error 2
make[1]: Leaving directory '/var/build-git2/curl/lib'
make: *** [Makefile:1266: all-recursive] Error 1
```

**Comment by bagder** [comment] 2023-05-08 16:44
@jurisuk you need #11031 for ngtcp2 0.15.0 or later

**Comment by tatsuhiro-t** [comment] 2023-05-09 09:56
I messed up libngtcp2_crypto library so version.  If you have multiple versions of ngtcp2 installed, it might cause trouble, especially, if you have newer ngtcp2 version than v0.13.1.
When I bump so version of libngtcp2.so, I should also bump libngtcp2_crypto, but I didn't.  That was my mistake.

**Comment by jurisuk** [comment] 2023-05-10 12:41
Thanks. I am scr***. 😬😬

**Comment by bagder** [comment] 2023-05-12 21:56
Since we cannot reproduce this with ngtcp2 0.15.0 and family, I think we can close this?

**Closed** 2023-05-13 05:31 UTC
Labels: crash, HTTP/3
