### ISSUE TITLE
Redirected GET request has spaces instead of '+' chars in URL, causing Bad Request

### ISSUE THREAD

**Issue by kylegranger** [curl/curl#4831] opened 2020-01-18 10:58 UTC
I have a problem with libcurl, which is giving me inconsistent redirect behavior on Android and Linux.  I'm doing a GET request, which fetches a login page.  I get an HTTP 302 response back, and then a second GET request is made (an automatic redirect).  However, there is a slight difference in that second request on the two platforms.  The one done on Ubuntu works, and that done on Android does not, due to space chars in the URL.

// From Linux (Ubuntu 18.04.3), I get the expected response from this redirected GET request.  It has plus characters on either side of 'profile'
~~~
GET /oauth/authorize?response_type=code&redirect_uri=https://sp.auth.adobe.com/adobe-services/oauth2&state=l3ArqA&scope=openid+profile+https://login.comcast.net/pdp/tve&client_id=adobepass-usa&acr_values=urn:oasis:names:tc:SAML:2.0:ac:classes:InternetProtocol HTTP/1.1
Host: oauth.xfinity.com
Accept: */*
ap_42: anonymous
ap_11: i686
ap_z: Mozilla/5.0 (X11; Linux i686; rv:47.0) Gecko/20100101 Firefox/47.0
User-Agent: Mozilla/5.0 (X11; Linux i686; rv:47.0) Gecko/20100101 Firefox/47.0
Cache-Control: no-cache
~~~

// On Android (libcurl is running in a native C++ module), almost the same redirect request is made.  But instead of plus characters, there are space characters.  This result in a Bad Request 400 response
~~~
GET /oauth/authorize?response_type=code&redirect_uri=https://sp.auth.adobe.com/adobe-services/oauth2&state=pzz8kz&scope=openid profile https://login.comcast.net/pdp/tve&client_id=adobepass-usa&acr_values=urn:oasis:names:tc:SAML:2.0:ac:classes:InternetProtocol HTTP/1.1
    Host: oauth.xfinity.com
    Accept: */*
    ap_42: anonymous
    ap_11: i686
    ap_z: Mozilla/5.0 (X11; Linux i686; rv:47.0) Gecko/20100101 Firefox/47.0
    User-Agent: Mozilla/5.0 (X11; Linux i686; rv:47.0) Gecko/20100101 Firefox/47.0
    Cache-Control: no-cache
~~~

The Android library is newer:  7.64.0.  The Linux library is 7.58.0
    linux:    curl version 73a00
    android:  curl version 74000

Headers are the same, the original requests are byte-for-byte the same. The original GET request and headers is this:
https://sp.auth.adobe.com/adobe-services/authenticate/saml/4065696?noflash=true&mso_id=Comcast_SSO&requestor_id=usa&no_iframe=false&domain_name=adobe.com&redirect_url=https%3A%2F%2Fwww.usanetwork.com%2Fmrrobot%2Fvideos%2F408-request-timeout
~~~
     add HTTP header: ap_42: anonymous
     add HTTP header: ap_11: i686
     add HTTP header: ap_z: Mozilla/5.0 (X11; Linux i686; rv:47.0) Gecko/20100101 Firefox/47.0
     add HTTP header: User-Agent: Mozilla/5.0 (X11; Linux i686; rv:47.0) Gecko/20100101 Firefox/47.0
     add HTTP header: Cache-Control: no-cache
~~~

On Linux (as on Android), when the HTTP 302 response comes after the first request, there are spaces in the Location field.  These are then converted to plus chars (only on Linux), and the "Issue another request to this URL" has correctly formed URL. 
~~~
< HTTP/1.1 302 Found
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Headers: ap_11,ap_42,ap_z,ap_19,ap_23,authorization
< Access-Control-Allow-Methods: POST,GET,OPTIONS,DELETE
< Cache-Control: No-Cache
< Content-Type: text/plain
< Date: Sat, 18 Jan 2020 10:47:53 GMT
< Location: https://oauth.xfinity.com/oauth/authorize?response_type=code&redirect_uri=https://sp.auth.adobe.com/adobe-services/oauth2&state=42IvhG&scope=openid profile https://login.comcast.net/pdp/tve&client_id=adobepass-usa&acr_values=urn:oasis:names:tc:SAML:2.0:ac:classes:InternetProtocol
< P3P: CP="NOI DSP COR CURa ADMa DEVa OUR BUS IND UNI COM NAV STA"
< Server: api-gateway/1.9.3.1
< Set-Cookie: passgw=gw-ap-prod-uw2; Path=/; HttpOnly
< Set-Cookie: AWSALB=XBWIX/jlQgrqYNPB9iCpC6gV7fIU22V8z4ZsU+4JDmDOkMpZeex91+Tu4XXqLhFkgkoM/BmA3d1w8Fz9GWv/74yJfbkS8siR1wRhIzITTw34gBYmJMe4tUOeSQfY; Expires=Sat, 25 Jan 2020 10:47:53 GMT; Path=/
< Set-Cookie: JSESSIONID=036106E0B98A44D73BE4E7DD979FAEF7; Path=/; HttpOnly
< Set-Cookie: redirect_url=https%3A%2F%2Fwww.usanetwork.com%2Fmrrobot%2Fvideos%2F408-request-timeout; Expires=Thu, 05-Feb-2088 14:02:00 GMT; Path=/; Secure
< Set-Cookie: client_type=html5; Expires=Thu, 05-Feb-2088 14:02:00 GMT; Path=/; Secure
< Set-Cookie: client_version=2.35; Expires=Thu, 05-Feb-2088 14:02:00 GMT; Path=/; Secure
< X-Request-Id: 7cuu8Oqs4MBzug8CgVS0qRGqOP0WeI94
< Content-Length: 0
< Connection: keep-alive
<  Connection #1 to host sp.auth.adobe.com left intact
< Issue another request to this URL: 'https://oauth.xfinity.com/oauth/authorize?response_type=code&redirect_uri=https://sp.auth.adobe.com/adobe-services/oauth2&state=42IvhG&scope=openid+profile+https://login.comcast.net/pdp/tve&client_id=adobepass-usa&acr_values=urn:oasis:names:tc:SAML:2.0:ac:classes:InternetProtocol'
~~~

I'm at a loss with how to get past this.

Thanks all, and greetings from Innsbruck!

**Comment by jay** [comment] 2020-01-19 07:27
Ref: https://tools.ietf.org/html/rfc3986
Ref: https://tools.ietf.org/html/rfc7230

~~~
Location      = URI-reference
URI-reference = URI / relative-ref
URI           = scheme ":" hier-part [ "?" query ] [ "#" fragment ]
query         = *( pchar / "/" / "?" )
pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
pct-encoded   = "%" HEXDIG HEXDIG
sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
              / "*" / "+" / "," / ";" / "="
HEXDIG        =  DIGIT / "A" / "B" / "C" / "D" / "E" / "F"
DIGIT         =  %x30-39             ; 0-9
ALPHA         =  %x41-5A / %x61-7A   ; A-Z / a-z
~~~

I think that is supposed to be encoded by the server, however Firefox and Chrome will encode it as %20.

**Comment by kylegranger** [comment] 2020-01-19 10:09
Thanks for the links... and yes, it does now look like a non-spec-conformant URL in the Location field -- i.e., that's the first thing that goes wrong.  This URL has spaces, which it shouldn't.

Location: https://oauth.xfinity.com/oauth/authorize?response_type=code&redirect_uri=https://sp.auth.adobe.com/adobe-services/oauth2&state=42IvhG&scope=openid profile https://login.comcast.net/pdp/tve&client_id=adobepass-usa&acr_values=urn:oasis:names:tc:SAML:2.0:ac:classes:InternetProtocol

For some reason, the 7.58.0 curl build treats this differently than 7.64.  My near term plan is to just build 7.58 for Android, and give it a go.  If that fails, then I have to dig into the code and change it there. And find out where-in-the-code 7.58 is inserting plus chars into the non normative location URL, thus making the query work.

AFAIK, there is no way to alter the redirects, as they are happening.  Using the debug callback and VERBOSE, I do get all the data in realtime.  I tried filtering for the "Location:" field and fixing it there by overwriting the char *data (kind of a hail mary hack, so to speak).  But the following HTTP GET was unchanged.  The data I get in the debug callback seems to be just a copy.

**Comment by bagder** [comment] 2020-01-19 14:25
Spaces are not part of URIs according to RFC 3986 as we follow, but browsers annoyingly allow them in the WHATWG URL spec. curl actually already tries to encode incoming spaces in URLs in Location: headers to `%20` (see test 663).

Does curl really use the space or does it use %20?

**Comment by kylegranger** [comment] 2020-01-19 14:54
The Location URL comes in with the space char, not %20.  With build 7.58.0 on Linux, the following GET request has the spaces replaced with '+' chars -- not %20.   With 7.64.0 on Android, there is not rewrite of the location URL, and there the call with the malformed URL fails (Bad Request 400).

**Comment by kylegranger** [comment] 2020-01-19 15:06
This is the debug output (grabbed from debug callback for printing to logcat) for the case where it does not work (Android, build 7.64).  This is the HTTP 302 response, which exactly matches what I get on Linux.  You can see the following GET, the spaces are not replaced with '+' chars.  (The Location line is long).  Everything is exactly the same on Linux -- except -- there are pluses instead of space chars.

 curl debug: type 1, size 20, text HTTP/1.1 302 Found
 curl debug: type 1, size 40, text Access-Control-Allow-Credentials: true
 curl debug: type 1, size 74, text Access-Control-Allow-Headers: ap_11,ap_42,ap_z,ap_19,ap_23,authorization
 curl debug: type 1, size 55, text Access-Control-Allow-Methods: POST,GET,OPTIONS,DELETE
 curl debug: type 1, size 25, text Cache-Control: No-Cache
 curl debug: type 1, size 26, text Content-Type: text/plain
 curl debug: type 1, size 37, text Date: Fri, 17 Jan 2020 19:10:24 GMT
 curl debug: type 1, size 292, text Location: https://oauth.xfinity.com/oauth/authorize?response_type=code&redirect_uri=https://sp.auth.adobe.com/adobe-services/oauth2&state=pzz8kz&scope=openid profile https://login.comcast.net/pdp/tve&client_id=adobepass-usa&acr_values=urn:oasis:names:tc:SAML:2.0:ac:classes:InternetProtocol
 curl debug: type 1, size 66, text P3P: CP="NOI DSP COR CURa ADMa DEVa OUR BUS IND UNI COM NAV STA"
 curl debug: type 1, size 29, text Server: api-gateway/1.9.3.1
 curl debug: type 1, size 53, text Set-Cookie: passgw=gw-ap-prod-uw2; Path=/; HttpOnly
 curl debug: type 1, size 192, text Set-Cookie: AWSALB=qPF+QwGG/tMyUPfFkDWzYFL1yTxV2u2mzYORh0yk9UhVXZ45DQ5LTQGq4paz31FOYSR4KxuMUkRShfkMUOc9jfX9u3nXeddiEuz6nSEKvpCFMWytvVQTUlzA+1dy; Expires=Fri, 24 Jan 2020 19:10:24 GMT; Path=/
 curl debug: type 1, size 75, text Set-Cookie: JSESSIONID=D79428075B62E3A3BEE09C8FB2DC7965; Path=/; HttpOnly
 curl debug: type 1, size 155, text Set-Cookie: redirect_url=https%3A%2F%2Fwww.usanetwork.com%2Fmrrobot%2Fvideos%2F408-request-timeout; Expires=Wed, 04-Feb-2088 22:24:31 GMT; Path=/; Secure
 curl debug: type 1, size 86, text Set-Cookie: client_type=html5; Expires=Wed, 04-Feb-2088 22:24:31 GMT; Path=/; Secure
 curl debug: type 1, size 88, text Set-Cookie: client_version=2.35; Expires=Wed, 04-Feb-2088 22:24:31 GMT; Path=/; Secure
 curl debug: type 1, size 48, text X-Request-Id: SUL9YV8LOawP8lJGD5JBhQNlfW71tkaR
 curl debug: type 1, size 19, text Content-Length: 0
 curl debug: type 1, size 24, text Connection: keep-alive
 curl debug: type 1, size 2, text 
 curl debug: type 2, size 520, text 
 GET /oauth/authorize?response_type=code&redirect_uri=https://sp.auth.adobe.com/adobe-services/oauth2&state=pzz8kz&scope=openid profile https://login.comcast.net/pdp/tve&client_id=adobepass-usa&acr_values=urn:oasis:names:tc:SAML:2.0:ac:classes:InternetProtocol HTTP/1.1
    Host: oauth.xfinity.com
    Accept: */*
    ap_42: anonymous
    ap_11: i686
    ap_z: Mozilla/5.0 (X11; Linux i686; rv:47.0) Gecko/20100101 Firefox/47.0
    User-Agent: Mozilla/5.0 (X11; Linux i686; rv:47.0) Gecko/20100101 Firefox/47.0
    Cache-Control: no-cache
curl debug: type 1, size 26, text HTTP/1.1 400 Bad Request
curl debug: type 1, size 37, text Date: Fri, 17 Jan 2020 19:10:26 GMT
curl debug: type 1, size 16, text Server: Apache

**Comment by bagder** [comment] 2020-01-19 15:10
I can't reproduce this problem with the current libcurl. Can you upgrade to 7.68.0 and see if it fixes the issue for you as well?

**Comment by kylegranger** [comment] 2020-01-19 15:13
Ok... and sure -- thanks for the response!

**Comment by bagder** [comment] 2020-01-19 15:15
I'm pretty sure it was fixed in [this commit](https://github.com/curl/curl/commit/c6f250c4d6a8964a24d99aaf0e0cb81ab9cb293f), shipped in 7.67.0...

**Comment by kylegranger** [comment] 2020-01-19 18:50
Alright... I just built 7.68.0 curl library for Android/arm64-v8a:  Problem fixed! I no longer get the Bad Request following the redirected query.

// A:  version
E/CTV: curl version 74400
// B:  Incoming Location (with the space chars)
 E/CTV: curl debug: type 1, size 292, nprint 292, text Location: https://oauth.xfinity.com/oauth/authorize?response_type=code&redirect_uri=https://sp.auth.adobe.com/adobe-services/oauth2&state=iVYXD8&scope=openid profile https://login.comcast.net/pdp/tve&client_id=adobepass-usa&acr_values=urn:oasis:names:tc:SAML:2.0:ac:classes:InternetProtocol
// C:  outgoing redirect url with %2B's inserted ('+' char encoding)
 E/CTV: curl debug: type 2, size 753, nprint 753, text GET /login?r=comcast.net&s=oauth&continue=https%3A%2F%2Foauth.xfinity.com%2Foauth%2Fauthorize%3Fresponse_type%3Dcode%26redirect_uri%3Dhttps%3A%2F%2Fsp.auth.adobe.com%2Fadobe-services%2Foauth2%26state%3DiVYXD8%26scope%3Dopenid%2Bprofile%2Bhttps%3A%2F%2Flogin.comcast.net%2Fpdp%2Ftve%26client_id%3Dadobepass-usa%26acr_values%3Durn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Aac%3Aclasses%3AInternetProtocol%26response%3D1&ipAddrAuthn=1&client_id=adobepass-usa&reqId=ff805143-6622-42b4-9c54-49f5015f3d79 HTTP/1.1

I think we're done here.  Danke schön, Daniel.

**Comment by jay** [comment] 2020-01-19 19:32
Thanks for confirming, duplicate of #4445.

**Closed by jay** 2020-01-19 19:32 UTC
Labels: HTTP, URL, duplicate
