### ISSUE TITLE
Handling of subdomain starting with a number 

### ISSUE THREAD

**Issue by pejobo** [curl/curl#11266] opened 2023-06-07 20:10 UTC
### I did this
I use a tool which uses internally curl for getting specific content from different websites. Recently one of the content providers provides the content under random subdomains. The subdomain names are "numeric", so it's just a chain of numbers. I learned it from the error log and by reproducing the behavior with curl directly from the command line. When pinpointing it down to the subdomain I looked up the rfc for domain names and learned that domain name parts must start with a letter. But I do not have control over the content provider (so that he changes the subdomain names he uses) nor the tool (i.e. that it uses another library to retrieve the content). 
I checked the behavior of wget and different browsers with different engines and all accepted urls with numeric subdomains. 
That is the error message:
curl: (3) URL using bad/illegal format or missing URL

### I expected the following
No error message

### curl/libcurl version

$ curl -V
curl 8.1.0 (armv7l-unknown-linux-gnueabihf) libcurl/8.1.0 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.53.0
Release-Date: 2023-05-17
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

### operating system

$ uname -a
Linux pi3 6.1.28-5-rpi-ARCH #1 SMP Wed May 17 13:01:32 MDT 2023 armv7l GNU/Linux

**Comment by dfandrich** [comment] 2023-06-07 20:20
Duplicate of #11129, fixed two releases ago in 8.1.1.

**Closed by dfandrich** 2023-06-07 20:20 UTC
