### ISSUE TITLE
curl wrong timing

### ISSUE THREAD

**Issue by tema-san** [curl/curl#1830] opened 2017-08-25 09:34 UTC
### I did this
>>time curl -w "@curl-format.txt" -o /dev/null -s https://meow.kiev.ua/

            time_namelookup:  0.004182
               time_connect:  4295.046898
            time_appconnect:  0.000000
           time_pretransfer:  4295.046932
              time_redirect:  0.000000
         time_starttransfer:  4295.122428
                            ----------
                 time_total:  4295.122458

real	0m0.162s
user	0m0.004s
sys	0m0.000s
than again:
>> time curl -w "@curl-format.txt" -o /dev/null -s https://meow.kiev.ua/

            time_namelookup:  0.004216
               time_connect:  0.079681
            time_appconnect:  0.000000
           time_pretransfer:  0.079708
              time_redirect:  0.000000
         time_starttransfer:  0.155239
                            ----------
                 time_total:  0.155290

real	0m0.162s
user	0m0.004s
sys	0m0.000s

### I expected the following
 time_total:  0.155290
real	0m0.162s
but got 
 time_total:  4295.122458 (1h+ )!!!!
while real	0m0.162s
### curl/libcurl version

curl 7.55.0 (x86_64-pc-linux-gnu) libcurl/7.55.0 OpenSSL/1.0.2l zlib/1.2.8 libidn2/2.0.2 libpsl/0.18.0 (+libidn2/2.0.2) libssh2/1.8.0 nghttp2/1.25.0 librtmp/2.3
Release-Date: 2017-08-09
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

### operating system
Debian unstable/sid

**Comment by bagder** [comment] 2017-08-25 09:37
Thanks!

Duplicate of #1769, fixed in 7.55.1 and #1771 already

**Closed by bagder** 2017-08-25 09:37 UTC
