### ISSUE TITLE
HTTPS proxy w/ HTTPS destination is broken due to allow multiple SSL backend change

### ISSUE THREAD

**Issue by jay** [curl/curl#1855] opened 2017-09-03 07:30 UTC
### I did this
`-v --proxy-insecure  --proxy https://127.0.0.1:8080 https://www.google.com`
Causes an access violation due to null pointer deref in commits after the change to allow for multiple SSL backends.

I'm using [this script](https://gist.github.com/agl/2da9e61528f0d373894d8c919abfb518) as the HTTPS proxy (note it's not a real proxy it's just faking a reply to what it assumes is a CONNECT and then connects to google.com 443).

_(Note this issue appears to be unrelated to #1853 which looks similar but AFAICT isn't)_
### Analysis
After the HTTPS proxy connection is established, the access violation is in ossl step1 when curl tries to connect to the destination:
https://github.com/curl/curl/blob/3baf36edf6ed1d7c74d68846d79f87334b573aea/lib/vtls/openssl.c#L1935-L1939
BACKEND (ie `connssl->backend`) is null though because what happens is once the https proxy is established its data is moved from ssl into proxy_ssl then ssl is cleared to be used again for the destination:
https://github.com/curl/curl/blob/3baf36edf6ed1d7c74d68846d79f87334b573aea/lib/vtls/vtls.c#L203-L215
but now there's new backend stuff:
https://github.com/curl/curl/blob/3baf36edf6ed1d7c74d68846d79f87334b573aea/lib/url.c#L4285-L4300

So it seems like we need to keep track of that when moving the data. I thought I could get around this by swapping the backend pointers but that's causing SYSCALL errors so it might be more complicated or I'm missing something obvious because it's late. Here's what it looks like though:
~~~diff
diff --git a/lib/vtls/vtls.c b/lib/vtls/vtls.c
index 3647dff..d1164a0 100644
--- a/lib/vtls/vtls.c
+++ b/lib/vtls/vtls.c
@@ -206,10 +206,20 @@ ssl_connect_init_proxy(struct connectdata *conn, int sockindex)
   DEBUGASSERT(conn->bits.proxy_ssl_connected[sockindex]);
   if(ssl_connection_complete == conn->ssl[sockindex].state &&
      !conn->proxy_ssl[sockindex].use) {
+    struct ssl_backend_data *pbdata;
+
     if(!Curl_ssl->support_https_proxy)
       return CURLE_NOT_BUILT_IN;
+
+    /* The pointers to the ssl backend data, which is opaque here, are swapped
+       rather than move the contents. */
+    pbdata = conn->proxy_ssl[sockindex].backend;
     conn->proxy_ssl[sockindex] = conn->ssl[sockindex];
+
     memset(&conn->ssl[sockindex], 0, sizeof(conn->ssl[sockindex]));
+    memset(pbdata, 0, Curl_ssl->sizeof_ssl_backend_data);
+
+    conn->ssl[sockindex].backend = pbdata;
   }
   return CURLE_OK;
 }
~~~

### curl/libcurl version
3baf36e 2017-09-02
~~~
curl 7.56.0-DEV (i386-pc-win32) libcurl/7.56.0-DEV OpenSSL/1.0.2l nghttp2/1.25.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Debug Largefile NTLM SSL HTTP2 HTTPS-proxy
~~~
### operating system
Windows 7

/cc @dscho

**Comment by dscho** [comment] 2017-09-05 10:16
Hrm. Your patch looks correct to me, though. And I cannot compile Go (if the script was in Python, there would be no problem...).

I will try to stare at it a bit more, maybe it will hit me.

**Comment by dscho** [comment] 2017-09-05 11:03
I managed to see something funny going on when trying to use TinyProxy: I receive something like this:

```
...
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
...
```

but it looks as if that is a regression between 7.47.0 and 7.55.1. Bisecting now to get a clearer picture.

**Comment by dscho** [comment] 2017-09-05 19:31
Update: i am still bisecting, but I have to skip many commits because either it fails to compile trying to find `idn2.h`, or it reports "* Unsupported proxy scheme for 'https://127.0.0.1:8888' * Closing connection -1; curl: (7) Unsupported proxy scheme for 'https://127.0.0.1:8888'", neither of which represent the "unknown protocol" problem nor its resolution. Will continue to bisect, but it's tough going.

**Comment by jay** [comment] 2017-09-05 19:43
Sorry that I cannot assist you with this at the moment however it sounds like you may be able to automate that bisect. See an automated bisect script example at https://github.com/curl/curl/issues/1703#issuecomment-318268511

**Comment by dscho** [comment] 2017-09-06 12:19
@jay thanks for offering help... I am actually quite aware of `git bisect run`... in this case, I encountered too many unforeseen cases, so I continued with the interactive version of the bisect. But as you said, i should have reverted to the automatic bisect a long time ago, it really wasted a lot of my time that I did not do that.

Now running on automatic.

**Comment by dscho** [comment] 2017-09-06 15:22
Oh wow. You want to know what I found out, @jay? As of a96319ebb934ac8d3df4b88c8eb0d7ba00d5f883, it seems that *my* attempts to use your command-line fail with "Unsupported proxy scheme". I have to use `--proxy http:https://127.0.0.1:8888/` instead of `--proxy https://127.0.0.1:8888/`. Are you *sure* that the command line [you indicated in your original report](https://github.com/curl/curl/issues/1855#issue-254858888) was really the one that you actually used?

**Comment by dscho** [comment] 2017-09-06 22:45
I found the culprit. PR coming soon (I am still verifying that I did not make other similar mistakes).

**Comment by dscho** [comment] 2017-09-07 10:54
BTW I have *no* idea why I needed the extra `https:` in `--proxy https:https://127.0.0.1:443`, but I did. Yet I do not have to do that any longer, so if there was any bug it has been fixed on `master` in the meantime.

**Closed** 2017-09-07 14:09 UTC
Labels: SSL/TLS
