### ISSUE TITLE
Curl pipelines requests via HTTP/1.1 in presence of another connection to the same server via HTTP/2

### ISSUE THREAD

**Issue by dmitrmax** [curl/curl#4885] opened 2020-02-05 18:11 UTC
### I did this
1) I'm using curl multi interface with CURLMOPT_PIPELING set to CURLPIPE_MULTIPLEX
2) I'm issuing multiple HTTP requests to the same server
3) First request opens connection but it is somehow handshaked to HTTP/1.1 (though ALPN announces both h2 and http1.1)
4) Second connection is handshaked to HTTP/2.
5) There are third and others connections which are mixed to HTTP/1.1 and HTTP/2

After this I see that curl puts several outstanding requests (up to 21) on HTTP/1.1 connection. Furthermore, POST and GET requests are mixed.  AFAIK, POSTs can't be pipelined by standard. But the main thing is that: when replies are coming, curl matches them with wrong easy handles. For example:
1) I have 21 outstanding requests before I get first reply. Among them 1st,  3rd, 6th, 8th, 9th, 14th and 18th are POST requests. Others are GET requests.
2) When I get callback for the first reply, curl supplies easy_handle of 7th request (though its content perfectly matches 1st request). 2nd reply is matched with 12th request. 3rd - with 20th, 4th - with 4th, 5th - with 8th. And so on.

Also it seems that others connections (including HTTP/2) are not used at all except for the request which created them.

Unfortunately, this mixed protocol version negotiation happens only from one specific location of our client app. Reproducing of this bug on your machines is highly unlikely (

### I expected the following
I expect several things:
1) First of all: no pipelining over HTTP/1.1 at all!
2) Using HTTP/2 connection if both HTTP/1.1 and HTTP/2 are available (and HTTP/1.1 should be closed in some time).
3) Matching replies with correct easy handle (appropriate to the request).

### curl/libcurl version
7.66

[curl -V output]

### operating system
Linux.

**Comment by bagder** [comment] 2020-02-05 21:50
I respect that you see something you consider to be a bug, but if you cannot provide a way for us to reproduce then there's not a whole lot we can do other than to explain how things are supposed to work, what we've fixed since the version you use and offer some hints on how you can debug this yourself.

1. HTTP Pipelining support was removed in 2f44e94efb3df, shipped in 7.65.0. Since then, curl does not support pipelining. It seems very unlikely that you actually see pipelining being used.
2. Without any other options, curl will prioritize reusing an existing connection to fire away new transfers over. If there's an available HTTP/1 connection alive, that might get used. We've recently fixed a few bugs that made curl not do multiplexing as much as it should. We even have a fix for this in git master that hasn't been shipped in a release yet.
3. That's a bug we have not seen reported before and I've not seen reproduced. I would urge you to run an example with as few transfers as possible that still reproduce the issue and then try to see what the pattern is when the problem appears, in order to start getting some sense in what's going on. Exactly how do you say it doesn't map responses to requests, how does it materialize?

**Comment by bagder** [comment] 2020-02-14 21:55
No response in over a week on a fresh report. Nothing to act on. Closing.

**Closed by bagder** 2020-02-14 21:55 UTC
Labels: HTTP, HTTP/2, needs-info-or-update
