### ISSUE TITLE
test3026 fails on CentOS 7 due to lack of _Atomic support in gcc 4.8.5

### ISSUE THREAD

**Issue by pghmcfc** [curl/curl#9277] opened 2022-08-08 11:09 UTC
Test 3026 fails on CentOS 7 like this:
```
test 3026...[curl_global_init thread-safety]
./libtest/lib3026 none >log/stdout3026 2>log/stderr3026
CMD (65280): ./libtest/lib3026 none >log/stdout3026 2>log/stderr3026
lib3026 returned 255, when expecting 0
 exit FAILED
== Contents of files in the log/ dir after test 3026
=== Start of file commands.log
 ./libtest/lib3026 none >log/stdout3026 2>log/stderr3026
=== End of file commands.log
=== Start of file ftpserver.cmd
 Testnum 3026
=== End of file ftpserver.cmd
=== Start of file stderr3026
 URL: none
 ../../../tests/libtest/lib3026.c:59 Have pthread but the CURL_VERSION_THREADSAFE feature flag is not set
=== End of file stderr3026
```
The `CURL_VERSION_THREADSAFE` feature flag is not set because CentOS 7 ships with `gcc` 4.8.5, which has C11 support but not `_Atomic` (apparently introduced in `gcc` 4.9).
```
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... -std=gnu11
checking whether gcc -std=gnu11 understands -c and -o together... yes
checking how to run the C preprocessor... gcc -std=gnu11 -E
checking if _Atomic is available... no
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for code coverage support... no
checking whether build environment is sane... yes
```
There is a discussion of the same sort of issue at https://github.com/redis/redis/issues/7509

I think probably the `lib3026.c` file should be checking `HAVE_ATOMIC` as well as `HAVE_PTHREAD_H`

**Comment by bagder** [comment] 2022-08-08 11:32
This looks like a problem we have fixed in master already. Like with 945a81e143b

**Comment by bagder** [comment] 2022-08-08 17:55
Duplicate of #9141

**Closed by bagder** 2022-08-08 17:55 UTC
Labels: tests

**Comment by pghmcfc** [comment] 2022-08-08 21:11
Confirmed, that fixes it, thanks.
