### ISSUE TITLE
libcurl can't work fine on Qemu Vexpress 

### ISSUE THREAD

**Issue by zhouweiguo2017** [curl/curl#2065] opened 2017-11-10 05:50 UTC
# I did this:

testcurl.c:
~~~c
#include <stdio.h>
#include <stdlib.h>
#include "curl/curl.h"

void preinit(int argc, char **argv, char **envp)
{
  printf("%s\n", __FUNCTION__);
}

void init(int argc, char **argv, char **envp)
{
  printf("%s\n", __FUNCTION__);
}

void fini()
{
    printf("%s\n", __FUNCTION__);
}

__attribute__((section(".init_array"))) typeof(init) *__init = init;
__attribute__((section(".preinit_array"))) typeof(preinit) *__preinit = preinit;
__attribute__((section(".fini_array"))) typeof(fini) *__fini = fini;

void __attribute__ ((constructor)) constructor()
{
    printf("%s\n", __FUNCTION__);
}

void __attribute__ ((destructor)) destructor()
{
    printf("%s\n", __FUNCTION__);
}


int main(int argc, char *argv[])
{
    printf("test curl on qemu\n");
    curl_global_init(CURL_GLOBAL_DEFAULT);

    return 0;
}
~~~
Makefile:
~~~shell
CROSS_COMPILE=/linuxdev/toolchains/aarch32/bin/arm-linux-gnueabihf-
CC      = $(CROSS_COMPILE)gcc
LD      = $(CROSS_COMPILE)ld
AR      = $(CROSS_COMPILE)ar
NM      = $(CROSS_COMPILE)nm
OBJCOPY = $(CROSS_COMPILE)objcopy
OBJDUMP = $(CROSS_COMPILE)objdump
READELF = $(CROSS_COMPILE)readelf

OBJS = testcurl.o

CFLAGS =  -g  -I./external/curl-7.56.1/include/
LDADD +=  ./external/curl-7.56.1/lib/.libs/libcurl.a 

BINARY = testcurl

.PHONY: all
all: $(BINARY)

$(BINARY): $(OBJS)
        $(CC)  -o $@ $(OBJS) $(LDADD)

%.o:%.c
        $(CC) -o $@ -c $< $(CFLAGS) 

.PHONY: clean
clean:
        rm -f $(OBJS) $(BINARY)
~~~
# I expected the following
copy the testcurl to Qemu Vexpress  VM, running  the testcurl from terminal,

 the program exit directly(shoudn't happen here, it seems that unexpected behaviour happened during loading the testcurl into memory and executing the testcurl from memory, and I tried use arm-linux-gnueabihf-objdump (on build host)  and gdb (on running board) to analysis but couldn't find any valueable clues ). the expected result as following:

~~~
root@Vexpress:/host/linuxdev/curl  ./testcurl 
preinit
init
constructor
test curl on qemu
destructor
fini
root@Vexpress:/host/linuxdev/curl/
~~~

after comment  curl_global_init(CURL_GLOBAL_DEFAULT) in testcurl.c  and rebuilt with Makefile and copy the new testcurl to target board and running testcurl again, could got the expected result.

# operating system
~~~
root@Vexpress:/ cat /proc/cpuinfo 
processor	: 0
model name	: ARMv7 Processor rev 1 (v7l)
BogoMIPS	: 125.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x2
CPU part	: 0xc0f
CPU revision	: 1

Hardware	: Generic DT based system
Revision	: 0000
Serial		: 0000000000000000
root@Vexpress:/ 
~~~
# build env
~~~
linuxdev:$ uname  -a
Linux 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
~~~
# build script:
~~~
linuxdev:$ cat build_curl.sh 
#curl-7.56.1.tar.gz

export CROSS_COMPILE=arm-linux-gnueabihf
export PATH=/linuxdev/toolchains/aarch32/bin/:$PATH
export SYSROOT=/linuxdev/toolchains/aarch32/arm-linux-gnueabihf/libc/
export CPPFLAGS=" -I${SYSROOT}/usr/include "
#export LDFLAGS="-L${SYSROOT}/usr/lib -lc -lm -ldl -lgcc"
export AR=arm-linux-gnueabihf-ar
export AS=arm-linux-gnueabihf-as
export LD=arm-linux-gnueabihf-ld
export RANLIB=arm-linux-gnueabihf-ranlib
export CC=arm-linux-gnueabihf-gcc
export NM=arm-linux-gnueabihf-nm
export CXX=arm-linux-gnueabihf-g++

./configure --host=${CROSS_COMPILE} --build=x86_64-pc-linux-gnu  --without-ca-bundle --without-ca-path --enable-static=yes --enable-shared=no  --prefix=/tmp/curl --without-nghttp2 --without-librtmp --without-libidn --without-libssh2 --without-libpsl --disable-ldap --disable-ldaps --disable-ftp --disable-rtsp --disable-dict --disable-telnet --disable-tftp --disable-pop3 --disable-imap --disable-smtp --disable-gopher --disable-manual --disable-smb --disable-sspi --disable-manual --enable-unix-sockets --disable-versioned-symbols --enable-hidden-symbols --disable-libcurl-option --disable-verbose --disable-file --disable-option-checking --disable-silent-rules --disable-debug --disable-optimize --disable-warnings --disable-werror --disable-curldebug  --disable-symbol-hiding --disable-ares --disable-rt --disable-dependency-tracking --disable-libtool-lock --disable-versioned-symbols --disable-threaded-resolver --disable-pthreads --disable-verbose --disable-sspi --disable-crypto-auth --disable-ntlm-wb --disable-tls-srp   
~~~

**Comment by zhouweiguo2017** [comment] 2017-11-10 06:43
@jay,  appreciate too much for help refine the text. it's more clear now.

**Comment by jay** [comment] 2017-11-10 07:16
are you sure armhf is your architecture? also you got nothing in gdb? that seems weird

**Comment by zhouweiguo2017** [comment] 2017-11-10 07:31
indeed weired.

the target board is Qemu Vexpress board.
the toolchain used here is: 
linuxdev:$ /linuxdev/toolchains/aarch32/bin/arm-linux-gnueabihf-gcc -v
Using built-in specs.
COLLECT_GCC=/ismp/optee/toolchains/aarch32/bin/arm-linux-gnueabihf-gcc
COLLECT_LTO_WRAPPER=/ismp/optee/toolchains/aarch32/bin/../libexec/gcc/arm-linux-gnueabihf/4.7.3/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: /cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-linux/.build/src/gcc-linaro-4.7-2013.02/configure --build=i686-build_pc-linux-gnu --host=i686-build_pc-linux-gnu --target=arm-linux-gnueabihf --prefix=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-linux/install --with-sysroot=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-linux/install/arm-linux-gnueabihf/libc --enable-languages=c,c++,fortran --enable-multilib --with-arch=armv7-a --with-tune=cortex-a9 --with-fpu=vfpv3-d16 --with-float=hard --with-pkgversion='crosstool-NG linaro-1.13.1-4.7-2013.02-01-20130221 - Linaro GCC 2013.02' --with-bugurl=https://bugs.launchpad.net/gcc-linaro --enable-__cxa_atexit --enable-libmudflap --enable-libgomp --enable-libssp --with-gmp=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-linux/.build/arm-linux-gnueabihf/build/static --with-mpfr=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-linux/.build/arm-linux-gnueabihf/build/static --with-mpc=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-linux/.build/arm-linux-gnueabihf/build/static --with-ppl=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-linux/.build/arm-linux-gnueabihf/build/static --with-cloog=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-linux/.build/arm-linux-gnueabihf/build/static --with-libelf=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-linux/.build/arm-linux-gnueabihf/build/static --with-host-libstdcxx='-L/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-linux/.build/arm-linux-gnueabihf/build/static/lib -lpwl' --enable-threads=posix --disable-libstdcxx-pch --enable-linker-build-id --enable-gold --with-local-prefix=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-linux/install/arm-linux-gnueabihf/libc --enable-c99 --enable-long-long --with-mode=thumb
Thread model: posix
gcc version 4.7.3 20130205 (prerelease) (crosstool-NG linaro-1.13.1-4.7-2013.02-01-20130221 - Linaro GCC 2013.02) 


root@Vexpress:/mnt/linuxdev ls
Makefile    external    testcurl    testcurl.c  testcurl.o
root@Vexpress:/mnt/linuxdev cat testcurl.c
#include <stdio.h>
#include <stdlib.h>
#include "curl/curl.h"

void preinit(int argc, char **argv, char **envp)
{
    printf("[%s,%d]%s\n", __FILE__, __LINE__, __FUNCTION__);
}

void init(int argc, char **argv, char **envp)
{
    printf("[%s,%d]%s\n", __FILE__, __LINE__, __FUNCTION__);
}

void fini()
{
    printf("[%s,%d]%s\n", __FILE__, __LINE__, __FUNCTION__);
}

__attribute__((section(".init_array"))) typeof(init) *__init = init;
__attribute__((section(".preinit_array"))) typeof(preinit) *__preinit = preinit;
__attribute__((section(".fini_array"))) typeof(fini) *__fini = fini;

void __attribute__ ((constructor)) constructor()
{
    printf("[%s,%d]%s\n", __FILE__, __LINE__, __FUNCTION__);
}

void __attribute__ ((destructor)) destructor()
{
    printf("[%s,%d]%s\n", __FILE__, __LINE__, __FUNCTION__);
}


int main(int argc, char *argv[])
{
    printf("test curl on qemu\n");
    //curl_global_init(CURL_GLOBAL_DEFAULT);

    return 0;
}
root@Vexpress:/mnt/linuxdev ./testcurl
[testcurl.c,7]preinit
[testcurl.c,12]init
[testcurl.c,26]constructor
test curl on qemu
[testcurl.c,31]destructor
[testcurl.c,17]fini
root@Vexpress:/mnt/linuxdev gdb ./testcurl
GNU gdb (GDB) 7.6
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /mnt/linuxdev/testcurl...done.
(gdb) b _start
Cannot access memory at address 0x8c1d
(gdb) b main
Breakpoint 1 at 0x8636: file testcurl.c, line 37.
(gdb) r
Starting program: /mnt/linuxdev/testcurl 
[testcurl.c,7]preinit
[testcurl.c,12]init
[testcurl.c,26]constructor

Breakpoint 1, main (argc=1, argv=0x7efffdf4) at testcurl.c:37
37	    printf("test curl on qemu\n");
(gdb) c
Continuing.
test curl on qemu
[testcurl.c,31]destructor
[testcurl.c,17]fini
[Inferior 1 (process 719) exited normally]
(gdb) quit
root@Vexpress:/mnt/linuxdev

**Comment by jay** [comment] 2017-11-10 07:37
ok but what happens in gdb when you uncomment the curl_global_init?

**Comment by zhouweiguo2017** [comment] 2017-11-10 07:48
root@Vexpress:/mnt/linuxdev ls
Makefile    external    testcurl    testcurl.c  testcurl.o
root@Vexpress:/mnt/linuxdev cat testcurl.c
#include <stdio.h>
#include <stdlib.h>
#include "curl/curl.h"

void preinit(int argc, char **argv, char **envp)
{
    printf("[%s,%d]%s\n", __FILE__, __LINE__, __FUNCTION__);
}

void init(int argc, char **argv, char **envp)
{
    printf("[%s,%d]%s\n", __FILE__, __LINE__, __FUNCTION__);
}

void fini()
{
    printf("[%s,%d]%s\n", __FILE__, __LINE__, __FUNCTION__);
}

__attribute__((section(".init_array"))) typeof(init) *__init = init;
__attribute__((section(".preinit_array"))) typeof(preinit) *__preinit = preinit;
__attribute__((section(".fini_array"))) typeof(fini) *__fini = fini;

void __attribute__ ((constructor)) constructor()
{
    printf("[%s,%d]%s\n", __FILE__, __LINE__, __FUNCTION__);
}

void __attribute__ ((destructor)) destructor()
{
    printf("[%s,%d]%s\n", __FILE__, __LINE__, __FUNCTION__);
}


int main(int argc, char *argv[])
{
    printf("test curl on qemu\n");
    curl_global_init(CURL_GLOBAL_DEFAULT);

    return 0;
}
root@Vexpress:/mnt/linuxdev ./testcurl
root@Vexpress:/mnt/linuxdev gdb ./testcurl
GNU gdb (GDB) 7.6
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /mnt/linuxdev/testcurl...random: fast init done
done.
(gdb) set disassemble-next-line on
(gdb) dir ./external/curl-7.56.1/lib/
Display all 455 possibilities? (y or n)
(gdb) dir ./external/curl-7.56.1/lib 
Source directories searched: /mnt/linuxdev/./external/curl-7.56.1/lib:$cdir:$cwd
(gdb) disas/m _start
Dump of assembler code for function _start:
   0x00009430 <+0>:	mov.w	r11, #0
   0x00009434 <+4>:	mov.w	lr, #0
   0x00009438 <+8>:	ldr.w	r1, [sp], #4
   0x0000943c <+12>:	mov	r2, sp
   0x0000943e <+14>:	str.w	r2, [sp, #-4]!
   0x00009442 <+18>:	str.w	r0, [sp, #-4]!
   0x00009446 <+22>:	ldr.w	r12, [pc, #20]	; 0x945c <_start+44>
   0x0000944a <+26>:	str.w	r12, [sp, #-4]!
   0x0000944e <+30>:	ldr	r0, [pc, #16]	; (0x9460 <_start+48>)
   0x00009450 <+32>:	ldr	r3, [pc, #16]	; (0x9464 <_start+52>)
   0x00009452 <+34>:	blx	0x9230 <__libc_start_main>
   0x00009456 <+38>:	blx	0x93e8 <abort>
   0x0000945a <+42>:	ldrbpl	r0, [r9, -r0]!
   0x0000945e <+46>:	ldrls	r0, [r9, -r3]!
   0x00009462 <+50>:	ldrpl	r0, [r5, -r0]!
   0x00009466 <+54>:	blmi	0xc947a
End of assembler dump.
(gdb) b *0x9430
Breakpoint 1 at 0x9430
(gdb) b _start
Breakpoint 2 at 0x944a
(gdb) b main
Breakpoint 3 at 0x9742: file testcurl.c, line 37.
(gdb) r
Starting program: /mnt/linuxdev/testcurl 
[Inferior 1 (process 663) exited with code 01]
(gdb)

**Comment by jay** [comment] 2017-11-10 07:58
I have no idea. Maybe it can't find a dependency? Try strace and see where it dies

**Comment by zhouweiguo2017** [comment] 2017-11-10 08:05
thanks so much. this issue is so strange and trouble me about two days.  

the fake libcurl.a as following  could works fine on the board:

linuxdev:$ ls
curl.c  curl.o  libcurl.a  Makefile
linuxdev:$ cat curl.c
#include <stdio.h>
#include "curl/curl.h"

CURLcode curl_global_init(long flags)
{
    printf("[%s,%d]enter %s\n", __FILE__, __LINE__, __FUNCTION__);
    printf("[%s,%d]enter %s\n", __FILE__, __LINE__, __FUNCTION__);
    printf("[%s,%d]enter %s\n", __FILE__, __LINE__, __FUNCTION__);
    printf("[%s,%d]enter %s\n", __FILE__, __LINE__, __FUNCTION__);
}
linuxdev:$ 

and I hacked source codes in lib/easy.c, when comments some code in the lib/easy.c, the generated libcurl.a could works fine on the board. So strange!!

**Comment by zhouweiguo2017** [comment] 2017-11-10 09:24
@jay, thanks for your patience and help. and guide me another/RIGHT way to troubleshooting the issue--- I spent about 1-2 two days to research and compare the disassembler code.  this issue could be resolved with another toolchain. it's just a workaround and the final root cause of the issue mightbe need more efforts to dig out.

linuxdev:$ ./arm-linux-gnueabihf-gcc -v
Using built-in specs.
COLLECT_GCC=./arm-linux-gnueabihf-gcc
COLLECT_LTO_WRAPPER=/ismp/optee/toolchains/aarch32/bin/../libexec/gcc/arm-linux-gnueabihf/6.2.1/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: /home/tcwg-buildslave/workspace/tcwg-make-release/label/docker-trusty-amd64-tcwg-build/target/arm-linux-gnueabihf/snapshots/gcc-linaro-6.2-2016.11/configure SHELL=/bin/bash --with-mpc=/home/tcwg-buildslave/workspace/tcwg-make-release/label/docker-trusty-amd64-tcwg-build/target/arm-linux-gnueabihf/_build/builds/destdir/x86_64-unknown-linux-gnu --with-mpfr=/home/tcwg-buildslave/workspace/tcwg-make-release/label/docker-trusty-amd64-tcwg-build/target/arm-linux-gnueabihf/_build/builds/destdir/x86_64-unknown-linux-gnu --with-gmp=/home/tcwg-buildslave/workspace/tcwg-make-release/label/docker-trusty-amd64-tcwg-build/target/arm-linux-gnueabihf/_build/builds/destdir/x86_64-unknown-linux-gnu --with-gnu-as --with-gnu-ld --disable-libstdcxx-pch --disable-libmudflap --with-cloog=no --with-ppl=no --with-isl=no --disable-nls --enable-c99 --enable-gnu-indirect-function --disable-multilib --with-tune=cortex-a9 --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-mode=thumb --enable-multiarch --with-build-sysroot=/home/tcwg-buildslave/workspace/tcwg-make-release/label/docker-trusty-amd64-tcwg-build/target/arm-linux-gnueabihf/_build/sysroots/arm-linux-gnueabihf --enable-lto --enable-linker-build-id --enable-long-long --enable-shared --with-sysroot=/home/tcwg-buildslave/workspace/tcwg-make-release/label/docker-trusty-amd64-tcwg-build/target/arm-linux-gnueabihf/_build/builds/destdir/x86_64-unknown-linux-gnu/arm-linux-gnueabihf/libc --enable-languages=c,c++,fortran,lto --enable-checking=release --disable-bootstrap --build=x86_64-unknown-linux-gnu --host=x86_64-unknown-linux-gnu --target=arm-linux-gnueabihf --prefix=/home/tcwg-buildslave/workspace/tcwg-make-release/label/docker-trusty-amd64-tcwg-build/target/arm-linux-gnueabihf/_build/builds/destdir/x86_64-unknown-linux-gnu
Thread model: posix
gcc version 6.2.1 20161016 (Linaro GCC 6.2-2016.11)

**Comment by bagder** [comment] 2017-11-10 16:25
To me, this looks like a toolchain problem and not a curl problem...

**Comment by jay** [comment] 2017-11-11 08:21
I tried a linaro vexpress image but I couldn't reproduce this. I cross compiled the reporter's testcurl.c and libcurl example [simple.c](https://github.com/curl/curl/blob/curl-7_56_1/docs/examples/simple.c) against cross compiled static libcurl.a. They and the curl tool worked ok in both qemu user mode and qemu arm system using linaro modified kernel.

~~~
curl 7.56.1 (arm-unknown-linux-gnueabihf) libcurl/7.56.1
Release-Date: 2017-10-23
Protocols: dict file ftp gopher http imap pop3 rtsp smtp telnet tftp 
Features: AsynchDNS IPv6 Largefile UnixSockets 
~~~

~~~
# root@genericarmv7a:~# ./testcurl
preinit
init
constructor
test curl on qemu
destructor
fini
~~~

Full instructions to reproduce in Ubuntu 16 LTS host:
~~~shell
sudo apt-get install qemu gcc-arm-linux-gnueabihf pkg-config-arm-linux-gnueabihf

mkdir ~/cross-compile-arm
cd ~/cross-compile-arm

curl --fail --location --remote-name-all https://curl.haxx.se/download/curl-7.56.1.tar.gz{,.asc}

gpg --recv-keys 27EDEAF22F3ABCEB50DB9A125CC908FDB71E12C2
gpg --verify curl-7.56.1.tar.gz.asc
tar xfz curl-7.56.1.tar.gz

cd curl-7.56.1
./configure --host=arm-linux-gnueabihf --prefix=`realpath ~/cross-compile-arm/root`
make
make install

mkdir ~/cross-compile-arm/linaro
cd ~/cross-compile-arm/linaro

curl -fOL http://releases.linaro.org/openembedded/vexpress-lsk/15.07/lsk-vexpress-openembedded_alip-armv7a-gcc-4.9_20150725-725.img.gz
echo "e74cd157e0366331a6329b258360dc9bc62b7c547e7f0a69bc24d85429691bea *lsk-vexpress-openembedded_alip-armv7a-gcc-4.9_20150725-725.img.gz" | sha256sum -c

# warning: unzipped image is 3gb
gzip -d lsk-vexpress-openembedded_alip-armv7a-gcc-4.9_20150725-725.img.gz

# Extract bootargs and uImage file needed to boot
sudo mkdir /mnt/tmp
sudo mount -o ro,loop,offset=$((63*512)) lsk-vexpress-openembedded_alip-armv7a-gcc-4.9_20150725-725.img /mnt/tmp
cp /mnt/tmp/uImage .
# note the bootargs, which should be passed to qemu
cat /mnt/tmp/boot.txt | grep bootargs
sudo umount /mnt/tmp

# Boot image.
# https://wiki.linaro.org/PeterMaydell/QemuVersatileExpress
# Modified:
# - Using uImage instead of vmlinuz since there's no initrd.
# - Using 256MB of RAM instead of 1GB since I'm in a VM with limited RAM.
# - Using tcp redirect so I can use scp to copy files.
sudo qemu-system-arm -kernel uImage -M vexpress-a9 -cpu cortex-a9 -m 256 -append 'console=ttyAMA0,38400n8  root=/dev/mmcblk0p2 rootwait ro mem=256M ip=dhcp clcd=xvga mmci.fmax=4000000' -sd lsk-vexpress-openembedded_alip-armv7a-gcc-4.9_20150725-725.img -nographic --redir tcp:2200::22

#
# TERM#1 is guest (linaro vexpress).
#

# Set root passwd for ssh
passwd

#
# TERM#2 is host (Ubuntu 16).
#

# Build the test files and copy them in.
cd ~/cross-compile-arm/root/lib

cat > testcurl.c
# contents removed for brevity, see first post

# Check that reporter's sample works in qemu user mode:
arm-linux-gnueabihf-gcc -I../include testcurl.c -o testcurl ./libcurl.a -lpthread
qemu-arm -L /usr/arm-linux-gnueabihf/ ./testcurl

# Check that libcurl simple.c example works in qemu user mode:
arm-linux-gnueabihf-gcc -I../include ~/cross-compile-arm/curl-7.56.1/docs/examples/simple.c -o simple ./libcurl.a -lpthread
qemu-arm -L /usr/arm-linux-gnueabihf/ ./simple

# Copy all relevant files to guest
scp -P 2200 ../bin/curl libcurl.so.4.5.0 simple testcurl root@localhost:.

#
# TERM#1 is guest (linaro vexpress).
#

# Test the programs
LD_PRELOAD=./libcurl.so.4.5.0 ./curl -V
LD_PRELOAD=./libcurl.so.4.5.0 ./curl google.com
./simple
./testcurl

# Done
shutdown -h -P now

#
# TERM#1 is host (Ubuntu 16).
#
~~~

**Comment by zhouweiguo2017** [comment] 2017-11-13 03:58
@jay, thanks for your efforts for this issue.

this issue could be reproduced with the toolchain as following (which used in my side):

wget https://launchpadlibrarian.net/132207760/gcc-linaro-arm-linux-gnueabihf-4.7-2013.02-01-20130221_linux.tar.xz

this issue mighbe a toolchain dependent issue according to bagder's comments.

**Comment by jay** [comment] 2017-11-13 04:05
I agree. That is outside the scope of curl so I'm closing.

**Closed by jay** 2017-11-13 04:05 UTC
Labels: build
