### ISSUE TITLE
curl 4.ident.me → curl: (3) URL using bad/illegal format or missing URL

### ISSUE THREAD

**Issue by pcarrier** [curl/curl#11214] opened 2023-05-28 02:44 UTC
### I did this

```
$ curl 4.ident.me
curl: (3) URL using bad/illegal format or missing URL
```

### I expected the following

```
$ curl 4.ident.me
185.57.32.117
```

### curl/libcurl version

Bisected the regression down to `17a15d884677e72d1f23c9249365e88af375f04a`.

```
curl 8.1.0-DEV (aarch64-apple-darwin22.4.0) libcurl/8.1.0-DEV zlib/1.2.11 libidn2/2.3.4 nghttp2/1.53.0
Release-Date: [unreleased]
Protocols: dict file ftp gopher http imap ldap ldaps mqtt pop3 rtsp smtp telnet tftp
Features: alt-svc AsynchDNS HTTP2 IDN IPv6 Largefile libz threadsafe UnixSockets
```

### operating system

```
Darwin wildcat.lan 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:01:02 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8112 arm64
```

**Comment by dfandrich** [comment] 2023-05-28 04:08
Duplicate of #11129

**Closed by dfandrich** 2023-05-28 04:08 UTC
