### ISSUE TITLE
Unable to compile cURL 7.66 under Visual Studio

### ISSUE THREAD

**Issue by lllaffer** [curl/curl#4364] opened 2019-09-16 08:49 UTC
### I did this
I use to compile cURL under Win 7 32, Visual Studio 2015/2017/2019

... nmake /f Makefile.vc VC=%VC% MACHINE=x86 mode=static WITH_DEVEL=z:\ WITH_SSL=dll WITH_SSH2=dll WITH_ZLIB=dll 

This (still) works fine for cURL before version 7.66.
Compilation of 7.66 throws error:

	LINK : fatal error LNK1181: cannot open input file "..\builds\libcurl-vc15-x86-release-static-ssl-dll-zlib-dll-ssh2-dll-ipv6-sspi-obj-lib\vssh\libssh2.obj"

### I expected the following
to compiles as it used to

### curl/libcurl version
7.66

### operating system
Win 7 32
Visual Studio 2015/2017/2019

### thx for your attention

Any advice ? ... Is there hope ? ... Am I alone ?

**Comment by bagder** [comment] 2019-09-16 08:54
Duplicate of #4322 - already fixed in git via #4323

**Closed by bagder** 2019-09-16 08:54 UTC

**Comment by lllaffer** [comment] 2019-09-16 09:49
The instruction goes like this:

	* download: master https://github.com/curl/curl
	* replace folder winbuild\
	* recompile
! joy
thx
