### ISSUE TITLE
Requests with threaded resolver slowed down

### ISSUE THREAD

**Issue by jovandeginste** [curl/curl#2636] opened 2018-06-05 14:40 UTC
We use Shibboleth, which is linked against `libcurl.so` (curl with openssl). We noticed that `shibd -t` was "fast" on some servers (2s) and "slow" on others (13s). After investigating, we noticed the difference was the version of libcurl: upgrading/downgrading `libcurl.so` alone made the test go fast or slow. The tests were run on CentOS 6 & CentOS 7 using Shibboleth's own libcurl-openssl, and my `libcurl.so` built from this repository.

Further investigation with `git bisect` told me that the slow-down started with this commit: 5113ad0424044458ac497fa1458ebe0101356b22
Fiddling with the source code, then told me this specific change appeared to introduce the delay:
https://github.com/curl/curl/commit/5113ad0424044458ac497fa1458ebe0101356b22#diff-34fcd5a6dcf246c01850a323e7bd3a8eL1372

I'm not entirely sure how it should be fixed; I have tried two approaches. I'm willing to write a PR, but since I have not sufficient knowledge of the code base, I would appreciate some feedback first.

This would seem the most reasonable fix:

```diff
--- a/lib/http.c
+++ b/lib/http.c
@@ -1369,7 +1369,7 @@ CURLcode Curl_http_connect(struct connectdata *conn, bool *done)
   if(CONNECT_FIRSTSOCKET_PROXY_SSL())
     return CURLE_OK; /* wait for HTTPS proxy SSL initialization to complete */
 
-  if(!Curl_connect_complete(conn))
+  if(conn->connect_state && !Curl_connect_complete(conn))
     /* nothing else to do except wait right now - we're not done here. */
     return CURLE_OK;
```

Alternatively, this would fix it for my tests too, but I think it is not what you would expect from that function:

```diff
--- a/lib/http_proxy.c
+++ b/lib/http_proxy.c
@@ -137,7 +137,7 @@ CURLcode Curl_proxy_connect(struct connectdata *conn, int sockindex)
 
 bool Curl_connect_complete(struct connectdata *conn)
 {
-  return conn->connect_state &&
+  return !conn->connect_state ||
     (conn->connect_state->tunnel_state == TUNNEL_COMPLETE);
 }
```

**Comment by bagder** [comment] 2018-06-05 15:07
What version are you seeing the problem in? Commit 9ef50ee0a436a via #1853 changed a few things in that territory.

**Comment by jovandeginste** [comment] 2018-06-05 15:15
I bisected between master and 7.51. I see now when going back up the chain some changes were made indeed (and something that resembles my fix). I'll try again with master right now.

**Comment by jovandeginste** [comment] 2018-06-05 15:16
So I double checked and do see the performance regression on master (a8324599d236930208510faf7ccaef91214e69fc)

**Comment by jovandeginste** [comment] 2018-06-05 15:17
(as a sidenote, the last fix I suggested seems to have been the right one, so yay none-the-less I guess...)

**Comment by bagder** [comment] 2018-06-05 15:29
Right, that fix is already in. But if you're still seeing the regression that clearly wasn't enough.

Can you elaborate on what you do to reproduce/see this issue? I rather not build, learn and run Shibboleth to do that... =)

**Comment by jovandeginste** [comment] 2018-06-05 15:37
I tried reproducing it without Shibboleth, but got stuck on that track :-)

Basically, shibboleth iterates over some resources (HTTPS URI's), fetches those and parses its configuration wrt. those external resources. I added some debug prints in the `Curl_http_connect` (before every `if(...) return CURLE_OK;`), I see it gets called 6 times and every time goes all the way to the final return. However, it takes 2 seconds between every invocation of `Curl_http_connect`, so I will add more debug prints :-)

**Comment by jovandeginste** [comment] 2018-06-05 15:49
FWIW, I just tried using 1ae2704d6edf02c218b7e30fc2e13ce52a991bea (the first commit after 9ef50ee0a436aeaa05adc9d78fda57e3ef53233e that successfully compiled), but it's slow too. I have to quit for the day, tomorrow I can try bisecting between 9ef50ee0a436aeaa05adc9d78fda57e3ef53233e and 5113ad0424044458ac497fa1458ebe0101356b22 (every time adding the patch) to see if I can find a new culprit ...

**Comment by bagder** [comment] 2018-06-05 15:56
Cool, sounds like a good approach. Just let me know what I can do to help.

**Comment by rodwiddowson** [comment] 2018-06-05 15:58
@jovandeginste FMI can you share the non confidential bits of `shibboleth2.xml ` config with me?

I'd like to be prewarned before someone without your tenacity in bug finding comes along.  Thanks.

Rod

**Comment by jovandeginste** [comment] 2018-06-05 17:59
@rodwiddowson I have a hard time parsing the xml file myself, but I'm trying to reproduce using sample xml configuration.

**Comment by jovandeginste** [comment] 2018-06-05 18:10
So I did a new bisect, every time cherry-picking the patch from 9ef50ee0a436aeaa05adc9d78fda57e3ef53233e, and here is the new breaking point:
Last good: ac8af8452706aa0d5244adb34efcec072d389070
First bad: d86e9182e41050be508a5dfbaa3f7070b817a685

I will now try to build disabling the threaded resolver.

**Comment by jovandeginste** [comment] 2018-06-05 18:53
OK I was bitten by a bug at that stage, namely that `--disable-threaded-resolver` did nothing. I saw master was fixed, so I'm building master again with that option.

**Comment by jovandeginste** [comment] 2018-06-05 20:36
Could not find anything else for the time being. Would be great to find out how exactly shibboleth calls libcurl, but I can't seem to find anything...

In our shibboleth configuration, a total of 6 remote resources are listed, each take 2s to fetch (2s of "sleep"). The total process takes about 13.5s, so 1.5s for everything minus the sleeps. This is in line with the total runtime when threaded resolver is disabled.

So it would seem the threaded resolver adds 2 seconds to every fetch of a remote resource via libcurl.

**Comment by bagder** [comment] 2018-06-05 21:04
This sounds like at least partly a shibboleth issue. libcurl itself hardly waits for 2 seconds somewhere.

I suspect the source for this is because the multi interface is used, a threaded-resolver build doesn't have a socket to return back during the name resolving phase. So the user of libcurl needs to wait for a short while and then call again, in a polling manner. That's not necessary with the non-threaded resolver since then this phase of "no socket" doesn't exist - the name resolving is then done entirely synchronously (or you'd build to use c-ares to resolve names asynchronously, but c-ares would then have a socket to wait for)...

So yes, the next step is clearly to understand how libcurl is invoked and the logic around how/when it gets called again.

**Comment by rodwiddowson** [comment] 2018-06-06 05:20
Shib uses curl in several different places and ways, if you point me at the config (or snippet) We’ll point you at the code.  Or you could take it to our jira (shibboleth.net/issues) or there’s a dev list. But we’ll try to keep it in one place?  I’ve alert Scott (lead dev) to this case...

**Comment by jovandeginste** [comment] 2018-06-06 05:45
@rodwiddowson can I contact you through email so I can sanitize our shibboleth config before publishing it here? I can reproduce the issue in a Docker container.

@bagder would you prefer continue the thread here, or move it over to shibboleth (as it now appears to be an issue on their side)

**Comment by rodwiddowson** [comment] 2018-06-06 05:54
@jovandeginste  please do.

rdw _at_ steadingsoftware _dot_ com

**Comment by rodwiddowson** [comment] 2018-06-06 08:55
Can we keep the case here for now?  I have [created a case](https://issues.shibboleth.net/jira/browse/CPPXT-132) for this in Shibboleth in case work is needed, but lets keep the conversation centralized.

**Comment by bagder** [comment] 2018-06-06 08:58
I'm fine with keeping it here, as long as we manage to get the right people's attention on it.

**Comment by rodwiddowson** [comment] 2018-06-06 09:13
@bagder I'm by no means the expert in Shib's use of cUrl (I just play an expert on TV), but I'll make sure the any message gets to where it needs to.

@jovandeginste Without bottoming this out: if you are looking for code 

- If it's the back-channel processing (Artfifact resolution of attribute pull) that's is slow you want to look [here](http://git.shibboleth.net/view/?p=cpp-xmltooling.git;a=blob;f=xmltooling/soap/impl/CURLSOAPTransport.cpp;h=ca2d6743f5318b106353a6733446964c44f745ef;hb=HEAD)
- If it is loading configuration remotely [here ](http://git.shibboleth.net/view/?p=cpp-xmltooling.git;a=blob;f=xmltooling/util/CurlURLInputStream.cpp;h=24353e18c50e6e85f465a699e4f9ab82c740ced2;hb=HEAD) is a good place to start.

Further in the latter you want to tinker with the Curl Options you can use  [TransportOptions](https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPTransportOption)

**Comment by bagder** [comment] 2018-06-06 11:51
the code piece pointed to above seems to use libcurl's easy interface only, which then makes my "suspicion" as mentioned above totally wrong...

**Comment by dtzWill** [comment] 2018-06-06 12:13
http://git.shibboleth.net/view/?p=cpp-xmltooling.git;a=blob;f=xmltooling/util/CurlURLInputStream.cpp;h=24353e18c50e6e85f465a699e4f9ab82c740ced2;hb=HEAD#l559 has a 2sec timeout and uses multi interface, FWIW.

**Comment by bagder** [comment] 2018-06-06 12:20
thanks @dtzWill, that's likely the culprit here.

1. It uses a fixed time-out instead of using [curl_multi_timeout](https://curl.haxx.se/libcurl/c/curl_multi_timeout.html) . That will improve this code in several aspects, not only this.
2. Previous libcurl versions could also return "so socket" and "no timeout", for which situation I would advice an implementation to wait for "a short while" and then call libcurl again. (We recently changed so that libcurl will return a suitable timeout (slowly increasing) even for the no-socket period.)

**Comment by rodwiddowson** [comment] 2018-06-06 12:29
@bagder ignore me I see it 

> This function was added in libcurl 7.15.4.

**Comment by scantor** [comment] 2018-06-06 14:00
We can accept the case as a Shibboleth bug, but the code there was actually just copied from Xerces itself (so it likely has the same bug) and that was why I used an API I'm totally uncomfortable with (the important areas in the library use the synchronous stuff.

We have a pointer to the case here, so you can close it out.

I doubt I would risk fixing this at this stage of our cycle unless this impacts "normal" use, but the OP can take that up with us to clarify the conditions under which it has this problem.

**Comment by jovandeginste** [comment] 2018-06-06 15:47
@scantor Would it be a reasonable short-term patch to lower the timeout to (say) 200ms? I say this without reading the code or searching for any documentation or commit log references :-)

For our own servers, I just built an rpm that puts a libcurl.so file in a (different) folder in `/opt/shibboleth/`, (similar to `libcurl-openssl` to [here](https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPLinuxRH6)) and change the `LD_LIBRARY_PATH` to use my library.

**Comment by scantor** [comment] 2018-06-06 15:50
Please take this to https://issues.shibboleth.net/jira/browse/CPPXT-132, I don't want to keep bugging the curl team over this.

My willingness to fix this this late in the cycle depends on understanding the scope of the impact, since I can't reproduce it at the moment.

**Comment by bagder** [comment] 2018-06-06 21:10
Thanks all for the great team work. I consider this issue closed from our behalf.

**Closed by bagder** 2018-06-06 21:10 UTC
Labels: connecting & proxies, performance

**Comment by jovandeginste** [comment] 2018-06-07 08:19
@bagder I think this issue can be marked as fixed, since it was in the end no longer related to curl

**Comment by jovandeginste** [comment] 2018-06-07 08:19
@bagder happy to help!
