### ISSUE TITLE
Out of memory when using self signed server certificate in curl 7.82

### ISSUE THREAD

**Issue by AlienJust** [curl/curl#8582] opened 2022-03-11 07:23 UTC
I running own gitlab and gitea instances. I access them via HTTPS using self signed certificates.

### I did this
`curl --cacert ~/gitlab.crt https://123.171.44.21:40443`
(my real ip addr isn't this)

### I expected the following
curl **7.81** gives me:
`<html><body>You are being <a href="https://123.171.44.21:40443/users/sign_in">redirected</a>.</body></html>`

curl **7.82** gives me:
`curl: (27) Out of memory`

### curl/libcurl version
[curl -V output]
```
curl 7.82.0 (x86_64-pc-linux-gnu) libcurl/7.82.0 OpenSSL/1.1.1m zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0
Release-Date: 2022-03-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

### operating system
`Linux march 5.16.13-arch1-1 #1 SMP PREEMPT Tue, 08 Mar 2022 20:07:36 +0000 x86_64 GNU/Linux`

**Comment by bagder** [comment] 2022-03-11 07:31
Duplicate of #8559

But yes, this is a bug with certificates that use CN-only. A banned practice in public CAs.

**Comment by danielgustafsson** [comment] 2022-04-21 07:53
Since the issue was fixed and will ship in the next release, is there any reason to keep this issue opened?

**Comment by bagder** [comment] 2022-04-21 08:06
No

**Closed by bagder** 2022-04-21 08:06 UTC
Labels: regression, TLS, duplicate
