### ISSUE TITLE
curl_easy_perform() fails to time out.

### ISSUE THREAD

**Issue by dwmw2** [curl/curl#5137] opened 2020-03-22 14:28 UTC
In https://github.com/domoticz/domoticz/issues/3975 it appears that a call to curl_easy_perform() is not returning, despite the `CURLOPT_TIMEOUT` and `CURLOPT_CONNECTTIMEOUT` options both being set (to 10 and 90 respectively).

This is on OpenWRT mips32, curl 7.60.3. Domoticz also uses `CURLOPT_NOSIGNAL`: 
https://github.com/domoticz/domoticz/blob/development/httpclient/HTTPClient.cpp#L97

**Comment by jay** [comment] 2020-03-22 18:41
We're on 7.69.1 now so try the latest version and enable verbose to see what's up. If you still have the issue give us a self-contained example to reproduce (if possible), your curl_version() and the resolver. The only thing I can think of still open is #4852, "Multi perform hang waiting for threaded resolver".

~~~c
  curl_version_info_data *ver = curl_version_info(CURLVERSION_NOW);
  
  if(!(ver->features & CURL_VERSION_ASYNCHDNS))
    printf("synchronous\n");
  else if(!ver->age || ver->ares_num)
    printf("ares\n");
  else
    printf("threaded\n");
~~~

_(On a related note if you intend to switch over to multi, as you suggest in that issue, be warned [CURLOPT_TIMEOUT](https://curl.haxx.se/libcurl/c/CURLOPT_TIMEOUT.html) counts queue time. Also, internally, the easy interface uses the multi interface.)_

**Comment by bagder** [comment] 2020-03-23 09:35
My **guess**: this looks and feels like a dead/slow name resolve call with the stock synchronous name resolver that without the use of signals have no way to abort it.

**Comment by dwmw2** [comment] 2020-03-23 21:16
OK, updated to 7.69.1 and threaded resolver enabled. Will see if it recurs. Thanks.

**Comment by bagder** [comment] 2020-04-02 22:21
@dwmw2 do you think we can close this now ?

**Comment by dwmw2** [comment] 2020-04-03 06:11
It happens much less now, but I have seen it at least once more with 7.69.1 and the threaded resolver. I need to make gdb work on this platform so I can investigate further.

**Comment by dwmw2** [comment] 2020-04-10 11:42
Definitely still happening. Annoyingly it was quite repeatable for a while yesterday, while I was AFK and couldn't properly investigate. I've now rebuilt libcurl for the embedded device with verbose strings, and enabled debugging but it doesn't seem to say anything until very late, after DNS resolution is already done:

```
Fri Apr 10 12:37:05 2020 daemon.info domoticz: SQLH UpdateValueInt Gas Temperature (left) HwID:2  DevID:82438 Type:80  sType:5 nValue:0 sValue:12.19
Fri Apr 10 12:37:05 2020 daemon.info domoticz: Curl using threaded resolver
Fri Apr 10 12:37:05 2020 daemon.info domoticz: HTTP GET: curl init...
Fri Apr 10 12:37:05 2020 daemon.info domoticz: HTTP: curl global timeout 10, connection timeout 90
Fri Apr 10 12:37:05 2020 daemon.info domoticz: HTTP GET: curl perform...
Fri Apr 10 12:37:05 2020 daemon.info domoticz: Curl debug:   Trying 52.72.33.25:443...
```

If this really is a resolver issue, that's going to lock up without ever seeing that first `Trying 52.72.33.25:443...` debug line from curl, isn't it?

In the short term, can I work around this just by putting IP addresses into /etc/hosts for the two hosts I'm trying to reach from my home automation system?

**Comment by dwmw2** [comment] 2020-04-13 07:57
Hm, perhaps not DNS. With debug enabled, this is the last thing I see from the thread using curl...
```
Apr 13 00:27:00 wndr3800.infradead.org domoticz: EventSystem: Script event triggered: /usr/share/domoticz/dzVents/runtime/dzVents.lua
Apr 13 00:27:00 wndr3800.infradead.org domoticz: SQLH: Do Task ItemType:6 Cmd: Value:https://app.api.surehub.io/api/device/422826/tag
Apr 13 00:27:00 wndr3800.infradead.org domoticz: HTTP GET: curl init...
Apr 13 00:27:00 wndr3800.infradead.org domoticz: HTTP: curl global timeout 10, connection timeout 90
Apr 13 00:27:00 wndr3800.infradead.org domoticz: HTTP GET: curl perform...
Apr 13 00:27:00 wndr3800.infradead.org domoticz: Curl debug:   Trying 34.195.171.241:443...
Apr 13 00:27:00 wndr3800.infradead.org domoticz: Curl debug: Connected to app.api.surehub.io (34.195.171.241) port 443 (#0)
Apr 13 00:27:00 wndr3800.infradead.org domoticz: Curl debug: ALPN, offering http/1.1
Apr 13 00:27:00 wndr3800.infradead.org domoticz: Curl debug: Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
```

On a *successful* invocation it would continue...

```
Apr 13 00:26:00 wndr3800.infradead.org domoticz: Curl debug: Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
Apr 13 00:26:01 wndr3800.infradead.org domoticz: Curl debug: successfully set certificate verify locations:
Apr 13 00:26:01 wndr3800.infradead.org domoticz: Curl debug:   CAfile: /etc/ssl/certs/ca-certificates.crt   CApath: none
Apr 13 00:26:01 wndr3800.infradead.org domoticz: Curl debug: TLSv1.2 (OUT), TLS header, Certificate Status (22):
```

**Comment by dwmw2** [comment] 2020-04-13 08:16
This is on OpenWRT 18.06, built against OpenSSL 1.0.2. I don't actually see *anything* that could block between those points in `ossl_connect_step1()`. In fact since this is OpenSSL 1.0.2 and I'm not using SRP auth, there isn't *anything* happening between the `infof()` that I see, and the call to `SSL_CTX_load_verify_locations()`. Not even anything that could use a blocking random, which was my first though. Will debug further...

**Comment by dwmw2** [comment] 2020-04-25 08:48
```
Apr 25 03:21:00 wndr3800.infradead.org domoticz: HTTP GET: curl perform...
Apr 25 03:21:00 wndr3800.infradead.org domoticz: Curl debug:   Trying 52.0.17.134:443...
Apr 25 03:21:00 wndr3800.infradead.org domoticz: Curl debug: Connected to app.api.surehub.io (52.0.17.134) port 443 (#0)
Apr 25 03:21:00 wndr3800.infradead.org domoticz: Curl debug: ALPN, offering http/1.1
Apr 25 03:21:00 wndr3800.infradead.org domoticz: Curl debug: OpenSSL cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
Apr 25 03:21:00 wndr3800.infradead.org domoticz: Curl debug: Will load verify locations (/etc/ssl/certs/ca-certificates.crt, none)
```

It really looks like it's in `SSL_CTX_load_verify_locations()`, because I've now added an `infof()` immediately before it *(which we see)*, and there's an `infof()` or `failf()` after it in every circumstance too which we *don't* see.

```
    /* tell SSL where to find CA certificates that are used to verify
       the servers certificate. */
    infof(data, "Will load verify locations (%s, %s)\n",
          ssl_cafile ? ssl_cafile : "none",
          ssl_capath ? ssl_capath : "none");

    if(!SSL_CTX_load_verify_locations(BACKEND->ctx, ssl_cafile, ssl_capath)) {
      if(verifypeer) {
        /* Fail if we insist on successfully verifying the server. */
        failf(data, "error setting certificate verify locations:\n"
              "  CAfile: %s\n  CApath: %s",
              ssl_cafile ? ssl_cafile : "none",
              ssl_capath ? ssl_capath : "none");
        return CURLE_SSL_CACERT_BADFILE;
      }
      /* Just continue with a warning if no strict  certificate verification
         is required. */
      infof(data, "error setting certificate verify locations,"
            " continuing anyway:\n");
    }
    else {
      /* Everything is fine. */
      infof(data, "successfully set certificate verify locations:\n");
    }
    infof(data,
          "  CAfile: %s\n"
          "  CApath: %s\n",
          ssl_cafile ? ssl_cafile : "none",
          ssl_capath ? ssl_capath : "none");
  }
```

I'm confused. I cannot see how `SSL_CTX_load_verify_locations()` could stall. Kind of wish I had a working gdb on this platform...

**Comment by jay** [comment] 2020-04-25 18:40
> I cannot see how `SSL_CTX_load_verify_locations()` could stall. Kind of wish I had a working gdb on this platform...

Maybe it is slowing down because there are a lot of certificates in the bundle and they are parsed at that time. Or it is blocking on read because another process has it open. Sprinkle printfs in [X509_load_cert_crl_file](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2u/crypto/x509/by_file.c#L244) for bundles and [add_cert_dir](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2u/crypto/x509/by_dir.c#L198) for directories. AFAICT the latter is a lot less likely to be a problem because when it adds a cert directory it doesn't actually parse anything it just makes note that certificate hash filenames are in that directory.

**Comment by dwmw2** [comment] 2020-04-26 06:56
It isn't just stalling and introducing a bit of latency and destroying real-time performance. It *never* comes back. It's occasionally been ten hours or so before I've noticed and reset it.

**Comment by jay** [comment] 2020-07-22 03:33
I don't think this is a libcurl problem. If you figure out what is causing it please update the thread.

**Closed by jay** 2020-07-22 03:33 UTC
Labels: SSL/TLS

**Comment by dwmw2** [comment] 2020-07-22 06:44
I upgraded the host to OpenWrt 19.07, with a newer version of OpenSSL, and the problem went away.

I concur, it probably wasn't curl itself.
