### ISSUE TITLE
Serious issues with unstable networks

### ISSUE THREAD

**Issue by NightMachinary** [curl/curl#2423] opened 2018-03-23 13:34 UTC
curl is terrible with unstable connections to the point of being unusable. Unfortunately most of the tools I need to use are implemented in a way that forgoing curl is not an option. The end result is a world of very unnecessary suffering.
What I propose is a flag settable in .curlrc that makes curl try to resume the download when retrying instead of just starting from the beginning. Another flag to set good timeouts and retry counts for unstable networks automatically is also very appreciated. Inspiration can be found in wget, that beast is just immune to network bumps!

PS: Changing to a better network is not an option here, developing countries' problems. 
PPS: My current .curlrc:
```
retry = 999
max-time = 300
continue = "-"
#retry-max-time = 0
```

**Comment by bagder** [comment] 2018-03-23 13:41
See [TODO](https://curl.haxx.se/docs/todo.html#retry_should_resume). Duplicate of #1084.

**Comment by bagder** [comment] 2018-04-04 09:26
See #2450

**Closed** 2018-05-21 21:37 UTC
Labels: cmdline tool, feature-request, help wanted
