### ISSUE TITLE
[Bug] "--connect-to", "--resolve" options don't seem to work properly

### ISSUE THREAD

**Issue by MasterInQuestion** [curl/curl#9153] opened 2022-07-14 04:43 UTC
&#xA0;&#xA0;&#xA0;&#xA0;The below command (Unix Shell):
[[
&#xA0;&#xA0;&#xA0;&#xA0;curl --trace '%' --connect-to 'example.com:443:162.159.137.85:443' -H 'Host: crypto.cloudflare.com' 'https://example.com/cdn-cgi/trace' -k;
]]
, and its "--resolve" variant comparable: don't seem to work as described in the documentation:
&#xA0;&#xA0;&#xA0;&#xA0;The connection seems to be directly made to "example.com" instead.

&#xA0;&#xA0;&#xA0;&#xA0;Related: [https://github<i>.</i>com/curl/curl/pull/5239#issuecomment-1042299222](https://github.com/curl/curl/pull/5239#issuecomment-1042299222)
\
\
\
\
== Additional info ==

[1] Using &#x60;--connect-to 'example.com:443:1.2.3.4:443'&#x60; in the example generates practically identical result.
[2] Changing all "example.com" related parts to "www.google.com" returns the error page from Google.
[3] &#x60;--connect-to 'example.com:443:127.0.0.1:443'&#x60; (and the "--resolve" type) seem to work as intended though.

**Comment by bagder** [comment] 2022-07-14 21:45
I cannot reproduce. You also forgot to tell us what curl version on what operating etc.

**Comment by MasterInQuestion** [comment] 2022-07-14 22:20
<pre style="white-space: pre-wrap; word-wrap: break-word; tab-size: 4">
	It was reproduced with 7.71.1 (Windows) and 7.82 (Unix), probably related with OpenSSL.

	Would you please give the command output and `curl -V`?
</pre>

**Comment by bagder** [comment] 2022-07-14 22:31
Here's curl 7.84.0 output on my debian linux:
~~~
$ curl --trace '%' --connect-to 'example.com:443:162.159.137.85:443' -H 'Host: crypto.cloudflare.com' 'https://example.com/cdn-cgi/trace' -k;
== Info: Connecting to hostname: 162.159.137.85
== Info: Connecting to port: 443
== Info:   Trying 162.159.137.85:443...
== Info: Connected to 162.159.137.85 (162.159.137.85) port 443 (#0)
== Info: ALPN: offers h2
== Info: ALPN: offers http/1.1
== Info: TLSv1.0 (OUT), TLS header, Certificate Status (22):
=> Send SSL data, 5 bytes (0x5)
0000: 16 03 01 02 00                                  .....
== Info: TLSv1.3 (OUT), TLS handshake, Client hello (1):
=> Send SSL data, 512 bytes (0x200)
0000: 01 00 01 fc 03 03 20 29 1d f4 6b 57 10 8d da 62 ...... )..kW...b
0010: 6e 32 2a 76 ba 14 6b 5c 34 db 9a c8 e9 a8 36 88 n2*v..k\4.....6.
0020: e4 a3 4f 96 83 25 20 65 6c 94 1c 3e ca 7e a9 56 ..O..% el..>.~.V
0030: 3b 1e a6 31 8a 19 5f 9c cf 73 f0 f8 29 fe 2d f0 ;..1.._..s..).-.
0040: 04 2e 7e 08 c9 aa 1c 00 3e 13 02 13 03 13 01 c0 ..~.....>.......
~~~

Looks like it connects to the specified host ?

**Comment by MasterInQuestion** [comment] 2022-07-15 00:31
&#xA0;&#xA0;&#xA0;&#xA0;Did you get HTTP 404 at last? The specified host ("162.159.137.85" [1]) in the request should not return that.
&#xA0;&#xA0;&#xA0;&#xA0;Also try the variations in # Additional info; and check more carefully.
[1] Which is attained through [ https://dns.google/query?name=crypto.cloudflare.com ].
\
\
=== Off-Topic ===

&#xA0;&#xA0;&#xA0;&#xA0;The bothersome Markdown rendering:
&#xA0;&#xA0;&#xA0;&#xA0;[
&#xA0;&#xA0;&#xA0;&#xA0;|&#x2A;| [Markdown] Add proper "white-space" handling for Markdown rendering
&#xA0;&#xA0;&#xA0;&#xA0;|&#x2A;| https://github.com/github-community/community/discussions/16929 ]

**Comment by jay** [comment] 2022-07-15 07:40
I tried this just now using curl master and cloudflare returns TLS alert unrecognized name. That is because the TLS SNI sent to the server is example.com as expected.

~~~
Transport Layer Security
    TLSv1.2 Record Layer: Alert (Level: Fatal, Description: Unrecognized Name)
        Content Type: Alert (21)
        Version: TLS 1.2 (0x0303)
        Length: 2
        Alert Message
~~~

**Comment by MasterInQuestion** [comment] 2022-07-15 09:11
&#xA0;&#xA0;&#xA0;&#xA0;So supposedly there should be a recent change (since commit [e9a2eced69effdc77326a58625fcfce04c9301c5](https://github.com/curl/curl/commit/e9a2eced69effdc77326a58625fcfce04c9301c5)) that caused the difference?

**Comment by jay** [comment] 2022-07-15 18:22
I doubt it, I don't see how that could possibly be related. You are relying on cloudflare not rejecting an arbitrary SNI and you just can't rely on that, especially with cloudflare which may use the SNI to route the connection to the correct backend server.

**Comment by jay** [comment] 2022-07-15 18:49
Sending `www.google.com` to that cloudflare IP also returns `tlsv1 unrecognized name`. As explained in the man page [--connect-to](https://curl.se/docs/manpage.html#--connect-to) does not change the SNI. If you can't show that connect-to is not working properly I will close this issue.

**Comment by jay** [comment] 2022-07-16 05:28
> But "--connect-to", "--resolve" don't seem to (at least in some versions) make the connection to the correct host.

You haven't shown that, you haven't provided the output and we were unable to reproduce with the command line you've given us, so I'm closing this.

> Is the main post really that difficult to understand, or my writing has been exceptionally poor that made things extraordinarily incomprehensible..?

Possibly some of it is lost in translation.

**Closed by jay** 2022-07-16 05:28 UTC
Labels: cmdline tool, connecting & proxies

**Comment by MasterInQuestion** [comment] 2022-07-16 06:00
&#xA0;&#xA0;&#xA0;&#xA0;Er... needless to haste so much I suppose.
&#xA0;&#xA0;&#xA0;&#xA0;.
&#xA0;&#xA0;&#xA0;&#xA0;[ Quote MasterInQuestion @ CE 2022-07-15 05:32:44 UTC:
[https://github<i>.</i>com/curl/curl/issues/9153#issuecomment-1184950581](https://github.com/curl/curl/issues/9153#issuecomment-1184950581)
&#xA0;&#xA0;&#xA0;&#xA0;The behavior is also verified with 7.84 (from [ [https://curl.se/windows/dl-7.84.0_5/curl-7.84.0_5-win64-mingw.zip](https://curl.se/windows/dl-7.84.0_5/curl-7.84.0_5-win64-mingw.zip) ]). ]
<.>&#xA0;&#xA0;&#xA0;&#xA0;Which would be an obvious target to try.

**Comment by MasterInQuestion** [comment] 2022-07-18 19:02
No one else could reproduce the issue? @bagder?

**Comment by bagder** [comment] 2022-07-18 21:33
I think you have misunderstood what the feature does. It works as documented and intended.

**Comment by MasterInQuestion** [comment] 2022-07-18 22:35
So you get results consistent with jay?

**Comment by bagder** [comment] 2022-07-19 08:59
I showed you the result of my command line, which shows it connecting to the correct host.

**Comment by MasterInQuestion** [comment] 2022-07-19 21:21
&#xA0;&#xA0;&#xA0;&#xA0;It didn't show the final result. Nor did you answer my further questions.
&#xA0;&#xA0;&#xA0;&#xA0;.
&#xA0;&#xA0;&#xA0;&#xA0;I also get similar display for that portion during testing.
&#xA0;&#xA0;&#xA0;&#xA0;But the eventually returned web page seems to indicate that the connection wasn't made to the correct host.

**Comment by bagder** [comment] 2022-07-19 21:39
It connects to that IP address that it says it connects to.

I do not get a 404 from that command line, probably because the SNI is wrong:
~~~
curl: (35) error:0A000458:SSL routines::tlsv1 unrecognized name

**Comment by MasterInQuestion** [comment] 2022-07-19 21:49
&#xA0;&#xA0;&#xA0;&#xA0;So you have result consistent with jay, seems.

&#xA0;&#xA0;&#xA0;&#xA0;Could someone verify it on the latest Windows build (aforementioned)?
