### ISSUE TITLE
xferinfo function is not called with multi interface on an unresponsive HTTP server

### ISSUE THREAD

**Issue by Deewiant** [curl/curl#7304] opened 2021-06-28 11:32 UTC
### I did this

Using the multi interface on Linux, made an HTTP request to a server that accepts the connection but doesn't respond at all, with `CURLOPT_XFERINFOFUNCTION` set (and of course `CURLOPT_NOPROGRESS` unset).

A test program is attached at the bottom of this report. It should work on at least any Linux system. I tried to make it as "reasonably minimal" as possible: it uses plain `poll` to implement the "backend" for the multi interface, handles errors with `assert`, etc. Build with `-DSERVER` to get the server, or with `-DEASY` to have the client use the easy interface which behaves differently. The server sleeps both before and after `accept`ing the incoming connection.

Logs from an example run:

Server:
```
13:42:12.540610635  waiting 2 seconds before accepting
13:42:14.541136982  accepted connection, waiting 2 seconds or until error...
13:42:16.542256676  exiting
```

Client (with a debug build of libcurl, and using the multi interface):
```
13:42:13.388605414  performing request with curl 7.78.0-DEV
13:42:13.388937856  timeout set to 0
13:42:13.388942594  poll nfds=0 timeout=0
13:42:13.388947463  timer expired
* STATE: INIT => CONNECT handle 0xc53378; line 1780 (connection #-5000)
* Added connection 0. The cache now contains 1 members
* family0 == v4, family1 == v6
*   Trying 127.0.0.1:31230...
* STATE: CONNECT => CONNECTING handle 0xc53378; line 1841 (connection #0)
13:42:13.389066059  xferinfo called
* Connected to 127.0.0.1 (127.0.0.1) port 31230 (#0)
* STATE: CONNECTING => PROTOCONNECT handle 0xc53378; line 1971 (connection #0)
13:42:13.389086408  xferinfo called
* STATE: PROTOCONNECT => DO handle 0xc53378; line 1994 (connection #0)
13:42:13.389095569  xferinfo called
> GET / HTTP/1.1
Host: 127.0.0.1:31230
Accept: */*

* STATE: DO => DID handle 0xc53378; line 2068 (connection #0)
13:42:13.389137982  xferinfo called
* STATE: DID => PERFORMING handle 0xc53378; line 2187 (connection #0)
13:42:13.389147642  xferinfo called
13:42:13.389155186  xferinfo called
13:42:13.389161254  xferinfo called
13:42:13.389168556  want POLLIN for 3
13:42:13.389174419  timeout set to 199
13:42:13.389178687  poll nfds=1 timeout=199
13:42:13.588425093  timer expired
13:42:13.588448279  timeout set to 1
13:42:13.588455140  poll nfds=1 timeout=1
13:42:13.589517426  timer expired
13:42:13.589534952  xferinfo called
13:42:13.589539874  xferinfo called
13:42:13.589545990  poll nfds=1 timeout=-1
* select/poll returned error
* multi_done
13:42:16.542465693  xferinfo called
* The cache now contains 0 members
* Closing connection 0
13:42:16.542512174  want to forget 3
13:42:16.542548121  request done with code 55
```

Note how no timeout is set after the 1-millisecond one expires, so we end up waiting until there's activity on the socket and otherwise hang forever.

### I expected the following

Timeouts to be set in such a way that xferinfo is called at least every second or so, as per the `CURLOPT_XFERINFOFUNCTION` documentation. With the easy interface (compile the test program with `-DEASY`) it behaves as expected.

I also tried to work around the issue by overriding the timeouts provided by libcurl, but it seems that `curl_multi_socket_action` ignores any "unexpected" `CURL_SOCKET_TIMEOUT` calls. I.e. even if the timeout passed to `poll` here is overridden to 100 milliseconds every time, the xferinfo function does not get called.

I've found two better workarounds:

1. Setting the full `CURLOPT_TIMEOUT_MS`, which guarantees an eventual timeout, but of course that overrides any custom logic one may want to have. (`CURLOPT_CONNECTTIMEOUT_MS` doesn't apply here since the connection itself is quick, the server hangs only afterwards.)
2. Combining the overridden timeout with calling `curl_multi_socket_action` with the actual underlying fd instead of `CURL_SOCKET_TIMEOUT`. Here we have to invent the `ev_bitmask` value: We can either pass 0, in which case libcurl will `poll` the socket by itself, see that there's nothing there, and do nothing, or we can pass `CURL_CSELECT_IN | CURL_CSELECT_OUT`, in which case libcurl will try to perform an operation, get `EAGAIN`, and also effectively do nothing. But crucially, the xferinfo function does get called either way, so the only downsides of this are the extra complexity and system call overhead.

### curl/libcurl version

I originally ran into this on 7.66.0. The test program was run mainly against a debug build of currentish master commit ca60a4398fc82e43e3b7caeff811db1ac5370dd0:

```
curl 7.78.0-DEV (Linux) libcurl/7.78.0-DEV OpenSSL/1.1.1f zlib/1.2.11
Release-Date: [unreleased]
Protocols: http https
Features: alt-svc AsynchDNS Debug HSTS HTTPS-proxy IPv6 Largefile libz NTLM SSL TrackMemory UnixSockets
```

### operating system

`Linux pc 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

### Test program

Should compile with any C99 compiler in a POSIX-compliant environment. Define `SERVER` to get the server or `EASY` to get a client that uses the easy interface.

```
#define _POSIX_C_SOURCE 199309L

#include <curl/curl.h>

#include <arpa/inet.h>
#include <assert.h>
#include <errno.h>
#include <poll.h>
#include <stdarg.h>
#include <stdio.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <time.h>
#include <unistd.h>

static void log(const char *fmt, ...) {
  struct timespec t;
  int err = clock_gettime(CLOCK_REALTIME, &t);
  assert(!err);
  char buf[sizeof "HH:MM:SS"];
  strftime(buf, sizeof buf, "%T", localtime(&t.tv_sec));
  fprintf(stderr, "%s.%09d  ", buf, (int)t.tv_nsec);
  va_list ap;
  va_start(ap, fmt);
  vfprintf(stderr, fmt, ap);
  va_end(ap);
  fputc('\n', stderr);
}

#ifdef SERVER

int main(void) {
  int sock = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
  assert(sock >= 0);
  struct sockaddr_in addr = {
    .sin_family = AF_INET,
    .sin_port = ntohs(31230),
    .sin_addr = {.s_addr = ntohl(0x7f000001)},
  };
  int err = bind(sock, (struct sockaddr *)&addr, sizeof addr);
  assert(!err);
  err = listen(sock, 1);
  assert(!err);
  log("waiting 2 seconds before accepting");
  sleep(2);
  int fd = accept(sock, NULL, NULL);
  assert(fd >= 0);
  log("accepted connection, waiting 2 seconds or until error...");
  struct pollfd pfd = {.fd = fd, .events = POLLERR};
  poll(&pfd, 1, 2000);
  log("exiting");
}

#else

static int xferinfo(void *u, curl_off_t dt, curl_off_t dn, curl_off_t ut,
                    curl_off_t un) {
  (void)u; (void)dt; (void)dn; (void)ut; (void)un;
  log("xferinfo called");
  return 0;
}

#define MAX_FDS 10

struct multi_polls {
  struct pollfd fds[MAX_FDS];
  nfds_t nfds;
  int timeout_ms;
  int timer_active;
};

static int multi_socket(CURL *easy, curl_socket_t s, int what, void *userp,
                        void *socketp) {
  (void)easy; (void)socketp;

  struct multi_polls *m = userp;

  nfds_t i = 0;
  for (; i < MAX_FDS; i++) {
    if (s == m->fds[i].fd) {
      break;
    }
  }

  short events;
  switch (what) {
  case CURL_POLL_IN:
    log("want POLLIN for %d", s);
    events = POLLIN;
    break;
  case CURL_POLL_OUT:
    log("want POLLOUT for %d", s);
    events = POLLOUT;
    break;
  case CURL_POLL_INOUT:
    log("want POLLIN | POLLOUT for %d", s);
    events = POLLIN | POLLOUT;
    break;

  case CURL_POLL_REMOVE: {
    log("want to forget %d", s);
    assert(i < MAX_FDS);
    close(m->fds[i].fd);
    --m->nfds;
    memmove(&m->fds[i], &m->fds[i + 1], (m->nfds - i) * sizeof *m->fds);
    return 0;
  }

  default:
    assert(0);
  }

  if (i == MAX_FDS) {
    assert(m->nfds < MAX_FDS);
    i = m->nfds++;
  }

  m->fds[i] = (struct pollfd){.fd = s, .events = events};
  return 0;
}

static int multi_timer(CURLM *multi, long timeout_ms, void *userp) {
  (void)multi;
  struct multi_polls *m = userp;
  if (timeout_ms < 0) {
    assert(timeout_ms == -1);
    m->timer_active = 0;
    log("timer stopped");
  } else {
    m->timeout_ms = timeout_ms > INT_MAX ? INT_MAX : (int)timeout_ms;
    m->timer_active = 1;
    log("timeout set to %d", timeout_ms);
  }
  return 0;
}

static void multi_action(CURLM *multi, curl_socket_t sock, int events) {
  int n = 0;
  CURLMcode mcode = curl_multi_socket_action(multi, sock, events, &n);
  assert(mcode == CURLM_OK);

  CURLMsg *msg = NULL;
  while ((msg = curl_multi_info_read(multi, &n)) != NULL) {
    assert(msg->msg == CURLMSG_DONE);

    log("request done with code %d", msg->data.result);
    curl_multi_remove_handle(multi, msg->easy_handle);
    curl_easy_cleanup(msg->easy_handle);
  }
}

int main(void) {
  CURLcode code = CURLE_OK;

  code = curl_global_init(CURL_GLOBAL_DEFAULT);
  assert(code == CURLE_OK);

  CURLM *multi = curl_multi_init();
  assert(multi);

  struct multi_polls m = {.nfds = 0, .timeout_ms = 0, .timer_active = 0};

  CURLMcode mcode = CURLM_OK;

  mcode = curl_multi_setopt(multi, CURLMOPT_SOCKETFUNCTION, multi_socket);
  assert(mcode == CURLM_OK);
  mcode = curl_multi_setopt(multi, CURLMOPT_TIMERFUNCTION, multi_timer);
  assert(mcode == CURLM_OK);
  mcode = curl_multi_setopt(multi, CURLMOPT_SOCKETDATA, &m);
  assert(mcode == CURLM_OK);
  mcode = curl_multi_setopt(multi, CURLMOPT_TIMERDATA, &m);
  assert(mcode == CURLM_OK);

  CURL *easy = curl_easy_init();
  assert(easy);

  code = curl_easy_setopt(easy, CURLOPT_URL, "http://127.0.0.1:31230");
  assert(code == CURLE_OK);
  code = curl_easy_setopt(easy, CURLOPT_XFERINFOFUNCTION, xferinfo);
  assert(code == CURLE_OK);
  code = curl_easy_setopt(easy, CURLOPT_NOPROGRESS, 0L);
  assert(code == CURLE_OK);

  code = curl_easy_setopt(easy, CURLOPT_VERBOSE, 1L);
  assert(code == CURLE_OK);

  const curl_version_info_data *curl_info = curl_version_info(CURLVERSION_NOW);
  log("performing request with curl %s", curl_info->version);

#ifdef EASY
  code = curl_easy_perform(easy);
  log("request done with code %d", code);
#else
  mcode = curl_multi_add_handle(multi, easy);
  assert(mcode == CURLM_OK);
  while (m.timer_active || m.nfds > 0) {
    int timeout_ms = m.timer_active ? m.timeout_ms : -1;
    log("poll nfds=%d timeout=%d", m.nfds, timeout_ms);
    int polled = poll(m.fds, m.nfds, timeout_ms);
    if (polled == -1 && errno == EINTR)
      continue;
    assert(polled != -1);

    if (polled == 0) {
      m.timer_active = 0;
      log("timer expired");
      multi_action(multi, CURL_SOCKET_TIMEOUT, 0);
    } else {
      for (nfds_t i = 0; i < m.nfds; i++) {
        short events = m.fds[i].revents;
        if (!events)
          continue;
        multi_action(multi, m.fds[i].fd,
                     events & POLLERR
                         ? CURL_CSELECT_ERR
                         : (events & POLLIN ? CURL_CSELECT_IN : 0) |
                           (events & POLLOUT ? CURL_CSELECT_OUT : 0));
        if (!--polled)
          break;
      }
    }
  }
#endif
}
#endif
```

**Comment by bagder** [comment] 2021-06-28 11:56
This is not a bug. This can however most probably be better clarified in the documentation.

libcurl will not setup a timer to get called just in order to call the progress callback. This means that if nothing happens on the socket, the control is in your application. You *can* call libcurl and indicate timeout, and then the callback will be called every once in a while, but that's a decision for you to make and libcurl will not insist on it.

**Comment by Deewiant** [comment] 2021-06-28 12:07
> libcurl will not setup a timer to get called just in order to call the progress callback. This means that if nothing happens on the socket, the control is in your application.

Fair enough. The documentation could indeed be clearer on this point.

> You can call libcurl and indicate timeout, and then the callback will be called every once in a while

This is the first workaround I mentioned I tried, but it doesn't seem to be working. If I take the test program and change line 198 from:

```c
int timeout_ms = m.timer_active ? m.timeout_ms : -1;
```

To:

```c
int timeout_ms = m.timer_active ? m.timeout_ms : 100;
```

I.e. causing `CURL_SOCKET_TIMEOUT` to get passed at least every 100ms even in the absence of a libcurl-provided timeout, I get a loop of this:

```
15:04:40.965584728  xferinfo called
15:04:40.965603233  xferinfo called
15:04:40.965630951  poll nfds=1 timeout=100
15:04:41.065856506  timer expired
15:04:41.065915607  poll nfds=1 timeout=100
15:04:41.166098762  timer expired
15:04:41.166142128  poll nfds=1 timeout=100
15:04:41.266324424  timer expired
15:04:41.266373001  poll nfds=1 timeout=100
15:04:41.366532871  timer expired
15:04:41.366556411  poll nfds=1 timeout=100
15:04:41.466632940  timer expired
15:04:41.466670675  poll nfds=1 timeout=100
15:04:41.566877325  timer expired
```

Note the absence of `xferinfo called`.

**Comment by bagder** [comment] 2021-06-28 18:10
Ah right, with the multi_socket API libcurl won't do anything on the transfer unless its timeout has fired - when you say timeout...  Because there could be thousands of handles in there and it wouldn't know for which you think it should run the progress callback for. You really can't trigger the callback manually when nothing has happened on the transfer using this API.

**Comment by Deewiant** [comment] 2021-06-28 21:05
Arguably it should run the callback for all of them, though I can see how that can get problematic with thousands of handles. But isn't that what happens on `CURL_SOCKET_TIMEOUT` anyway?

Ideally it would run the callback for all of them that both have a progress function and haven't had progress in the last second. Currently my workaround is to do essentially that in the application: Capping the timeouts provided to `CURLMOPT_TIMERFUNCTION` if any handle in the multi handle has opted in to this behaviour, and calling `curl_multi_socket_action(multi, sock, 0, &n)` for all such handles. libcurl then polls the handle, determines there's nothing to do, but at least calls the progress function. This does feel a bit like relying on implementation quirks rather than intended behaviour, though.

It feels to me like there's _something_ that could be done in the API to improve this case, but I'm not sure what that would be. One small option would be to add something like `CURL_CSELECT_PROGRESSONLY` to short-cut some of the internal processing that the `0` triggers (i.e. avoiding the `poll`), but it doesn't seem to really fit very well. A dedicated function for that (i.e. to replace the `curl_multi_socket_action` call) would be cleaner but I'm not sure the added API surface is really justified for such a specific thing.

Having peeked a bit at the internals, the most powerful option would appear to be a wrapper of some sort around `Curl_expire`. It looks to me like it provides the "add a timeout for an easy handle within a multi handle" operation that I'm missing and thus the use case would be served by calling it with 1000 essentially unconditionally. But I understand that libcurl's API is intentionally fairly lean and this kind of thing might be too powerful. (Allowing myself to get carried away a bit, I can imagine building out a family of APIs from this around `multi->timetree`: being able to introspect it in the application seems quite useful, and having access to fancier operations like "add a timeout for this socket in 1000 ms unless there's already one within 1250 ms" or something would be great.)

**Comment by bagder** [comment] 2021-06-28 21:50
> But isn't that what happens on CURL_SOCKET_TIMEOUT anyway?

No. Then it just iterates over the subset of transfers that currently have expired timers. The timers are in a sorted tree so it won't iterate over handles superfluously.

> my workaround is to do essentially that in the application

I will go a step further and say that it is the way to do it.

> It looks to me like it provides the "add a timeout for an easy handle within a multi handle" operation that I'm missing and thus the use case would be served by calling it with 1000 essentially unconditionally

Yes, in theory there could be a new `CURLMOPT_MULTI_PROGRESSFUNCTION_INTERVAL` option created that would make such a timeout for each handle added to a multi handle, which then could "force" the progress callback to trigger for idle transfers. I'm not convinced that's necessary since you can work around this in the application.

**Comment by Deewiant** [comment] 2021-06-29 07:10
> I'm not convinced that's necessary since you can work around this in the application.

I guess it's not necessary, but of course it has benefits in efficiency and overall simplicity. curl already has a sorted tree of timers, which is basically the ideal structure for this use case. Currently the application has to either duplicate something similar on its end, or not keep track of per-handle timers and resign itself to triggering extra `poll` and progress function calls far more often than necessary (every time the global timer triggers).

**Comment by bagder** [comment] 2021-06-29 14:06
I noticed that the current behavior is documented in the `CURLOPT_XFERINFOFUNCTION` man page:

> If you transfer data with the multi interface, this function will not be
> called during periods of idleness unless you call the appropriate libcurl
> function that performs transfers.

I could probably be talked into agreeing that your proposed enhanced functionality could be a boost to those that truly want the progress callback when using the multi_socket API.

**Comment by Deewiant** [comment] 2021-06-29 18:21
I remember seeing that sentence, and got the same understanding from it that lead to filing this issue in the first place: I figured that as long as I use the multi interface in a "normal" way, triggering `curl_multi_socket_action` on I/O readiness or `CURL_SOCKET_TIMEOUT`, the progress function would get called. I think it should be clarified to say that additional operations on top of that, i.e. calls that look like `curl_multi_socket_action(multi, sock, 0, &n)`, are necessary.

> I could probably be talked into agreeing that your proposed enhanced functionality could be a boost to those that truly want the progress callback when using the multi_socket API.

I'm glad to hear it. So you would suggest having it as a multi option, `CURLMOPT_MULTI_PROGRESSFUNCTION_INTERVAL`? Having already poked around a bit near `Curl_expire` and the overall multi functionality, if you give me some pointers I could take a stab at implementing it.

And just in case we're not dealing with an XY problem: The main reason I'm using the progress callback is to implement timeout logic that doesn't exactly match any of the "baked-in" possibilities with the various `CURLOPT_*`. Should I be doing something else instead?

**Comment by bagder** [comment] 2021-07-01 15:07
> So you would suggest having it as a multi option, CURLMOPT_MULTI_PROGRESSFUNCTION_INTERVAL?

Doesn't something like that seem reasonable? (The exact name can always be debated)

> The main reason I'm using the progress callback is to implement timeout logic that doesn't exactly match any of the "baked-in" possibilities with the various CURLOPT_*. Should I be doing something else instead?

That's hard for me to tell. Your argument that libcurl already has the sorted tree to know for which specific transfers to call is convincing as the application otherwise needs to duplicate that kind of logic in order to know which particular transfers that should be considered.

**Comment by Deewiant** [comment] 2021-07-01 15:20
> > So you would suggest having it as a multi option, CURLMOPT_MULTI_PROGRESSFUNCTION_INTERVAL?
> 
> Doesn't something like that seem reasonable? (The exact name can always be debated)

Sure, it should cover all cases.

But as I mentioned before, ideally there'd be something more dynamic. There's a range of choices here, at least: multi option, easy option, functionality to set it dynamically per-easy. For instance in my case of dealing with timeouts, I don't care about calls to the progress function until the next timeout is due to occur (or the request state changes, but that's I/O and already works fine), which varies by request and request state.

> > The main reason I'm using the progress callback is to implement timeout logic that doesn't exactly match any of the "baked-in" possibilities with the various CURLOPT_*. Should I be doing something else instead?
> 
> That's hard for me to tell.

I meant in a more general sense: Is there another way, with libcurl, to implement timeout logic than by using the existing easy options or a progress callback?

**Comment by bagder** [comment] 2021-07-02 09:18
> in my case of dealing with timeouts, I don't care about calls to the progress function until the next timeout is due to occur

Isn't this statement contradicting this very issue? If the server is unresponsive, there might not be any next timeout at all. Or if you have `CURLOPT_TIMEOUT` set to a worst case, that timeout could be minutes or hours away. I thought that was pretty much the reason for this issue.

> Is there another way, with libcurl, to implement timeout logic than by using the existing easy options or a progress callback?

libcurl doesn't really expose or offer the timeout logic in external APIs so I don't think so.

But you're certainly right that there's a plethora of options available to provide this feature. We just need to decide what provides a suitable balance of easy of use and functionality.

**Comment by Deewiant** [comment] 2021-07-02 10:04
> > in my case of dealing with timeouts, I don't care about calls to the progress function until the next timeout is due to occur
> If the server is unresponsive, there might not be any next timeout at all.

I meant "next timeout" here in terms of the high-level logic, not the timers in the implementation (in libcurl or otherwise). In other words, the timestamp after which my progress callback would return nonzero to abort the transfer.

**Comment by bagder** [comment] 2021-07-30 14:20
Since this is not a bug, I'm closing this issue. The enhancement that's been discussed in here can of course still be pursued and made into a puill-request to help mitigate this shortcoming.

**Closed by bagder** 2021-07-30 14:20 UTC
Labels: documentation, libcurl API
