### ISSUE TITLE
ci.appveyor fail results

### ISSUE THREAD

**Issue by chaos-ui** [curl/curl#7127] opened 2021-05-25 13:33 UTC
### curl/libcurl version

[curl -V output]

**Comment by bagder** [comment] 2021-05-25 14:29
Duplicate of #6972 

This is a known problem, but without a solution...

**Closed by bagder** 2021-05-25 14:29 UTC
Labels: CI

**Comment by chaos-ui** [comment] 2021-05-25 14:42
Okay, I shall try to find the solution, thankyou will close as draft
