### ISSUE TITLE
Weird verbose output with patched OpenSSL build

### ISSUE THREAD

**Issue by D4v1dH03** [curl/curl#7843] opened 2021-10-12 02:36 UTC
### I did this
Build curl with patched OpenSSL from quictls (`0ce9b02`), nghttp2 (`fa7a916`), ngtcp2 (`86f005b`) as well as (`d741fb9`) and try to curl youtube.com with option `--tlsv1.3` as a test
### I expected the following
Handshake output are consistent TLSv1.3, (OUT)/ (IN) ......

However I see this:
```
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
```
### curl/libcurl version
`master` branch at commit `e38d2e5`
[curl -V output]
```
curl 7.80.0-DEV (aarch64-apple-darwin21.1.0) libcurl/7.80.0-DEV OpenSSL/3.0.0 zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 nghttp2/1.46.0-DEV ngtcp2/0.1.0-DEV nghttp3/0.1.0-DEV
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets zstd
```
### operating system
`Darwin [redacted] 21.1.0 Darwin Kernel Version 21.1.0: Thu Sep 30 06:42:03 PDT 2021; root:xnu-8019.40.96.0.2~12/RELEASE_ARM64_T8101 arm64`

**Comment by jay** [comment] 2021-10-12 05:40
Ref: https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_msg_callback.html
Ref: https://github.com/curl/curl/blob/curl-7_79_0/lib/vtls/openssl.c#L2109

Our code for that is straightforward. Possibly this is a bug in OpenSSL or quic handling. I can't reproduce with curl master and OpenSSL/1.1.1j. I suggest try building from openssl-3.0.0 and/or openssl-3.0 (which is the dev branch for 3.0 it seems).

~~~
curl 7.80.0-DEV (i386-pc-win32) libcurl/7.80.0-DEV OpenSSL/1.1.1j nghttp2/1.43.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Debug HSTS HTTP2 HTTPS-proxy IPv6 Largefile NTLM SSL Unicode UnixSockets alt-svc
~~~

**Comment by bagder** [comment] 2021-10-12 06:26
Yes, the original upstream OpenSSL 3.0.0 has no QUIC support.

**Comment by bagder** [comment] 2021-10-14 09:27
I believe curl shows the information as provided. I don't think curl can (should) behave differently. I believe this is not a curl bug.

**Comment by bagder** [comment] 2021-10-16 15:02
I'm going to close this issue as works as intended. curl only shows what OpenSSL tells it.

**Closed by bagder** 2021-10-16 15:02 UTC
Labels: SSL/TLS
