### ISSUE TITLE
Crash due to readrewind fseek'in a FILE* of null pointer in 8.4.0

### ISSUE THREAD

**Issue by zhihaoy** [curl/curl#13181] opened 2024-03-25 05:38 UTC
### I did this

We collected a crash in a system. The usage pattern can summerized as: put a `CURL` easy handle in a multi handle, run `curl_multi_perform` periodically in a thread. The easy handle has customized write function and data and no other customized callbacks. During the crash, the program is POSTing to a url via HTTPS.

The symptom is that, the code runs into the a snippet that is deleted in 14bcea074a78227248b00bb6fb22462e0c1b65aa

![p1](https://github.com/curl/curl/assets/43971430/cfccc2ab-f0dd-4b38-9544-4c38266e785a)

and then, because this easy handle does not have a customized read function, the code attemps to rewind its "input file" with `fseek`, but the `state.in` is `NULL`, which leads to a crash in CRT.

![p2](https://github.com/curl/curl/assets/43971430/dfdfb0ce-8a42-4637-9484-8d2cc262c9a9)

We don't have a minimal reproduce at the moment, but hope to get some insights about this issue.

The code snippet in question was introduced in 1b3973180b6b7f1023240a67d3acdb11b534bf03. Is it likely to be the cause of the issue? *If so*, since the code is removed recently by 14bcea074a78227248b00bb6fb22462e0c1b65aa (which looks like a refactoring), is there a behavior change asssociated with it and can fix the issue?

### curl/libcurl version

curl 8.4.0

### operating system

Windows 10 Version 22000 MP (4 procs) Free x64

**Comment by bagder** [comment] 2024-03-25 08:30
> the program is POSTing to a url via HTTPS

How is it POSTing? Using which easy options?

**Comment by zhihaoy** [comment] 2024-03-25 22:08
The handle's `state.httpreq` is set to 1, i.e., `HTTPREQ_POST`. What we did in the code is the following: set `CURLOPT_WRITEDATA`, `CURLOPT_WRITEFUNCTION`, `CURLOPT_WRITEHEADER`. We set `CURLOPT_POST` to `CURL_FALSE`, `CURLOPT_READFUNCTION` to `nullptr`, and `CURLOPT_READDATA` to `nullptr` just in case some prior code paths did something to this handle. Then the code sets `CURLOPT_POSTFIELDSIZE_LARGE` and `CURLOPT_POSTFIELDS`.

**Comment by bagder** [comment] 2024-03-25 23:37
Ok, that sounds odd since with POSTFIELDS set it should never rewind.

The entire rewindbeforesend send logic has now been refactored (in 14bcea074a78227248b00bb6fb22462e0c1b). It would be helpful if you retested with current git/a daily snapshot or perhaps with 8.7.0 which is going to be released on March 27.

**Comment by bagder** [comment] 2024-04-08 14:54
Please?

And if it still fails, please provide us with a full example that reproduces the problem to help us debug this!

**Comment by zhihaoy** [comment] 2024-04-08 21:33
We are not seeing a second crash coming out of the stress test, so we don't think it's that easy to create a minimal reproduce. We'll upgrade to curl 8.7.0 at some point.

**Comment by bagder** [comment] 2024-04-22 20:46
Nothing for us to act on, closing.

**Closed by bagder** 2024-04-22 20:46 UTC
Labels: crash, HTTP, needs-info
