### ISSUE TITLE
cURL 7.77.0 can crash(Segfault @Curl_ssl_getsessionid) then closing SSL connection at least on HTTP2/Push.

### ISSUE THREAD

**Issue by vityank** [curl/curl#7223] opened 2021-06-09 15:26 UTC
cURL 7.77.0 can crash(Segfault @Curl_ssl_getsessionid) then closing SSL connection.
Reproduced by PHP's curl H2 tests(Uses HTTP2 Push with multi interface and pipelining/multiplexing) on url https://http2.golang.org/serverpush. 
PHP Test: ext/curl/tests/bug77535.phpt
Version 7.75.0 works fine.

### I expected the following

cURL 7.77.0

[curl -V output]
curl 7.77.0 (x86_64-pc-linux-gnu) libcurl/7.77.0 OpenSSL/1.1.1k zlib/1.2.11 zstd/1.5.0 libidn2/2.3.1 libssh2/1.9.0 nghttp2/1.43.0 OpenLDAP/2.4.58
Release-Date: 2021-05-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS Debug GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP TrackMemory UnixSockets zstd
### operating system
CentOS 7.7
3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Backtrace:

#0  0x00007fffe7c4527e in Curl_ssl_getsessionid (data=0x1351558, conn=0x12701c8, isProxy=false,
    ssl_sessionid=0x7fffffff9db0, idsize=0x0, sockindex=0) at vtls/vtls.c:422
#1  0x00007fffe7c43db1 in ossl_disassociate_connection (data=0x1351558, sockindex=0)
    at vtls/openssl.c:4559
#2  0x00007fffe7c45aa5 in Curl_ssl_detach_conn (data=0x1351558, conn=0x12701c8) at vtls/vtls.c:603
#3  0x00007fffe7bf8467 in Curl_detach_connnection (data=0x1351558) at multi.c:883
#4  0x00007fffe7bf7b1c in multi_done (data=0x1351558, status=CURLE_OK, premature=false) at multi.c:608
#5  0x00007fffe7bfb30c in multi_runsingle (multi=0x11241c8, nowp=0x7fffffffa150, data=0x1351558)
    at multi.c:2389
#6  0x00007fffe7bfb6d7 in curl_multi_perform (multi=0x11241c8, running_handles=0x7fffffffa198)
    at multi.c:2520
#7  0x00007fffe7eb468e in zif_curl_multi_exec (execute_data=<optimized out>, return_value=0x7ffff2c1e370)
    at php-7.3.28/ext/curl/multi.c:294
#8  0x00000000006ab193 in ZEND_DO_ICALL_SPEC_RETVAL_USED_HANDLER ()
    at php-7.3.28/Zend/zend_vm_execute.h:694
#9  execute_ex (ex=0x1351558) at php-7.3.28/Zend/zend_vm_execute.h:55503
#10 0x00000000006b4658 in zend_execute (op_array=op_array@entry=0x7ffff2c94a80,
    return_value=return_value@entry=0x7ffff2c1e0e0)
    at php-7.3.28/Zend/zend_vm_execute.h:60935

Program received signal SIGSEGV, Segmentation fault.0x00007fffe7c4527e in Curl_ssl_getsessionid (data=0x1351648, conn=0x1270258, isProxy=false,ssl_sessionid=0x7fffffff9d70, idsize=0x0,sockindex=0) 
at vtls/vtls.c:422
422        
 if(!check->sessionid)

(gdb) print check
$1 = (struct Curl_ssl_session *) 0x0

**Comment by bagder** [comment] 2021-06-09 21:08
Duplicate of #7148, already fixed in master

**Closed** 2021-06-10 06:11 UTC
Labels: HTTP/2, crash
