### ISSUE TITLE
curl_mime_data() ony uses 0xff bytes and then repeats them

### ISSUE THREAD

**Issue by vigilanz** [curl/curl#1996] opened 2017-10-19 11:38 UTC
### I did this
Trying to send an SMTP email with MIME (normal part, HTML part and two attachments).

### I expected the following
I initially added attachment data using curl_mime_data() and then called curl_mime_encode(part, "base64").

Now the problem is that ... the data repeats after 0xFF bytes. So when opening the sent mail in Alpine and saving the attachment (it was a 50KB image in that case), you see a JPEG header repeating. It has nothing to do with the encoder, the problem persists if I do the base64-encoding myself and just set the header.

Solution is to upload attachment data via curl_mime_data_cb(). Documentation points out that curl_mime_data() might be memory inefficient ... well ... in fact, it is not as it always uses 256 bytes only, but user would expect it different, so maybe just fix docs telling that 256 bytes is max.

To reproduce:
Compose a MIME mail and attach a JPEG with this setup:
        part = curl_mime_addpart(mime);
        curl_mime_type(part, "image/jpeg");
        curl_mime_filename(part, "myfile.jpg");
        curl_mime_data(part, img_buffer, img_size);
        curl_mime_encoder(part, "base64");

### curl/libcurl version
curl 7.56.0 (x86_64-pc-linux-gnu) libcurl/7.56.0 OpenSSL/1.0.1t zlib/1.2.8
Release-Date: 2017-10-04
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy 

### operating system
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.8 (jessie)
Release:        8.8
Codename:       jessie

**Comment by bagder** [comment] 2017-10-19 12:17
can you give this a look @monnerat ?

**Comment by monnerat** [comment] 2017-10-19 15:06
I suspect this should be fixed by https://github.com/curl/curl/commit/5f9e2ca09b57d82baf239039835b3b06dc41bbc5

The encoding input buffer is 256-byte long (used in part read call) and 255 is the greater multiple of 3 (a base64 binary group) that fits in it.

I write a test for it... hang on.

**Comment by monnerat** [comment] 2017-10-19 19:28
I confirm the cause is the same as for https://github.com/curl/curl/pull/1988 and is thus already fixed by https://github.com/curl/curl/commit/5f9e2ca09b57d82baf239039835b3b06dc41bbc5

There is now a new test (652) for this case: https://github.com/curl/curl/commit/34def509eff19ae2b1d91f390b22f1b450f8f4dd

**Comment by bagder** [comment] 2017-10-19 23:02
lovely, nice work @monnerat !

**Comment by bagder** [comment] 2017-10-23 06:51
Presumed to be fixed!

**Closed by bagder** 2017-10-23 06:51 UTC
Labels: SMTP
