### ISSUE TITLE
Download statistics on curl command line are wrong

### ISSUE THREAD

**Issue by Bylon2** [curl/curl#5079] opened 2020-03-11 15:37 UTC
### I did this

Use curl command line simply:

```
Download starts at: 09:51:50 CET, link: https://undisclosed_url

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4970M  100 4970M    0     0  2369k      0  0:35:47  0:35:47 --:--:-- 1588k

Download ended at: 10:48:39 CET with 0, header:HTTP/1.1 200 OK

```

### I expected the following

I expected that the "average download" and "time spent" would be correct!

It took 56 minutes and 49 seconds to complete the download, and the average speed was like the last recorded speed: around 1500k.

Instead curl (command line) says it took 35 minutes 47 seconds and subsequently computes a much higher average download.

(I added timings on my script so that the real time spent is visible)

This is on Raspeberry Pi 4 with the standard Raspbian curl that is in the repositories.
Versions: see below.

### curl/libcurl version

```
$ curl -V
curl 7.64.0 (arm-unknown-linux-gnueabihf) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

### operating system
```
$ uname -a; lsb_release -a
Linux raspberrypi 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

```

### [Edit] Severity (my estimate)

**Minor** to Medium.
The downloaded file is correct, but the display is mostly irrelevant and does not help for estimated or even elapsed times/speeds.

It could be "Medium" if the bug is around how times are computed on ARM and thas has effect on other parameters : "timeouts" and the like.

**Comment by jay** [comment] 2020-03-11 18:26
Is there something else in your shell script that is taking the extra time? What happens if you add `--write-out "Time total: %{time_total}"` ([total transfer time in seconds](https://curl.haxx.se/docs/manpage.html#-w)). Also please try [the latest curl](https://curl.haxx.se/download.html) and see if you can reproduce.

**Comment by Bylon2** [comment] 2020-03-11 18:54
Will do!

The line of script is just doing that:

`curl -D "${TMPFILE}" "${link}" -o "${OUTPUTDIR}${file_name}"`

Which triggers the display you see.

In fact it is steadily downloading around 1500k (give of take a few k), and if you look at the "average download" it is gradually going up to the point where it displays 2369k at the end, although at no time there is ever any 'spike' faster than 1600k.

Definitely something wrong with time management on that machine!

**Comment by bagder** [comment] 2020-03-11 22:37
I suspect this could be be the problem (related to 32 bit time_t) we fixed in b1616dad8f088, released in 7.66.0.

**Comment by Bylon2** [comment] 2020-03-12 06:28
Indeed, looks like a good candidate!

So I have 2 tests to run:
- Same thing I did + writeout
- Compile the later version + test

**Comment by Bylon2** [comment] 2020-03-15 10:50
Test 1 is done (with current curl version prior to the change).

Indeed **"Time spent" is blocked at 35:47** which is the maximum number of milliseconds that can be expressed in a 32bits signed counter, because 35:48 would be 2.148.000.000 which overflows the sign.

That means any download which duration is above that figure will display the statistics bug.

**Comment by bagder** [comment] 2020-03-15 10:53
Ack, because the code will then cap the time at that maximum amount so it'll then start counting the transfer speed as higher than it actually was as the data amount continues to increase while the time is fixed at 35m47s.

**Comment by bagder** [comment] 2020-03-15 10:54
This is a duplicate of #4165

**Comment by Bylon2** [comment] 2020-03-15 10:56
Do you think there is any change the single patch you point will fix curl 7.64?

I'm asking that related to release management at Debian (no version change of software in the repo with few exceptions)

**Comment by bagder** [comment] 2020-03-15 12:59
I think so, but iirc we also did some minor follow-up commits after that one.

**Comment by Bylon2** [comment] 2020-03-15 21:20
I could apply the 7.66 patch on 7.64 and will shortly test it on my machine.

The only thing that does not apply (strangely) is
```
int Curl_resolver_getsock(struct connectdata *conn,
                          curl_socket_t *socks,
                          int numsocks)
{
  time_t milli;
  timediff_t ms;
  struct Curl_easy *data = conn->data;
  struct resdata *reslv = (struct resdata *)data->state.resolver;
  (void)socks;
  (void)numsocks;
  ms = Curl_timediff(Curl_now(), reslv->start);
  if(ms < 3)
    milli = 0;
  else if(ms <= 50)
    milli = ms/3;
  else if(ms <= 250)
    milli = 50;
  else
    milli = 200;
  Curl_expire(data, milli, EXPIRE_ASYNC_NAME);
  return 0;
}
```

In this function, the change was
```
  else if(ms <= 50)
    milli = (time_t)ms/3;
  else if(ms <= 250)
```

It is probably clean to have applied the change same as other places, but this change seem non-important for correctness.

Indeed, at this place we know ms is a positive integer between 4 and 50, hence it could stay a timediff_t, that does not make any difference at all on the result.

So I simply removed this (curiously) failing snippet in the 'patch'. I said 'curiously' because the patch should apply since the function didn't seem to change apart from that, and has just changed line which normally `patch` knows how to handle!

**Comment by jay** [comment] 2020-03-15 21:44
The function was modified in later versions, patch won't find all the common lines in 7.64.0. The cast looks like it was just to silence a compiler warning because it may be converting a 64-bit timediff_t to a 32-bit time_t. In that particular case measuring resolve time it's fine either way, the cast just silences the warning.

**Comment by bagder** [comment] 2020-03-15 22:50
Since this is a known bug already fixed, it is time to close this!

**Closed by bagder** 2020-03-15 22:50 UTC
Labels: cmdline tool

**Comment by Bylon2** [comment] 2020-03-16 07:43
@Badger don't worry I was intending to close it myself, but I was just waiting the result of a positive test.

So here it is with the Raspbian Buster 32bits 7.64 curl patched with the commit mentioned above (minus snippet 2 -see above too)

```
$ curl -D /tmp/tmp.smKSVApTsVu2b.txt https://example.com/undisclosed_url -o /path/dest_file --write-out "Time total: %{time_total}\n"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4970M  100 4970M    0     0  1496k      0  0:56:40  0:56:40 --:--:-- 1660k
Time total: 3400,892467
        Command being timed: "curl -D /tmp/tmp.smKSVApTsVu2b.txt https://example.com/undisclosed_url -o /path/dest_file --write-out Time total: %{time_total}\n"
        User time (seconds): 161.04
        System time (seconds): 69.52
        Percent of CPU this job got: 6%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 56:40.92
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 9096
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 2
        Minor (reclaiming a frame) page faults: 526
        Voluntary context switches: 1851357
        Involuntary context switches: 218890
        Swaps: 0
        File system inputs: 176
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

So yes, the counter is now correct: both the "Time spent" and the total time with write-out, even when the download takes more than 35 min and 47 sec.


Then for Raspbian Buster 32 bits we have 2 solutions:
- Patch the existing 7.64
- Use the "unstable" repository to install 7.68

**Conclusion:** closing  is confirmed!

**Comment by bagder** [comment] 2020-03-16 07:49
Thank you @Bylon2!
