### ISSUE TITLE
solve the problem about using of uninitialized value

### ISSUE THREAD

**Issue by huzunhao** [curl/curl#4978] opened 2020-02-25 03:08 UTC
### I did this
I did fuzz testing and found the following uninitialized variable problem.

Uninitialized value was created by an allocation of 'ssrem' in the stack frame of function 'Curl_updateconninfo'
    #0 0x53a8a0 in Curl_updateconninfo /src/curl/lib/connect.c:675

SUMMARY: MemorySanitizer: use-of-uninitialized-value /src/curl/lib/mprintf.c:827:17 in dprintf_formatf

### I expected the following
initialize the ssrem variable
### curl/libcurl version
7.66.0
[curl -V output]
[MemorySanitizer:https://github.com/curl/curl/pull/4977](https://github.com/curl/curl/pull/4977)
### operating system
aarch64

Linux localhost.localdomain 4.19.36-vhulk1906.1.0.h288.eulerosv2r8.aarch64 #1 SMP Mon Apr 1 00:00:00 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

**Comment by jay** [comment] 2020-02-25 03:48
> Uninitialized value was created by an allocation of 'ssrem' in the stack frame of function 'Curl_updateconninfo'
> #0 0x53a8a0 in Curl_updateconninfo /src/curl/lib/connect.c:675
> 
> SUMMARY: MemorySanitizer: use-of-uninitialized-value /src/curl/lib/mprintf.c:827:17 in dprintf_formatf

Can you try it with 7.68? That error doesn't make any sense to me. What does ssrem have to do with dprintf? It is never passed to a printf function. Let's take a look in 7.68:

https://github.com/curl/curl/blob/2cfac302fbeec68f1727cba3d1705e16f02220ad/lib/connect.c#L703-L711

and

https://github.com/curl/curl/blob/2cfac302fbeec68f1727cba3d1705e16f02220ad/lib/mprintf.c#L827

which should not be a problem because Curl_strerror always sets the buffer to 0 before attempting to find an error message so we don't need to check its return:

https://github.com/curl/curl/blob/2cfac302fbeec68f1727cba3d1705e16f02220ad/lib/strerror.c#L725

**Comment by bagder** [comment] 2020-03-05 11:53
No feedback, not a reproduced problem, closing.

**Closed by bagder** 2020-03-05 11:53 UTC
Labels: crash, needs-info-or-update
