### ISSUE TITLE
No windows visual studio build on the download page

### ISSUE THREAD

**Issue by bnolan** [curl/curl#1437] opened 2017-04-21 07:27 UTC
### I did this

I tried to download a build of libcurl to use in visual studio.

### I expected the following

I could download one, but one doesn't exist. Is this some kind of anti-windows crusade or did I do something wrong?

### curl/libcurl version

Any

### operating system

Windows

**Comment by Lukasa** [comment] 2017-04-21 07:32
Given that all of the Windows builds appear to be volunteer-provided, I suspect this is less an "anti-windows crusade" and more a "no-one has volunteered to build libcurl for Visual Studio". Would you like to volunteer?

**Comment by bagder** [comment] 2017-04-21 08:59
The curl project itself provides *no* binaries or otherwise packaged versions of curl and libcurl for any platform - we only ship source code releases (the so called tarballs, that are provided with a few different compression algorithms but all have the exact same content). We do however try to point to and even host as many third party provided curl packages we can and know of, which is why the download page is as long and populated as it is.

If there's missing packages, that's either because nobody told us about an existing such package so that there's no pointer to it, or perhaps there's nobody yet providing such packages. In either case, we rely on volunteers to provide what's not there now.

Like in every other aspect of an open source project: where's there's nothing right now there's an opportunity for someone to step up and help us.

That said, this is not a bug so I'm closing this issue.

**Closed by bagder** 2017-04-21 08:59 UTC
