### ISSUE TITLE
Performance fluctuation?

### ISSUE THREAD

**Issue by Phantomape** [curl/curl#6420] opened 2021-01-06 12:48 UTC
I was trying to do a benchmark on how DNS cache affects libcurl performance. However, I've noticed a weird situation that `curl_easy_perform` performs much faster in the first few runs, and then the performance drops and remain steady afterwards.

### I did this
Here is my source code
```
#include <curl/curl.h>
#include <thread>
#include <chrono>

static const int32_t numTests = 10;

static void BM_CURLWithoutDNSCache()
{
    CURL *curl = curl_easy_init();
    if (!curl)
    {
        return;
    }

    curl_easy_setopt(curl, CURLOPT_URL, "kubernetes:6443");
    /* only reuse addresses for a very short time */
    curl_easy_setopt(curl, CURLOPT_DNS_CACHE_TIMEOUT, 0L);

    CURLcode ret;
    for (size_t i = 0; i < numTests; i++)
    {
        auto start = std::chrono::high_resolution_clock::now();
        ret = curl_easy_perform(curl);
        auto end = std::chrono::high_resolution_clock::now();
        auto duration = std::chrono::duration_cast<std::chrono::microseconds>(end - start).count();
        std::cout << "curl_easy_perform costs: " << duration << " us" << std::endl;
    }
    curl_easy_cleanup(curl);
}

static void BM_CURLWithDNSCache()
{
    CURL *curl = curl_easy_init();
    if (!curl)
    {
        return;
    }

    curl_easy_setopt(curl, CURLOPT_URL, "kubernetes:6443");
    /* only reuse addresses for a very short time */
    curl_easy_setopt(curl, CURLOPT_DNS_CACHE_TIMEOUT, 10L);

    CURLcode ret;
    for (size_t i = 0; i < numTests; i++)
    {
        auto start = std::chrono::high_resolution_clock::now();
        ret = curl_easy_perform(curl);
        auto end = std::chrono::high_resolution_clock::now();
        auto duration = std::chrono::duration_cast<std::chrono::microseconds>(end - start).count();
        std::cout << "curl_easy_perform costs: " << duration << " us" << std::endl;
    }
    curl_easy_cleanup(curl);
}

int main() {
    BM_CURLWithDNSCache();
    BM_CURLWithoutDNSCache();
    return 0;
}
```
and the result is like this
![image](https://user-images.githubusercontent.com/8809221/103770107-6cf4d800-5060-11eb-8422-13b9545c8187.png)

### I expected the following

The curl performance should remain steady

### curl/libcurl version

libcurl.so.4.4.0 (default package libcurl4-openssl-dev under ubuntu 16.04)

[curl -V output]
```
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
```
### operating system

4.15.0-39-generic #42~16.04.1-Ubuntu SMP Wed Oct 24 17:09:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Update
The problem occurs when the domain name does not have a valid endpoint, when I tried to use a valid endpoint, the performance remains quite steady

**Comment by bagder** [comment] 2021-01-06 14:58
> curl 7.47.0

That seems like a version that is completely unnecessary to measure with - as its old, deprecated and we've fixed a bazillion things in curl since then. We'll only really care If you can reproduce with a modern version...

**Comment by jay** [comment] 2021-01-07 05:23
If you disable DNS caching then the transfers are going to take longer. I can't reproduce that in Ubuntu 16.04 LTS with 7.74 or the packaged 7.47 OpenSSL or GnuTLS version. Note `kubernetes` doesn't resolve so I changed it to a local hostname that does resolve but left the port at 6443 for connection refused. Turn on CURLOPT_VERBOSE and maybe that will give you an idea of what's happening.

~~~
owner@ubuntu1604-x64-vm:~$ g++ -o a a.cpp -std=c++11 -I /usr/include -L /usr/lib/x86_64-linux-gnu -lcurl -Wl,-rpath,/usr/lib/x86_64-linux-gnu
owner@ubuntu1604-x64-vm:~$ ./a
libcurl/7.47.0 OpenSSL/1.0.2g zlib/1.2.8 libidn/1.32 librtmp/2.3
curl_easy_perform costs: 6651 us
curl_easy_perform costs: 533 us
curl_easy_perform costs: 879 us
curl_easy_perform costs: 401 us
curl_easy_perform costs: 410 us
curl_easy_perform costs: 442 us
curl_easy_perform costs: 411 us
curl_easy_perform costs: 476 us
curl_easy_perform costs: 454 us
curl_easy_perform costs: 387 us
curl_easy_perform costs: 5087 us
curl_easy_perform costs: 5085 us
curl_easy_perform costs: 4883 us
curl_easy_perform costs: 5214 us
curl_easy_perform costs: 4823 us
curl_easy_perform costs: 5038 us
curl_easy_perform costs: 4982 us
curl_easy_perform costs: 4836 us
curl_easy_perform costs: 5055 us
curl_easy_perform costs: 4590 us
owner@ubuntu1604-x64-vm:~$ g++ -o a a.cpp -std=c++11 -I /usr/include -L /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 -Wl,-rpath,/usr/lib/x86_64-linux-gnu
owner@ubuntu1604-x64-vm:~$ ./a
libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
curl_easy_perform costs: 4760 us
curl_easy_perform costs: 437 us
curl_easy_perform costs: 571 us
curl_easy_perform costs: 389 us
curl_easy_perform costs: 530 us
curl_easy_perform costs: 579 us
curl_easy_perform costs: 403 us
curl_easy_perform costs: 1310 us
curl_easy_perform costs: 433 us
curl_easy_perform costs: 548 us
curl_easy_perform costs: 5581 us
curl_easy_perform costs: 4788 us
curl_easy_perform costs: 4509 us
curl_easy_perform costs: 4590 us
curl_easy_perform costs: 4884 us
curl_easy_perform costs: 4995 us
curl_easy_perform costs: 4881 us
curl_easy_perform costs: 5090 us
curl_easy_perform costs: 5059 us
curl_easy_perform costs: 5070 us
owner@ubuntu1604-x64-vm:~$ g++ -o a a.cpp -std=c++11 -fsanitize=address,undefined -fno-sanitize-recover -fno-omit-frame-pointer -Wformat -Werror=format-security -Werror=array-bounds -g -ggdb -rdynamic `curl-config --cflags --libs` -lcurl
owner@ubuntu1604-x64-vm:~$ ./a
libcurl/7.74.0 OpenSSL/1.1.1i zlib/1.2.8 nghttp2/1.42.0 librtmp/2.3
curl_easy_perform costs: 4739 us
curl_easy_perform costs: 460 us
curl_easy_perform costs: 396 us
curl_easy_perform costs: 517 us
curl_easy_perform costs: 526 us
curl_easy_perform costs: 491 us
curl_easy_perform costs: 970 us
curl_easy_perform costs: 467 us
curl_easy_perform costs: 445 us
curl_easy_perform costs: 592 us
curl_easy_perform costs: 2203 us
curl_easy_perform costs: 10260 us
curl_easy_perform costs: 2462 us
curl_easy_perform costs: 2909 us
curl_easy_perform costs: 4890 us
curl_easy_perform costs: 65490 us
curl_easy_perform costs: 1748 us
curl_easy_perform costs: 2140 us
curl_easy_perform costs: 1853 us
curl_easy_perform costs: 2234 us
~~~

~~~diff
--- a.cpp.orig	2021-01-07 00:10:41.182017447 -0500
+++ a.cpp	2021-01-07 00:10:27.769440918 -0500
@@ -1,7 +1,10 @@
 #include <curl/curl.h>
+#include <iostream>
 #include <thread>
 #include <chrono>
 
+using namespace std;
+
 static const int32_t numTests = 10;
 
 static void BM_CURLWithoutDNSCache()
@@ -12,7 +15,7 @@
         return;
     }
 
-    curl_easy_setopt(curl, CURLOPT_URL, "kubernetes:6443");
+    curl_easy_setopt(curl, CURLOPT_URL, "test:6443");
     /* only reuse addresses for a very short time */
     curl_easy_setopt(curl, CURLOPT_DNS_CACHE_TIMEOUT, 0L);
 
@@ -36,7 +39,7 @@
         return;
     }
 
-    curl_easy_setopt(curl, CURLOPT_URL, "kubernetes:6443");
+    curl_easy_setopt(curl, CURLOPT_URL, "test:6443");
     /* only reuse addresses for a very short time */
     curl_easy_setopt(curl, CURLOPT_DNS_CACHE_TIMEOUT, 10L);
 
@@ -53,6 +56,7 @@
 }
 
 int main() {
+    printf("%s\n", curl_version());
     BM_CURLWithDNSCache();
     BM_CURLWithoutDNSCache();
     return 0;
~~~

**Comment by bagder** [comment] 2021-01-10 14:47
I can't see any error here, can you?

**Comment by jay** [comment] 2021-01-10 21:24
No but I'd like the reporter to show us verbose output.

**Comment by bagder** [comment] 2021-01-18 22:21
@Phantomape, we will close this issue with "no error" unless you provide us with more data.

**Comment by nardl** [comment] 2021-01-24 21:54
[[[************]()]()]()]()]()

**Closed** 2021-01-31 22:30 UTC
Labels: HTTP, name lookup, needs-info-or-update, not-a-bug, performance
