### ISSUE TITLE
High CPU usage on macOS on network disconnect with long polling

### ISSUE THREAD

**Issue by nokeya** [curl/curl#4313] opened 2019-09-09 19:45 UTC
### I did this
Application using libcurl multi, based on asiohiper, with SSL and HTTP2.
Simultaneously running requests to one host:
- one long polling - waits on request, either for timeout or answer for 60 seconds
- one or more usual requests, with short timeout. server answers them momentarily 

Steps to reproduce:
1. Change urls to working ones, compile and run [https://pastebin.com/1j4SSQZx](https://pastebin.com/1j4SSQZx) - modified asiohiper: added more options for SSL, random requests to reproduce bug
2. See long polling request waiting, usual requests getting executed
3. Disconnect the network (turn Wi-Fi off)

### I expected the following

- Long polling request keep waiting on timers without any CPU load
- usual request failing on network errors

### What I got

- after first normal request failed, curl keeps reentering `event_cb` for long polling url again and again without any delay, making huge load on CPU
- usual requests failing on network errors, as expected

### Versions
Works well in 7.61.1 and prior
Broken in 7.62 and all after (master too)

- tested with asio 1.12 from boost 1.68
- nghttp2 version doesn't matter (tested on several)
- SSL backend and its version doesn't matter (tested several versions of openssl, also with libressl, darwinssl, boringssl)

### operating system
macOS 10.13, 10.14

**Comment by nokeya** [comment] 2019-09-09 19:50
libcurl built like this (example with openSSL, but it really doesn't matter)

`./configure --enable-ipv6 --with-ssl=/Users/user/dev_proj/openssl/build --with-nghttp2=/Users/user/dev_proj/nghttp2/build --disable-shared --enable-static --disable-ldap --prefix=/Users/user/dev_proj/curl-7.61.1/build --without-ca-path --without-ca-bundle --without-libidn2 CFLAGS="-mmacosx-version-min=10.11" --disable-manual --enable-hidden-symbols`

**Comment by nokeya** [comment] 2019-10-15 14:26
New info:
It is caused by `CURLMOPT_PIPELINING` set to `CURLPIPE_MULTIPLEX`.
If it is set, reproduces even on 7.61.1

Seems `CURLPIPE_MULTIPLEX` is default since 7.62, this is why at first I thought it was caused by that release

Also, macOS 10.15 too

**Comment by bagder** [comment] 2019-10-15 16:00
This is a fairly complicated recipe (>500 lines of code) using boost asio which I basically have on clue how it works.

> curl keeps reentering event_cb for long polling url again and again without any delay, making huge load on CPU

That's not exactly *curl* reentering that function, right? The comments says that function gets called by asio when there's activity on the socket? So that means *there's activity on the socket* ? What activity is that?

In this case then libcurl must've told your application via the socket callback to wait for such an activity on that socket and when your callback then tells libcurl about it, it doesn't update the application about what to wait for and thus the callback keeps getting called when the situation remains. It would perhaps indicate that libcurl doesn't properly detect the state of the connection at that point but I would need more details to better understand.

**Comment by nokeya** [comment] 2019-10-16 10:34
I debugged asio a little, seems that in handler of kqueue events we got `kevent`s with `EV_EOF` flag set for this socket ([kqueue doc](https://www.freebsd.org/cgi/man.cgi?kqueue)). According to the docs in this case socket is invalid and should no longer be used.

But we have no such info in `event_cb` callback.
I will investigate more, maybe this issue is caused by asio, not by curl

**Comment by bagder** [comment] 2019-12-16 13:45
As this issue cannot easily be reproduced without a specific third party library and the recipe is quite convoluted, I'm going to close this. If you can come up with a way to repro, that doesn't involve using another event library then I'm very interested. You should be able to simulate that with plain old poll() or similar just for the purpose of reproducing this problem, if indeed the problem is within libcurl.

**Closed by bagder** 2019-12-16 13:45 UTC
Labels: HTTP/2, performance, regression
