### ISSUE TITLE
Curl is ignoring content encoding in the case of metalink

### ISSUE THREAD

**Issue by ytrezq** [curl/curl#7111] opened 2021-05-20 19:27 UTC
example@WINDOWS81:/mnt/c/Users/example/Desktop/rtorrent/test$ curl --compressed --metalink http://ytrezq.sdfeu.org/info/OpenEthereum.metalink -o OpenEthereum.metalink -v
    Metalink: parsing (http://ytrezq.sdfeu.org/info/OpenEthereum.metalink) metalink/XML...
    *   Trying 178.63.35.195:80...
    * Connected to ytrezq.sdfeu.org (178.63.35.195) port 80 (#0)
    > GET /info/OpenEthereum.metalink HTTP/1.1
    > Host: ytrezq.sdfeu.org
    > User-Agent: curl/7.76.1
    > Accept: */*
    > Accept-Encoding: deflate, gzip, br
    > Connection: Upgrade, HTTP2-Settings
    > Upgrade: h2c
    > HTTP2-Settings: AAMAAABkAAQCAAAAAAIAAAAA
    >
    * Mark bundle as not supporting multiuse
    < HTTP/1.1 200 OK
    < Date: Thu, 20 May 2021 18:55:01 GMT
    < Server: Apache/2.2.32 (Unix) mod_ssl/2.2.34 OpenSSL/1.0.2o
    < Last-Modified: Sun, 16 May 2021 09:15:13 GMT
    < ETag: "1cb5f3d9-679f93f-5c26eea1f55d4"
    < Accept-Ranges: bytes
    < Content-Length: 108656959
    < Content-Type: application/x-git-receive-pack-advertisement
    < Content-Encoding: gzip
    < Content-Language: fr-FR
    <
    Metalink: parsing FAILED
    * Failure writing output to destination
    * Closing connection 0
    curl: (23) Failure writing output to destination

The reason is it didn’t decompress the network stream.

**Comment by bagder** [comment] 2021-05-20 21:14
How do you know it didn't? The (auto) decompression is done by libcurl while all metalink logic is in the tool code, which makes me wonder why metalink on/off can have even the tiniest effect on compression...

**Comment by bagder** [comment] 2021-05-20 21:50
When I try with curl 7.74.0, it works and the file starts to download.

When I instead try the command line with current master it fails to download the file, but I do not get the metalink error message. It looks like a regression...

**Comment by ytrezq** [comment] 2021-05-21 07:38
> When I try with curl 7.74.0, it works and the file starts to download.
> 
> When I instead try the command line with current master it fails to download the file, but I do not get the metalink error message. It looks like a regression...

@bagder the reason is I updated file. Now curl core dumps after downloading a few files from the metalink.

**Comment by bagder** [comment] 2021-05-21 13:43
If you run it with gdb or valgrind, do you get any more details about the segfault? What libmetalink version are you using? What TLS library did you build with?

**Comment by ytrezq** [comment] 2021-05-21 13:47
@bagder I m simply using up to date Fedora rawhide packages. Did you try with the new file?

**Comment by bagder** [comment] 2021-05-21 13:51
> @bagder I m simply using up to date Fedora rawhide packages

Then can't you check and tell me?

> Did you try with the new file?

Yes. It doesn't crash for me.

**Comment by ytrezq** [comment] 2021-05-21 13:54
> > Did you try with the new file?
> 
> Yes. It doesn't crash for me.

Even after downloading the first 1000 files?

**Comment by bagder** [comment] 2021-06-02 22:03
I'm sorry, but we are looking into completely removing metalink support from curl: #7176

**Comment by jay** [comment] 2021-06-13 06:45
Sorry but metalink is no longer supported. Won't fix.

**Closed by jay** 2021-06-13 06:45 UTC
Labels: HTTP, cmdline tool, needs-info-or-update
