### ISSUE TITLE
cURL using connection specific headers which violates HTTP/2

### ISSUE THREAD

**Issue by brjoha** [curl/curl#3832] opened 2019-05-02 21:20 UTC
### I did this
% curl -v -x [proxy] http://dummy.restapiexample.com/api/v1/employees --http2-prior-knowledge

### I expected the following
[success]

### curl/libcurl version
7.64.1

[curl -V output]
$ curl -v -x [proxy] http://dummy.restapiexample.com/api/v1/employees --http2-prior-knowledge
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x1b99480)
> GET http://dummy.restapiexample.com/api/v1/employees HTTP/2
> Host: dummy.restapiexample.com
> User-Agent: curl/7.64.1
> Accept: */*
> Proxy-Connection: Keep-Alive
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
* HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
* stopped the pause stream!
* Connection #0 to host 127.0.0.1 left intact
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
* Closing connection 0

### operating system
Linux

### notes
The appearance of the "Proxy-Connection" header is an RFC violation.

HTTP/2 prohibits connection-specific header fields. The following header fields must not appear: "Connection", "Keep-Alive", "Proxy-Connection", "Transfer-Encoding" and "Upgrade". Additionally, "TE" header field must not include any value other than "trailers".

**Comment by jay** [comment] 2019-05-02 22:05
Invalid http2 headers should be ignored and not sent.
https://github.com/curl/curl/blob/521bbbe29928f9bc1c61306df612e856d45cbe5a/lib/http2.c#L1818-L1844

![Capture](https://user-images.githubusercontent.com/965580/57109759-52535300-6d04-11e9-9bc5-56503059aae0.PNG)

Anyway that is not the issue. This looks like a duplicate of #3570 since we don't support HTTP/2 proxies yet as noted in the TODO:
https://github.com/curl/curl/blob/521bbbe29928f9bc1c61306df612e856d45cbe5a/docs/TODO#L260-L262

I think though it's an interesting point whether `--http2-prior-knowledge` should apply to http proxies.

**Comment by brjoha** [comment] 2019-05-03 02:17
cURL is talking HTTP/2 to the proxy server (it is nghttp2 based), which closes the stream with a protocol error because of the connection header presence.   If the proxy option is not used, so that the proxy server becomes the destination server, then cURL omits the connection header and the stream is accepted.

**Comment by jay** [comment] 2019-05-03 02:55
This is essentially a duplicate of #3570 AFAICT. We don't support HTTP/2 proxy servers. I confirmed in Wireshark the header is not sent (see screenshot). However I will leave this open for a bit to see if anyone else has a different take.

**Comment by bagder** [comment] 2019-05-04 22:08
I'm with you @jay. We should fix the proxy support though...

> --http2-prior-knowledge

Yeah, it should *probably* apply to the target server and not a proxy...

**Comment by jay** [comment] 2019-05-09 02:58
Since we don't support HTTP/2 proxies yet I've changed libcurl to ignore the HTTP/2 prior knowledge setting except when tunneling to the destination host. If you need HTTP/2 to the destination host you'll have to tunnel it using [--proxytunnel](https://curl.haxx.se/docs/manpage.html#-p).

**Closed by jay** 2019-05-09 02:58 UTC
Labels: HTTP/2, connecting & proxies, duplicate
