### ISSUE TITLE
curl_multi still breaks in 8.10.1 with libev

### ISSUE THREAD

**Issue by JulesRapanga** [curl/curl#15154] opened 2024-10-04 21:11 UTC
### I did this

I use libcurl in my product with `libev` and `curl_multi` following the pattern in ~multi-event.c~[evhiperfifo](https://github.com/curl/curl/blob/master/docs/examples/evhiperfifo.c). We had deployed 8.10.0 and noticed the effects of https://github.com/curl/curl/issues/14898 after a couple of days and had to do a rollback. We updated to 8.10.1 once we realised it had the fix, but after running it in for a week (after 500,000 requests on 40 machines) one of the machines hit the problem again.

Obviously that's not very reproducible but one complete lockup is too many. 

I can make and run debug builds if you've got any patches or flags that might shed light on what's going on but I don't know of a way to trigger the freeze itself.

### I expected the following

curl_multi to not freeze.

### curl/libcurl version

curl 8.10.1

### operating system

Ubuntu Focal

**Comment by JulesRapanga** [comment] 2024-10-05 12:43
We don't know what triggers it but we can detect it once it has happened so we could for example set the `CURLOPT_DEBUGFUNCTION` on subsequent requests. We could build with `--enable-debug` but perhaps you know of some relevant internal curl state that would help shed light on the situation?

**Comment by bagder** [comment] 2024-10-06 21:08
What makes you convinced it is related to #14898 ?

**Comment by JulesRapanga** [comment] 2024-10-07 07:20
It has the same symptoms we experienced 8.10.0; calls to `curl_multi_add_handle` returns `CURLM_OK` so we log that the request has started, but the request is never made and we never get `curl_multi_info_read` returning `CURLMSG_DONE` (unclear if that's because we're no longer getting the callbacks from `libev` that lead to us calling that.

**Comment by jonitis** [comment] 2024-10-09 09:05
I can just add that after updating from CURL 8.7.1 to 8.10.1 we also see regressions or changes in behaviour:

1. Starting from CURL 8.8.0 the curl_easy_getinfo(CURLINFO_SCHEME) returns scheme in lowercase, when previously it was returned in uppercase. Documentation was updated to use case-insensitive string matching. Unless clients know about this change they get broken code that worked previously.
2. Previously it was sufficient to call curl_easy_setopt(CURLOPT_CUSTOMREQUEST, "PUT") to do https upload. With new version it requires curl_easy_setopt(CURLOPT_UPLOAD, 1). Otherwise the callback for reading data (CURLOPT_READFUNCTION) is not called.
3. For every second HTTPS GET request to download file from server I get error code 42 (CURLE_ABORTED_BY_CALLBACK (42) Aborted by callback. A callback returned "abort" to libcurl.). Handler code for CURLOPT_WRITEFUNCTION just writes portions of downloaded data to file. We also use curl_multi API for asynchronous operations (not libev, but similar libubox mainloop library from OpenWRT). Other users that use just curl_easy API does not seem to be affected. Will investigate more, but I do not think the callback function ever returned size_t smaller than libcurl provided (we always say that we consumed all data). I can't rule out we use API in wrong way, but reverting to 8.7.1 fixes problem.

**Comment by bagder** [comment] 2024-10-09 09:08
@jonitis Please don't pile on unrelated details in this issue. Those are clearly other issues and should be filed as separate entries and be treated individually.

**Comment by jonitis** [comment] 2024-10-09 14:25
Related detail is that problem with CURLE_ABORTED_BY_CALLBACK errors when using curl_multi API appeared between 8.8.0 (GOOD) and 8.9.0 (BAD).

**Comment by JulesRapanga** [comment] 2024-10-10 10:14
@bagder (or maybe @icing) I have a core dump and can examine the `struct Curl_easy` of a stuck request in 8.10.1 (stuck for ~20 minutes before we killed it). Is there anything in that (or reachable from that) which would be useful in debugging this? If not, is there something that we should inspect 'live' next time it happens instead of going straight to coredumping?

**Comment by bagder** [comment] 2024-10-16 07:17
What is the state of the transfer when it gets stuck? What protocol? I assume you run the OpenSSL backend? Which OpenSSL version?

Getting a log trace of such a transfer might reveal details. `curl_global_trace("all");` maybe.

**Comment by JulesRapanga** [comment] 2024-10-16 08:55
[curl_easy_and_multi.txt](https://github.com/user-attachments/files/17392126/curl_easy_and_multi.txt) <- dump of the stuck `Curl_easy` and `Curl_multi` objects.
I can't pretend to understand the thousand members of `Curl_multi` and `Curl_easy` but `mstate = MSTATE_INIT` suggests that it hasn't started working on it at all. I believe that the `ev_run` worker has not locked up as it continues to perform related tasks. 
The request is HTTPS PUT, we use a patched version of OpenSSL based on 1.1.1za.

We've been running libcurl 8.9.1 with our debug to notice a stall for a week on around 700 machines and haven't seen any sign of a stall, so we're very confident that it's a libcurl change that is to blame. 

I'll add `curl_global_trace("all");` to our next build and and see if I can run that (along with libcurl 8.10.1) on a number of non-production nodes to see what we see.

**Comment by AchilleasTsiamoulis** [comment] 2024-10-28 21:16
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by bagder** [comment] 2024-11-09 09:41
How about creating a small example source code based on the same logic that your app has, that reproduces the problem so that someone else can help you debug this?

**Comment by sokurenko** [comment] 2024-11-22 15:02
Can you please try with https://github.com/curl/curl/pull/15627 ? It fixed issue for me

**Comment by jay** [comment] 2024-11-26 06:14
#15627 has since landed in 4cded6de. Please try to reproduce from the master branch.

**Comment by JulesRapanga** [comment] 2024-11-27 15:01
I wasn't able to reproduce it without the fix but I didn't try anything in particular to induce it other than running my service on a few dozen machines for a month. It did happen again but on a build running without debug. It does sound like https://github.com/curl/curl/pull/15627 could be the answer though, and it's unlikely that there's a *third* bug coming out of https://github.com/curl/curl/commit/a58b50fca6eb543896a7c1cb05bb21aa1fc49251.

**Comment by jay** [comment] 2024-11-29 17:44
The next release is on December 11. If you can reproduce it in that release then we'll take another look.

**Closed by jay** 2024-11-29 17:44 UTC
Labels: needs-info, multi-event
