### ISSUE TITLE
Max TLS1.1 but OUT is TLS 1.3

### ISSUE THREAD

**Issue by abeumer** [curl/curl#5356] opened 2020-05-08 12:49 UTC
We have some older servers which are maintained for legacy purposes and I can't upgrade them to support a higher TLS version.
After updating my Ubuntu 20.04 development server to openssl 1.1.1f and curl 7.68.0 I can no longer connect to them using PHP + curl.

I got the error: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol

So after trying several things I noticed that it tried to connect using a to high TLS version as our legacy servers only support TLS 1.1

So I tried specifying the max TLS protocol using:
curl_setopt($curl, CURLOPT_SSLVERSION, CURL_SSLVERSION_MAX_TLSv1_1);
Which did not help. I still got the "unsupported protocol" error.

I than switched to the command line to run the curl command directly.
curl -v --tls-max 1.1 https://curl.haxx.se/
And I noticed that it still says
* TLSv1.3 (OUT), TLS alert, internal error (592):

### I did this
~~~
curl -v --tls-max 1.1 https://curl.haxx.se/
*   Trying 151.101.130.49:443...
* TCP_NODELAY set
* Connected to curl.haxx.se (151.101.130.49) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS alert, internal error (592):
* error:141E70BF:SSL routines:tls_construct_client_hello:no protocols available
* Closing connection 0
curl: (35) error:141E70BF:SSL routines:tls_construct_client_hello:no protocols available
~~~

Running the same command on a CentOS 7.7 machine with curl 7.29.0 works:
~~~
curl -v --tls-max 1.1 https://curl.haxx.se/
* About to connect() to curl.haxx.se port 443 (#0)
*   Trying 151.101.2.49...
* Connected to curl.haxx.se (151.101.2.49) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=j2.shared.global.fastly.net,O="Fastly, Inc.",L=San Francisco,ST=California,C=US
*       start date: mrt 12 19:08:12 2020 GMT
*       expire date: mrt 07 17:48:32 2021 GMT
*       common name: j2.shared.global.fastly.net
*       issuer: CN=GlobalSign CloudSSL CA - SHA256 - G3,O=GlobalSign nv-sa,C=BE
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: curl.haxx.se
> Accept: */*
> 
< HTTP/1.1 200 OK
< Connection: keep-alive
< Content-Length: 8700
< Server: Apache
< X-Frame-Options: SAMEORIGIN
< Last-Modified: Fri, 08 May 2020 10:05:05 GMT
~~~

### I expected the following
I expected a working TLS 1.1 connection

### curl/libcurl version
openssl 1.1.1f
curl 7.68.0

[curl -V output]
~~~
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
~~~

### operating system
~~~
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
~~~

Linux srv02 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment] 2020-05-08 14:57
First: `--tls-max` was introduced in 6448f98c1857de521fb2dd3f9d4e5659845b5474 (#1166), shipped the first time in 7.54.0... You obviously could not use that in an earlier curl version!

Then: I don't get any internal error with OpenSSL 1.1.1g against curl.haxx.se when I try it and I claim the option works since the curl site refuses to negotiate below TLS 1.2. "internal error" from OpenSSL also doesn't sound like a curl issue.

Shouldn't you rather point out a TLS 1.1-using server that you can't connect to?

**Comment by emilengler** [comment] 2020-05-08 15:08
Can you post the output of `openssl ciphers -s -v`?
This shows the available ciphers of your OpenSSL built. I think the problem is that openssl was compiled without TLS 1.1 support

**Comment by bagder** [comment] 2020-05-08 15:23
Who are you asking @emilengler ?

In my case `openssl ciphers -s -v`  show lots of TLSv1 and even SSLv3. But I also tried `openssl s_client -tls1_1 -connect curl.haxx.se:443` and it gets an error very similar to curl's: `SSL routines:ssl3_read_bytes:tlsv1 alert protocol version`.

**Comment by emilengler** [comment] 2020-05-08 15:26
@bagder I was asking @abeumer.
I have similar results on Debian buster

**Comment by jay** [comment] 2020-05-09 06:16
Ubuntu 16:
~~~
owner@ubuntu1604-x64-vm:~$ curl -v --tls-max 1.1 https://curl.haxx.se/
*   Trying 151.101.2.49:443...
* TCP_NODELAY set
* Connected to curl.haxx.se (151.101.2.49) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.1 (OUT), TLS handshake, Client hello (1):
* TLSv1.1 (IN), TLS alert, protocol version (582):
* error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
* Closing connection 0
curl: (35) error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
~~~
~~~
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1d zlib/1.2.8 nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets
~~~

> * TLSv1.3 (OUT), TLS alert, internal error (592):
> * error:141E70BF:SSL routines:tls_construct_client_hello:no protocols available

That doesn't make any sense shouldn't it be (IN)

**Comment by jay** [comment] 2020-05-09 06:20
> That doesn't make any sense shouldn't it be (IN)

Actually I guess it could make sense if your OpenSSL was built in a way that it just doesn't support it.

**Comment by abeumer** [comment] 2020-05-11 06:21
> Can you post the output of `openssl ciphers -s -v`?
> This shows the available ciphers of your OpenSSL built. I think the problem is that openssl was compiled without TLS 1.1 support

openssl ciphers -s -v
TLS_AES_256_GCM_SHA384  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(256) Mac=AEAD
TLS_CHACHA20_POLY1305_SHA256 TLSv1.3 Kx=any      Au=any  Enc=CHACHA20/POLY1305(256) Mac=AEAD
TLS_AES_128_GCM_SHA256  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(128) Mac=AEAD
ECDHE-ECDSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AESGCM(256) Mac=AEAD
ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AESGCM(256) Mac=AEAD
DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD
ECDHE-ECDSA-CHACHA20-POLY1305 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=CHACHA20/POLY1305(256) Mac=AEAD
ECDHE-RSA-CHACHA20-POLY1305 TLSv1.2 Kx=ECDH     Au=RSA  Enc=CHACHA20/POLY1305(256) Mac=AEAD
DHE-RSA-CHACHA20-POLY1305 TLSv1.2 Kx=DH       Au=RSA  Enc=CHACHA20/POLY1305(256) Mac=AEAD
ECDHE-ECDSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AESGCM(128) Mac=AEAD
ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AESGCM(128) Mac=AEAD
DHE-RSA-AES128-GCM-SHA256 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(128) Mac=AEAD
ECDHE-ECDSA-AES256-SHA384 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AES(256)  Mac=SHA384
ECDHE-RSA-AES256-SHA384 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AES(256)  Mac=SHA384
DHE-RSA-AES256-SHA256   TLSv1.2 Kx=DH       Au=RSA  Enc=AES(256)  Mac=SHA256
ECDHE-ECDSA-AES128-SHA256 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AES(128)  Mac=SHA256
ECDHE-RSA-AES128-SHA256 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AES(128)  Mac=SHA256
DHE-RSA-AES128-SHA256   TLSv1.2 Kx=DH       Au=RSA  Enc=AES(128)  Mac=SHA256
ECDHE-ECDSA-AES256-SHA  TLSv1 Kx=ECDH     Au=ECDSA Enc=AES(256)  Mac=SHA1
ECDHE-RSA-AES256-SHA    TLSv1 Kx=ECDH     Au=RSA  Enc=AES(256)  Mac=SHA1
DHE-RSA-AES256-SHA      SSLv3 Kx=DH       Au=RSA  Enc=AES(256)  Mac=SHA1
ECDHE-ECDSA-AES128-SHA  TLSv1 Kx=ECDH     Au=ECDSA Enc=AES(128)  Mac=SHA1
ECDHE-RSA-AES128-SHA    TLSv1 Kx=ECDH     Au=RSA  Enc=AES(128)  Mac=SHA1
DHE-RSA-AES128-SHA      SSLv3 Kx=DH       Au=RSA  Enc=AES(128)  Mac=SHA1
AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
AES128-GCM-SHA256       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(128) Mac=AEAD
AES256-SHA256           TLSv1.2 Kx=RSA      Au=RSA  Enc=AES(256)  Mac=SHA256
AES128-SHA256           TLSv1.2 Kx=RSA      Au=RSA  Enc=AES(128)  Mac=SHA256
AES256-SHA              SSLv3 Kx=RSA      Au=RSA  Enc=AES(256)  Mac=SHA1
AES128-SHA              SSLv3 Kx=RSA      Au=RSA  Enc=AES(128)  Mac=SHA1

**Comment by abeumer** [comment] 2020-05-11 07:04
> Shouldn't you rather point out a TLS 1.1-using server that you can't connect to?

I tried a different machine that's still on Ubuntu 19.10:
curl 7.65.3
OpenSSL 1.1.1c  28 May 2019
curl -v --tls-max 1.1 https://backup02.mindtime.nl
*   Trying 178.20.173.70:443...
* TCP_NODELAY set
* Connected to backup02.mindtime.nl (178.20.173.70) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.1 (OUT), TLS handshake, Client hello (1):
* TLSv1.1 (IN), TLS handshake, Server hello (2):
* TLSv1.0 (IN), TLS handshake, Certificate (11):
* TLSv1.0 (IN), TLS handshake, Server finished (14):
* TLSv1.0 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.0 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.0 (OUT), TLS handshake, Finished (20):
* TLSv1.0 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.0 / AES256-SHA
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Wildcard; CN=*.mindtime.nl
*  start date: Dec 18 00:00:00 2017 GMT
*  expire date: Dec 31 23:59:59 2020 GMT
*  subjectAltName: host "backup02.mindtime.nl" matched cert's "*.mindtime.nl"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: backup02.mindtime.nl
> User-Agent: curl/7.65.3

On the Ubuntu 20.04 machine:
curl 7.68.0
OpenSSL 1.1.1f  31 Mar 2020
curl -v --tls-max 1.1 https://backup02.mindtime.nl
*   Trying 178.20.173.70:443...
* TCP_NODELAY set
* Connected to backup02.mindtime.nl (178.20.173.70) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS alert, internal error (592):
* error:141E70BF:SSL routines:tls_construct_client_hello:no protocols available
* Closing connection 0
curl: (35) error:141E70BF:SSL routines:tls_construct_client_hello:no protocols available

I just upgraded using do-release-upgrade and apt-get dist-upgrade after a while.
So no special custom installation of openssl or curl

**Comment by bagder** [comment] 2020-05-11 09:03
It seems entirely depending on the openssl build. I tried with my own build of openssl from git (reasonably up-to-date with master) :

~~~
$ curl -v --tls-max 1.1 https://backup02.mindtime.nl
...
* SSL connection using TLSv1.0 / AES256-SHA
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Wildcard; CN=*.mindtime.nl
*  start date: Dec 18 00:00:00 2017 GMT
*  expire date: Dec 31 23:59:59 2020 GMT
...
~~~
It that works fine.

But still:
~~~
$ curl -v --tls-max 1.1 https://curl.haxx.se/ -o /dev/null
...
curl: (35) error:1400042E:SSL routines::tlsv1 alert protocol version
~~~
curl version:
~~~
curl 7.71.0-DEV (x86_64-pc-linux-gnu) libcurl/7.71.0-DEV OpenSSL/3.0.0 zlib/1.2.11 brotli/1.0.7 c-ares/1.15.0 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) nghttp2/1.41.0-DEV librtmp/2.3
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli Debug GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP TrackMemory UnixSockets

**Comment by corentingi** [comment] 2020-05-11 11:18
Hello,

I've been having the same issue with a few colleagues on both Linux 20.04 and MacOS Mojave.

The problem also affects `--tlsv1.x` flags and it depends on the curl version / openssl version in use.

I'll try to add some version examples where it's working or not.

**Comment by abeumer** [comment] 2020-05-11 11:25
> The problem also affects `--tlsv1.x` flags and it depends on the curl version / openssl version in use.

Don't forget that the --tlsv1.x parameter meaning changed as well.
--tlsv1.x means TLS 1.1 **or higher**. it used to mean: use TLS 1.1

**Comment by corentingi** [comment] 2020-05-11 11:26
Ok I see. I should have checked the man page before...

**Comment by bagder** [comment] 2020-05-11 11:29
> Don't forget that the --tlsv1.x parameter meaning changed as well.

The parameter changed **for some configurations** since it didn't work uniformly across curl and its many backends. We consider that a bugfix.

**Comment by abeumer** [comment] 2020-05-13 09:54
So if I understand correctly: The problem is not with Curl.
It's with openssl being build without support for older TLS versions like 1.1.

So I would have to rebuild openssl with support for TLS1.1 to fix this issue?

**Comment by jay** [comment] 2020-05-13 18:16
According to [this answer](https://stackoverflow.com/a/50111708) on SO if you're using OpenSSL 1.1.x then you can get the supported versions from the command line:
~~~shell
/usr/local/ssl/bin/openssl s_client -help 2>&1 | awk '/-ssl[0-9]|-tls[0-9]/{print $1}''
~~~

**Comment by bagder** [comment] 2020-05-15 15:17
Yes, I believe you need to make sure your TLS library supports 1.1. I don't think this is a curl issue.

**Comment by malle-pietje** [comment] 2020-05-16 06:24
Chiming in here with the same issue on Ubuntu 20.04. Here's the list of supported TLS versions in openssl:
```
# openssl s_client -help 2>&1 | awk '/-ssl[0-9]|-tls[0-9]/{print $1}'
-tls1
-tls1_1
-tls1_2
-tls1_3
```

**Comment by jay** [comment] 2020-05-16 06:44
Is it all websites or just some? How about https://example.com? Can you capture it in Wireshark?
`curl -v --tls-max 1.1 https://example.com`

**Comment by malle-pietje** [comment] 2020-05-16 09:12
From the Ubuntu 20.04 host:
```
# curl -v --tls-max 1.1 https://example.com
*   Trying 93.184.216.34:443...
* TCP_NODELAY set
* Connected to example.com (93.184.216.34) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS alert, internal error (592):
* error:141E70BF:SSL routines:tls_construct_client_hello:no protocols available
* Closing connection 0
curl: (35) error:141E70BF:SSL routines:tls_construct_client_hello:no protocols available
```
From another host where this issue does not occur:
```
curl -v --tls-max 1.1 https://example.com
* Rebuilt URL to: https://example.com/
*   Trying 93.184.216.34...
* TCP_NODELAY set
* Connected to example.com (93.184.216.34) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (OUT), TLS change cipher, Client hello (1):
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS Unknown, Certificate Status (22):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using unknown / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=Los Angeles; O=Internet Corporation for Assigned Names and Numbers; OU=Technology; CN=www.example.org
*  start date: Nov 28 00:00:00 2018 GMT
*  expire date: Dec  2 12:00:00 2020 GMT
*  subjectAltName: host "example.com" matched cert's "example.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* (304) (OUT), TLS Unknown, Unknown (23):
* (304) (OUT), TLS Unknown, Unknown (23):
* (304) (OUT), TLS Unknown, Unknown (23):
* Using Stream ID: 1 (easy handle 0x55a0725dc4a0)
* (304) (OUT), TLS Unknown, Unknown (23):
> GET / HTTP/2
> Host: example.com
> User-Agent: curl/7.60.0
> Accept: */*
> 
....
```

**Comment by malle-pietje** [comment] 2020-05-16 09:55
From the same host but with different max TLS level:
```
# curl -v --tls-max 1.2 https://example.com
*   Trying 93.184.216.34:443...
* TCP_NODELAY set
* Connected to example.com (93.184.216.34) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=Los Angeles; O=Internet Corporation for Assigned Names and Numbers; OU=Technology; CN=www.example.org
*  start date: Nov 28 00:00:00 2018 GMT
*  expire date: Dec  2 12:00:00 2020 GMT
*  subjectAltName: host "example.com" matched cert's "example.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5575ee4dec20)
> GET / HTTP/2
...
```

**Comment by malle-pietje** [comment] 2020-05-16 09:56
Not a specialist in that area but this makes me think the TLS 1.1 implementation in openssl is broken...

**Comment by bagder** [comment] 2020-05-28 14:14
Closing. Everything said in here so far points to this being artifacts/limitations in the TLS library and not in curl, suggesting this is not an issue for us. If there's any evidence indicating that curl is actually misbehaving, please speak up and I will reopen.

**Closed by bagder** 2020-05-28 14:14 UTC
Labels: SSL/TLS

**Comment by fuomag9** [comment] 2021-12-07 23:01
btw, running `curl -v --tls-max 1.1 https://example.com` on an `ubuntu:18.04` container works, on a `ubuntu:20.04` container fails as per the errors of @malle-pietje

**Comment by abeumer** [comment] 2021-12-08 07:37
Edit /etc/ssl/openssl.cnf

Change:
[default_conf]
ssl_conf = ssl_sect
[ssl_sect]
system_default = system_default_sect
[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT@SECLEVEL=2

To
[default_conf]
ssl_conf = ssl_sect
[ssl_sect]
system_default = system_default_sect
[system_default_sect]
MinProtocol = TLSv1.**1**
CipherString = DEFAULT@SECLEVEL=**1**

And it should work again. Keep in mind that this is lowering the security settings!
