### ISSUE TITLE
ltmain.sh problem on AIX by use bounce shell (curl 7.60.0)

### ISSUE THREAD

**Issue by elephoenix** [curl/curl#2611] opened 2018-05-28 08:12 UTC
### I did this

 1125           for _G_char in '\' '`' '"' '$' 
 1130             IFS=$_G_char
 1131             for _G_part in $func_quote_portable_result

-bash-3.00$ uname -a
AIX aix61-dev6 1 6 000CDA62D600
-bash-3.00$ 
-bash-3.00$ cat t.sh  
#!/bin/sh

func_quote_portable_result="aaa\\bbb\\ccc"
#func_quote_portable_result="aaa\`bbb\`ccc"
#func_quote_portable_result="aaa\"bbb\"ccc"
#func_quote_portable_result="aaa\$bbb\$ccc"

for _G_char in '\' '`' '"' '$'; do
  IFS=$_G_char
  for _G_part in $func_quote_portable_result; do
        echo "part : $_G_part"
  done
done

-bash-3.00$ 
-bash-3.00$ sh ./t.sh
part : aabbpart : aabbpart : aabbpart : aabb-bash-3.00$ 
-bash-3.00$ 
-bash-3.00$ ls -al /bin/sh
-r-xr-xr-x    5 bin      bin          288056 Oct 05 2007  /bin/sh
-bash-3.00$ 

### I expected the following
backslash can use as IFS on AIX

### curl/libcurl version

7.60.0

### operating system
AIX6.1

**Comment by bagder** [comment] 2018-05-28 08:55
Well unfortunately the `ltmain.sh` file is generated by `libtoolize`, a part of the libtool project - so this is an issue easily fixed by us. When we generate releases, a fresh one is generated. In the 7.60.0 release, the file was generated with libtool 2.4.6 (the debian package is named `2.4.6 Debian-2.4.6-2.1`)

Did 7.59.0 build fine? That was produced with an older version of the debian package at release time (`2.4.6 Debian-2.4.6-2`). I'm attaching the file from 7.59.0 for convenience, just rename it to `ltmain.sh` and run everything again.

[ltmain.sh from 7.59.0](https://github.com/curl/curl/files/2044393/ltmain.sh-7.59.0.txt)

**Comment by elephoenix** [comment] 2018-05-28 09:44
yes, 7.59.0 is ok.

The problem looks like is backslash can't use IFS on bounce shell.
I've wrote a test program test this problem.

================
-bash-3.00$ cat b.sh 
#!/bin/sh

IFS='\'
mystr="ab\cd\ef"
for part in $mystr; do
    echo "what $part"
done

-bash-3.00$ 
-bash-3.00$ bash b.sh
what ab
what cd
what ef
-bash-3.00$ 
-bash-3.00$ sh b.sh 
what ab-bash-3.00$ 
-bash-3.00$ 
================

**Comment by elephoenix** [comment] 2018-05-28 10:44
Tried with libcurl 7.60.0 with 7.59.0's ltmain.sh, it's okay. however is it really ok to do so?

**Comment by bagder** [comment] 2018-05-28 10:45
Yes, it is perfectly fine.

**Comment by elephoenix** [comment] 2018-05-28 10:48
ok.  but better have solution on this problem in next release, many thanks! :)

**Comment by bagder** [comment] 2018-05-28 11:35
Yes, I would like to see this fixed before then. Ideally in the package I use, but if not I'll consider downgrading my package to the previous version.

I reported this issue [in the debian bug tracker](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=900276) as well.

**Comment by bagder** [comment] 2018-10-10 21:44
That debian bug is now closed and the issue is said to be fixed in Debian's libtool version "2.4.6-6"

**Comment by danielgustafsson** [comment] 2018-11-12 08:49
Does that mean we can close this as it will be fixed in the next release (unless it was already fixed in 7.62.0 that is..)

**Comment by bagder** [comment] 2018-11-12 09:30
I believe this was fixed already in 7.62.0. Can you verify @elephoenix ?

**Comment by bagder** [comment] 2019-03-07 12:16
Probably fixed.

**Closed by bagder** 2019-03-07 12:16 UTC
Labels: build
