### ISSUE TITLE
Crash at HTTPS connection end

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#2777] opened 2018-07-22 14:55 UTC
### I did this

Test case 2043:
`curl --ssl-no-revoke https://revoked.grc.com/`
results in a read access violation with the following call stack because `conn->data` is null:
```
Curl_ssl_sessionid_lock(connectdata * conn=[nonnull])
Curl_schannel_shutdown(connectdata * conn=[nonnull], int sockindex=0)
Curl_ssl_shutdown(connectdata * conn=[nonnull], int sockindex=0)
Curl_schannel_close(connectdata * conn=[nonnull], int sockindex=0)
Curl_ssl_close(connectdata * conn=[nonnull], int sockindex=0)
Curl_disconnect(Curl_easy * data=[nonnull], connectdata * conn=[nonnull], bool dead_connection=false)
Curl_conncache_close_all_connections(conncache * connc=[nonnull])
curl_multi_cleanup(Curl_multi * multi=[nonnull])
Curl_close(Curl_easy * data=[nonnull])
curl_easy_cleanup(Curl_easy * data=[nonnull])
main_free(GlobalConfig * config=[nonnull])
main(int argc=[...], char * * argv=[nonnull])
```

It's set to `NULL` when `Curl_disconnect` calls `Curl_conncache_remove_conn` as `conn->bundle` is nonnull.

### I expected the following

No crash.

### curl/libcurl version

https://github.com/curl/curl/commit/6d13432bfa1097da7efb4a5fffac27a22af2002c
```
curl 7.61.1-DEV (Windows) libcurl/7.61.1-DEV WinSSL
Release-Date: [unreleased]
Protocols: http https
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL
```

### operating system

Windows 10

**Comment by bagder** [comment] 2018-07-22 15:30
Yes, I believe #2771 is the fix

**Comment by MarcelRaad** [comment] 2018-07-22 19:08
Ah, I missed that. Looks good!

**Comment by bagder** [comment] 2018-07-22 19:16
Duplicate of #2764

**Closed by bagder** 2018-07-22 19:16 UTC
