### ISSUE TITLE
cURL command parameters problem, not retrying the right number of times

### ISSUE THREAD

**Issue by googled** [curl/curl#4923] opened 2020-02-14 04:34 UTC
Here's my cURL command:

```
/usr/bin/curl --ipv4 --connect-timeout 1 --retry 15 --retry-delay 2 --retry-max-time 15 --no-keepalive --no-tcp-nodelay -L --silent 'http://www.example.org' -v --trace-time
```

When there's a network congestion issue, it doesn't retry the number of times specified... Here's the output I get:

```
13:29:01.884487 *   Trying 104.18.47.34... 
13:29:02.382339 * After 498ms connect time, move on! 
13:29:02.382512 * connect to 104.18.47.34 port 80 failed: Connection timed out 
13:29:02.382595 *   Trying 104.18.46.34... 
13:29:02.631165 * After 248ms connect time, move on! 
13:29:02.631287 * connect to 104.18.46.34 port 80 failed: Connection timed out 
13:29:02.631369 * Failed to connect to www.example.org port 80: Connection timed out
13:29:02.631423 * Closing connection 0
```

Any idea what is wrong...

**Comment by jay** [comment] 2020-02-14 05:33
What's your `curl -V`? Try the [latest curl](https://curl.haxx.se/download.html). `--retry-max-time 15` is going to limit it to 15 seconds so remove that and you should see 15 retries. Also that's a very short connect time, I can't imagine it would be good for much.

**Comment by googled** [comment] 2020-02-14 05:39
curl 7.58.0

As you can see the retries in the output were all made within the first second. The problem is not with the max time parameter as it is never reached. Also, I also need this parameter as I don't want it to run for longer than 15 seconds.

**Comment by jay** [comment] 2020-02-14 08:07
Setting a time limit on retry takes precedence over how many times it will retry.

> As you can see the retries in the output were all made within the first second.

I can't reproduce this. I tried to simulate it by putting an entry for www.example.com in /etc/hosts and then setting the vm network adapter to 100% packet loss and it takes the full 15 seconds.

<details><summary>click to expand full output</summary>

~~~
owner@ubuntu1604-x64-vm:~/curl$ src/curl --ipv4 --connect-timeout 1 --retry 15 --retry-delay 2 --retry-max-time 15 --no-keepalive --no-tcp-nodelay -L --silent 'http://www.example.org' -v --trace-time
02:54:40.051767 * STATE: INIT => CONNECT handle 0x62a000000208; line 1392 (connection #-5000)
02:54:40.051958 * Rebuilt URL to: http://www.example.org/
02:54:40.052094 * Added connection 0. The cache now contains 1 members
02:54:40.052278 * STATE: CONNECT => WAITRESOLVE handle 0x62a000000208; line 1428 (connection #0)
02:54:40.057383 *   Trying 104.18.46.34...
02:54:40.057605 * STATE: WAITRESOLVE => WAITCONNECT handle 0x62a000000208; line 1509 (connection #0)
02:54:41.053214 * Connection timed out after 1001 milliseconds
02:54:41.053289 * multi_done
02:54:41.053327 * stopped the pause stream!
02:54:41.053493 * Closing connection 0
02:54:41.053548 * The cache now contains 0 members
02:54:43.056369 * STATE: INIT => CONNECT handle 0x62a000000208; line 1392 (connection #-5000)
02:54:43.056481 * Rebuilt URL to: http://www.example.org/
02:54:43.056541 * Added connection 1. The cache now contains 1 members
02:54:43.056573 * Hostname www.example.org was found in DNS cache
02:54:43.056621 *   Trying 104.18.46.34...
02:54:43.056754 * STATE: CONNECT => WAITCONNECT handle 0x62a000000208; line 1444 (connection #1)
02:54:44.056627 * Connection timed out after 1000 milliseconds
02:54:44.056691 * multi_done
02:54:44.056718 * stopped the pause stream!
02:54:44.056748 * Closing connection 1
02:54:44.056786 * The cache now contains 0 members
02:54:46.058624 * STATE: INIT => CONNECT handle 0x62a000000208; line 1392 (connection #-5000)
02:54:46.058739 * Rebuilt URL to: http://www.example.org/
02:54:46.058792 * Added connection 2. The cache now contains 1 members
02:54:46.058869 * Hostname www.example.org was found in DNS cache
02:54:46.058932 *   Trying 104.18.46.34...
02:54:46.059034 * STATE: CONNECT => WAITCONNECT handle 0x62a000000208; line 1444 (connection #2)
02:54:47.060647 * Connection timed out after 1001 milliseconds
02:54:47.060712 * multi_done
02:54:47.060739 * stopped the pause stream!
02:54:47.060832 * Closing connection 2
02:54:47.060862 * The cache now contains 0 members
02:54:49.062833 * STATE: INIT => CONNECT handle 0x62a000000208; line 1392 (connection #-5000)
02:54:49.062932 * Rebuilt URL to: http://www.example.org/
02:54:49.062995 * Added connection 3. The cache now contains 1 members
02:54:49.063028 * Hostname www.example.org was found in DNS cache
02:54:49.063066 *   Trying 104.18.46.34...
02:54:49.063168 * STATE: CONNECT => WAITCONNECT handle 0x62a000000208; line 1444 (connection #3)
02:54:50.064585 * Connection timed out after 1001 milliseconds
02:54:50.064651 * multi_done
02:54:50.064681 * stopped the pause stream!
02:54:50.064713 * Closing connection 3
02:54:50.064739 * The cache now contains 0 members
02:54:52.067743 * STATE: INIT => CONNECT handle 0x62a000000208; line 1392 (connection #-5000)
02:54:52.067896 * Rebuilt URL to: http://www.example.org/
02:54:52.068128 * Added connection 4. The cache now contains 1 members
02:54:52.068200 * Hostname www.example.org was found in DNS cache
02:54:52.068278 *   Trying 104.18.46.34...
02:54:52.068451 * STATE: CONNECT => WAITCONNECT handle 0x62a000000208; line 1444 (connection #4)
02:54:53.068972 * Connection timed out after 1001 milliseconds
02:54:53.069035 * multi_done
02:54:53.069062 * stopped the pause stream!
02:54:53.069132 * Closing connection 4
02:54:53.069193 * The cache now contains 0 members
02:54:55.072258 * STATE: INIT => CONNECT handle 0x62a000000208; line 1392 (connection #-5000)
02:54:55.072390 * Rebuilt URL to: http://www.example.org/
02:54:55.072482 * Added connection 5. The cache now contains 1 members
02:54:55.072591 * Hostname www.example.org was found in DNS cache
02:54:55.072650 *   Trying 104.18.46.34...
02:54:55.072758 * STATE: CONNECT => WAITCONNECT handle 0x62a000000208; line 1444 (connection #5)
02:54:56.073075 * Connection timed out after 1000 milliseconds
02:54:56.073143 * multi_done
02:54:56.073171 * stopped the pause stream!
02:54:56.073203 * Closing connection 5
02:54:56.073235 * The cache now contains 0 members
~~~

</details>

curl-7_58_0:
~~~
curl 7.58.0-DEV (x86_64-pc-linux-gnu) libcurl/7.58.0-DEV OpenSSL/1.1.1d zlib/1.2.8 nghttp2/1.40.0 librtmp/2.3
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS Debug TrackMemory IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy 
~~~


Try the latest curl.

**Comment by bagder** [comment] 2020-02-14 08:59
"Connection timed out" wasn't handled as a transient error correctly until 7.67.0 (see #4461 and commit 490effc193f548d02f7cc9b05) so this is basically fixed already if you follow @jay's advice and upgrade.

**Comment by bagder** [comment] 2020-02-16 16:57
We believe this is already fixed.

**Closed by bagder** 2020-02-16 16:57 UTC
Labels: cmdline tool
