### ISSUE TITLE
curl: (23) Failed writing body (0 != 426) when trying to dowload file with cyrilic filename

### ISSUE THREAD

**Issue by Q3CPMA** [curl/curl#2030] opened 2017-10-29 17:19 UTC
### I did this
`curl -sSOLC- https://upload.wikimedia.org/wikipedia/commons/9/9e/%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%90%D0%BD%D0%B4%D1%80%D0%B5%D0%B5%D0%B2%D0%B8%D1%87_%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2_-_%D0%AF%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%A5%D1%80%D0%B8%D1%81%D1%82%D0%B0_%D0%BD%D0%B0%D1%80%D0%BE%D0%B4%D1%83_(%D0%AF%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%9C%D0%B5%D1%81%D1%81%D0%B8%D0%B8)_-_Google_Art_Project.jpg` and I get `curl: (23) Failed writing body (0 != 426)`
If I use `-o out.jpg` instead of `-O`, it works.
### I expected the following
The file is downloaded.
### curl/libcurl version
```
curl 7.56.1 (x86_64-pc-linux-gnu) libcurl/7.56.1 OpenSSL/1.0.2l zlib/1.2.11
Release-Date: 2017-10-23
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM SSL libz TLS-SRP UnixSockets HTTPS-proxy
```
### operating system
Gentoo GNU/Linux

**Comment by monnerat** [comment] 2017-10-30 02:27
curl doesn't unescape the file base path when extracting the file name from the URL for the `-O` option. Is it intentional or a bug ?

The escaped file name is 372-byte long, unescaping it would result in a 148-byte string.

372 bytes is more than the maximum allowed by the system of 255. Thus the file cannot be created and this is the reason for failure.

**Comment by Q3CPMA** [comment] 2017-10-30 08:03
Ah yeah, I forgot about this. It's definitely not  bug in this case. Fortunately, I wrote a little tool to urldecode, so I'll just have to wire curl to automatically do `curl "$url" -o "$(urldecode "$url")"`.

**Comment by monnerat** [comment] 2017-10-30 13:52
@bagder: need your opinion about the following question:

> curl doesn't unescape the file base path when extracting the file name from the URL for the -O option. Is it intentional or a bug ?

**Comment by bagder** [comment] 2017-10-30 14:19
It is very much intentional - and documented. If we should ever try to decode that, we would need a new option to make that happen and it will be complicated due to charsets etc.

**Comment by monnerat** [comment] 2017-10-30 14:21
@bagder: Thanks for your reply. Q3CPMA has a workaround, so the problem is over.

Closing.

**Closed by monnerat** 2017-10-30 14:21 UTC
