### ISSUE TITLE
Reuse of FTP socket timing out in multi

### ISSUE THREAD

**Issue by damonearp** [curl/curl#3043] opened 2018-09-24 18:58 UTC
### I did this

We've been using libcurl's multi interface with libevent to provide an FTP and HTTP client for our project. The other day Alpine Linux 3.7 updated their curl package to 7.61.1 from 7.61.0 and one of our tests started failing. Today I built and statically linked 7.61.1 into our program on CentOS 7 and the test is now failing in the same way. The issue appears to be with reuse of an FTP socket. 

### I expected the following

The FTP connection to be reused and the file to be downloaded. Instead our 5 second connection timeout happens.

### curl/libcurl version

7.61.1

### operating system

Linux (Alpine 3.7 musl & CentOS 7 glibc)

### CURLOPT_VERBOSE output

How we are setting up the easy handles:
  
  * Both have `CURLOPT_URL`  set to `ftp://admin:admin@vsftpd/README`. 
  * The first sets `CURLOPT_NOBODY` to stat the file. 
  * The second sets `CURLOPT_HTTPGET` regardless of what url is passed to it
  * All requests are enabling the cookie engine with `CURLOPT_COOKIEFILE` set to `""` regardless of protocol. Just disabled this and it's still failing if cookie engine is never initialized.
  * `CURLOPT_FILETIME` is enabled on all requests 
  * Finally, none of our HTTP tests are experiencing a problem reusing the connection

Output from the request when stat was called
```
STATE: INIT => CONNECT handle 0x7f7c44012458; line 1428 (connection #-5000)
Added connection 0. The cache now contains 1 members
STATE: CONNECT => WAITRESOLVE handle 0x7f7c44012458; line 1464 (connection #0)
  Trying 172.17.0.2...
TCP_NODELAY set
STATE: WAITRESOLVE => WAITCONNECT handle 0x7f7c44012458; line 1545 (connection #0)
Connected to vsftpd (172.17.0.2) port 21 (#0)
STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x7f7c44012458; line 1599 (connection #0)
Marked for [keep alive]: FTP default
FTP 0x7f7c70001de0 (line 3117) state change from STOP to WAIT220
STATE: SENDPROTOCONNECT => PROTOCONNECT handle 0x7f7c44012458; line 1613 (connection #0)
220 (vsFTPd 3.0.2)
USER admin
FTP 0x7f7c70001de0 (line 803) state change from WAIT220 to USER
331 Please specify the password.
PASS admin
FTP 0x7f7c70001de0 (line 2545) state change from USER to PASS
230 Login successful.
PWD
FTP 0x7f7c70001de0 (line 815) state change from PASS to PWD
257 "/"
Entry path is '/'
FTP 0x7f7c70001de0 (line 2869) state change from PWD to STOP
protocol connect phase DONE
STATE: PROTOCONNECT => WAITDO handle 0x7f7c44012458; line 1634 (connection #0)
STATE: WAITDO => DO handle 0x7f7c44012458; line 1649 (connection #0)
DO phase starts
MDTM README
FTP 0x7f7c70001de0 (line 1574) state change from STOP to MDTM
ftp_perform ends with SECONDARY: 0
STATE: DO => DOING handle 0x7f7c44012458; line 1683 (connection #0)
213 20180924173931
TYPE I
FTP 0x7f7c70001de0 (line 3442) state change from MDTM to TYPE
200 Switching to Binary mode.
SIZE README
FTP 0x7f7c70001de0 (line 1435) state change from TYPE to SIZE
213 4096
REST 0
FTP 0x7f7c70001de0 (line 1415) state change from SIZE to REST
350 Restart position accepted (0).
FTP 0x7f7c70001de0 (line 1369) state change from REST to RETR_PREQUOTE
FTP 0x7f7c70001de0 (line 1749) state change from RETR_PREQUOTE to STOP
DO phase is complete2
STATE: DOING => DO_DONE handle 0x7f7c44012458; line 1770 (connection #0)
STATE: DO_DONE => DONE handle 0x7f7c44012458; line 1829 (connection #0)
multi_done
Remembering we are in dir ""
Connection #0 to host vsftpd left intact
Expire cleared
```

Output from the read fs call which tries to download the file 
```
STATE: INIT => CONNECT handle 0x7f7c580081f8; line 1428 (connection #-5000)
Found bundle for host vsftpd: 0x7f7c700064d8 [serially]
Re-using existing connection! (#0) with host vsftpd
Connected to vsftpd (172.17.0.2) port 21 (#0)
STATE: CONNECT => WAITDO handle 0x7f7c580081f8; line 1473 (connection #0)
Operation timed out after 5005 milliseconds with 0 out of 0 bytes received
multi_done
Marked for [closure]: FTP ended with bad error code
Closing connection 0
The cache now contains 0 members
```

Our multi/libevent code is working with curl 7.29.0 (centos7), 7.38.0 (debian 8), 7.52.1 (debian 9) and 7.61.0 (Alpine 3.7 before they updated). Thanks.

**Comment by damonearp** [comment] 2018-09-24 21:36
I spent some more time today disabling features to see if I could narrow this down more. Looks like enabling pipelining and multiplexing on the multi handle causes issues with FTP reuse. If I comment out the code below all our tests succeed with 7.61.1.

```c
#if LIBCURL_VERSION_MAJOR >= 7 && LIBCURL_VERSION_MINOR >= 43
    curl_multi_setopt(inst->multi, CURLMOPT_PIPELINING, CURLPIPE_HTTP1 | CURLPIPE_MULTIPLEX);
#else
    curl_multi_setopt(inst->multi, CURLMOPT_PIPELINING, 1l);
#endif
```

**Comment by bagder** [comment] 2018-09-24 21:41
Yes, I think your right. There's a clue in the fact that in the second transfer, the problematic one, it goes into the `WAITDO` state, which it shouldn't do for FTP. The bug happens at this place in the code:

https://github.com/curl/curl/blob/16fefeee1e4d6d8534f97f8c133b2e509cca4d9e/lib/multi.c#L1470

And the function it calls, `Curl_pipeline_wanted` simply returns true if the pipeline bit was set... I'll work up a PR to fix. Stand by!

**Comment by bagder** [comment] 2018-09-24 21:51
It could be noted that in git master we've disabled pipelining support with the commit f7208df7d9d5cd5e15e2d8 and from my reading of the logic after that patch, I don't think your error case will trigger. Any chance you can confirm that?

If so, I don't think I need to particularly work on a fix since pipelining support will eventually get dropped anyway.

**Comment by damonearp** [comment] 2018-09-24 23:35
Just tested branch master, explicitly enabling both pipelining and multiplexing. Everything worked, thank you. I'll let you close.

**Comment by bagder** [comment] 2018-09-25 12:28
Thanks for confirming that @damonearp. I'll close this now since the bug can no longer reproduce - with a mental note that if we would revert the pipeline-deprecation code this bug would be brought back!

**Closed by bagder** 2018-09-25 12:28 UTC
Labels: FTP
