### ISSUE TITLE
Curl incorrectly logs localhost to IP, but connects to the correct IP address

### ISSUE THREAD

**Issue by michael-o** [curl/curl#8491] opened 2022-02-21 12:19 UTC
### I did this
Connect via HTTP to a server running on localhost. The local interface is a cloned from the host beneath, curl itself runs in a jail along with the web server:
```
# ifconfig lo1
lo1: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet 127.0.1.2 netmask 0xffffffff
        groups: lo
# grep localhost /etc/hosts
::1             localhost
127.0.1.2               localhost
# grep hosts /etc/nsswitch.conf
hosts: files dns
```

curl output:
```
# curl http://localhost:8081/ --verbose -I
* Uses proxy env variable NO_PROXY == 'localhost .siemens.net .siemens.com .siemens.de'
*   Trying 127.0.0.1:8081...
* Connected to localhost (127.0.1.2) port 8081 (#0)
> HEAD / HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.80.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404
HTTP/1.1 404
< Content-Type: text/html;charset=utf-8
Content-Type: text/html;charset=utf-8
< Content-Language: en
Content-Language: en
< Transfer-Encoding: chunked
Transfer-Encoding: chunked
< Date: Mon, 21 Feb 2022 12:15:23 GMT
Date: Mon, 21 Feb 2022 12:15:23 GMT

<
* Connection #0 to host localhost left intact
```

As you can see ` Trying 127.0.0.1:8081...` connects likely directly to DNS to resolve localhost because:
```
# host localhost
localhost.ad001.siemens.net has address 127.0.0.1
localhost.ad001.siemens.net has IPv6 address ::1
```
This entry has been added intentionally by AD admins.

### I expected the following
I'd expect curl to use system functions to resolve hostname to IP even if it is informative:
```
# python3
Python 3.7.12 (default, Jan  4 2022, 17:23:05)
[Clang 10.0.1 (git@github.com:llvm/llvm-project.git llvmorg-10.0.1-0-gef32c611a on freebsd12
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.gethostbyname("localhost")
'127.0.1.2'
>>>
```

### curl/libcurl version
curl --version
curl 7.80.0 (amd64-portbld-freebsd12.2) libcurl/7.80.0 OpenSSL/1.1.1h zlib/1.2.11 nghttp2/1.46.0
Release-Date: 2021-11-10
Protocols: file http https
Features: AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz SPNEGO SSL UnixSockets

### operating system
FreeBSD deblndw011x1j.ad001.siemens.net 12.3-STABLE FreeBSD 12.3-STABLE GENERIC  amd64

**Comment by bagder** [comment] 2022-02-21 13:01
localhost means 127.0.0.1 and ::1 these days, no resolve necessary: https://daniel.haxx.se/blog/2021/05/31/curl-localhost-as-a-local-host/

This is intentional

**Comment by bagder** [comment] 2022-02-21 16:24
it is an interesting and somewhat confusing output, but in this case the `127.0.1.2` address it shows is the one extracted from the used socket which thus isn't the same IP (`127.0.0.1`) that was used to connect to.

**Comment by michael-o** [comment] 2022-02-21 18:29
> it is an interesting and somewhat confusing output, but in this case the `127.0.1.2` address it shows is the one extracted from the used socket which thus isn't the same IP (`127.0.0.1`) that was used to connect to.

...and that's exactly what I reported. Confusing output for the user at the end. Curl isn't a browser and it isn't meant for the average Joe.

**Comment by bagder** [comment] 2022-02-21 21:37
> Curl isn't a browser and it isn't meant for the average Joe.

I don't understand what this means. What are you suggesting is wrong or should be fixed here?

**Comment by michael-o** [comment] 2022-02-21 21:40
> > Curl isn't a browser and it isn't meant for the average Joe.
> 
> I don't understand what this means. What are you suggesting is wrong or should be fixed here?

In your blog post you almost only reference browsers, but curl isn't a browser. A browser is a layman's tool for a very narrow usecase while curl is a specialist tool for a wide range of usecases. It does not have to be idiotproof, but consistent. From my PoV of view the output and behavior are inconsistent.

**Comment by bagder** [comment] 2022-02-21 21:43
> the output and behavior are inconsistent.

IMHO, that's because your network setup is "funny", not because of curl.

**Comment by dfandrich** [comment] 2022-02-21 21:46
There are two addresses involved in the transfer. Which of them do you feel is
wrong?

**Comment by michael-o** [comment] 2022-02-21 21:48
> There are two addresses involved in the transfer. Which of them do you feel is wrong?

127.0.0.1

**Comment by michael-o** [comment] 2022-02-21 21:53
> > the output and behavior are inconsistent.
> 
> IMHO, that's because your network setup is "funny", not because of curl.

No, all `127.0.0.0/8` is loopback. A cloned loopback is perfectly normal to gain more control over the host. Looking at 1a0ebf6632f889eedd42e03db9c337e7f029cc21 that is a lot of code just to hard code `localhost` to 127.0.0.1.

**Comment by bagder** [comment] 2022-02-21 21:56
localhost getting fixed to 127.0.0.1 is not my idea, we adapt to the world around us. As you can see, there are specs saying so and other clients already doing it. Besides, even in this report curl seems to be doing the right thing and you're mostly upset about what address it seems to show in verbose output?

**Comment by bagder** [comment] 2022-02-21 21:58
Making localhost resolve to these two addresses is not a bug. If that's what you're reporting, then I think this case can be closed.

**Comment by michael-o** [comment] 2022-02-21 22:06
> Making localhost resolve to these two addresses is not a bug. If that's what you're reporting, then I think this case can be closed.

But making this assumption is wrong. localhost is not guaranteed to map to 127.0.0.1, though I agree with ::1 becuase IPv6 does not have anything else. I have seen tests in other software which had 127.0.0.1 hardcoded instead of localhost. The tests failed. For obvious reasons. If you want to add some kind of protection, I'd just expect a test for the resolved IP against the valid range. If the IPv4 is out of range then this A record is invalid.

**Comment by bagder** [comment] 2022-02-22 17:10
Yet, the command line that started this issue **worked** so we're not even talking about a failure. curl has had this behavior since version 7.78.0 and while a few others expressed concerns like your before this change landed, we have received zero bug reports on this. That's even fewer than I had anticipated.

**Comment by jay** [comment] 2022-02-23 07:44
Ref: https://github.com/curl/curl/issues/7160

**Closed** 2022-02-24 08:24 UTC
Labels: not-a-bug, name lookup
