### ISSUE TITLE
--max-time doesn't control the DNS resolving time 

### ISSUE THREAD

**Issue by leonfancy** [curl/curl#4139] opened 2019-07-22 16:07 UTC
### I did this
I build the latest version **7.65.3** curl  in Ubuntu 18.04.

And edit file `/etc/resolv.conf` to change the `nameserver` to a wrong server address to simulate DNS resolving timeout.

```
nameserver 8.8.8.21
```

After that, I run the below command:
```
$ time ./curl --max-time 2 www.google.com
curl: (28) Resolving timed out after 2000 milliseconds

real    0m20.028s
user    0m0.017s
sys     0m0.002s
```

The curl error information display timeout after 2000ms, but actually it takes 20 seconds. It always take 20 seconds no matter what the `--max-time`  is.

I also tested with curl **7.58.0**, it looks like the `--max-time` is working, but not accurate.

```
time curl --max-time 2 www.google.com
curl: (28) Resolving timed out after 2512 milliseconds

real    0m2.521s
user    0m0.000s
sys     0m0.010s
```

I found the actual time is always 0.5 seconds bigger than the `--max-time` option value when `--max-time` is set to a value bigger than 1 seconds.
```
time curl --max-time 3 www.google.com
curl: (28) Resolving timed out after 3512 milliseconds

real    0m3.521s
user    0m0.009s
sys     0m0.000s
```  
```
time curl --max-time 5 www.google.com
curl: (28) Resolving timed out after 5514 milliseconds

real    0m5.524s
user    0m0.005s
sys     0m0.005s

```
The actual time is always about 1.5 seconds when `--max-time` is set to a value between 0.5 and 1 seconds.
```
time curl --max-time 0.6 www.google.com
curl: (28) Resolving timed out after 1511 milliseconds

real    0m1.520s
user    0m0.001s
sys     0m0.010s
```
```
time curl --max-time 0.7 www.google.com
curl: (28) Resolving timed out after 1511 milliseconds

real    0m1.520s
user    0m0.011s
sys     0m0.000s
```
The actual time is almost the same as `--max-time` value when it is set to a value less than 0.5.
```
time curl --max-time 0.2 www.google.com
curl: (28) Resolving timed out after 253 milliseconds

real    0m0.263s
user    0m0.006s
sys     0m0.005s
```
```
time curl --max-time 0.1 www.google.com
curl: (28) Resolving timed out after 124 milliseconds

real    0m0.134s
user    0m0.010s
sys     0m0.001s
```
### I expected the following
Curl should time out exactlly after ` --max-time` when the DNS resovling is not working correctly.

### curl/libcurl version

```
curl 7.65.3 (x86_64-pc-linux-gnu) libcurl/7.65.3
Release-Date: 2019-07-19
Protocols: dict file ftp gopher http imap pop3 rtsp smtp telnet tftp
Features: AsynchDNS IPv6 Largefile UnixSockets
```

```
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

### operating system
Ubuntu 18.04.

**Comment by bagder** [comment] 2019-07-22 21:40
Duplicate of #297

**Closed** 2019-07-25 21:41 UTC
