### ISSUE TITLE
Cannot resolve named proxy host when configured with async DNS

### ISSUE THREAD

**Issue by martenjj** [curl/curl#12955] opened 2024-02-18 16:13 UTC
### I did this

The system proxy variables are set to include a named proxy host:
```
 $ env|grep proxy
no_proxy=localhost
https_proxy=http://proxyhost:8118
http_proxy=http://proxyhost:8118
$ 
```
The host name is resolvable and reachable:
```
$ ping proxyhost
PING proxyhost (192.168.6.13) 56(84) bytes of data.
64 bytes from proxyhost (192.168.6.13): icmp_seq=1 ttl=64 time=0.177 ms
64 bytes from proxyhost (192.168.6.13): icmp_seq=2 ttl=64 time=0.171 ms
64 bytes from proxyhost (192.168.6.13): icmp_seq=3 ttl=64 time=0.191 ms
^C
--- proxyhost ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2070ms
rtt min/avg/max/mdev = 0.171/0.179/0.191/0.008 ms
$ 
```
However, attempting to fetch content through the proxy fails as follows.  The destination IP is an AirPrint scanner on the local network, the content is not interesting.
```
$ curl -v http://192.168.6.73:80/eSCL/ScannerStatus >/dev/null
* Uses proxy env variable no_proxy == 'localhost'
* Uses proxy env variable http_proxy == 'http://proxyhost:8118'
* Could not resolve proxy: proxyhost
* Couldn't resolve proxy 'proxyhost'
* Closing connection
curl: (5) Could not resolve proxy: proxyhost
$
```

### I expected the following

The content to be fetched.

Specifying the proxy as a literal IP address works:
```
$ http_proxy=http://192.168.6.13:8118 curl -v http://192.168.6.73:80/eSCL/ScannerStatus >/dev/null
* Uses proxy env variable no_proxy == 'localhost'
* Uses proxy env variable http_proxy == 'http://192.168.6.13:8118'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 192.168.6.13:8118...
* Connected to 192.168.6.13 (192.168.6.13) port 8118
> GET http://192.168.6.73/eSCL/ScannerStatus HTTP/1.1
> Host: 192.168.6.73
> User-Agent: curl/8.4.0
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 OK
< Cache-Control: no-store
< Accept-Encoding: identity
< X-Frame-Options: DENY
< Content-Length: 6582
< Content-Type: text/xml
< Connection: close
< Pragma: no-cache
< Proxy-Connection: keep-alive
< 
{ [4344 bytes data]
100  6582  100  6582    0     0   137k      0 --:--:-- --:--:-- --:--:--  139k
* Closing connection
$ 
```
Also, with curl configured to not use async DNS also works:
```
$ env|grep proxy
no_proxy=localhost
https_proxy=http://proxyhost:8118
http_proxy=http://proxyhost:8118
$ 

$ curl -v http://192.168.6.73:80/eSCL/ScannerStatus \>/dev/null
* Uses proxy env variable no_proxy == 'localhost'
* Uses proxy env variable http_proxy == 'http://proxyhost:8118'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 192.168.6.13:8118...
* Connected to proxyhost (192.168.6.13) port 8118  
> GET http://192.168.6.73/eSCL/ScannerStatus HTTP/1.1
> Host: 192.168.6.73  
> User-Agent: curl/8.4.0  
> Accept: */*  
> Proxy-Connection: Keep-Alive  
> 
< HTTP/1.1 200 OK
< Cache-Control: no-store
< Accept-Encoding: identity
< X-Frame-Options: DENY
< Content-Length: 6582
< Content-Type: text/xml
< Connection: close
< Pragma: no-cache
< Proxy-Connection: keep-alive
< 
{ [4344 bytes data]
100  6582  100  6582    0     0   134k      0 --:--:-- --:--:-- --:--:--  136k
\* Closing connection
$ 
```

### curl/libcurl version

$ curl -V
curl 8.4.0 (x86_64-pc-linux-gnu) libcurl/8.4.0 OpenSSL/3.0.10 zlib/1.2.13 nghttp2/1.51.0
Release-Date: 2023-10-11
Protocols: dict file ftp ftps http https imap imaps mqtt pop3 pop3s rtsp smtp smtps tftp
Features: alt-svc AsynchDNS HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM SSL threadsafe TLS-SRP UnixSockets
$ 

This report is the same whether curl is configured to use async DNS or not.  The configure options actually used are:

With:

configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --datarootdir=/usr/share --disable-dependency-tracking --disable-silent-rules --disable-static --docdir=/usr/share/doc/curl-8.4.0 --htmldir=/usr/share/doc/curl-8.4.0/html --with-sysroot=/ --libdir=/usr/lib64 --without-ca-fallback --with-ca-bundle=/etc/ssl/certs/ca-certificates.crt --without-gnutls --without-mbedtls --without-rustls --with-ssl --with-ca-path=/etc/ssl/certs --with-default-ssl-backend=openssl --enable-alt-svc --enable-basic-auth --enable-bearer-auth --enable-digest-auth --enable-kerberos-auth --enable-negotiate-auth --enable-aws --enable-dict --disable-ech --enable-file --enable-ftp --disable-gopher --enable-hsts --enable-http --enable-imap --disable-ldap --disable-ldaps --enable-ntlm --disable-ntlm-wb --enable-pop3 --enable-rt --enable-rtsp --disable-smb --without-libssh2 --enable-smtp --disable-telnet --enable-tftp --enable-tls-srp --enable-ares --enable-cookies --enable-dateparse --enable-dnsshuffle --enable-doh --enable-symbol-hiding --enable-http-auth --enable-ipv6 --enable-largefile --enable-manual --enable-mime --enable-netrc --enable-progress-meter --enable-proxy --enable-socketpair --disable-sspi --disable-static --enable-pthreads --enable-threaded-resolver --disable-versioned-symbols --without-amissl --without-bearssl --without-brotli --with-fish-functions-dir=/usr/share/fish/vendor_completions.d --with-nghttp2 --without-hyper --without-libidn2 --without-gssapi --without-libgsasl --without-libpsl --without-msh3 --without-nghttp3 --without-ngtcp2 --without-quiche --without-librtmp --without-schannel --without-secure-transport --without-test-caddy --without-test-httpd --without-test-nghttpx --disable-websockets --without-winidn --without-wolfssl --with-zlib --without-zstd --with-zsh-functions-dir=/usr/share/zsh/site-functions

Without:

configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --datarootdir=/usr/share --disable-dependency-tracking --disable-silent-rules --disable-static --docdir=/usr/share/doc/curl-8.4.0 --htmldir=/usr/share/doc/curl-8.4.0/html --with-sysroot=/ --libdir=/usr/lib64 --without-ca-fallback --with-ca-bundle=/etc/ssl/certs/ca-certificates.crt --without-gnutls --without-mbedtls --without-rustls --with-ssl --with-ca-path=/etc/ssl/certs --with-default-ssl-backend=openssl --enable-alt-svc --enable-basic-auth --enable-bearer-auth --enable-digest-auth --enable-kerberos-auth --enable-negotiate-auth --enable-aws --enable-dict --disable-ech --enable-file --enable-ftp --disable-gopher --enable-hsts --enable-http --enable-imap --disable-ldap --disable-ldaps --enable-ntlm --disable-ntlm-wb --enable-pop3 --enable-rt --enable-rtsp --disable-smb --without-libssh2 --enable-smtp --disable-telnet --enable-tftp --enable-tls-srp --disable-ares --enable-cookies --enable-dateparse --enable-dnsshuffle --enable-doh --enable-symbol-hiding --enable-http-auth --enable-ipv6 --enable-largefile --enable-manual --enable-mime --enable-netrc --enable-progress-meter --enable-proxy --enable-socketpair --disable-sspi --disable-static --enable-pthreads --enable-threaded-resolver --disable-versioned-symbols --without-amissl --without-bearssl --without-brotli --with-fish-functions-dir=/usr/share/fish/vendor_completions.d --with-nghttp2 --without-hyper --without-libidn2 --without-gssapi --without-libgsasl --without-libpsl --without-msh3 --without-nghttp3 --without-ngtcp2 --without-quiche --without-librtmp --without-schannel --without-secure-transport --without-test-caddy --without-test-httpd --without-test-nghttpx --disable-websockets --without-winidn --without-wolfssl --with-zlib --without-zstd --with-zsh-functions-dir=/usr/share/zsh/site-functions

### operating system

Gentoo Linux 64-bit

**Comment by jay** [comment] 2024-02-18 18:54
This is most likely a problem with your resolver configuration and not with curl. curl uses getaddrinfo for IPv6 builds.

Try a program that also uses getaddrinfo like wget. Try the latest curl 8.6.0 with `curl -4 ...` for IPv4-only lookup (PF_INET) and `curl -6 ...` for IPv6-only lookup (PF_INET6).

**Comment by martenjj** [comment] 2024-02-18 19:53
Wget seems to work correctly through the proxy.  Although Gentoo always builds curl with "--enable-ipv6", the system is not configured for any IPv6 interfaces or name resolution.
```
$ curl -V
curl 8.6.0 (x86_64-pc-linux-gnu) libcurl/8.6.0 OpenSSL/3.0.10 zlib/1.2.13 c-ares/1.19.1 libpsl/0.21.2 nghttp2/1.51.0
Release-Date: 2024-01-31
Protocols: dict file ftp ftps http https imap imaps ipfs ipns mqtt pop3 pop3s rtsp smtp smtps tftp
Features: alt-svc AsynchDNS HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM PSL SSL threadsafe TLS-SRP UnixSockets
$ 

$ curl -4 -v http://192.168.6.73:80/eSCL/ScannerStatus >/dev/null
* Uses proxy env variable no_proxy == 'localhost'
* Uses proxy env variable http_proxy == 'http://proxyhost:8118'
* Could not resolve proxy: proxyhost
* Couldn't resolve proxy 'proxyhost'
* Closing connection
curl: (5) Could not resolve proxy: proxyhost
$ 

$ curl -6 -v http://192.168.6.73:80/eSCL/ScannerStatus >/dev/null
* Uses proxy env variable no_proxy == 'localhost'
* Uses proxy env variable http_proxy == 'http://proxyhost:8118'
* Could not resolve proxy: proxyhost
* Couldn't resolve proxy 'proxyhost'
* Closing connection
curl: (5) Could not resolve proxy: proxyhost
$

$ wget -O/dev/null http://192.168.6.73:80/eSCL/ScannerStatus
--2024-02-18 19:45:36--  http://192.168.6.73/eSCL/ScannerStatus
Resolving proxyhost... 192.168.6.13
Connecting to proxyhost|192.168.6.13|:8118... connected.
Proxy request sent, awaiting response... 200 OK
Length: 6582 (6.4K) [text/xml]
Saving to: ‘/dev/null’
/dev/null               100%[============================>]   6.43K  --.-KB/s    in 0s      
2024-02-18 19:45:36 (804 MB/s) - ‘/dev/null’ saved [6582/6582]
$ 
```

**Comment by bagder** [comment] 2024-02-18 21:42
Both the with and without builds use `--enable-threaded-resolver` so why is the without build not using asynch?

**Comment by bagder** [comment] 2024-02-18 22:26
Also:

This is widely used functionality without anyone else reporting problems. The default build for users everywhere uses the asynch (threaded) resolver. I cannot reproduce any problems.

**Comment by jay** [comment] 2024-02-18 23:55
Please try [getaddrinfo.c](https://gist.github.com/jay/0fe0db29305184d63b7914acb3eae820) which retrieves addresses the same way libcurl does.

**Comment by martenjj** [comment] 2024-02-27 08:16
Using the supplied test program seems to work correctly.  System is not configured with any IPv6 address or interfaces.

$ cc -o getaddrinfo getaddrinfo.c 
$
$ ./getaddrinfo -4 proxyhost
192.168.6.13
$ ./getaddrinfo -6 proxyhost
getaddrinfo: (-2) Name or service not known
$ ./getaddrinfo  proxyhost
192.168.6.13
$ 

Not sure whether it is using or whether I need to use any special config or link options for the async DNS resolver, though.

**Comment by bagder** [comment] 2024-03-03 21:24
How is the `proxyhost` name being resolved?

We need more information to try to reproduce, as otherwise we cannot act on this.

**Comment by bagder** [comment] 2024-03-07 21:54
We need more information or we will be forced to close this issue since there is nothing for us to act on here.

**Comment by bagder** [comment] 2024-03-22 23:32
No response

**Closed by bagder** 2024-03-22 23:32 UTC
Labels: needs-info, name lookup
