### ISSUE TITLE
Terminal colors not reset to its original properties after curl bold output

### ISSUE THREAD

**Issue by stefanos82** [curl/curl#2930] opened 2018-09-02 15:15 UTC
Specs:
```
OS: GNU / Linux Debian testing 64-bit
curl version: 7.61.0
```
I run `curl -vI https://google.com` and got the following output:
![image](https://user-images.githubusercontent.com/1777466/44957454-88250b00-aedb-11e8-8e15-bf8123db63b2.png)
To reset it, I have to run either `echo -e '\033[m0'` or `printf "%b\n" "\033m0"`.

Should I consider this a bug?

**Comment by bagder** [comment] 2018-09-02 16:34
Duplicate of #2736

**Closed by bagder** 2018-09-02 16:34 UTC
