### ISSUE TITLE
curl proxy-anyauth issue

### ISSUE THREAD

**Issue by devzero2000** [curl/curl#4586] opened 2019-11-11 15:09 UTC
### I did this
curl -U "user":"password" -x http://"proxy":8080 http://google.com --proxy-anyauth --trace-ascii /tmp/traceascii

### I expected the following
I expected the google home page instead i get http 407 from the proxy. The proxy support Negotiate, NTLM and Basic Auth. If i use Basic Auth ( with --proxy-basic) or NTLM (with --proxy-ntlm) the command worked good.

This the content of the /tmp/traceascii. From what I can understand curl finds an authentication error with the Negotiate authentication and does not go ahead with other forms of authentication. Is this the behavior expected by proxy-anyauth or is it a bug?

== Info: About to connect() to proxy <proxy> port 8080 (#0)
== Info:   Trying xx.xx.xx.xx...
== Info: Connected to <proxy> (xx.xx.xx.xx) port 8080 (#0)
=> Send header, 121 bytes (0x79)
0000: GET http://google.com/ HTTP/1.1
0021: User-Agent: curl/7.29.0
003a: Host: google.com
004c: Accept: */*
0059: Proxy-Connection: Keep-Alive
0077:
== Info: HTTP 1.0, assume close after body
<= Recv header, 44 bytes (0x2c)
0000: HTTP/1.0 407 Proxy Authentication Required
<= Recv header, 15 bytes (0xf)
0000: Server: squid
<= Recv header, 19 bytes (0x13)
0000: Mime-Version: 1.0
<= Recv header, 37 bytes (0x25)
0000: Date: Mon, 11 Nov 2019 14:49:28 GMT
<= Recv header, 25 bytes (0x19)
0000: Content-Type: text/html
<= Recv header, 22 bytes (0x16)
0000: Content-Length: 2829
<= Recv header, 42 bytes (0x2a)
0000: X-Squid-Error: ERR_CACHE_ACCESS_DENIED 0
<= Recv header, 31 bytes (0x1f)
0000: Proxy-Authenticate: Negotiate
<= Recv header, 26 bytes (0x1a)
0000: Proxy-Authenticate: NTLM
<= Recv header, 60 bytes (0x3c)
0000: Proxy-Authenticate: Basic realm="Authenticating in "DOMAIN""
<= Recv header, 46 bytes (0x2e)
0000: X-Cache: MISS from <proxy>
<= Recv header, 58 bytes (0x3a)
0000: X-Cache-Lookup: NONE from <proxy>:8080
<= Recv header, 44 bytes (0x2c)
0000: Via: 1.0 <proxy> (squid)
== Info: HTTP/1.0 connection set to keep alive!
<= Recv header, 24 bytes (0x18)
0000: Connection: keep-alive
<= Recv header, 2 bytes (0x2)
0000:
== Info: Ignoring the response-body
<= Recv data, 2829 bytes (0xb0d)
<redacted: proxy answer with an error message>
== Info: Connection #0 to host <proxy> left intact
== Info: Issue another request to this URL: 'http://google.com/'
== Info: Found bundle for host google.com: 0x725930
== Info: Re-using existing connection! (#0) with host <proxy>
== Info: Connected to <proxy> (xx.xx.xx.xx) port 8080 (#0)
=> Send header, 121 bytes (0x79)
0000: GET http://google.com/ HTTP/1.0
0021: User-Agent: curl/7.29.0
003a: Host: google.com
004c: Accept: */*
0059: Proxy-Connection: Keep-Alive
0077:
== Info: HTTP 1.0, assume close after body
<= Recv header, 44 bytes (0x2c)
0000: HTTP/1.0 407 Proxy Authentication Required
<= Recv header, 15 bytes (0xf)
0000: Server: squid
<= Recv header, 19 bytes (0x13)
0000: Mime-Version: 1.0
<= Recv header, 37 bytes (0x25)
0000: Date: Mon, 11 Nov 2019 14:49:28 GMT
<= Recv header, 25 bytes (0x19)
0000: Content-Type: text/html
<= Recv header, 22 bytes (0x16)
0000: Content-Length: 2829
<= Recv header, 42 bytes (0x2a)
0000: X-Squid-Error: ERR_CACHE_ACCESS_DENIED 0
== Info: gss_init_sec_context() failed: : No Kerberos credentials available (default cache: KEYRING:persistent:1000)
<= Recv header, 31 bytes (0x1f)
0000: Proxy-Authenticate: Negotiate
<= Recv header, 26 bytes (0x1a)
0000: Proxy-Authenticate: NTLM
<= Recv header, 60 bytes (0x3c)
0000: Proxy-Authenticate: Basic realm="Authenticating in "DOMAIN""
<= Recv header, 46 bytes (0x2e)
0000: X-Cache: MISS from <proxy>
<= Recv header, 58 bytes (0x3a)
0000: X-Cache-Lookup: NONE from <proxy>:8080
<= Recv header, 44 bytes (0x2c)
0000: Via: 1.0 <proxy> (squid)
== Info: HTTP/1.0 connection set to keep alive!
<= Recv header, 24 bytes (0x18)
0000: Connection: keep-alive
<= Recv header, 2 bytes (0x2)
0000:
<= Recv data, 2829 bytes (0xb0d)
<redacted: proxy answer with an error message>
== Info: Connection #0 to host <proxy> left intact

### curl/libcurl version

[curl -V output]
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.36 zlib/1.2.7 libidn/1.28 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets

### operating system

cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)

**Comment by bagder** [comment] 2019-11-11 15:15
> User-Agent: curl/7.29.0

That's the curl version we shipped on **February 6, 2013**. I'm sure that version had a lot of bugs. We've literally fixed *thousands* of bugs since then. Some of them have for sure involved proxy authentication and could very well include this.

**Comment by devzero2000** [comment] 2019-11-11 22:02
This is from curl build just now from the master branch
*************************
./curl -V
curl 7.67.1-DEV (x86_64-unknown-linux-gnu) libcurl/7.67.1-DEV OpenSSL/1.0.2k-fips zlib/1.2.7
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTPS-proxy Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL UnixSockets
***********************
Below is the trace-ascii result from the previous test with this curl version. 

== Info: Uses proxy env variable no_proxy == '".a.b.c"'
== Info:   Trying xx.xx.xx.xx:8080...
== Info: TCP_NODELAY set
== Info: Connected to "proxy" (xx.xx.xx.xx) port 8080 (#0)
=> Send header, 125 bytes (0x7d)
0000: GET http://google.com/ HTTP/1.1
0021: Host: google.com
0033: User-Agent: curl/7.67.1-DEV
0050: Accept: */*
005d: Proxy-Connection: Keep-Alive
007b:
== Info: Mark bundle as not supporting multiuse
== Info: HTTP 1.0, assume close after body
<= Recv header, 44 bytes (0x2c)
0000: HTTP/1.0 407 Proxy Authentication Required
<= Recv header, 15 bytes (0xf)
0000: Server: squid
<= Recv header, 19 bytes (0x13)
0000: Mime-Version: 1.0
<= Recv header, 37 bytes (0x25)
0000: Date: Mon, 11 Nov 2019 21:47:14 GMT
<= Recv header, 25 bytes (0x19)
0000: Content-Type: text/html
<= Recv header, 22 bytes (0x16)
0000: Content-Length: 2829
<= Recv header, 42 bytes (0x2a)
0000: X-Squid-Error: ERR_CACHE_ACCESS_DENIED 0
<= Recv header, 31 bytes (0x1f)
0000: Proxy-Authenticate: Negotiate
<= Recv header, 26 bytes (0x1a)
0000: Proxy-Authenticate: NTLM
<= Recv header, 60 bytes (0x3c)
0000: Proxy-Authenticate: Basic realm="Authenticating in "DOMAIN""
<= Recv header, 46 bytes (0x2e)
0000: X-Cache: MISS from "proxy"
<= Recv header, 58 bytes (0x3a)
0000: X-Cache-Lookup: NONE from "proxy":8080
<= Recv header, 44 bytes (0x2c)
0000: Via: 1.0 "proxy" (squid)
== Info: HTTP/1.0 connection set to keep alive!
<= Recv header, 24 bytes (0x18)
0000: Connection: keep-alive
<= Recv header, 2 bytes (0x2)
0000:
== Info: Ignoring the response-body
<= Recv data, 2829 bytes (0xb0d)
940: <redacted: html auth error messagee from proxy>
== Info: Connection #0 to host "proxy" left intact
== Info: Issue another request to this URL: 'http://google.com/'
== Info: Uses proxy env variable no_proxy == '".a.b.c"'
== Info: Found bundle for host "proxy": 0x229f1c0 [serially]
== Info: Re-using existing connection! (#0) with proxy "proxy"
== Info: Connected to "proxy" (xx.xx.xx.xx) port 8080 (#0)
== Info: gss_init_sec_context() failed: SPNEGO cannot find mechanisms to negotiate.
== Info: Proxy auth using Negotiate with user 'dssspatch'
=> Send header, 125 bytes (0x7d)
0000: GET http://google.com/ HTTP/1.0
0021: Host: google.com
0033: User-Agent: curl/7.67.1-DEV
0050: Accept: */*
005d: Proxy-Connection: Keep-Alive
007b:
== Info: Mark bundle as not supporting multiuse
== Info: HTTP 1.0, assume close after body
<= Recv header, 44 bytes (0x2c)
0000: HTTP/1.0 407 Proxy Authentication Required
<= Recv header, 15 bytes (0xf)
0000: Server: squid
<= Recv header, 19 bytes (0x13)
0000: Mime-Version: 1.0
<= Recv header, 37 bytes (0x25)
0000: Date: Mon, 11 Nov 2019 21:47:14 GMT
<= Recv header, 25 bytes (0x19)
0000: Content-Type: text/html
<= Recv header, 22 bytes (0x16)
0000: Content-Length: 2829
<= Recv header, 42 bytes (0x2a)
0000: X-Squid-Error: ERR_CACHE_ACCESS_DENIED 0
== Info: gss_init_sec_context() failed: SPNEGO cannot find mechanisms to negotiate.
<= Recv header, 31 bytes (0x1f)
0000: Proxy-Authenticate: Negotiate
<= Recv header, 26 bytes (0x1a)
0000: Proxy-Authenticate: NTLM
<= Recv header, 60 bytes (0x3c)
0000: Proxy-Authenticate: Basic realm="Authenticating in "DOMAIN""
<= Recv header, 46 bytes (0x2e)
0000: X-Cache: MISS from "proxy"
<= Recv header, 58 bytes (0x3a)
0000: X-Cache-Lookup: NONE from "proxy":8080
<= Recv header, 44 bytes (0x2c)
0000: Via: 1.0 "proxy" (squid)
== Info: HTTP/1.0 connection set to keep alive!
<= Recv header, 24 bytes (0x18)
0000: Connection: keep-alive
<= Recv header, 2 bytes (0x2)
0000:
<= Recv data, 2401 bytes (0x961)
940: <redacted: html auth error messagee from proxy>
<= Recv data, 428 bytes (0x1ac)
940: <redacted: html auth error messagee from proxy>
== Info: Connection #0 to host "proxy" left intact

**Comment by bagder** [comment] 2019-11-14 17:51
Ah too bad, then this is *still* a problem after this many years... Unfortunately we don't have test cases for Negotiate and I personally don't have any setups that use it so I have a hard time to work on these things as well.

**Comment by bagder** [comment] 2020-01-09 15:00
[This unfortunately remains a KNOWN_BUG](https://curl.haxx.se/docs/knownbugs.html#libcurl_can_fail_to_try_alternat) and is a duplicate of #876

Duplicate of #876

**Closed by bagder** 2020-01-09 15:00 UTC
Labels: Authentication, KNOWN_BUGS material, connecting & proxies, help wanted
