### ISSUE TITLE
Internal SSL engine error encountered during the SSL handshake with curl 7.87.0

### ISSUE THREAD

**Issue by micwinxx** [curl/curl#10226] opened 2023-01-04 16:37 UTC
### I did this
OS: `macOS 11.2.1 build 20D75`
build curl from scratch with: `./configure --disable-shared --with-secure-transport --enable-threaded-resolver --disable-ldap --disable-rtsp --without-librtmp --without-zlib`
a curl POST request fails non-deterministically, e.g., 
running `curl -v https:/www.google.com --data "POST https://www.google.com"` sometimes (non-deterministically) fails with
```
*   Trying 142.251.34.164:443...
* Connected to www.google.com (142.251.34.164) port 443 (#0)
* ALPN: offers http/1.1
* Internal SSL engine error encountered during the SSL handshake
* Closing connection 0
curl: (35) Internal SSL engine error encountered during the SSL handshake
```
This behavior is new with curl 7.87.0 and there where no issues with 7.86.0. 
Also, it seems that it can fail GET requests.

(We also experiencing other strange effects with 7.87.0 which might be unrelated but are hard to reproduce.)

### I expected the following

not to fail/error out

### curl/libcurl version

new in 7.87.0

```
curl -V
curl 7.87.0 (x86_64-apple-darwin20.3.0) libcurl/7.87.0 SecureTransport
Release-Date: 2022-12-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile NTLM NTLM_WB SSL threadsafe UnixSockets
```

### operating system

`macOS 11.2.1 build 20D75 Darwin Kernel Version 20.3.0 x86_64`

**Comment by dfandrich** [comment] 2023-01-04 19:07
Dupe of #10227 (this one was first but that one has slightly more information).

**Closed by dfandrich** 2023-01-04 19:07 UTC
