### ISSUE TITLE
libcurl reuse connection bug when switch network from wifi to Cellular on iphone

### ISSUE THREAD

**Issue by codefei** [curl/curl#3132] opened 2018-10-13 02:26 UTC
### I did this
I use libcurl as network library on iphone, when I switch network type, from wifi(use eh0 interface) to 4G (will use pdp_ip0 interface), and I send the same request again,  libcurl will reuse the connection, but the request can't send success because the connection can't use, the reuse socket is dead

1. send request use wifi, the request is send success
2. close wifi and use Cellular
3. send same request again, the request will can't send success, error code is 28

**detail log in the attachment**

### I expected the following
libcurl found the connection dead, open the connection

[libcurl_error.log](https://github.com/curl/curl/files/2474999/libcurl_error.log)

### curl/libcurl version

[curl -V output]
7.61.0

### operating system
iPhoneX(iPhone10,3)

**Comment by bagder** [comment] 2018-10-13 08:53
This normally works fine since libcurl typically gets an error back when it tries to send data over the reused connection that no longer lives. In your case, for some reason that seems unclear to me, libcurl sends the GET on the dead connection without getting an error back so it doesn't fallback and retries on a new connection which it would do otherwise.

In fact, this failure you're seeing looks just like a normal failure to libcurl...

**Comment by codefei** [comment] 2018-10-13 09:19
The essential question I think when switch from WiFi to cellular on iPhone, libcurl can not know the connection is dead, libcurl should not reuse the connection.   
Because after network changed use different network interface, so reuse the connection will get timeout issue.

**Comment by codefei** [comment] 2018-10-13 09:34
libcurl how to know connection is dead? If the sever active close the socket, the client will receive FIN, this situation libcurl will think the connection is dead and open new connection right?

I have a idea monitor network changes, but how I can cleanup all cached connections?

**Comment by bagder** [comment] 2018-10-13 10:11
Yes, if the connection was closed then libcurl will rather easily detect that and retry with a new connection. If you check your log again, you can see that libcurl managed to send out a full request on the connection without an error being returned, which would indicate to libcurl that the connection was not dead at that time.

> how I can cleanup all cached connections?

Close the handle. The idea to offer a way to [flush the connection pool is listed in the TODO](https://curl.haxx.se/docs/todo.html#Offer_API_to_flush_the_connectio)...

**Comment by codefei** [comment] 2018-10-13 10:37
Thanks a lot for your reply.

In the log, the first request is sent success by libcurl using WiFi on iphone.  
Then I close WiFi and use celliuar. The connection is reused. After about 10s I receive 28 error code from libcurl.  
I expect the second request can send success immediately.

Another question If the server shutdown abnormal whether libcurl will know the connection is dead？

**Comment by codefei** [comment] 2018-10-13 10:45
The second request is not send out.

**Comment by bagder** [comment] 2018-10-13 10:49
> The connection is reused. After about 10s I receive 28 error code from libcurl.

The request is sent out on that reused connection immediately without any error being returned. Then it takes 10 seconds for the kernel/connection/server to close it, and then libcurl notices that. libcurl was waiting for a response to come back during those 10 seconds.

> If the server shutdown abnormal whether libcurl will know the connection is dead？

libcurl acts on what happens with the connection and can't really tell what the server did or didn't. It detects "dead" connections (for whatever reason) using a few different means, but most importantly here: on a dead connection it can't normally successfully send a full request. That's sort of an odd definition of a dead connection.

**Comment by codefei** [comment] 2018-10-13 11:52
> The request is sent out on that reused connection immediately without any error being returned.

I don't think so. Before I send the second request through cellular(4G), the wifi is disabled by me.
**The phone ip is changed and network route is changed, 192.168.1.107 could't use anymore.**
> local address = 192.168.1.107, local port = 58174, socketfd = 8

I also test post request, the second request socket event log has no action of CURL_POLL_OUT, the action parameter informs the callback on the status of the given socket

```
2018-10-13 19:33:10.362321+0800 CommonExample[261:5157] [D][CommonNetwork][Network.mm, socketCallback, 134][Debug:socket call back with sockfd = 8, action = 2
2018-10-13 19:33:10.388327+0800 CommonExample[261:5157] [D][CommonNetwork][Network.mm, socketCallback, 134][Debug:socket call back with sockfd = 8, action = 1
2018-10-13 19:33:10.412522+0800 CommonExample[261:5157] [D][CommonNetwork][Network.mm, socketCallback, 134][Debug:socket call back with sockfd = 8, action = 4
---------------------------------
2018-10-13 19:33:19.092308+0800 CommonExample[261:5157] [D][CommonNetwork][Network.mm, socketCallback, 134][Debug:socket call back with sockfd = 8, action = 1
2018-10-13 19:33:29.092712+0800 CommonExample[261:5157] [D][CommonNetwork][Network.mm, socketCallback, 134][Debug:socket call back with sockfd = 8, action = 4
```

**Comment by bagder** [comment] 2018-10-13 13:00
Isn't line 93-100 showing the request getting sent on the reused connection?
~~~
=> Send header, 0000000234 bytes (0x000000ea)
0000: GET /query?type=yuantong&postid=11111111111 HTTP/1.1
0036: Host: www.kuaidi100.com
004f: User-Agent:  iOS/12.0 Model/iPhone10,3 BundleID/com.xuntest.Comm
008f: onExample AppVersion/1.0 AppBuild/1 cURL/7.61.0
00c0: Accept: */*
00cd: Accept-Encoding: identity
00e8: 
~~~

**Comment by codefei** [comment] 2018-10-14 08:34
In my case,  the network interface is down, but libcurl think the connection is ok, and reuse the cached connection, because libcurl doesn't know the the event. 

So how I can solve my problem? And I hope can  normal use connection cache.    
Can you give me a suggestion? Because now no libcurl interface can refresh all cached connections. What about manual close all sockets when network changed?

**Comment by bagder** [comment] 2018-10-16 21:03
> So how I can solve my problem? And I hope can normal use connection cache.
Can you give me a suggestion?

Your kernel seems to act in a way that libcurl doesn't handle, and quite frankly it puzzles me. If the connection is dead, why doesn't it return an error when libcurl writes data to it? That's the final hint to libcurl - as it already tests for "aliveness" some other ways as well.

A connection going dead when libcurl wants to reuse it is not a rare situation. It happens all the time and yet your issue is not being reported by others. I don't understand it, and I don't have a lot of good ideas on how to handle this!

**Comment by bagder** [comment] 2019-01-10 15:01
I cannot  reproduce nor understand. Will move to `KNOWN_BUGS`, but looks like a broken TCP implementation for which I don't think we can do a lot.

**Comment by codefei** [comment] 2019-01-11 10:58
So this issue seems related to iOS system? I will continue to study this case when I am free. Now I just disable the connection reuse feature.

**Comment by codefei** [comment] 2019-01-11 12:45
When I change from WiFi to 4G, the apple’s Xcode tool still shows the tcp
connection is active. But reuse the connection will get timeout.

Daniel Stenberg <notifications@github.com>于2019年1月10日 周四23:01写道：

**Comment by codefei** [comment] 2019-01-13 17:15
When I change from WiFi to 4G, the apple’s Xcode tool still shows the tcp
connection is active. But reuse the connection will get timeout.  
![wechatimg856](https://user-images.githubusercontent.com/7637224/51088379-d1df0580-1799-11e9-9eae-78e7f8883d90.jpeg)

**Comment by bagder** [comment] 2019-01-14 07:31
> The application layer can detect the network change event

Sure, but it is really hard for the application layer to know if a network change caused the connection to die or not so it still makes sense to *try* the connection to see if it is still alive or not, exactly what curl already does.

In your scenario, the connection is still alive and that's the problem. If the connection would've been brought down then curl would see that and retry by creating a new one.

**Comment by gvanem** [comment] 2019-01-14 08:20
FYI, the same problem happens often in 3G/4G radio-equipment with dual SIM-cards. A switch from one SIM card to the other (like from Telenor to Telia) could hardly maintain the same app-level connection (remote IP). Meaning a complete flush of the conn-cache.

I guess an app-level heartbeat seems best to detect the switch? Like OpenSSL did, but [wrongly](https://www.youtube.com/watch?v=1dOCHwf8zVQ).

**Comment by gvanem** [comment] 2019-01-14 08:32
Interesting. And in HTTP/3, QUIC?

**Comment by bagder** [comment] 2019-01-14 08:36
QUIC is similar to HTTP/2 in this aspect. It has a [PING frame](https://tools.ietf.org/html/draft-ietf-quic-transport-17#section-19.2) in the transport layer, which could be used for this. But QUIC is also much better at [Connection Migration](https://tools.ietf.org/html/draft-ietf-quic-transport-17#section-9) so an existing QUIC connection can be moved from 4G to wifi and back without it having to shutdown in the first place!

**Comment by bagder** [comment] 2019-05-12 14:42
1. I can't see any curl bug here, this is just a slow/bad TCP stack.
2. With the new `CURLOPT_MAXAGE_CONN` option, this situation can at least be reduced.

**Closed by bagder** 2019-05-12 14:42 UTC
Labels: KNOWN_BUGS material, connecting & proxies
