### ISSUE TITLE
Slow upload speeds

### ISSUE THREAD

**Issue by ViperCode7** [curl/curl#708] opened 2016-03-09 01:13 UTC
### I did this
Uploading 10 rar files (500MB total) through php_curl but speeds are way too low.
I also used a callback and I noticed it reads 8kb slices. For 500MB, that's a lot of reads.

### I expected the following
Upload speeds to max out, speeds I get when using a form in Chrome are 12MB/s (96 Mbps), to the same server and the same form parameters.

Is tere a way to set up a bigger slice size?

### curl/libcurl version
lib 7.47.1

[curl -V output perhaps?]
no

### operating system
Win 7 SP1 x64.

**Comment by jay** [comment] 2016-03-09 03:43
Can you give us a self contained example that can be used to reproduce this without using PHP? In Windows 7 x64 I just posted a 100MB file to http://testmy.net/uploader using curl 7.47.1 and it went full speed.

**Comment by bagder** [comment] 2016-03-09 07:06
> I noticed it reads 8kb slices

How did you notice that and what do you mean with "slices" here?

**Comment by ViperCode7** [comment] 2016-03-09 07:53
@jay, I need it in php because the form requires preactivation and postupload finalization. In a batch that would be a lot more complicated to do since responses are XML and HTTP. Unfortunately no exaple, because the service I upload to is a payed service and it's tied to my IP.

Bu what exacly are you looking for?

@badger Take one global var, an int. Mix in CURLOPT_NOPROGRESS false and CURLOPT_PROGRESSFUNCTION 'callback'. Let that 'callback' increment the global var until done, don't do anything else in it. For a 500MB upload I got a 64000-ish value last night. 500MB / 64000 = 8kb. As per docs: "The callback gets told how much data libcurl will transfer and has transferred, in number of bytes". Anyway, as per Process Explorer performance counters, the delta reads at 1 second intervals are at 1.4 MB at a count of 90. My bad, it doesn't amount to 8KB per slice but 16KB. Other bytes delta are at less than 8KB and of 240-ish count, making it at 2MB/s exactly the speed with which cURL uploads. These are values on the spot. Still, a lot of read slices compared to Chrome. Same form, same host, same files to upload, delta reads at 11.5 MB/s with 750 reads/sec and Other delta at 10.4 MB/s at 700 ops, again these are on the spot, not accounting for prebuffering. But overall, the Other delta show the amount of data I see going out the NIC. BTW, the counter for the NIC is done with Nirsoft AdapterWatch.

I'm just asking here why a one process libcurl through php gets slow uploads, while the same thing in Chrome maxes out my upload speeds?

**Comment by bagder** [comment] 2016-03-09 08:02
16K is an internal buffer size so that would be totally expected. But also not a problem, that's not normally a limiting factor and refer back to @jay's statement: you can saturate very high bandwidth pipes with that buffer size as well.

My suggestion: try uploading any 500MB data using the curl command line tool from and to the same machines to get a view on how fast curl can do it. That'll also tell us if the problem is in your code/PHP or if it is a bottle neck is truly in libcurl.

**Comment by bagder** [comment] 2016-03-09 08:04
BTW, is that multipart formposts uploads you're talking about or what kind of uploads is it?

**Comment by jay** [comment] 2016-03-10 08:59
Well his max upstream bandwidth is 20x more than mine so maybe he's experiencing something I can't. In Windows 7 x64 I just did several speed tests in each of Chrome, Firefox and libcurl (7.47.1) to a NY server via HTTP using 50MB of POST data and I get about the same results in Chrome, Firefox and libcurl 7.47.1 of ~600KB/s pretty consistently.

> I'm just asking here why a one process libcurl through php gets slow uploads, while the same thing in Chrome maxes out my upload speeds?

@ViperCode7 We don't have enough information to answer that yet. [Can you try this example in C](https://gist.github.com/jay/daac01682f17c2dc213e), it has instructions on how you can do what I did and upload via browser and then via libcurl and compare the results. Also, note in the source the `#if 1` section by CURLOPT_READFUNCTION. If you have worse performance using the program then change that to `#if 0` and it will read the whole file into memory first, and see if that makes a difference.

**Comment by bagder** [comment] 2016-03-10 09:19
Great test app @jay!

For fun (acknowledging that I run a different OS and everything), I ran it against my localhost HTTP server (Apache) on Linux and it is actually *amazingly* fast. 4GB is sent in about 1.5 to 1.9 seconds. The test app doesn't even have timing resolution enough to tell the speed very accurately.

I then sent 500MB to my (remote) web server (https://daniel.haxx.se) over HTTPS. I have 100 mbit uplink and the server is at only a little over 2ms ping-time away (7 hops according to traceroute) and it reported:

    Transfer rate: 11013 KB/sec (524288000 bytes in 46 seconds)

I don't think it can do better on this link! =)

**Comment by jay** [comment] 2016-03-11 05:14
The speedtest kB/s is actually lowercase k which I missed last night. That means the comparison I was making was not an accurate. When I compare both as kB/s then libcurl is often a little bit faster by about 20kB/s. So since then I've edited the example to show several other data rates (Mbps, kB/s) and also to error if all the data wasn't uploaded. @bagder you may want to test again with the updated version since it's possible for a server to reply before all the data is uploaded and I didn't account for that.

Now the output looks like this:
~~~
Transfer rate: 625 KB/sec (52428883 bytes in 82 seconds)

Other data rate units:

                  5.12 Mbps
               5122.19 kbps
                  0.61 MiB/s
                625.27 KiB/s
                640.27 kB/s   <-------- This is the one to compare against.
             640274.00 B/s
~~~

**Comment by bagder** [comment] 2016-03-11 08:19
It doesn't change much for my tests:

4GB to localhost on Linux 4.3.5 kernel to Apache 2.1.18

Transfer rate: 2286472 KB/sec (4000000000 bytes in 2 seconds)

Other data rate units:

              18730.78 Mbps
           18730779.00 kbps
               2232.88 MiB/s
            2286472.05 KiB/s
            2341347.38 kB/s
         2341347375.00 B/s

Sending 500MB to my (remote) server from the same Linux machine, over my 100mbit connection to an Apache HTTP server. Note that I kept streaming music and used the machine normally during this test so the test shared the bandwidth with other applications.

Transfer rate: 11045 KB/sec (524288000 bytes in 46 seconds)

Other data rate units:

                 90.48 Mbps
              90480.69 kbps
                 10.79 MiB/s
              11045.01 KiB/s
              11310.09 kB/s
           11310086.00 B/s

**Comment by bagder** [comment] 2016-03-11 09:43
@jay, I think it could be an idea to save your test code somewhere and turn into a first iteration of a "libcurl transfer speed measurement" tool since we do get questions and concerns similar to this at times. Then we can extend this over time to be able to measure other kinds of transfers and protocols too.

**Comment by bagder** [comment] 2016-03-11 10:03
Interesting little additional tidbit: I switched on HTTP/2 for my "remote case" (that already were speaking HTTPS), and it seems to send data in the same speed.

**Comment by bagder** [comment] 2016-03-11 14:17
Changing the code to upload straight from memory is repeatedly slightly faster on localhost:
~~~~
Transfer rate: 2935752 KB/sec (4000000000 bytes in 1 seconds)

Other data rate units:

              24049.68 Mbps
           24049680.62 kbps
               2866.95 MiB/s
            2935752.03 KiB/s
            3006210.08 kB/s
         3006210078.00 B/s

**Comment by ViperCode7** [comment] 2016-03-13 00:00
@bagder, it's multipart form data

I've uploaded it with curl.exe (curl-7.47.1-win64-mingw), it was tricky, after the post it gets a location and that one also gets a js redirect to finalize the file... eventually I've managed to do the upload, same speeds, around 2 MB/s.

Also tried ZOOM FileUploader, this one also maxes out my bw with just one file to upload... captured it's HTTP packets and all are the same as Chrome's and the PHP script's (with cURL) I wrote initially about.

Later in writing this post I also tried a WGET approach, this time I only got 500KB/s. And using the hacked bits from wget (since natively it doesn't support multipart uploads) I also did a PHP fsockopen approach and got 5MB/s, all data was read in memory, about 200MB. Again not ideal, even if speeds are better.

@jay, I can't use that program as the data would not pertain to my issue. When uploading to a host outside my country my speed is capped at 1.5MB/s, below the 2MB/s issue speed I get with cURL. So even with that test program, with php's libcurl, zoom, chrome, it would show the same speed, around 1.5MB/s.

http://testmy.net/ gave me 1.2MB/s with a server from Germany. With french and dutch servers I usually deal I get at 1.5MB/s.

The main reason I'm in this mess is that I need a way to move files in a short window of time and if my country hosts could offer these speeds I said why not give it a try. Luckily the premium status allows me to post multiple uploads at the same time, an acceptable workaround, which is what I've been using the past couple of days.

Other than that, there are not many hosts I can upload to with my max speeds, but this one was an odd case.

**Comment by bagder** [comment] 2016-03-13 09:50
The point with @jay's test program and me running it on another platform was however just to see what the theoretical limits could be and if we have an architectural problem that would limit upload speeds, as you implied in your original post. If you'd run the test program on your windows machine it would tell us how fast libcurl *can* upload in your situation so the difference between the test program and your "live" problem case would then be attributed to other factors.

**Comment by ViperCode7** [comment] 2016-03-13 17:00
I didn't manage to compile it.

```
# Project: PostUpload
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = PostUpload.o
LINKOBJ  = PostUpload.o
LIBS     = -L"W:/Downloads/CPPp/App/Dev-Cpp/MinGW64/lib" -L"W:/Downloads/CPPp/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -L"W:/Downloads/PostUpload/curl-7.40.0-devel-mingw64/lib64"
INCS     = -I"W:/Downloads/CPPp/App/Dev-Cpp/MinGW64/include" -I"W:/Downloads/CPPp/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"W:/Downloads/CPPp/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"W:/Downloads/PostUpload/curl-7.40.0-devel-mingw64/include"
CXXINCS  = -I"W:/Downloads/CPPp/App/Dev-Cpp/MinGW64/include" -I"W:/Downloads/CPPp/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"W:/Downloads/CPPp/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"W:/Downloads/CPPp/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"W:/Downloads/PostUpload/curl-7.40.0-devel-mingw64/include"
BIN      = curl-7.40.0-devel-mingw64/bin/PostUpload.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

PostUpload.o: PostUpload.c
	$(CC) -c PostUpload.c -o PostUpload.o $(CFLAGS)
```
Error: W:\Downloads\PostUpload\collect2.exe	[Error] ld returned 1 exit status

**Comment by bagder** [comment] 2016-03-15 10:02
Is that really all the errors it showed? Did you build your libcurl to use any dependency libs? Do you have them around when you link this example app too?

**Comment by jay** [comment] 2016-03-19 18:19
> Transfer rate: 2935752 KB/sec (4000000000 bytes in 1 seconds)

Mine was slower, in Windows 7 x64 it took me 11 seconds to Apache/2.4.18 (Win64) OpenSSL/1.0.2g.
Transfer rate: 361322 KB/sec (4000000000 bytes in 11 seconds)

> I didn't manage to compile it.

@ViperCode7 It looks like you didn't link to libcurl.

**Comment by bagder** [comment] 2016-03-19 21:26
> Transfer rate: 361322 KB/sec

I'd say that is still speedy enough to make me claim the 16K buffer size is not a significant blocker. For science, can you try changing `CURL_MAX_WRITE_SIZE` to 32K and 64K, rebuild and see if it you can notice any speed difference?

**Comment by bagder** [comment] 2016-03-27 15:49
Sorry, but we've seen no evidence that curl itself is slow. Closing this.

**Closed by bagder** 2016-03-27 15:49 UTC

**Comment by jay** [comment] 2016-03-28 05:23
@bagder here are the results. I built from 3d144ab and POSTed 4000000000 bytes 6 times for each `CURL_MAX_WRITE_SIZE` of 16384, 32768, 65536 and 1048576 to localhost `Apache/2.4.18 (Win64) OpenSSL/1.0.2g`. I tried plain unencrypted and then encrypted in OpenSSL, WinSSL and wolfSSL.

Of the SSL libraries OpenSSL was fastest by a large margin. Bumping the buffer to 32k decreased the total transfer time by a second.

WinSSL (schannel) was slower than OpenSSL by 30 seconds and it could not use a buffer size above 16384. I reviewed `schannel_send` for both of these issues. In the former case I could not figure out why it's slower. I tried removing the polling code and refactoring the rest but there was no difference. Do you think it's possible it may be the limitations of the library? In the latter case the maximum message length returned by the library is 16384, and currently if a larger size is given to send then [we return CURLE_SEND_ERROR](https://github.com/curl/curl/blob/curl-7_48_0/lib/vtls/schannel.c#L838-L842). A simple workaround for that is split it up into 16k chunks however in that case testing buffer sizes that are a multiple of 16k would not make a difference in speed.

**wolfSSL was slower than OpenSSL by 220 seconds.** That's slow enough to make me question whether I made a mistake but I don't see one. And [cyassl_send](https://github.com/curl/curl/blob/curl-7_48_0/lib/vtls/cyassl.c#L516-L532) looks pretty straightforward. Could you try to reproduce?
~~~
HTTP: 'DLL Release' x64 - CURL_MAX_WRITE_SIZE 16384
Transfer rate: 353155 KB/sec (4000000000 bytes in 11 seconds)
Transfer rate: 353667 KB/sec (4000000000 bytes in 11 seconds)
Transfer rate: 342533 KB/sec (4000000000 bytes in 11 seconds)
Transfer rate: 342533 KB/sec (4000000000 bytes in 11 seconds)
Transfer rate: 360289 KB/sec (4000000000 bytes in 11 seconds)
Transfer rate: 342083 KB/sec (4000000000 bytes in 11 seconds)

HTTP: 'DLL Release' x64 - CURL_MAX_WRITE_SIZE 32768
Transfer rate: 434752 KB/sec (4000000000 bytes in 9 seconds)
Transfer rate: 440042 KB/sec (4000000000 bytes in 9 seconds)
Transfer rate: 437724 KB/sec (4000000000 bytes in 9 seconds)
Transfer rate: 415957 KB/sec (4000000000 bytes in 9 seconds)
Transfer rate: 513170 KB/sec (4000000000 bytes in 8 seconds)
Transfer rate: 435479 KB/sec (4000000000 bytes in 9 seconds)

HTTP: 'DLL Release' x64 - CURL_MAX_WRITE_SIZE 65536
Transfer rate: 457728 KB/sec (4000000000 bytes in 9 seconds)
Transfer rate: 462005 KB/sec (4000000000 bytes in 8 seconds)
Transfer rate: 465418 KB/sec (4000000000 bytes in 8 seconds)
Transfer rate: 475155 KB/sec (4000000000 bytes in 8 seconds)
Transfer rate: 472454 KB/sec (4000000000 bytes in 8 seconds)
Transfer rate: 465418 KB/sec (4000000000 bytes in 8 seconds)

HTTP: 'DLL Release' x64 - CURL_MAX_WRITE_SIZE 1048576
Transfer rate: 450340 KB/sec (4000000000 bytes in 9 seconds)
Transfer rate: 477829 KB/sec (4000000000 bytes in 8 seconds)
Transfer rate: 468881 KB/sec (4000000000 bytes in 8 seconds)
Transfer rate: 469784 KB/sec (4000000000 bytes in 8 seconds)
Transfer rate: 469784 KB/sec (4000000000 bytes in 8 seconds)
Transfer rate: 462881 KB/sec (4000000000 bytes in 8 seconds)



HTTPS: 'DLL Release - DLL OpenSSL' x64 - CURL_MAX_WRITE_SIZE 16384
Transfer rate: 224976 KB/sec (4000000000 bytes in 17 seconds)
Transfer rate: 234019 KB/sec (4000000000 bytes in 17 seconds)
Transfer rate: 237794 KB/sec (4000000000 bytes in 16 seconds)
Transfer rate: 233362 KB/sec (4000000000 bytes in 17 seconds)
Transfer rate: 235999 KB/sec (4000000000 bytes in 17 seconds)
Transfer rate: 235771 KB/sec (4000000000 bytes in 17 seconds)

HTTPS: 'DLL Release - DLL OpenSSL' x64 - CURL_MAX_WRITE_SIZE 32768
Transfer rate: 248173 KB/sec (4000000000 bytes in 16 seconds)
Transfer rate: 252423 KB/sec (4000000000 bytes in 15 seconds)
Transfer rate: 249139 KB/sec (4000000000 bytes in 16 seconds)
Transfer rate: 254728 KB/sec (4000000000 bytes in 15 seconds)
Transfer rate: 253949 KB/sec (4000000000 bytes in 15 seconds)
Transfer rate: 255511 KB/sec (4000000000 bytes in 15 seconds)

HTTPS: 'DLL Release - DLL OpenSSL' x64 - CURL_MAX_WRITE_SIZE 65536
Transfer rate: 250401 KB/sec (4000000000 bytes in 16 seconds)
Transfer rate: 260018 KB/sec (4000000000 bytes in 15 seconds)
Transfer rate: 261918 KB/sec (4000000000 bytes in 15 seconds)
Transfer rate: 260018 KB/sec (4000000000 bytes in 15 seconds)
Transfer rate: 259741 KB/sec (4000000000 bytes in 15 seconds)
Transfer rate: 257346 KB/sec (4000000000 bytes in 15 seconds)

HTTPS: 'DLL Release - DLL OpenSSL' x64 - CURL_MAX_WRITE_SIZE 1048576
Transfer rate: 257872 KB/sec (4000000000 bytes in 15 seconds)
Transfer rate: 265244 KB/sec (4000000000 bytes in 15 seconds)
Transfer rate: 261375 KB/sec (4000000000 bytes in 15 seconds)
Transfer rate: 258949 KB/sec (4000000000 bytes in 15 seconds)
Transfer rate: 251919 KB/sec (4000000000 bytes in 16 seconds)
Transfer rate: 261655 KB/sec (4000000000 bytes in 15 seconds)



HTTPS: 'DLL Release - DLL Windows SSPI' x64 - CURL_MAX_WRITE_SIZE 16384
Transfer rate: 85170 KB/sec (4000000000 bytes in 46 seconds)
Transfer rate: 91552 KB/sec (4000000000 bytes in 43 seconds)
Transfer rate: 92842 KB/sec (4000000000 bytes in 42 seconds)
Transfer rate: 92397 KB/sec (4000000000 bytes in 42 seconds)
Transfer rate: 93364 KB/sec (4000000000 bytes in 42 seconds)
Transfer rate: 89589 KB/sec (4000000000 bytes in 44 seconds)

HTTPS: 'DLL Release - DLL Windows SSPI' x64 - CURL_MAX_WRITE_SIZE 32768
  0% uploaded...
Error: libcurl: (55) Failed sending data to the peer

HTTPS: 'DLL Release - DLL Windows SSPI' x64 - CURL_MAX_WRITE_SIZE 65536
  0% uploaded...
Error: libcurl: (55) Failed sending data to the peer

HTTPS: 'DLL Release - DLL Windows SSPI' x64 - CURL_MAX_WRITE_SIZE 1048576
  0% uploaded...
Error: libcurl: (55) Failed sending data to the peer



HTTPS: 'DLL Release - DLL wolfSSL' x64 - CURL_MAX_WRITE_SIZE 16384
Transfer rate: 15148 KB/sec (4000000000 bytes in 258 seconds)
Transfer rate: 14806 KB/sec (4000000000 bytes in 264 seconds)
Transfer rate: 15244 KB/sec (4000000000 bytes in 256 seconds)
Transfer rate: 15024 KB/sec (4000000000 bytes in 260 seconds)
Transfer rate: 15151 KB/sec (4000000000 bytes in 258 seconds)
Transfer rate: 15137 KB/sec (4000000000 bytes in 258 seconds)

HTTPS: 'DLL Release - DLL wolfSSL' x64 - CURL_MAX_WRITE_SIZE 32768
Transfer rate: 15178 KB/sec (4000000000 bytes in 257 seconds)
Transfer rate: 16323 KB/sec (4000000000 bytes in 239 seconds)
Transfer rate: 16364 KB/sec (4000000000 bytes in 239 seconds)
Transfer rate: 15824 KB/sec (4000000000 bytes in 247 seconds)
Transfer rate: 16082 KB/sec (4000000000 bytes in 243 seconds)
Transfer rate: 16396 KB/sec (4000000000 bytes in 238 seconds)

HTTPS: 'DLL Release - DLL wolfSSL' x64 - CURL_MAX_WRITE_SIZE 65536
Transfer rate: 14867 KB/sec (4000000000 bytes in 263 seconds)
Transfer rate: 16538 KB/sec (4000000000 bytes in 236 seconds)
Transfer rate: 16337 KB/sec (4000000000 bytes in 239 seconds)
Transfer rate: 16878 KB/sec (4000000000 bytes in 231 seconds)
Transfer rate: 16108 KB/sec (4000000000 bytes in 243 seconds)
Transfer rate: 17070 KB/sec (4000000000 bytes in 229 seconds)

HTTPS: 'DLL Release - DLL wolfSSL' x64 - CURL_MAX_WRITE_SIZE 1048576
Transfer rate: 17125 KB/sec (4000000000 bytes in 228 seconds)
Transfer rate: 15906 KB/sec (4000000000 bytes in 246 seconds)
Transfer rate: 15561 KB/sec (4000000000 bytes in 251 seconds)
Transfer rate: 15650 KB/sec (4000000000 bytes in 250 seconds)
Transfer rate: 15666 KB/sec (4000000000 bytes in 249 seconds)
Transfer rate: 15555 KB/sec (4000000000 bytes in 251 seconds)
~~~

**Comment by jay** [comment] 2016-03-28 05:40
In hindsight I probably should have recorded the ciphers used.

**Comment by bagder** [comment] 2016-03-28 10:38
I can't reproduce that. With WolfSSL 3.7 on my linux againt localhost, I get speeds that are very similar to OpenSSL. They vary a little run to run but here's a typical:

~~~~
Transfer rate: 2810098 KB/sec (4000000000 bytes in 1 seconds)

Other data rate units:

              23020.32 Mbps
           23020324.06 kbps
               2744.24 MiB/s
            2810098.15 KiB/s
            2877540.51 kB/s
         2877540508.00 B/s

**Comment by jay** [comment] 2016-03-29 07:24
I tried wolfSSL v3.7.0 but the speed was still slow. I've since [posted](http://www.yassl.com/forums/post2465.html#p2465) about this in their forum.

**Comment by jay** [comment] 2016-04-04 05:08
The slower speeds with wolfSSL were because I didn't have AESNI enabled. I enabled it in the wolfssl project and now wolfSSL is only 4 seconds slower than OpenSSL on average.
~~~
HTTPS: 'DLL Release - DLL wolfSSL' x64 - CURL_MAX_WRITE_SIZE 16384
Transfer rate: 203737 KB/sec (4000000000 bytes in 19 seconds)
Transfer rate: 197635 KB/sec (4000000000 bytes in 20 seconds)
Transfer rate: 195930 KB/sec (4000000000 bytes in 20 seconds)
Transfer rate: 195322 KB/sec (4000000000 bytes in 20 seconds)
Transfer rate: 205592 KB/sec (4000000000 bytes in 19 seconds)
Transfer rate: 195782 KB/sec (4000000000 bytes in 20 seconds)

HTTPS: 'DLL Release - DLL wolfSSL' x64 - CURL_MAX_WRITE_SIZE 32768
Transfer rate: 202428 KB/sec (4000000000 bytes in 19 seconds)
Transfer rate: 203578 KB/sec (4000000000 bytes in 19 seconds)
Transfer rate: 203249 KB/sec (4000000000 bytes in 19 seconds)
Transfer rate: 204741 KB/sec (4000000000 bytes in 19 seconds)
Transfer rate: 215684 KB/sec (4000000000 bytes in 18 seconds)
Transfer rate: 204741 KB/sec (4000000000 bytes in 19 seconds)

HTTPS: 'DLL Release - DLL wolfSSL' x64 - CURL_MAX_WRITE_SIZE 65536
Transfer rate: 207107 KB/sec (4000000000 bytes in 19 seconds)
Transfer rate: 220431 KB/sec (4000000000 bytes in 18 seconds)
Transfer rate: 198418 KB/sec (4000000000 bytes in 20 seconds)
Transfer rate: 187431 KB/sec (4000000000 bytes in 21 seconds)
Transfer rate: 202754 KB/sec (4000000000 bytes in 19 seconds)
Transfer rate: 196087 KB/sec (4000000000 bytes in 20 seconds)

HTTPS: 'DLL Release - DLL wolfSSL' x64 - CURL_MAX_WRITE_SIZE 1048576
Transfer rate: 209192 KB/sec (4000000000 bytes in 19 seconds)
Transfer rate: 210251 KB/sec (4000000000 bytes in 19 seconds)
Transfer rate: 210240 KB/sec (4000000000 bytes in 19 seconds)
Transfer rate: 211126 KB/sec (4000000000 bytes in 19 seconds)
Transfer rate: 211480 KB/sec (4000000000 bytes in 18 seconds)
Transfer rate: 210773 KB/sec (4000000000 bytes in 19 seconds)
~~~
