### ISSUE TITLE
curl cutting off post data

### ISSUE THREAD

**Issue by Jan1205** [curl/curl#1949] opened 2017-10-05 12:36 UTC
### I did this
I submitted a bug report at the php project:
https://bugs.php.net/bug.php?id=75315

### I expected the following
the correct post data

### curl/libcurl version
curl 7.56.0 (x86_64-pc-linux-gnu) libcurl/7.56.0 OpenSSL/1.0.2l zlib/1.2.8 nghttp2/1.24.0
Release-Date: 2017-10-04
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy

### operating system
Debian 9

**Comment by bagder** [comment] 2017-10-05 12:42
Can you please provide an example that we can reproduce this problem with, using only curl or libcurl - not involving PHP ? I don't understand what that recipe you link to is actually telling libcurl to do.

**Comment by Jan1205** [comment] 2017-10-05 14:01
With commandline curl it works perfect! The same with curl:
`curl -X POST -d test1=a -d test2=b -d test3=c --data-urlencode "test4@-" https://content.nol-is.de/service.php < post.data.txt`

The result (curl-request.log.txt) is correct. The same request with PHP fails (example code see PHP bug tracker). The result of the php script (php-request.log.txt).

PHP works with curl 7.55.0 correctly, but not with curl 7.56.0.

[post.data.txt](https://github.com/curl/curl/files/1359556/post.data.txt)
[curl-request.log.txt](https://github.com/curl/curl/files/1359554/curl-request.log.txt)
[php-request.log.txt](https://github.com/curl/curl/files/1359555/php-request.log.txt)

**Comment by bagder** [comment] 2017-10-05 18:21
Since curl works, that pushes the ball over to PHP's half of the field again - curl itself of course uses libcurl, presumably the same way PHP uses it to do this transfer. What does PHP tell libcurl to send, and how? Can you ask PHP/CURL to show a full trace like `--trace` or `--trace-ascii` enable? Can you at least enable verbose so that we can see the outgoing request headers and we can confirm a Content-Length that is a few bytes less in the PHP case than in the command line case?

**Comment by Jan1205** [comment] 2017-10-06 08:48
Thanks for your reply. I hope now we have more informations. It is very curious.

The result with curl 7.55.0 and curl 7.56.0 is the same:

`curl -v -d test1=a -d test2=b -d test3=c --data-urlencode "test4@-" https://test.nol-is.de/service.php < post.data.txt`

```
*  Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to test.nol-is.de (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs/
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=DE; postalCode=31582; ST=Niedersachsen; L=Nienburg/Weser; street=Celler Strasse 53; O=NOLIS GmbH; OU=PremiumSSL Wildcard; CN=*.nol-is.de
*  start date: Jan 16 00:00:00 2017 GMT
*  expire date: Feb 27 23:59:59 2020 GMT
*  subjectAltName: host "test.nol-is.de" matched cert's "*.nol-is.de"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Organization Validation Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0xa75220)
> POST /service.php HTTP/2
> Host: test.nol-is.de
> User-Agent: curl/7.55.0
> Accept: */*
> Content-Length: 28125
> Content-Type: application/x-www-form-urlencoded
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* We are completely uploaded and fine
< HTTP/2 200
< date: Fri, 06 Oct 2017 08:19:53 GMT
< server: Apache
< vary: Accept-Encoding
< content-type: text/html; charset=UTF-8
<
int(28122)
```

```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to test.nol-is.de (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs/
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=DE; postalCode=31582; ST=Niedersachsen; L=Nienburg/Weser; street=Celler Strasse 53; O=NOLIS GmbH; OU=PremiumSSL Wildcard; CN=*.nol-is.de
*  start date: Jan 16 00:00:00 2017 GMT
*  expire date: Feb 27 23:59:59 2020 GMT
*  subjectAltName: host "test.nol-is.de" matched cert's "*.nol-is.de"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Organization Validation Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x149d230)
> POST /service.php HTTP/2
> Host: test.nol-is.de
> User-Agent: curl/7.56.0
> Accept: */*
> Content-Length: 28125
> Content-Type: application/x-www-form-urlencoded
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* We are completely uploaded and fine
< HTTP/2 200
< date: Fri, 06 Oct 2017 08:00:35 GMT
< server: Apache
< vary: Accept-Encoding
< content-type: text/html; charset=UTF-8
<
int(28122)
```

`curl --trace curl-trace.txt -d test1=a -d test2=b -d test3=c --data-urlencode "test4@-" https://test.nol-is.de/service.php < post.data.txt`

result see curl-trace.txt
[curl-trace.txt](https://github.com/curl/curl/files/1362050/curl-trace.txt)

I changed the php code:

```
$fp = fopen('php-trace.txt', 'w');

curl_setopt($ch, CURLOPT_URL, 'https://test.nol-is.de/service.php');
curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_VERBOSE, true);
curl_setopt($ch, CURLOPT_STDERR, $fp);
```

I get following result:

PHP 7.1.10 curl 7.55.0
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to test.nol-is.de (127.0.0.1) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs/
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=DE; postalCode=31582; ST=Niedersachsen; L=Nienburg/Weser; street=Celler Strasse 53; O=NOLIS GmbH; OU=PremiumSSL Wildcard; CN=*.nol-is.de
*  start date: Jan 16 00:00:00 2017 GMT
*  expire date: Feb 27 23:59:59 2020 GMT
*  subjectAltName: host "test.nol-is.de" matched cert's "*.nol-is.de"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Organization Validation Secure Server CA
*  SSL certificate verify ok.
> POST /service.php HTTP/1.1

Host: test.nol-is.de

Accept: */*

Content-Length: 28470

Expect: 100-continue

Content-Type: multipart/form-data; boundary=------------------------73df9963bc5f2d9d



< HTTP/1.1 100 Continue

< HTTP/1.1 200 OK

< Date: Fri, 06 Oct 2017 08:18:16 GMT

< Server: Apache

< Upgrade: h2,h2c

< Connection: Upgrade

< Vary: Accept-Encoding

< Transfer-Encoding: chunked

< Content-Type: text/html; charset=UTF-8

< 

* Connection #0 to host test.nol-is.de left intact
```

PHP 7.1.10 curl 7.56.0
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to test.nol-is.de (127.0.0.1) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs/
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=DE; postalCode=31582; ST=Niedersachsen; L=Nienburg/Weser; street=Celler Strasse 53; O=NOLIS GmbH; OU=PremiumSSL Wildcard; CN=*.nol-is.de
*  start date: Jan 16 00:00:00 2017 GMT
*  expire date: Feb 27 23:59:59 2020 GMT
*  subjectAltName: host "test.nol-is.de" matched cert's "*.nol-is.de"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Organization Validation Secure Server CA
*  SSL certificate verify ok.
> POST /service.php HTTP/1.1

Host: test.nol-is.de

Accept: */*

Content-Length: 28470

Expect: 100-continue

Content-Type: multipart/form-data; boundary=------------------------73df9963bc5f2d9d



< HTTP/1.1 100 Continue

< HTTP/1.1 200 OK

< Date: Fri, 06 Oct 2017 08:18:16 GMT

< Server: Apache

< Upgrade: h2,h2c

< Connection: Upgrade

< Vary: Accept-Encoding

< Transfer-Encoding: chunked

< Content-Type: text/html; charset=UTF-8

< 

* Connection #0 to host test.nol-is.de left intact
```

The content length with curl 7.55.0 and 7.56.0 is also the same! The list of the content lengths:

```
curl 7.55.0: 28125
curl 7.56.0: 28125
PHP (curl 7.55.0): 28470
PHP (curl 7.56.0): 28470
```

In my previous comment you can see the different result, but the filesize ist the same (see curl-request.log.txt and php-request.log.txt). For example: parameter "json4" is not in the output. I'm not sure where the bug is: php or curl.

**Comment by bagder** [comment] 2017-10-06 08:54
You made a multipart formpost with your PHP/CURL program but your receiving end doesn't deal with it and presumes are regular x-www-form-urlencoded POST.

The bug is in your PHP program, the sender _or_ the receiver depending on what POST format you actually want to use.

**Comment by Jan1205** [comment] 2017-10-06 09:30
PHP sets internally "multipart/form-data". Our PHP-CURL-Request:
```
curl_setopt($ch, CURLOPT_URL, 'https://test.nol-is.de/service.php');
curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
```
The result is only a output from $_REQUEST (see service.php):
` print_r($_REQUEST, true)`

Then it seems to be a PHP bug. But a version change helps: PHP 7.1.10 CURL 7.55.0 works, PHP 7.1.10 CURL 7.65.0 not. Yesterday we create a PHP ticket: https://bugs.php.net/bug.php?id=75315

**Comment by buhman** [comment] 2017-10-11 07:07
> PHP 7.1.10 CURL 7.55.0 works, PHP 7.1.10 CURL 7.65.0 not

Are you sure this isn't a duplicate of #1965 caused by https://github.com/curl/curl/pull/1839 ?

**Comment by bagder** [comment] 2017-10-12 07:54
@buhman, this is not using stdin like #1965 but gets a `Content-Length:` and everything so I don't see how it can be the same...

**Comment by buhman** [comment] 2017-10-12 08:04
> gets a Content-Length: and everything so I don't see how it can be the same...

I think the C-L above is the request C-L.

> is not using stdin like

`"test4@-" https://localhost/service.php < post.data.txt`

**Comment by monnerat** [comment] 2017-10-13 00:37
I think it rather is the same bug as https://github.com/jeroen/curl/issues/126 and there's PR https://github.com/curl/curl/pull/1988 (work in progress) to fix it.

**Comment by Jan1205** [comment] 2017-10-13 10:18
The change 5f9e2ca fixes the bug. The PHP example works perfekt after the change. Many thanks to all the contributors. Great work!

**Comment by monnerat** [comment] 2017-10-29 15:35
Fixed by https://github.com/curl/curl/commit/5f9e2ca09b57d82baf239039835b3b06dc41bbc5

Closing

**Closed by monnerat** 2017-10-29 15:35 UTC
Labels: HTTP
