### ISSUE TITLE
Segmentation fault when using --proxy-negotiate --proxy-user : 

### ISSUE THREAD

**Issue by cacheguard** [curl/curl#8816] opened 2022-05-08 11:42 UTC
### I did this

Hi,
The context: password for the user foo on my kdc is foo. I'm using squid as a remote proxy.

On the client:

echo foo | kinit foo
klist # The output is OK

curl --proxy-negotiate --proxy-user : --proxy 192.168.1.254:3128 --url http://example.com

### I expected the following
The content of http://example.com as the output

BUT -- Got a Segmentation fault

### curl/libcurl version

[curl -V output] curl 7.81.0 (i686-pc-linux-gnu) libcurl/7.81.0 OpenSSL/1.1.1m zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libssh2/1.10.0 OpenLDAP/2.6.1
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets zstd

### operating system

Linux built from scratched (based on LFS 11.1-rc1)

Linux kernel 4.19.0-20-amd64

**Comment by bagder** [comment] 2022-05-08 21:14
I don't have any such proxy setup to reproduce with. Any chance you can try with the latest curl and see if it still happens? And if it does, can you post a stack trace from the crash here? (ideally of course with curl built with debug enabled so that we get more symbols shown)

**Comment by jay** [comment] 2022-05-10 07:39
> #0 0x00007ffff790fdf8 in gss_display_status () from /usr/lib/libgss.so.3
> #1 0x00007ffff7ed7740 in display_gss_error (status=0, type=2, buf=0x7fffffffde60 "An unsupported mechanism was requested. ", len=40) at curl_gssapi.c:95

It looks like it crashes in the second iteration of the loop below. When there are multiple errors in the queue gss_display_status requires the parameters remain the same to retrieve the additional errors. AFAICS that is done correctly so I don't know why the crash.

https://github.com/curl/curl/blob/1669b17d3a1a1fd824308544ca0ec02a2a4f50ea/lib/curl_gssapi.c#L86-L110

**Comment by danielgustafsson** [comment] 2022-05-10 08:11
Could it be that `gss_display_status()` returns an error and the `status_string.value` member is a null pointer? `gss_release_buffer` will have reset the value at this point so perhaps we need to check `maj_stat` for error and/or `status_string.length` for non-zero before we attempt to `msnprintf` the `status_string`?

**Comment by jay** [comment] 2022-05-11 07:06
I think it's unlikely an error is returned because in OP's trace you can see the buffer was written to. However I agree with you it's a good idea to better address what happens on error. I suggest make a PR with your patch which looks fine to me. Also status_string should be properly initialized, so that a bad pointer isn't freed on error. `gss_buffer_desc status_string = GSS_C_EMPTY_BUFFER;`.

**Comment by jay** [comment] 2022-05-14 06:48
@cacheguard #8832 has landed for safer error handling. Please try to reproduce from master.

**Comment by bagder** [comment] 2022-09-24 23:00
No response, might be fixed.

**Closed by bagder** 2022-09-24 23:00 UTC
Labels: crash, connecting & proxies, authentication

**Comment by cacheguard** [comment] 2024-07-25 14:21
Hi,

We just upgraded to the latest version and unfortunately the bug is still there. Below  some output that may help:

```
curl -V
curl 8.9.0 (x86_64-pc-linux-gnu) libcurl/8.9.0 OpenSSL/1.1.1s zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libssh2/1.10.0 nghttp2/1.48.0 OpenLDAP/2.6.2
Release-Date: 2024-07-24
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz NTLM SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

Our **curl** command is built from scratch. Below the compilation configuration we used:

```
./configure \
	    --prefix=/usr \
	    --disable-static \
	    --with-ca-bundle=/etc/ca-bundle.crt \
	    --with-openssl \
	    --with-gssapi \
	    --with-brotli \
	    --enable-ldap \
	    --enable-ldaps \
	    --with-nghttp2 \
	    --without-ngtcp2 \
	    --with-libssh2 \
            --enable-threaded-resolver
```
Is it possible that we forgot some options that produce the segmentation fault?

Best Regards,
CG

**Comment by cacheguard** [comment] 2024-07-25 14:31
Complementary information: an older curl version (see below) works without producing the segmentation fault.

```
curl -V
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1n zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06, security patched: 7.64.0-4+deb10u9
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL


```

Thanks

**Comment by bagder** [comment] 2024-07-25 21:59
@cacheguard please submit a new bug (this is already messy and reopening it will just increase the mess and confusion). And if you really want this to be fixed, we need your help and assistance. As you can see, this issue was previously closed because of a lack of response.

**Comment by cacheguard** [comment] 2024-07-25 22:50
> @cacheguard please submit a new bug (this is already messy and reopening it will just increase the mess and confusion). And if you really want this to be fixed, we need your help and assistance. As you can see, this issue was previously closed because of a lack of response.

Thank you for your response. So sorry to respond so late (yes! 2 years after is really late), but late is better than never ;-) Actually we need that curl command for testing purpose only and it's not blocking for us to don't have a fix.

I admit that creating the right testing environment shouldn't be so easy (you need a web proxy, a Kerberos server... + the right configuration to make them work together). We already sent you a debug trace and we can continue to assist in debugging this issue but on a best effort basis only.

No problem to submit a new bug but if would be a copy/paste of this one. Don't you think that it would be preferable to reopen this one (as it wasn't really fixed)?

BR
