### ISSUE TITLE
CURLOPT_RESOLVE: Add support for multiple IP addresses per entry not work as expected

### ISSUE THREAD

**Issue by codefei** [curl/curl#2827] opened 2018-08-02 06:06 UTC
### I did this
when use CURLOPT_RESOLVE option, and set multi ip address for the hosts, for example
```
struct curl_slist *host = NULL
host = curl_slist_append(host, "api.xxx.com:80:115.239.210.27");
host = curl_slist_append(host, "api.xxx.com:80:115.239.210.28");
host = curl_slist_append(host, "api.xxx.com:80:115.239.210.29");
```
libcurl will only use the last record ip, even the ip cannot be connected, don't really support multi ip.

* RESOLVE api.xxx.com:80 is - old addresses discarded!
* Added api.xxx.com:80:115.239.210.27 to DNS cache
* RESOLVE api.xxx.com:80 is - old addresses discarded!
* Added api.xxx.com:80:115.239.210.28 to DNS cache
* RESOLVE api.xxx.com:80 is - old addresses discarded!
* Added api.xxx.com:80:115.239.210.29 to DNS cache
* Found bundle for host api.xxx.com: 0x1c804d2f0 [serially]
* Hostname api.xxx.com was found in DNS cache
*   Trying 115.239.210.29...

### I expected the following
if one ip cannot connect, libcurl can auto use another ip for the host

### curl/libcurl version

[curl -V output]
cURL/7.61.0

### operating system
Mobile/15F79 ===  iOS/11.4 Model/iPhone10,3 BundleID
iphonex

**Comment by bagder** [comment] 2018-08-02 09:38
Every new line replaces the former one. I believe this is documented.

It is also documented that the way to provide multiple IP addresses for a single name is to provide them in a comma-separated list:
~~~c
host = curl_slist_append(host, "api.xxx.com:80:115.239.210.27,115.239.210.28,115.239.210.29");

**Comment by codefei** [comment] 2018-08-02 14:19
oh, it's my fault.  
Do you know curl how to use these ips？I can't find document about this.
And I test if first ip is not reachable, it will use next ip.
Since it's not bug, I will close the issue

**Comment by bagder** [comment] 2018-08-12 17:34
So, this works as intended and was just used wrongly. Closing.

**Closed by bagder** 2018-08-12 17:34 UTC
Labels: not-a-bug

**Comment by bigbrother323** [comment] 2018-08-31 03:59
host = curl_slist_append(host, "devauth2.anlian.co:4433:47.254.129.48,47.88.188.111");
I use it as you say,but occur* Resolve devauth2.anlian.co:4433:47.254.129.48,47.88.188.111 found illegal!.

**Comment by bagder** [comment] 2018-08-31 07:56
@bigbrother323 if you experience this with a current curl release, then please file a new bug and provide all the necessary details so that we can understand it and fix it!

**Comment by bigbrother323** [comment] 2018-08-31 08:27
* Resolve devauth2.anlian.co:4433:47.254.129.48,47.88.188.111 found illegal!
* STATE: INIT => CONNECT handle 0x12386e0; line 1034 (connection #-5000)
* Rebuilt URL to: https://devauth2.anlian.co:4433/
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => WAITRESOLVE handle 0x12386e0; line 1071 (connection #0)
*   Trying 47.88.188.111...
* STATE: WAITRESOLVE => WAITCONNECT handle 0x12386e0; line 1151 (connection #0)
*   Trying 47.254.130.205...
* connect to 47.88.188.111 port 4433 failed: Connection refused
*   Trying 47.254.130.205...
* connect to 47.254.130.205 port 4433 failed: Connection refused
*   Trying 47.254.129.48...
curl -V 7.61.0
operating system
win10 vs2017

**Comment by bagder** [comment] 2018-08-31 08:32
That's not filing a new issue.

**Comment by bigbrother323** [comment] 2018-08-31 09:27
@bagder So,How do I solve it.

**Comment by bagder** [comment] 2018-08-31 10:39
At the top right of this page there's a big green button that says "new issue". that's how you report a new bug.
