### ISSUE TITLE
RTSP Ip camera frame callback issue

### ISSUE THREAD

**Issue by nikitbiraj** [curl/curl#4377] opened 2019-09-19 07:41 UTC
I am trying to get frames from IP camera though rtsp command
rtsp://admin:admin12345@192.168.1.200:554/Streaming/Channels/101/

Since the camera connection is successfull, I don't see callback function to be called to get frames.
*   Trying 192.168.1.200...
* Connected to 192.168.1.200 (192.168.1.200) port 554 (#0)

Below are the settings to connect camera and get frames:

curl_easy_setopt(astCurlImgData->curl, CURLOPT_URL, "rtsp://admin:admin12345@192.168.1.200:554/Streaming/Channels/101/");

curl_easy_setopt(astCurlImgData->curl, CURLOPT_RTSP_STREAM_URI, astCurlImgData>ppaui8ConPar1[0]);

curl_easy_setopt(astCurlImgData->curl, CURLOPT_VERBOSE, 1);

curl_easy_setopt(astCurlImgData->curl, CURLOPT_RTSP_REQUEST(long)CURL_RTSPREQ_RECEIVE);

curl_easy_setopt(astCurlImgData->curl, CURLOPT_INTERLEAVEFUNCTION, interleave_callback);
curl_easy_setopt(astCurlImgData->curl, CURLOPT_INTERLEAVEDATA, (void *)astCurlImgData);

Libcurl Version : curl-7.41.0
OS WIndows 10

Any idea why there is no callback called to get frames?

Thany you

**Comment by bagder** [comment] 2019-09-20 14:53
There is not enough details to tell or for us to act on. Using this report we can't reproduce the problem. You don't tell us protocol exchange details and we don't know what server (software) this runs. You also use a libcurl version that is 4.5 years old.

**Comment by nikitbiraj** [comment] 2019-09-23 11:07
Hello,
Now I am using using curl-7.66.0 (New version)
I am trying to connect an IP camera through CURL using RTSP command rtsp://admin:admin12345@192.168.1.200:554/Streaming/Channels/101

Since camera connection is successful, why the callback is not called to fetch frames?
![CURL](https://user-images.githubusercontent.com/16545325/65420768-9c59e400-de1f-11e9-8098-93ff88c196e8.png)

Using below commands to connect camera and to call INTERLEAVE function
CURLcode curl_retval;   

astCurlImgData->curl = curl_easy_init();
if(astCurlImgData->curl)
{
	curl_easy_setopt(astCurlImgData->curl, CURLOPT_URL, astCurlImgData->ppaui8ConPar1[0]);
    curl_easy_setopt(astCurlImgData->curl, CURLOPT_RTSP_STREAM_URI, astCurlImgData->ppaui8ConPar1[0]);
	curl_easy_setopt(astCurlImgData->curl, CURLOPT_VERBOSE, 1);
	curl_easy_setopt(astCurlImgData->curl, CURLOPT_RTSP_REQUEST,(long)CURL_RTSPREQ_RECEIVE);

	curl_easy_setopt(astCurlImgData->curl, CURLOPT_INTERLEAVEFUNCTION, interleave_callback);
	curl_easy_setopt(astCurlImgData->curl, CURLOPT_INTERLEAVEDATA, (void *)astCurlImgData);for(;;)
	{
		if(CURLE_OK != (curl_retval=curl_easy_perform(astCurlImgData->curl)))
		{
			 printf("curl_retval:[%d]\n", curl_retval);
			//printf("\nCamera disconnection\n");
			PostThreadMessage(astCurlImgData->dwCurlThreadID,
					VIAN_MESSAGE_CAMERA_ERR,0,0);
			astCurlImgData->i32CamTerminteFlag = FALSE;
			
		}
	}
}

Callback:
size_t interleave_callback(void *ptr, size_t size, size_t nmemb,
                           void *userdata)
{
	 struct local *l = (struct local *)userdata;
	 printf("ïn callback\n");
         /* take care of the packet in 'ptr', then return... */
         return size * nmemb;
}

**Comment by nikitbiraj** [comment] 2019-09-26 08:20
Any reply for above issue?

**Comment by bagder** [comment] 2019-09-26 09:21
That's not a known curl problem and we can't reproduce it. What can we say? Let me know what we can do to help you debug this. It could be a curl bug. Or a server bug. Or something in between.

**Comment by nikitbiraj** [comment] 2019-09-26 10:01
Misguiding statement 
**That's not a known curl problem ??
It could be a curl bug??**

What should I infer from this?

Does CURL support RTSP of a camera to fetch frames in callback?

**Comment by bagder** [comment] 2019-09-26 10:09
Welcome to curl, an open source project written by volunteers. We provide products as-is to the best of our abilities and we rely on help, debugging and development by contributors.

You've reported an issue to this project. I respond to you about this problem, for free, about a free product about a problem I don't understand.

You have not made it possible for us to reproduce the problem and thus research it from our end. You're then left to debug it yourself (with our support from this end).

curl supports RTSP, sure. You know that. Maybe there's a problem in your use case, maybe not.

If this is not good enough, I would recommend you considering [purchasing support](https://www.wolfssl.com/products/curl/).

**Comment by nikitbiraj** [comment] 2019-09-26 10:27
I don't understand why you are not able to reproduce the problem where I am connecting a simple IP camera which has rtsp support and wrote few lines  of code to connect through curl and an CURLOPT_INTERLEAVEFUNCTION for callback.
I am just not getting HOW?

Anyways Thanks for your valuable time.

**Comment by bagder** [comment] 2019-09-26 10:48
I don't have access to any such "simple IP camera" with RTSP support and if I had, it wouldn't necessarily reproduce this problem since chances are this problem doesn't happen for everyone.

**Comment by nikitbiraj** [comment] 2019-09-26 11:06
Thanks

**Comment by bagder** [comment] 2019-12-15 11:43
Since we have no way to reproduce this, it isn't clear what to do or if this is a bug in the server or perhaps something else. It is not likely to get any further action until things change.

**Comment by nikitbiraj** [comment] 2019-12-16 04:41
Thanks for keeping the post active. 
The question is still open since I am still not able to get frames from CURL RTSP streaming protocol.

**Comment by bagder** [comment] 2020-03-30 08:16
Closing this due to lack of information.

If you can show us a way to reproduce an RTSP problem, then we can reopen this or create a new bug. Until then this is just circumstantial to us and we can't act on it.

**Closed by bagder** 2020-03-30 08:16 UTC
Labels: RTSP, needs-info-or-update
