### ISSUE TITLE
curl built with SecureTransport fails when `--cacert` or `SSL_CERT_FILE` are used

### ISSUE THREAD

**Issue by petemoore** [curl/curl#976] opened 2016-08-23 09:08 UTC
### I did this

First I download the latest version of the cacert file in pem format:

```
pmoore@Petes-iMac:~ $ curl -L https://curl.haxx.se/ca/cacert.pem > ~/cacert.pem
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  244k  100  244k    0     0   252k      0 --:--:-- --:--:-- --:--:--  252k
```

Next I try to use it with `--cacert` option using curl built with SecureTransport:

```
pmoore@Petes-iMac:~ $ /usr/local/Cellar/curl/7.50.1/bin/curl --cacert ~/cacert.pem -I https://storage.googleapis.com/golang/go1.7.src.tar.gz
curl: (51) SSL: certificate verification failed (result: 5)
```

Similar result when using environment variable `SSL_CERT_FILE`:

```
pmoore@Petes-iMac:~ $ SSL_CERT_FILE=~/cacert.pem /usr/local/Cellar/curl/7.50.1/bin/curl -I https://storage.googleapis.com/golang/go1.7.src.tar.gz
curl: (51) SSL: certificate verification failed (result: 5)
```

Note, this happens for all https urls, not just the one above.

### I expected the following

```
HTTP/1.1 200 OK
X-GUploader-UploadID: AEnB2UplWlz4rniGH-7K0_WwhXYZci9pdEYGrZDSyEwTLv9X3rgeLfEDM2NLPZdQ_9slzjYOD8jaRDtNBDnk3Onswn0M05lVIA
Expires: Tue, 23 Aug 2016 09:52:59 GMT
Date: Tue, 23 Aug 2016 08:52:59 GMT
Cache-Control: public, max-age=3600
Last-Modified: Mon, 15 Aug 2016 23:20:30 GMT
ETag: "a30c3bd1a7fcc6a48acfb74936a19b4c"
x-goog-generation: 1471303230615000
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 14091954
Content-Type: application/x-gzip
x-goog-hash: crc32c=B1onUw==
x-goog-hash: md5=oww70af8xqSKz7dJNqGbTA==
x-goog-storage-class: STANDARD
Accept-Ranges: bytes
Content-Length: 14091954
Server: UploadServer
Alternate-Protocol: 443:quic
Alt-Svc: quic=":443"; ma=2592000; v="35,34,33,32,31,30"
```

### Curl version

```
pmoore@Petes-iMac:~ $ /usr/local/Cellar/curl/7.50.1/bin/curl -V
curl 7.50.1 (x86_64-apple-darwin15.5.0) libcurl/7.50.1 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets 
```

### Operating System

Apple OS X El Capitan Version 10.11.6

```
pmoore@Petes-iMac:~ $ uname -a
Darwin Petes-iMac.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
```

### Summary

If curl is built *without* OpenSSL support, the OpenSSL parameter options and environment variables should not be supported. This causes problems when a system has more than one version of curl installed, and one requires a certificate bundle, and therefore e.g. sets the `SSL_CERT_FILE` environment variable. The version of curl that doesn't support this setting should not use it.

Please note this bug originated from NixOS/nix#921.

**Comment by layus** [comment] 2016-08-23 09:25
Also related to #492

**Comment by bagder** [comment] 2016-08-23 09:31
Related, but quite different. The *path* argument wasn't supported. The *file* argument is. Why this case doesn't work is not due to wrong things passed to libcurl by the command line tool, it is due to Secure Transport magic that doesn't work as presumed within libcurl.

**Comment by bagder** [comment] 2016-08-23 09:32
ping @nickzman for ideas

**Comment by layus** [comment] 2016-08-23 09:34
Yep, if what is described in https://docwhat.org/el-capitan-and-the-evils-of-openssl/ is right, then it has nothing to do with curl. But there is no reference for that assertion:
> SecureTransport (OS X’s replacement for OpenSSL) may fall back to using OpenSSL if the environment variable SSL_CERT_FILE is set.
We cannot be sure it is the root of the problem, even if it looks so.

**Comment by bagder** [comment] 2016-08-23 09:43
Unfortunately that blog post just adds to the "it doesn't work" choir without providing many clues as to why. It requires a dev on mac to do some digging.

But since this bug hasn't always shown, I would suspect it has something to do with the particular PEM file used. Did anyone try like an older file or bisecting exactly which parts of the file that is troublesome? 

Did anyone file a bug with Apple, since surely they have this problem in their native curl as well?

**Comment by petemoore** [comment] 2016-08-23 16:47
@bagder

> Did anyone file a bug with Apple, since surely they have this problem in their native curl as well?

I've raised __Bug 27968953__ _"SecureTransport problem causes /usr/bin/curl to fail if env var SSL_CERT_FILE is set, or --cacert option is passed"_ with the Apple Bug Reporter, against product "OS X". The content of the bug is essentially the same as the content here.

**Comment by nickzman** [comment] 2016-08-23 17:01
Okay, I took a look.

First of all, the blog above is dead wrong. Apple's libcurl uses Secure Transport exclusively; the only apps bundled with macOS that still use OpenSSL are Apache and Subversion.

The Secure Transport engine supports the --cacert option, and if it's set, then it'll translate the certificates in the bundle into their SecCertificateRef data structures, and then use the SecTrustRef API to evaluate the trust. If it's not set, then SSLHandshake() will automatically evaluate the trust using the certificates in the Keychain.

And I used the certificate bundle on the Haxx site, and was able to connect to Apple, the Washington Post, Entrust, etc. Of the sites I tested, only Google's was problematic, and I wonder if it has something to do with the server certificate in the middle...

> % curl -v https://storage.googleapis.com/
> *   Trying 2607:f8b0:4001:c02::80...
> * Connected to storage.googleapis.com (2607:f8b0:4001:c02::80) port 443 (#0)
> * TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
> * Server certificate: *.storage.googleapis.com
> * Server certificate: Google Internet Authority G2
> * Server certificate: GeoTrust Global CA

Does this work with other back-ends? I can't build the OpenSSL back-end anymore because Apple pulled the SDK a while back.

Also, in general, unless you know what you're doing, you shouldn't use the --cacert option with the Secure Transport engine. It's always better to just let the Keychain do the certificate validation; the main reason --cacert is supported in Secure Transport is for backward compatibility with software coming from GNU/Linux and other systems that need to run a shell script that accesses an HTTPS site with a self-signed certificate located in a file. If that doesn't cover your use case, then just let the Keychain do the validation.

**Comment by jay** [comment] 2016-08-23 17:13
works: OpenSSL, NSS, WinSSL, mbedTLS
doesn't: wolfSSL

wolfssl error is 'CA signer not available for verification'. might be related to wolfSSL/wolfssl#360

tried both recent files
Certificate data from Mozilla as of: Wed Apr 20 03:12:05 2016
Certificate data from Mozilla as of: Fri Apr 29 06:21:56 2016

**Comment by petemoore** [comment] 2016-08-23 17:39
The site https://akamai.bintray.com/ (used by homebrew) seems to exhibit the same problem as https://storage.googleapis.com/.

Note that you _can_ download https://homebrew.bintray.com/bottles/openssl-1.0.2h_1.el_capitan.bottle.tar.gz in a browser, so presumably the certificate chain is ok. Using curl though we get `SSL: certificate verification failed (result: 5)`.

```
pmoore@Petes-iMac:~ $ curl -L -v https://homebrew.bintray.com/bottles/openssl-1.0.2h_1.el_capitan.bottle.tar.gz
*   Trying 159.122.18.156...
* Connected to homebrew.bintray.com (159.122.18.156) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.bintray.com
* Server certificate: GeoTrust SSL CA - G3
* Server certificate: GeoTrust Global CA
> GET /bottles/openssl-1.0.2h_1.el_capitan.bottle.tar.gz HTTP/1.1
> Host: homebrew.bintray.com
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 302 
< Server: nginx
< Date: Tue, 23 Aug 2016 17:34:46 GMT
< Content-Length: 0
< Connection: keep-alive
< Location: https://akamai.bintray.com/55/55728391c10d1c33c069ef5bf3e5ca77334605ab6c1c7810b6eedc91337807c2?__gda__=exp=1471974406~hmac=31a131a1476e806cb4b79d0e20251674ddf4fe8094db56b1d78cd35b5ba44e67&response-content-disposition=attachment%3Bfilename%3D%22openssl-1.0.2h_1.el_capitan.bottle.tar.gz%22&response-content-type=application%2Fgzip&requestInfo=U2FsdGVkX1_09QbrzGkX6XThbRVcdVr9g-RzAzQS8PDVuLLqCMfC1fKoTN8-7w7_sCyr07tb9jEuI3gqlIm8W3tr3Anc-N9gfG59Zxqx91f4TcRPuBcDm1ZCX6et4-p3HEm-R0gFndjDCrI6AgTDJA
< 
* Connection #0 to host homebrew.bintray.com left intact
* Issue another request to this URL: 'https://akamai.bintray.com/55/55728391c10d1c33c069ef5bf3e5ca77334605ab6c1c7810b6eedc91337807c2?__gda__=exp=1471974406~hmac=31a131a1476e806cb4b79d0e20251674ddf4fe8094db56b1d78cd35b5ba44e67&response-content-disposition=attachment%3Bfilename%3D%22openssl-1.0.2h_1.el_capitan.bottle.tar.gz%22&response-content-type=application%2Fgzip&requestInfo=U2FsdGVkX1_09QbrzGkX6XThbRVcdVr9g-RzAzQS8PDVuLLqCMfC1fKoTN8-7w7_sCyr07tb9jEuI3gqlIm8W3tr3Anc-N9gfG59Zxqx91f4TcRPuBcDm1ZCX6et4-p3HEm-R0gFndjDCrI6AgTDJA'
*   Trying 104.108.162.43...
* Connected to akamai.bintray.com (104.108.162.43) port 443 (#1)
* SSL: certificate verification failed (result: 5)
* Closing connection 1
curl: (51) SSL: certificate verification failed (result: 5)
```

**Comment by jay** [comment] 2016-08-23 18:06
Look at the akamai.bintray.com chain:
~~~
 0 s:/C=US/ST=CA/L=Milpitas/O=JFrog Inc./OU=IT/CN=*.bintray.com
   i:/C=NL/L=Amsterdam/O=Verizon Enterprise Solutions/OU=Cybertrust/CN=Verizon Akamai SureServer CA G14-SHA2
 1 s:/C=NL/L=Amsterdam/O=Verizon Enterprise Solutions/OU=Cybertrust/CN=Verizon Akamai SureServer CA G14-SHA2
   i:/C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
 2 s:/C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
   i:/C=US/O=GTE Corporation/OU=GTE CyberTrust Solutions, Inc./CN=GTE CyberTrust Global Root
~~~

Looks pretty similar to the [akamai example in the wolfssl issue](https://github.com/wolfSSL/wolfssl/issues/360#issuecomment-200693758). Try using the GTE CyberTrust Global Root (aka DigiCert Global Root) as cacert:
```
-----BEGIN CERTIFICATE-----
MIICWjCCAcMCAgGlMA0GCSqGSIb3DQEBBAUAMHUxCzAJBgNVBAYTAlVTMRgwFgYD
VQQKEw9HVEUgQ29ycG9yYXRpb24xJzAlBgNVBAsTHkdURSBDeWJlclRydXN0IFNv
bHV0aW9ucywgSW5jLjEjMCEGA1UEAxMaR1RFIEN5YmVyVHJ1c3QgR2xvYmFsIFJv
b3QwHhcNOTgwODEzMDAyOTAwWhcNMTgwODEzMjM1OTAwWjB1MQswCQYDVQQGEwJV
UzEYMBYGA1UEChMPR1RFIENvcnBvcmF0aW9uMScwJQYDVQQLEx5HVEUgQ3liZXJU
cnVzdCBTb2x1dGlvbnMsIEluYy4xIzAhBgNVBAMTGkdURSBDeWJlclRydXN0IEds
b2JhbCBSb290MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCVD6C28FCc6HrH
iM3dFw4usJTQGz0O9pTAipTHBsiQl8i4ZBp6fmw8U+E3KHNgf7KXUwefU/ltWJTS
r41tiGeA5u2ylc9yMcqlHHK6XALnZELn+aks1joNrI1CqiQBOeacPwGFVw1Yh0X4
04Wqk2kmhXBIgD8SFcd5tB8FLztimQIDAQABMA0GCSqGSIb3DQEBBAUAA4GBAG3r
GwnpXtlR22ciYaQqPEh346B8pt5zohQDhT37qw4wxYMWM4ETCJ57NE7fQMh017l9
3PR2VX2bY1QY6fDq81yx2YtCHrnAlU66+tXifPVoYb+O7AWXX1uw16OFNMQkpw0P
lZPvy5TYnh+dXIVtx6quTx8itc2VrbqnzPmrC3p/
-----END CERTIFICATE-----
```

**Comment by bagder** [comment] 2016-08-23 18:12
Meanwhile, a friend heard my plea on twitter and filed "rdar://27967491" (apple bug number) for this case and another contact did the same(!) and said "Works on Sierra already, though."

**Comment by petemoore** [comment] 2016-08-23 20:04
Thanks all for your quick response on this issue! 👍

**Comment by bagder** [comment] 2016-08-28 17:40
Ok, this seems to identify a Secure Transport bug/problem, possibly fixed by Apple already for a pending release. Not reproducible for other TLS backends except WolfSSL but is probably a known bug (https://github.com/wolfSSL/wolfssl/issues/360) there as well.

Is there anything we can do to soften the pains or work around this flaw? It really is a bug in the TLS layer, not in curl...

**Comment by nickzman** [comment] 2016-08-28 17:52
We need to make it clear that the --cacert option should not be used with Secure Transport, except in the situation where the user is bringing over some code from some other OS to macOS that needs to connect to an HTTPS server with a self-signed certificate stored in a file. And even then, it's still a better idea to just import the certificate into the Keychain and mark it as trusted. That way, it'll work with (almost) every app that comes with macOS, and many third-party apps as well.

**Comment by jay** [comment] 2016-08-28 17:57
But what exactly is the bug, did they say? It seems like SecureTransport is not trying alternate chains with the imported certificates, but it is with its certificate store? Is there an option we can use to control that, and did Apple provide any useful information in their internal report?

**Comment by jay** [comment] 2016-08-28 17:58
My terminology may be wrong here, are the certificates not imported? I'm not sure how this works on Mac OS

**Comment by bagder** [comment] 2016-08-28 17:59
Yes, we should make that clear in the documentation.

But in the Homebrew case it seems like an obvious use case for a setup that *may* use another (OpenSSL) backend so by using --cacert both builds could've worked the same. If only the secure transport version had played ball.

@Jay wrote:

> But what exactly is the bug, did they say? 

They haven't said (that I'm aware of). I don't expect to get that information either. I'm afraid I have no direct communication with anyone working on the "inside" and they're not really known to communicate openly.

**Comment by nickzman** [comment] 2016-08-28 18:28
I've written up a clause for curl.1 and CURLOPT_CAINFO.3. Before I commit, what do you think of the following statement:

> (iOS and macOS only) If curl is built against Secure Transport, then this
> option is supported for backward compatibility with other SSL engines, but it
> should not be set. If the option is not set, then curl will use the
> certificates in the system and user Keychain to verify the peer, which is the
> preferred method of verifying the peer's certificate chain.

**Comment by bagder** [comment] 2016-08-28 21:32
👍

**Comment by nickzman** [comment] 2016-08-28 21:47
All right; the documentation change has been pushed.

**Closed by nickzman** 2016-08-28 21:47 UTC
Labels: SSL/TLS
