### ISSUE TITLE
hsts option not expanding directories in curlrc

### ISSUE THREAD

**Issue by SuperSandro2000** [curl/curl#8209] opened 2022-01-02 11:31 UTC
### I did this

I created ``~/.curlrc`` with the following content

```
hsts = ~/.curl-hsts

head
```

and then did a curl command on a host that has HSTS headers set.

### I expected the following

``~/.curl-hsts`` file being created the same way as when I do ``curl --hsts ~/.curl-hsts https://some-website-with-hsts.com/``

### What actually happened

The file is only created when hsts is supplied via the cli. It seems to be that curl is not expanding the ``~`` to the home directory. An absolute path is also not working and environment variables are also not expanded ``$HOME/.curl-hsts``.

### curl/libcurl version

```
curl 7.80.0 (x86_64-pc-linux-gnu) libcurl/7.80.0 OpenSSL/3.0.1 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.1 libpsl/0.21.0 (+libidn2/2.3.0) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.6
Release-Date: 2021-11-10
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

### operating system

```
Linux host 5.13.0-21-generic #21-Ubuntu SMP Tue Oct 19 08:59:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bagder** [comment] 2022-01-02 11:46
`~/` is never expanded in config files

**Comment by SuperSandro2000** [comment] 2022-01-02 12:24
Why is that? I would expect that it is expanded in a option that accepts a path.

**Comment by bagder** [comment] 2022-01-02 12:29
It's just not a feature anyone ever implemented.

**Comment by bagder** [comment] 2022-01-02 12:34
see also #2317

**Comment by bagder** [comment] 2022-01-02 22:09
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!

Duplicate of #2317

**Closed by bagder** 2022-01-02 22:09 UTC
Labels: cmdline tool, feature-request

**Comment by SuperSandro2000** [comment] 2022-01-03 08:12
I ended up just doing 

```
alias curl='curl --hsts ~/.curl-hsts'
```
