### ISSUE TITLE
Debug callback not preserved until libssh2.c:sftp_disconnect

### ISSUE THREAD

**Issue by ccbenny** [curl/curl#6995] opened 2021-05-03 15:28 UTC
### I did this

We are using libcurl in our in-house software.
The code uses SFTP with libssh2 via the curl_easy interface.
We are setting `CURLOPT_DEBUGFUNCTION` to get as much information as possible and record it in our own log files.
We had an unrelated bug [6990](https://github.com/curl/curl/issues/6990) that should have output an error message using `failf`.
Even after this bug is fixed and that particular call is not executed any more, there are calls to `infof` in the disconnect code that we would like to get.

### I expected the following

My debug function should have been called, but it wasn't.

### curl/libcurl version

Git master

### operating system

Debian buster, also tested on bullseye/sid.

### Initial analysis

It seems that the CURL handle (`Curl_easy` struct)  that is passed to `libssh2.sftp_disconnect` is not the same as the one used during the SFTP data transfer where we registered the debug function.  This second handle comes from `Curl_conncache_close_all_connections`.  From my debugging the struct member `set.fdebug` is set to NULL in the `Curl_easy` struct in `sftp_disconnect` instead of my configured debug callback.

**Comment by bagder** [comment] 2021-05-17 11:40
Does #7078 fix this problem as well perhaps?

**Comment by ccbenny** [comment] 2021-05-17 16:04
Daniel Stenberg writes:
> Does #7078 fix this problem as well perhaps?

That would be branch bagder/handler-attach?  No that does not seem
change this.

**Comment by bagder** [comment] 2021-05-17 16:16
Right, the issue is different. The problem is that the closing of the connection(s) at this point is done with a "closure handle" that was created entirely for the purpose of just shutting down the connections as the original transfer handle is no longer associated with the connection and is not even around anymore. Addressing this issue without introducing side-effects is complicated...

**Closed** 2021-08-14 21:33 UTC
Labels: known-issue, SCP/SFTP, libcurl API
