### ISSUE TITLE
Enable typecheck macros on clang

### ISSUE THREAD

**Issue by jeroen** [curl/curl#4038] opened 2019-06-18 12:17 UTC
I would like to use typechecking macros in the R bindings to know e.g. if a certain parameter should be a `const char*` or `curl_slist *` like this:

```c
_curl_is_slist_option(opt);
```

Currently these macros are only included for `GCC >= 4.3`: https://github.com/curl/curl/blob/6617db6a7ed322d28322896aa20bcabf3a479e7c/include/curl/curl.h#L2853-L2857

These macros are unavailable on clang which has `__GNUC_MINOR__ = 2`. However the macros seem to work fine. Should we add another condition based on `__clang__` to enable these macros?

**Comment by bagder** [comment] 2019-06-18 13:39
> Should we add another condition based on `__clang__` to enable these macros?

Seems reasonable, yes!

**Comment by jeroen** [comment] 2019-06-18 13:48
Do you remember why this was only enabled for GCC 4.3 and up? Is there a certain feature that we need? Then we can try to find the corresponding clang version. Or do you think we can enable this on clang regardless of the version?

**Comment by MarcelRaad** [comment] 2019-06-18 13:57
IIRC, I tried to enable this for clang around 2017 and it didn't compile. I probably used the default clang on Ubuntu 14.04 (via Windows Subsystem for Linux), which seems to be 3.4.

**Comment by bagder** [comment] 2019-06-18 13:57
They check for gcc 4.3 because they need that version of gcc to work. commit 7a8a20416fd7 mentions this.

I have no idea what clang versions that support or don't support this.

**Comment by bagder** [comment] 2019-06-18 14:50
It still doesn't work unmodified anyway. This is clang-8 output:
~~~
In file included from file.c:23:
In file included from ../lib/curl_setup.h:145:
In file included from ../include/curl/curl.h:2859:
../include/curl/typecheck-gcc.h:164:1: warning: unknown attribute '__warning__' ignored
      [-Wunknown-attributes]
_CURL_WARNING(_curl_easy_setopt_err_long,
^
../include/curl/typecheck-gcc.h:160:30: note: expanded from macro '_CURL_WARNING'
  static void __attribute__((__warning__(message)))                           \
                             ^
../include/curl/typecheck-gcc.h:166:1: warning: unknown attribute '__warning__' ignored
      [-Wunknown-attributes]
_CURL_WARNING(_curl_easy_setopt_err_curl_off_t,
^
../include/curl/typecheck-gcc.h:160:30: note: expanded from macro '_CURL_WARNING'
  static void __attribute__((__warning__(message)))                           \
                             ^
../include/curl/typecheck-gcc.h:168:1: warning: unknown attribute '__warning__' ignored
      [-Wunknown-attributes]
_CURL_WARNING(_curl_easy_setopt_err_string,
^
../include/curl/typecheck-gcc.h:160:30: note: expanded from macro '_CURL_WARNING'
  static void __attribute__((__warning__(message)))                           \
                             ^

**Comment by jeroen** [comment] 2019-06-18 15:25
I'm not seeing that warning with clang on MacOS (tested back until macos 10.11)

**Comment by MarcelRaad** [comment] 2019-06-18 15:28
@jeroen Maybe you have optimizations disabled? The typecheck does nothing in non-optimized builds

**Comment by jeroen** [comment] 2019-06-18 15:32
Here is [the code](https://github.com/jeroen/curl/blob/master/src/handle.c#L4-L7) that I am testing with:

```c
#include <curl/curl.h>
#ifndef __CURL_TYPECHECK_GCC_H
#include <curl/typecheck-gcc.h>
#endif
```

And further down I am using `_curl_is_slist_option()`, `_curl_is_long_option()` `_curl_is_string_option` and so on, which all seem to work on all versions I tested.

**Comment by bagder** [comment] 2019-06-18 15:50
I had to make sure I use `-O3` but then I get the same problems on my mac, using clang: `Apple LLVM version 10.0.0 (clang-1000.11.45.5)`

**Comment by jeroen** [comment] 2019-06-18 17:32
Hmm okay. But the problem does not appear if the bindings use it? For example below: 

```c
#include <curl/curl.h>
#ifndef __CURL_TYPECHECK_GCC_H
#include <curl/typecheck-gcc.h>
#endif

int main(){
	if(_curl_is_string_option(CURLOPT_POSTFIELDS)){
		printf("CURLOPT_POSTFIELDS is a string\n");
	} else {
		printf("CURLOPT_POSTFIELDS is not a string\n");
	}
}
```

And then compile with O3 with xcode:

```
jeroen$ clang -O3 test.c
jeroen$ ./a.out
CURLOPT_POSTFIELDS is not a string
```

**Comment by bagder** [comment] 2019-06-18 20:53
I get the error when compiling my test code too (still on the mac), which is a tiny source code using libcurl. Output below.

This happens because `__warning__()` is not supported by clang. Adding a line like:
~~~c
#define __warning__(x)
~~~
... removes the compiler warnings, but it also breaks the type checking functionality.

I searched and browsed a bit but I couldn't find any obvious replacement to try with instead. And in fact, even for gcc this function is basically undocumented.

~~~gcc
$ cd debug
$ clang -O3 debugit.c -I../include -lcurl
In file included from debugit.c:1:
In file included from ../include/curl/curl.h:2859:
../include/curl/typecheck-gcc.h:164:1: warning: unknown attribute '__warning__' ignored [-Wunknown-attributes]
_CURL_WARNING(_curl_easy_setopt_err_long,
^
../include/curl/typecheck-gcc.h:160:30: note: expanded from macro '_CURL_WARNING'
  static void __attribute__((__warning__(message)))                           \
                             ^
../include/curl/typecheck-gcc.h:166:1: warning: unknown attribute '__warning__' ignored [-Wunknown-attributes]
_CURL_WARNING(_curl_easy_setopt_err_curl_off_t,
^
../include/curl/typecheck-gcc.h:160:30: note: expanded from macro '_CURL_WARNING'
  static void __attribute__((__warning__(message)))                           \
                             ^
../include/curl/typecheck-gcc.h:168:1: warning: unknown attribute '__warning__' ignored [-Wunknown-attributes]
_CURL_WARNING(_curl_easy_setopt_err_string,
^

...

**Comment by jeroen** [comment] 2019-06-18 21:09
I am actually not interested in the `__warning__` stuff. What I am interested is using these macros in my bindings, that allow me to identify the type of a user-provided option at runtime

```
_curl_is_long_option()
_curl_is_off_t_option()
_curl_is_string_option()
_curl_is_postfields_option()
_curl_is_slist_option()
```

So perhaps I'll try to propose a solution to always include `<typecheck-gcc.h>`, and only make the stuff that uses `__warning__` conditional on GCC 4.2.1.

**Comment by bagder** [comment] 2019-06-18 21:18
Just be aware that we're not promising these functions as part of any libcurl ABI or API...

**Comment by jeroen** [comment] 2019-06-18 21:23
They're all macros so I guess there is only an API to worry about, no ABI :) Do you think it is likely these would break or disappear in future versions? Would you advice against using them to infer the type of an option? There is really no other good method to do this I think.

**Comment by bagder** [comment] 2019-06-18 21:29
I'm only covering my back. These functions worked exactly like this since they were introduced and I have no particular reason to believe they will change.

**Comment by jeroen** [comment] 2019-06-19 06:23
That sounds good. I've already tested it back to CentOS6 and it seems to work.

And these macro's are actively maintained? Such that the list of string / slist opts is complete enough to enforce it in my code when the user sets an option?

https://github.com/curl/curl/blob/cf35bd79bdbe7b2155c87ed5a5da7815367ec9de/include/curl/typecheck-gcc.h#L374-L385

**Comment by bagder** [comment] 2019-06-19 07:16
Barring bugs, they work! =)

**Comment by bagder** [comment] 2019-06-19 07:19
Found a bug in that list you showed, filed #4042

**Comment by bagder** [comment] 2019-12-15 11:44
The PR that worked on this got closed. This is not a bug, it is an enhancement request. Closing for now.

**Closed by bagder** 2019-12-15 11:44 UTC
Labels: build, enhancement
