### ISSUE TITLE
SSL certificate appears as expired but still active

### ISSUE THREAD

**Issue by XMegamanX** [curl/curl#5875] opened 2020-08-28 08:20 UTC
Greetings !
I cannot download a file from a server but curl failed to do it because of an expired certificate, nevertheless, which is still active. What could be the problem ?

Thanks

### I did this

curl -L -v https://my.website.com/myfile.mp4
*   Trying XX.XXX.XX.XX...
* TCP_NODELAY set
* Connected to my.website.com(XX.XXX.XX.XX) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, certificate expired (557):
* SSL certificate problem: certificate has expired
* Closing connection 0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl --insecure -vvI https://my.website.com 2>&1 | awk 'BEGIN { cert=0 } /^\* SSL connection/ { cert=1 } /^\*/ { if (cert) print }'
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: OU=Domain Control Validated; OU=Gandi Standard Wildcard SSL; CN=*.website.com
*  start date: Sep  4 00:00:00 2019 GMT
*  expire date: Nov  5 23:59:59 2020 GMT
*  issuer: C=FR; ST=Paris; L=Paris; O=Gandi; CN=Gandi Standard SSL CA 2
*  SSL certificate verify result: certificate has expired (10), continuing anyway.
* Connection #0 to host my.website.com left intact
* Closing connection 0

### I expected the following
Download the file

### curl/libcurl version

curl 7.61.1 (x86_64-koji-linux-gnu) libcurl/7.61.1 OpenSSL/1.0.2k zlib/1.2.7 libidn2/2.3.0 libssh2/1.4.3 nghttp2/1.39.2
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy Metalink 

### operating system

Linux Ubuntu 16.04 xenial xxxxx  4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment] 2020-08-28 08:59
See #5496. this is an OpenSSL bug.

**Comment by jay** [comment] 2020-08-29 03:34
If you have an actual website to reproduce this I can try but otherwise we're going to close this.

**Comment by bagder** [comment] 2020-08-30 21:01
Duplicate of #5496

**Closed by bagder** 2020-08-30 21:01 UTC
Labels: SSL/TLS, duplicate
