### ISSUE TITLE
Slow connection to localhost on Windows (happy eyeballs algo)

### ISSUE THREAD

**Issue by fdgStilla** [curl/curl#14144] opened 2024-07-10 09:03 UTC
### I did this

Simple GET to a localhost server:
```cpp
CURL* curl = curl_easy_init();
if(curl)
{
    curl_easy_setopt(curl, CURLOPT_URL, "http://localhost:9876/run");
    CURLcode res = curl_easy_perform(curl);
    if(res != CURLE_OK) fprintf(stderr, "curl_easy_perform() failed: %s\n", curl_easy_strerror(res));
    curl_easy_cleanup(curl);
}
```
The request takes about 250ms

### I expected the following

When I replace `"http://localhost:9876/run"` by `"http://127.0.0.1:9876/run"`, the request takes about 50ms.

My investigation so far:
- This issue was already raised in 2018: https://github.com/curl/curl/issues/2281 and closed by https://github.com/curl/curl/commit/6bc83044881b241857ef061a7b648738a16e408a which was just a documentation update to the known bugs.
- This known bug was removed from the documentation in 2022: https://github.com/curl/curl/commit/44e5c7e4b0204f671d0b812668905a6afa313e45, and marked as fixed by https://github.com/curl/curl/commit/1a0ebf6632f889eedd42e03db9c337e7f029cc21.
- The issue does not seem to be fixed. I don't know if it helps but when I debug get_localhost returns get_localhost6 which is the ipv6 ::1
- To fix the issue I had to do something like this:
```cpp
            if(host.find("localhost") != std::string::npos)
            {
                curl_easy_setopt(curl, CURLOPT_HAPPY_EYEBALLS_TIMEOUT_MS, 0L);
            }
```

### curl/libcurl version

curl 8.8.0

### operating system

Windows 11

**Comment by icing** [comment] 2024-07-10 09:35
If your localhost is `127.0.0.1` *and* `::1`, the ipv6 is tried first. Your local server does not seem to be listening there and neither does your OS refuse a connection on it. So curl will wait 200ms before trying the ipv4 address where your service can be reached.

Now, I am not familiar with Windows, so I do not know what expectations are. From a pure networking view, what curl does here works as designed.

**Comment by bagder** [comment] 2024-07-10 09:38
I agree with @icing. This seems to work as intended. If there's nothing listening on port 9876 on TCP/IPv6 it needs to timeout first before it attempts IPv4. Lowering the timeout to 0 of course then removes the delay, as tested.

**Comment by bagder** [comment] 2024-07-10 11:56
I think we can perhaps discuss shortening the default happy eyeballs timeout to reduce the impact, for this and other non-functioning IPv6 cases.

**Comment by bagder** [comment] 2024-07-10 11:58
Hm. Does this use case cause an immediate connection failure over IPv6 and if so, should get the IPv4 connect attempt start sooner than the 200ms timeout?

**Comment by icing** [comment] 2024-07-10 11:59
if the ipv6 failed, it should start the ipv4 attempt right away. But I do not think we have a test for that.

**Comment by bagder** [comment] 2024-07-10 12:20
I tested it like this (on Linux) and found no problem:

~~~
curl --resolve localhost:80:[ff02::11],127.0.0.1 localhost -v -o /dev/null
~~~

I also did the slightly more involved way and added two lines to my `/etc/hosts` to the same effect just to rule out that `--resolve`  would somehow change things, but it did not and that way worked equally fine.

Running the above command with `time` fives this output on my dev machine:
~~~
real    0m0.017s
user    0m0.008s
sys     0m0.008s

**Comment by fdgStilla** [comment] 2024-07-10 13:30
Before using libcurl I was using cpprestsdk and we noticed this regression when switching to libcurl, so it is weird to say that it is an intented behavior of libcurl to wait for 200ms.
I can reproduce with the curl command line in a cmd console (300ms for localhost vs 100ms for 127.0.0.1). But `curl` in powershell (an alias for Invoke-WebRequest?) takes only 150ms with localhost.

**Comment by bagder** [comment] 2024-07-10 13:44
> it is weird to say that it is an intented behavior of libcurl to wait for 200ms.

Why is it "weird"? Are you saying that the IPv6 connect attempt fails within those first 200 milliseconds? You did not show us any verbose log or other tracing output.

If it did not fail, it will start the IPv4 connect attempt after 200 milliseconds. That is how happy eyeballs work.

> I can reproduce with the curl command line in a cmd console (300ms for localhost vs 100ms for 127.0.0.1). But curl in powershell (an alias for Invoke-WebRequest?) takes only 150ms with localhost.

That probably just means that Invoke-WebRequest does not do happy eyeballs and does not add a lot to this case.

**Comment by bagder** [comment] 2024-07-10 13:54
@fdgStilla the problem is that when curl tries to connect to TCP/IPv6 on port 9876, **it does not fail** (within 200 milliseconds).

**Comment by fdgStilla** [comment] 2024-07-10 13:57
Some logs:
The command below shows that IPv6 is tried before IPv4
```
curl -v http://localhost:9876/run
* Host localhost:9876 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:9876...
*   Trying 127.0.0.1:9876...
* Connected to localhost (127.0.0.1) port 9876
```
The command below takes 2s to fail to connect to the IPv6
```
curl -v http://[::1]:9876/run
*   Trying [::1]:9876...
* connect to ::1 port 9876 from :: port 62291 failed: Connection refused
* Failed to connect to ::1 port 9876 after 2057 ms: Couldn't connect to server
* Closing connection
curl: (7) Failed to connect to ::1 port 9876 after 2057 ms: Couldn't connect to server
```
Thanks for taking the time to investigate this issue.
I am not saying that libcurl has a bug, from what you are saying I understand that libcurl uses a happy eyeballs algo that may be useful in other cases.
I am saying that compared to other libraries or tools we observe a different behavior that is silently slowing the local application on windows.
If I still want to use libcurl, what is your recommendation to correctly use it without slowing the application?

**Comment by jzakrzewski** [comment] 2024-07-10 14:08
If you don't want IPv6, you can set `CURLOPT_IPRESOLVE` to `CURL_IPRESOLVE_V4`.
It may have implications for IPv6-only hosts though.

**Comment by bagder** [comment] 2024-07-10 14:09
> I am saying that compared to other libraries or tools we observe a different behavior that is silently slowing the local application on windows.

Yes, on your specific local situation it does. It should not in most (other) cases, as there should normally not be something listening on that port just idling and doing nothing. That is an unusual scenario. (Or optionally it is curl not detecting the error case faster.)

Do you know what makes it take 2 full seconds to get the connection refused?

> what is your recommendation to correctly use it without slowing the application?

Primarily to stop whatever it is that makes it take two seconds to realize it cannot connect to IPv6 localhost. 

If you cannot do that: reducing the happy eyeballs timeout is a decent work-around unless you want to disable IPv6 completely as @jzakrzewski suggests above-

**Comment by fdgStilla** [comment] 2024-07-11 15:37
I confirm that it takes 2s to fail to reach an invalid address, for example when trying to reach 127.0.0.1 without any server running I get the following (with trace activated):
```
* [READ] client_reset, clear readers
* [SETUP] added
* [HAPPY-EYEBALLS] created ipv4 (timeout 300000ms)
* [HAPPY-EYEBALLS] ipv4 starting (timeout=300000ms)
*   Trying 127.0.0.1:9876...
* [TCP] cf_socket_open() -> 0, fd=416
* [TCP] local address 0.0.0.0 port 64612...
* [HAPPY-EYEBALLS] ipv4 connect -> 0, connected=0
* [TCP] adjust_pollset, !connected, POLLOUT fd=416
* [HAPPY-EYEBALLS] adjust_pollset -> 1 socks
* [TCP] adjust_pollset, !connected, POLLOUT fd=416
* [HAPPY-EYEBALLS] adjust_pollset -> 1 socks
* [TCP] not connected yet
* [HAPPY-EYEBALLS] ipv4 connect -> 0, connected=0
* [TCP] adjust_pollset, !connected, POLLOUT fd=416
* [HAPPY-EYEBALLS] adjust_pollset -> 1 socks
* [TCP] adjust_pollset, !connected, POLLOUT fd=416
* [HAPPY-EYEBALLS] adjust_pollset -> 1 socks
* [TCP] not connected yet
* [HAPPY-EYEBALLS] ipv4 connect -> 0, connected=0
* [TCP] adjust_pollset, !connected, POLLOUT fd=416
* [HAPPY-EYEBALLS] adjust_pollset -> 1 socks
* [TCP] adjust_pollset, !connected, POLLOUT fd=416
* [HAPPY-EYEBALLS] adjust_pollset -> 1 socks
* connect to 127.0.0.1 port 9876 from 0.0.0.0 port 64612 failed: Connection refused
* [HAPPY-EYEBALLS] ipv4 connect -> 7, connected=0
* [HAPPY-EYEBALLS] ipv4 done
* [HAPPY-EYEBALLS] all eyeballers failed
* [HAPPY-EYEBALLS] ipv4 assess started=1, result=7
* Failed to connect to 127.0.0.1 port 9876 after 2046 ms: Couldn't connect to server
* [WRITE] cw-out done
* Closing connection
* [SETUP] close
* [HAPPY-EYEBALLS] close
* [TCP] destroy
* [HAPPY-EYEBALLS] destroy
* [SETUP] destroy
```

Is it helpful?
Do you have any windows to test this behavior on your side?

**Comment by fdgStilla** [comment] 2024-07-12 13:56
@bagder Ok I finally understood why it takes 2s to fail.
This is the default behavior for any windows when using [connect](https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-connect) to a host where the the port is unused.
A very details explanation can be found [here](https://mskb.pkisolutions.com/kb/175523).
It can be reproduced with a very basic usage of connect:
```cpp
        SOCKET sock = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
        sockaddr_in clientService;
        clientService.sin_family = AF_INET;
        clientService.sin_addr.s_addr = inet_addr("127.0.0.1");
        clientService.sin_port = htons(9876);
        // takes 2s
        connect(sock, (SOCKADDR*)&clientService, sizeof(clientService));
```
And I reproduced also with a non blocking connect like curl does.

The behavior seems to be different when trying to connect with a remote host, eg jsonplaceholder.typicode.com:9876 with a unused port, then we get 21s to reach it, which seems to match the description in the link above (3 more attempts with 3 seconds, doubling each time: 3+3*2+3*2*2=21s).

So my request seems justified, it will always take 200ms to connect to a windows using localhost if the IPv6 is not using the port.
Maybe the happy eyeball algo should have a very reduced timeout in case of local address since there is no reason for the connection to fail by a timeout.

Another solution (which would be costly I guess) would be to really try the IPv4 and IPv6 in parallel instead of sequentially (like in it described [here](https://en.wikipedia.org/wiki/Happy_Eyeballs)).

**Comment by bagder** [comment] 2024-07-24 12:49
The are tried in parallel, it's just that the IPv4 attempt is started slightly delayed (by 200 milliseconds). As that is how the original happy eyeballs RFC suggested it should be done.

**Comment by bagder** [comment] 2024-08-07 18:21
This is deemed not a bug so I am closing this issue, I would love to figure out a way to make connection failures fail faster on Windows, but it seems complicated due to the behaviors in their TCP stack.

**Closed by bagder** 2024-08-07 18:21 UTC
Labels: connecting & proxies, not-a-curl-bug, Windows
