### ISSUE TITLE
Basic auth with Non-URL encoded @ sign in password in user argument breaks when curl follows relative redirects.

### ISSUE THREAD

**Issue by chastabor** [curl/curl#5949] opened 2020-09-10 17:36 UTC
### I did this
curl -i -L --HEAD --user 'user:p@ssword' https://example.org/path
HTTP/1.1 302 302
Date: Thu, 10 Sep 2020 17:06:14 GMT
Server: Apache
Content-Security-Policy: frame-ancestors *.example.org;
Location: /path/
X-UA-Compatible: IE=edge

curl: (6) Could not resolve host: ssword@example.org

### I expected the following
HTTP/1.1 302 302
Date: Thu, 10 Sep 2020 16:59:24 GMT
Server: Apache
Content-Security-Policy: frame-ancestors *.example.org;
Location: /path/
X-UA-Compatible: IE=edge

HTTP/1.1 302 302
Date: Thu, 10 Sep 2020 16:59:24 GMT
Server: Apache
Content-Security-Policy: frame-ancestors *.example.org;
Set-Cookie: JSESSIONID=A1...1; Path=/path; Secure; HttpOnly
Location: /path/index.html
X-UA-Compatible: IE=edge

HTTP/1.1 200 200
Date: Thu, 10 Sep 2020 16:59:25 GMT
Server: Apache
Content-Security-Policy: frame-ancestors *.example.org;
Set-Cookie: JSESSIONID=A1AA...2; Path=/path; Secure; HttpOnly
Content-Type: text/html;charset=UTF-8
X-UA-Compatible: IE=edge

### curl/libcurl version
curl 7.69.0 (x86_64-alpine-linux-musl) libcurl/7.69.0 OpenSSL/1.1.1d zlib/1.2.11 nghttp2/1.40.0
Release-Date: 2020-03-04
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets

### operating system
alpine:edge container on RHEL7 host

Linux 2b9cae2aaefe 3.10.0-1127.8.2.el7.x86_64 #1 SMP Thu May 7 19:30:37 EDT 2020 x86_64 GNU/Linux

Note On Ubuntu with older version of curl it successfully follows the redirects without the password defined in the user argument having to be url encoded:

uname -a
Linux my-pc 4.15.0-111-generic #112-Ubuntu SMP Thu Jul 9 20:32:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

curl -V
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

This is not an issue if the "p@ssword" in the user argument is URL encoded or if the Location header returned is a full URL with protocol like "https://example.org/path/index.html" as opposed to a relative redirect with "/path/index.html"

**Comment by bagder** [comment] 2020-09-10 17:59
I believe this might already be fixed in current master.

**Comment by bagder** [comment] 2020-09-11 08:20
@chastabor Can you try the latest curl version and confirm?

**Comment by chastabor** [comment] 2020-09-11 16:57
It is working now. I built it a alpine docker container with the latest version:
curl -V
curl 7.73.0-DEV (x86_64-pc-linux-musl) libcurl/7.73.0-DEV OpenSSL/1.1.1g
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS HTTPS-proxy IPv6 Largefile NTLM NTLM_WB SSL TLS-SRP UnixSockets

**Comment by jay** [comment] 2020-09-12 04:14
Thanks. Duplicate of jeroen/curl#224

**Closed by jay** 2020-09-12 04:14 UTC
Labels: HTTP, authentication, duplicate
