### ISSUE TITLE
CURLOPT_RESOLVE: Set multiple name not work.

### ISSUE THREAD

**Issue by ggandycong** [curl/curl#4249] opened 2019-08-21 02:27 UTC
I want to  access multiple **url** by one curl handle, so I hope that set multiple name simultaneously,but I find only last one is valid. eg:
```
HttpCurl::HttpCurl()
	:curl_handle(nullptr),fileFd(nullptr),performRetCode(CURL_LAST),
	 isNeedDeciDeEncrypt(true),encrypt(false)    
{
	curl_handle = curl_easy_init();
	curl_easy_setopt(curl_handle, CURLOPT_WRITEFUNCTION, WriteCallback);
	curl_easy_setopt(curl_handle, CURLOPT_WRITEDATA, this);

        host = curl_slist_append(NULL, "google.com:80:192.168.113.128");
	host = curl_slist_append(NULL, "example.com:80:127.0.0.1");
	curl_easy_setopt(curl_handle, CURLOPT_RESOLVE, host);
}
```
Result:
 Added example.com:80:127.0.0.1 to DNS cache.
Please give me some advice.

**Comment by jzakrzewski** [comment] 2019-08-21 05:57
If I'm not mistaken, you have to append to an existing list instead of creating a new one, so:
```c++
host = curl_slist_append(host, "example.com:80:127.0.0.1");
```

**Comment by ggandycong** [comment] 2019-08-21 06:08
> If I'm not mistaken, you have to append to an existing list instead of creating a new one, so:
> 
> ```c++
> host = curl_slist_append(host, "example.com:80:127.0.0.1");
> ```
You're right.  it work. 
Thanks you very much!

**Comment by bagder** [comment] 2019-08-21 13:06
Not a bug. Closing.

**Closed by bagder** 2019-08-21 13:06 UTC
Labels: name lookup, not-a-bug
