### ISSUE TITLE
test 1940 is consistently broken on the Cirrus CI Windows builds

### ISSUE THREAD

**Issue by bagder** [curl/curl#8920] opened 2022-05-25 21:54 UTC
Somewhat related note: test 1940 is consistently broken on the Cirrus CI Windows builds due to invalid line endings. Maybe something is written with the wrong mode there?

Generally speaking: IMHO Windows CI stability is now at a point there it makes sense to always review failures instead of ignoring them without looking at all and thinking the flakiness is the cause. 😉

_Originally posted by @mback2k in https://github.com/curl/curl/pull/8900#issuecomment-1137770369_

The test runs fine on appveyor builds. The line endings should be fine as the section is marked as text. I don't know why it happens.

**Comment by mback2k** [comment] 2022-05-26 10:13
Thanks for the analysis so far @jay , but maybe a stupid question: why are we expecting headers to terminate with LF anyway? Aren't headers normally terminated with CRLF and this is how we do it in other tests usually? Maybe this is the reason the problem only surfaces this time.

**Comment by bagder** [comment] 2022-05-26 14:33
> Does it?

No I was wrong. I must have hallucinated. The question is then why it doesn't have CRLF there since it is marked as text...

**Comment by mback2k** [comment] 2022-05-26 14:46
> > Does it?
> 
> 
> 
> No I was wrong. I must have hallucinated. The question is then why it doesn't have CRLF there since it is marked as text...

It is not marked as text as shown in @jay's screenshot.

An another information: non of the AppVeyor builds using msys are actual native Win32 cross-builds. All of them compile to the msys-specific Linux emulation layer. Only the VS builds there and the Azure Windows builds are Win32 native by cross-compiling from msys using mingw.

**Comment by bagder** [comment] 2022-05-26 21:04
> It is not marked as text as shown in @jay's screenshot.

With **marked** I mean using that property in the test case. Like this on line 50:

https://github.com/curl/curl/blob/a77d14d22ae93aa15670522e453f78744649b8cc/tests/data/test1940#L50

I think the screenshot shows the stdout data isn't treated the way that the test case tells it to.

**Comment by bagder** [comment] 2022-05-26 21:06
> And another information: non of the AppVeyor builds using msys are actual native Win32 cross-builds

But why does that matter? I seem to recall that they need the text mode set nonetheless?

**Comment by mback2k** [comment] 2022-05-26 23:17
> > It is not marked as text as shown in @jay's screenshot.
> 
> 
> 
> With **marked** I mean using that property in the test case. Like this on line 50:
> 
> 
> 
> https://github.com/curl/curl/blob/a77d14d22ae93aa15670522e453f78744649b8cc/tests/data/test1940#L50
> 
> 
> 
> I think the screenshot shows the stdout data isn't treated the way that the test case tells it to.

Interesting, then I don't understand why he showed it without the text mode on stdout above:
![image](https://user-images.githubusercontent.com/231943/170594517-caac7628-07c4-4a6e-9d84-ad25188cd265.jpeg)

**Comment by mback2k** [comment] 2022-05-26 23:20
> > And another information: non of the AppVeyor builds using msys are actual native Win32 cross-builds
> 
> 
> 
> But why does that matter? I seem to recall that they need the text mode set nonetheless?

I am pointing this out while I am not sure about its relevance, because I think this is an important distinction to keep in mind since it **could** be influencing file modes, stdout/stderr redirection and similar things.

The msys environment is basically POSIX oriented and uses LF, while mingw builds (even from msys) use CRLF.

**Comment by jay** [comment] 2022-05-28 07:45
It looks like c9b60f0 which landed 2 days ago changed the mode to text, so now it is correct that check-expected show [CR][LF] and check-generated (which is generated from lib1940) is still [LF]? 

https://github.com/curl/curl/blob/10cd69623a544c83bae6d90acdf141981ae53174/tests/libtest/lib1940.c#L57-L58

**Comment by mback2k** [comment] 2022-05-28 10:15
And I think it is generated with [LF] due to the use of the msys instead of Win32 build target environment. I guess runtest.pl needs and update to distinguish these.

**Comment by bagder** [comment] 2022-05-28 21:54
Any chance anyone of you can reproduce this locally?

**Comment by jay** [comment] 2022-05-28 22:40
I'll give it a try. The expected stdout CRLF looks correct if the target is mingw, because $has_textaware will be true

https://github.com/curl/curl/blob/462196e6b4a47f924293a0e26b8e9c23d37ac26f/tests/runtests.pl#L2994-L3001

And as Marc mentioned earlier mingw gcc should give CRLF output when \n, so the way I see it maybe msys gcc was used to compile lib1940 (the output we're comparing against) and that's why it's outputting LF only

**Comment by bagder** [comment] 2022-05-28 23:31
Even if lib1940 outputs LF only to stdout, `mode="text"` means that `runtests.pl` should convert the line endings to CRLF for this case so both files compared after the test has run (`check-expected` and `check-generated`) *should* have CRLFs, if things work as intended.

**Comment by jay** [comment] 2022-05-29 07:38
I tried to build 'shared/release Schannel/SSPI/WinIDN/libssh2' but ran into some errors.

https://github.com/curl/curl/blob/10cd69623a544c83bae6d90acdf141981ae53174/.cirrus.yml#L82-L88

First I needed packages libffi libffi-devel. Then impacket (cryptography) won't build without rust but I don't see a msys2 build of rust. That aside when I run configure in msys2 it doesn't detect it as a native windows build, but in the CI it does. Therefore things like --enable-sspi --with-schannel don't work for me. I have the right mingw headers but I guess I don't have the right msys2 headers? Marc are you able to build this configuration outside of the CI?

**Comment by mback2k** [comment] 2022-05-29 16:56
I will try to look into this tonight, but can't promise this due to our 2,5 months old child 😉

**Comment by mback2k** [comment] 2022-05-29 16:57
Side note: the Cirrus CI builds are mingw builds just like the Azure builds, but unlike the AppVeyor builds.

**Comment by mback2k** [comment] 2022-05-29 22:28
So I was able to reproduce this locally. First of all `mode="text"` only affects the "expected" part of the diff, but not the "generated" part. So the generated part stays [LF] if it is generated as such. `@actual` is not affected, only `@validstdout` is:
https://github.com/curl/curl/blob/22eab9d4132a53ffa0d6c11126a2460a9d567f64/tests/runtests.pl#L4380-L4386
https://github.com/curl/curl/blob/22eab9d4132a53ffa0d6c11126a2460a9d567f64/tests/runtests.pl#L4394

So removing `mode="text"` from the test data makes it work again. I will submit a PR to see if it brakes other platforms.

**Closed** 2022-05-30 07:24 UTC
Labels: Windows, CI
