### ISSUE TITLE
Spurious CURLE_WRITE_ERROR at transfer end with Brotli encoding

### ISSUE THREAD

**Issue by fds242** [curl/curl#13226] opened 2024-03-29 08:09 UTC
### I did this

Enabling libcurl's built-in Brotli encoding support with curl 8.7.1 results in a spurious CURLE_WRITE_ERROR at the end of transfers when using HTTP/2 or HTTP/3.
There was no such issue with curl 8.6.0 or earlier.

It's caused by these lines in `lib/content_encoding.c` in `brotli_do_write()`:
```
  if(!bp->br)
    return CURLE_WRITE_ERROR;  /* Stream already ended. */
```
A change in curl 8.7.1 is causing this function to be called with `nbytes == 0` when not using http/1.x, which is not properly handled.

Easy to reproduce with the `curl` tool:

`curl --http2 --compressed -i https://curl.se`
`curl --http3-only --compressed -i https://curl.se`

> HTTP/3 200 
> content-length: 3313
> server: nginx/1.21.1
> content-type: text/html
> [...]
> **content-encoding: br**
> 
> [...]
> `</html>`
> curl: (23) Failed writing received data to disk/application

Requires curl to be built with support for brotli and HTTP/2 or HTTP/3.
There's no error if you force HTTP/1.1, eg. `curl --http1.1 --compressed -i https://curl.se`

I changed the code in the above function like this as a workaround:
```
  if(!bp->br) {
	if (nbytes == 0)
	  return CURLE_OK;
    return CURLE_WRITE_ERROR;  /* Stream already ended. */
  }
```
But perhaps the better question is why this function is even getting called with `nbytes == 0` in the first place, and a better fix is elsewhere. If I may suggest, reusing this CURLE_WRITE_ERROR error code for Content-Encoding _decoding issues_ made me initially waste time looking in all the wrong places. A different error code or at least failf() messages would be quite helpful in future issues around here.

### I expected the following

The transfer finishing successfully with `CURLE_OK`.

### curl/libcurl version

curl 8.7.1

### operating system

macOS 14.4.1 (most likely any)

**Comment by vszakats** [comment] 2024-03-29 08:22
Thanks. The fix for this landed via #13219 / https://github.com/curl/curl/commit/b30d694a027eb771c02a3db0dee0ca03ccab7377.

Duplicate of #13212 #13209.

**Closed by vszakats** 2024-03-29 08:22 UTC
