### ISSUE TITLE
Issue with 302 direct for ipv6 .

### ISSUE THREAD

**Issue by amit1990sumit** [curl/curl#1910] opened 2017-09-22 19:37 UTC
I am facing issue while redirect to ipv6. In that case, the ipv4 stack is disabled and only support ipv6.
It looks issue in 302 redirects  If I try the call to http://localhost8/test.html gets redirected to http://127.0.0.1/test.html which is obviously wrong and fails since the IPv4 stack is disabled.

 It appears some issue in the 302 handling when the server redirects to  HTTP address that has an IPv6 address, so a redirect to something like http://[2005:538:2301::9] instead of a redirect to a domain that will point to that address and somehow, it default to 127.0.0.1 which fails. 

Here, It should not be redirected to ipv4 address if it is disabled.

Thanks,

**Comment by bagder** [comment] 2017-09-22 21:14
Can you show us the full response headers of the 302 response?

If the redirect is indeed sending the user-agent to 127.0.0.1, then that implies IPv4 and the server is to blame here, not curl.

**Comment by amit1990sumit** [comment] 2017-09-23 04:13
Thanks for the reply, Below is the full response header.

HTTP/1.1 302 Moved Temporarily
Server: nginx/1.13.3
Date: Wed, 02 Aug 2017 15:20:49 GMT
Content-Type: text/html
Content-Length: 161
Location: http://[2001:428:3801::5]:8080/
Proxy-Connection: Keep-alive

<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.13.3</center>
</body>
</html>

**Comment by bagder** [comment] 2017-09-23 15:50
I don't understand what you're saying. Can you show us the 'curl -v' output when those response headers are received by curl and how it acts incorrectly? And also, please tell us what curl version on what platform you're using (preferably by showing the `curl -V` output)

**Comment by amit1990sumit** [comment] 2017-09-23 16:53
Thanks for the reply. I don't know how to get curl -v from my app
I am using firefox browser in windows, I shared header response from Charles what you ask above and I am using curl-7.41.0.

Below I shared more detail.

 I locally configured the server to reproduce the issue. I start two instances of nginx so that from one server to another I can redirect. I disabled the ipv4 from setting in window system and enabled the ipv6 only. 
Here issue comes when I tried to redirect ipv6 address like [2005:538:2301::9]:8080 so In that case, I am getting header as
 | HTTP/1.1 302 Moved Temporarily
-- | --
Server | nginx/1.13.3
Date | Wed, 02 Aug 2017 15:06:07 GMT
Content-Type | text/html
Content-Length | 161
**Location | http://[2001:428:3801::5]:8080/test.html**
Proxy-Connection | Keep-alive

So it should move to [2001:428:3801::5]:8080/test.html but somehow it picked 127.0.0.1/test.html and it fails because the ipv4 stack is disabled. Also observed one more thing that it is working fine in chrome but not working for firefox, chrome or ie.

I do not understand why it picks 127.0.0.1 when 302 redirect.

Thanks again,

**Comment by bagder** [comment] 2017-09-23 21:41
I can't reproduce this issue (although I've only tried with recent curl versions). When I replay your exact set of headers, curl picks the IPv6 address from the `Location:` just fine and tries to use it - which fails if IPv6 doesn't work on the machine.

**Comment by amit1990sumit** [comment] 2017-09-24 05:27
Thanks for the reply.
Did you also disable ipv4 in ur machine?

**Comment by bagder** [comment] 2017-09-24 09:57
No I didn't disable IPv4 on my test machine, as I can't access internet without it. No I didn't try Firefox on it since it doesn't seem related.

I suggest you enable `CURLOPT_VERBOSE` in your program and see what it tells you about the redirect and the address(es) libcurl tries to use.

**Comment by amit1990sumit** [comment] 2017-09-24 12:02
Sure, I will update with CURLOPT_VERBOSE.
Thanks again.

**Comment by bagder** [comment] 2017-10-02 15:17
Thanks a lot for your report!

I've failed to reproduce this problem myself, so can I ask you to provide us with more details from your runs so that we can better understand what you're seeing. Without added details we can't work on this.

**Comment by amit1990sumit** [comment] 2017-10-04 12:09
Thanks for the reply, could you please put the issue on hold for some time.

**Comment by bagder** [comment] 2017-10-04 12:21
Thanks, I'll even close it for now. If you find out and can report additional details, just come back with it and we can open it again.

**Closed by bagder** 2017-10-04 12:21 UTC
Labels: HTTP

**Comment by amit1990sumit** [comment] 2017-10-04 13:23
Sure, Thanks
