### ISSUE TITLE
--compressed fails with error 23

### ISSUE THREAD

**Issue by finkjsc** [curl/curl#13212] opened 2024-03-27 21:37 UTC
### I did this

curl --compressed -o "test.txt" "https://www.troyhunt.com/rss/"

### I expected the following

Output file to be written without error, but fails with error 23: Failed writing received data to disk/application.

Oddly the file is written correctly but still the error persists.

Works without --compressed.

Most other URL's work, but many now fail with this error.

Versions before 8.7.1 worked without this error.

### curl/libcurl version

curl 8.7.1 (x86_64-w64-mingw32) libcurl/8.7.1 LibreSSL/3.8.3 zlib/1.3.1 brotli/1.1.0 zstd/1.5.5 WinIDN libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.60.0 ngtcp2/1.4.0 nghttp3/1.2.0
Release-Date: 2024-03-27
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL SSPI threadsafe UnixSockets zstd

### operating system

Windows 10 Pro 22H2

**Comment by dfandrich** [comment] 2024-03-27 21:50
This may be a duplicate of #13209

**Comment by icing** [comment] 2024-03-28 10:11
Please see #13219 for a fix.

**Closed** 2024-03-28 15:22 UTC
