### ISSUE TITLE
ruby/curb test fails on Fedora 40 on 32bit

### ISSUE THREAD

**Issue by mtasaka** [curl/curl#14272] opened 2024-07-25 12:18 UTC
### I did this

On Fedora 40 and rawhide, ruby/curb test_download_bad_url_gives_404 testsuite:
https://github.com/taf2/curb/blob/13144ec5d50ffea0460298cc5de8a0b33db78d22/tests/tc_curl_download.rb#L64
fails **on i686** like:

```
Error: test_download_bad_url_gives_404(TestCurbCurlDownload): Curl::Err::GotNothingError: Server returned nothing (no headers, no data): Empty reply from server
/builddir/build/GIT/curb/lib/curl/easy.rb:80:in `perform'
/builddir/build/GIT/curb/lib/curl/easy.rb:462:in `download'
/builddir/build/GIT/curb/tests/tc_curl_download.rb:68:in `test_download_bad_url_gives_404'
     65:     dl_url = "http://127.0.0.1:9129/this_file_does_not_exist.html"
     66:     dl_path = File.join(Dir::tmpdir, "dl_url_test.file")
     67: 
  => 68:     curb = Curl::Easy.download(dl_url, dl_path)
     69:     assert_equal Curl::Easy, curb.class
     70:     assert_equal 404, curb.response_code
     71:   ensure
```

... but succeeds on all other **64bit** architecture.

Git bisect shows that this test failure starts from https://github.com/curl/curl/commit/e492c7c524263e47844ec9354102fcf200e686a8 .

Looking at https://github.com/curl/curl/blob/e492c7c524263e47844ec9354102fcf200e686a8/lib/transfer.c#L451-L458 :
with the above test_download_bad_url_gives_404 testsuite, at the line 452, dumping values shows:

`max_recv_speed[68719476736] total_received[0] bytestoread[16384]`
`data->set.max_recv_speed = 68719476736 = 1ULL << 36;` 

Here on 32 bit `curl_off_t == long long`,  but `size_t == unsinged long (32bit)`, so `(size_t)net_limit` is now 0, so `bytestoread` is now set to 0, and this seems to the cause of the failure.

### I expected the following

No test failure

### curl/libcurl version

Okay curl 8.5.0
Fail: curl 8.6.0: as written above failure begins with https://github.com/curl/curl/commit/e492c7c524263e47844ec9354102fcf200e686a8 

### operating system

Fedora 40 / rawhide i686

**Comment by mtasaka** [comment] 2024-07-25 12:20
Something like the following is needed:

```
diff --git a/lib/transfer.c b/lib/transfer.c
index 59a3f05cb..0f6c6c33b 100644
--- a/lib/transfer.c
+++ b/lib/transfer.c
@@ -453,6 +453,8 @@ static CURLcode readwrite_data(struct Curl_easy *data,
       curl_off_t net_limit = data->set.max_recv_speed - total_received;
       if(net_limit <= 0)
         break;
+      if (net_limit > SIZE_MAX)
+        net_limit = SIZE_MAX;
       if((size_t)net_limit < bytestoread)
         bytestoread = (size_t)net_limit;
     }
```

**Comment by icing** [comment] 2024-07-26 08:41
Thanks @mtasaka for the report. I made #14277 as a fix for this, a slight alteration of your proposed patch. Would like to know if this works for you as intended.

**Comment by mtasaka** [comment] 2024-07-26 11:43
#14277 works as expected, rubygem-curb test failure on i686 is  resolved with the PR, thank you.

**Closed** 2024-07-26 22:01 UTC
