### ISSUE TITLE
OpenSSL 1.1.0b crashes my app on exit, because OPENSSL_cleanup() is called too late!

### ISSUE THREAD

**Issue by nased0** [curl/curl#1055] opened 2016-10-05 12:28 UTC
### I did this
I closed my application. My app crashes on exit every time if compiled (by C++ Builder) with OpenSSL 1.1.0b library, works correctly if compiled with OpenSSL 1.0.2j.
My application consists of main exe and communications module dynamically loaded by LoadLibrary. Only comm. module uses OpenSSL and curl dll's (linked by linker using lib files created from dlls by implib -a ). 
Unloading the comm. module (by FreeLibrary) doesn't crash my app, only exiting from the main exe program does.
I took screenshot of this crash under WinDbg:
http://images84.fotosik.pl/59/5b151fd6d0982b81.png

### I expected the following
Application closed correctly.
### curl/libcurl version
curl 7.50.3 (i386-pc-win32) libcurl/7.50.3 OpenSSL/1.1.0b zlib/1.2.8 WinIDN
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS TrackMemory IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz
### operating system
Windows 7 Professional x64

OPENSSL_Cleanup() function is called by setting the exit callback function by atexit.
https://msdn.microsoft.com/en-us/library/tze57ck3.aspx

![openssl_1_1_crash](https://cloud.githubusercontent.com/assets/13164219/19112933/b790a81c-8b07-11e6-916f-2bfd126ba102.png)

Unfortunately OpenSSL_cleanup() was called at the wrong time, because OpenSSL libraries were unloaded earlier along with my comm. dll library and variable lasthandler invalidated, so OPENSSL_free(lasthandler) crashed.

My solution is to call OPENSSL_cleanup() after curl_global_cleanup() in function DllEntryPoint of my comm. library. 
But in my opinion  OPENSSL_cleanup() should be called by curl_global_cleanup() and the exit callback function removed.
Edit:
It is impossible to "undo" atexit !
http://stackoverflow.com/questions/2310673/can-i-undo-or-remove-an-atexit-command

**Comment by bagder** [comment] 2016-10-06 07:12
I don't understand. Your application calls `OPENSSL_cleanup()` (for some reason) and that causes a crash. How is that libcurl's fault? Can you help explain what I'm missing here?

The final cleanup call to make with libcurl is `curl_global_cleanup` and that will cleanup OpenSSL on libcurl's behalf.

**Comment by nased0** [comment] 2016-10-06 07:17
My application doesn't crash when I call OPENSSL_cleanup() at DllEntryPoint.
It crashes when I don't do that and OPENSSL_cleanup() is called at process exit by a callback set by atexit(OPENSSL_cleanup) in openssl-1.1.0b\crypto\init.c, because my communications dll and its OpenSSL are unloaded from memory at this time!
`DEFINE_RUN_ONCE_STATIC(ossl_init_base)
{
#ifdef OPENSSL_INIT_DEBUG
    fprintf(stderr, "OPENSSL_INIT: ossl_init_base: Setting up stop handlers\n");
#endif
    /*
     * We use a dummy thread local key here. We use the destructor to detect
     * when the thread is going to stop (where that feature is available)
     */
    CRYPTO_THREAD_init_local(&threadstopkey, ossl_init_thread_stop_wrap);
#ifndef OPENSSL_SYS_UEFI
    atexit(OPENSSL_cleanup);
#endif
    if ((init_lock = CRYPTO_THREAD_lock_new()) == NULL)
        return 0;
    OPENSSL_cpuid_setup();
    base_inited = 1;
    return 1;
}`

**Comment by bagder** [comment] 2016-10-06 07:22
Thanks for the clarification! Still, the [OpenSSL docs](https://www.openssl.org/docs/man1.1.0/crypto/OPENSSL_init_crypto.html) say

> Developers of libraries using OpenSSL are discouraged from calling this function and should instead, typically, rely on auto-deinitialisation. This is to avoid error conditions where both an application and a library it depends on both use OpenSSL, and the library deinitialises it before the application has finished using it.

So it seems libcurl shouldn't call that function in any case!?

**Comment by nased0** [comment] 2016-10-06 07:26
Well, this auto-deinitialisation works incorrectly in my case.

**Comment by bagder** [comment] 2016-10-06 07:29
It looks like that, but that's done by OpenSSL itself, not libcurl. I don't see what we can do about this. Can you?

**Comment by nased0** [comment] 2016-10-06 07:34
If OPENSSL_cleanup() was called by curl_global_cleanup(), second call at process exit will execute, but the flag stopped will be set to 1 and the function will return without crash.
`void OPENSSL_cleanup(void)
{
    OPENSSL_INIT_STOP *currhandler, *lasthandler;
    /* If we've not been inited then no need to deinit */
    if (!base_inited)
        return;

    /* Might be explicitly called and also by atexit */
    if (stopped)
        return;
    stopped = 1;`

**Comment by bagder** [comment] 2016-10-06 07:52
You're then advocating acting exactly like the docs explicitly tells us not to do. It would effectively kill applications where OpenSSL is used outside of libcurl after `curl_global_cleanup()` is called.

**Comment by nased0** [comment] 2016-10-06 08:01
You are right, I haven't considered such case.
It is OpenSSL 1.1 fault. I'd like to note that the OPENSSL_cleanup code in my case refers to the deallocated memory at exit's callback!

**Comment by jay** [comment] 2016-10-07 05:11
What is the bug here? OpenSSL using atexit? When FreeLibrary is called on the OpenSSL DLL and the refcount reaches 0 the CRT is [supposed to](https://msdn.microsoft.com/en-us/library/988ye33t.aspx) call atexit before the the library is actually freed:

> process detach: the run-time library code calls DllMain with process detach selected and then calls a list of termination functions, including **atexit** functions, destructors for the global objects, and destructors for the static objects.

(See openssl/openssl#653 and openssl/openssl#654 for background)

**Comment by nased0** [comment] 2016-10-07 07:12
I'm using C++ Builder 10.1 to compile both main exe and communications dll , that has curl and openssl dlls linked (by lib stubs).
Unfortunately atexit callback is not called when my communications dll is freed (by FreeLibrary), only when the main executable terminates. I checked it by putting beep command at the beginning of OPENSSL_cleanup in OpenSSL library (and of course removing my call to OPENSSL_cleanup at DllEntryPoint). Program does not beep when I unload my communications library, only when exe terminates, then crashes.
It may be a bug in C++ Builder runtime. I tried both "classic" compiler and new clang compiler, with the same result.

**Comment by jay** [comment] 2016-10-07 17:50
This sounds like an issue that should be reported to OpenSSL. Can you reproduce without using the libcurl DLL?

**Comment by nased0** [comment] 2016-10-07 18:25
I think so, libcurl dll is used to initialize OpenSSL, so I can initialize it by myself in the same way.
But I only have access to C++ Builder 10.1 at work, so I should be able to do it in the next week.
IMO it should be reported to Embarcadero.

**Comment by jay** [comment] 2016-10-07 19:08
> IMO it should be reported to Embarcadero.

Yeah you're right, I didn't realize they don't use Microsoft's CRT. In that case I would try to eliminate both DLLs from the issue. Make your own DLL with function foo and from it call atexit(foo) and see if the function is called on FreeLibrary or program exit. Closing for now since this does not appear to be curl related.

**Closed by jay** 2016-10-07 19:08 UTC
Labels: SSL/TLS

**Comment by dot-asm** [comment] 2016-10-10 14:04
> communications dll , that has curl and openssl dlls linked (by lib stubs).

Question is how was "openssl dll" compiled? Key question is where does atexit as it's seen by OpenSSL dll come from. Normally, i.e. with either of *supported* configurations, it comes from CRT capable of calling handlers upon FreeLibrary.

> IMO it should be reported to Embarcadero.

Well, formally atexit implementation that doesn't execute handlers on FreeLibrary doesn't actually violate standard. But I'd like to hear what would they say. And yeah, this also means that one can blame OpenSSL for relying on implementation-specific behaviour...

Sorry about crashing the thread. I would contact @nased0 directly if a public address was available. Further communications should take place elsewhere...

**Comment by nased0** [comment] 2016-10-10 17:19
Curl and OpenSSL dlls were compiled with Visual Studio 2015, lib files for them were generated by commands:
implib -a libcurle-1_1.lib libcurl.dll
implib -a libcryptoe-1_1.lib libcrypto-1_1.dll 
implib -a libssle-1_1.lib libssl-1_1.dll

Lib files were linked with communications dll by Embarcadero c++ builder compiler pragmas in one of its cpp files:
#pragma comment(lib, "libcurle-1_1.lib")
#pragma comment(lib, "libcryptoe-1_1.lib")

**Comment by t-j-h** [comment] 2016-10-11 01:03
@dot-asm @mattcaswell

That atexit on linux is invoked on shared library unload is actually platform-specific behaviour and noted as such in the documentation (where in this case we are talking about a glibc enhancement which was put in place). The Microsoft Windows SDK at https://msdn.microsoft.com/en-us/library/tze57ck3.aspx (the latest) does not state that anything occurs on FreeLibrary so in this context the usage within OpenSSL is in error. Microsoft Windows is a supported platform and the assumption within the code is incorrect. The Microsoft specific extension _onexit is closer to the behaviour - see https://msdn.microsoft.com/en-us/library/zk17ww08.aspx

There is also the issue of a shared library using OpenSSL as well as an application using OpenSSL needing to make sure that the shared library unloading doesn't break things for the application (or any other shared library) that is also using OpenSSL.
