### ISSUE TITLE
Segmentation fault on some request

### ISSUE THREAD

**Issue by pizdjuk** [curl/curl#8055] opened 2021-11-25 00:15 UTC
### I did this

 curl -F "file=t.tmp" http://0x0.st

### I expected the following

Upload a file

### curl/libcurl version

curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

### operating system

Linux localhost 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment] 2021-11-25 07:18
Tip: add `-v`  to that command line and you'll see that `Segmentation fault` is the response from the server. Not a curl crash. This is not a bug.

**Comment by bagder** [comment] 2021-11-25 07:51
Duplicate of #2427

**Closed by bagder** 2021-11-25 07:51 UTC
Labels: HTTP, not-a-bug
