### ISSUE TITLE
Crash in ossl_new_session_cb() with null data pointer

### ISSUE THREAD

**Issue by bnason-nf** [curl/curl#4141] opened 2019-07-22 17:47 UTC
Hi,

I'm getting a crash in Curl when I drive it through OpenSSL, and it ends up hitting the Curl ossl_new_session_cb() function with a null data pointer. I'm not sure that this isn't my mistake, but in any case, would it be reasonable to avoid the crash like this?

```
diff --git a/lib/vtls/openssl.c b/lib/vtls/openssl.c
index fb9f27123..934c71a74 100644
--- a/lib/vtls/openssl.c
+++ b/lib/vtls/openssl.c
@@ -2250,6 +2250,8 @@ static int ossl_new_session_cb(SSL *ssl, SSL_SESSION *ssl_sessionid)
     return 0;

   data = conn->data;
+  if (!data)
+    return 0;

   /* The sockindex has been stored as a pointer to an array element */
   sockindex_ptr = (curl_socket_t*) SSL_get_ex_data(ssl, sockindex_idx);
```

Thanks,
Benbuck

**Comment by danielgustafsson** [comment] 2019-07-22 19:49
Wouldn't that just be a way to paper over bad code?

**Comment by bnason-nf** [comment] 2019-07-22 20:03
Hi @danielgustafsson,

I agree with your sentiment, and I will be investigating my code to fix whatever the real issue is. At the same time, it seems undesirable for Curl to crash in this scenario when it can trivially protect itself.

Thanks,
Benbuck

**Comment by danielgustafsson** [comment] 2019-07-22 21:07
My concern is that a caller will be unable to distinguish this error from `conn` being NULL, and those are two different things. Also, even if we protect this callsite, won't it simply crash fractions of a second later somewhere else in case data is NULL? And if it doesn't, that seems like a treasure chest for subtle bugs.

**Comment by bnason-nf** [comment] 2019-07-22 21:53
Hi @danielgustafsson,

I'm not familiar enough with this code to say whether there is a significant distinction between adding a null pointer check for data, compared to the existing null pointer check for conn immediately above it. Is that behavior different with your understanding? For what it's worth, with the null data check it doesn't crash. Also, it seems harmless to not cache the session in any situation, right?

Thanks,
Ben

**Comment by jay** [comment] 2019-07-22 22:41
If you're threading please follow [thread safety guidelines](https://curl.haxx.se/libcurl/c/threadsafe.html). Please try the latest version of curl 7.65.3. If you still have the issue after both of those things then please give us your curl_version() and a minimal self-contained example that can be used to reproduce.

**Comment by bnason-nf** [comment] 2019-07-23 00:30
Hi @jay,

Yes, this could easily be a threading issue, but I am using 7.65.3. I probably won't have time to put together a nice repro until next week, so I'll follow up here later.

Thanks,
Ben

**Comment by bnason-nf** [comment] 2019-08-21 20:27
Hi,

I'm finally getting around to digging into this a bit more today. The change in behavior that is leading to a crash was (re-)introduced in commit e3a53e3efb942a5446a22725340e36af63f1632e. Specifically, the line in `Curl_conncache_return_conn()` that sets `conn->data = NULL` was added.

Our code is using curl in a non-conventional way, and in particular for this crash it looks like us enabling `CURLOPT_CONNECT_ONLY` is problematic.

This simple patch fixes the crash for us, but I'm not sure it's the best solution:

```
diff --git a/lib/multi.c b/lib/multi.c
index 2b6b1bc52..67a3553a3 100644
--- a/lib/multi.c
+++ b/lib/multi.c
@@ -625,7 +625,7 @@ static CURLcode multi_done(struct Curl_easy *data,
     if(!result && res2)
       result = res2;
   }
-  else {
+  else if (!data->set.connect_only) {
     char buffer[256];
     /* create string before returning the connection */
     msnprintf(buffer, sizeof(buffer),
```
Any thoughts on this?

Thanks,
Benbuck

**Comment by bagder** [comment] 2019-08-23 13:03
I'm not super thrilled with this proposed change. The code flow there *either* kills the connection *or* stores in the connection cache. With your proposed change you introduce a third way and that's.... just  leave it ?

> it looks like us enabling CURLOPT_CONNECT_ONLY is problematic.

But how is it problematic? Please show with a stand-alone example that shows how it is problematic and then we can work on a fix that we all agree is a good one!

**Comment by bnason-nf** [comment] 2019-08-23 16:57
Hi @bagder,

I think in essence we are seeing the connection get reused by `multi_done()`, which breaks the promise in the documentation for CURLOPT_CONNECT_ONLY which says:

> Transfers marked connect only will not reuse any existing connections and connections marked connect only will not be allowed to get reused.

If this still doesn't make sense to you I will try to put together a simple repro case.

Thanks,
Benbuck

**Comment by bagder** [comment] 2019-08-26 09:50
> we are seeing the connection get reused by multi_done(), which breaks the promise in the documentation for CURLOPT_CONNECT_ONLY

Can you walk me through how that happens? You're first making a "regular" transfer to a host and then you set `CURLOPT_CONNECT_ONLY` to make a second one, and that request is then reusing the former already existing connection contrary to the docs?

**Comment by bnason-nf** [comment] 2019-08-30 00:26
Hi @bagder:

We are using Curl to create a secure WebSocket connection with CURLOPT_URL=https://the.url, CURLOPT_CONNECT_ONLY=1, and CURLOPT_SSL_CTX_FUNCTION=sslContextCallback.

This is the call stack just prior to that crash that sets conn->data=NULL:

```
curl: Curl_conncache_return_conn(connectdata* conn)
curl: multi_done(Curl_easy* data, CURLcode status, bool premature)
curl: multi_runsingle(Curl_multi* multi, curltime now, Curl_easy* data)
curl: curl_multi_perform(Curl_multi* multi, int* running_handles)
(application code)
```

This is the call stack for the crash itself:

```
curl: ossl_new_session_cb(SSL* ssl, SSL_SESSION* ssl_sessionid)
openssl: ssl_update_cache(SSL* s, int mode)
openssl: tls_process_new_session_ticket(SSL* s, PACKET* pkt)
openssl: ossl_statem_client_process_message(SSL* s, PACKET* pkt)
openssl: read_state_machine(SSL* s)
openssl: state_machine(SSL* s, int server)
openssl: ossl_statem_connect(SSL* s)
openssl: ssl3_read_bytes(SSL* s, int type, int* recvd_type, unsigned char* buf, size_t len, int peek, size_t* readbytes)
openssl: ssl3_read_internal(SSL* s, void* buf, size_t len, int peek, size_t* readbytes)
openssl: ssl3_read(SSL* s, void* buf, size_t len, size_t* readbytes)
openssl: ssl_read_internal(SSL* s, void* buf, size_t num, size_t* readbytes)
openssl: SSL_read(SSL* s, void* buf, int num)
(application code)
```

The crash is because ossl_new_session_cb() doesn't expect conn->data to be null, but Curl_conncache_return_conn() sets it to null. So one way to avoid this crash is to add the null check in my original description.

Another way we found to avoid this crash is by disabling the OpensSSL session callback from within the Curl SSL context callback:

```
SSL_CTX_sess_set_new_cb(ctx, NULL);
```

This is an acceptable workaround for us, but it seems like the first call stack should never happen, since Curl adding this connect only connection back to the connection cache seems to go against the statement in the documentation that says this type of connection isn't allowed to be reused. Unless maybe we are misunderstanding the documentation?

Thanks,
Benbuck

**Comment by bagder** [comment] 2019-08-30 14:18
> Curl adding this connect only connection back to the connection cache seems to go against the statement in the documentation

Absolutely, it makes no good there since no subsequent connection should reuse it anyway! How about forcing it to get disconnected in `multi_done`, like this?

~~~diff
diff --git a/lib/multi.c b/lib/multi.c
index 37c4e55a5..4c6d7e4bf 100755
--- a/lib/multi.c
+++ b/lib/multi.c
@@ -605,11 +605,11 @@ static CURLcode multi_done(struct Curl_easy *data,
      state it is for re-using, so we're forced to close it. In a perfect world
      we can add code that keep track of if we really must close it here or not,
      but currently we have no such detail knowledge.
   */
 
-  if((data->set.reuse_forbid
+  if(((data->set.reuse_forbid || data->set.connect_only)
 #if defined(USE_NTLM)
       && !(conn->http_ntlm_state == NTLMSTATE_TYPE2 ||
            conn->proxy_ntlm_state == NTLMSTATE_TYPE2)
 #endif
 #if defined(USE_SPNEGO)

**Comment by bnason-nf** [comment] 2019-09-03 17:38
Hi @bagder,

I may be misunderstanding the API, but I don't see how the CURLOPT_CONNECT_ONLY option would be useful with that change, since it would close the socket before we got a chance to use it, right? Is there a way to keep the socket open for us to use, but not put it back into the connection cache?

Thanks,
Benbuck

**Comment by bagder** [comment] 2019-09-04 06:22
Ha, right of course. I don't know what I was thinking. It of course needs to be held open to be able to get extracted and used by the application...

> Is there a way to keep the socket open for us to use, but not put it back into the connection cache?

No. I think it has to be put into the connection cache so that it can be disconnected and killed properly later...

**Comment by bagder** [comment] 2019-09-04 09:47
So back to reproducing. I can use [sendrecv.c](https://curl.haxx.se/libcurl/c/sendrecv.html) as-is without problems. Can you figure out what I need to do to reproduce the crash?

**Comment by pps83rbx** [comment] 2019-09-09 19:43
I think it would be easier just to add an example that shows libcurl users how to properly upgrade and use connection freely (similarly to websokets).

**Comment by bagder** [comment] 2019-09-10 05:58
Easier for whom and to do what? I haven't seen this bug trigger so I'm at loss what it takes to happen. As for using sockets libcurl creates, doesn't sendrecv.c show this already?

But please, if you can think of an example that we're missing please write it up and file a PR and I'll be more than happy to add it!

**Comment by pps83rbx** [comment] 2019-09-10 06:21
> But please, if you can think of an example that we're missing please write it up and file a PR and I'll be more than happy to add it!

I'm looking for one myself :) Is that the best way how to do websocket establishment using libcurl? This example simply does connect, as I understand, there are some other approaches others suggested in mailing list or that's the recommended way?

**Comment by bagder** [comment] 2019-09-10 13:10
> that's the recommended way?

Please ask questions on the curl-library mailing list. This issue discusses a crash so anything that isn't related to this crash is off-topic.

**Comment by bnason-nf** [comment] 2019-09-10 15:20
Hi all,

Sorry for the delay on this, we are trying to put together a simple repro case, but it's not our highest priority so it's taking us some time. We hope to be able to provide something useful soon.

Thanks,
Benbuck

**Comment by bagder** [comment] 2019-12-15 11:41
No activity for a long time: closing. The recent changes for connect-only connections might also change the nature of this.

**Closed by bagder** 2019-12-15 11:41 UTC
Labels: SSL/TLS, crash, needs-info-or-update
