### ISSUE TITLE
wrong handling of broken IPv6

### ISSUE THREAD

**Issue by buzo-ffm** [curl/curl#3585] opened 2019-02-18 19:42 UTC
Curl behaves differently than before when a site cannot be reached via IPv6, but only IPv4. This causes network-manager (using libcurl) to loop forever and take 100% of one CPU. Please see https://bugs.archlinux.org/task/61688 for all the details.

In that report, it is stated that the change https://github.com/curl/curl/commit/4c35574bb785ce44d72db5483541c9da2d885705 is the cause, see comment https://bugs.archlinux.org/task/61688#comment177215 .

**Comment by buzo-ffm** [comment] 2019-02-18 19:46
The bug report for network-manager about this issue is here: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/issues/123

**Comment by bagder** [comment] 2019-02-18 22:09
I *think* this problem (even if this report is doing a lot of wild guessing and drawing funny conclusions) is already addressed in git with 4015fae044ce52, since it seems similar to the symptoms in #3542.

**Comment by heftig** [comment] 2019-02-19 08:34
We backported that commit and the one it fixes without success.

**Comment by bagder** [comment] 2019-02-19 08:42
Can you make a standalone libcurl-using example that reproduces the problem?

**Comment by bagder** [comment] 2019-02-19 09:09
And maybe try the git master version in its entirety first to make sure that the problem is still there.

**Comment by buzo-ffm** [comment] 2019-02-19 09:18
The libcurl-using code is [here](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/blob/master/src/nm-connectivity.c) within the _#if WITH_CONCHECK_ blocks, but I don't know how to make a standalone example from it.

**Comment by heftig** [comment] 2019-02-19 09:20
The problem is still present as of commit 5908e900b.

FTR, the URL in question here is http://www.archlinux.org/check_network_status.txt, so http2 is not involved.

**Comment by heftig** [comment] 2019-02-19 09:22
@buzo-ffm NM's connectivity code had lots of changes in master; we're actually running https://gitlab.freedesktop.org/NetworkManager/NetworkManager/blob/nm-1-14/src/nm-connectivity.c .

**Comment by bagder** [comment] 2019-02-19 09:25
The title says "wrong handling" of "broken IPv6". In what way is it broken?

**Comment by heftig** [comment] 2019-02-19 09:28
I have a working IPv4 and IPv6 setup here; dropping all IPv6 packets from www.archlinux.org (via `ip6tables -A INPUT -s 2a01:4f8:172:1d86::1/128 -j DROP`) makes NM enter an infinite loop once it attempts to retrieve the URL.

**Comment by bagder** [comment] 2019-02-19 09:33
If you, on the same machine with that filter enabled, run `curl -v http://www.archlinux.org/check_network_status.txt` (built from the problematic commit), what happens then?

**Comment by heftig** [comment] 2019-02-19 09:36
It runs fine, first trying IPv6 and quickly failing, then using IPv4. With `-6` it times out after two minutes.

**Comment by bagder** [comment] 2019-02-19 10:12
Unfortunately my dev machines don't have working IPv6 so I can't easily reproduce this setup.

With a debug build created with `configure --enable-debug`, the curl command line tool gets an undocumented new option called `--test-event` that will make it run its normal operations internally with the event-based API (that NM is using) instead of the regular easy API that it otherwise uses. Any chance you can see if that  reproduces it?

    $ curl --test-event -v http://www.archlinux.org/check_network_status.txt

**Comment by heftig** [comment] 2019-02-19 10:50
Hah, that does get into a loop printing `* call curl_multi_socket_action(socket 4)`.

**Comment by heftig** [comment] 2019-02-19 10:52
```
* STATE: INIT => CONNECT handle 0x55590a766ea8; line 1429 (connection #-5000)
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => WAITRESOLVE handle 0x55590a766ea8; line 1470 (connection #0)
*   Trying 2a01:4f8:172:1d86::1...
* TCP_NODELAY set
* STATE: WAITRESOLVE => WAITCONNECT handle 0x55590a766ea8; line 1551 (connection #0)
* socket cb: socket 3 ADDED as OUT
*   Trying 138.201.81.199...
* TCP_NODELAY set
* socket cb: socket 4 ADDED as OUT
* call curl_multi_socket_action(socket 4)
* call curl_multi_socket_action(socket 4)
* call curl_multi_socket_action(socket 4)
[et cetera]
```

**Comment by buzo-ffm** [comment] 2019-02-19 11:04
FWIW, my IPv6 is working fine, yet I am hit by this bug. The reason could be me having more than one default route:

default via fe80::**** dev enp0s31f6 proto ra metric 100 pref medium
default via fe80::**** dev wlp58s0 proto ra metric 600 pref medium
default via fd28:**** dev buzo metric 1024 pref low

**Comment by heftig** [comment] 2019-02-19 11:09
Since curl moves on to IPv4 quite quickly if the initial attempt at IPv6 takes too long, I guess just having a slow enough connection to the server is enough to trigger this.

**Closed** 2019-02-20 07:16 UTC
Labels: regression
