### ISSUE TITLE
" error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding" on curl 7.74.0 (works on curl 7.68.0)

### ISSUE THREAD

**Issue by MirtoBusico** [curl/curl#7535] opened 2021-08-05 16:13 UTC
### I did this
I have a site with certificates signed by a private CA that I try to access.
This works using curl 7.68.0 (on Ubuntu 20.04) but gives the error 0407008A if I use curl 7.74.0 (on Ubuntu 21.04)

### I expected the following
Obtain the site home page (curl 7.68.0)
```
sysop@p02serv:~$ curl -v https://k6k.p02.net
*   Trying 192.168.102.50:443...
* TCP_NODELAY set
* Connected to k6k.p02.net (192.168.102.50) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=IT; ST=Italy; L=Rome; O=Busico Mirto; OU=Laboratory; CN=k6k.p02.net
*  start date: Aug  5 14:27:44 2021 GMT
*  expire date: Aug  3 14:27:44 2031 GMT
*  subjectAltName: host "k6k.p02.net" matched cert's "*.p02.net"
*  issuer: C=IT; ST=Italy; L=Rome; O=Busico Mirto; OU=Laboratory; CN=Busico Mirto; emailAddress=mirtobusico@gmail.com
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: k6k.p02.net
> User-Agent: curl/7.68.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Thu, 05 Aug 2021 15:31:47 GMT
< Server: Apache/2.4.41 (Ubuntu)
< Last-Modified: Fri, 30 Jul 2021 10:57:26 GMT
< Content-Length: 1087
< Content-Type: text/html
< Accept-Ranges: bytes
< Vary: Accept-Encoding
< 
<!--
```

But I obtain an error with curl 7.74.0
```
mirto@c37-mirto:~$ curl -v https://p02serv.p02.net
*   Trying 192.168.102.50:443...
* Connected to p02serv.p02.net (192.168.102.50) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, decrypt error (563):
* error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
* Closing connection 0
curl: (35) error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
mirto@c37-mirto:~$ curl -v https://k6k.p02.net
*   Trying 192.168.102.50:443...
* Connected to k6k.p02.net (192.168.102.50) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, decrypt error (563):
* error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
* Closing connection 0
curl: (35) error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
mirto@c37-mirto:~$ curl --version
curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1j zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh/0.9.5/openssl/zlib nghttp2/1.43.0 librtmp/2.3
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
mirto@c37-mirto:~$ 
```

### curl/libcurl version
Working
```
sysop@p02serv:~$ curl --version
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
sysop@p02serv:~$ 
```
NOT working (error 0407008A)
```
mirto@c37-mirto:~$ curl --version
curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1j zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh/0.9.5/openssl/zlib nghttp2/1.43.0 librtmp/2.3
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
mirto@c37-mirto:~$
```

### operating system
Ubuntu Mate 20.04 (working)
```
sysop@p02serv:~$ uname -a
Linux p02serv 5.8.0-63-generic #71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
sysop@p02serv:~$
```
Ubuntu-studio 21-04 (ERROR)
```
mirto@c37-mirto:~$ uname -a
Linux c37-mirto 5.11.0-25-lowlatency #27-Ubuntu SMP PREEMPT Sat Jul 10 00:06:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
mirto@c37-mirto:~$ 
```

What can I do?

**Comment by bagder** [comment] 2021-08-08 15:56
This looks like OpenSSL returns that error. It also looks like one of your OpenSSL versions doesn't return an error there. I suspect this is unrelated to the different curl versions...

**Comment by MirtoBusico** [comment] 2021-08-08 17:02
Well, on Ubuntu 20.04 (working) I see
```
OpenSSH_8.2p1 Ubuntu-4ubuntu0.3, OpenSSL 1.1.1f  31 Mar 2020
```
On Ubuntu 21.04 (with error) I see
```
OpenSSH_8.4p1 Ubuntu-5ubuntu1, OpenSSL 1.1.1j  16 Feb 2021
```
So the difference seems 1f versus 1j 

Do you know how to find informations about OpenSSL version incompatibilities?

**Comment by bagder** [comment] 2021-08-08 21:51
If you can tell us how to reproduce this problem we could help.

Otherwise I would propose you try the same curl with different OpenSSL versions or vice versa to find out which one is to blame!

**Comment by jay** [comment] 2021-08-08 23:05
Also try using the openssl tool instead of curl, for example:
`openssl s_client -connect k6k.p02.net:443 -servername k6k.p02.net < /dev/null`

**Comment by MirtoBusico** [comment] 2021-08-09 17:02
I'm reinstalling one of the involved machines.
I'll post a reply asap

**Comment by MirtoBusico** [comment] 2021-08-11 16:13
> If you can tell us how to reproduce this problem we could help.
> 
> Otherwise I would propose you try the same curl with different OpenSSL versions or vice versa to find out which one is to blame!

Well, I have a 78 page document with all the step I followed. If it can be useful I can attach the document here.
Estracting only the step that I think are relevant to reproduce the issue they are:

1) create the server (here p02serv) with
   - operating system Ubuntu Mate 20.04.2 (Linux p02serv 5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux)
   - ssh version: OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020
   - create a Certification Authority (CA) and then create key and cert files for "k6k.p02.net")
   - install apache2, enable https and put key and cert in the default-ssl site
 2) create a client (here santech)
    - operating system Kubuntu 20.04.2 (Linux santech 5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux)
    - ssh version: OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020
    - install the CA cerificate in the browser and in the operaing system
    - in the file /etc/hosts put a line with k6k.p02.net address
 3) create a second client (here vm-mirto)
     - operating system Ubuntu Studio 21.04 (Linux vm-mirto 5.11.0-25-lowlatency #27-Ubuntu SMP PREEMPT Sat Jul 10 00:06:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux)
     - ssh version: OpenSSH_8.4p1 Ubuntu-5ubuntu1, OpenSSL 1.1.1j  16 Feb 2021
     - install the CA cerificate in the browser and in the operaing system
     -  in the file /etc/hosts put a line with k6k.p02.net address
With this framework:
1) try curl from santech to p02serv (it is OK)
```
mirto@santech:~$ curl -v https://p02serv.p02.net >/dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 192.168.102.50:443...
* TCP_NODELAY set
* Connected to p02serv.p02.net (192.168.102.50) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [21 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [960 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=IT; ST=Italy; L=Rome; O=Busico Mirto; OU=Laboratory; CN=p02serv
*  start date: Aug  5 13:59:55 2021 GMT
*  expire date: Aug  3 13:59:55 2031 GMT
*  subjectAltName: host "p02serv.p02.net" matched cert's "*.p02.net"
*  issuer: C=IT; ST=Italy; L=Rome; O=Busico Mirto; OU=Laboratory; CN=Busico Mirto; emailAddress=mirtobusico@gmail.com
*  SSL certificate verify ok.
} [5 bytes data]
> GET / HTTP/1.1
> Host: p02serv.p02.net
> User-Agent: curl/7.68.0
> Accept: */*
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [265 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [265 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Wed, 11 Aug 2021 16:05:48 GMT
< Server: Apache/2.4.41 (Ubuntu)
< Last-Modified: Thu, 05 Aug 2021 13:45:00 GMT
< ETag: "2aa6-5c8d02013b699"
< Accept-Ranges: bytes
< Content-Length: 10918
< Vary: Accept-Encoding
< Content-Type: text/html
< 
{ [5 bytes data]
100 10918  100 10918    0     0   242k      0 --:--:-- --:--:-- --:--:--  242k
* Connection #0 to host p02serv.p02.net left intact
mirto@santech:~$
```
2) try to curl from vm-mirto to p02serv (ERROR  0407008A)
```
mirto@vm-mirto:~$ curl -v https://p02serv.p02.net >/dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 192.168.102.50:443...
* Connected to p02serv.p02.net (192.168.102.50) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [21 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [960 bytes data]
* TLSv1.3 (OUT), TLS alert, decrypt error (563):
} [2 bytes data]
* error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (35) error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
mirto@vm-mirto:~$
```

Have I to send other informations/tests?

**Comment by MirtoBusico** [comment] 2021-08-11 16:29
> Also try using the openssl tool instead of curl, for example:
> `openssl s_client -connect k6k.p02.net:443 -servername k6k.p02.net < /dev/null`

With the previos reply framework:
From santech to p02serv (OK)
```
mirto@santech:~$ openssl s_client -connect k6k.p02.net:443 -servername k6k.p02.net < /dev/null
CONNECTED(00000003)
depth=1 C = IT, ST = Italy, L = Rome, O = Busico Mirto, OU = Laboratory, CN = Busico Mirto, emailAddress = mirtobusico@gmail.com
verify return:1
depth=0 C = IT, ST = Italy, L = Rome, O = Busico Mirto, OU = Laboratory, CN = k6k.p02.net
verify return:1
---
Certificate chain
 0 s:C = IT, ST = Italy, L = Rome, O = Busico Mirto, OU = Laboratory, CN = k6k.p02.net
   i:C = IT, ST = Italy, L = Rome, O = Busico Mirto, OU = Laboratory, CN = Busico Mirto, emailAddress = mirtobusico@gmail.com
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDrzCCApegAwIBAgIUOd6HgRhS2c/+/gFb87ZBPHFr9lkwDQYJKoZIhvcNAQEL
BQAwgZUxCzAJBgNVBAYTAklUMQ4wDAYDVQQIDAVJdGFseTENMAsGA1UEBwwEUm9t
ZTEVMBMGA1UECgwMQnVzaWNvIE1pcnRvMRMwEQYDVQQLDApMYWJvcmF0b3J5MRUw
EwYDVQQDDAxCdXNpY28gTWlydG8xJDAiBgkqhkiG9w0BCQEWFW1pcnRvYnVzaWNv
QGdtYWlsLmNvbTAeFw0yMTA4MDUxNDI3NDRaFw0zMTA4MDMxNDI3NDRaMG4xCzAJ
BgNVBAYTAklUMQ4wDAYDVQQIDAVJdGFseTENMAsGA1UEBwwEUm9tZTEVMBMGA1UE
CgwMQnVzaWNvIE1pcnRvMRMwEQYDVQQLDApMYWJvcmF0b3J5MRQwEgYDVQQDDAtr
NmsucDAyLm5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALyN/q9N
SZMHbjz+Sj4VhwrCiyP0+/g2K+USTxJpBvwxQZoBwehTqX0qqHhYMUXY3yyRIEMS
LfwV5HQj7MrtG4Y9rTN2u3OQMqGuqo0vmg3jwQ9jOkO9jGQRtsWyKZZiWWzCKQ0W
IM0pj2Mpe+K8nwEzkBuaj4bKHPDOBqIcker+fjEbRHZID7q8cWIZZSZKuv1oZ78Q
icMzRpdNW2DdQpNjAzuS419hmOxfWUW4IdzIEWvCoEEaLacnm3DPFXSwcjIe1zIZ
AyTrztxr6xWcAjSA0E9lZbCoPynJSrngEc0p996Q+WzeDzZUr7VPZ8ngEO1gAoC7
2YGvy9cPEmIdHDECAwEAAaMdMBswGQYDVR0RBBIwEIIDazZrggkqLnAwMi5uZXQw
DQYJKoZIhvcNAQELBQADggEBAAoTOCuSa1DFCi0hk2iGczwoDaGpnOLnaiaB1yVP
3qROyENrog+ZwzxeP+a5ZjrUy516k/7Qc73hA6+xC6LBOSuGB+9JPOhMavvu3u8i
eFy74YeKf9neXC/l0hLsoHFboEdfFGBZKr/SfC/40NqoW/ZiBVcWZiuoRuHppMar
w/OIo6GdkA6i0spcukiV+vDwYgtCRUVXR9vEtZ7OvKuQ3GRcXJOX2BDy8SBGXoy9
yFL4DEP//CnQGiWOmxQFEcywuMH1GCm5Ake5vW7aMTA5mE+qHTpT4MoMGpdJop6b
TgrR70A1Q3EijiFktZ9f3bPjemvq1Iklm0cJriRaet+zxdg=
-----END CERTIFICATE-----
subject=C = IT, ST = Italy, L = Rome, O = Busico Mirto, OU = Laboratory, CN = k6k.p02.net

issuer=C = IT, ST = Italy, L = Rome, O = Busico Mirto, OU = Laboratory, CN = Busico Mirto, emailAddress = mirtobusico@gmail.com

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1507 bytes and written 383 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
DONE
mirto@santech:~$ 

```
From vm-mirto to p02serv (ERROR certificate signature failure)
```
mirto@vm-mirto:~$  openssl s_client -connect k6k.p02.net:443 -servername k6k.p02.net < /dev/null
CONNECTED(00000003)
depth=1 C = IT, ST = Italy, L = Rome, O = Busico Mirto, OU = Laboratory, CN = Busico Mirto, emailAddress = mirtobusico@gmail.com
verify return:1
depth=0 C = IT, ST = Italy, L = Rome, O = Busico Mirto, OU = Laboratory, CN = k6k.p02.net
verify error:num=7:certificate signature failure
verify return:1
depth=0 C = IT, ST = Italy, L = Rome, O = Busico Mirto, OU = Laboratory, CN = k6k.p02.net
verify return:1
---
Certificate chain
 0 s:C = IT, ST = Italy, L = Rome, O = Busico Mirto, OU = Laboratory, CN = k6k.p02.net
   i:C = IT, ST = Italy, L = Rome, O = Busico Mirto, OU = Laboratory, CN = Busico Mirto, emailAddress = mirtobusico@gmail.com
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDrzCCApegAwIBAgIUOd6HgRhS2c/+/gFb87ZBPHFr9lkwDQYJKoZIhvcNAQEL
BQAwgZUxCzAJBgNVBAYTAklUMQ4wDAYDVQQIDAVJdGFseTENMAsGA1UEBwwEUm9t
ZTEVMBMGA1UECgwMQnVzaWNvIE1pcnRvMRMwEQYDVQQLDApMYWJvcmF0b3J5MRUw
EwYDVQQDDAxCdXNpY28gTWlydG8xJDAiBgkqhkiG9w0BCQEWFW1pcnRvYnVzaWNv
QGdtYWlsLmNvbTAeFw0yMTA4MDUxNDI3NDRaFw0zMTA4MDMxNDI3NDRaMG4xCzAJ
BgNVBAYTAklUMQ4wDAYDVQQIDAVJdGFseTENMAsGA1UEBwwEUm9tZTEVMBMGA1UE
CgwMQnVzaWNvIE1pcnRvMRMwEQYDVQQLDApMYWJvcmF0b3J5MRQwEgYDVQQDDAtr
NmsucDAyLm5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALyN/q9N
SZMHbjz+Sj4VhwrCiyP0+/g2K+USTxJpBvwxQZoBwehTqX0qqHhYMUXY3yyRIEMS
LfwV5HQj7MrtG4Y9rTN2u3OQMqGuqo0vmg3jwQ9jOkO9jGQRtsWyKZZiWWzCKQ0W
IM0pj2Mpe+K8nwEzkBuaj4bKHPDOBqIcker+fjEbRHZID7q8cWIZZSZKuv1oZ78Q
icMzRpdNW2DdQpNjAzuS419hmOxfWUW4IdzIEWvCoEEaLacnm3DPFXSwcjIe1zIZ
AyTrztxr6xWcAjSA0E9lZbCoPynJSrngEc0p996Q+WzeDzZUr7VPZ8ngEO1gAoC7
2YGvy9cPEmIdHDECAwEAAaMdMBswGQYDVR0RBBIwEIIDazZrggkqLnAwMi5uZXQw
DQYJKoZIhvcNAQELBQADggEBAAoTOCuSa1DFCi0hk2iGczwoDaGpnOLnaiaB1yVP
3qROyENrog+ZwzxeP+a5ZjrUy516k/7Qc73hA6+xC6LBOSuGB+9JPOhMavvu3u8i
eFy74YeKf9neXC/l0hLsoHFboEdfFGBZKr/SfC/40NqoW/ZiBVcWZiuoRuHppMar
w/OIo6GdkA6i0spcukiV+vDwYgtCRUVXR9vEtZ7OvKuQ3GRcXJOX2BDy8SBGXoy9
yFL4DEP//CnQGiWOmxQFEcywuMH1GCm5Ake5vW7aMTA5mE+qHTpT4MoMGpdJop6b
TgrR70A1Q3EijiFktZ9f3bPjemvq1Iklm0cJriRaet+zxdg=
-----END CERTIFICATE-----
subject=C = IT, ST = Italy, L = Rome, O = Busico Mirto, OU = Laboratory, CN = k6k.p02.net

issuer=C = IT, ST = Italy, L = Rome, O = Busico Mirto, OU = Laboratory, CN = Busico Mirto, emailAddress = mirtobusico@gmail.com

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1507 bytes and written 383 bytes
Verification error: certificate signature failure
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 7 (certificate signature failure)
---
DONE
mirto@vm-mirto:~$ 
```
Any hint?

**Comment by MirtoBusico** [comment] 2021-08-12 10:42
Here the commands I followed to create certificates.

Certification authority creation:
```
sysop@p02serv:~/p02certs$ sudo openssl genrsa -out p02ca.key 2048
Generating RSA private key, 2048 bit long modulus (2 primes)
..................................................+++++
........................+++++
e is 65537 (0x010001)
sysop@p02serv:~/p02certs$ ls -lh
totale 4,0K
-rw------- 1 root root 1,7K ago  5 15:49 p02ca.key
sysop@p02serv:~/p02certs$ sudo openssl req -x509 -new -nodes -key p02ca.key -sha256 -days 3650 -out p02ca.pem
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:IT
State or Province Name (full name) [Some-State]:Italy
Locality Name (eg, city) []:Rome
Organization Name (eg, company) [Internet Widgits Pty Ltd]:Busico Mirto
Organizational Unit Name (eg, section) []:Laboratory
Common Name (e.g. server FQDN or YOUR name) []:Busico Mirto
Email Address []:mirtobusico@gmail.com
sysop@p02serv:~/p02certs$ ls -lh
totale 8,0K
-rw------- 1 root root 1,7K ago  5 15:49 p02ca.key
-rw-r--r-- 1 root root 1,5K ago  5 15:51 p02ca.pem
sysop@p02serv:~/p02certs$
```

Creation of k6k.p02.net certificate and key
Cofiguration file k6kssl.cnf containing
```
[req]
default_bits = 2048
distinguished_name = req_distinguished_name
prompt = no

[req_distinguished_name]
C = IT
ST = Italy
L = Rome
O = Busico Mirto
OU = Laboratory
CN = k6k.p02.net

[v3_ca]
subjectAltName = @alt_names

[alt_names]
DNS.1 = k6k
# Support subdomains
DNS.2 = *.p02.net
```
Request and certificate creation
```
sysop@p02serv:~$ cd p02certs/
sysop@p02serv:~/p02certs$ vi k6kssl.cnf
sysop@p02serv:~/p02certs$ sudo openssl req -new -sha256 -nodes -newkey rsa:2048 -keyout k6k.key -out k6k.csr -config k6kssl.cnf
[sudo] password di sysop: 
Generating a RSA private key
..................................................................................................+++++
.....+++++
writing new private key to 'k6k.key'
-----
sysop@p02serv:~/p02certs$
sysop@p02serv:~/p02certs$ sudo openssl x509 -req -in k6k.csr -CA p02ca.pem -CAkey p02ca.key -CAcreateserial -out k6k.crt -sha256 -days 3650 -extfile k6kssl.cnf -extensions v3_ca
Signature ok
subject=C = IT, ST = Italy, L = Rome, O = Busico Mirto, OU = Laboratory, CN = k6k.p02.net
Getting CA Private Key
sysop@p02serv:~/p02certs$ ls -lh
totale 44K
-rw-r--r-- 1 root  root  1,4K ago  5 16:27 k6k.crt
-rw-r--r-- 1 root  root  1013 ago  5 16:25 k6k.csr
-rw------- 1 root  root  1,7K ago  5 16:25 k6k.key
-rw-rw-r-- 1 sysop sysop  287 ago  5 16:24 k6kssl.cnf
-rw------- 1 root  root  1,7K ago  5 15:49 p02ca.key
-rw-r--r-- 1 root  root  1,5K ago  5 15:51 p02ca.pem
-rw-r--r-- 1 root  root    41 ago  5 16:27 p02ca.srl
```
Do you see anything weird?

**Comment by jay** [comment] 2021-08-15 06:46
Maybe it has something to do with the way you configured the web server? Did you specify the wrong certificate or key in the configuration? In nginx I set it to this and it works:

ssl_certificate /dir/k6k.crt;
ssl_certificate_key /dir/k6k.key;

~~~
curl 7.79.0-DEV (i386-pc-win32) libcurl/7.79.0-DEV OpenSSL/1.1.1j nghttp2/1.43.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Debug HSTS HTTP2 HTTPS-proxy IPv6 Largefile NTLM SSL Unicode UnixSockets alt-svc
 ~~~

**Comment by MirtoBusico** [comment] 2021-08-15 10:07
Well, I don't know nginx.
Mi Apache configuration is:
```
sysop@p02serv:~$ cd /etc/apache2/sites-enabled/
sysop@p02serv:/etc/apache2/sites-enabled$ ls -lh
totale 0
lrwxrwxrwx 1 root root 35 ago  5 15:45 000-default.conf -> ../sites-available/000-default.conf
lrwxrwxrwx 1 root root 35 ago  5 15:45 default-ssl.conf -> ../sites-available/default-ssl.conf
lrwxrwxrwx 1 root root 31 ago  5 16:32 k6k-ssl.conf -> ../sites-available/k6k-ssl.conf
sysop@p02serv:/etc/apache2/sites-enabled$ cat k6k-ssl.conf 
<IfModule mod_ssl.c>
        <VirtualHost *:443>
                ServerAdmin webmaster@localhost
                ServerName k6k.p02.net

                DocumentRoot /var/www/k6k

                ErrorLog ${APACHE_LOG_DIR}/errork6k.log
                CustomLog ${APACHE_LOG_DIR}/accessk6k.log combined

                SSLCertificateFile      /home/sysop/p02certs/k6k.crt
                SSLCertificateKeyFile   /home/sysop/p02certs/k6k.key

                <FilesMatch "\.(cgi|shtml|phtml|php)$">
                                SSLOptions +StdEnvVars
                </FilesMatch>
                <Directory /usr/lib/cgi-bin>
                                SSLOptions +StdEnvVars
                </Directory>
                # –----------------------------------------------- 
                #        Keycloak
                # –----------------------------------------------- 

                ProxyPreserveHost On
                SSLProxyEngine On
                SSLProxyCheckPeerCN On
                SSLProxyCheckPeerExpire On
                RequestHeader set X-Forwarded-Proto "https"
                RequestHeader set X-Forwarded-Port "443"
                ProxyRequests Off
                ProxyPass / http://127.0.0.1:8080/
                ProxyPassReverse / http://127.0.0.1:8080/

        </VirtualHost>
</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
sysop@p02serv:/etc/apache2/sites-enabled$ 
```
Do you see anything strange / missing?

**Comment by jay** [comment] 2021-08-16 07:21
I can't review your apache config but I'd check to make sure SSLCertificateFile and SSLCertificateKeyFile are valid and check errork6k.log. "certificate signature failure" from the openssl tool makes it likely this is not a curl problem.

**Comment by jay** [comment] 2021-09-03 06:25
likely not a curl issue and no further response, closing

**Closed by jay** 2021-09-03 06:25 UTC
Labels: SSL/TLS, needs-info
