### ISSUE TITLE
no_proxy not working as expected

### ISSUE THREAD

**Issue by Carlospi99** [curl/curl#9981] opened 2022-11-25 13:45 UTC
### I did this

I was using the version 7_85_0  and with the no_proxy flag was taking in account for anything in the list.

`no_proxy=local,.example.com,.another.com`

But in the version  7_86_0 
is only taking in account the last entry of the list, I have change order and it is always the last one that works.
### curl/libcurl version

curl 7.86.0 (x86_64-alpine-linux-musl) libcurl/7.86.0 OpenSSL/3.0.7 zlib/1.2.13 brotli/1.0.9 nghttp2/1.51.0
Release-Date: 2022-10-26

No sure if someone had the same

**Comment by bagder** [comment] 2022-11-25 13:51
Duplicate of #9813 

There were also a few other regressions in the noproxy logic, but we believe all of them are fixed in master and will be shipped in the pending 7.87.0 release.

**Comment by henning-schild** [comment] 2022-11-25 19:46
You likely want to cherry-pick all commits listed here https://github.com/curl/curl/issues/9813#issuecomment-1315878462 or get in touch with your distributor to do so.

**Closed** 2022-11-26 16:00 UTC
Labels: regression, duplicate, connecting & proxies

**Comment by henning-schild** [comment] 2022-11-26 22:53
@Carlospi99 please also get in touch with your distro to report the bug with them, they can pick the changes and likely want to take 7.87.0 as soon as it comes out
