### ISSUE TITLE
--write-out displays strange values (thousands of seconds) on ARM processors

### ISSUE THREAD

**Issue by bortzmeyer** [curl/curl#6932] opened 2021-04-22 14:49 UTC
### I did this

curl --silent --output /dev/null --write-out "DNS: %{time_namelookup}\n" https://www.afnic.fr/
DNS: 20176

### I expected the following

DNS: 0.019298

or something similar since the info was in the cache. Anyway, I'm sure that it was not twenty thousands seconds.

### curl/libcurl version

curl 7.74.0 (armv6l-unknown-linux-gnueabihf) libcurl/7.74.0 OpenSSL/1.1.1i zlib/1.2.11 zstd/1.4.5 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.41.0
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd

### operating system

Linux alarmpi 5.4.83-3-ARCH #1 SMP PREEMPT Mon Jan 4 01:09:25 UTC 2021 armv6l GNU/Linux

The problem also occurs on another ARM machine but never on x86_64. An endianness problem?

**Comment by bagder** [comment] 2021-04-22 14:54
Yes sorry, this is unfortunately a bug in 7.74.0 were I accidentally made it output microseconds instead of seconds with fractions. Fixed in 7.75.0

Duplicate of #6321

**Comment by bortzmeyer** [comment] 2021-04-23 12:14
Indeed, 7.76 fixed the problem (which has nothing to do with ARM processors), thanks.

**Closed** 2021-04-25 21:34 UTC
Labels: cmdline tool
