### ISSUE TITLE
connection is still name resolving, cant reuse?

### ISSUE THREAD

**Issue by bethebest0622** [curl/curl#13375] opened 2024-04-15 13:23 UTC
### I did this

curl reuse connection can save much time, when sending http get/post request repeatly.

I used it for a long time, but recently i found the messge:
```
* processing: http://471646160aapi.hbdm.com/linear-swap-api/v1/swap_cross_cancel?AccessKeyId=630ffb31-bgbfh5tv3f-3eb9569d-895e0&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2024-04-15T13%3A20%3A18&Signature=wNb%2BSWQtPh4VqLjtzglS9iUh2pu3BVkKjegP61ILWg8%3D
* Found bundle for host: 0x7f5c640076b0 [serially]
* Can not multiplex, even if we wanted to
* Connection #0 is still name resolving, can't reuse
* Connection #1 is still name resolving, can't reuse
* Connection #2 is still name resolving, can't reuse
* Connection #3 is still name resolving, can't reuse
* Connection #4 is still name resolving, can't reuse
* Connection #5 is still name resolving, can't reuse
* Connection #6 is still name resolving, can't reuse
* Connection #7 is still name resolving, can't reuse
* Hostname 471646160aapi.hbdm.com was found in DNS cache
*   Trying 172.31.9.166:80...
* getpeername() failed with errno 107: Transport endpoint is not connected
* Connected to 471646160aapi.hbdm.com () port 80
* getpeername() failed with errno 107: Transport endpoint is not connected
> * processing: http://471646160aapi.hbdm.com/linear-swap-api/v1/swap_cross_cancel?AccessKeyId=630ffb31-bgbfh5tv3f-3eb9569d-895e0&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2024-04-15T13%3A20%3A18&Signature=wNb%2BSWQtPh4VqLjtzglS9iUh2pu3BVkKjegP61ILWg8%3D
* Found bundle for host: 0x7f5c640076b0 [serially]
* Can not multiplex, even if we wanted to
```

it shows not reuse the connection even there is existed connections, could you help on this, how can i reuse connections correctly?

### I expected the following

reuse the connections

### curl/libcurl version

curl 8.2.1

### operating system

centos stream 8

**Comment by bagder** [comment] 2024-04-15 14:13
Thanks a lot for your report!

I've failed to reproduce this problem myself, so can I ask you to provide us with more details on how to go ahead and repeat this. Preferably with a command line or a stand-alone program we can run from our ends against a public URL to trigger the problem?

**Comment by bagder** [comment] 2024-06-14 21:51
Cannot reproduce, nothing to act on. Closing.

**Closed by bagder** 2024-06-14 21:51 UTC
Labels: needs-info, connecting & proxies
