### ISSUE TITLE
Java HTTPS service makes cURL 7.64.0 hang in TLS handshake

### ISSUE THREAD

**Issue by cpunxx** [curl/curl#4170] opened 2019-07-30 12:14 UTC
I think I've found a way to hang the latest cURL included in Raspbian Linux. I think it should not let a server disrupt itself like this, and this might be a bug.

I have two servers (Raspbian 10) where the problem occurs. Both have cURL 7.64.0-4. I also have a development machine (Devuan Ascii) which works fine. It has cURL 7.52.1-5+deb9u9.

An API server offers a HTTPS service from a Java application. A web server consumes the API service via cURL from PHP. The pattern of failures and successes is like this:

- When the web server uses cURL against the API server - bug.
- When the web server uses PHP streams against the API server - OK.
- When I run cURL manually from the web server - bug.
- When I run cURL manually from the dev machine - OK.

Sidenote: servers communicate in a LAN, therefore the web server is instructed to ignore the API server's certificate.

A script written in Bash tests the API server by requesting a session ID from it like this:

curl -v -o temp.xml --insecure --header "Content-Type:application/xml" -X POST -v https://192.168.1.11:10443/GetSession -T GetSession

In the OK scenario, I can run any number of these tests - all of them complete. In the buggy scenario, approximately on the third run (luck varies, it could be time-dependent), cURL hangs and keeps waiting for a response, while the API server cannot see a request.

Log from buggy scenario:
-------------------- start of log --------------------
```

root@www:/opt/api-test# ./test
* Expire in 0 ms for 6 (transfer 0x12ca7c0)
*   Trying 192.168.1.11...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x12ca7c0)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 192.168.1.11 (192.168.1.11) port 10443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [193 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [155 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [42 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [4600 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: OU=Domain Control Validated; OU=Gandi Standard SSL; CN=droid.eu.com
*  start date: Jul 19 00:00:00 2019 GMT
*  expire date: Jul 19 23:59:59 2021 GMT
*  issuer: C=FR; ST=Paris; L=Paris; O=Gandi; CN=Gandi Standard SSL CA 2
*  SSL certificate verify ok.
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0} [5 bytes data]
> POST /GetSession HTTP/1.1
> Host: 192.168.1.11:10443
> User-Agent: curl/7.64.0
> Accept: */*
> Content-Type:application/xml
> Content-Length: 195
> Expect: 100-continue
> 
* Expire in 1000 ms for 0 (transfer 0x12ca7c0)
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [50 bytes data]
< HTTP/1.1 100 Continue
< Content-Length: 0
} [5 bytes data]
* We are completely uploaded and fine
100   195    0     0  100   195      0     76  0:00:02  0:00:02 --:--:--    76{ [5 bytes data]
< HTTP/1.1 200 OK
< Access-control-allow-headers: *
< Date: Tue, 30 Jul 2019 12:08:30 GMT
< Access-control-allow-methods: *
< Access-control-allow-origin: *
< Content-length: 502
< 
{ [5 bytes data]
100   697  100   502  100   195    161     62  0:00:03  0:00:03 --:--:--   224
* Connection #0 to host 192.168.1.11 left intact

root@www:/opt/api-test# ./test
* Expire in 0 ms for 6 (transfer 0x1ebe7c0)
*   Trying 192.168.1.11...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x1ebe7c0)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 192.168.1.11 (192.168.1.11) port 10443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [193 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [155 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [42 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [4600 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: OU=Domain Control Validated; OU=Gandi Standard SSL; CN=droid.eu.com
*  start date: Jul 19 00:00:00 2019 GMT
*  expire date: Jul 19 23:59:59 2021 GMT
*  issuer: C=FR; ST=Paris; L=Paris; O=Gandi; CN=Gandi Standard SSL CA 2
*  SSL certificate verify ok.
} [5 bytes data]
> POST /GetSession HTTP/1.1
> Host: 192.168.1.11:10443
> User-Agent: curl/7.64.0
> Accept: */*
> Content-Type:application/xml
> Content-Length: 195
> Expect: 100-continue
> 
* Expire in 1000 ms for 0 (transfer 0x1ebe7c0)
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [50 bytes data]
< HTTP/1.1 100 Continue
< Content-Length: 0
} [5 bytes data]
* We are completely uploaded and fine
{ [5 bytes data]
< HTTP/1.1 200 OK
< Access-control-allow-headers: *
< Date: Tue, 30 Jul 2019 12:08:32 GMT
< Access-control-allow-methods: *
< Access-control-allow-origin: *
< Content-length: 502
< 
{ [5 bytes data]
100   697  100   502  100   195   1039    403 --:--:-- --:--:-- --:--:--  1443
* Connection #0 to host 192.168.1.11 left intact

root@www:/opt/api-test# ./test
* Expire in 0 ms for 6 (transfer 0x2847c0)
*   Trying 192.168.1.11...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x2847c0)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 192.168.1.11 (192.168.1.11) port 10443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
  0     0    0     0    0     0      0      0 --:--:--  0:00:35 --:--:--     0
```
--------------------

As you see, the third run hangs and hasn't timed out even after 35 seconds. Unless I restart the whole server (nothing less seems to work), any subsequent runs hang immediately, with no success preceding failure.  I suspect problems with re-use of connections.

My cURL code in PHP and its working replacement using the PHP stream API are as follows:

------- stream API code ---------

```
function post($path,$xml,$debug=false) {
    $aContext = stream_context_create(
        array(
            'http'=>array(
            'header'=>"Content-type: application/xml",
            'method'=>'POST',
            'content'=>$xml
            ),         
            "ssl"=>array(
            "verify_peer"=>false,
            "verify_peer_name"=>false
            )
        )
    );
    return file_get_contents($path, 0, $aContext);
```
}
-------------- end -------------

---------- cURL code ----------
```
function post_curl_failing($path,$xml,$debug=false) {
    $handle = curl_init();
    curl_setopt($handle, CURLOPT_VERBOSE, 1);
    curl_setopt($handle, CURLOPT_URL,$path);
    curl_setopt($handle, CURLOPT_POST, true);
    curl_setopt($handle, CURLOPT_RETURNTRANSFER, 1); // return the raw output 
    curl_setopt($handle, CURLOPT_SSL_VERIFYPEER, 0); // ignore the domain name in the cert, we're in LAN
    curl_setopt($handle, CURLOPT_SSL_VERIFYHOST, 0); // ignore the domain name in the cert, we're in LAN
    curl_setopt($handle, CURLOPT_TIMEOUT, 10);
    curl_setopt($handle, CURLOPT_HTTPHEADER, array('Content-Type: application/xml'));
    curl_setopt($handle, CURLOPT_POSTFIELDS, $xml);
    $ret = curl_exec($handle);
 
    if ($debug == true) {
        if (!curl_errno($handle)) {
            $info = curl_getinfo($handle);
            echo "<p>CURL INFO: time ". $info["total_time"] ." seconds to request ". $info["url"]."</p>\n";
        } else {
            echo "<p>CURL ERROR: ".curl_error($handle)."</p>\n";
        }
    }
    
    curl_close($handle);   
    return $ret;
}
```
--------- end --------

**Comment by cpunxx** [comment] 2019-07-30 12:31
P.S. The API server is written in Java and uses the "com.sun.net.httpserver.HttpsServer" class. I 've made no attempt to investigate its ability to re-use connections, nor have I made any attempt to give it this ability. I thus assume it cannot re-use connections and would not advertise this capability to a client, but I'm a newbie in that corner of the HTTP protocol.... server should grant clients 10 seconds of time to complete work, after that, connections will be dropped harshly.

If you want to test, currently you can reach this service on the website mentioned in the certificate in the above logs (use port 10443 and query the contest "/GetSession"). If you want it to answer nicely, send it something like:

<?xml version="1.0" encoding="UTF-8"?>
<GetSession>
    <session>00000000000000000000000000000000000000000000000000</session>
    <override>0</override>
    <language>en</language>
</GetSession>

**Comment by bagder** [comment] 2019-07-30 13:05
When curl outputs the progress meter just like you showed in the third invoke:

     0     0    0     0    0     0      0      0 --:--:--  0:00:35 --:--:--     0

... it means curl has established the connection, issued the request and is just waiting for data to arrive from the server over the connection. I strongly doubt that this is a curl problem as everything is working fine to that point and the moving progress meter also indicates that.

We would need a way to reproduce this problem in order to further diagnose what is happening, so just knowing that you can make this happen on a local server of your own is going to make this hard to act on.

> If you want to test, currently you can reach this service on the website mentioned in the certificate in the above logs (use port 10443 and query the contest "/GetSession").

Can you give us a complete command line to run? (and I don't expect anyone of us will actually run your exact curl version on your exact system setup)

**Comment by cpunxx** [comment] 2019-07-30 16:29
To recreate it, I would advise this as the simplest path: create a file named "GetSession" with the below content:

```
<?xml version="1.0" encoding="UTF-8"?>
<GetSession>
    <session>00000000000000000000000000000000000000000000000000</session>
    <override>0</override>
    <language>en</language>
</GetSession>
```

...and then, in the same directory, repeatedly run:

curl -v -o temp.xml --header "Content-Type:application/xml" -X POST -v https://droid.eu.com:10443/GetSession -T GetSession

**Comment by bagder** [comment] 2019-07-30 16:47
I can verify the same behavior: the server doesn't send any response and curl just sits waiting for it. I don't see how this is curl's bug though.

**Comment by cpunxx** [comment] 2019-07-30 16:49
But, how could this fit the pattern of *another* cURL not hanging? The server should respond the same way any time, one cURL hangs, other cURL does not hang, and PHP streams never hangs. Something seems fishy to me.

**Comment by cpunxx** [comment] 2019-07-30 16:54
P.S. I can provide server logs of your try:

```
2019-07-30 17:45:38.587   safePutClient() wants lock
2019-07-30 17:45:38.587   safePutClient() releasing lock after 0 ms of use
2019-07-30 17:45:40.385   -------------------- connect ------------------------
2019-07-30 17:45:40.385   Handling GetSession from h-163-240.A498.priv.bahnhof.se/155.4.163.240:39760
2019-07-30 17:45:40.387   getClient() returning client 2
-------------------- request ------------------------
<?xml version="1.0" encoding="UTF-8"?>
<GetSession>
    <session>00000000000000000000000000000000000000000000000000</session>
    <override>0</override>
    <language>en</language>
</GetSession>
2019-07-30 17:45:40.469   Validating [session] value [00000000000000000000000000000000000000000000000000].
2019-07-30 17:45:40.469   Validating [override] value [0].
2019-07-30 17:45:40.470   Existing session not required.
2019-07-30 17:45:40.470   Authenticated session not required.
2019-07-30 17:45:40.470   Validating [language] value [en].
2019-07-30 17:45:40.471   NULL session, skipping entire permission filter.
2019-07-30 17:45:40.471   REQUEST:
2019-07-30 17:45:40.471   language [en]
2019-07-30 17:45:40.472   Start new session for IP [h-163-240.A498.priv.bahnhof.se/155.4.163.240:39760], language [en].
2019-07-30 17:45:40.472   Session address [h-163-240.A498.priv.bahnhof.se/155.4.163.240].
2019-07-30 17:45:40.472   Session start [1564505140472].
2019-07-30 17:45:40.473   Session salt [-8499847072041603292].
2019-07-30 17:45:40.473   Session ID [1249373370486971987084148703113947790408484929978].
2019-07-30 17:45:40.495   -------------------- response ------------------------
2019-07-30 17:45:40.495   <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<GetSessionR>
    <errorLevel>ok</errorLevel>
    <errorId></errorId>
    <errorInfo>Language [en] set.</errorInfo>
    <t_errorTitle>t_errorTitle</t_errorTitle>
    <t_errorLevel>Error severity level:</t_errorLevel>
    <t_errorInfo>Log message (already written):</t_errorInfo>
    <t_errorPrompt>Your observations:</t_errorPrompt>
    <t_send>Send</t_send>
    <sessionId>1249373370486971987084148703113947790408484929978</sessionId>
</GetSessionR>

Preparing response of [507] B.
2019-07-30 17:45:40.496   CORS headers addded.
2019-07-30 17:45:40.500   safePutClient() wants lock
2019-07-30 17:45:40.500   safePutClient() releasing lock after 0 ms of use
2019-07-30 17:45:42.099   getClient() returning client 4
2019-07-30 17:45:42.105   safePutClient() wants lock
2019-07-30 17:45:42.106   safePutClient() releasing lock after 0 ms of use
2019-07-30 17:45:47.107   getClient() returning client 1
2019-07-30 17:45:47.115   safePutClient() wants lock
2019-07-30 17:45:47.115   safePutClient() releasing lock after 0 ms of use
2019-07-30 17:45:47.115   THREAD REPORT:
pool: 4, core: 2, active: 4, complete: 55, task: 60, isShutdown: false, isTerminated: false
2019-07-30 17:45:47.117   SESSION REPORT:
2019-07-30 17:45:47.117   IP 192.168.1.10/192.168.1.10:57042, LANG et, AGE 1141 s , IDL 1140 s , ID 1317164179858624363541736911702765709256083269383
2019-07-30 17:45:47.118   IP 62.65.219.245.cable.starman.ee/62.65.219.245:39448, LANG en, AGE 895 s , IDL 895 s , ID 188463404189876144857566437290820182607317486093
2019-07-30 17:45:47.118   IP 62.65.219.245.cable.starman.ee/62.65.219.245:39450, LANG en, AGE 893 s , IDL 893 s , ID 391988244392466811868380317866740298360856769057
2019-07-30 17:45:47.119   IP 62.65.219.245.cable.starman.ee/62.65.219.245:61403, LANG en, AGE 892 s , IDL 892 s , ID 372444351048739145438001581385673660315864709381
2019-07-30 17:45:47.119   IP 62.65.219.245.cable.starman.ee/62.65.219.245:39454, LANG en, AGE 890 s , IDL 890 s , ID 417908997137028247815062328919085707101423144949
2019-07-30 17:45:47.120   IP 62.65.219.245.cable.starman.ee/62.65.219.245:39456, LANG en, AGE 888 s , IDL 888 s , ID 939141600311505752101828131914664306317161367408
2019-07-30 17:45:47.120   IP 62.65.219.245.cable.starman.ee/62.65.219.245:56116, LANG en, AGE 819 s , IDL 819 s , ID 443308221081083979282007864590542239795591254898
2019-07-30 17:45:47.121   IP 62.65.219.245.cable.starman.ee/62.65.219.245:56118, LANG en, AGE 818 s , IDL 818 s , ID 736942310106141381676146533188346864498212485080
2019-07-30 17:45:47.121   IP 62.65.219.245.cable.starman.ee/62.65.219.245:56120, LANG en, AGE 538 s , IDL 538 s , ID 1438690546904906924263632100060241513457745553104
2019-07-30 17:45:47.122   IP h-163-240.A498.priv.bahnhof.se/155.4.163.240:39760, LANG en, AGE 6 s , IDL 6 s , ID 1249373370486971987084148703113947790408484929978
2019-07-30 17:45:47.122   JDBC has 4 idle and 0 busy clients, totaling 4 clients.

```

**Comment by bagder** [comment] 2019-07-30 16:57
Well, since we don't know why the server behaves this way it's hard to tell. I would imagine that perhaps some minor things in how the requests are issued differ and makes the server do like this?

I don't understand the log at all so I don't think it helps. I tried two different curl versions but neither ever got any response even after having waited for over a minute...

**Comment by cpunxx** [comment] 2019-07-30 16:58
Would a packet dump recorded with wireshark help any?

**Comment by cpunxx** [comment] 2019-07-30 16:59
P.S. Alternatively, maybe I should try to recreate it with ordinary HTTP... then I could eavesdrop on the traffic packet-by-packet easily enough... but I don't know if it would happen then.

**Comment by bagder** [comment] 2019-07-30 17:04
From what I can see on packet traces in my end, the TLS handshake never completes for me.

**Comment by cpunxx** [comment] 2019-07-30 17:18
Thanks, I think I'm starting to understand this. I can also confirm that the client hello has gone out, and the server then says:

> sun.net.httpserver.ServerImpl$Exchange@341358 is rejected

...so it's the server deciding to ignore the client in certain conditions. I will try to read up on this from the Java HttpServer documentation. Fortunately I can work around it, but for me, the surprise was that old cURL worked... then it suddenly stopped working and puzzled me quite a lot.

**Comment by cpunxx** [comment] 2019-07-30 17:19
P.S. Finally got a cURL instance to time out also, so while it's a behaviour change, it might not be a bug after all:

> curl: (28) Operation timed out after 300084 milliseconds with 0 out of 0 bytes received

**Comment by bagder** [comment] 2019-08-01 09:56
> so while it's a behaviour change

Possibly your upgraded version uses a different TLS library/version too? I still think this isn't so much a "behaviour change" as in some little detail in the TLS handshake is now different (but still valid and good TLS) and this server isn't handling it correctly.

curl, even version 7.64.0, is used widely all over the globe against a vast number of servers and this is not a problem others report. It is not a guaranteed conclusion but a strong indication.

**Comment by bagder** [comment] 2019-08-26 10:12
No news, presumed to be a server-side issue. Closing.

**Closed by bagder** 2019-08-26 10:12 UTC
Labels: HTTP, SSL/TLS, needs-info-or-update
