### ISSUE TITLE
tests/server/resolv not working properly on macOS

### ISSUE THREAD

**Issue by dfandrich** [curl/curl#11776] opened 2023-08-31 20:15 UTC
### I did this

tests/server/resolv does not give correct results for non-dotted hostnames on a macOS box I tried it on, but works correctly for dotted names:
```
$ tests/server/resolve --ipv6 asdfghjkl
$ tests/server/resolve --ipv6 ip6-localhost
$ tests/server/resolve asdfghjkl
$ tests/server/resolve localhost
$ tests/server/resolve asdfghjkl.com
Resolving IPv4 'asdfghjkl.com' didn't work
$ tests/server/resolve google.com
$ tests/server/resolve --ipv6 google.com
$ ping6 ip6-localhost
ping6: getaddrinfo -- nodename nor servname provided, or not known
```
Needless to say, its use in tests 241 and 1083 to test if ip6-localhost is resolvable does not work and it causes those tests to fail instead of being skipped.

### I expected the following

`tests/server/resolve --ipv6 ip6-localhost` should return an error if the machine cannot resolve the name ip6-localhost

### curl/libcurl version

curl 8.3.0-DEV (aarch64-apple-darwin21.6.0) libcurl/8.3.0-DEV LibreSSL/3.7.3 zlib/1.2.11 nghttp2/1.55.1
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe UnixSockets

### operating system

macOS  12.6
Darwin gcc104.fsffrance.org 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101 arm64

**Comment by st3fan** [comment] 2023-09-08 01:33
I can't reproduce this on macOS 13.5.1

```
uname -a
Darwin Defiant.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:52 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103 arm64
```

```
src/curl --version
WARNING: this libcurl is Debug-enabled, do not use in production

curl 8.3.0-DEV (aarch64-apple-darwin22.6.0) libcurl/8.3.0-DEV SecureTransport zlib/1.2.11 libidn2/2.3.4 nghttp2/1.55.1
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS Debug HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TrackMemory UnixSockets
```

(SecureTransport vs LibreSSL)

You do not have `ip6-localhost` in your `/etc/hosts` ?

**Comment by bagder** [comment] 2023-10-19 12:25
cannot reproduce on newer macOS versions. @dfandrich should we just close this and move on or what do you think?

**Comment by dfandrich** [comment] 2023-10-19 18:13
I think I figured it out. The host has a `search` line in `/etc/resolv.conf` that points to a domain name that must have a wildcard entry. *Any* hostname will match and get an address. A dotted name bypasses the wildcard entry so it fails to resolve, as expected. I don't see how curl could do anything about this. Thanks for verifying that `server/resolv` is working.

**Closed** 2023-10-28 00:26 UTC
Labels: tests
