### ISSUE TITLE
Missed to modify member variable name

### ISSUE THREAD

**Issue by kuldeepSiemens** [curl/curl#13548] opened 2024-05-07 08:41 UTC
### I did this

Please find the explanation for issue found when updating from curl - 8.6.0 to curl - 8.7.0. which is causing build failure
- In file **lib/cf-socket.c**, Four member variables of **struct cf_socket_ctx** extracted in separate structure **struct ip_quadruple**.

![struct-cf_socket_ctx](https://github.com/curl/curl/assets/169130506/9ce97f33-f514-479e-b752-11234d81c728)

- This new extracted structure defined in file **urldata.h**.

![urldata](https://github.com/curl/curl/assets/169130506/26b53b48-cb56-418c-b6b8-96cd7235a86f)

- please find the below photo for change required in member variable call in curl - 8.6.0 and curl - 8.7.0

![diff](https://github.com/curl/curl/assets/169130506/2e73f01d-b8c7-4c00-9995-d661d9045ee2)

- In curl-8.7.0 version we have modified the member variable calls in same way every place but we missed to modify at one place. which is causing build error in Linux platform. please find below photo for missed place in **lib/cf-socket.c**,
![77](https://github.com/curl/curl/assets/169130506/0a12027e-64b0-4d31-8774-bb74243a1442)

- Please do the necessary changes in upcoming next curl version.

### I expected the following

- Please find below changes and solution for upcoming curl version to solve the build issue

![sol](https://github.com/curl/curl/assets/169130506/1f967326-0650-436f-9f6b-ac3fb8026ff4)

### curl/libcurl version

curl 8.7.0

### operating system

Linux

**Comment by bagder** [comment] 2024-05-07 08:58
Duplicate of #13210 fixed in d82869d7a5793ac6e14f4a4b1e0aed91528e6e0f

**Closed** 2024-05-07 11:15 UTC
Labels: build, outdated
