### ISSUE TITLE
Regression of curl --version and -V performance, takes 5 seconds after update

### ISSUE THREAD

**Issue by artem-zinnatullin** [curl/curl#8057] opened 2021-11-25 14:09 UTC
### I did this

I've installed `curl` (7.80.0) from Homebrew:

1. `brew install curl`
2. `export PATH="/opt/homebrew/opt/curl/bin:$PATH"`

While checking `curl --version` output to compare previous system installed version with the new one, I've noticed that `curl --version` now takes 5+ seconds!

```console
$ time curl --version 

curl 7.80.0 (arm-apple-darwin21.1.0) libcurl/7.80.0 (SecureTransport) OpenSSL/1.1.1l zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.46.0 librtmp/2.3 OpenLDAP/2.6.0
Release-Date: 2021-11-10
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets zstd

curl --version   0.02s  user 0.02s system 0% cpu 5.064 total
avg shared (code):         0 KB
avg unshared (data/stack): 0 KB
avg total memory:          0 KB
max memory:                8512 KB
page faults from disk:     223
other page faults:         685
```

Same with `-V`.

### I expected the following

I've expected `--version` to take few milliseconds, previous version I had that comes with macOS runs in 10ms

```console
$ time curl --version

curl 7.77.0 (x86_64-apple-darwin21.0) libcurl/7.77.0 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.42.0
Release-Date: 2021-05-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets

curl --version   0.00s  user 0.00s system 61% cpu 0.010 total
avg shared (code):         0 KB
avg unshared (data/stack): 0 KB
avg total memory:          0 KB
max memory:                3120 KB
page faults from disk:     2
other page faults:         359
```

### curl/libcurl version

7.80.10

[curl -V output]

```console
curl 7.80.0 (arm-apple-darwin21.1.0) libcurl/7.80.0 (SecureTransport) OpenSSL/1.1.1l zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.46.0 librtmp/2.3 OpenLDAP/2.6.0
Release-Date: 2021-11-10
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets zstd
```

### operating system

macOS 12.0.1 running on 2020 M1 Macbook Pro 13.

---

It's not only slow for humans, some provisioning scripts might be relying on `curl --version` and will degrade too.

**Comment by artem-zinnatullin** [comment] 2021-11-25 14:26
I think memory usage and memory paging difference between versions hints at something (modules are different too of course and idk how Apple builds `curl`).

Running `curl artemzin.com` (just as an example) yield in ~same performance ~180ms, but different memory usage too:

7.77.0:

```console
time curl artemzin.com
<html>
…
</html>

curl artemzin.com   0.01s  user 0.01s system 9% cpu 0.172 total
avg shared (code):         0 KB
avg unshared (data/stack): 0 KB
avg total memory:          0 KB
max memory:                4816 KB
page faults from disk:     0
other page faults:         468
```

7.80.0:

```console
time curl artemzin.com
<html>
…
</html>

curl artemzin.com   0.01s  user 0.01s system 12% cpu 0.181 total
avg shared (code):         0 KB
avg unshared (data/stack): 0 KB
avg total memory:          0 KB
max memory:                7488 KB
page faults from disk:     8
other page faults:         660
```

**Comment by bagder** [comment] 2021-11-25 15:12
Cannot reproduce:
~~~
$ time /usr/local/opt/curl/bin/curl --version
curl 7.80.0 (x86_64-apple-darwin20.6.0) libcurl/7.80.0 (SecureTransport) OpenSSL/1.1.1l zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.46.0 librtmp/2.3 OpenLDAP/2.6.0
Release-Date: 2021-11-10
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets zstd

real    0m0.029s
user    0m0.011s
sys     0m0.008s

**Comment by divinity76** [comment] 2021-11-25 15:13
can you add a `strace time curl --version` on a gist or paste.debian.net or something?

**Comment by bagder** [comment] 2021-11-25 15:14
on macOS I believe you need to use dtruss:

    sudo dtruss curl --version

**Comment by deltamualpha** [comment] 2021-11-25 15:39
My brew copy on my new M1 is fast, as expected:

```
❯ time /opt/homebrew/opt/curl/bin/curl --version
curl 7.80.0 (arm-apple-darwin21.1.0) libcurl/7.80.0 (SecureTransport) OpenSSL/1.1.1l zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.46.0 librtmp/2.3 OpenLDAP/2.6.0
Release-Date: 2021-11-10
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets zstd
/opt/homebrew/opt/curl/bin/curl --version  0.01s user 0.01s system 85% cpu 0.027 total
```

**Comment by bagder** [comment] 2021-12-06 16:05
No further info received. Since it has been proven to work fine in several installations since, we presume this is a user-specific problem in their setup/environment/hardware. Closing.

**Closed by bagder** 2021-12-06 16:05 UTC
Labels: needs-info, cmdline tool, performance

**Comment by artem-zinnatullin** [comment] 2021-12-06 16:20
Apologies for delay with response, I no longer can reproduce it, the only thing I've done with laptop since then — reboot.

Weird.. if I stumble upon this again I'll try to do strace or dtruss.

Thanks for checking on your side and sorry for posting this quasi-flaky issue!
