### ISSUE TITLE
Typo in option CURLOPT_MAIL_RCPT_ALLLOWFAILS (3 "L")

### ISSUE THREAD

**Issue by flashcode** [curl/curl#10218] opened 2023-01-03 21:15 UTC
### I did this

Use the option `CURLOPT_MAIL_RCPT_ALLLOWFAILS` in a program that uses curl (note the 3 "L" in the name).

The option is defined in [curl.h](https://github.com/curl/curl/blob/master/include/curl/curl.h#L2111):

```C
  /* allow RCPT TO command to fail for some recipients */
  CURLOPT(CURLOPT_MAIL_RCPT_ALLLOWFAILS, CURLOPTTYPE_LONG, 290),
```

### I expected the following

Option has name: `CURLOPT_MAIL_RCPT_ALLOWFAILS` (only 2 "L": `ALLOW` + `FAILS`).

### curl/libcurl version

curl 7.87.0 (x86_64-pc-linux-gnu) libcurl/7.87.0 OpenSSL/3.0.7 zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.51.0 librtmp/2.3
Release-Date: 2022-12-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

### operating system

```
Linux anaconda 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux
```

### Suggested fix

I think for compatibility a new option should be added with the proper name and the current one could be deprecated (marked for removal in future).

**Comment by dfandrich** [comment] 2023-01-03 21:43
Dupe of #10047

**Comment by flashcode** [comment] 2023-01-03 22:45
Oh right, sorry, I looked for existing issues but forgot to check pull requests.

Then I close this issue.

**Closed** 2023-01-03 22:45 UTC
