### ISSUE TITLE
libcurl 7.52.1 unix socket option not working on ubuntu xenial  

### ISSUE THREAD

**Issue by mccormickt12** [curl/curl#1274] opened 2017-02-21 22:34 UTC
[ There are collections of known issues to be aware of:
  https://curl.haxx.se/docs/knownbugs.html https://curl.haxx.se/docs/todo.html ]

### I did this
Not a curl expert by any means, but from what I can tell curl 7.52.1 is not using the unix socket param

curl --unix-socket /var/run/docker.sock http://localhost/events -vvv

on system curl or 7.51.0 i see 

curl --unix-socket /var/run/docker.sock http://localhost/events -vvv
*   Trying /var/run/docker.sock...
* Connected to localhost (/var/run/docker.sock) port 80 (#0)
> GET /events HTTP/1.1
> Host: localhost
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Server: Docker/1.12.3 (linux)
< Date: Tue, 21 Feb 2017 22:24:00 GMT
< Transfer-Encoding: chunked
<

on 7.52.1 I see
* STATE: INIT => CONNECT handle 0x17a0f88; line 1413 (connection #-5000)
* Added connection 0. The cache now contains 1 members
*   Trying 127.0.0.1...
* TCP_NODELAY set
* STATE: CONNECT => WAITCONNECT handle 0x17a0f88; line 1466 (connection #0)
* connect to 127.0.0.1 port 80 failed: Connection refused
* Failed to connect to localhost port 80: Connection refused
* Closing connection 0
* The cache now contains 0 members
* Expire cleared
curl: (7) Failed to connect to localhost port 80: Connection refused

### curl/libcurl version
./curl -V
curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2g zlib/1.2.8
Protocols: http https
Features: Debug TrackMemory IPv6 Largefile NTLM SSL libz TLS-SRP UnixSockets HTTPS-proxy

### operating system
uname -r
4.4.0-62-generic

cat /etc/*rel*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by jay** [comment] 2017-02-21 22:49
https://github.com/curl/curl/compare/curl-7_52_0...curl-7_52_1
I'm not seeing a whole lot it could be, are you sure about the versions and can you try the latest build from the repo?

**Comment by frenche** [comment] 2017-02-21 22:56
Can't reproduce on 7.53.0-DEV using:
socat UNIX-LISTEN:/tmp/foo.sock TCP:localhost:80
curl -v --unix-socket /tmp/foo.sock http://localhost/

**Comment by jay** [comment] 2017-02-21 23:07
me neither, using 7.52.1 in Ubuntu 16.04 LTS
~~~
curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2j zlib/1.2.8 nghttp2/1.18.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy 
~~~

**Comment by mccormickt12** [comment] 2017-02-21 23:07
@isaac, i see the same issue when i do your socat/curl test (output
below).  If I get some time later, I will try with dev.

sudo hawkeye/foss/curl/dist/bin/curl -v --unix-socket /tmp/foo.sock
http://localhost/
sudo: unable to resolve host ubuntu-xenial-master: Connection timed out
* STATE: INIT => CONNECT handle 0x19ecf88; line 1413 (connection #-5000)
* Added connection 0. The cache now contains 1 members
*   Trying 127.0.0.1...
* TCP_NODELAY set
* STATE: CONNECT => WAITCONNECT handle 0x19ecf88; line 1466 (connection #0)
* connect to 127.0.0.1 port 80 failed: Connection refused
* Failed to connect to localhost port 80: Connection refused
* Closing connection 0
* The cache now contains 0 members
* Expire cleared
curl: (7) Failed to connect to localhost port 80: Connection refused

**Comment by mccormickt12** [comment] 2017-02-21 23:16
I actually updated from 7.51.0 to 7.52.1 . Still seeing the behavior described though

**Comment by jay** [comment] 2017-02-21 23:22
Is there something in your curlrc that could cause it? If you can do a bisect that would help. https://github.com/curl/curl/wiki/how-to-git-bisect

**Comment by mccormickt12** [comment] 2017-02-21 23:26
no curlrc as far as i know, i will try out the bisect

**Comment by mccormickt12** [comment] 2017-02-22 01:22
commit 0b8d682f81ee9acb763dd4c9ad805fe08d1227c0 is the commit causing the issue, based on the bisect
you guys probably haven't been able to repro so far because we are using these configure flags
    ./configure \
        --enable-shared=yes \
        --enable-static=no \
        --enable-http \
        --enable-https \
        --enable-unix-sockets \
        --enable-debug \
        --disable-ares \
        --disable-dependency-tracking \
        --disable-ftp \
        --disable-sftp \
        --disable-file \
        --disable-ldap \
        --disable-ldaps \
        --disable-rtsp \
        --disable-proxy \
        --disable-dict \
        --disable-telnet \
        --disable-tftp \
        --disable-pop3 \
        --disable-imap \
        --disable-smtp \
        --disable-rtmp \
        --disable-gopher \
        --disable-smb \
        --disable-ntlm-wb \
        --disable-manual

**Comment by jay** [comment] 2017-02-22 03:15
ah. I see it, [some of the code](https://github.com/curl/curl/blob/curl-7_53_0/lib/url.c#L6299-L6312) is in a ifndef CURL_DISABLE_PROXY. I think a good way to handle this would be move all the code in that proxy block into a helper function and then in create_conn

#ifdef USE_UNIX_SOCKETS
unix sockets stuff
#endif
#ifndef CURL_DISABLE_PROXY
if(!data->set.str[STRING_UNIX_SOCKET_PATH] etc) 
  create_conn_proxy_helper(foo)
#endif

**Comment by frenche** [comment] 2017-02-22 05:25
Ouch, thanks @jay for spotting this, I'll work on a fix asap (unless you have it figured-out already).
Thanks @mccormickt12 for reporting this.

**Comment by jay** [comment] 2017-02-22 06:41
no I don't have a fix worked out, that was just a hasty suggestion based on my personal belief that guards like that spread over so many lines make it harder to catch things like this during review. i had actually looked that commit over for a different reason after it was committed and it looked fine. it's very difficult to tell unless you expand many lines. that proxy block spans like 150 lines

**Comment by mccormickt12** [comment] 2017-02-23 05:39
Thanks for the help and being so responsive. I am not super knowledgable
about your release cycle and i know this isn't a major bug, but any idea on
a timeframe on when this will get out in a release? If it would help I
could look into it and make the change, but I imagine that would be more
work for everyone

**Comment by jay** [comment] 2017-02-23 06:29
> any idea on a timeframe on when this will get out in a release?

Not yet

> If it would help I could look into it and make the change

I think @frenche is already doing it

**Comment by bagder** [comment] 2017-02-23 07:18
@mccormickt12 I believe there's a quick and super-easy work-around for you until then: don't disable proxy functionality

**Comment by frenche** [comment] 2017-02-23 20:34
Ok, I think I'll start with a simple fix, based on @jay's suggestion, but then I'd like to investigate why we disable proxy on unix-socket connections, I think there is no reason not to support it.

@Lekensteyn any thoughts? Thanks.

**Comment by bagder** [comment] 2017-02-24 08:15
@frenche that association certainly is wrong. unix domain socket support should not be bundled with proxy support!

**Comment by frenche** [comment] 2017-02-24 08:29
@bagder I'm not talking about the ifdef bug, this I'm fixing right now.

I'm talking on current design that when using unix-socket, then proxy is disabled in the code, and I'm not sure I understand why, see:
https://github.com/curl/curl/blob/curl-7_53_0/lib/url.c#L6302

**Comment by bagder** [comment] 2017-02-24 08:33
Ah, sorry. Yes well I can take guess why this was made like this: if unix-socket is used to reach the target server, the proxy will not be used. So unix-socket is then used as a shortcut to always reach the server so proxy is disabled. I'm not saying I completely agree with this.

I think instead unix-sockets should be made as a shortcut to the *connecting* to whatever curl is connecting to, so with unix-sockets specified together with a proxy we'd expect the unix-socket to be the way to reach the proxy and not the server.

Makes sense?

**Comment by frenche** [comment] 2017-02-24 09:57
@bagder, makes perfect sense to me, the unix-socket can be used to connect to a proxy, I'll give it a try.

Meanwhile, I've made a fix for the ifdef issue, @mccormickt12, mind checking if it works for you:
https://github.com/frenche/curl/commit/f7f7ece82e44a96f146add437200b64707714bec

**Comment by frenche** [comment] 2017-02-24 11:13
Here is a new version of the fix, including support for connecting to a proxy via unix-socket:
https://github.com/frenche/curl/commit/b7e989788782b434f2187bc0fc2c864f956093d6

To test proxy, I've configured mod_proxy on port 8181 and started socat listening on a unix socket and streaming to the proxy, like this:
socat UNIX-LISTEN:/tmp/foo.sock,fork TCP:localhost:8181

Then, I run the below to connect via the proxy:
curl -v --unix-socket /tmp/foo.sock -x http://abc  https://target/ -k

Works as expected with the new version of the fix.

**Comment by Lekensteyn** [comment] 2017-02-24 20:40
The reason why proxy support was disabled for Unix sockets is because the original use case did not have a realistic scenario for proxy support combined with Unix sockets (and taking a shortcut was easier). Proxies are implemented as additional layer between "the user" and "the protocol" (HTTP over TCP/IP). Unix sockets were considered an alternative connector between "the user" and "the protocol".

You can add proxying support after the Unix socket (and before "the protocol"), but that is quite a special case since you must not create a custom IP socket (which would act as proxy). If there is not a realistic use case for HTTP proxies over a Unix socket, I guess it is better not to add it (unless some strong tests are added).

**Comment by frenche** [comment] 2017-02-24 21:06
Thanks for your input, I think it depends how you look at the feature, what it actually does is allowing  to stream the data over a unix-socket instead of using the network, that could be applied to proxy connections as well.
See the example above his it is fixed to support proxy connections and how it solves an example use case, which I think is perfectly valid.

**Comment by jay** [comment] 2017-02-25 08:07
I'm not opposed to the added functionality with this fix but I think it's a fair question why anyone would want to do that. Isn't the point of these sockets less overhead and doesn't that just create an extra step ie more overhead? Like why not just bypass the socket and do `curl -v -x http://abc https://target/ -k`. It seems you _are_ going over tcp with socat to reach the proxy... aren't you?

Also is there a way to write a test for the new functionality, maybe there is an existing similar test that you could build off of?

**Comment by frenche** [comment] 2017-02-25 09:07
On Sat, Feb 25, 2017 at 10:07 AM, Jay Satiro <notifications@github.com> wrote:
> I'm not opposed to the added functionality with this fix but I think it's a
> fair question why anyone would want to do that. Isn't the point of these
> sockets less overhead and doesn't that just create an extra step ie more
> overhead? Like why not just bypass the socket and do curl -v -x http://abc
> https://target/ -k. It seems you are going over tcp with socat to reach the
> proxy... aren't you?

I doubt the benefit of unix-socket is merely to save overhead of
network in fact I'd assume tcp connection to localhost to have about
the same low overhead since the OS knows it is not really going over
the network.
IMO the idea to allow using unix-socket may have many useful
applications for security, tunneling, debugging etc.
The same ideas could be applied to proxy connections and I see no
reason to limit the feature the way it is today.
I used socat and mod_proxy to demonstrate, but one can think of a
proxy daemon listening on a unix-socket while having a secure access
to the network so only users with permissions could connect thru it to
some applications (after authentication maybe, etc).

> Also is there a way to write a test for the new functionality, maybe there
> is an existing similar test that you could build off of?

I'll try but it may take a while and I wouldn't want to hold the ifdef
bug-fix so I'd suggest to merge the first version of the fix for now.

**Comment by bagder** [comment] 2017-02-25 10:52
> it's a fair question why anyone would want to do that

I don't think we need to answer that. I think we should offer unix-domains to skip TCP as a connection/stream method, and I don't see a reason to limit that to a server and prevent it from being done to a proxy. From curl's point of view, there's very little difference.

**Comment by Lekensteyn** [comment] 2017-02-25 14:28
Fixing Unix domain sockets when proxy support is disabled sounds good, can you prepare a PR for that? (Also, fix the typos in the commit message while at it.)

Adding support for proxies behind a Unix domain socket is a different feature that need tests. There was a real-world use case for the original patch (accessing PHP-FPM which was listening on a Unix socket). Feel free to propose a patch if you have a similar real-world use-case for proxies behind Unix sockets (socat does not count).

**Comment by frenche** [comment] 2017-02-25 15:05
On Sat, Feb 25, 2017 at 4:28 PM, Peter Wu <notifications@github.com> wrote:
> Fixing Unix domain sockets when proxy support is disabled sounds good, can
> you prepare a PR for that? (Also, fix the typos in the commit message while
> at it.)

Agree, let's first fix the regression, opened  #1289

> Adding support for proxies behind a Unix domain socket is a different
> feature that need tests. There was a real-world use case for the original
> patch (accessing PHP-FPM which was listening on a Unix socket). Feel free to
> propose a patch if you have a similar real-world use-case for proxies behind
> Unix sockets (socat does not count).

I think the use case proposed is perfectly valid, and that proxy
should not be disabled when streaming thru unix-socket, instead the
unix-socket should be used to connect to the proxy as suggested.

**Comment by jay** [comment] 2017-02-25 23:44
> IMO the idea to allow using unix-socket may have many useful applications for security, tunneling, debugging etc. The same ideas could be applied to proxy connections and I see no reason to limit the feature the way it is today. I used socat and mod_proxy to demonstrate, but one can think of a proxy daemon listening on a unix-socket while having a secure access to the network so only users with permissions could connect thru it to some applications (after authentication maybe, etc).

I see. You are saying something such as Tor could setup a unix domain socket proxy and then curl should be able to communicate over that.

> let's first fix the regression, opened #1289

Fixed in 1f8023c, thanks again.

> I think the use case proposed is perfectly valid, and that proxy should not be disabled when streaming thru unix-socket, instead the unix-socket should be used to connect to the proxy as suggested.

Ok, after researching this issue I think that makes sense. Please submit a separate PR. The test may be a little difficult, I don't know if there is httpproxy unix socket. See f1cc2a2 for how unix socket support was implemented in runtests, you'll need to make a %HTTPPROXYUNIXPATH I think?

**Closed by jay** 2017-02-25 23:44 UTC
Labels: connecting & proxies

**Comment by rjkmurray** [comment] 2017-03-03 21:06
Proxy port to 000.000.000 you are a ghost.

**Comment by rjkmurray** [comment] 2017-03-03 21:10
I kid the repository  is called badger and has ways to enforce proxy
