### ISSUE TITLE
init_resolve_thread() failed for ; Cannot allocate memory

### ISSUE THREAD

**Issue by XinrongHuang** [curl/curl#5481] opened 2020-05-29 03:46 UTC
### I did this
1) Cross-compile dynamic libraries
CPPFLAGS="-I/home/xin/Downloads/openssl/install -I/home/xin/Downloads/openssl/install/include" LDFLAGS="-L/home/xin/Downloads/openssl/install/lib" LIBS="-ldl -lssl -lcrypto"  ./configure --with-ssl\
        --disable-dict\
        --disable-ftp\
        --disable-imap\
        --disable-ldap\
        --disable-ldaps\
        --disable-pop3\
        --disable-proxy\
        --disable-rtsp\
        --disable-smtp\
        --disable-telnet\
        --disable-tftp\
        --disable-zlib\
        --without-ca-bundle\
        --without-gnutls\
        --without-libidn\
        --without-librtmp\
        --without-libssh2\
        --without-nss\
        --without-zlib\
        --enable-shared\
        --enable-static\
        --host=arm-himix200-linux\
        CC=arm-himix200-linux-gcc\
        CXX=arm-himix200-linux-g++ --prefix=$PWD/__install

2) run multi-formadd.c sample
### I expected the following
init_resolve_thread() failed for ; Cannot allocate memory
### curl/libcurl version
7.71.0-DEV
[curl -V output]

### operating system
Linux (none) 4.9.37 #4 SMP Fri Jan 3 01:09:39 PST 2020 armv7l GNU/Linux

**Comment by XinrongHuang** [comment] 2020-05-29 04:27
I changed to version 7.70.0 with the same result

**Comment by jay** [comment] 2020-05-29 07:03
I can't find that error message, do you know where it is from? `printf("%s\n", curl_version());` and double check that you're using the expected version.

**Comment by bagder** [comment] 2020-05-29 07:14
I suspect this is related to your target or cross-compiled setup or something - pthread issue? Try running the same example on your  x86 Linux host to compare.

**Comment by bagder** [comment] 2020-06-01 15:26
There is nothing in this issue we can act upon. We need more evidence or indications of this being an actual curl problem or we will close this issue soon.

**Comment by XinrongHuang** [comment] 2020-06-02 01:37
I used the version of curl, 7.53.0-dev, and the same problem occurred on the command line. Was the version of the SSL library wrong when I compiled it?I'm openssl version "openssl 1.0.2l 25 May 2017"

**Comment by XinrongHuang** [comment] 2020-06-03 03:34
I used the command line to test, send HTTPS request, use the -k option can normal request, do not use the -k option will be wrong, is there something wrong with my openssl?

**Comment by bagder** [comment] 2020-06-03 06:04
Your curl version is old. Your OpenSSL version is end-of-lifed. Using `-k` is wrong an insecure. See the [SSLCERTS](https://curl.haxx.se/docs/sslcerts.html) doccument.

But... the fact  that it didn't fail with a "Cannot allocate memory" would indicate that problem isn't caused by libcurl.

**Closed** 2020-06-22 18:19 UTC
Labels: name lookup
