### ISSUE TITLE
Failed to connect via HTTP3 while browser is able to connect

### ISSUE THREAD

**Issue by D4v1dH03** [curl/curl#6868] opened 2021-04-07 23:25 UTC
### I did this
Tried to connect to any host (e.g. Google) that supports http3, both directly via the `--http3` flag and the `alt-svc` method

But the connection failed with curl error 7 (resource temporarily unavailable) 

I do not have any firewalls or any other traffic filtering or blocking on my home network because the Firefox browser can connect via HTTP3 but curl cannot.
### I expected the following
The connection succeeds without error
### curl/libcurl version
curl 7.76.1-DEV (x86_64-pc-linux-gnu) libcurl/7.76.1-DEV
[curl -V output]
```
curl 7.76.1-DEV (x86_64-pc-linux-gnu) libcurl/7.76.1-DEV GnuTLS/3.7.1 zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) nghttp2/1.44.0-DEV ngtcp2/0.1.0-DEV nghttp3/0.1.0-DEV libgsasl/1.8.1
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsyncDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Largefile libz Metalink NTLM NTLM_WB PSL SSL TLS-SRP unixSockets zstd
```
### operating system
```
Linux Fedora 5.11.1-300.fc34.x86_64 #1 SMP Tue Mar 30 16:37:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by icebluey** [comment] 2021-04-08 01:28
Duplicate of #6864 sort of.

**Comment by bagder** [comment] 2021-04-08 06:31
Duplicate of #6864 yes

**Closed by bagder** 2021-04-08 06:31 UTC
