### ISSUE TITLE
HTTP2 vs SSLv2 and the -2 command line option

### ISSUE THREAD

**Issue by perlun** [curl/curl#3150] opened 2018-10-19 08:20 UTC
### I did this

```shell
$ curl http://localhost:10003 -v -2
```

### I expected the following

An HTTP/2 request to be made.

Instead, an _SSLv2_ request was attempted.

Of course, listing the command line options quickly showed me what the correct option for http2 would be:

```
$ curl -h | grep 2
     --connect-to <HOST1:PORT1:HOST2:PORT2> Connect to host
     --http2         Use HTTP 2
     --http2-prior-knowledge Use HTTP 2 without HTTP/1.1 Upgrade
     --oauth2-bearer <token> OAuth 2 Bearer Token
     --post302       Do not switch to GET after following a 302
 -2, --sslv2         Use SSLv2
     --tlsv1.2       Use TLSv1.2
```

### I suggest the following change to curl to be made

[RFC 6176](https://tools.ietf.org/html/rfc6176) (dated 2011) bans the usage of SSL 2.0, which has been deprecated all the way since 1996 (!) when SSL 3.0 was introduced (which is also outdated at the time of writing.) Our current command line option, which gives precedence to SSL 2.0 over HTTP 2 (by providing a short-form of the getopt option for SSL 2.0) does not, in my opinion, make sense. We should adjust `curl` to let `-2` be a shorthand for `--http2` instead, since HTTP 2 is definitely a much more forward-looking technology than SSL 2.0.

> (We could even consider dropping support for SSL 2.0 altogether, but that's a separate can of worms that I'm not intending to open at this very moment - there _might_ be good reasons for keeping it; I do not know.)

Adding `-2` as shorthand for `--http2` is likely to be a trivial change and I can volunteer to make a PR about this if there is public approval for it, but I wanted to file this issue first to avoid spending time on something that could get rejected.

### curl/libcurl version

```
curl 7.61.0 (x86_64-pc-linux-gnu) libcurl/7.61.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.34.0 librtmp/2.3
Release-Date: 2018-07-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

### operating system

```
$ uname -a
Linux alladin 4.18.0-2-amd64 #1 SMP Debian 4.18.10-2 (2018-10-07) x86_64 GNU/Linux
```

**Comment by bagder** [comment] 2018-10-19 11:52
I can't recall us *ever* having repurposed a command line switch like this during our entire history, and I'm very hesitant to start now.

1. While SSLv2 is dead and gone from the public Internet there's no way for us to truly say how common it still is in private legacy environments. There's at least a certain amount of old documentation and command line examples still around using the option.
2. I don't consider this to be a particularly big win.
3. curl is already using "2TLS" as default, meaning that for HTTPS connections curl will already by default try to use HTTP/2, which only leaves non-HTTPS users to use this option and that's not widely used over the Internet at least

**Comment by danielgustafsson** [comment] 2018-10-19 12:01
I think repurposing an option, that hasn't been deprecated and removed for X years, would break the stability "contract" that curl offers. There would have to be a substantial gain to warrant that IMO.

**Comment by bagder** [comment] 2018-10-19 22:37
Right. If we want to use `-2` for something else in the future, we first need to remove it carefully. Something like this:

1. add a plan to docs/DEPRECATED.md. We've sort of went with a 6 months pre-notification period so far.
2. document it clearly as deprecated DO NOT USE in the documentation (the short version option that is)
3. add a warning message if it is used
4. remove the -2 short option for real in the release for real in maybe (no earlier than) April 2019
5. have a quarantine period where the option is unused (I'd suggest *at least* another 6 months, ideally longer)
6. then we can discuss what feature that is important enough to warrant us spending a short option letter on it! =)

**Comment by perlun** [comment] 2018-10-23 05:59
@bagder 

> I can't recall us _ever_ having repurposed a command line switch like this during our entire history, and I'm very hesitant to start now.

Fair enough, I can buy into some of that thinking. :wink: 

> 3\. curl is already using "2TLS" as default, meaning that for HTTPS connections curl will already by default try to use HTTP/2, which only leaves non-HTTPS users to use this option and that's not widely used over the Internet at least

I _think_ in my use case I am actually using HTTP/2 in non-HTTPS mode (I was doing some gRPC work, setting up a local java-grpc based server and playing out with sending a request to it, which I when I was surprised to find that the `-2` option didn't at all do what I expected from it... :laughing: The gRPC server logged that requests were being made using HTTP/1.1, which is not supported by the gRPC library I am using.)

----

What you're writing about putting the option in quarantine instead of dangerously just reusing it makes sense though. I _do_ think that reserving short options for things that have been deprecated (on the Internet) for the last 22 years is perhaps not optimal. If we (after careful consideration) decide to do something like this, are there perhaps other short options that could also be deprecated at the same time? I am thinking: so we avoid these kind of surprises multiple times; perhaps it's better to have one larger "spring cleaning" than cleaning a little all the time, in this case, to reduce the number of potential "surprise moments".

**Comment by bagder** [comment] 2018-10-23 06:33
> that reserving short options for things that have been deprecated (on the Internet) for the last 22 years is perhaps not optimal

The option was added almost 21 years ago and back then SSLv2 was still used and I did not foresee the SSL/TLS future development! =)

> are there perhaps other short options that could also be deprecated at the same time?

I'm sure we can dig up a few more. `-3` for SSLv3 is in a very similar situation. I'm pretty sure `-1` for "TLSv1" isn't going to be used much either going forward either.

I can also think of a few other basically never used options: `-t` (telnet options), `-N` (no buffering), `-B` (ascii mode), `-j` (start a new cookie session)

**Comment by perlun** [comment] 2018-10-25 05:28
> The option was added almost 21 years ago and back then SSLv2 was still used and I did not foresee the SSL/TLS future development! =)

Fair enough, I won't hold that against you @bagder :wink: 

As for next steps - would you be fine with a PR doing steps 1-3 (i.e. documenting these options as deprecated, warning about their usage)? Or do you think it needs to be discussed further before?

**Comment by kdudka** [comment] 2018-10-25 08:31
6 months of deprecation + 6 months of absence before recycling a commonly used command-line option for a completely different purpose does not help much for enterprise users because they upgrade curl to the latest upstream release once in a few years.

**Comment by bagder** [comment] 2018-10-25 09:13
Yeah, going down this route is scary - and you make a good point that 6 + 6 months is on the short side for this suggested progress. We should expand it.

The thing that saves even enterprise users here is when we do this for options that are truly **expected to not at all be in use anymore** and not just be rare. I can't believe that even enterprise users are using SSLv2 for example.

The ultimate question is probably *why* we should bother with this at all. There's this small gain in that we can get a short option freed up to use again in a future to compared with the risk that a few scripts and command lines somewhere start to fail somewhere (and that only posts online go bad).

Maybe a good topic for curl up 2019... =)

**Comment by dm8tbr** [comment] 2018-10-25 09:56
I can see both sides as important.
I wonder if such convenience options (as that's what it's about, quick access, less typing) could have mappings. By default a mapping that never reassigns things. Upon *explicit* user consent (environment variable, command line option) other mappings like -2 for HTTP/2.
This would enable two things:

- introducing updated short mappings
- 'themed' short mappings

There is an inherent risk. If people write their "my greatest ever guide to cURL" and *forget* to mention they turned on the `--general-mapping-2019` or such in their `.profile`.

Thoughts? Certainly not something to decide hastily.

**Comment by vszakats** [comment] 2018-10-25 12:03
I'm in favour of planned/documented deprecation in general, but _repurposing_ an existing option for something different seems to result in much confusion and worse: unintended results for users, _without being aware of it_. 

So, while it's tempting to free-up easy-to-type/remember short options, it probably isn't worth the troubles it will cause. Repurposing may be reasonable in case an option has only been introduced as "experimental", and in recent versions (making its initial fluid status clear from the get go and usage likely to be low anyway).

Options that make no sense anymore or are deemed dangerous, IMO should be made dummies and new/fixed/altered functionality be introduced under new option names.

**Comment by bagder** [comment] 2018-11-26 12:14
Closing this since this is not a bug and while we can possibly working on deprecating some options long-term, that is better done as a PR or perhaps a discussion for the mailing list. It is hard to see that we can *ever* repurpose a command line option without a significant risk that it will cause problems to someone, somewhere, and it is probably just not worth that.

**Closed by bagder** 2018-11-26 12:14 UTC
Labels: cmdline tool
