### ISSUE TITLE
git clone fails with http2 since 8.1.0 for a specific repo

### ISSUE THREAD

**Issue by lazka** [curl/curl#11201] opened 2023-05-25 07:11 UTC
### I did this

* `git clone --mirror https://chromium.googlesource.com/angle/angle.git`

It never finishes on Arch Linux and fails with `error: RPC failed; HTTP 499 curl 18 HTTP/2 stream 7 was reset` on Windows/MSYS2.

* Downgrading to 8.0.1 makes things work again
* Forcing git to use HTTP 1.1 makes things work again (`git config --global http.version HTTP/1.1`)

### I expected the following

The clone to work

### curl/libcurl version

```
curl 8.1.1 (x86_64-pc-linux-gnu) libcurl/8.1.1 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.53.0
Release-Date: 2023-05-23
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

### operating system

Arch Linux Docker container on Ubuntu

`Linux 6093131048a6 6.2.0-20-generic #20-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  6 07:48:48 UTC 2023 x86_64 GNU/Linux`

**Comment by icing** [comment] 2023-05-25 07:59
Thanks for the report. I am setting up to reproduce.

**Comment by nekopsykose** [comment] 2023-05-25 08:19
i ran into the same, the fix from https://github.com/curl/curl/issues/11194 fixes it for me (i.e. it seems to be a dupe of that, even though the issue is different). my testcase was `git clone https://chromium.googlesource.com/v8/v8` with 8.1.1 (not sure why only googlesource fails with this, haha)

@lazka you should test https://github.com/curl/curl/commit/5c58cb0212bcf63cce33a974906bf9905948b4bb applied on 8.1.1

**Comment by lazka** [comment] 2023-05-25 08:23
> @lazka you should test [5c58cb0](https://github.com/curl/curl/commit/5c58cb0212bcf63cce33a974906bf9905948b4bb) applied on 8.1.1

I can give that a try later today

**Comment by icing** [comment] 2023-05-25 08:53
Thanks @nekopsykose! I can confirm, with a local built git and libcurl 8.1.1 the command hangs. Using curl `master` it runs through.

**Comment by nekopsykose** [comment] 2023-05-25 19:57
yeah, forgot to mention that part, just had to remove all the tests from the diff first

**Comment by icing** [comment] 2023-05-26 07:26
Thanks for confirming the fix!

**Closed by icing** 2023-05-26 07:26 UTC
