### ISSUE TITLE
HTTP/2 connection reuse is broken in 7.49.1

### ISSUE THREAD

**Issue by gevaerts** [curl/curl#855] opened 2016-06-02 18:54 UTC
curl --http1.1 -v https://http2bin.org/get https://http2bin.org/get
curl --http2 -v https://http2bin.org/get https://http2bin.org/get

The problem is that the version detection in lib/http.c around line 3310 assumes HTTP/major.minor, and 8243a958 changes that, so HTTP/2 gets detected as 10, which then makes a lot of code fall back to HTTP/1.0 behaviour such as connection closing.

Note that 8243a958 was committed between 7.49 and 7.49.1, so the current released version (7.49.1) is affected.

**Comment by bagder** [comment] 2016-06-02 19:05
Ouch. And no test caught it... =( I guess it also tells us we should add a test for this together with the fix.

**Comment by gevaerts** [comment] 2016-06-02 19:33
(found by adu on irc, by the way, not by me)

**Comment by andydude** [comment] 2016-06-02 22:26
I (I'm adu on irc) have a fix for this, but I'm still running the tests to see if there are any regressions.

**Comment by jay** [comment] 2016-06-05 07:22
We fixed this in 1aa899f, thanks.

**Closed by jay** 2016-06-05 07:22 UTC
Labels: connecting & proxies, HTTP, HTTP/2

**Comment by Jesin** [comment] 2016-07-09 23:47
This also caused the `-L`/`--location` flag to be ignored when curl 7.49.1 uses HTTP/2. This has broken a few scripts. The flag seems to work again as of f9eed596a3115e583a124ccf7f929573ee5a7da4. Would this be worth making another bugfix release, or is 7.50 close to finished?

**Comment by bagder** [comment] 2016-07-10 19:05
I don't see how this should cause the `--location` to get ignored, that sounds like a separate issue!

7.50.0 is due to be released on July 21 so there will be no 7.49.X patch release before that.

**Comment by jay** [comment] 2016-07-11 01:19
@bagder It looks as though that was a symptom of the parsing bug. When http2 status parsing failed the code [defaulted to 200](https://github.com/curl/curl/blob/curl-7_49_1/lib/http.c#L3333) (ouch indeed).

**Comment by GitBubble** [comment] 2016-07-11 03:58
c来自我的华为手机-------- 原始邮件 --------主题：Re: [curl/curl] HTTP/2 connection reuse is broken in 7.49.1 (#855)发件人：Jay Satiro 收件人：curl/curl 抄送：@bagder It looks as though that was a symptom of the parsing bug. When http2 status parsing failed the code defaulted to 200 (ouch indeed).
