### ISSUE TITLE
curl version 7.62.0 adds DNS retry and timeout_time is long case ANR when exiting.  How to control DNS retry timeout time.connect_timeout only  has an effect on first resolve.

### ISSUE THREAD

**Issue by DaisyMoney** [curl/curl#3691] opened 2019-03-20 02:36 UTC
### curl/libcurl version

[curl -V output]

**Comment by DaisyMoney** [comment] 2019-03-20 03:03
step 1: set connect_timeout time:5 seconds. curl_easy_setopt(m_curlHandle, CURLOPT_CONNECTTIMEOUT_MS, 5000);
step 2: curl_easy_setopt(m_curlHandle, CURLOPT_URL, "http://www.player.com/networksimulator/services/index.m3u8"); the domain"www.player.com"cannot be resolved.
we find curl first resolved host timed out after 5 seconds,then retry,but it takes about 24 seconds.

Line 2060: 03-20 09:48:27.975 D/Epplib  (10618) Curl info:Resolving timed out after 5000 milliseconds
Line 5416: 03-20 09:48:51.037 D/Epplib  (10618) Curl info:Could not resolve host: www.player.com

then I retry.double connect_timeout time.
step 3: set connect_timeout time:10 seconds. curl_easy_setopt(m_curlHandle, CURLOPT_CONNECTTIMEOUT_MS, 10000);
step 2: curl_easy_setopt(m_curlHandle, CURLOPT_URL, "http://www.player.com/networksimulator/services/index.m3u8"); the domain"www.player.com"cannot be resolved.

first resolved host timed out after 10 seconds,then retry,but it takes about 16seconds.
Line 7131: 03-20 09:49:01.539 D/Epplib  (10618) Curl info:Resolving timed out after 10000 milliseconds
Line 7714: 03-20 09:49:17.821 D/Epplib  (10618) Curl info:Could not resolve host: www.player.com

curl version:7.62.0

**Comment by jay** [comment] 2019-03-20 03:12
This sounds like #2975. curl waits for the resolver thread to complete which means it's most likely waiting for getaddrinfo to return since that call is blocking.

**Comment by DaisyMoney** [comment] 2019-03-20 03:49
> This sounds like #2975. curl waits for the resolver thread to complete which means it's most likely waiting for getaddrinfo to return since that call is blocking.

Yes,it looks like. we use "Easy interface",and it happens ANR when exiting

**Comment by DaisyMoney** [comment] 2019-03-20 07:02
**I did this**

> I change curl version from 7.62.0 to 7.58.0

step 1: set connect_timeout time:5 seconds. curl_easy_setopt(m_curlHandle, CURLOPT_CONNECTTIMEOUT_MS, 5000);
step 2: curl_easy_setopt(m_curlHandle, CURLOPT_URL, "http://www.player.com/networksimulator/services/index.m3u8"); the domain"www.player.com"cannot be resolved.
I found version 7.58.0 resolved host timed out after 5 seconds , And did not retry.
03-20 14:53:13.208 D/Epplib  ( 8142) Curl info:Resolving timed out after 5515 milliseconds 

**curl/libcurl version** 7.58.0

operating system

**Comment by bagder** [comment] 2019-03-20 12:05
Duplicate of #2975

**Closed by bagder** 2019-03-20 12:05 UTC
Labels: name lookup
