### ISSUE TITLE
Slow to detect dead connections on Win10

### ISSUE THREAD

**Issue by pps83** [curl/curl#3722] opened 2019-04-03 00:13 UTC
I use 7.63 and I fund out that if libcurl tries to reuse stale connection it won't be able to complete request and instead will timeout. When I tried 7.64.1 I see that this isn't a problem anymore, it detects stale connections and recreates them. However, it takes 80ms for each stale connection to be detected that it's broken (on Win10). Can't libcurl see earlier when connections are reset by the remote host to avoid testing them later on?

Also, when I tried to use 7.64.1 I thought that it was some kind of DEV unreleased version because in 7.63 we had:
```
#define LIBCURL_VERSION "7.63.0"
#define LIBCURL_TIMESTAMP "2018-12-12"
```
and in 7.64.1 we have:
```
#define LIBCURL_VERSION "7.64.1-DEV"
#define LIBCURL_TIMESTAMP "[unreleased]"
```

So, I switched to 7.64 instead, but had a crash when I tried to test if it handles stale connections properly:

> Exception thrown: read access violation.
> data was nullptr.
```
>	Curl_failf(Curl_easy * data, const char * fmt, ...) Line 264	C
 	Curl_send_plain(connectdata * conn, int num, const void * mem, unsigned int len, CURLcode * code) Line 414	C
 	Curl_write_plain(connectdata * conn, unsigned int sockfd, const void * mem, unsigned int len, int * written) Line 438	C
 	Curl_schannel_shutdown(connectdata * conn, int sockindex) Line 2013	C
 	Curl_ssl_shutdown(connectdata * conn, int sockindex) Line 560	C
 	Curl_schannel_close(connectdata * conn, int sockindex) Line 1938	C
 	Curl_ssl_close(connectdata * conn, int sockindex) Line 555	C
 	Curl_disconnect(Curl_easy * data, connectdata * conn, bool dead_connection) Line 802	C
 	multi_done(Curl_easy * data, CURLcode status, bool premature) Line 620	C
 	multi_runsingle(Curl_multi * multi, curltime now, Curl_easy * data) Line 2024	C
 	curl_multi_perform(Curl_multi * multi, int * running_handles) Line 2217	C
```

also, 7.64.0 also has the same problems with curlver.h indicating that it's a unreleased dev version.

So,
 - is the stale connection bug fixed in 7.64.0/7.64.1?
 - is the data null ptr bug known and fixed (I've seen something similar in changelog, but not exactly the same).
 - can curl detect timeouts faster to avoid using stale connections?
 
and curlver.h should be fixed I guess.

**Comment by jay** [comment] 2019-04-03 02:31
> * is the stale connection bug fixed in 7.64.0/7.64.1?

This is unclear. You also said _"When I tried 7.64.1 I see that this isn't a problem anymore"_? Offhand I can't remember a similar issue. 4015fae ? Run a [bisect](https://github.com/curl/curl/wiki/how-to-git-bisect).

> * is the data null ptr bug known and fixed (I've seen something similar in changelog, but not exactly the same).

927a5bd fixed in 7.64.1

> * can curl detect timeouts faster to avoid using stale connections?

I'm pretty sure we're at the mercy of the OS.

> and curlver.h should be fixed I guess.

You'll see -DEV when you work from the repo. So if you work from tag curl-7_64_1 you'll see 7.64.1-DEV. You may also see it after that tag, until the next time it is updated. The releases from the [download page](https://curl.haxx.se/download.html) do not have -DEV. curl-7_64_1 source release for example:

~~~c
#define LIBCURL_VERSION "7.64.1"
#define LIBCURL_VERSION_MAJOR 7
#define LIBCURL_VERSION_MINOR 64
#define LIBCURL_VERSION_PATCH 1
#define LIBCURL_VERSION_NUM 0x074001
#define LIBCURL_TIMESTAMP "2019-03-27"
~~~

**Comment by pps83** [comment] 2019-04-03 04:56
> > * is the stale connection bug fixed in 7.64.0/7.64.1?
> 
> This is unclear. You also said _"When I tried 7.64.1 I see that this isn't a problem anymore"_? Offhand I can't remember a similar issue. [4015fae](https://github.com/curl/curl/commit/4015fae044ce52a639c9358e22a9e948f287c89f) ? Run a [bisect](https://github.com/curl/curl/wiki/how-to-git-bisect).
> 

I just re-tested and I can tell for sure that I do see this bug with 7.64.1. It seems that if I wait like 5 minutes then when libcurl tries to re-use existing connections it will see they are dead withing 80ms, but if I wait much longer then when it tries to use these stale connections it doesn't get any errors and simply times out (after very long time).

> > * can curl detect timeouts faster to avoid using stale connections?
> 
> I'm pretty sure we're at the mercy of the OS.

afaik if remote closes socket then we should receive some kind of event immediately without waiting 10 minutes. There is obviously possibility that connection was physically cut, in this case no notification is possible.

**Comment by jay** [comment] 2019-04-03 06:28
Can you experiment with some older versions and see if they show the same issue? Do you have a self contained example that can be used to reproduce?

**Comment by pps83** [comment] 2019-04-05 01:10
I'm testing now with 7.64.1 to see what's going on. So far I tried to use http and it seemed ok and detected dead connection instantly. testing now https to see if it's specific to https (I had that problem with https, but tested http with wireshark).

Is there a way to limit keepalive time that libcurl keeps connections open?

**Comment by pps83** [comment] 2019-04-05 05:22
I run some tests and I confirm that I observe the problem on the wire: if a connections stays idle for very long time then attempts to reuse it lead to lengthy retries:

![image](https://user-images.githubusercontent.com/1614246/55604874-d7a80f80-5726-11e9-8449-06cefb8a4a5b.png)

just to make sure, I tried both http and https and the problem is identical.
If connection stayed idle for 5-10 minutes, then attempts to reuse it result in almost instant reply from remote with a `RST`:

![image](https://user-images.githubusercontent.com/1614246/55605004-4edda380-5727-11e9-99f1-817f6cef154a.png)


So, it's definitely not an issue in curl, and doesn't seem to be os specific issue either. Anybody who tries to reuse connections that were idle for that long may end up with the same situation. Obviously browsers had that problem before and handle it properly somehow. Perhaps they limit time a connection can be kept alive. Any ideas what could be causing the problem and what can be done for a workaround? Could it be nat dropping associations and when unknown tcp packet comes without prior connection sequence and because of that `RST` from remote doesn't reach libcurl. It could be also that the server handles these requests differently if they were stale for a long time (however, I can't imagine that it would be any different from handling stale connections that were alive for 5-10 minutes).

**Comment by bagder** [comment] 2019-04-05 07:22
curl doesn't have a max-time for keeping the connections in the pool, which browsers typically have. I would not oppose introducing such a limit in curl. After the first few minutes, the chances of a (working) connection reuse has basically been reduced to zero.

**Comment by pps83** [comment] 2019-04-05 18:55
> curl doesn't have a max-time for keeping the connections in the pool, which browsers typically have. I would not oppose introducing such a limit in curl.

Can you please give some pointers where such code for keepalive timeouts should be implemented in curl?

**Comment by pps83** [comment] 2019-04-05 21:51
It seems that [CURLOPT_TCP_KEEPALIVE](https://curl.haxx.se/libcurl/c/CURLOPT_TCP_KEEPALIVE.html) can be used as a workaround. I tried it and I see each minute TCP keep-alive messages. What's interesting, is that I see these on one socket only! In wireshark I see like 5-10 opens sockets, only only one of them sends these keep-alives.

**Comment by bagder** [comment] 2019-04-06 20:57
> Can you please give some pointers where such code for keepalive timeouts should be implemented in curl

Keepalive? I was thinking about a max-time for connection reuse, so connections that are found to be older than NNN seconds would get closed instead and not attempted to get reused.

**Comment by pps83** [comment] 2019-04-08 02:38
> Keepalive? I was thinking about a max-time for connection reuse, so connections that are found to be older than NNN seconds would get closed instead and not attempted to get reused.

Sorry for confusion, that's what I was referring to. I think I'd be more comfortable with just closing connections than relying on keepalives.

One interesting observation as mentioned previously. I have 8 connections to my host, when TCP keepalive is enabled, win10 closes 7 sockets after a minute and sends keepalives only on one of them. I kind of like that behavior, but not sure if other platforms would behave the same.

**Comment by bagder** [comment] 2019-04-08 07:50
> I think I'd be more comfortable with just closing connections than relying on keepalives.

Right, and I think they both serve their individual purposes. (Or *would*, when/if we add a max-age option for the connection pool.)

> I have 8 connections to my host, when TCP keepalive is enabled, win10 closes 7 sockets after a minute and sends keepalives only on one of them. I kind of like that behavior, but not sure if other platforms would behave the same.

TCP keep-alive *should* send traffic over that TCP connection with some interval, the OS can not single-handedly decide to *not* do it for a few of them. In your case here, I presume those 7 connections are actually not maintained by the server end which is why they get closed due to keepalive.

**Comment by pps83** [comment] 2019-04-10 20:39
> TCP keep-alive _should_ send traffic over that TCP connection with some interval, the OS can not single-handedly decide to _not_ do it for a few of them. In your case here, I presume those 7 connections are actually not maintained by the server end which is why they get closed due to keepalive.

I don't know why the os does it that way, but after 1 minute of idle time, it clearly sends a keepalive for one socket and closes all other sockets to that host, eg has nothing to do with the server.

**Comment by bagder** [comment] 2019-04-13 10:35
Ok. I suppose this still falls down to: no visible bug in curl that causes this. It just happens that the TCP stack takes a little while to detect this. I will work on a adding a max idle time for the connection pool as a separate enhancement.

**Closed** 2019-05-12 14:17 UTC
Labels: connecting & proxies, not-a-bug
