### ISSUE TITLE
Crash when curl is used from inside an OpenSSL engine

### ISSUE THREAD

**Issue by qpernil** [curl/curl#6256] opened 2020-11-27 09:44 UTC
Hi!
The yubihsm-pkcs11 module internally uses the curl library, which on initialization calls CONF_modules_load_file to disable errors on missing config files (I presume). When yubihsm-pkcs11 is used by the openssl command through libengine-pkcs11-openssl on Ubuntu Focal or Groovy there is a crash in int_ctx_new (crypto/evp/pmeth_lib.c:171). This seems to happen because CONF_modules_load_file seems to be called twice in this case, once implicitly from openssl library initialization, and then again later when the pkcs11 engine initializes yubihsm-pkcs11, which calls curl_global_init, which in turn calls CONF_modules_load_file. Both calls use NULL as the config file name so they end up loading the default config file twice, and some debugging revealed that the EVP_PKEY_METHOD it finds contains an invalid function pointer in pmeth->init. It might be the fact that the pkcs11 engine gets loaded twice, but the second time it gets rejected because it is already registered with the same id, and subsequently freed. Maybe this freeing messes up some common state also used by the existing pkcs11 engine.

The command i use is

YUBIHSM_PKCS11_CONF=yubihsm_pkcs11.conf OPENSSL_CONF=engine.cnf openssl dgst -engine pkcs11 -keyform engine -sha256 -sign -label_xxx

I explicitly point to the following config file 'engine.cnf'

...
openssl_conf = openssl_init

[openssl_init]
engines = engines_section

[engines_section]
pkcs11 = pkcs11_section

[pkcs11_section]
engine_id = pkcs11
dynamic_path = /usr/lib/x86_64-linux-gnu/engines-1.1/pkcs11.so
MODULE_PATH = /usr/local/lib/pkcs11/yubihsm_pkcs11.so
PIN = 0001password
init = 0
...

And yubihsm_pkcs11.conf:

...
connector=http://localhost:12345
...

The line number comes from an openssl built with --debug from github branch OpenSSL_1_1_1-stable and installed to the default location /usr/local/lib (where it will be used by default).

The same crash happens in the openssl version that comes with Ubuntu Focal and Groovy, but not earlier Ubuntu releases.

**Comment by qpernil** [comment] 2020-11-27 09:49
I think the solution to this is for curl to call OPENSSL_init_ssl with an OPENSSL_INIT_SETTINGS that specifies the same flags to not error on missing config files that it now uses in the call to CONF_modules_load_file. The documentation and historical functionality of CONF_module_load_file seem to indicate it should work, but it clearly doesn't. I'm thinking the intent of the call is to avoid having applications using curl failing unexpectedly, but the current flags will still fail on errors in files it does find, so that goal is perhaps not fully achieved anyway... My proposed change shouldn't change that functionality, hopefully.

**Comment by qpernil** [comment] 2020-11-27 21:40
I have tested a modified version of curl that has the CONF_module_load replaced with OPENSSL_init_ssl with the same flags (to allow a missing config file) and that makes it work. So I think curl should use the 'modern' apis if openssl version is > 1.1.

**Comment by jay** [comment] 2020-11-28 07:36
This sounds like a duplicate of #6254 and I would guess is an OpenSSL issue. Looks like you guessed same openssl/openssl#13548

**Comment by qpernil** [comment] 2020-11-28 10:17
I think it is both. Curl might be better off not calling this function as there is a newer way of doing it that seems to work, see above. But I think openssl also has a bug that makes i thrash some internal structure if this is called twice.

**Comment by qpernil** [comment] 2020-11-28 11:26
In fact mattcaswell pointed out that not failing on conf errors is now the default in openssl, so I think there is no need to call anything if openssl >= 1.1.0 (or 1.1.1 if the default were not the same in 1.1.0) since the auto-initialization in openssl will just magically call all that is needed.

**Comment by bagder** [comment] 2020-11-28 11:35
It's really impossible to keep up with OpenSSL's ideas of how to init their library in different versions.

I read this as saying that with >= 1.1.0  we can set `CURL_DISABLE_OPENSSL_AUTO_LOAD_CONFIG` and it should behave better? Like this:
~~~diff
diff --git a/lib/vtls/openssl.c b/lib/vtls/openssl.c
index fc0c4e15f..dc121feb4 100644
--- a/lib/vtls/openssl.c
+++ b/lib/vtls/openssl.c
@@ -88,10 +88,14 @@
   !defined(OPENSSL_NO_ENGINE) && !defined(OPENSSL_NO_UI_CONSOLE)
 #define USE_OPENSSL_ENGINE
 #include <openssl/engine.h>
 #endif
 
+#if (OPENSSL_VERSION_NUMBER >= 0x10100000L) /* 1.1.0 or later */
+#define CURL_DISABLE_OPENSSL_AUTO_LOAD_CONFIG
+#endif
+
 #include "warnless.h"
 #include "non-ascii.h" /* for Curl_convert_from_utf8 prototype */
 
 /* The last #include files should be: */
 #include "curl_memory.h"

**Comment by qpernil** [comment] 2020-11-30 07:41
I think that for >= 1.1.0 you can skip ALL openssl init, also stuff that's not covered by that #define. So I think a better way of doing things would be to put everything within the existing check for OpenSSL version, something like this:

#if (OPENSSL_VERSION_NUMBER >= 0x10100000L) && \
    !defined(LIBRESSL_VERSION_NUMBER)
#else 

  OPENSSL_load_builtin_modules();

#ifdef USE_OPENSSL_ENGINE
  ENGINE_load_builtin_engines();
#endif

#ifndef CURL_DISABLE_OPENSSL_AUTO_LOAD_CONFIG
  CONF_modules_load_file(NULL, NULL,
                         CONF_MFLAGS_DEFAULT_SECTION|
                         CONF_MFLAGS_IGNORE_MISSING_FILE);
#endif

  /* Lets get nice error messages */
  SSL_load_error_strings();

  /* Init the global ciphers and digests */
  if(!SSLeay_add_ssl_algorithms())
    return 0;

  OpenSSL_add_all_algorithms();

#endif

**Comment by qpernil** [comment] 2020-11-30 07:42
But I have to add I haven't tested with OpenSSL 1.1.0, only 1.1.1

**Comment by bagder** [comment] 2020-11-30 08:32
I only have one concern with this: it's a rather big change and historically. changing *anything* in the OpenSSL init sequence will bounce back two months from now when someone has a special OpenSSL build/engine/config that we couldn't test now and that the (lacking) OpenSSL docs certainly don't cover and we have to backpedal again.

If we stick to *only* fix the module load (like #6260 ), it might be a too small fix but it also feels much more conservative and one with a bigger chance of not hitting someone in the face down the road...

**Comment by qpernil** [comment] 2020-11-30 08:41
I certainly understand those concerns. And this fixes it for me, I'm testing from the PR branch right now. Thx a lot !

**Comment by qpernil** [comment] 2020-11-30 10:34
Just a note, as you may see in the bug report I made to openssl (https://github.com/openssl/openssl/issues/13548) the correct way to initialize openssl >= 1.1.0. i.e. code that woks on both would be
OPENSSL_init_ssl(OPENSSL_INIT_LOAD_CONFIG, NULL);
(Thx to mattcaswell for this)

That code would be a no-op if the application using curl had already initialized openssl (which would happen automatically in many cases)

**Comment by bagder** [comment] 2020-11-30 13:13
ok, lets try that then... could be the start of an adventure! :smile:

**Comment by qpernil** [comment] 2020-12-02 07:57
May I ask what the future holds for this PR ? I'm wondering when it might make it into master and then further into a release.

**Comment by bagder** [comment] 2020-12-02 09:29
If you with "this PR" mean #6260, it will be landed as soon as we agree what the proper fix to be. If that happens before December 9, it will ship in the curl 7.74.0 release. If not, it will be be included in the subsequent release etc.

I don't see anything major preventing it from getting merged really soon.

**Closed** 2020-12-03 21:31 UTC
Labels: SSL/TLS, crash
