### ISSUE TITLE
libcurl version 7.52.1 is not compatible with axTLS version 2.1.2

### ISSUE THREAD

**Issue by gnanagurun** [curl/curl#1235] opened 2017-01-31 12:28 UTC
### I did this
When i tried to compile libcurl (7.52.1) with axTLS (2.1.2), i'm getting a lot of compilation issue. One of the main issue is the axtls library call "ssl_client_new()" whose function arguments are changed.
### I expected the following
When i can expect this compilation issues will be solved?
### curl/libcurl version
libcurl version is 7.52.1 and axTLS version is 2.1.2
[curl -V output perhaps?]

### operating system
Linux

**Comment by bagder** [comment] 2017-01-31 12:35
Duplicate of #1220

**Closed by bagder** 2017-01-31 12:35 UTC
Labels: build
