### ISSUE TITLE
CONNECT_ONLY connections can get closed when cache is full

### ISSUE THREAD

**Issue by loblik** [curl/curl#4369] opened 2019-09-17 14:47 UTC
There was a discussion recently about connection cache and CONNECT_ONLY connections. in this issue https://github.com/curl/curl/issues/3983#issuecomment-498570205_ . And I think I've just hit the same thing.

I use CONNECT_ONLY to establish the connection and then put filedescriptor in own event loop to do some websocket communication. Recently I've noticed that sometimes connection is closed when it's returned to cache. I think this makes CURLINFO_ACTIVESOCKET unusable since Curl_conncache_return_conn does not consider CONNECT_ONLY connection as in use.

Here an example to reproduce the issue.

```c
#include <curl/curl.h>
#include <unistd.h>
#include <fcntl.h>

void addNewConn(CURLM *multi)
{
    CURL *easyRaw = curl_easy_init();
    curl_easy_setopt(easyRaw, CURLOPT_URL, "https://curl.haxx.se/");
    curl_easy_setopt(easyRaw, CURLOPT_CONNECT_ONLY, 1L);
    curl_easy_setopt(easyRaw, CURLOPT_VERBOSE, 1L);

    curl_multi_add_handle(multi, easyRaw);
}

int main(void)
{

    CURLM *multi_handle = curl_multi_init();

    curl_multi_setopt(multi_handle, CURLMOPT_MAXCONNECTS, 1); 

    addNewConn(multi_handle);

    int still_running, repeats = 0, sockfd;

    for (;;)
    {   
      CURLMcode mc; 

      mc = curl_multi_perform(multi_handle, &still_running);

      if(mc == CURLM_OK ) { 

        struct CURLMsg *m; 

        int msgq = 0;
        m = curl_multi_info_read(multi_handle, &msgq);
        if(m && (m->msg == CURLMSG_DONE)) {
          CURL *e = m->easy_handle;
          if( repeats++)
            break;
          curl_easy_getinfo(m->easy_handle, CURLINFO_ACTIVESOCKET, &sockfd);
          printf("active socket socfd: %d\n", sockfd);
          addNewConn(multi_handle);
        }   

        mc = curl_multi_wait(multi_handle, NULL, 0, 1000, NULL);
      }   
    }   

    if (fcntl(sockfd, F_GETFD) < 0)
    {   
        printf("socfd: %d\n", sockfd);
        perror("fcntl");
    }   

    return 0;
}
```

**Comment by bagder** [comment] 2019-12-09 16:44
I don't see how this is a bug. This seems to work exactly as intended:

1. You limit libcurl to only keep **one** connection alive.
2. You issue a request that sets up a connect-only request , performs that and extracts the socket
3. You then create a new request, that cannot reuse the first connection and that runs.
4. When the second request completes, it puts it back in the connection cache, finds that it needs to "kill off" one to fit it within the set limit. It then closes the oldest.

Where is the error here?

**Comment by loblik** [comment] 2019-12-10 06:33
I have just set the cache size to one to make this easier to reproduce. But I've experienced this even with default setting. It behaves exactly as you described. The problem is the CONNECT_ONLY connections with extracted socket using CURLINFO_ACTIVESOCKET probably should not be closed (until curl_easy_cleanup is called). As this makes extracted socket unusable.

**Comment by bagder** [comment] 2019-12-10 09:17
The error here is probably that the connection should be treated as *in use* and thus shouldn't be considered for closing.

**Comment by loblik** [comment] 2019-12-10 11:32
Yes. I cannot reproduce it with that change anymore. Thanks

**Closed** 2019-12-11 08:27 UTC
Labels: connecting & proxies, needs-info-or-update
