### ISSUE TITLE
Failed post form data with error code 43

### ISSUE THREAD

**Issue by xinchao86** [curl/curl#2565] opened 2018-05-12 07:57 UTC
### I did this
I used the follow code to post form data, but it failed with error code 43.  It executed successful in another curl version platform with same code.
Fail curl version is this:
"
curl 7.50.1-DEV (Android 7.1.2 armv8-a) libcurl/7.50.1-DEV BoringSSL zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: IPv6 NTLM SSL libz UnixSockets
"
Success curl version is this:
"
curl 7.21.3 (arm-unknown-eabi) libcurl/7.21.3 OpenSSL/1.0.1j zlib/1.2.8
Protocols: http https
Features: IPv6 NTLM SSL libz
"
int main(void) {
    CURL *curl;
    CURLcode res;
    curl_global_init(CURL_GLOBAL_ALL);
    struct curl_httppost* post = NULL;
    struct curl_httppost* last = NULL;
    curl_formadd(&post, &last, CURLFORM_COPYNAME, "ICCID", CURLFORM_COPYCONTENTS, "0000000", CURLFORM_END);
    curl_formadd(&post, &last, CURLFORM_COPYNAME, "files", CURLFORM_FILE, "/sdcard/1.zip", CURLFORM_CONTENTTYPE, "application/octet-stream", CURLFORM_END);
    curl = curl_easy_init();
    if(curl) {
        curl_easy_setopt(curl, CURLOPT_URL, "http://xx.xx.xx.xxx/acquisitionservice/acq/system_data");
        curl_easy_setopt(curl, CURLOPT_HTTPPOST, post);
        res = curl_easy_perform(curl);
        if (res != CURLE_OK) {
            ALOGE("send: file uploade failed, error=%d", res);
        } else {
            ALOGD("send: file uploade success.");
        }
        curl_easy_cleanup(curl);
    }
    curl_formfree(post);
    curl_global_cleanup();
    return 0;
}
PS: Use curl command also fail in fail curl version platform.
"
msm8953_64:/ # curl -F "files=haha" "http://xx.xx.xx.xxx/acquisitionservice/acq/system_data"
curl: (43) A libcurl function was given a bad argument
"
### I expected the following
Stuck this , hope resolve! Tks!
### curl/libcurl version
curl 7.50.1-DEV (Android 7.1.2 armv8-a) libcurl/7.50.1-DEV BoringSSL zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: IPv6 NTLM SSL libz UnixSockets
[curl -V output]

### operating system
android 7.1.2

**Comment by monnerat** [comment] 2018-05-12 10:32
I do not have an Android, but I have tried to reproduce on Linux x86_64 in vain.
Since you try to use a development version almost 2 years old, it is very hard to know what precise code you are effectively running.
Maybe you should try with the latest stable version: the (now deprecated) formadd API code has been considerably changed and is now based on the new mime API.

**Comment by xinchao86** [comment] 2018-05-14 01:30
My curl code is 'https://github.com/xinchao86/Android-7.1.2-libcurl.git'. Please help to check it, I can't modify it casually because it is Android source code。I just try to use the code to post form data. Did the version code's api have changed? Could you show me how to use the new api? It's great if you list some sample code.

**Comment by bagder** [comment] 2018-05-14 06:04
@xinchao86 your libcurl code looks fine. You can verify this by building and trying it out on a Linux of your choice, as it should work the same there as on Android.

Also, enabled `CURLOPT_VERBOSE` and see if that gives any more clues.

**Comment by xinchao86** [comment] 2018-05-17 08:32
Can't make the curl in Linux. But I can make official  curl 7.50.1 in Linux, and it's no problem. So I think it's an android curl 7.50.1 version issue. I had merged curl 7.43.0 of CM 14.1 for fixing the issue.

**Comment by bagder** [comment] 2018-05-17 22:19
If you can't give us more details and we can't reproduce this problem (in a modern version), we might just as well close this issue.

**Comment by xinchao86** [comment] 2018-05-19 06:03
You can close the issue. Thank you for your help.

**Closed** 2018-05-19 09:08 UTC
