### ISSUE TITLE
Issue with FileZilla server (GnuTLS) and close_notify

### ISSUE THREAD

**Issue by jeanfremit** [curl/curl#11383] opened 2023-06-25 15:48 UTC
### I did this

I upload files via explicit FTPS (AUTH TLS) from a Windows client with curl 8.1.2 linked against OpenSSL 3.1.1, to a FileZilla server 1.7.2 hosted by a Windows box. 
When the data link uses Wifi or a mobile telephone network (3G/4G), I frequently encounter an issue where curl does not send the TLS alert close_notify, which triggers the wrath of GnuTLS in FileZilla server, and a FTP reply 426 ECONNABORTED. 

### I expected the following

I expected curl to send the TLS alert close_notify before closing the socket of the data channel

### curl/libcurl version
8.1.2

### solution

I have narrowed the issue  to two lines in vtls/openssl.c in ossl_close():

```C
(void)SSL_read( backend->handle, buf, sizeof buf);
(void)SSL_shutdown( backend->handle );
```

actually, SSL_shutdown() can fail. The OpenSSL documentation states that the caller should retry the call is the return value is less than zero, as long as the SSL error is SSL_ERROR_WANT_READ or SSL_ERROR_WANT WRITE. For me the following replacement code solved the issue:

```C
int res = SSL_read(  backend->handle, buf, sizeof buf);
int error = SSL_get_error(  backend->handle, res );
if (SSL_ERROR_SYSCALL != error) {
   int res = 0;
   while (res = (SSL_shutdown( backend->handle )) < 0) {
      error = SSL_get_error( backend->handle, res );
      if (error != SSL_ERROR_WANT_READ 
    && error  !SSL_ERROR_WANT ) 
        break;
   }
```
}

[curl -V output]

### operating system

WIndows for both Client and Server.

Best regards.

**Comment by icing** [comment] 2023-06-26 07:31
This looks as if it would block until the SSL stack is actually able to send the close notify. 

If the outgoing socket is "full", EGAIN is returned. SSL would convert that into an SSL_WANT_WRITE. This would then hang forever in a busy loop (we are non-blocking so this would 100% CPU) until the server reads from its end of the socket.

TLS close notify handling and merits have been debated for years. We treat *sending* it as a "best effort" before closing the socket. And that is what the code does. I think it disproportional to block before closing of the socket - at the mercy of the other end or a middle box. This would halt any other ongoing transfer in curl.

I believe this is not worth it. But I am no expert on FTP and its attack vectors.

**Comment by jeanfremit** [comment] 2023-06-26 08:35
Hello Stefan,
Thank you for your swift answer. I am no OpenSSL expert. Just placed a tracepoint after the call of SSL_shutdown() and discovered that it failed frequently in my particular setup (wobbly data link using WiFi or cellular phone network). Then I monitored the number of retries (still with a tracepoint) and found that a *single* retry always fixed the issue, and dispatched the TLS alert close_notify. It just happens to work for me. Limiting the number of iterations would probably make sense, though.About the close_notify alert mandated by TLSv1.3, I discovered that there is much controversy. But I talk to a FileZilla server using GnuTLS, which is adamant that it receive the close_notify before detecting socket closure.
If my humble suggestion does not make its way into the codebase, this not a big deal for me, I'll just check openssl.c in future versions of curl, and apply my patch for my own needs. I always build curl from sources, so this is not an issue.
With best regards,Alain


   Le lundi 26 juin 2023 à 09:31:29 UTC+2, Stefan Eissing ***@***.***> a écrit :  
 
 


This looks as if it would block until the SSL stack is actually able to send the close notify.

If the outgoing socket is "full", EGAIN is returned. SSL would convert that into an SSL_WANT_WRITE. This would then hang forever in a busy loop (we are non-blocking so this would 100% CPU) until the server reads from its end of the socket.

TLS close notify handling and merits have been debated for years. We treat sending it as a "best effort" before closing the socket. And that is what the code does. I think it disproportional to block before closing of the socket - at the mercy of the other end or a middle box. This would halt any other ongoing transfer in curl.

I believe this is not worth it. But I am no expert on FTP and its attack vectors.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  

|  | Virus-free.www.avast.com |

**Comment by 2i-mh** [comment] 2023-09-13 13:03
We actually do see this issue a lot, especially with FileZilla servers, but also with VSFTP (there, the server response is `426 Failure reading network stream`). Interestingly, this does not happen just at random and at instable wireless connections, but seems to depend solely on the file size and connection speed to the server - and repeated attempts at uploading a file of that particular size all fail in the same way.

In particular, I've seen one server where it is impossible to upload a file of size 9977696 bytes. The client always runs on windows 10 and I have no way to run a debug version of curl, just using the "official" windows binaries directly from the curl project. However I was able to debug this on the level of Winsock's `send` function - and in cases where the upload fails that way, it's always that the last `send` on the data connection fails with `WSAEWOULDBLOCK`. This of course also happens a lot already  during the actual upload of the file, but those `send`s are properly repeated after waiting for it to unblock, but the last one is not. It seems that this particular server is rather slow, and with just the right file size, the last `send` of the real file data just fills the socket's send buffer enough that the following `send` for the close notify is almost guaranteed to fail... 

So it would really be nice if a more robust attempt at sending the close_notify could be made.

**Comment by jay** [comment] 2023-09-13 20:23
> In particular, I've seen one server where it is impossible to upload a file of size 9977696 bytes. The client always runs on windows 10 and I have no way to run a debug version of curl, just using the "official" windows binaries directly from the curl project. However I was able to debug this on the level of Winsock's `send` function - and in cases where the upload fails that way, it's always that the last `send` on the data connection fails with `WSAEWOULDBLOCK`.

Try using [SSLKEYLOGFILE](https://everything.curl.dev/usingcurl/tls/sslkeylogfile) to confirm what is actually sent at the end

**Comment by 2i-mh** [comment] 2023-09-14 10:26
> Try using [SSLKEYLOGFILE](https://everything.curl.dev/usingcurl/tls/sslkeylogfile) to confirm what is actually sent at the end

OK, used `SSLKEYLOGFILE`  and wireshark. `172.XX.XX.XX` is my client, `77.YY.YYY.YY` is the server.

The working case looks like this (snapshot beginngin at the last 2 actaul file data TLS packets):
```
No.	Time	Source	Destination	Protocol	Length	Info
130	5.244832	172.XX.XX.XX	77.YY.YYY.YY	TLSv1.3	3392	Application Data
131	5.281730	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	53298 → 55043 [ACK] Seq=242 Ack=47150 Win=262656 Len=0
132	5.282844	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	53298 → 55043 [ACK] Seq=242 Ack=50054 Win=262656 Len=0
133	5.283045	172.XX.XX.XX	77.YY.YYY.YY	TLSv1.3	1772	Application Data
134	5.283487	172.XX.XX.XX	77.YY.YYY.YY	TLSv1.3	78	Alert (Level: Warning, Description: Close Notify)
135	5.283712	172.XX.XX.XX	77.YY.YYY.YY	TCP	54	55043 → 53298 [FIN, ACK] Seq=100864 Ack=242 Win=262400 Len=0
136	5.283933	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	53298 → 55043 [ACK] Seq=242 Ack=52958 Win=262656 Len=0
137	5.284270	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	53298 → 55043 [ACK] Seq=242 Ack=55862 Win=262656 Len=0
138	5.285178	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	53298 → 55043 [ACK] Seq=242 Ack=58766 Win=262656 Len=0
139	5.285824	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	53298 → 55043 [ACK] Seq=242 Ack=61670 Win=262656 Len=0
140	5.286305	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	53298 → 55043 [ACK] Seq=242 Ack=64574 Win=262656 Len=0
141	5.290533	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	53298 → 55043 [ACK] Seq=242 Ack=67478 Win=262656 Len=0
142	5.290533	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	53298 → 55043 [ACK] Seq=242 Ack=70382 Win=262656 Len=0
143	5.290533	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	53298 → 55043 [ACK] Seq=242 Ack=73286 Win=262656 Len=0
144	5.290533	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	53298 → 55043 [ACK] Seq=242 Ack=76190 Win=262656 Len=0
145	5.290533	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	53298 → 55043 [ACK] Seq=242 Ack=79094 Win=262656 Len=0
146	5.291260	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	53298 → 55043 [ACK] Seq=242 Ack=82716 Win=262656 Len=0
147	5.291970	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	53298 → 55043 [ACK] Seq=242 Ack=84168 Win=262656 Len=0
148	5.292395	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	53298 → 55043 [ACK] Seq=242 Ack=87072 Win=262656 Len=0
149	5.294019	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	53298 → 55043 [ACK] Seq=242 Ack=89976 Win=262656 Len=0
150	5.294392	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	53298 → 55043 [ACK] Seq=242 Ack=92880 Win=262656 Len=0
151	5.294928	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	53298 → 55043 [ACK] Seq=242 Ack=95784 Win=262656 Len=0
152	5.295613	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	53298 → 55043 [ACK] Seq=242 Ack=99122 Win=262656 Len=0
154	5.326586	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	53298 → 55043 [ACK] Seq=242 Ack=100864 Win=262656 Len=0
155	5.326586	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	53298 → 55043 [ACK] Seq=242 Ack=100865 Win=262656 Len=0
156	5.328171	77.YY.YYY.YY	172.XX.XX.XX	TLSv1.3	78	Alert (Level: Warning, Description: Close Notify)
157	5.328171	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	53298 → 55043 [FIN, ACK] Seq=266 Ack=100865 Win=262656 Len=0
158	5.328239	172.XX.XX.XX	77.YY.YYY.YY	TCP	54	55043 → 53298 [RST, ACK] Seq=100865 Ack=266 Win=0 Len=0
```
After the file is transferred completely, the close_notify alert is sent, and we also get one back from the server.

In the broken case, it looks like this:
```
No.	Time	Source	Destination	Protocol	Length	Info
6703	10.093493	172.XX.XX.XX	77.YY.YYY.YY	TLSv1.3	2958	Application Data [TCP segment of a reassembled PDU]
6704	10.094334	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9859560 Win=262656 Len=0
6705	10.094388	172.XX.XX.XX	77.YY.YYY.YY	TCP	2958	54333 → 56170 [ACK] Seq=9975720 Ack=242 Win=262400 Len=2904 [TCP segment of a reassembled PDU]
6706	10.094946	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9862464 Win=262656 Len=0
6707	10.095004	172.XX.XX.XX	77.YY.YYY.YY	TCP	2958	54333 → 56170 [ACK] Seq=9978624 Ack=242 Win=262400 Len=2904 [TCP segment of a reassembled PDU]
6708	10.095925	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9865368 Win=262656 Len=0
6709	10.095980	172.XX.XX.XX	77.YY.YYY.YY	TCP	2958	54333 → 56170 [ACK] Seq=9981528 Ack=242 Win=262400 Len=2904 [TCP segment of a reassembled PDU]
6710	10.096905	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9868272 Win=262656 Len=0
6711	10.096960	172.XX.XX.XX	77.YY.YYY.YY	TCP	2958	54333 → 56170 [ACK] Seq=9984432 Ack=242 Win=262400 Len=2904 [TCP segment of a reassembled PDU]
6712	10.097283	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9871176 Win=262656 Len=0
6713	10.097337	172.XX.XX.XX	77.YY.YYY.YY	TCP	2958	54333 → 56170 [ACK] Seq=9987336 Ack=242 Win=262400 Len=2904 [TCP segment of a reassembled PDU]
6714	10.097986	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9874080 Win=262656 Len=0
6715	10.098041	172.XX.XX.XX	77.YY.YYY.YY	TLSv1.3	1594	Application Data
6716	10.098694	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9876984 Win=262656 Len=0
6717	10.102103	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9879888 Win=262656 Len=0
6718	10.102770	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9882792 Win=262656 Len=0
6719	10.103677	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9885696 Win=262656 Len=0
6720	10.104590	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9888600 Win=262656 Len=0
6721	10.105268	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9891504 Win=262656 Len=0
6722	10.105952	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9894408 Win=262656 Len=0
6723	10.106635	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9897312 Win=262656 Len=0
6724	10.107545	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9900216 Win=262656 Len=0
6725	10.108474	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK- Seq=242 Ack=9903120 Win=262656 Len=0
6726	10.108921	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9906024 Win=262656 Len=0
6727	10.109832	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9908928 Win=262656 Len=0
6728	10.110514	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9911832 Win=262656 Len=0
6729	10.111198	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9914736 Win=262656 Len=0
6730	10.118725	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9917640 Win=262656 Len=0
6731	10.119409	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9920544 Win=262656 Len=0
6732	10.120308	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9923448 Win=262656 Len=0
6733	10.121219	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9926352 Win=262656 Len=0
6734	10.121903	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9929256 Win=262656 Len=0
6735	10.123052	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9932160 Win=262656 Len=0
6736	10.123734	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9935064 Win=262656 Len=0
6737	10.124874	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9937968 Win=262656 Len=0
6738	10.125564	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9940872 Win=262656 Len=0
6739	10.126240	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9943776 Win=262656 Len=0
6740	10.126921	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9946680 Win=262656 Len=0
6741	10.127832	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9949584 Win=262656 Len=0
6742	10.128255	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9952488 Win=262656 Len=0
6743	10.129418	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9955392 Win=262656 Len=0
6744	10.130275	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9958296 Win=262656 Len=0
6745	10.130790	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9961200 Win=262656 Len=0
6746	10.131471	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9964104 Win=262656 Len=0
6747	10.132377	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9967008 Win=262656 Len=0
6748	10.133065	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9969912 Win=262656 Len=0
6749	10.133983	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9972816 Win=262656 Len=0
6750	10.134885	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9975720 Win=262656 Len=0
6751	10.135567	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9978624 Win=262656 Len=0
6752	10.136249	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9981528 Win=262656 Len=0
6753	10.136936	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9984432 Win=262656 Len=0
6754	10.137847	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9987336 Win=262656 Len=0
6755	10.139022	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9990240 Win=262656 Len=0
6756	10.139386	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [ACK] Seq=242 Ack=9991781 Win=262656 Len=0
6797	12.595718	77.YY.YYY.YY	172.XX.XX.XX	TCP	60	56170 → 54333 [FIN, ACK] Seq=242 Ack=9991781 Win=262656 Len=0
6799	12.595762	172.XX.XX.XX	77.YY.YYY.YY	TCP	54	54333 → 56170 [ACK] Seq=9991781 Ack=243 Win=262400 Len=0
```
There is no close_notify alert on the wire, and the connection is closed. I also verified that the whole file data is present up to the last byte. 

I saw that under this particular configuration, the actual payload data is processed into chunks of up to 16384 bytes each, and for each of those, an indivudal `send` is done, containing on TLS application data packet. As a result, the "critical" case is when `file_size % 16384` get's close to the maximum of 16383. 
Original file size was 9977696 (which has a remainder of 16224), but I was able to reliably reproduce the missing close_notify also with sizes of 1785696 and 1458016.

**Comment by icing** [comment] 2023-09-15 07:14
Could you check if #11858 helps with the shutdown problems?

**Comment by 2i-mh** [comment] 2023-09-19 08:13
I don't have the infrastructure to build custom versions of curl for windows, so I can't really test this PR.

However, I don't see how the lastest changes in #11858 would help here. In the scenario described above, the code would end ìn `CURL_TRC_CF(data, cf, "SSL shutdown, blocked send, leaving");` and give up, as it did before. I understand that you do not want to add longer block times, but maybe a single attempt at re-sending the close-notify only in the `SSL_ERROR_WANT_WRITE` case, after waiting only a few milliseconds, could mitigate this issue well enough in practice.

**Comment by bagder** [comment] 2024-02-10 16:52
Is this still fail the same way using current git master?

**Comment by 2i-mh** [comment] 2024-02-13 09:29
As I said, I don't have the infrastructure to build custom versions of curl for windows, so I can't really test any git versions. However, looking at the master source: https://github.com/curl/curl/blob/5691a6cf363242da38bd7e469b13a2e741a295c6/lib/vtls/openssl.c#L1915-L1917  

A blocked close_notify send attempt is still just ignored and not repeated. Are there any other recent code changes which should prevent this from happening?

Unfortunatelty, I also don't have access to this server which "reliably" had shown this behavior any more.
What I can say is that we still saw this issue with 8.5.0 in the wild, with different servers. However, due to the nature of this issue being so timing-critical, it's hard to reproduce on purpose.

**Closed** 2024-02-27 23:21 UTC
Labels: TLS, FTP, KNOWN_BUGS material
