### ISSUE TITLE
Socket is already closed when CURL_POLL_REMOVE notification is received

### ISSUE THREAD

**Issue by pkropachev** [curl/curl#14976] opened 2024-09-20 05:41 UTC
### I did this

Hello Team!

We faced with problem, it looks like sometimes socket is already closed when `CURLMOPT_SOCKETFUNCTION` callback is called with  `CURL_POLL_REMOVE` argument. See example [ephiperfifo.c](https://github.com/curl/curl/blob/dff66196d0bc52b53a91f59d3972769412f9639b/docs/examples/ephiperfifo.c).
Immediately after calling callback we check `fd` with `fnctl()` or `epoll_ctl()` and both syscalls return `errno 9` (`EBADF`).

Could you please confirm if it's not guaranteed by `CURLMOPT_SOCKETFUNCTION` function with `CURL_POLL_REMOVE` argument that `fd` won't be closed before this notification?

As far as I understand possible workaround can be registering `CURLOPT_CLOSESOCKETFUNCTION` callback and closing `fd` by our self?

Unfortunately it's difficult to reproduce, so I can't provide some simple example for reproducing.

Thanks!

### curl/libcurl version

curl 8.6.0

### operating system

Ubuntu 20.04.6 LTS

**Comment by bagder** [comment] 2024-09-22 19:13
It would be helpful if you tested the latest version just to see if the problem still remains. libcurl is meant to remove the socket before closing it.

But without a way to reproduce it, or a detailed log from you where it happens, I don't think we can do much!

**Comment by pkropachev** [comment] 2024-09-23 07:29
Ok, sure. I will try to reproduce. Actually I guess our problem is related with setting `CURLMOPT_MAXCONNECTS` options. Not sure if it's proper way of using. Anyway I will provide example and the resulting behavior.

**Comment by steve-chavez** [comment] 2024-09-24 00:14
I'm also seeing this on `libcurl 8.0.1`. Digging the source code I found that this was fixed on https://github.com/curl/curl/pull/4211, but no test was added. So it could be that a regression happened after 7.66.0 (I haven't confirmed it was fixed here though).

Also got here after following the [ephiperfifo](https://curl.se/libcurl/c/ephiperfifo.html) example. The error is hard to reproduce for me, it happens when making  ~10K requests.

**Comment by steve-chavez** [comment] 2024-09-24 15:05
Just in case it helps. For me this only happens when name resolution is involved, I can't reproduce locally. All the requests that succeed go through a `CURL_POLL_OUT -> CURL_POLL_IN -> CURL_POLL_REMOVE` sequence, the ones that fail do `CURL_POLL_OUT -> CURL_POLL_REMOVE` and then timeout if a `fnctl` check is done to avoid the EBADF error with EPOLL_CTL_DEL.

**Comment by steve-chavez** [comment] 2024-09-27 19:31
I've managed to put a reproduction on https://gist.github.com/steve-chavez/75a85d222f5efac35122cb759c91047e and I can confirm I don't receive the `EBADF` starting from `8.8.0`, but there are timeouts as mentioned on https://github.com/curl/curl/issues/15079#issue-2553597083.

Seems the problem on the older versions was that timeouts were happening but the file descriptors were removed before the `epoll_ctl` fired.

**Comment by bagder** [comment] 2024-10-06 21:16
My reading of the info provided in this issue is that this problem does not exist in the latest release?

**Comment by pkropachev** [comment] 2024-10-07 07:46
Let me check on my side as well.

**Comment by bagder** [comment] 2024-10-13 21:37
Presumed fixed.

**Closed by bagder** 2024-10-13 21:37 UTC
Labels: needs-info, libcurl API
