### ISSUE TITLE
feature request: SSL certificate pinning

### ISSUE THREAD

**Issue by libBletchley** [curl/curl#1912] opened 2017-09-23 10:19 UTC
cURL does not have SSL certificate pinning.  In principle a user should be able to supply a fingerprint and cURL should reject requests for which the certificate does not match.  For example, one might envision this command to retrieve pop3 e-mail over Tor:
```
curl --socks4a 127.0.0.1:9050\
      --fingerprint '26:35:FC:88:05:3C:B2:6C:01:54:9B:03:99:15:B1:3E:4E:E9:27:66'\
      pop3://username%40elude.in:password@eludemaillhqfkh5.onion
```
**workaround**
The workaround is normally to use `fetchmail` instead of cURL, which offers certificate pinning.  Users can include fingerprints in their `~/.fetchmailrc` file.  However `fetchmail` cannot be used on `.onion` sites.

**Comment by bagder** [comment] 2017-09-23 11:39
See https://curl.haxx.se/libcurl/c/CURLOPT_PINNEDPUBLICKEY.html

**Comment by bagder** [comment] 2017-09-23 11:42
And of course curl's `--pinnedpubkey`

**Comment by libBletchley** [comment] 2017-09-23 12:03
Thanks.  That's not in the man page of my version, but indeed I see it in recent versions.  Although it looks like I have to supply the key.  It would be convenient to let cURL do the work of obtaining the key, and just enforce a fingerprint.

Anyway, I'm glad there's a mechanism in place.  Apparently the key must be downloaded using openssl, and then the fingerprint checked, before passing the key to curl.

**Comment by bagder** [comment] 2017-09-23 15:42
> it looks like I have to supply the key

You need to tell curl the "pinned" hash, yes.

> It would be convenient to let cURL do the work of obtaining the key, and just enforce a fingerprint.

curl certainly obtains it, as how would it otherwise compare the string against what you tell it?

> Apparently the key must be downloaded using openssl

No, you can use any tool you like that can do it. The openssl command line is an example that's handy to use since it works and many users have it installed already.

**Comment by bagder** [comment] 2017-09-23 15:48
This is not a bug, closing.

**Closed by bagder** 2017-09-23 15:48 UTC
Labels: not-a-bug, SSL/TLS

**Comment by sedimentation-fault** [comment] 2017-12-23 23:40
I would love to see a _--proxy-pinnedpubkey_ option, i.e. a way to pin the public key of an SSL proxy used to connect to a server, in addition to the existing option of pinning the public key of the server itself with _--pinnedpubkey_.
Do I have to open a separate feature request, or is it already doable and I just can't find it?
