### ISSUE TITLE
Problem with the -Z and 25% CPU on 7.69.0

### ISSUE THREAD

**Issue by skipik** [curl/curl#5043] opened 2020-03-05 19:10 UTC
### I did this
1. Create a .bat or .cmd with the following text and run it
```
@echo off
cd ..\
if not exist Installer (md Installer)
cd Installer
if exist vs_*.exe (del /f/s/q vs_*.exe > nul)
start /i /b curl.exe -C - -RLZSs --remote-name-all https://aka.ms/vs/15/release/vs_Enterprise.exe https://aka.ms/vs/15/release/vs_Professional.exe https://aka.ms/vs/15/release/vs_TestProfessional.exe https://aka.ms/vs/15/release/vs_Community.exe https://aka.ms/vs/15/release/vs_TeamExplorer.exe https://aka.ms/vs/15/release/vs_TestAgent.exe https://aka.ms/vs/15/release/vs_TestController.exe https://aka.ms/vs/15/release/vs_FeedbackClient.exe https://aka.ms/vs/15/release/vs_BuildTools.exe
exit /b
```
curl mush be in path or the same folder with the script
It can't download all the exe on 7.69 and gives me 25% CPU all the time.
Everything is fine on 7.68.

### I expected the following
All the exe files should be downloaded without any problems.

### curl/libcurl version

curl 7.69.0 (x86_64-pc-win32) libcurl/7.69.0 OpenSSL/1.1.1d (Schannel) zlib/1.2.11 brotli/1.0.7 WinIDN libssh2/1.9.0 nghttp2/1.40.0
Release-Date: 2020-03-04
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP brotli libz

### operating system

Microsoft Windows 10 Enterprise (x64) Build 18363.693 (1909/November 2019 Update)

**Comment by jay** [comment] 2020-03-07 06:57
Fixed by 8aa04e9. This may (or may not) be considered a dupe of #5044. The underlying cause is the same.

**Closed** 2020-03-07 06:57 UTC
Labels: HTTP/2, cmdline tool, duplicate

**Comment by VictorVG** [comment] 2020-03-08 00:34
Is my script, but if use variant based on FOR cycle:
```
@echo off
echo.
echo This script required cURL 7.66.0 or newer!
setlocal
cd ..\
if not exist Installer (md Installer)
cd Installer
for %%A in (
           BuildTools
           Community
           Enterprise
           Professional
           TeamExplorer
           TestAgent
           TestController
           ) do (if exist vs_%%A.exe del /f/s/q vs_%%A.exe > nul) & start /i /b curl -C - -RLZOSs https://aka.ms/vs/16/release/vs_%%A.exe
exit /b
```
then script working success, if used first variant
```
rem Required cURL 7.66.0 or newer!
@echo off
cd ..\
if not exist Installer (md Installer)
cd Installer
if exist vs_*.exe (del /f/s/q vs_*.exe > nul) & start /i /b curl -C - -RLSs --remote-name-all https://aka.ms/vs/15/release/vs_Enterprise.exe https://aka.ms/vs/15/release/vs_Professional.exe  https://aka.ms/vs/15/release/vs_TestProfessional.exe https://aka.ms/vs/15/release/vs_Community.exe https://aka.ms/vs/15/release/vs_TeamExplorer.exe https://aka.ms/vs/15/release/vs_TestAgent.exe https://aka.ms/vs/15/release/vs_TestController.exe https://aka.ms/vs/15/release/vs_FeedbackClient.exe https://aka.ms/vs/15/release/vs_BuildTools.exe
exit /b
```
script don't work for any version cURL 7.66 - 7.69 w/o exist or no swinish -Z in to command line - is possibly my error, but in to Win 7 SP1 x64 I don't see 100% used core CPU time - possible the reason for this phenomenon is an attempt to software methods for fix hardware errors in CPU circuits with virtual SMP (Hyper Treading) - and there are enough places where a synchronization violation and the subsequent "trigger race" can occur.

The software patch simply hides the fact that there is a circuitry error, but in reality you need to completely rework the CPU circuitry - since the pseudo SMP (Johnson’s technology is Hyper Trading) is applicable only in very specific computational problems and requires very careful calculation of the circuit diagrams over the entire temperature range operating voltages and frequencies. But nobody does it - it’s too time-consuming and colleagues usually get by with general modeling of the circuit as a whole, and phenomena like Sectre / Meldown often occur only with a specific combination of frequencies, voltages and temperatures, which makes it difficult to diagnose them using selective tests - to the level of “impossible” .

**Comment by VictorVG** [comment] 2020-03-12 00:13
In to script is my typo. Fixed:

```
@rem Required cURL 7.66.0 or newer!
@echo off
cd ..\
if not exist Installer (md Installer)
cd Installer
del /f/q vs_*.exe > nul & start /i /b curl -C - -RLZSs --remote-name-all https://aka.ms/vs/15/release/vs_Enterprise.exe https://aka.ms/vs/15/release/vs_Professional.exe  https://aka.ms/vs/15/release/vs_TestProfessional.exe https://aka.ms/vs/15/release/vs_Community.exe https://aka.ms/vs/15/release/vs_TeamExplorer.exe https://aka.ms/vs/15/release/vs_TestAgent.exe https://aka.ms/vs/15/release/vs_TestController.exe https://aka.ms/vs/15/release/vs_FeedbackClient.exe https://aka.ms/vs/15/release/vs_BuildTools.exe --
exit /b
```
