### ISSUE TITLE
schannel: failed to decrypt data, need more data  error in window11 with libcurl

### ISSUE THREAD

**Issue by anu743** [curl/curl#14807] opened 2024-09-06 07:37 UTC
### I did this

when try to download a file using curl through proxy and below command:
curl -fvk --proxy 120.0.0.1:3501 -o Test.bin <URL_to_download> -v -k -l 
 download is successful but : "schannel: failed to decrypt data, need more data " error is coming
 
TLS handshake was successful

i tried running with --tls-max 1.2 flag and --ssl-no-revoke flag but still the issue is coming

its happening only when i tried to download the file from windows.

but how to confirm that this is issue with windows and TLS compatability. 

### I expected the following

expected to completed the download without errors

### curl/libcurl version

curl/8.2.1

### operating system

window11

**Comment by icing** [comment] 2024-09-06 07:47
Do you see an error returned by curl or is it just the message that you think should not happen?

**Comment by anu743** [comment] 2024-09-06 07:59
Curl is returning this error during download.
when i do the request from windows.

logs:
< HTTP/1.0 200 Connection established
< Proxy-agent: tinyproxy/1.11.0-rc1-62-git-90adf28
<
* CONNECT phase completed
* CONNECT tunnel established, response 200
* schannel: disabled automatic use of client certificate
GET <URL>
> Host: eddlargedataadls2cgwtest.blob.core.windows.net
> User-Agent: curl/8.2.1
> Accept: */*
* schannel: failed to decrypt data, need more data
* schannel: failed to decrypt data, need more data
* schannel: failed to decrypt data, need more data
* schannel: failed to decrypt data, need more data
* schannel: failed to decrypt data, need more data
* schannel: failed to decrypt data, need more data
* schannel: failed to decrypt data, need more data
< HTTP/1.1 200 OK
< Content-Length: 524288037
< Content-Type: application/octet-stream
< Content-MD5: olMZCY3LMWL5cm6dA7F+aA==
< Last-Modified: Wed, 28 Aug 2024 13:56:20 GMT
< Accept-Ranges: bytes
< ETag: "0x8DCC7693238AF04"
< Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
< x-ms-request-id: 51e34464-801e-0021-7159-f98b1c000000
< x-ms-version: 2022-11-02
< x-ms-resource-type: file
< x-ms-creation-time: Tue, 16 Apr 2024 08:42:56 GMT
< x-ms-lease-status: unlocked
< x-ms-lease-state: available
< x-ms-blob-type: BlockBlob
< x-ms-server-encrypted: true
< x-ms-owner: $superuser
< x-ms-group: $superuser
< x-ms-permissions: rw-r-----
< Date: Wed, 28 Aug 2024 14:46:39 GMT
<
{ [15724 bytes data]
* schannel: failed to decrypt data, need more data
* schannel: failed to decrypt data, need more data
* schannel: failed to decrypt data, need more data
* schannel: failed to decrypt data, need more data
* schannel: failed to decrypt data, need more data
* schannel: failed to decrypt data, need more data

so this schannel error is keep printing until the download completes

**Comment by icing** [comment] 2024-09-06 08:00
So the download completes successfully, but the stream of messages is - understandably - annoying. Did I get this right?

**Comment by anu743** [comment] 2024-09-06 08:03
its not about annoying.. 
just wanted to make sure , that its not effecting the download and why this error is happening.
how can i fix it or resolve it.

or confirm that its causing due to windows compatibility with TLS and curl

**Comment by icing** [comment] 2024-09-06 08:22
> its not about annoying.. just wanted to make sure , that its not effecting the download and why this error is happening. how can i fix it or resolve it.
> 
> or confirm that its causing due to windows compatibility with TLS and curl

It is not an error indication, e.g. nothing has gone wrong. The cause of this is that the Schannel library gets a chunk of data from your proxy that is not a complete TLS record. Therefore, it cannot decode it and needs the rest of the packet's data. When it arrives, it will complete the decryption and everything is fine.

Under most network conditions, TLS packets arrive pretty much complete and it is rare that this happens. But your proxy seems to forward the data in chunks that make this more frequent. Why it does that, I do not know.

**Comment by anu743** [comment] 2024-09-06 14:36
okay, Thanks a lot for the clarification.

**Comment by jay** [comment] 2024-09-06 17:12
We are discussing moving this message into a level of tracing or eliminating it. What it basically means is decryption failed because the received message is incomplete. Depending on network conditions you may see it very frequently in verbose.

**Comment by jay** [comment] 2024-10-30 04:48
Closing since #14826 fixed this.

**Closed by jay** 2024-10-30 04:48 UTC
Labels: TLS, Windows
