### ISSUE TITLE
HTTP code 416, -C - switch appends error page to binary file

### ISSUE THREAD

**Issue by tkzv** [curl/curl#2288] opened 2018-02-05 12:09 UTC
### I did this
First
`curl -O https://cs9.pikabu.ru/post_img/2018/02/04/5/1517725680171469429.gif `
then
`curl -O https://cs9.pikabu.ru/post_img/2018/02/04/5/1517725680171469429.gif -C -`
because I thought the file didn't finish downloading.

### I expected the following
If the file was incomplete, I expected downloading to finish. If the file was complete, I expected out-of-range error and refusal to download, since the error pages are normally much smaller than the file I already had -- about 9M. 

Instead, curl added the following 206 byte text to the end of the GIF:
```
<html>
<head><title>416 Requested Range Not Satisfiable</title></head>
<body bgcolor="white">
<center><h1>416 Requested Range Not Satisfiable</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

### curl/libcurl version
[curl -V output]
```
curl -V
curl 7.45.0 (x86_64-pc-win32) libcurl/7.45.0 OpenSSL/1.0.2d zlib/1.2.8 WinIDN libssh2/1.4.3_DEV
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp scp sftp smtp smtps te
lnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz
```

### operating system
Windows 8.1

**Comment by jay** [comment] 2018-02-06 02:45
Duplicate of #1163

**Closed by jay** 2018-02-06 02:45 UTC
Labels: HTTP, cmdline tool, duplicate
