### ISSUE TITLE
CURLOPT_READFUNCTION function isn't called when using websockers.

### ISSUE THREAD

**Issue by DonDuijnstee** [curl/curl#12587] opened 2023-12-22 14:14 UTC
### I did this

When trying to setup websockets using curl_multi the CURLOPT_READFUNCTION doesn't get called for sending data over the websocket connection. The callback function isn't called ( placed a breakpoint with the debugger ).

### I expected the following

I expected curl would call the callback function for sending data over the websocket connection.

### curl/libcurl version

8.4.0

### operating system

Windows

**Comment by bagder** [comment] 2023-12-22 15:38
Nothing says it would be called. But yeah, that's a feature we want to add.

**Comment by bagder** [comment] 2023-12-27 08:27
Duplicate of #11402

**Closed by bagder** 2023-12-27 08:27 UTC
Labels: enhancement, WebSocket
