### ISSUE TITLE
The warning output gets mangled by the progress meter

### ISSUE THREAD

**Issue by combor** [curl/curl#4422] opened 2019-09-25 12:43 UTC
### I did this

Hi, I'm having problems hiding the progress bar but keeping the warings on the screen.
With such command I'm getting only the last error:
```
curl -Lkf --connect-timeout 5 \
    --max-time 10 \
    --retry 5 \
    --retry-max-time 40 \
    --show-error \
    --silent \
    --output /tmp/response \
    -w "Requested URL: %{url_effective}\nResponse code: %{http_code}\n" \
    'https://httpstat.us/503'

Requested URL: https://httpstat.us/503
Response code: 503
curl: (22) The requested URL returned error: 503 Service Unavailable
```
If I remove `--silent` I'm getting this:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Transient problem: HTTP error Will retry in 1 seconds. 5 retries
Warning: left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Transient problem: HTTP error Will retry in 2 seconds. 4 retries
Warning: left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Transient problem: HTTP error Will retry in 4 seconds. 3 retries
Warning: left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Transient problem: HTTP error Will retry in 8 seconds. 2 retries
Warning: left.
^C
```
Or this ( no new lines before `Warning`) - depends on the error type:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 1 seconds. 5 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 2 seconds. 4 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 4 seconds. 3 retries left.
^C
```

How can I hide the progress bar? After some googling it seems like the most wanted feature on the internet :)

Maybe the new flag can be introduced? Something like `--do-not-ever-show-me-the-progress-bar-as-i-know-what-im-doing` ?

### I expected the following
```
Warning: Transient problem: timeout Will retry in 1 seconds. 5 retries left.
Warning: Transient problem: timeout Will retry in 2 seconds. 4 retries left.
Warning: Transient problem: timeout Will retry in 4 seconds. 3 retries left.
...
curl: (22) The requested URL returned error: 503 Service Unavailable
```
### curl/libcurl version

curl 7.54.0 (x86_64-apple-darwin18.0) libcurl/7.54.0 LibreSSL/2.6.5 zlib/1.2.11 nghttp2/1.24.1
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy

### operating system
Darwin GBML242731 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

**Comment by bagder** [comment] 2019-09-25 12:50
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!

You clearly noticed that `-s / --silent` removed the progress bar so for being *"like the most wanted feature on the internet :)"* it was rather simple, right?

Now you want to keep some "talk" output and remove other and that's a different matter and we don't really let the user pick-and-choose among all of them. We have normal mode, silent mode and verbose mode. You need to pick one of them.

Or work on adding some sort of new selection option that isn't currently available...

**Comment by combor** [comment] 2019-09-25 12:54
Thanks for the quick response. As you probably noticed this is a bug report as well. Please check the second output from the non-silenced curl. The output with warings doesn't have new lines which makes it non-readable. Is this something that you consider as a bug?

**Comment by bagder** [comment] 2019-09-25 13:01
I guess it is a bug yes.

The problem is of course that we have both the progress meter and the warnings getting shown and it's a bad mix since the progress meter will destroy anything else that is also shown... It will never be "pretty".

**Comment by combor** [comment] 2019-09-25 13:09
Thanks, sounds like a good solution would be to hide the progress meter.

**Comment by bagder** [comment] 2019-09-25 13:11
When?

**Comment by combor** [comment] 2019-09-25 13:17
Maybe when a flag is specified to hide it ? I mean, if it's hard to make it pretty by default I recon It would be desirable to let user to choose what to output.

**Comment by bagder** [comment] 2019-10-08 09:54
@combor, I presume then you'd be happy with something in the style of #4470 which allows tusers o switch off the progress-bar only, but not making curl silent otherwise?

**Comment by combor** [comment] 2019-10-08 09:56
Yes, that would be perfect. Thanks @bagder

**Comment by jay** [comment] 2019-10-08 18:58
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: timeout Will retry in 4 seconds. 3 retries left.
^C

I can't reproduce the missing newline using master in Windows 7. Do you see that when you use master?

**Comment by combor** [comment] 2019-10-08 19:05
@jay try curling a host that will refuse connections. I can reproduce it while trying to connect to http://localhost:1234
```
 curl -Lkf --connect-timeout 5     --max-time 10     --retry 5     --retry-max-time 40     --show-error       --output /tmp/response     -w "Requested URL: %{url_effective}\nResponse code: %{http_code}\n"     'https://localhost:1234'

 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Requested URL: https://localhost:1234/
Response code: 000
curl: (7) Failed to connect to localhost port 1234: Connection refused

```
I havent tried master though.

**Comment by jay** [comment] 2019-10-08 19:17
Interesting. I can't reproduce that here. It doesn't seem to affect Windows or maybe it's a timing issue.

**Comment by combor** [comment] 2019-10-08 19:40
I just tried on windows and it actually doesn't do that while connection is refused. But by mistake I have copied exactly same command from macOS and because windows doesn't like single quotes it can't resolve localhost. Now it has no new lines in the output. Try executing exactly this:
```
c:\>curl.exe -Lkf --connect-timeout 5     --max-time 10     --retry 5     --retry-max-time 40     --show-error       --output /tmp/response     -w "Requested URL: %{url_effective}\nResponse code: %{http_code}\n"     'https://localhost:1234'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: 'https
Warning: Transient problem: timeout Will retry in 1 seconds. 5 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: 'https
Warning: Transient problem: timeout Will retry in 2 seconds. 4 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: 'https
Warning: Transient problem: timeout Will retry in 4 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: 'https
Warning: Transient problem: timeout Will retry in 8 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: 'https
Warning: Transient problem: timeout Will retry in 16 seconds. 1 retries left.
```
This is latest curl v 7.66.0

The other interesting thing is when connection is refused the expotential backoff seems to not be triggered. Is this intentional?

**Comment by jay** [comment] 2019-10-08 21:33
Ok I see. That doesn't work (look at your error message) because of the single quotes and you must have --retry-connrefused in your curlrc. Here's a minimal repro that shows me the issue in older curl versions but not in newer ones.

curl 7.59:
~~~
> curl -V && curl --retry-connrefused --retry 3 --output NUL https://localhost:1234
curl 7.59.0-DEV (i686-w64-mingw32) libcurl/7.59.0-DEV mbedTLS/2.7.0 zlib/1.2.11 libssh2/1.8.0 nghttp2/1.29.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS Debug TrackMemory IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz HTTP2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: connection refused Will retry in 1 seconds. 3
Warning: retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0Warning: Transient problem: connection refused Will retry in 2 seconds. 2
Warning: retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: connection refused Will retry in 4 seconds. 1
Warning: retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 1234: Connection refused
~~~

master:
~~~
> curld -V && curld --retry-connrefused --retry 3 --output NUL https://localhost:1234
curl 7.67.0-DEV (i386-pc-win32) libcurl/7.67.0-DEV OpenSSL/1.0.2s nghttp2/1.39.1
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Debug HTTP2 HTTPS-proxy IPv6 Largefile NTLM SSL
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (7) Failed to connect to localhost port 1234: Connection refused
Warning: Transient problem: connection refused Will retry in 1 seconds. 3
Warning: retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (7) Failed to connect to localhost port 1234: Connection refused
Warning: Transient problem: connection refused Will retry in 2 seconds. 2
Warning: retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (7) Failed to connect to localhost port 1234: Connection refused
Warning: Transient problem: connection refused Will retry in 4 seconds. 1
Warning: retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (7) Failed to connect to localhost port 1234: Connection refused
~~~

**Comment by combor** [comment] 2019-10-08 21:58
Ok, so it seems that new lines problem exists only when using non existent domain. Here an example:
```
curl.exe -V && curl.exe --retry-connrefused --retry 3 --output NUL https://non.existent.domain
curl 7.66.0 (x86_64-pc-win32) libcurl/7.66.0 OpenSSL/1.1.1d (Schannel) zlib/1.2.11 brotli/1.0.7 WinIDN libssh2/1.9.0 nghttp2/1.39.2
Release-Date: 2019-09-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP brotli libz

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: non.existent.domain
Warning: Transient problem: timeout Will retry in 1 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: non.existent.domain
Warning: Transient problem: timeout Will retry in 2 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: non.existent.domain
Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: non.existent.domain
```

**Comment by jay** [comment] 2019-10-08 22:05
Ok. I see it isn't called in some places. If the host cannot be resolved then [Curl_pgrsDone](https://github.com/curl/curl/blob/curl-7_66_0/lib/progress.c#L140-L157) (which adds the newline when the progress meter is done) is not called.

Curl_pgrsDone is called by multi_done which is the cleanup but multi_done is not called for early states in the state machine. If I add it to CURLM_STATE_WAITRESOLVE state it will solve at least something. I don't know if it is safe for all states though, @bagder.

~~~diff
diff --git a/lib/multi.c b/lib/multi.c
index 6dfe884..4b8fd78 100755
--- a/lib/multi.c
+++ b/lib/multi.c
@@ -1616,6 +1616,7 @@ static CURLMcode multi_runsingle(struct Curl_multi *multi,
       if(result) {
         /* failure detected */
         stream_error = TRUE;
+        multi_done(data, result, TRUE);
         break;
       }
     }
~~~

~~~
> curld -o NUL --retry 1 DOESNOTEXIST
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (6) Could not resolve host: DOESNOTEXIST
Warning: Transient problem: timeout Will retry in 1 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (6) Could not resolve host: DOESNOTEXIST
~~~

**Comment by bagder** [comment] 2019-11-08 22:35
`multi_done()` is meant to be the counter-part to `multi_do()`. If it stops before do is called, I think it makes sense that done isn't called... but maybe we need to change that.

**Comment by bagder** [comment] 2020-02-14 22:10
I consider this bug very minor and won't work on it myself. It's been open 3+ months without activity. I think we should close it and I'm not sure it is even worth documenting in KNOWN_BUGS...

**Closed** 2020-03-17 16:58 UTC
Labels: KNOWN_BUGS material, cmdline tool
