### ISSUE TITLE
Busy loop at Curl_is_connected on MacOS 12.4.

### ISSUE THREAD

**Issue by linhaisongtao** [curl/curl#9320] opened 2022-08-16 09:20 UTC
### My app run libcurl for a few minutes, and meet CPU rate up to over 400%. dumped app, found busy loop on libcurl.
    1027 Thread_145252   DispatchQueue_77: task.policy.ConnQueue  (concurrent)
    +  1027 start_wqthread  (in libsystem_pthread.dylib) + 15  [0x7ff81cfc0f57]
    +    1027 _pthread_wqthread  (in libsystem_pthread.dylib) + 256  [0x7ff81cfc1f8a]
    +      1027 _dispatch_worker_thread2  (in libdispatch.dylib) + 160  [0x7ff81ce1e25c]
    +        1027 _dispatch_root_queue_drain  (in libdispatch.dylib) + 343  [0x7ff81ce1dac2]
    +          1027 _dispatch_async_redirect_invoke  (in libdispatch.dylib) + 704  [0x7ff81ce1043f]
    +            1027 _dispatch_continuation_pop  (in libdispatch.dylib) + 453  [0x7ff81ce10d7c]
    +              1027 _dispatch_client_callout  (in libdispatch.dylib) + 8  [0x7ff81ce0e317]
    +                1027 _dispatch_call_block_and_release  (in libdispatch.dylib) + 12  [0x7ff81ce0d0cc]
    +                  ! 1026 scurl_http_do  (in MyApp) + 178  [0x10ddf4b93]
    +                  !   1013 curl_easy_perform  (in MyApp) + 306  [0x10dd6a38e]
    +                  !   : 474 curl_multi_perform  (in MyApp) + 114  [0x10dd7d873]
    +                  !   : | 442 sigpipe_ignore  (in MyApp) + 87  [0x10dd7d971]
    +                  !   : | + 440 __platform_sigaction  (in libsystem_platform.dylib) + 103  [0x7ff81cfda6eb]
    +                  !   : | + ! 440 __sigaction  (in libsystem_kernel.dylib) + 10  [0x7ff81cf8d65e]
    +                  !   : | + 2 __platform_sigaction  (in libsystem_platform.dylib) + 42,46  [0x7ff81cfda6ae,0x7ff81cfda6b2]
    +                  !   : | 29 sigpipe_ignore  (in MyApp) + 58  [0x10dd7d954]
    +                  !   : | + 28 __platform_sigaction  (in libsystem_platform.dylib) + 103  [0x7ff81cfda6eb]
    +                  !   : | + ! 28 __sigaction  (in libsystem_kernel.dylib) + 10,20  [0x7ff81cf8d65e,0x7ff81cf8d668]
    +                  !   : | + 1 __platform_sigaction  (in libsystem_platform.dylib) + 103  [0x7ff81cfda6eb]
    +                  !   : | 3 sigpipe_ignore  (in MyApp) + 91,61  [0x10dd7d975,0x10dd7d957]
    +                  !   : 440 curl_multi_perform  (in MyApp) + 153  [0x10dd7d89a]
    +                  !   : | 439 __platform_sigaction  (in libsystem_platform.dylib) + 103  [0x7ff81cfda6eb]
    +                  !   : | + 438 __sigaction  (in libsystem_kernel.dylib) + 10,0  [0x7ff81cf8d65e,0x7ff81cf8d654]
    +                  !   : | + 1 DYLD-STUB$$__sigaction  (in libsystem_platform.dylib) + 0  [0x7ff81cfdf0ac]
    +                  !   : | 1 sigaction  (in libsystem_c.dylib) + 0  [0x7ff81ceb6ec6]
    +                  !   : 93 curl_multi_perform  (in MyApp) + 129  [0x10dd7d882]
    +                  !   : | 76 multi_runsingle  (in MyApp) + 706  [0x10dd7dc3a]
    +                  !   : | + 64 Curl_is_connected  (in MyApp) + 507  [0x10dd62ba5]
    +                  !   : | + ! 62 verifyconnect  (in MyApp) + 45  [0x10dd6319b]
    +                  !   : | + ! : 62 getsockopt  (in libsystem_kernel.dylib) + 10,0  [0x7ff81cf8bf3e,0x7ff81cf8bf34]
    +                  !   : | + ! 2 verifyconnect  (in MyApp) + 45,61  [0x10dd6319b,0x10dd631ab]
    +                  !   : | + 11 Curl_is_connected  (in MyApp) + 125  [0x10dd62a27]
    +                  !   : | + ! 11 Curl_now  (in MyApp) + 23  [0x10dd89436]
    +                  !   : | + !   11 clock_gettime  (in libsystem_c.dylib) + 184  [0x7ff81cea070e]
    +                  !   : | + !     6 _mach_boottime_usec  (in libsystem_c.dylib) + 126,106,...  [0x7ff81ceca11a,0x7ff81ceca106,...]
    +                  !   : | + !     5 _mach_boottime_usec  (in libsystem_c.dylib) + 116  [0x7ff81ceca110]
    +                  !   : | + !       4 gettimeofday  (in libsystem_c.dylib) + 45  [0x7ff81ce986ac]
    +                  !   : | + !       | 3 __commpage_gettimeofday_internal  (in libsystem_kernel.dylib) + 36  [0x7ff81cf8a1a0]
    +                  !   : | + !       | + 3 mach_absolute_time  (in libsystem_kernel.dylib) + 28,31  [0x7ff81cf88e3c,0x7ff81cf88e3f]
    +                  !   : | + !       | 1 __commpage_gettimeofday_internal  (in libsystem_kernel.dylib) + 104  [0x7ff81cf8a1e4]
    +                  !   : | + !       1 gettimeofday  (in libsystem_c.dylib) + 0  [0x7ff81ce9867f]
    +                  !   : | + 1 Curl_is_connected  (in MyApp) + 287  [0x10dd62ac9]
    +                  !   : | +   1 Curl_socket_check  (in MyApp) + 145  [0x10dd8176b]
    +                  !   : | +     1 Curl_poll  (in MyApp) + 566  [0x10dd81a30]
    +                  !   : | 11 multi_runsingle  (in MyApp) + 3002  [0x10dd7e532]
    +                  !   : | + 9 Curl_pgrsUpdate  (in MyApp) + 42  [0x10dd8087c]
    +                  !   : | + ! 9 Curl_now  (in MyApp) + 23  [0x10dd89436]
    +                  !   : | + !   8 clock_gettime  (in libsystem_c.dylib) + 184  [0x7ff81cea070e]
    +                  !   : | + !   : 4 _mach_boottime_usec  (in libsystem_c.dylib) + 116  [0x7ff81ceca110]
    +                  !   : | + !   : | 3 gettimeofday  (in libsystem_c.dylib) + 45  [0x7ff81ce986ac]
    +                  !   : | + !   : | + 3 __commpage_gettimeofday_internal  (in libsystem_kernel.dylib) + 36  [0x7ff81cf8a1a0]
    +                  !   : | + !   : | +   3 mach_absolute_time  (in libsystem_kernel.dylib) + 28,65  [0x7ff81cf88e3c,0x7ff81cf88e61]
    +                  !   : | + !   : | 1 gettimeofday  (in libsystem_c.dylib) + 6  [0x7ff81ce98685]
    +                  !   : | + !   : 3 _mach_boottime_usec  (in libsystem_c.dylib) + 106,126  [0x7ff81ceca106,0x7ff81ceca11a]
    +                  !   : | + !   : 1 _mach_boottime_usec  (in libsystem_c.dylib) + 131  [0x7ff81ceca11f]
    +                  !   : | + !   :   1 DYLD-STUB$$mach_boottime_usec  (in libsystem_c.dylib) + 0  [0x7ff81cf1182c]
    +                  !   : | + !   1 clock_gettime  (in libsystem_c.dylib) + 205  [0x7ff81cea0723]
    +                  !   : | + 1 Curl_pgrsUpdate  (in MyApp) + 73  [0x10dd8089b]
    +                  !   : | + ! 1 Curl_timediff_us  (in MyApp) + 62  [0x10dd8950f]
    +                  !   : | + 1 Curl_pgrsUpdate  (in MyApp) + 277  [0x10dd80967]
    +                  !   : | 2 multi_runsingle  (in MyApp) + 334  [0x10dd7dac6]
    +                  !   : | + 1 multi_handle_timeout  (in MyApp) + 34  [0x10dd7f833]
    +                  !   : | + ! 1 Curl_timeleft  (in MyApp) + 0  [0x10dd624bc]
    +                  !   : | + 1 multi_handle_timeout  (in MyApp) + 291  [0x10dd7f934]
    +                  !   : | +   1 multi_done  (in MyApp) + 605  [0x10dd7c81e]
    +                  !   : | +     1 Curl_disconnect  (in MyApp) + 327  [0x10dd8befa]
    +                  !   : | +       1 Curl_closesocket  (in MyApp) + 132  [0x10dd6324d]
    +                  !   : | +         1 close  (in libsystem_kernel.dylib) + 10  [0x7ff81cf893a2]
    +                  !   : | 2 multi_runsingle  (in MyApp) + 2876  [0x10dd7e4b4]
    +                  !   : | + 2 multi_handle_timeout  (in MyApp) + 34  [0x10dd7f833]
    +                  !   : | +   2 Curl_timeleft  (in MyApp) + 76,234  [0x10dd62508,0x10dd625a6]
    +                  !   : | 1 multi_runsingle  (in MyApp) + 582  [0x10dd7dbbe]
    +                  !   : | + 1 Curl_connect  (in MyApp) + 167  [0x10dd8c5f6]
    +                  !   : | +   1 create_conn  (in MyApp) + 14274  [0x10dd8fe44]
    +                  !   : | +     1 Curl_resolv  (in MyApp) + 284  [0x10dd6dec0]
    +                  !   : | +       1 SCDynamicStoreCopyProxiesWithOptions  (in SystemConfiguration) + 552  [0x7ff81dba08b8]
    +                  !   : | +         1 SCDynamicStoreCopyValue  (in SystemConfiguration) + 292  [0x7ff81db9ca4f]
    +                  !   : | +1 configget  (in SystemConfiguration) + 170  [0x7ff81db9cbdf]
    +                  !   : | +  1 mach_msg  (in libsystem_kernel.dylib) + 56  [0x7ff81cf88ce8]
    +                  !   : | +    1 mach_msg_trap  (in libsystem_kernel.dylib) + 10  [0x7ff81cf8897a]
    +                  !   : | 1 multi_runsingle  (in MyApp) + 8  [0x10dd7d980]
    +                  !   : 3 curl_multi_perform  (in MyApp) + 114,153,...  [0x10dd7d873,0x10dd7d89a,...]
    +                  !   : 2 curl_multi_perform  (in MyApp) + 28  [0x10dd7d81d]
    +                  !   : | 2 Curl_now  (in MyApp) + 23  [0x10dd89436]
    +                  !   : |   2 clock_gettime  (in libsystem_c.dylib) + 184  [0x7ff81cea070e]
    +                  !   : |     1 _mach_boottime_usec  (in libsystem_c.dylib) + 116  [0x7ff81ceca110]
    +                  !   : |     + 1 gettimeofday  (in libsystem_c.dylib) + 0  [0x7ff81ce9867f]
    +                  !   : |     1 _mach_boottime_usec  (in libsystem_c.dylib) + 106  [0x7ff81ceca106]
    +                  !   : 1 curl_multi_perform  (in MyApp) + 195  [0x10dd7d8c4]
    +                  !   :   1 Curl_splaygetbest  (in MyApp) + 37  [0x10dd88e95]
    +                  !   :     1 Curl_splay  (in MyApp) + 33  [0x10dd88d12]
    +                  !   12 curl_easy_perform  (in MyApp) + 288  [0x10dd6a37c]
    +                  !   : 12 curl_multi_poll  (in MyApp) + 26  [0x10dd7d6a5]
    +                  !   :   6 multi_wait  (in MyApp) + 313  [0x10dd7d35e]
    +                  !   :   | 5 multi_timeout  (in MyApp) + 66  [0x10dd7f615]
    +                  !   :   | + 5 Curl_now  (in MyApp) + 23  [0x10dd89436]
    +                  !   :   | +   5 clock_gettime  (in libsystem_c.dylib) + 184  [0x7ff81cea070e]
    +                  !   :   | +     3 _mach_boottime_usec  (in libsystem_c.dylib) + 116  [0x7ff81ceca110]
    +                  !   :   | +     ! 2 gettimeofday  (in libsystem_c.dylib) + 45  [0x7ff81ce986ac]
    +                  !   :   | +     ! : 2 __commpage_gettimeofday_internal  (in libsystem_kernel.dylib) + 36  [0x7ff81cf8a1a0]
    +                  !   :   | +     ! :   2 mach_absolute_time  (in libsystem_kernel.dylib) + 26,28  [0x7ff81cf88e3a,0x7ff81cf88e3c]
    +                  !   :   | +     ! 1 gettimeofday  (in libsystem_c.dylib) + 0  [0x7ff81ce9867f]
    +                  !   :   | +     1 _mach_boottime_usec  (in libsystem_c.dylib) + 37  [0x7ff81ceca0c1]
    +                  !   :   | +     ! 1 mach_boottime_usec  (in libsystem_kernel.dylib) + 13  [0x7ff81cf95247]
    +                  !   :   | +     1 _mach_boottime_usec  (in libsystem_c.dylib) + 126  [0x7ff81ceca11a]
    +                  !   :   | 1 multi_timeout  (in MyApp) + 131  [0x10dd7f656]
    +                  !   :   |   1 Curl_timediff  (in MyApp) + 61  [0x10dd894b3]
    +                  !   :   4 multi_wait  (in MyApp) + 30,52,...  [0x10dd7d243,0x10dd7d259,...]
    +                  !   :   2 multi_wait  (in MyApp) + 767  [0x10dd7d524]
    +                  !   :     2 Curl_poll  (in MyApp) + 42,103  [0x10dd81824,0x10dd81861]

### I think we should put a timeout when use SOCKET_WRITABLE at method Curl_is_connected.

eg:
CURLcode Curl_is_connected(struct Curl_easy *data,
                           struct connectdata *conn,
                           int sockindex,
                           bool *connected)
{
  ...
      /* check socket for connect */
      long left_connect_time_ms = conn->timeoutms_per_addr[i] -(Curl_timediff(now, conn->connecttime));
      if(left_connect_time_ms < 0){
        left_connect_time_ms = 0;
      }
      //rc = SOCKET_WRITABLE(conn->tempsock[i], 0); original code
      rc = SOCKET_WRITABLE(conn->tempsock[i], (timediff_t)left_connect_time_ms);  //Optimized code
  ...
}

**Comment by bagder** [comment] 2022-08-16 09:36
Adding a timeout there would break the multi interface badly since it would block there on a single connection.

But how come the connection signals writable but still can't be confirmed to be connected? Can you explain how we can reproduce this issue?

**Comment by bagder** [comment] 2022-08-26 12:19
Lack of information, closing.

**Closed by bagder** 2022-08-26 12:19 UTC
Labels: needs-info
