### ISSUE TITLE
Occur changing dimension from seconds to another (for all timings parameters: time_namelookup, time_connect, time_appconnect, time_pretransfer, time_redirect, time_starttransfer, time_total) for cURL from ver. 7.74.0

### ISSUE THREAD

**Issue by algh37** [curl/curl#6416] opened 2021-01-05 13:09 UTC
**Description:**

**In previous version of cURL (7.73.0) described problem was absent and all timings values were in real second dimension:**

$ curl --version
**curl 7.73.0** (x86_64-w64-mingw32) libcurl/7.73.0 OpenSSL/1.1.1h (Schannel) zlib/1.2.11 brotli/1.0.9 zstd/1.4.5 libidn2/2.3.0 libssh2/1.9.0 nghttp2/1.41.0
Release-Date: 2020-10-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS brotli HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP zstd

**but in latest version (7.74.0) :**

MINGW64 /c/curl-7.74.0_2-win64-mingw/curl-7.74.0_2-win64-mingw/bin
$ ./curl --version
**curl 7.74.0** (x86_64-pc-win32) libcurl/7.74.0 OpenSSL/1.1.1i (Schannel) zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 WinIDN libssh2/1.9.0 nghttp2/1.42.0
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP Unicode UnixSockets alt-svc brotli libz zstd

occur problem with dimension for all timings parameters, in response come value in thousands of seconds, please look at **ACTUAL RESULT**.

**ACTUAL RESULT:**

```
MINGW64 /c/curl-7.74.0_2-win64-mingw/curl-7.74.0_2-win64-mingw/bin
$ ./curl -w "@all_google.com_timings.txt" -o NUL -s "http://wordpress.com/"

     time_namelookup:  19754s
        time_connect:  60355s
     time_appconnect:  0s
    time_pretransfer:  60477s
       time_redirect:  0s
  time_starttransfer:  103622s
                     ----------
          time_total:  103840s
```
        

**EXPECTED RESULT:**

```
$ curl --version
curl 7.73.0 (x86_64-w64-mingw32) libcurl/7.73.0

$ curl -w "@all_google.com_timings.txt" -o NUL -s "http://wordpress.com/"
     time_namelookup:  0,036830s
        time_connect:  0,080611s
     time_appconnect:  0,000000s
    time_pretransfer:  0,080714s
       time_redirect:  0,000000s
  time_starttransfer:  0,125696s
                     ----------
          time_total:  0,125839s
```

should have seconds dimension

**Comment by bagder** [comment] 2021-01-05 13:11
Duplicate of #6321

**Comment by algh37** [comment] 2021-01-05 13:45
@bagder 
thanks for info, but how fast will be created new ver. of cURL with fix for this problem and in which version / subversion will be this fix ?

**Comment by bagder** [comment] 2021-01-05 13:49
The fix is landed in the master branch already. It will be part of  the 7.75.0 release that we plan to ship on February 3, 2021.

**Closed** 2021-01-05 15:28 UTC
