### ISSUE TITLE
Issue building curl 7.66.0 on Windows

### ISSUE THREAD

**Issue by kartikkrishnan11** [curl/curl#4375] opened 2019-09-18 23:45 UTC
I am trying to compile  curl-7.66.0 on Windows Server 2012 R2 using Visual Studio 2017 ( in VS 2015 compatibility mode ) with options:
GEN_PDB=yes WITH_ZLIB=no WITH_SSH2=no ENABLE_IPV6=yes ENABLE_SSPI=no ENABLE_IDN=no ENABLE_SPNEGO=no ENABLE_WINSSL=no

I am pointing to openssl & openldap libraries for the build to use and that seems to work fine.
The windows build fails as it is looking for libssh2.obj  while creating the dll( See log file )
[build_release_x64.log](https://github.com/curl/curl/files/3628740/build_release_x64.log)

Below is the snippet of the error in the log file.

Using SSL: true
Using NGHTTP2: false
Using c-ares:
Using SSH2:
Using ZLIB:
Using IDN: false
Using IPv6: true
Using SSPI: false
Using WinSSL: false
CFLAGS: /I. /I ../lib /I../include /nologo /W4 /wd4127 /EHsc /DWIN32 /FD /c /DBUILDING_LIBCURL /DUSE_OPENLDAP /I../../deps/include /DUSE_OPENSSL /I../../deps/include\openssl /DUSE_IPV6 /Zi /Fd..uilds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib\libcurl-AXW.pdb
LFLAGS: /nologo /machine:x64 /LIBPATH:../../deps/lib libeay32-TMWD.lib ssleay32-TMWD.lib bcrypt.lib /incremental:no /opt:ref,icf /DEBUG
GenPDB: true
Debug: no
Machine: x64
	link.exe /DLL /nologo /machine:x64 "/LIBPATH:../../deps/lib"  libeay32-TMWD.lib ssleay32-TMWD.lib bcrypt.lib /incremental:no /opt:ref,icf /DEBUG ws2_32.lib oldap32-AXW.lib olber32-AXW.lib advapi32.lib crypt32.lib /out:..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib\libcurl-AXW.dll  /IMPLIB:..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib\libcurl-AXW.lib ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/file.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/timeval.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/base64.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/hostip.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/progress.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/formdata.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/cookie.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/http.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/sendf.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/ftp.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/url.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/dict.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/if2ip.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/speedcheck.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/ldap.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/version.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/getenv.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/escape.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/mprintf.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/telnet.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/netrc.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/getinfo.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/transfer.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/strcase.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/easy.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/security.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/curl_fnmatch.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/fileinfo.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/ftplistparser.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/wildcard.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/krb5.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/memdebug.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/http_chunks.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/strtok.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/connect.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/llist.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/hash.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/multi.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/content_encoding.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/share.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/http_digest.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/md4.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/md5.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/http_negotiate.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/inet_pton.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/strtoofft.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/strerror.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/amigaos.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/hostasyn.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/hostip4.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/hostip6.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/hostsyn.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/inet_ntop.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/parsedate.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/select.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/tftp.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/splay.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/strdup.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/socks.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/curl_addrinfo.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/socks_gssapi.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/socks_sspi.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/curl_sspi.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/slist.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/nonblock.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/curl_memrchr.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/imap.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/pop3.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/smtp.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/pingpong.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/rtsp.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/curl_threads.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/warnless.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/hmac.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/curl_rtmp.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/openldap.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/curl_gethostname.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/gopher.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/idn_win32.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/http_proxy.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/non-ascii.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/asyn-ares.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/asyn-thread.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/curl_gssapi.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/http_ntlm.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/curl_ntlm_wb.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/curl_ntlm_core.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/curl_sasl.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/rand.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/curl_multibyte.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/hostcheck.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/conncache.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/dotdot.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/x509asn1.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/http2.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/smb.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/curl_endian.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/curl_des.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/system_win32.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/mime.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/sha256.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/setopt.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/curl_path.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/curl_ctype.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/curl_range.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/psl.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/doh.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/urlapi.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/curl_get_line.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/altsvc.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vauth/vauth.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vauth/cleartext.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vauth/cram.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vauth/digest.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vauth/digest_sspi.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vauth/krb5_gssapi.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vauth/krb5_sspi.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vauth/ntlm.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vauth/ntlm_sspi.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vauth/oauth2.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vauth/spnego_gssapi.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vauth/spnego_sspi.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vtls/openssl.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vtls/gtls.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vtls/vtls.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vtls/nss.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vtls/polarssl.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vtls/polarssl_threadlock.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vtls/wolfssl.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vtls/schannel.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vtls/schannel_verify.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vtls/sectransp.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vtls/gskit.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vtls/mbedtls.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vtls/mesalink.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vquic/ngtcp2.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vquic/quiche.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vssh/libssh2.obj  ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vssh/libssh.obj   ..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib\libcurl.res
**LINK : fatal error LNK1181: cannot open input file '..\builds\libcurl-vc14-x64-release-dll-ssl-dll-ipv6-obj-lib/vssh/libssh2.obj'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\link.exe"' : return code '0x49d'**
**Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\nmake.exe"' : return code '0x2**

The same process worked for curl 7.65.1.
I realized the following difference between curl-7.65.1 had curl-7.66.0.

- curl 7.65.1 has ssh.c & ssh-libssh.c under src/lib
- These files have been removed and we have libssh.c & libssh2.c under src\lib\vssh
- Modifying MakefileBuild.vc under src\winbuild seems to work. I made the following changes:

1. Under the LIB_DIROBJ target, I added 
@if not exist "$(LIB_DIROBJ)\vssh" mkdir $(LIB_DIROBJ)\vssh
2. We also need to add a line to compile the .c files under vssh, so i added:
{$(LIBCURL_SRC_DIR)\vssh\}.c{$(LIB_DIROBJ)\vssh\}.obj:
	$(CURL_CC) $(CFLAGS) /Fo"$@"  $<

These changes cause the build to work.

**Comment by jay** [comment] 2019-09-19 03:20
Duplicate of #4322, fixed in master

**Closed by jay** 2019-09-19 03:20 UTC
Labels: duplicate

**Comment by kartikkrishnan11** [comment] 2019-09-19 16:28
Great. That's what i had added to the build as well. It works well now!
Thanks
