### ISSUE TITLE
Segmentation fault after curl_multi_cleanup with external event loop

### ISSUE THREAD

**Issue by drok** [curl/curl#2782] opened 2018-07-24 07:52 UTC
### I did this

My application is a message router, taking events from multiple sources and signalling multiple HTTP/1.1 application servers as a result of these events. Some of the events are related and form streams of events (tasks), all being sent via the same `CURL` context (multi handle), while others form other streams.

The implementation uses several `CURL *` contexts, one for each task. Each context is used to POST data to multiple URLs. The application uses libuv as an event loop, and sets up the `CURL` handles to use it as an external event loop.

The application itself is a server, and thus long lived process, while the tasks, and the the `CURL *` contexts come and go in an asynchronous manner. Some are long lived, some short.

When a task ends, `curl_multi_cleanup()` is called on its respective `CURL` handle, but the application keeps running, serving other tasks, and other `CURL` handles.

Using one `CURL` context to handle all the event streams/tasks is not possible because many tasks report to the same URL. Each task needs to use a distinct TLS connection (distinct QOS/DSCP settings for throttling purposes, for example), but the event streams can/should be pipelined.

### I expected the following

When `curl_multi_cleanup()` is called, libcurl should call the socket callback, `CURLMOPT_SOCKETFUNCTION` to `CURL_POLL_REMOVE` any sockets used by the `CURL` handle, and close the sockets properly, finishing any SSL conversations, or at least terminating them.

Instead, after curl_multi_cleanup, socket events still arrive, and libuv calls curl_perform on a now freed handle, causing a segmentation fault.

Properly closing a connection may involve more chatter with the server (saying "goodbye", depending on the protocol) so I would expect that `curl_multi_cleanup()` would not be able to `free(multi)` at all before returning. Rather, the `curl_multi_cleanup()` call simply signals the beginning of the teardown handshake, libcurl should start performing the handshake, only closing the sockets sockets, and freeing the multi handle when there is nothing left to do, some time later, perhaps after many more socket events.
 
### curl/libcurl version

> curl 7.58.0 (i686-redhat-linux-gnu) libcurl/7.58.0 OpenSSL/1.0.1e zlib/1.2.3 c-ares/1.10.0 libssh2/1.4.2 nghttp2/1.6.0
> Release-Date: 2018-01-24
> Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
> Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy Metalink

### operating system

> LSB Version:    :base-4.0-ia32:base-4.0-noarch:core-4.0-ia32:core-4.0-noarch
> Distributor ID: CentOS
> Description:    CentOS release 6.9 (Final)
> Release:        6.9
> Codename:       Final

**Comment by bagder** [comment] 2018-07-24 08:20
> I would expect that curl_multi_cleanup() would not be able to free(multi) at all before returning. 

It *has* to do that. There's no API or function to call to do the remaining shutdown so the curl_multi_cleanup() function will block in order to close down everything and free the handle before returning.

A future improvement would indeed be to allow the cleanup to work in a non-blocking manner...

**Comment by drok** [comment] 2018-07-24 19:19
From an external event loop perspective, which my application has, `curl_multi_cleanup()` has to both return immediately, and not free the handle if work is not complete. The (external) event loop will certainly not stop until all the sockets it's responsible for are either closed or removed from polling, so libcurl can continue to look forward to calls from the event loop to `curl_multi_socket_action()`

In cases where libcurl manages the event loop itself, it's reasonable to expect that curl_multi_cleanup() should close all open sockets, and take some time to do so, before `free()` and returning. To leave sockets open can be considered a bug. I would not think of a proper shutdown as an "improvement", but as expected basic functionality.

Perhaps a `CURLMOPT_TIMEOUT` option is needed so the application can specify how long until a graceful teardown is abandoned and a forceful termination is performed. The eventual bugfix to this issue should implement a reasonable default timeout.

> It has to do that. There's no API or function to call to do the remaining shutdown so the curl_multi_cleanup() function will block in order to close down everything and free the handle before returning.

Is there another API function needed over and above the existing interface to handle to need for a teardown handshake and correspondingly, deferred `free()` ? I don't see such a need.

**Comment by bagder** [comment] 2018-07-25 15:56
> curl_multi_cleanup() has to both return immediately, and not free the handle if work is not complete.

That sounds like a good challenge...

> Is there another API function needed over and above the existing interface to handle for signalling progress of a teardown handshake and correspondingly, deferred free() ? I don't see such a need

If you can provide a solution that doesn't, then I'm all but happy. I haven't been able to.

> It's not clear to me why v7.20.0 changed the return code of curl_multi_socket_action()

We did it because basically nobody took advantage of that feature, so it only complicated people's loops with no added benefit.

> but returning anything other than CURLM_CALL_MULTI_PERFORM when more work needs to and can be performed, would arguably be a bug.

Indeed. Are you saying you've found such a case?

**Comment by drok** [comment] 2018-07-25 18:16
>> curl_multi_cleanup() has to both return immediately, and not free the handle if work is not complete.

> That sounds like a good challenge...

This would best be done when I take on rewriting multi.c as I intend to for #2701. That work will implement proper pipelining, as specified by the RFC, and I also hope you will reconsider your plans to obsolete pipelining of HTTP/1.1. The RFC is not removing/deprecating this very useful feature, nor is HTTP/1.1 going away any time in the forseeable future, and it is needed by many applications. It is the only performance improvement possible when HTTP/2 and or a lower-latency connection are not available.

If I understand correctly, the main knock against HTTP/1.1 pipelining is that it doesn't support cancelling requests. The design of the feature never claimed to support cancelling, yet some developers expect it, and claim it's broken as a result. Also, head-of-line is an issue inherent to all pipelines, and it doesn't mean pipelines don't work or should not be implemented. Pipelining is perfectly appropriate for applications that do not require cancelling, and are not affected by head-of-line issues. Apps that either require cancelling or are susceptible to head-of-line issues, are not candidates for pipelining, and should not use it. Human browsing of the internet is a clear case where pipelining won't work, but there are many other applications for the HTTP/1.1 protocol where humans are not (directly) involved, **pipelining is highly desireable. Highly.** In my opinion the only thing **broken** is the developers expectations. If your library is intended to be used in browsers, go ahead and obsolete pipelining, but if you intend it to be used in non-browsers (think the **git** application, or other back-end applications), you'll see that pipelining is very much needed. In git, for example, no cancelling is needed, nor is head-of-line a problem, but cloning over a high-latency link need not be slower than the bandwidth of the link.

For now, the immediate problem is the segfault, which can be fixed by terminating and removing the multi's sockets from the event loop, and freeing the handle, without blocking, I think. It's a band-aid, but is good enough for now.

>> Is there another API function needed over and above the existing interface to handle for signalling progress of a teardown handshake and correspondingly, deferred free() ? I don't see such a need

> If you can provide a solution that doesn't, then I'm all but happy. I haven't been able to.

consider the following pseudocode:

```
curl_multi_cleanup(CURL* multi) {
	if (multi->num_sockets_alive == 0)
		free(multi)
	else if (shutdown_of_all_connections(CURL* multi) == COMPLETE)
		return MULTI_OK
	else 
		multi->want_cleanup = true
		return CALL_MULTI_PERFORM
}

curl_multi_socket_action(CURL* multi, socket_t socket) {
	service_the_socket(socket);
	if (multi->num_sockets_alive == 0)
		if (multi->want_cleanup)
			free(multi)
		return MULTI_OK
	else
		return CALLL_MULTI_PERFORM
}

static shutdown_of_all_connections(CURL* multi) {
	foreach conn in multi->connections
		conn->close_when_done = true
		/*
	       Ie, tell otherwise idling connections to stop waiting
		   and service the close_when_done flag
		 */
		if (conn->FSM == COMPLETE)
			foreach socket in conn->sockets
				service_the_socket(socket)
}

static service_the_socket(socket) {
	... do work, advance the connection's FSM
	if (FSM == COMPLETE)
		if (close_when_done)
			protocol->start_teardown()
	if (FSM == END)
		socket_cb(socket, POLL_REMOVE)
		close(socket)
		multi->num_sockets_alive--;
}

```

Ie, if there are any active connections at the time curl_multi_cleanup is called, mark them for closing, nudge the IDLE ones, so they stop being idle, and return CALL_MULTI_PERFORM (more work needed)

As the outstanding easy_handles complete, the respective connection(s) will go into some COMPLETE/IDLE state, and the "close_when_done" flag will cause them to further progress towards closing.

Eventually after all sockets in the multi have performed their END tasks, none are left alive, and when the curl_multi_socket action returns from the last outstanding connection, it will return MULTI_OK, telling the app that all the multi's sockets have been closed. If cleanup had been previously requested, it also means the multi has been free()'s

As sockets are waited on during teardown, following the cleanup request, the timeout won't be the normal read/write timeout, but the time remaining in a new SHUTDOWN_TIMEOUT period. Any remaining easy_handles that could not be serviced by then will have to be returned to the app via the normal `check_multi_info()` mechanism, perhaps with a new `CURLE_SHUTDOWN` CURLcode, to signal a permanent failure to the application.

**Comment by bagder** [comment] 2018-07-26 14:08
If you want to argue for us to keep pipelining support in libcurl, I will gladly participate in such a discussion. The curl-library mailing list is the place for doing that, not in an issue about a segfault. 

Making `curl_multi_cleanup()` return `CALL_MULTI_PERFORM` is indeed an interesting idea and I think I like it. It is however a modification of the API so we should probably require a special option to be set for it to work like that. I think however that we should fix this segfault independently of that...

**Comment by bagder** [comment] 2018-08-13 06:57
I would still like to get a recipe on how to reproduce this that also uses the API as per the documentation.

**Comment by bagder** [comment] 2018-08-24 07:10
Closing this since we've received no indication or source code showing that this is indeed a libcurl problem.

**Closed by bagder** 2018-08-24 07:10 UTC
Labels: crash, needs-info-or-update
