### ISSUE TITLE
cURL error 56: OpenSSL SSL_read: No error information

### ISSUE THREAD

**Issue by WouterFlorijn** [curl/curl#4982] opened 2020-02-26 15:46 UTC
I'm getting this error:

> cURL error 56: OpenSSL SSL_read: No error information (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

When I google it, I literally get zero results. It appears nobody on earth ever ran into this error.

To be clear, there are other "versions" of this error, that also provide a description, like "SSL_ERROR_SYSCALL, errno 104".

### I did this

Sent a request with mutual TLS through PHP (Guzzle library).

### I expected the following

The request is successful.

### curl/libcurl version

```
curl 7.67.0 (x86_64-alpine-linux-musl) libcurl/7.67.0 OpenSSL/1.1.1d zlib/1.2.11 nghttp2/1.40.0
Release-Date: 2019-11-06
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets
```

### operating system

Linux {DEPLOYMENT_NAME} 4.14.138+ #1 SMP Tue Sep 3 02:58:08 PDT 2019 x86_64 Linux

**Comment by bagder** [comment] 2020-02-26 17:04
We need a way to reproduce or much more details to understand this issue. You're also not using the latest version. As this currently, stands we can't do anything...

**Comment by WouterFlorijn** [comment] 2020-02-27 13:31
@bagder do you know if the "No error information" is coming from curl, or from underlying OpenSSL or HTTP implementations? I think this error might be the same as #4624, as well as a bunch of other error 56s with different messages.

As it stands, it's very difficult to reproduce as it seems to happen randomly and with different messages on different curl versions. This is happening only with poorly implemented bank APIs that use mutual TLS. I would conclude that their TLS implementation is incorrect or incomplete, and that all curl could do is display clearer errors and have an option to ignore these errors. Using curl 7.66.0 or 7.68.0 already is an improvement, since 7.67.0 seems to be more strict, as mentioned in #4624.

Maybe this information is useful.

**Comment by jay** [comment] 2020-02-27 23:09
We have addressed this already, as noted in that issue and the corresponding commit
~~~
- Improve SYSCALL error message logic in ossl_send and ossl_recv so that
  "No error" / "Success" socket error text isn't shown on SYSCALL error.
~~~
I'm closing this as a dupe. If you see the error in the latest curl feel free to reopen.

**Closed by jay** 2020-02-27 23:09 UTC
Labels: SSL/TLS, duplicate
