### ISSUE TITLE
Use SO_REUSEADDR when using --local-port

### ISSUE THREAD

**Issue by JsBergbau** [curl/curl#6288] opened 2020-12-09 01:27 UTC
### I did this
curl --local-port 5000 ifconfig.me/all
curl --local-port 5000 ifconfig.me/all
### I expected the following
Both requests should be successfull, however only first was successful because socket isn't closed yet
### curl/libcurl version
[curl -V output]
curl 7.64.0 (arm-unknown-linux-gnueabihf) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

### operating system
Linux raspberrypi 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux

Example Python-Code do track down
```python
#!/usr/bin/python3

import socket

# create an INET, STREAMing socket
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR,1) #The magic line
s.bind(("",5000))
s.connect(("ifconfig.me", 80))

request = "GET /all HTTP/1.1\r\nHost:ifconfig.me\r\n\r\n"
s.send(request.encode()) 

response = s.recv(4096)  
http_response = repr(response)
print(http_response)
```
When having the line
`s.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR,1)` you can call the script immediately after exit again and it will give you an answer. Line commented out it gives an error like curl
```
./portReuse.py
Traceback (most recent call last):
  File "./portReuse.py", line 8, in <module>
    s.bind(("",5000))
OSError: [Errno 98] Address already in use
```

**Comment by emilengler** [comment] 2021-01-07 09:28
Confirmed! The bug is also present on f52c6981c53ae55b3f9e9179c698a66bd2f7b655

**Comment by emilengler** [comment] 2021-01-07 09:36
I don't think it's a good idea to use SO_REUSEADDR though. It might be possible that another application is using that port and it would be bad if we would force hook us into this.

**Comment by bagder** [comment] 2021-01-07 09:50
Right, `SO_REUSEADDR` is not really "fixing a bug" it is gambling that we can reuse the port number at once even though there could possibly be some old packets destined for the port in transit. It is however a common thing to set and is rarely cause problems, probably because of TCP sequence numbers in combination with additional checks on top (like TLS).

So it's a judgement call. The added convenience for users who don't have to wait for `TIME_WAIT` to elapse contra the small risk that the new connection will get old packets.

**Comment by emilengler** [comment] 2021-01-08 11:53
@JsBergbau To fix the problem, libcurl already has a solution AFAIK. There are some curlopts (sorry forgot there name) that make it possible to get and therefore adjust the socket that libcurl will be using. It would be possible to set `SO_REUSEADDR` there and then use that socket for future connections.

**Comment by crrodriguez** [comment] 2021-02-17 18:05
No, it is not a good idea for the library itself to do this.. selecting the source port is also a bad idea.. your gambling may race against another buggy application selecting the same source port and if your port is within local_port_range your are screwed unless you make a reservation using sysctl.. the curl utility may be able to avoid you shooting yourself in the foot, but the library should just provide a working rifle :-) and error out whatever the kernel think is right.

Now the curl tool could in theory use SO_LINGER before closing its network socket but that also cause blocking..

**Comment by bagder** [comment] 2021-02-17 23:24
A fix for an application that wants this set for libcurl could probably be to use `CURLOPT_SOCKOPTFUNCTION`.

**Comment by bagder** [comment] 2021-03-12 12:43
Thanks for all the feedback everyone. I'm going to make call here and take the conservative route: no change. Setting the reuse_addr bit adds a tiny teeny risk to operations and I'm not ready to do that.

**Closed by bagder** 2021-03-12 12:43 UTC
Labels: connecting & proxies

**Comment by JsBergbau** [comment] 2021-03-12 17:48
@bagder 
I understand now that making this change could cause some trouble. However since libcurl supports this option as emilengler wrote, how about an additional option like `--so-reuse`. So when you need that option you can use it?

**Comment by emilengler** [comment] 2021-03-13 17:13
> @bagder 
> 
> I understand now that making this change could cause some trouble. However since libcurl supports this option as emilengler wrote, how about an additional option like `--so-reuse`. So when you need that option you can use it?

I'm afraid this might lead to too many wrong usages. I personally prefer a compile time option but I am still against both due to the reasons pointed out by bagder

**Comment by JsBergbau** [comment] 2021-03-13 17:48
> I'm afraid this might lead to too many wrong usages.

Can you tell how exactly this could lead to wrong usages? When you write in the man pages that you should use it at your own risk?
A compile time option would mean that your curl uses it all the time or not. That I think is not a good idea. There are cases when you need it and there are cases when you don't. And in addition it wouldn't be very comfortable since you normally install curl just with the packetmanager.
