### ISSUE TITLE
libcurl rtsp teardown failed while getting signal (Ctrl+c)

### ISSUE THREAD

**Issue by givenchyhuang** [curl/curl#991] opened 2016-09-04 12:26 UTC
### I did this
```I was writing the rtsp code using libcurl from https://curl.haxx.se/libcurl/c/rtsp.html.
I wrote the signal handler to catch the Ctrl+C and teardown the curl/uri to close the session while playing.
I got the error message - " curl_easy_perform() failed: Failed initialization " but I had already initialized the curl in main function.```

### I expected the following
`When playing, the program could catch the signal and teardown the uri successfully instead of Failed to initialize the curl`

### curl/libcurl version
`7.46.0`

### operating system

`ubuntu 16.04 64bit`

### code sample
```
#include <stdlib.h> 
#include <string.h> 
#include <curl/curl.h> 
#include <signal.h> 
CURL *curl; 
char *uri ; 
static void rtsp_teardown(CURL *curl, const char *uri) 
{ 
      curl_easy_setopt(curl, CURLOPT_RTSP_REQUEST, (long)CURL_RTSPREQ_TEARDOWN); 
      curl_easy_perform(curl); 
} 
void sighand(int signo){
      switch(signo){
            case SIGQUIT: 
                  rtsp_teardown(curl,uri);  
      }
}

void signal(){
      struct sigaction actions; 
      memset(&actions, 0, sizeof(actions)); 
      sigemptyset(&actions.sa_mask); 
      actions.sa_flags = 0; 
      actions.sa_handler = sighand; 
      signal(SIGQUIT, sighand);
} 
/* 
rtsp option,describe .. functions could be found from url above. 
*/ 
int main() 
{ 
      /* 
            initial variable could be found from url above 
      */ 
      signal(); 
      curl_global_init(CURL_GLOBAL_ALL); 
      curl = curl_easy_init(); 
      if(curl != NULL) { 
            rtsp_options(curl, uri); 
            rtsp_describe(curl, uri); 
            rtsp_setup(curl, uri, transport); 
            rtsp_play(curl, uri, range); 
      } 
      return 0; 
}
```

**Comment by bagder** [comment] 2016-09-04 12:28
Try writing your code within "~~~" markers for the markdown to work better!

**Comment by bagder** [comment] 2016-09-04 12:34
Calling `curl_easy_perform()` from *within* the signal handler seems like a bad idea. A signal handler should typically do as little as possible and if you want to call libcurl again when shutting down you should trigger that within the handler, but run it outside of it.

But then I would also argue that it feels like too much to run more traffic after control-c has been invoked... just my opinion there though.

**Comment by givenchyhuang** [comment] 2016-09-04 12:45
If I don't teardown the rtsp session with rtsp server while catching any signals, I could not play for a long time with new rtsp connection because of the timeout mechanism in rtsp server.
Therefore I want to teardown session first and then create a new connection to avoid the timeout from previous session.

**Comment by bagder** [comment] 2016-09-04 16:48
Let me quote the [glibc manual](https://www.gnu.org/software/libc/manual/html_node/Nonreentrancy.html) on how to write a signal handler:

>  The best practice is to write a handler that does nothing but set an external variable that the program checks regularly, and leave all serious work to the program. This is best because the handler can be called asynchronously, at unpredictable times--perhaps in the middle of a primitive function, or even between the beginning and the end of a C operator that requires multiple instructions.

**Comment by bagder** [comment] 2016-09-06 22:11
In other words: you cannot expect libcurl to work properly when run like that from inside your signal handler since libcurl is not reentrant like that. If you can reproduce a problem like this without calling libcurl from the signal handler then I'm very interested. If not, I consider this case closed!

**Comment by bagder** [comment] 2016-09-09 13:44
If this can be reproduced outside a signal handler it might be a bug, until then we close it.

**Closed by bagder** 2016-09-09 13:44 UTC
Labels: needs-info-or-update
