### ISSUE TITLE
8.11.0 seems to break flatpak update

### ISSUE THREAD

**Issue by heirecka** [curl/curl#15509] opened 2024-11-07 13:27 UTC
### I did this

After updating curl to 8.11.0 flatpak update fails with

```
❯ flatpak update
Looking for updates…
F: Warning: Treating remote fetch error as non-fatal since app/org.kde.krename/x86_64/stable is already installed: No such ref 'app/org.kde.krename/x86_64/stable' in remote flathub
...
```

running it with --verbose gives me
```
❯ flatpak --verbose update
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/heiko/.local/share/flatpak
Looking for updates…
F: Fetching summary index file for remote ‘flathub’
F: Loading https://dl.flathub.org/repo/summary.idx using curl
F: Received 9310 bytes
F: Loading https://dl.flathub.org/repo/summaries/4ca90c4f724a16511d94856acc64cc3736a0786ff23e9618974b08cce7c14db6.idx.sig using curl
F: Loading https://dl.flathub.org/repo/summary.idx.sig using curl
F: Received 592 bytes
F: Failed to download optional summary index: Signature made Thu Jan  1 01:00:00 1970 using [unknown name] key ID 562702E9E3ED7EE8
BAD signature from "Flathub Repo Signing Key <flathub@flathub.org>"
Primary key ID 4184DD4D907A7CAE
Primary key expires Mon Jun 14 15:18:56 2027
...
```

Downgrading to 8.10.1 makes it work again

### I expected the following

flatpak update to continue to fetch updates.

### curl/libcurl version

curl 8.11.0 (x86_64-pc-linux-gnu) libcurl/8.11.0 OpenSSL/3.3.2 zlib/1.3.1 zstd/1.5.6 libidn2/2.3.7 libssh2/1.11.1 nghttp2/1.64.0
Release-Date: 2024-11-06
Protocols: dict file ftp ftps gopher gophers http https imap imaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp ws wss
Features: AsynchDNS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz SSL threadsafe TLS-SRP UnixSockets zst

### operating system

Exherbo Linux

**Comment by bagder** [comment] 2024-11-08 07:56
I'm afraid we are going to need more details about how this transfer is done and what it is that fails. Otherwise there really is nothing for us to act on here.

**Comment by razzeee** [comment] 2024-11-08 09:03
Should probably be raised with flatpak. The code is contained to this file mostly https://github.com/flatpak/flatpak/blob/main/common/flatpak-utils-http.c

**Comment by bagder** [comment] 2024-11-08 09:10
> There was #15511 in 8.11.0.

... which very well might be exactly the problem based on this code snippet from flatpak:

https://github.com/flatpak/flatpak/blob/b730771bd793b34fb63fcbf292beed35476e5b92/common/flatpak-utils-http.c#L514-L526

**Comment by meator** [comment] 2024-11-08 09:43
I can also confirm that 878bc429f26c27294787dc59d7b53345d9edc5aa fixes the issue.

**Comment by bagder** [comment] 2024-11-08 10:50
Duplicate of #15511

**Closed by bagder** 2024-11-08 10:50 UTC
Labels: regression
