### ISSUE TITLE
git clone fails with http2 since 8.10.0 for a specific repo

### ISSUE THREAD

**Issue by lazka** [curl/curl#14923] opened 2024-09-15 16:06 UTC
### I did this

This is basically the same as https://github.com/curl/curl/issues/11201 I reported last year, which seems to be back now.

* `git clone --mirror https://chromium.googlesource.com/angle/angle.git`

it never finishes. In CI on Windows I also get:

```
  error: RPC failed; HTTP 502 curl 92 HTTP/2 stream 7 was not closed cleanly: INTERNAL_ERROR (err 2)
  fatal: expected 'packfile'
```

though this might be due to some timeout on the server side (?)

* Downgrading to 8.9.1 makes things work again
* Forcing git to use HTTP 1.1 makes things work again (`git config --global http.version HTTP/1.1`)

### I expected the following

git clone starts downloading things and clones the repo

### curl/libcurl version

curl 8.10.0

### operating system

Arch Linux

**Comment by bagder** [comment] 2024-09-15 21:33
Probably a duplicate of #14892. Fixed in master with #14895.

**Comment by lazka** [comment] 2024-09-15 21:47
Thanks, I'll try the patch tomorrow.

**Comment by lazka** [comment] 2024-09-16 09:06
I can confirm that backporting the relvant parts of 70d3a9b6aa69f and bef0acaf212a71c782e0b8 fixes things

**Closed** 2024-09-17 06:35 UTC
Labels: HTTP/2
