### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by leonrom** [curl/curl#803] opened 2016-05-12 13:13 UTC
### I did this
execue your example https.cpp (from https://curl.haxx.se/libcurl/c/example.html) with next changes:

//    curl_easy_setopt(curl, CURLOPT_URL, "https://example.com/");
    curl_easy_setopt(curl, CURLOPT_URL, "https://dev2.epcon.pl:64444/LFC_RTDB/");
    long verify = 0;
    curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, verify); // because _epcon.pl_ has bad sertificate
    curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, verify); // -"- 
    curl_easy_setopt(curl, CURLOPT_PORT, 64444); 

### I expected the following
get some values...
But I obtain message "**Segmentation fault**" !!!

With curl_easy_setopt(curl, CURLOPT_URL, "https://example.com/");  - all works fine

### curl/libcurl version

$ curl -V
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP 

### operating system
Linux Mint 17.2

Can't found any answer in Internet, sorry....
Thanks!

**Comment by bagder** [comment] 2016-05-12 14:23
I cannot reproduce this. The URL you used doesn't work for me though, I get a `Failed to connect to dev2.epcon.pl port 64444: Connection refused`

**Comment by leonrom** [comment] 2016-05-13 13:01
Many thanks! 
But https://dev2.epcon.pl is allowed only for my IP. Too pity :((
"because epcon.pl has bad certificate" - may be here is the  reason....

**Comment by bagder** [comment] 2016-05-13 13:24
We can't really tell what the reason is unless you give us much more data, since we can't repeat it ourselves. Like for example, you can provide a stack trace with a debugger or run it with valgrind and show us that that says.

But you could consider trying a more recent libcurl version first because chances are we already fixed the problem...

**Comment by leonrom** [comment] 2016-05-16 08:41
Many thanks for Your attempts to help me! 
I'd upgraded libcurl to last version - all was all same bad...
But!!!
But all starts work fine when I add third parameter - CURLOPT_SSLVERSION. All  curl_easy_setopt's now looks like thioses:

    curl_easy_setopt(curl, CURLOPT_URL, "https://dev2.epcon.pl:64443/LFC_RTDB/");
    curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, false); 
    curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);
    **curl_easy_setopt(curl, CURLOPT_SSLVERSION, CURL_SSLVERSION_SSLv3);**

Obviously, I don't now what it means, but it works for me,-  LIBCURL is the best!

Thanks and best wishes!

**Comment by bagder** [comment] 2016-05-16 12:50
Well, libcurl shouldn't segfault even when failing to negotiate the correct SSL version...

**Comment by jay** [comment] 2016-05-16 19:40
You are using the latest libcurl and still it segfaults? Can you reproduce using the curl tool? `curl --trace out https://dev2.epcon.pl:64443/LFC_RTDB`

You can build curl with `--enable-debug` , then get a backtrace. If it's a problem in libcurl we'd really like to know so we can fix it. Thanks

**Comment by leonrom** [comment] 2016-05-17 13:16
Sorry for now,- I'll try to execute your inquiry tomorrow (18.05)...

**Comment by leonrom** [comment] 2016-05-18 07:39
[config.log.txt](https://github.com/curl/curl/files/269845/config.log.txt)
[curl_test.cpp.txt](https://github.com/curl/curl/files/269843/curl_test.cpp.txt)
[work_with_libcurl.pdf](https://github.com/curl/curl/files/269844/work_with_libcurl.pdf)

Hi Jay
3 files in attachments - all what I can answer to you. Please, read pdf-file.
Second time did wrote request to epcon.pl - for now they does not give permissions to other users :((
Thanks

**Comment by leonrom** [comment] 2016-05-18 08:00
One moment, please! 
I intend to upgrade my Linux - and after that tell you, how it will work

**Comment by bagder** [comment] 2016-05-20 22:00
@leonrom we'd like to see the stack trace from the actual segfault. Like if you run it with a debugger and then enter 'where' or 'bt' when it crashes.

Without that, we'd need a way to reproduce it. One (or both) of those two.

**Comment by jay** [comment] 2016-05-22 04:40
> libcurl/7.35.0 GnuTLS/2.12.23 zlib/1.2.8 libidn/1.28 librtmp/2.3

Please in the future don't put the information in the PDF, there's no reason to do that. Just put it in the comments here. I checked in Mint 17 x64 and it appears that there's several of the packaged libcurl that vary by SSL backend. So likely you have installed libcurl3-gnutls libcurl4-gnutls-dev in addition to OpenSSL libcurl. Install the debugging symbols

sudo apt-get install libcurl3-dbg

Run your program using gdb like `gdb ./yourprog` and in gdb type `run` to start it. After it faults type `where` or `bt` and give us that output.

**Comment by leonrom** [comment] 2016-05-23 11:54
Many thanks !
I did as you wrote. 

Firstly I compile program (text is in file “curl_test.cpp.txt”). Next simple run it. Next run through dbg. Next insall libcurl3-dbg as Jay wish. And once more run through dbg (twice doing 'run'). Logs are in file “test 1.txt”

Second I read in the log “You might want to run 'apt-get -f install' to correct” and did so and repeat  tests logged in file “Test 2.txt”

Good luck!

[curl_test.cpp.txt](https://github.com/curl/curl/files/277394/curl_test.cpp.txt)
[test 1.txt](https://github.com/curl/curl/files/277393/test.1.txt)
[test 2.txt](https://github.com/curl/curl/files/277395/test.2.txt)

**Comment by bagder** [comment] 2016-05-23 12:12
As test2.txt shows, this is a crash in gnutls' `gnutls_x509_crt_import()` function.

I found [this report](http://lists.gnutls.org/pipermail/gnutls-devel/2014-April/006910.html) about exactly this same crash sent to the GnuTLS project back in 2014, and already then response said that [the GnuTLS version is too old and is unsupported](http://lists.gnutls.org/pipermail/gnutls-devel/2014-April/006922.html).

So, I'd urge you to do one or more of the following:

 - upgrade your gnutls
 - switch to a libcurl version built against another TLS backend
 - report this bug to your distro - assuming you use a still supported distro version as otherwise you could start with upgrading that

I don't see any action left for the curl project to do here.

**Closed** 2016-05-23 12:13 UTC
Labels: HTTP, needs-info-or-update, SSL/TLS

**Comment by leonrom** [comment] 2016-05-23 12:18
The third variant is "the  simplest" for me:) And much useful for others users of Mint/Ubuntu.
I'll do report with reference to your answer, OK?
Many thanks!

**Comment by bagder** [comment] 2016-05-23 12:23
Oh certainly please, do if you think that is helpful!

**Comment by leonrom** [comment] 2016-05-23 12:25
I think to get to LinuxMint distributor the reference to whole this correspondence:  https://github.com/curl/curl/issues/803
Unless you do not mind, of course

**Comment by bagder** [comment] 2016-05-23 12:26
We have a public bug tracker for a purpose. Everything is open, public and available to share with the world!
